Repository SigNoz/signoz, pull requests merged in 2022-12, with the labels that each got.

#1788 feat: search in tags is updated
  frontend/public/locales/en-GB/traceDetails.json
  frontend/public/locales/en/traceDetails.json
  frontend/src/container/TraceDetail/SelectedSpanDetails/Tags/Tag.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/Tags/index.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/Tags/styles.ts
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
Labels: trace-detail-page

#1802 feat: events is updated by adding the timestamp
  frontend/src/components/Graph/Plugin/Legend.ts
  frontend/src/container/NewDashboard/DashboardSettings/General/AddTags/index.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/Events/Event.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/Events/index.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/container/TraceDetail/utils.ts
  frontend/src/types/api/trace/getTraceItem.ts
Labels: trace-detail-page

#1810 chore(clickhouse): 🔧 include cluster.xml for distributed set up
  deploy/docker-swarm/clickhouse-setup/clickhouse-cluster.xml
  deploy/docker/clickhouse-setup/clickhouse-cluster.xml
  deploy/docker/clickhouse-setup/docker-compose-distributed.yaml
  pkg/query-service/tests/test-deploy/clickhouse-cluster.xml
Labels: chore

#1608 1374 dbcalls querybuilder
  frontend/src/container/MetricsApplication/MetricsPageQueries/DBCallQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/ExternalQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/ExternalQueries.tsx
  frontend/src/container/MetricsApplication/MetricsPageQueries/MetricsPageQueriesFactory.ts
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/index.tsx
Labels: application-page

#1775 [feat] ee/google auth implementation
  ee/query-service/app/api/api.go
  ee/query-service/app/api/auth.go
  ee/query-service/dao/interface.go
  ee/query-service/dao/sqlite/auth.go
  ee/query-service/dao/sqlite/domain.go
  ee/query-service/model/domain.go
  ee/query-service/model/errors.go
  ee/query-service/model/sso.go
  ee/query-service/sso/google.go
  ee/query-service/sso/model.go
  ee/query-service/sso/saml/request.go
  frontend/src/container/OrganizationSettings/AuthDomains/Create/Row/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/Create/Row/styles.ts
  frontend/src/container/OrganizationSettings/AuthDomains/Create/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/Create/styles.ts
  frontend/src/container/OrganizationSettings/AuthDomains/Edit/EditGoogleAuth.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/Edit/EditSAML.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/Edit/helpers.ts
  frontend/src/container/OrganizationSettings/AuthDomains/Edit/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/Switch/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/helpers.test.ts
  frontend/src/container/OrganizationSettings/AuthDomains/helpers.ts
  frontend/src/container/OrganizationSettings/AuthDomains/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/styles.ts
  frontend/src/container/OrganizationSettings/AuthDomains/utils.test.ts
  frontend/src/container/OrganizationSettings/AuthDomains/utils.ts
  frontend/src/types/api/SAML/deleteDomain.ts
  frontend/src/types/api/SAML/listDomain.ts
  frontend/src/types/api/SAML/postDomain.ts
  frontend/src/types/api/SAML/updateDomain.ts
  go.mod
  go.sum
Labels: request-more-info

#1824 fix: 🐛 log parsing issue
  deploy/docker/clickhouse-setup/docker-compose.yaml
  pkg/query-service/tests/test-deploy/docker-compose.yaml
Labels: bug, codeball:approved

#1821 fix: remove shared variable in TTL and async TTL queries
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug, request-more-info, codeball:needs-careful-review

#1838 fix: scroll is added in case of extra space
  frontend/src/modules/Servicemap/ServiceMap.tsx
Labels: ok-to-test

#1835 fix: add default value for materialized column in distributed logs table
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug, codeball:needs-careful-review

#1839 chore: introduce docker_multi_node_cluster and by default set to false
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
  pkg/query-service/tests/test-deploy/docker-compose.yaml
  pkg/query-service/tests/test-deploy/otel-collector-config.yaml
Labels: chore, request-more-info, codeball:approved

#1847 Revert "chore: use local table for innery query (#1815)
  pkg/query-service/app/metrics/query_builder.go
  pkg/query-service/constants/constants.go
Labels: chore

#1858 fix: do not show result of intermediate sub queries in external calls
  frontend/src/container/MetricsApplication/MetricsPageQueries/ExternalQueries.ts
Labels: bug, codeball:approved

#1896 chore: Updating stale edition message
  frontend/public/locales/en/translation.json
Labels: chore, request-more-info, codeball:approved

#1901 feat: event time is updated when root span is missing
  frontend/src/container/TraceDetail/SelectedSpanDetails/Events/Event.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/Events/EventStartTime.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/Events/RelativeStartTime.tsx
  frontend/src/container/TraceDetail/index.tsx
Labels: enhancement

#1897 fix: allow multiple spaces between a filter expression
  pkg/query-service/app/logs/parser.go
  pkg/query-service/app/logs/parser_test.go
Labels: bug, codeball:needs-careful-review

#1885 fix: proxy_read_timeout updated in nginx conf
  deploy/docker-swarm/common/nginx-config.conf
  deploy/docker/common/nginx-config.conf
  pkg/query-service/app/http_handler.go
Labels: bug, codeball:needs-careful-review

#1909 fix: removes password validations other than length
  pkg/query-service/auth/rbac.go
Labels: bug

#1904 fix(FE): remove unnecessary complexity from password check
  frontend/src/pages/SignUp/utils.ts
Labels: ok-to-test

#1910 fix: logs selection of filter is fixed
  frontend/src/components/Logs/AddToQueryHOC.tsx
Labels: bug, codeball:needs-careful-review

#1889 fix: logs issues
  frontend/src/container/LogControls/index.tsx
  frontend/src/container/LogsSearchFilter/index.tsx
  frontend/src/container/LogsSearchFilter/useSearchParser.ts
Labels: bug, codeball:needs-careful-review

#1863 fix docker-compose for swarm and related changes for distributed clickhouse
  deploy/docker-swarm/clickhouse-setup/data/clickhouse-2/.gitkeep
  deploy/docker-swarm/clickhouse-setup/data/clickhouse-3/.gitkeep
  deploy/docker-swarm/clickhouse-setup/data/zookeeper-1/.gitkeep
  deploy/docker-swarm/clickhouse-setup/data/zookeeper-2/.gitkeep
  deploy/docker-swarm/clickhouse-setup/data/zookeeper-3/.gitkeep
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/data/clickhouse-2/.gitkeep
  deploy/docker/clickhouse-setup/data/clickhouse-3/.gitkeep
  deploy/docker/clickhouse-setup/data/zookeeper-1/.gitkeep
  deploy/docker/clickhouse-setup/data/zookeeper-2/.gitkeep
  deploy/docker/clickhouse-setup/data/zookeeper-3/.gitkeep
Labels: bug, codeball:needs-careful-review

#1912 fix: flush logs before starting
  frontend/src/container/LogsSearchFilter/index.tsx
Labels: bug, codeball:approved

#1875 fix(query_range): invalid memory address or nil pointer dereference
  pkg/query-service/app/http_handler.go
Labels: bug, codeball:needs-careful-review

#1899 fix: live tail time out is updated
  frontend/src/api/logs/livetail.ts
Labels: bug, codeball:needs-careful-review

#1926 fix: per page is added in the dependancy
  frontend/src/container/LogsSearchFilter/index.tsx
Labels: bug, codeball:approved

#1900 fix: respect durationSort feature flag on getSpanFilters API
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/model/response.go
Labels: bug, enhancement, request-more-info, codeball:needs-careful-review

#1931 fix(version): use link instead of click handler
  frontend/src/container/Version/index.tsx
Labels: frontend

#1922 Chore/analytics
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/logs/parser.go
  pkg/query-service/app/server.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/response.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore, request-more-info, codeball:needs-careful-review

#1935 fix: error handling for index removal from selected field
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#1919 add exception page filters support
  frontend/src/container/AllError/constant.ts
  frontend/src/container/AllError/index.tsx
  frontend/src/container/AllError/utils.ts
  frontend/src/types/api/errors/getAll.ts
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/parser.go
  pkg/query-service/model/queryParams.go
Labels: codeball:needs-careful-review

#1936 fix: exception filter clear
  frontend/src/container/AllError/index.tsx
Labels: bug, request-more-info, codeball:approved

#1939 chore/analytics
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/server.go
  pkg/query-service/dao/sqlite/connection.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore, request-more-info, codeball:needs-careful-review

#1934 fix(logs): prevent duplicate logs dispatch
  frontend/src/container/LogsAggregate/index.tsx
  frontend/src/pages/Logs/index.tsx
Labels: frontend, logs

#1929 fix(sidebar): highlight active feature in nested route
  frontend/src/container/SideNav/index.tsx
Labels: frontend

#1945 fix: apply filters on count of exceptions
  frontend/src/container/AllError/index.tsx
  frontend/src/types/api/errors/getErrorCounts.ts
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/parser.go
Labels: bug, codeball:needs-careful-review

#1952 Removing Beta tag from Logs
  frontend/src/container/SideNav/menuItems.ts
Labels: request-more-info, codeball:approved
