Repository SigNoz/signoz, pull requests merged in 2022-10, with the labels that each got.

#1585 feat: add compression codec for materialized columns
  pkg/query-service/app/clickhouseReader/reader.go
Labels: enhancement

#1550 1363 externalcall querybuilder
  frontend/src/container/GridGraphLayout/Graph/FullView/index.metricsBuilder.tsx
  frontend/src/container/MetricsApplication/MetricsPageQueries/ExternalQueries.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/index.tsx
  frontend/src/lib/resourceAttributes.ts
  frontend/src/types/api/dashboard/getAll.ts
Labels: request-more-info

#1556 feat: SAML settings is updated
  frontend/public/locales/en-GB/organizationsettings.json
  frontend/public/locales/en/organizationsettings.json
  frontend/src/api/SAML/deleteDomain.ts
  frontend/src/api/SAML/listAllDomain.ts
  frontend/src/api/SAML/postDomain.ts
  frontend/src/api/SAML/updateDomain.ts
  frontend/src/api/features/getFeatureFlags.ts
  frontend/src/constants/featureKeys.ts
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/AddDomain/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/Create/Row/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/Create/Row/styles.ts
  frontend/src/container/OrganizationSettings/AuthDomains/Create/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/Create/styles.ts
  frontend/src/container/OrganizationSettings/AuthDomains/Edit/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/Switch/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/styles.ts
  frontend/src/container/OrganizationSettings/AuthDomains/utils.test.ts
  frontend/src/container/OrganizationSettings/AuthDomains/utils.ts
  frontend/src/container/OrganizationSettings/index.tsx
  frontend/src/container/Timeline/index.tsx
  frontend/src/hooks/useFeatureFlag.ts
  frontend/src/store/reducers/app.ts
  frontend/src/types/actions/app.ts
  frontend/src/types/api/SAML/deleteDomain.ts
  frontend/src/types/api/SAML/listDomain.ts
  frontend/src/types/api/SAML/postDomain.ts
  frontend/src/types/api/SAML/updateDomain.ts
  frontend/src/types/api/features/getFeaturesFlags.ts
  frontend/src/types/reducer/app.ts
Labels: request-more-info

#1620 chore: bump SigNoz/prometheus to v1.9.74
  go.mod
  go.sum
Labels: chore, request-more-info

#1635 1627 login: onsubmit is added
  frontend/src/container/Login/index.tsx
Labels: ok-to-test

#1662 feat: all trace now open in new tab
  frontend/src/container/Trace/TraceTable/index.tsx
Labels: ok-to-test
