Repository SigNoz/signoz, pull requests merged in 2022-04, with the labels that each got.

#922 feat(query-service): Add cold storage support in getTTL API
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/parser.go
  pkg/query-service/model/response.go
  pkg/query-service/tests/cold_storage_test.go
  pkg/query-service/tests/test-deploy/data/signoz.db
Labels: enhancement, query-service, ok-to-test, clickhouse

#908 chore: links are updated for all dashboard and promql
  frontend/src/container/ListOfDashboard/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/Query.tsx
Labels: enhancement, frontend, manual-testing-needed

#921 bug: logged in check is added in the useEffect
  frontend/src/container/AppLayout/index.tsx
Labels: bug, frontend

#934 feat: service map is handled when there is no service
  frontend/src/modules/Servicemap/ServiceMap.tsx
  frontend/src/store/actions/serviceMap.ts
  frontend/src/store/actions/types.ts
  frontend/src/store/reducers/serviceMap.ts
Labels: bug, frontend

#928 feat: Tag value suggestion
  frontend/src/api/trace/getTagValue.ts
  frontend/src/container/Trace/Search/AllTags/Tag/TagValue.tsx
  frontend/src/container/Trace/Search/AllTags/Tag/index.tsx
  frontend/src/container/Trace/Search/AllTags/Tag/styles.ts
  frontend/src/types/api/trace/getTagValue.ts
Labels: enhancement, frontend

#534 Fix(FE) : Ask for confirmation before deleting any dashboard from dashboard list
  frontend/src/container/ListOfDashboard/TableComponents/DeleteButton.tsx
Labels: ok-to-test

#935 feat: FE memory fixes and UX enhancements
  frontend/src/components/Graph/Plugin/EmptyGraph.ts
  frontend/src/components/Graph/hasData.ts
  frontend/src/components/Graph/index.tsx
  frontend/src/container/GridGraphLayout/Graph/FullView/EmptyGraph.tsx
  frontend/src/container/GridGraphLayout/Graph/FullView/index.tsx
  frontend/src/container/MetricsApplication/Tabs/Application.tsx
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
Labels: ok-to-test

#818 feat: editor config is added
  .editorconfig
Labels: enhancement, request-more-info

#846 bug: Trace filter page fixes
  frontend/src/container/Trace/Filters/Panel/PanelBody/Common/Checkbox.tsx
  frontend/src/container/Trace/Filters/Panel/PanelBody/CommonCheckBox/index.tsx
  frontend/src/container/Trace/Filters/Panel/PanelBody/Duration/index.tsx
  frontend/src/container/Trace/Filters/Panel/PanelHeading/index.tsx
  frontend/src/container/Trace/Filters/Panel/PanelHeading/styles.ts
  frontend/src/container/Trace/Search/AllTags/index.tsx
  frontend/src/container/Trace/Search/index.tsx
  frontend/src/container/Trace/TraceTable/index.tsx
  frontend/src/pages/Trace/index.tsx
  frontend/src/store/actions/trace/getInitialFilter.ts
  frontend/src/store/actions/trace/getInitialSpansAggregate.ts
  frontend/src/store/actions/trace/parseFilter/index.ts
  frontend/src/store/actions/trace/parseFilter/spanAggregateCurrentPage.ts
  frontend/src/store/actions/trace/parseFilter/spanAggregateOrder.ts
  frontend/src/store/actions/trace/selectTraceFilter.ts
  frontend/src/store/actions/trace/updateTagPanelVisiblity.ts
  frontend/src/store/actions/trace/util.ts
  frontend/src/store/reducers/trace.ts
  frontend/src/types/actions/trace.ts
  frontend/src/types/api/trace/getSpanAggregate.ts
  frontend/src/types/reducer/trace.ts
Labels: bug, frontend, trace-detail-page, manual-testing-needed

#945 fix: Fix jest
  frontend/babel.config.js
  frontend/jest.config.ts
  frontend/package.json
  frontend/src/components/NotFound/NotFound.test.tsx
  frontend/src/components/NotFound/__snapshots__/NotFound.test.tsx.snap
  frontend/src/container/TraceFlameGraph/__tests__/TraceFlameGraph.test.tsx
  frontend/src/container/TraceFlameGraph/__tests__/__snapshots__/TraceFlameGraph.test.tsx.snap
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: bug, frontend, test

#929 feat: dynamic step size for the data for graphs
  frontend/.eslintignore
  frontend/src/lib/__tests__/getStep.test.ts
  frontend/src/lib/getStep.ts
  frontend/src/modules/Usage/UsageExplorer.tsx
  frontend/src/pages/Trace/index.tsx
  frontend/src/store/actions/dashboard/getQueryResults.ts
Labels: request-more-info

#924 feat: version page is added
  frontend/public/locales/en/translation.json
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/api/user/getLatestVersion.ts
  frontend/src/constants/routes.ts
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/Header/Breadcrumbs/index.tsx
  frontend/src/container/SideNav/index.tsx
  frontend/src/container/SideNav/styles.ts
  frontend/src/container/Version/index.tsx
  frontend/src/container/Version/styles.ts
  frontend/src/pages/Status/index.tsx
  frontend/src/store/reducers/app.ts
  frontend/src/types/actions/app.ts
  frontend/src/types/api/user/getLatestVersion.ts
  frontend/src/types/reducer/app.ts
Labels: enhancement, frontend, manual-testing-needed

#965 Bug: Trace filter fix incoming from metrics page
  frontend/src/container/MetricsApplication/Tabs/Application.tsx
  frontend/src/container/MetricsApplication/TopEndpointsTable.tsx
  frontend/src/container/Trace/Filters/Panel/PanelBody/Common/Checkbox.tsx
  frontend/src/container/Trace/Filters/Panel/PanelBody/Duration/index.tsx
  frontend/src/container/Trace/Filters/Panel/PanelHeading/index.tsx
  frontend/src/container/Trace/Search/index.tsx
  frontend/src/container/Trace/TraceTable/index.tsx
  frontend/src/store/actions/trace/getInitialSpansAggregate.ts
  frontend/src/store/actions/trace/selectTraceFilter.ts
  frontend/src/store/actions/trace/util.ts
Labels: ok-to-test

#966 feat: onClick is added in the row
  frontend/src/container/Trace/TraceTable/index.tsx
Labels: ok-to-test

#969 chore(refactor): Signup app layout
  frontend/public/locales/en-GB/common.json
  frontend/public/locales/en-GB/translation.json
  frontend/public/locales/en/common.json
  frontend/src/container/AppLayout/index.tsx
  frontend/src/pages/SignUp/index.tsx
Labels: ok-to-test

#968 bug: unused import is removed and two unwanted eslint rule is removed
  frontend/.eslintrc.js
  frontend/src/container/Trace/Search/AllTags/Tag/TagValue.tsx
  frontend/src/container/Trace/TraceTable/index.tsx
  frontend/src/container/TriggeredAlerts/index.tsx
  frontend/src/wdyr.ts
  frontend/tsconfig.json
Labels: bug, enhancement, ok-to-test

#981 bug: wdyr is updated
  frontend/src/wdyr.ts
Labels: ok-to-test, request-more-info

#923 chore: generate uuid on server side
  pkg/query-service/app/dashboards/model.go
Labels: chore

#997 (bugfix): remove validation on post data id
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/http_handler.go
Labels: bug, request-more-info

#995 Use fetch fix
  frontend/src/container/GeneralSettings/GeneralSettings.tsx
  frontend/src/container/GeneralSettings/index.tsx
  frontend/src/container/ListAlertRules/index.tsx
  frontend/src/container/Trace/Search/AllTags/Tag/TagValue.tsx
  frontend/src/pages/ChannelsEdit/index.tsx
  frontend/src/pages/EditRules/index.tsx
Labels: ok-to-test

#1009 feat: ⚡️support resource attributes in query-service
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/interface.go
  pkg/query-service/app/parser.go
  pkg/query-service/model/queryParams.go
Labels: enhancement, query-service, backend, request-more-info

#1005 feat: dashboard search and filter
  frontend/.eslintignore
  frontend/package.json
  frontend/src/container/ListOfDashboard/SearchFilter/Dashboard.machine.tsx
  frontend/src/container/ListOfDashboard/SearchFilter/Dashboard.machine.typegen.ts
  frontend/src/container/ListOfDashboard/SearchFilter/QueryChip.tsx
  frontend/src/container/ListOfDashboard/SearchFilter/index.tsx
  frontend/src/container/ListOfDashboard/SearchFilter/styles.ts
  frontend/src/container/ListOfDashboard/SearchFilter/types.ts
  frontend/src/container/ListOfDashboard/SearchFilter/utils.ts
  frontend/src/container/ListOfDashboard/dashboardSearchAndFilter.ts
  frontend/src/container/ListOfDashboard/index.tsx
  frontend/yarn.lock
Labels: ok-to-test

#1012 (feat): metric attributes auto-complete APIs
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/interface.go
  pkg/query-service/app/parser/metrics.go
  pkg/query-service/app/server.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/model/response.go
Labels: enhancement, request-more-info

#987 feat: ✨ support gRPC status, method in trace table
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/model/response.go
Labels: enhancement, query-service, backend

#979 feat: Error exception
  frontend/public/locales/en-GB/errorDetails.json
  frontend/public/locales/en-GB/translation.json
  frontend/public/locales/en/errorDetails.json
  frontend/public/locales/en/translation.json
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/api/errors/getAll.ts
  frontend/src/api/errors/getByErrorTypeAndService.ts
  frontend/src/api/errors/getById.ts
  frontend/src/components/Editor/index.tsx
  frontend/src/constants/routes.ts
  frontend/src/container/AllError/index.tsx
  frontend/src/container/ErrorDetails/index.tsx
  frontend/src/container/ErrorDetails/styles.ts
  frontend/src/container/Header/Breadcrumbs/index.tsx
  frontend/src/container/SideNav/menuItems.ts
  frontend/src/pages/AllErrors/index.tsx
  frontend/src/pages/ErrorDetails/index.tsx
  frontend/src/types/api/errors/getAll.ts
  frontend/src/types/api/errors/getByErrorTypeAndService.ts
  frontend/src/types/api/errors/getById.ts
Labels: ok-to-test

#976 chore(BE): fix some typos
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/dao/sqlite/userPreferenceImpl.go
  sample-apps/hotrod/hotrod-delete.sh
  sample-apps/hotrod/hotrod-install.sh
Labels: request-more-info

#1019 bug: editor is updated in error details page
  frontend/src/components/Editor/index.tsx
  frontend/src/container/ErrorDetails/index.tsx
Labels: bug, frontend
