Repository SigNoz/signoz, pull requests merged in 2022-11, with the labels that each got.

#1647 fix README.zh-cn.md readable
  README.zh-cn.md
Labels: documentation

#1674 Feature flagging
  ee/query-service/license/manager.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/server.go
  pkg/query-service/constants/constants.go
  pkg/query-service/featureManager/manager.go
Labels: enhancement, codeball:needs-careful-review

#1700 feat: add ability to import Grafana dashboards
  frontend/public/locales/en-GB/dashboard.json
  frontend/public/locales/en/dashboard.json
  frontend/src/api/dashboard/create.ts
  frontend/src/container/ListOfDashboard/ImportJSON/index.tsx
  frontend/src/container/ListOfDashboard/index.tsx
  frontend/src/types/api/dashboard/create.ts
  go.mod
  go.sum
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/model/dashboards.go
Labels: enhancement, request-more-info, codeball:needs-careful-review

#1704 fix: parser updated to support escaped single quotes in search
  pkg/query-service/app/logs/parser.go
  pkg/query-service/app/logs/parser_test.go
Labels: bug

#1708 fix Logs contains issue
  frontend/src/container/Logs/index.tsx
  frontend/src/container/LogsSearchFilter/SearchFields/QueryBuilder/QueryBuilder.tsx
  frontend/src/container/LogsSearchFilter/SearchFields/QueryBuilder/utils.ts
  frontend/src/container/LogsSearchFilter/SearchFields/utils.ts
  frontend/src/container/LogsTable/index.tsx
Labels: ok-to-test

#1705 Feat: dynamic tooltip
  frontend/src/api/dynamicConfigs/getDynamicConfigs.ts
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/ConfigDropdown/Config/ErrorLink.tsx
  frontend/src/container/ConfigDropdown/Config/Link.tsx
  frontend/src/container/ConfigDropdown/Config/index.tsx
  frontend/src/container/ConfigDropdown/index.tsx
  frontend/src/container/Header/index.tsx
  frontend/src/store/reducers/app.ts
  frontend/src/types/actions/app.ts
  frontend/src/types/api/dynamicConfigs/getDynamicConfigs.ts
  frontend/src/types/reducer/app.ts
  pkg/query-service/app/http_handler.go
  pkg/query-service/constants/constants.go
  pkg/query-service/integrations/signozio/dynamic_config.go
  pkg/query-service/integrations/signozio/response.go
Labels: enhancement, ok-to-test, request-more-info, codeball:needs-careful-review

#1712 feat: refresh interval is added
  frontend/src/container/TopNav/AutoRefresh/config.ts
  frontend/src/container/TopNav/AutoRefresh/index.tsx
  frontend/src/container/TopNav/AutoRefresh/styles.ts
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
  frontend/src/container/TopNav/DateTimeSelection/styles.ts
Labels: request-more-info

#1715 fix: update trace URI when coming from metrics
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/TopOperationsTable.tsx
Labels: bug, request-more-info

#1718 fix: include inner panels support and map job,instance correctly
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/model/dashboards.go
Labels: bug, request-more-info, codeball:needs-careful-review

#1732 feat: onClick is updated in Trace Filter table
  frontend/src/container/Trace/TraceTable/index.tsx
Labels: enhancement, trace-filter-page

#1733 feat: value graph is updated
  frontend/src/components/ValueGraph/styles.ts
Labels: dashboards

#1731 feat: filter is added in exceptions page
  frontend/src/container/AllError/index.tsx
Labels: enhancement, exceptions, codeball:needs-careful-review

#1737 fix: getNanoTimestamp function and cache fix
  frontend/src/container/AllError/utils.ts
  frontend/src/container/TopNav/Breadcrumbs/index.tsx
  frontend/src/pages/ErrorDetails/index.tsx
Labels: bug, request-more-info

#1727 fix: Logs issues are fixed
  frontend/src/container/LogControls/styles.ts
  frontend/src/container/LogLiveTail/OptionIcon.tsx
  frontend/src/container/LogLiveTail/config.ts
  frontend/src/container/LogLiveTail/index.tsx
  frontend/src/container/LogLiveTail/styles.ts
  frontend/src/container/Logs/index.tsx
  frontend/src/container/LogsAggregate/index.tsx
  frontend/src/container/LogsFilters/index.tsx
  frontend/src/container/LogsSearchFilter/SearchFields/QueryBuilder/QueryBuilder.tsx
  frontend/src/container/LogsSearchFilter/SearchFields/QueryBuilder/styles.ts
  frontend/src/container/LogsSearchFilter/SearchFields/Suggestions.tsx
  frontend/src/container/LogsSearchFilter/SearchFields/index.tsx
  frontend/src/container/LogsSearchFilter/SearchFields/styles.tsx
  frontend/src/container/LogsSearchFilter/index.tsx
  frontend/src/container/LogsSearchFilter/styles.ts
  frontend/src/container/LogsSearchFilter/useSearchParser.ts
  frontend/src/container/LogsTable/index.tsx
  frontend/src/pages/Logs/index.tsx
  frontend/src/pages/Logs/styles.ts
  frontend/src/store/reducers/logs.ts
Labels: bug, request-more-info

#1655 fix: data is fetched while applying license
  frontend/src/container/Licenses/ApplyLicenseForm.tsx
  frontend/src/container/Licenses/ListLicenses.tsx
  frontend/src/container/Licenses/index.tsx
  frontend/src/container/Licenses/styles.ts
Labels: ok-to-test

#1744 display message updated
  frontend/public/locales/en-GB/licenses.json
  frontend/public/locales/en/licenses.json
Labels: request-more-info, codeball:approved

#1706 feat: [UI] clickhouse queries in alert builder
  frontend/public/locales/en-GB/alerts.json
  frontend/public/locales/en/alerts.json
  frontend/src/container/CreateAlertRule/SelectAlertType/index.tsx
  frontend/src/container/CreateAlertRule/SelectAlertType/styles.ts
  frontend/src/container/CreateAlertRule/defaults.ts
  frontend/src/container/CreateAlertRule/index.tsx
  frontend/src/container/EditRules/index.tsx
  frontend/src/container/FormAlertRules/ChQuerySection.tsx
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/FormAlertRules/ChartPreview/styles.ts
  frontend/src/container/FormAlertRules/QuerySection.tsx
  frontend/src/container/FormAlertRules/UserGuide/index.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/FormAlertRules/utils.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/query.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/types.ts
  frontend/src/pages/CreateAlert/index.tsx
  frontend/src/types/api/alerts/alertTypes.ts
  frontend/src/types/api/alerts/compositeQuery.ts
  frontend/src/types/api/alerts/create.ts
  frontend/src/types/api/alerts/def.ts
Labels: request-more-info

#1749 fix: trace table pagination
  frontend/src/container/Trace/TraceTable/index.tsx
  frontend/src/container/Trace/TraceTable/util.ts
Labels: bug, codeball:needs-careful-review

#1648 feat: introduce getSubTreeSpans function in clickhouse query builder & introduce smart trace detail algorithm
  ee/query-service/app/api/api.go
  ee/query-service/app/api/metrics.go
  ee/query-service/app/api/traces.go
  ee/query-service/app/db/metrics.go
  ee/query-service/app/db/reader.go
  ee/query-service/app/db/trace.go
  ee/query-service/app/server.go
  ee/query-service/constants/constants.go
  ee/query-service/model/plans.go
  ee/query-service/model/trace.go
  frontend/src/api/trace/getTraceItem.ts
  frontend/src/container/Trace/TraceTable/index.tsx
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/container/TraceDetail/utils.ts
  frontend/src/pages/TraceDetail/index.tsx
  frontend/src/types/api/trace/getTraceItem.ts
  go.mod
  go.sum
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/server.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/featureSet.go
  pkg/query-service/model/response.go
  pkg/query-service/model/response_easyjson.go
Labels: enhancement, request-more-info, codeball:needs-careful-review

#1763 fix: parser updated to differentiate between params and query string
  pkg/query-service/app/logs/parser.go
  pkg/query-service/app/logs/parser_test.go
Labels: bug, logs

#1759 fix[logs][FE]: live tail is fixed
  frontend/src/components/Graph/xAxisConfig.ts
  frontend/src/container/LogLiveTail/index.tsx
  frontend/src/container/LogsAggregate/index.tsx
  frontend/src/container/LogsSearchFilter/SearchFields/QueryBuilder/QueryBuilder.tsx
  frontend/src/container/LogsSearchFilter/SearchFields/styles.tsx
  frontend/src/container/LogsSearchFilter/index.tsx
  frontend/src/container/TopNav/AutoRefresh/index.tsx
  frontend/src/store/reducers/global.ts
  frontend/src/store/reducers/logs.ts
  frontend/src/types/actions/globalTime.ts
  frontend/src/types/reducer/globalTime.ts
Labels: request-more-info

#1768 fix: logs aggregate endpoint updated to differentiate between params and query string
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug, ok-to-test
