Repository SigNoz/signoz, pull requests merged in 2022-01, with the labels that each got.

#597 ci: using --wait helm install flag instead of waiting manually
  .github/workflows/e2e-k3s.yaml
Labels: ok-to-test

#600 ci: inject local images to k3d instead of publishing them
  .github/workflows/e2e-k3s.yaml
Labels: ok-to-test

#612 fix(frontend): pin mini-css-extract-plugin version to 2.4.5 to fix frontend builds
  frontend/package.json
Labels: bug

#610 ci: removing file filtering from some workflows
  .github/workflows/e2e-k3s.yaml
  .github/workflows/remove-label.yaml
Labels: ci/cd

#614 ci: filtering 'push' workflow to main and release branches
  .github/workflows/push.yaml
Labels: ci/cd

#615 ci: making some improvements to e2e-k3s workflow
  .github/workflows/e2e-k3s.yaml
Labels: ci/cd

#609 ci: adding a dummy push to check if the image push workflow works
  pkg/query-service/main.go
Labels: ci/cd

#628 chore: Add migration file path in otel collector config
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
Labels: chore, backend

#626 Feat/support error tab page
  deploy/docker/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-entrypoint-initdb.d/init-db.sql
  pkg/query-service/app/clickhouseReader/options.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/druidReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/interface.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/server.go
  pkg/query-service/config/dashboards/.gitkeep
  pkg/query-service/go.mod
  pkg/query-service/go.sum
  pkg/query-service/main.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/model/response.go
Labels: enhancement, backend, ok-to-test

#633 chore: add codeowners for automatic review request
  .github/CODEOWNERS
Labels: chore

#631 chore: update clean signoz command in install script
  deploy/install.sh
Labels: chore

#640 chore: Integrate behaviorbot for welcome messages on first pull request or issue
  .github/config.yaml
Labels: chore

#639 chore: ♻️ single manifest file for the hotrod
  sample-apps/hotrod/deployment.yaml
  sample-apps/hotrod/hotrod-load/locust-cm.yaml
  sample-apps/hotrod/hotrod-load/master-deployment.yaml
  sample-apps/hotrod/hotrod-load/scripts-cm.yaml
  sample-apps/hotrod/hotrod-load/service.yaml
  sample-apps/hotrod/hotrod-load/slave-deployment.yaml
  sample-apps/hotrod/hotrod.yaml
  sample-apps/hotrod/service.yaml
Labels: chore

#599 fix: local dev setup
  .gitignore
  CONTRIBUTING.md
  Makefile
  pkg/query-service/go.mod
Labels: backend

#643 ci(k3s): k3s CI workflow enhancements
  .github/workflows/e2e-k3s.yaml
Labels: enhancement, ci/cd

#630 change migration file path
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
Labels: backend

#590 BUG: refresh button is now fixed
  frontend/src/container/GridGraphLayout/Graph/FullView/index.tsx
Labels: bug, frontend, ok-to-test

#654 exclude filter support and fix for not sending null string in groupby for aggregates API
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/parser.go
  pkg/query-service/constants/constants.go
  pkg/query-service/go.mod
  pkg/query-service/go.sum
  pkg/query-service/model/queryParams.go
Labels: bug, enhancement, backend

#651 ci(k3s): attaching release name to resources in e2e-k3s
  .github/workflows/e2e-k3s.yaml
Labels: ci/cd

#652 chore: install script improvements
  CONTRIBUTING.md
  README.de-de.md
  README.md
  README.pt-br.md
  README.zh-cn.md
  deploy/install.sh
Labels: chore

#659 chore(log-option): set hotrod log options for hotrod app
  deploy/docker/clickhouse-setup/docker-compose.arm.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
Labels: chore

#661 ci(k3s): 💚 fix correct raw github URL for hotrod manifest
  .github/workflows/e2e-k3s.yaml
Labels: bug
