Repository SigNoz/signoz, pull requests merged in 2022-02, with the labels that each got.

#660 Fix 414 errors trace filter API
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/parser.go
  pkg/query-service/model/queryParams.go
Labels: bug, backend, ok-to-test

#673 chore: 🚚 rename config .yaml to yml for behaviorbot
  .github/config.yml
Labels: chore

#681 fix: exclude added for status field
  pkg/query-service/app/clickhouseReader/reader.go
Labels: request-more-info

#667 chore(helm-charts): 🚚 migrate helm charts to SigNoz/charts repository
  deploy/kubernetes/platform/Chart.lock
  deploy/kubernetes/platform/Chart.yaml
  deploy/kubernetes/platform/charts/alertmanager-0.5.0.tgz
  deploy/kubernetes/platform/charts/frontend-0.5.4.tgz
  deploy/kubernetes/platform/charts/query-service-0.5.4.tgz
  deploy/kubernetes/platform/charts/zookeeper-6.0.0.tgz
  deploy/kubernetes/platform/crds/clickhouse-operator-install.yaml
  deploy/kubernetes/platform/signoz-charts/alertmanager/.helmignore
  deploy/kubernetes/platform/signoz-charts/alertmanager/Chart.yaml
  deploy/kubernetes/platform/signoz-charts/alertmanager/ci/config-reload-values.yaml
  deploy/kubernetes/platform/signoz-charts/alertmanager/templates/NOTES.txt
  deploy/kubernetes/platform/signoz-charts/alertmanager/templates/_helpers.tpl
  deploy/kubernetes/platform/signoz-charts/alertmanager/templates/configmap.yaml
  deploy/kubernetes/platform/signoz-charts/alertmanager/templates/ingress.yaml
  deploy/kubernetes/platform/signoz-charts/alertmanager/templates/pdb.yaml
  deploy/kubernetes/platform/signoz-charts/alertmanager/templates/serviceaccount.yaml
  deploy/kubernetes/platform/signoz-charts/alertmanager/templates/services.yaml
  deploy/kubernetes/platform/signoz-charts/alertmanager/templates/statefulset.yaml
  deploy/kubernetes/platform/signoz-charts/alertmanager/unittests/__snapshot__/ingress_test.yaml.snap
  deploy/kubernetes/platform/signoz-charts/alertmanager/unittests/ingress_test.yaml
  deploy/kubernetes/platform/signoz-charts/alertmanager/values.yaml
  deploy/kubernetes/platform/signoz-charts/frontend/.helmignore
  deploy/kubernetes/platform/signoz-charts/frontend/Chart.yaml
  deploy/kubernetes/platform/signoz-charts/frontend/templates/NOTES.txt
  deploy/kubernetes/platform/signoz-charts/frontend/templates/_helpers.tpl
  deploy/kubernetes/platform/signoz-charts/frontend/templates/config.yaml
  deploy/kubernetes/platform/signoz-charts/frontend/templates/deployment.yaml
  deploy/kubernetes/platform/signoz-charts/frontend/templates/ingress.yaml
  deploy/kubernetes/platform/signoz-charts/frontend/templates/service.yaml
  deploy/kubernetes/platform/signoz-charts/frontend/templates/serviceaccount.yaml
  deploy/kubernetes/platform/signoz-charts/frontend/templates/tests/test-connection.yaml
  deploy/kubernetes/platform/signoz-charts/frontend/values.yaml
  deploy/kubernetes/platform/signoz-charts/query-service/.helmignore
  deploy/kubernetes/platform/signoz-charts/query-service/Chart.yaml
  deploy/kubernetes/platform/signoz-charts/query-service/templates/NOTES.txt
  deploy/kubernetes/platform/signoz-charts/query-service/templates/_helpers.tpl
  deploy/kubernetes/platform/signoz-charts/query-service/templates/ingress.yaml
  deploy/kubernetes/platform/signoz-charts/query-service/templates/prometheus-configmap.yaml
  deploy/kubernetes/platform/signoz-charts/query-service/templates/service.yaml
  deploy/kubernetes/platform/signoz-charts/query-service/templates/serviceaccount.yaml
  deploy/kubernetes/platform/signoz-charts/query-service/templates/statefulset.yaml
  deploy/kubernetes/platform/signoz-charts/query-service/templates/tests/test-connection.yaml
  deploy/kubernetes/platform/signoz-charts/query-service/values.yaml
  deploy/kubernetes/platform/templates/clickhouse-config.yaml
  deploy/kubernetes/platform/templates/clickhouse-instance.yaml
  deploy/kubernetes/platform/templates/clickhouse-operator/clusterrole.yaml
  deploy/kubernetes/platform/templates/clickhouse-operator/clusterrolebinding.yaml
  deploy/kubernetes/platform/templates/clickhouse-operator/configmap.yaml
  deploy/kubernetes/platform/templates/clickhouse-operator/deployment.yaml
  deploy/kubernetes/platform/templates/clickhouse-operator/service.yaml
  deploy/kubernetes/platform/templates/clickhouse-operator/serviceaccount.yaml
  deploy/kubernetes/platform/templates/otel-collector-metrics/otel-collector-metrics-config.yaml
  deploy/kubernetes/platform/templates/otel-collector-metrics/otel-collector-metrics-deployment.yaml
  deploy/kubernetes/platform/templates/otel-collector-metrics/otel-collector-metrics-service.yaml
  deploy/kubernetes/platform/templates/otel-collector/otel-collector-config.yaml
  deploy/kubernetes/platform/templates/otel-collector/otel-collector-deployment.yaml
  deploy/kubernetes/platform/templates/otel-collector/otel-collector-service.yaml
  deploy/kubernetes/platform/values.yaml
Labels: chore

#682 fix: exclude operation in trace APIs
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/constants/constants.go
Labels: bug, backend

#650 bug(wepack): optimisation config is updated
  frontend/webpack.config.prod.js
Labels: bug, frontend, ok-to-test

#692 bug(UI): frontend build is fixed
  frontend/src/constants/env.ts
Labels: request-more-info

#693 chore: Env fix
  frontend/src/constants/env.ts
Labels: request-more-info

#711 bug: dashboard graph is now fixed
  frontend/src/components/Graph/index.tsx
Labels: bug, frontend, ok-to-test, request-more-info

#712 bug: full view legend is now fixed
  frontend/src/container/GridGraphLayout/Graph/index.tsx
  frontend/src/container/GridGraphLayout/index.tsx
Labels: ok-to-test, request-more-info

#706 bug(FE): error state in the bar panel is added
  frontend/src/container/GridGraphLayout/Graph/index.tsx
  frontend/src/container/GridGraphLayout/Graph/styles.ts
Labels: bug, frontend

#701 feat: now webpack filename are hashed
  frontend/webpack.config.prod.js
Labels: bug, frontend, ok-to-test

#677 fix: Dashboard page does not call API on clicking on apply button
  frontend/src/container/NewWidget/index.tsx
Labels: ok-to-test

#723 chore: 🔧 update default jaeger endpoint in hotrod manifest
  sample-apps/hotrod/hotrod.yaml
Labels: chore

#727 chore: 🔧 update default jaeger endpoint in hotrod manifest
  sample-apps/hotrod/hotrod.yaml
Labels: chore

#743 WIP(FE): Trace detail page - Flame Graph + Timeline + Layout
  frontend/package.json
  frontend/src/container/AppLayout/styles.ts
  frontend/src/container/Timeline/index.tsx
  frontend/src/container/Timeline/style.module.css
  frontend/src/container/TraceFlameGraph/index.tsx
  frontend/src/container/TraceFlameGraph/styles.ts
  frontend/src/lib/getRandomColor.ts
  frontend/src/modules/Traces/SelectedSpanDetails.tsx
  frontend/src/modules/Traces/TraceGraph.tsx
  frontend/src/pages/Trace/styles.ts
  frontend/src/store/actions/traces.ts
  frontend/src/types/global.d.ts
  frontend/src/utils/getSpanTreeMetadata.ts
  frontend/src/utils/spanToTree.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
  frontend/webpack.config.prod.js
  frontend/yarn.lock
Labels: request-more-info

#742 WIP(FE): Trace details Chart is added
  frontend/src/container/GantChart/SpanLength/index.tsx
  frontend/src/container/GantChart/SpanLength/styles.ts
  frontend/src/container/GantChart/SpanName/index.tsx
  frontend/src/container/GantChart/SpanName/styles.ts
  frontend/src/container/GantChart/Trace/index.tsx
  frontend/src/container/GantChart/Trace/styles.ts
  frontend/src/container/GantChart/index.tsx
  frontend/src/container/GantChart/styles.ts
  frontend/src/container/GantChart/utils.ts
  frontend/src/container/SideNav/index.tsx
  frontend/src/container/SideNav/styles.ts
  frontend/src/container/Timeline/index.tsx
  frontend/src/container/TraceFlameGraph/index.tsx
  frontend/src/modules/Traces/SelectedSpanDetails.tsx
  frontend/src/modules/Traces/TraceGraph.tsx
  frontend/src/modules/Traces/utils.ts
  frontend/src/store/actions/traces.ts
  frontend/src/utils/spanToTree.ts
Labels: request-more-info

#759 Trace details
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/api/trace/getTraceItem.ts
  frontend/src/constants/routes.ts
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/styles.ts
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/container/TraceDetail/utils.ts
  frontend/src/modules/Traces/FilterStateDisplay.tsx
  frontend/src/modules/Traces/TraceGanttChart/TraceGanttChart.css
  frontend/src/modules/Traces/TraceGanttChart/TraceGanttChart.tsx
  frontend/src/modules/Traces/TraceGanttChart/TraceGanttChartHelpers.ts
  frontend/src/modules/Traces/TraceGanttChart/index.tsx
  frontend/src/modules/Traces/TraceGraph.css
  frontend/src/modules/Traces/TraceGraphColumn.tsx
  frontend/src/modules/Traces/TraceGraphDef.tsx
  frontend/src/modules/Traces/styles.ts
  frontend/src/pages/TraceDetail/index.tsx
  frontend/src/store/actions/index.ts
  frontend/src/store/actions/traceFilters.ts
  frontend/src/store/actions/traces.ts
  frontend/src/store/actions/types.ts
  frontend/src/store/reducers/index.ts
  frontend/src/store/reducers/traceFilters.ts
  frontend/src/store/reducers/traces.ts
  frontend/src/types/api/trace/getTraceItem.ts
Labels: request-more-info

#760 WIP(FE): trace detail styling changes
  frontend/src/container/GantChart/SpanLength/index.tsx
  frontend/src/container/GantChart/SpanLength/styles.ts
  frontend/src/container/GantChart/SpanName/index.tsx
  frontend/src/container/GantChart/Trace/index.tsx
  frontend/src/container/TraceDetail/TraceGraph.module.css
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/container/TraceFlameGraph/__tests__/TraceFlameGraph.test.tsx
  frontend/src/container/TraceFlameGraph/__tests__/__snapshots__/TraceFlameGraph.test.tsx.snap
  frontend/src/lib/getRandomColor.ts
  frontend/src/store/actions/traces.ts
  frontend/src/utils/getSpanTreeMetadata.ts
  frontend/src/utils/spanToTree.ts
Labels: request-more-info

#761 feat: trace detail page is updated
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/typings/react-app-env.ts
  frontend/src/typings/react-graph-vis.ts
Labels: request-more-info

#763 feat(TraceDetail): new trace detail page focus, hover, span select and much more...
  frontend/src/container/GantChart/Trace/index.tsx
  frontend/src/container/GantChart/Trace/styles.ts
  frontend/src/container/GantChart/index.tsx
  frontend/src/container/GantChart/utils.ts
  frontend/src/container/Timeline/index.tsx
  frontend/src/container/Trace/TraceTable/index.tsx
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/container/TraceFlameGraph/index.tsx
  frontend/src/container/TraceFlameGraph/styles.ts
  frontend/src/hooks/useUrlQuery.ts
  frontend/src/utils/toFixed.ts
Labels: request-more-info

#765 feat: Trace details
  frontend/src/container/GantChart/Trace/styles.ts
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/container/TraceDetail/utils.ts
Labels: request-more-info

#766 feat: new trace detail page styling changes
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/GantChart/Trace/index.tsx
  frontend/src/container/GantChart/styles.ts
  frontend/src/container/TraceDetail/SelectedSpanDetails/styles.ts
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/pages/TraceDetail/constants.ts
Labels: request-more-info

#756 feat: add hasError tag in searchTraces response
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/model/response.go
Labels: enhancement, backend, request-more-info

#755 bug: onClick cursor is added and display date is converted to minutes and 12hr format
  frontend/src/container/Trace/TraceTable/index.tsx
Labels: bug, frontend, trace-detail-page

#758 Add section for CPU architecture
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, request-more-info

#753 Removing Feedback FAB
  frontend/src/container/AppLayout/FeedBack/index.tsx
  frontend/src/container/AppLayout/FeedBack/styles.ts
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/SideNav/Slack.tsx
  frontend/src/container/SideNav/index.tsx
  frontend/src/container/SideNav/styles.ts
Labels: ok-to-test

#719 feat: slack community link is updated
  frontend/src/container/SideNav/Slack.tsx
  frontend/src/container/SideNav/index.tsx
  frontend/src/container/SideNav/styles.ts
Labels: enhancement, frontend

#750 fix: avoid panic by handling getOutboundIP() error
  pkg/query-service/telemetry/telemetry.go
Labels: bug

#689 feat: tag value suggestion API
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/druidReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/interface.go
  pkg/query-service/app/parser.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/model/response.go
Labels: enhancement, backend

#705 bug: useDebounce function is fixed
  frontend/src/hooks/useDebouncedFunction.ts
Labels: bug, frontend, ok-to-test

#733 test(Trace): Trace page test are added
  frontend/cypress/CustomFunctions/uncaughtExpection.ts
  frontend/cypress/fixtures/trace/initialAggregates.json
  frontend/cypress/fixtures/trace/initialSpanFilter.json
  frontend/cypress/fixtures/trace/initialSpans.json
  frontend/cypress/integration/trace/index.spec.ts
  frontend/src/container/Trace/Graph/index.tsx
  frontend/src/container/Trace/TraceGraphFilter/index.tsx
Labels: test, request-more-info

#731 bug: clear all now moves with selected filter rather than user selected filter
  frontend/src/container/Trace/Filters/Panel/PanelHeading/index.tsx
Labels: bug, frontend, trace-filter-page, ok-to-test, request-more-info, manual-testing-needed

#767 feat: new trace detail page styling changes
  frontend/src/container/GantChart/SpanLength/index.tsx
  frontend/src/container/GantChart/Trace/index.tsx
  frontend/src/container/GantChart/index.tsx
  frontend/src/container/GantChart/styles.ts
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/styles.ts
  frontend/src/container/TraceDetail/index.tsx
Labels: request-more-info

#567 fix: code vulnerability is fixed
  frontend/src/components/TextToolTip/index.tsx
Labels: bug, enhancement, frontend

#568 Feat(UI): toggle tabs is updated in the setting tab
  frontend/src/components/RouteTab/index.tsx
  frontend/src/container/EditAlertChannels/index.tsx
  frontend/src/container/SettingsWrapper/index.tsx
  frontend/src/pages/AlertChannelCreate/index.tsx
  frontend/src/pages/AllAlertChannels/index.tsx
  frontend/src/pages/Settings/index.tsx
  frontend/src/store/actions/app/index.ts
  frontend/src/store/actions/app/toggleSettingsTab.ts
  frontend/src/store/reducers/app.ts
  frontend/src/types/actions/app.ts
  frontend/src/types/reducer/app.ts
Labels: enhancement, frontend

#770 chore: Trace styles
  frontend/src/container/SideNav/index.tsx
  frontend/src/container/SideNav/styles.ts
  frontend/src/container/TraceDetail/SelectedSpanDetails/styles.ts
  frontend/src/container/TraceDetail/index.tsx
Labels: request-more-info

#768 feat: new trace detail page modify caret icon
  frontend/src/container/GantChart/Trace/index.tsx
Labels: request-more-info

#771 Revert "chore: Trace styles"
  frontend/src/container/SideNav/index.tsx
  frontend/src/container/SideNav/styles.ts
  frontend/src/container/TraceDetail/SelectedSpanDetails/styles.ts
  frontend/src/container/TraceDetail/index.tsx
Labels: chore

#772 bug: styles are updated
  frontend/src/container/SideNav/index.tsx
  frontend/src/container/SideNav/styles.ts
  frontend/src/container/TraceDetail/SelectedSpanDetails/styles.ts
  frontend/src/container/TraceDetail/index.tsx
Labels: request-more-info
