Repository SigNoz/signoz, pull requests merged in 2022-08, with the labels that each got.

#1450 chore: bump json-iterator version to v1.1.12
  pkg/query-service/go.mod
  pkg/query-service/go.sum
Labels: chore

#1458 feat: added user preferred channel filters in alerts
  frontend/public/locales/en-GB/alerts.json
  frontend/public/locales/en/alerts.json
  frontend/src/container/FormAlertRules/BasicInfo.tsx
  frontend/src/container/FormAlertRules/ChannelSelect/index.tsx
  frontend/src/container/FormAlertRules/ChannelSelect/styles.ts
  frontend/src/container/FormAlertRules/labels/styles.ts
  frontend/src/container/FormAlertRules/styles.ts
  frontend/src/types/api/alerts/def.ts
Labels: request-more-info

#1455 feat: show messaging/cron/browser services in listing page
  frontend/src/api/metrics/getTopLevelOperations.ts
  frontend/src/api/metrics/getTopOperations.ts
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/TopOperationsTable.tsx
  frontend/src/container/MetricsTable/index.tsx
  frontend/src/store/actions/metrics/getInitialData.ts
  frontend/src/store/reducers/metric.ts
  frontend/src/types/actions/metrics.ts
  frontend/src/types/api/metrics/getTopLevelOperations.ts
  frontend/src/types/api/metrics/getTopOperations.ts
  frontend/src/types/reducer/metrics.ts
  pkg/query-service/app/clickhouseReader/options.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/parser.go
  pkg/query-service/config/prometheus.yml
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/model/response.go
Labels: enhancement

#1467 feat: improve service map
  frontend/src/container/TopNav/DateTimeSelection/config.ts
  frontend/src/modules/Servicemap/ServiceMap.tsx
  frontend/src/modules/Servicemap/utils.ts
  frontend/src/store/actions/serviceMap.ts
  frontend/src/store/actions/types.ts
  frontend/src/store/reducers/serviceMap.ts
  pkg/query-service/app/clickhouseReader/options.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/response.go
Labels: enhancement, request-more-info

#1466 feat: use materialized view for usage explorer API
  pkg/query-service/app/clickhouseReader/options.go
  pkg/query-service/app/clickhouseReader/reader.go
Labels: enhancement, usage-explorer, request-more-info

#1474 fix: add defaultDependencyGraphTable to getTTL status check
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug, request-more-info

#1483 fix: interval should be 1d=24h (#1482)
  frontend/src/lib/getMinMax.ts
Labels: request-more-info

#1499 fix: escape and encode operations regex for overview details
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/lib/getMinMax.ts
Labels: bug, ok-to-test

#1501 feat: add more options in service map time dropdown
  frontend/src/container/TopNav/DateTimeSelection/config.ts
Labels: enhancement, request-more-info, codeball:approved

#1502 fix: escape and encode operations regex for overview details
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
Labels: bug, request-more-info

#1506 single otlp receiver
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
Labels: request-more-info

#1515 fix: live tail sse prod issue
  frontend/package.json
  frontend/src/api/logs/livetail.ts
  frontend/yarn.lock
Labels: request-more-info

#1517 feat: restrict timestamp from adding it to query
  frontend/src/components/Logs/LogItem/index.tsx
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogLiveTail/index.tsx
Labels: request-more-info

#1521 fix: do not show services without any data for select interval
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#1527 fix: eslint and tsc fixes for logs
  frontend/package.json
  frontend/src/api/logs/livetail.ts
  frontend/src/components/Logs/AddToQueryHOC.tsx
  frontend/src/components/Logs/CopyClipboardHOC.tsx
  frontend/src/components/Logs/LogItem/index.tsx
  frontend/src/container/GeneralSettings/GeneralSettings.tsx
  frontend/src/container/GeneralSettings/Retention.tsx
  frontend/src/container/LogControls/index.tsx
  frontend/src/container/LogDetailedView/ActionItem.tsx
  frontend/src/container/LogDetailedView/JsonView.tsx
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogDetailedView/index.tsx
  frontend/src/container/LogLiveTail/OptionIcon.tsx
  frontend/src/container/LogLiveTail/index.tsx
  frontend/src/container/Logs/index.tsx
  frontend/src/container/LogsAggregate/index.tsx
  frontend/src/container/LogsFilters/FieldItem.tsx
  frontend/src/container/LogsFilters/index.tsx
  frontend/src/container/LogsSearchFilter/SearchFields/FieldKey.tsx
  frontend/src/container/LogsSearchFilter/SearchFields/QueryBuilder/QueryBuilder.tsx
  frontend/src/container/LogsSearchFilter/SearchFields/Suggestions.tsx
  frontend/src/container/LogsSearchFilter/SearchFields/index.tsx
  frontend/src/container/LogsSearchFilter/SearchFields/utils.ts
  frontend/src/container/LogsSearchFilter/index.tsx
  frontend/src/container/LogsSearchFilter/useSearchParser.ts
  frontend/src/container/LogsTable/index.tsx
  frontend/src/container/LogsTable/styles.ts
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/TopNav/Breadcrumbs/index.tsx
  frontend/src/lib/__fixtures__/logql.ts
  frontend/src/lib/__tests__/logql/reverseParser.test.ts
  frontend/src/lib/__tests__/logql/splitter.test.ts
  frontend/src/lib/logql/parser.ts
  frontend/src/lib/logql/reverseParser.ts
  frontend/src/lib/logql/splitter.ts
  frontend/src/lib/logql/tokens.ts
  frontend/src/lib/logs/fieldSearch.ts
  frontend/src/lib/logs/flatLogData.ts
  frontend/src/lib/logs/generateFilterQuery.ts
  frontend/src/pages/Logs/index.tsx
  frontend/src/store/actions/logs/addToSelectedField.ts
  frontend/src/store/actions/logs/getFields.ts
  frontend/src/store/actions/logs/getLogs.ts
  frontend/src/store/actions/logs/getLogsAggregate.ts
  frontend/src/store/reducers/index.ts
  frontend/src/store/reducers/logs.ts
  frontend/src/types/actions/logs.ts
  frontend/src/types/api/logs/getLogs.ts
  frontend/src/types/api/logs/getLogsAggregate.ts
  frontend/src/types/reducer/logs.ts
  frontend/yarn.lock
Labels: request-more-info

#1534 chore: 🔧 enable logs capturing by default
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
  pkg/query-service/tests/test-deploy/docker-compose.yaml
  pkg/query-service/tests/test-deploy/otel-collector-config.yaml
Labels: chore
