Repository SigNoz/signoz, pull requests merged in 2022-06, with the labels that each got.

#1240 fix: dashboard is updated
  frontend/src/container/ListOfDashboard/index.tsx
Labels: ok-to-test

#1241 chore(alertmanager): 🔧 use query-service internal port
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose.arm.yaml
  pkg/query-service/tests/test-deploy/docker-compose.arm.yaml
  pkg/query-service/tests/test-deploy/docker-compose.yaml
Labels: chore

#1243 feat(FE): save dashboard with RBAC permissions
  frontend/src/container/GridGraphLayout/index.tsx
  frontend/src/utils/permission/index.ts
Labels: request-more-info

#1229 fix: incorrect 5xx rate calculation
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#1235 fix: using legacy_createStore instead of createStore as it seem it is depecreated
  frontend/src/store/index.ts
Labels: request-more-info

#1020 Add v2 query range metrics API
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/interface.go
  pkg/query-service/app/metrics/query_builder.go
  pkg/query-service/app/metrics/query_builder_test.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/parser/metrics.go
  pkg/query-service/app/parser_test.go
  pkg/query-service/constants/constants.go
  pkg/query-service/go.mod
  pkg/query-service/go.sum
  pkg/query-service/model/queryParams.go
  pkg/query-service/model/response.go
Labels: request-more-info

#1317 chore(deps): bump github.com/SigNoz/prometheus from v1.9.71 to v1.9.72
  pkg/query-service/go.mod
  pkg/query-service/go.sum
Labels: chore, request-more-info

#1319 fix: light mode issues are fixed
  frontend/src/index.html.ejs
Labels: frontend

#1320 fix: dashboard save layout
  frontend/src/container/GridGraphLayout/index.tsx
Labels: request-more-info

#1326 chore(install-script): 🗑️ remove arm YAML as already satisfied by existing YAML
  deploy/install.sh
Labels: chore, codeball:approved

#1331 chore: css for light mode is updated in sidebar
  frontend/src/container/SideNav/index.tsx
  frontend/src/container/SideNav/styles.ts
Labels: request-more-info

#1344 fix: decimal-precision is made undefined
  frontend/src/components/Graph/yAxisConfig.ts
Labels: request-more-info
