Repository SigNoz/signoz, pull requests merged in 2022-03, with the labels that each got.

#799 chore: trace changes are updated
  frontend/src/container/TraceDetail/SelectedSpanDetails/ErrorTag.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
  frontend/src/types/api/trace/getTraceItem.ts
  frontend/src/utils/spanToTree.ts
Labels: request-more-info

#795 feat: timeline normalisation
  frontend/src/container/GantChart/SpanLength/index.tsx
  frontend/src/container/GantChart/Trace/index.tsx
  frontend/src/container/GantChart/index.tsx
  frontend/src/container/Timeline/index.tsx
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/container/TraceDetail/utils.ts
  frontend/src/container/TraceFlameGraph/index.tsx
  frontend/src/utils/getSpanTreeMetadata.ts
Labels: request-more-info

#804 feat: new trace detail page themeing and interval loop fix
  frontend/src/container/GantChart/SpanLength/index.tsx
  frontend/src/container/GantChart/SpanLength/styles.ts
  frontend/src/container/GantChart/Trace/index.tsx
  frontend/src/container/GantChart/Trace/styles.ts
  frontend/src/container/Timeline/index.tsx
  frontend/src/container/Timeline/types.ts
  frontend/src/container/Timeline/utils.ts
  frontend/src/container/TraceDetail/SelectedSpanDetails/ErrorTag.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/styles.ts
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/container/TraceFlameGraph/index.tsx
  frontend/src/hooks/useThemeMode.ts
Labels: request-more-info

#805 chore: error tag is updated
  frontend/src/container/Timeline/index.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/ErrorTag.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/styles.ts
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/types/api/trace/getTraceItem.ts
  frontend/src/utils/spanToTree.ts
Labels: request-more-info

#806 chore: error tag is updated
  frontend/src/container/TraceDetail/SelectedSpanDetails/ErrorTag.tsx
Labels: request-more-info

#807 chore: console is removed
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
  frontend/src/utils/spanToTree.ts
Labels: request-more-info

#809 chore: expanded panel is updated
  frontend/src/container/TraceDetail/SelectedSpanDetails/ErrorTag.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
Labels: request-more-info

#810 chore: trace detail time dropdown is removed
  frontend/src/container/Header/index.tsx
Labels: request-more-info

#803 chore: update otel-collector to 0.43.0
  deploy/docker/clickhouse-setup/docker-compose.arm.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/otel-collector-metrics-config.yaml
Labels: chore, backend, request-more-info

#796 feat(backend): support custom events in span
  pkg/query-service/model/response.go
Labels: enhancement, request-more-info

#791 chore: typo is fixed
  frontend/src/container/Trace/TraceGraphFilter/config.ts
Labels: bug, frontend, request-more-info, manual-testing-needed

#800 chore: styles is updated for the not found button
  frontend/src/components/NotFound/styles.ts
Labels: bug, frontend, request-more-info

#718 bug(FE): sorting of date is fixed
  frontend/src/api/trace/getSpansAggregate.ts
  frontend/src/container/Trace/TraceTable/index.tsx
  frontend/src/store/actions/trace/getInitialSpansAggregate.ts
  frontend/src/types/api/trace/getSpanAggregate.ts
Labels: bug, frontend, ok-to-test

#741 bug: Trace search bug is resolved
  frontend/src/container/Trace/Search/AllTags/Tag/index.tsx
  frontend/src/container/Trace/Search/util.ts
Labels: bug, frontend, ok-to-test

#801 chore: ♿️ add hotrod template and install/delete scripts
  sample-apps/hotrod/README.md
  sample-apps/hotrod/hotrod-delete.sh
  sample-apps/hotrod/hotrod-install.sh
  sample-apps/hotrod/hotrod-template.yaml
Labels: chore

#817 feat(eslint): sonar js plugin for eslint is added
  frontend/.eslintrc.js
  frontend/package.json
  frontend/yarn.lock
Labels: enhancement, frontend, request-more-info, manual-testing-needed

#816 feat(eslint): eslint-plugin-react-hooks is added
  frontend/package.json
  frontend/yarn.lock
Labels: request-more-info

#824 bug(dashboard): useCallback is removed
  frontend/src/container/ListOfDashboard/TableComponents/Name.tsx
Labels: bug, frontend, p0, request-more-info

#823 fix: install deps node-gyp error
  frontend/package.json
  frontend/yarn.lock
Labels: bug, frontend

#819 fix: expand and unexpand on active span path
  frontend/src/container/GantChart/Trace/index.tsx
Labels: bug, frontend, request-more-info

#815 Fix: Update Documentation to configure front-end and run back-end.
  CONTRIBUTING.md
Labels: documentation

#829 Create repo-stats.yml
  .github/workflows/repo-stats.yml
Labels: request-more-info

#834 Remove gitpod support temporarily
  CONTRIBUTING.md
Labels: documentation

#831 ci: 💚 fix e2e-k3s workflow as needed with the chart changes
  .github/workflows/e2e-k3s.yaml
Labels: bug

#828 bug(FE): timeline interval is updated
  frontend/src/container/Timeline/index.tsx
Labels: request-more-info

#844 feat(FE): adaptive x axis time labels
  frontend/src/components/Graph/__tests__/xAxisConfig.test.ts
  frontend/src/components/Graph/index.tsx
  frontend/src/components/Graph/xAxisConfig.ts
  frontend/src/container/GridGraphLayout/Graph/FullView/index.tsx
  frontend/src/container/Trace/Graph/config.ts
  frontend/src/container/Trace/Graph/index.tsx
Labels: frontend

#860 feat: y-axis units for pre-defined and dashboard graphs
  frontend/package.json
  frontend/src/components/Graph/index.tsx
  frontend/src/components/Graph/yAxisConfig.ts
  frontend/src/container/GridGraphComponent/index.tsx
  frontend/src/container/GridGraphLayout/Graph/FullView/index.tsx
  frontend/src/container/GridGraphLayout/Graph/index.tsx
  frontend/src/container/GridGraphLayout/index.tsx
  frontend/src/container/MetricsApplication/Tabs/Application.tsx
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraph.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/index.tsx
  frontend/src/container/NewWidget/LeftContainer/index.tsx
  frontend/src/container/NewWidget/RightContainer/YAxisUnitSelector.tsx
  frontend/src/container/NewWidget/RightContainer/dataFormatCategories.ts
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/Trace/Graph/index.tsx
  frontend/src/container/Trace/TraceGraphFilter/config.ts
  frontend/src/container/Trace/TraceGraphFilter/index.tsx
  frontend/src/store/actions/dashboard/updateQuery.ts
  frontend/src/store/reducers/dashboard.ts
  frontend/src/store/reducers/trace.ts
  frontend/src/types/actions/dashboard.ts
  frontend/src/types/actions/trace.ts
  frontend/src/types/reducer/trace.ts
  frontend/yarn.lock
Labels: request-more-info

#845 fix(FE): trace detail events error handling
  frontend/src/container/Timeline/index.tsx
  frontend/src/container/Timeline/utils.ts
  frontend/src/container/TraceDetail/SelectedSpanDetails/ErrorTag.tsx
Labels: bug, frontend, trace-detail-page, manual-testing-needed

#861 chore: styled tab is updated to Tab from antd
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
Labels: request-more-info

#836 chore(install-script): ✨ remove mandatory sudo and digest improvement
  deploy/install.sh
Labels: chore

#851 feat(UI): monaco editor is updated
  frontend/package.json
  frontend/src/components/Editor/index.tsx
  frontend/src/components/Editor/styles.ts
  frontend/yarn.lock
Labels: bug, frontend, ui, ok-to-test, manual-testing-needed

#842 feat: onClick in new tab is added
  frontend/src/container/MetricsTable/index.tsx
  frontend/src/container/Trace/TraceTable/index.tsx
Labels: enhancement, frontend, ok-to-test, request-more-info, manual-testing-needed

#852 feat: timestamp is updated for selected start time
  frontend/src/container/Timeline/index.tsx
  frontend/src/container/TraceDetail/index.tsx
Labels: bug, frontend, trace-detail-page, manual-testing-needed

#840 fix: save layout bug is resolved
  frontend/src/container/GridGraphLayout/Graph/index.tsx
  frontend/src/container/GridGraphLayout/index.tsx
  frontend/src/container/GridGraphLayout/utils.ts
  frontend/src/container/NewDashboard/ComponentsSlider/index.tsx
  frontend/src/container/NewWidget/LeftContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/store/actions/dashboard/saveDashboard.ts
  frontend/src/types/api/dashboard/getAll.ts
Labels: bug, frontend, dashboards, ok-to-test, manual-testing-needed

#878 feat: data time, UI and graph label consistency across FE
  frontend/Dockerfile
  frontend/src/components/Graph/index.tsx
  frontend/src/constants/app.ts
  frontend/src/container/MetricsApplication/Tabs/Application.tsx
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/SideNav/index.tsx
  frontend/src/container/Trace/Graph/index.tsx
  frontend/src/container/Trace/Graph/styles.ts
  frontend/src/container/Trace/TraceGraphFilter/config.ts
  frontend/src/container/Trace/TraceGraphFilter/styles.ts
  frontend/src/container/Trace/TraceTable/index.tsx
  frontend/src/store/actions/app/index.ts
  frontend/src/store/actions/app/sideBarCollapse.ts
  frontend/src/store/reducers/app.ts
  frontend/src/types/actions/app.ts
  frontend/src/types/reducer/app.ts
Labels: bug, frontend, ok-to-test

#789 feat(FE): react-i18next is added
  frontend/package.json
  frontend/public/locales/en/translation.json
  frontend/src/ReactI18/index.tsx
  frontend/src/index.tsx
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/yarn.lock
Labels: enhancement, frontend, manual-testing-needed

#883 fix: trace filter groupby selection is breaking the FE
  frontend/src/container/Trace/Graph/config.ts
  frontend/src/container/Trace/Graph/index.tsx
  frontend/yarn.lock
Labels: request-more-info

#802 bug: useHistory is removed and dashboard loading component is removed
  frontend/src/container/GridGraphLayout/Graph/Bar/index.tsx
  frontend/src/container/GridGraphLayout/index.tsx
  frontend/src/container/Header/index.tsx
  frontend/src/container/ListOfDashboard/index.tsx
  frontend/src/container/MetricsApplication/TopEndpointsTable.tsx
  frontend/src/container/NewDashboard/ComponentsSlider/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/SideNav/index.tsx
  frontend/src/pages/Dashboard/index.tsx
  frontend/src/pages/DashboardWidget/index.tsx
  frontend/src/store/actions/dashboard/applySettingsToPanel.ts
Labels: bug, frontend, manual-testing-needed

#886 chore: 🔧 Add targets to clear docker standalone and swarm data
  Makefile
Labels: chore

#885 chore: 🔧 set dimensions_cache_size in signozspanmetrics processor
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker-swarm/clickhouse-setup/otel-collector-metrics-config.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/otel-collector-metrics-config.yaml
Labels: chore

#887 chore(makefile): 🔧 add down-x86 and down-arm targets
  Makefile
Labels: chore

#890 fix: top endpoints table overflow
  frontend/src/container/MetricsApplication/Tabs/Application.tsx
  frontend/src/container/MetricsApplication/Tabs/styles.ts
Labels: bug, frontend

#897 chore: onChange event is added
  frontend/src/components/Editor/index.tsx
Labels: ok-to-test

#900 chore(install-script): 🔧 amazon-linux improvements and fixes
  deploy/install.sh
Labels: bug, chore

#904 husky: pre-commit hook is added
  frontend/.husky/pre-commit
  frontend/package.json
  frontend/yarn.lock
Labels: enhancement, frontend

#914 chore: tsc fix are updated over frontend
  frontend/src/components/Graph/Plugin/Legend.ts
  frontend/src/components/NotFound/NotFound.test.tsx
  frontend/src/components/Styled/index.ts
  frontend/src/components/Styled/styles.ts
  frontend/src/container/AllAlertChannels/Delete.tsx
  frontend/src/container/GantChart/SpanLength/index.tsx
  frontend/src/container/GridGraphLayout/Graph/FullView/EmptyGraph.tsx
  frontend/src/container/GridGraphLayout/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/Query.tsx
  frontend/src/container/NewWidget/RightContainer/YAxisUnitSelector.tsx
  frontend/src/container/Timeline/index.tsx
  frontend/src/container/Timeline/utils.ts
  frontend/src/container/Trace/Graph/config.ts
  frontend/src/container/Trace/Graph/index.tsx
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/container/TraceFlameGraph/__tests__/TraceFlameGraph.test.tsx
  frontend/src/container/TraceFlameGraph/index.tsx
  frontend/src/hooks/useFetch.ts
  frontend/src/lib/__tests__/getStep.test.ts
  frontend/src/modules/Usage/UsageExplorer.tsx
  frontend/src/pages/DashboardWidget/index.tsx
  frontend/src/store/actions/dashboard/deleteDashboard.ts
  frontend/src/store/actions/dashboard/getDashboard.ts
  frontend/src/store/actions/dashboard/updateDashboardTitle.ts
  frontend/src/store/actions/trace/selectTraceFilter.ts
  frontend/src/typings/chartjs-adapter-date-fns.d.ts
  frontend/src/typings/d3-tip.d.ts
Labels: bug, frontend

#916 bug 🐛 : on click tag filter is now fixed
  frontend/src/container/Trace/Search/AllTags/index.tsx
Labels: bug, frontend, ok-to-test

#868 feat: Amol/webhook
  deploy/docker/clickhouse-setup/docker-compose.yaml
  frontend/src/api/channels/createWebhook.ts
  frontend/src/api/channels/editWebhook.ts
  frontend/src/components/Graph/index.tsx
  frontend/src/container/AllAlertChannels/Delete.tsx
  frontend/src/container/CreateAlertChannels/config.ts
  frontend/src/container/CreateAlertChannels/index.tsx
  frontend/src/container/EditAlertChannels/index.tsx
  frontend/src/container/FormAlertChannels/Settings/Webhook.tsx
  frontend/src/container/FormAlertChannels/index.tsx
  frontend/src/container/Timeline/index.tsx
  frontend/src/pages/AlertChannelCreate/index.tsx
  frontend/src/pages/ChannelsEdit/index.tsx
  frontend/src/types/api/channels/createWebhook.ts
  frontend/src/types/api/channels/editWebhook.ts
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/druidReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/interface.go
  pkg/query-service/constants/constants.go
  pkg/query-service/integrations/alertManager/manager.go
  pkg/query-service/integrations/alertManager/model.go
  pkg/query-service/model/response.go
Labels: enhancement, frontend, query-service, alerts

#906 chore: build.yml file is updated for more strict frontend checks
  .github/workflows/build.yaml
Labels: enhancement, frontend

#930 fix: dashboard table element overflow
  frontend/package.json
  frontend/src/container/ListOfDashboard/TableComponents/DeleteButton.tsx
  frontend/src/container/ListOfDashboard/TableComponents/Name.tsx
  frontend/src/container/ListOfDashboard/TableComponents/styles.ts
Labels: ok-to-test
