Repository SigNoz/signoz, pull requests merged in 2022-05, with the labels that each got.

#838 perf: Query-service Performance Improvements (traces)
  deploy/docker/clickhouse-setup/docker-compose.arm.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
  pkg/processors/flattener/Dockerfile
  pkg/processors/flattener/README.md
  pkg/processors/flattener/go.mod
  pkg/processors/flattener/go.sum
  pkg/processors/flattener/main.go
  pkg/query-service/Dockerfile
  pkg/query-service/app/clickhouseReader/options.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/clickhouseReader/reader_test.go
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/dashboards/provision.go
  pkg/query-service/app/druidReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/interface.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/parser/metrics.go
  pkg/query-service/app/server.go
  pkg/query-service/config/dashboards/.gitkeep
  pkg/query-service/constants/constants.go
  pkg/query-service/constants/constants_test.go
  pkg/query-service/dao/sqlite/connection.go
  pkg/query-service/druidQuery/mysql-client.go
  pkg/query-service/druidQuery/mysql-query.go
  pkg/query-service/druidQuery/query.go
  pkg/query-service/go.mod
  pkg/query-service/go.sum
  pkg/query-service/godruid/.gitignore
  pkg/query-service/godruid/LICENSE
  pkg/query-service/godruid/README.md
  pkg/query-service/godruid/aggregations.go
  pkg/query-service/godruid/client.go
  pkg/query-service/godruid/client_test.go
  pkg/query-service/godruid/dimension_spec.go
  pkg/query-service/godruid/filters.go
  pkg/query-service/godruid/granularities.go
  pkg/query-service/godruid/havings.go
  pkg/query-service/godruid/post_aggregations.go
  pkg/query-service/godruid/queries.go
  pkg/query-service/godruid/specs.go
  pkg/query-service/main.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/model/response.go
  pkg/query-service/telemetry/ignoredPaths.go
Labels: enhancement, chore

#1023 feat: some routes are removed from the date picker to display
  frontend/src/container/TopNav/index.tsx
Labels: enhancement

#1031 bugfix: missing destination name for DiskItem
  pkg/query-service/model/response.go
Labels: bug, request-more-info

#1038 fix: migrate service map APIs from GET to POST
  frontend/src/store/actions/serviceMap.ts
Labels: request-more-info

#1043 fix: trace detail layout issue
  frontend/src/container/AppLayout/styles.ts
Labels: request-more-info

#1045 fix: aggregate of avg and percentile
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/model/response.go
Labels: bug, request-more-info

#1046 fix: convert serviceMap API to POST
  pkg/query-service/app/http_handler.go
Labels: bug, request-more-info

#1056 fix: dashboard uuid issue
  frontend/src/container/NewDashboard/ComponentsSlider/index.tsx
Labels: request-more-info

#1057 fix: resource attribute error message
  frontend/src/container/MetricsApplication/ResourceAttributesFilter/index.tsx
Labels: request-more-info

#1058 chore: analtics changed after rbac
  pkg/query-service/app/http_handler.go
  pkg/query-service/dao/sqlite/connection.go
  pkg/query-service/dao/sqlite/rbac.go
  pkg/query-service/telemetry/telemetry.go
Labels: request-more-info

#1062 fix: handle empty data scenarios
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug, request-more-info

#1068 chore: change in error message on register
  pkg/query-service/auth/auth.go
  pkg/query-service/auth/utils.go
Labels: chore, request-more-info

#1070 chore: changed permission for edit and delete alert channels
  pkg/query-service/app/http_handler.go
Labels: chore, request-more-info

#1075 fix: fixed graph axis and tooltip
  frontend/src/components/Graph/index.tsx
  frontend/src/components/Graph/yAxisConfig.ts
  frontend/src/lib/getChartData.ts
Labels: request-more-info

#1080 fix(auth): Fix error message for forbidden requests
  pkg/query-service/app/http_handler.go
Labels: request-more-info

#1081 fix: y-axis time unit
  frontend/src/components/Graph/yAxisConfig.ts
Labels: request-more-info

#1086 fix: error and exception type error
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/model/response.go
Labels: bug, request-more-info

#1089 fix: lagInFrame and leadInFrame nullable
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#1088 fix: y-axis generic time unit conversion
  frontend/src/components/Graph/yAxisConfig.ts
Labels: request-more-info

#1092 fix: fix typo and return empty struct instead of null
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/model/response.go
Labels: bug, request-more-info

#1098 fix: exceptionStacktrace typo
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug, request-more-info

#1104 chore(nginx-config): 🔧 add cache control headers for UI
  deploy/docker-swarm/common/nginx-config.conf
  deploy/docker/common/nginx-config.conf
Labels: chore

#1136 chore: 🔧 improve nginx cache configuration
  deploy/docker-swarm/common/nginx-config.conf
  deploy/docker/common/nginx-config.conf
Labels: chore

#1138 fix: service map label readable
  frontend/src/modules/Servicemap/ServiceMap.tsx
Labels: ok-to-test

#1127 fix: removed unnecessary file
  frontend/src/container/IsRouteAccessible/index.tsx
Labels: ok-to-test

#1163 feat: tooltip is added and max width is configured in the left panel to show text ellipsis
  frontend/src/container/Trace/Filters/Panel/PanelBody/Common/Checkbox.tsx
  frontend/src/container/Trace/Filters/Panel/PanelBody/Common/styles.ts
  frontend/src/pages/Trace/styles.ts
Labels: ok-to-test

#1111 Add section outlining ideal workflow for significant features/changes
  CONTRIBUTING.md
Labels: enhancement, request-more-info

#1176 feat: added status code of api calls
  pkg/query-service/app/server.go
Labels: request-more-info

#1151 feat: signoz gh-bot integration
  .github/workflows/create-issue-on-pr-merge.yml
Labels: enhancement, request-more-info, update docs on SigNoz.io

#1180 chore(docker): 🚀 Update Dockerfile and .dockerignore files
  deploy/docker/common/nginx-config.conf
  frontend/.dockerignore
  frontend/Dockerfile
Labels: chore

#1181 fix(husky): 🚨 integrate is-ci and webpack-cli version bump
  frontend/Dockerfile
  frontend/package.json
  frontend/yarn.lock
Labels: bug

#1184 fix: ts typings and remove cypress types
  frontend/package.json
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/container/Header/index.tsx
  frontend/src/container/Header/styles.ts
  frontend/src/container/TopNav/CustomDateTimeModal/index.tsx
  frontend/src/container/TriggeredAlerts/FilteredTable/index.tsx
  frontend/src/index.tsx
  frontend/src/lib/__tests__/getStep.test.ts
  frontend/src/modules/Servicemap/index.ts
  frontend/src/modules/Servicemap/index.tsx
  frontend/src/modules/Usage/UsageExplorerDef.tsx
  frontend/src/modules/Usage/index.tsx
  frontend/src/typings/window.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: request-more-info

#1196 setTTL apis async
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/interface.go
  pkg/query-service/app/parser.go
  pkg/query-service/constants/constants.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/model/response.go
Labels: request-more-info

#1204 feat: TTL FE enhancements
  frontend/public/locales/en-GB/generalSettings.json
  frontend/public/locales/en-GB/translation.json
  frontend/public/locales/en/generalSettings.json
  frontend/public/locales/en/translation.json
  frontend/src/container/GeneralSettings/GeneralSettings.tsx
  frontend/src/container/GeneralSettings/StatusMessage.tsx
  frontend/src/container/GeneralSettings/index.tsx
Labels: ok-to-test

#1173 fix: 🐛 convert TTL APIs to async #902
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/interface.go
  pkg/query-service/app/parser.go
  pkg/query-service/constants/constants.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/model/response.go
  pkg/query-service/tests/auth_test.go
  pkg/query-service/tests/cold_storage_test.go
Labels: bug

#1206 Fix/set tt lapis
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/constants/constants.go
  pkg/query-service/tests/auth_test.go
  pkg/query-service/tests/cold_storage_test.go
Labels: bug, request-more-info

#1201 chore: TTL and S3 config related changes
  frontend/public/locales/en-GB/generalSettings.json
  frontend/public/locales/en-GB/translation.json
  frontend/public/locales/en/generalSettings.json
  frontend/public/locales/en/translation.json
  frontend/src/api/settings/getRetention.ts
  frontend/src/container/GeneralSettings/GeneralSettings.tsx
  frontend/src/container/GeneralSettings/StatusMessage.tsx
  frontend/src/container/GeneralSettings/index.tsx
  frontend/src/container/GeneralSettings/styles.ts
  frontend/src/container/GeneralSettings/utils.ts
  frontend/src/types/api/settings/common.ts
  frontend/src/types/api/settings/getRetention.ts
  frontend/src/types/api/settings/setRetention.ts
  frontend/src/types/common/index.ts
Labels: chore, request-more-info

#1207 feat: dashboard layout is updated from widgets
  frontend/src/container/GridGraphLayout/index.tsx
Labels: ok-to-test

#1208 fix: trace table is fixed
  frontend/src/container/Trace/TraceTable/index.tsx
Labels: ok-to-test

#1209 fix: layout is updated
  frontend/src/container/GridGraphLayout/index.tsx
Labels: ok-to-test
