Repository SigNoz/signoz, pull requests merged in 2022-09, with the labels that each got.

#1557 feat: add support for dashboard variables
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metrics/query_builder.go
  pkg/query-service/app/parser/metrics.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/model/response.go
Labels: enhancement, request-more-info, codeball:needs-careful-review

#1558 fix: reuse the query engine and storage for alerts pqlEngine
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/server.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/pqlEngine/engine.go
Labels: bug, codeball:needs-careful-review

#1551 feat: introduce search trace ID component
  frontend/src/container/Trace/Filters/Panel/PanelBody/SearchTraceID/index.tsx
  frontend/src/container/Trace/Filters/Panel/PanelBody/index.tsx
  frontend/src/container/Trace/Filters/index.tsx
  frontend/src/store/reducers/trace.ts
  frontend/src/types/reducer/trace.ts
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/constants/constants.go
  pkg/query-service/model/queryParams.go
Labels: enhancement, codeball:needs-careful-review

#1562 feat: webpack chunk name is updated
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/pages/GettingStarted/DocCard.tsx
  frontend/src/pages/GettingStarted/Section.tsx
  frontend/src/pages/GettingStarted/index.tsx
  frontend/src/pages/GettingStarted/renderConfig.tsx
  frontend/src/pages/GettingStarted/styles.ts
  frontend/src/pages/GettingStarted/types.ts
  frontend/src/pages/GettingStarted/utmParams.ts
Labels: ok-to-test

#1567 chore: Introduce enterprise edition license
  CONTRIBUTING.md
  LICENSE
  README.de-de.md
  README.md
  README.pt-br.md
  README.zh-cn.md
  ee/LICENSE
  pkg/query-service/version/version.go
Labels: chore, codeball:needs-careful-review

#1588 1587 update readme signoz vs jaeger
  README.md
Labels: request-more-info

#1586 fix: filter items can be empty
  pkg/query-service/app/parser/metrics.go
Labels: bug, codeball:needs-careful-review

#1582 feat: #1524 refresh button bug fix
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
Labels: ok-to-test, request-more-info
