Repository SigNoz/signoz, pull requests merged in 2022-07, with the labels that each got.

#1348 fix: add request/response interceptors for ApiV2Instance
  frontend/src/api/index.ts
Labels: bug, codeball:approved

#1356 chore: added metrics for analytics
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/telemetry/ignoredPaths.go
  pkg/query-service/telemetry/telemetry.go
Labels: request-more-info

#1355 chore: bump SigNoz/prometheus to 1.9.73
  pkg/query-service/go.mod
  pkg/query-service/go.sum
Labels: chore, request-more-info

#1354 docs: add list of project maintainers
  README.md
Labels: request-more-info

#1328 feat: add support for not regex
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metrics/query_builder.go
  pkg/query-service/app/metrics/query_builder_test.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/utils/time.go
Labels: enhancement

#1365 feat: missing spans handling by returning a forest of trees
  frontend/src/container/GantChart/Trace/index.tsx
  frontend/src/container/GantChart/Trace/styles.ts
  frontend/src/container/GantChart/index.tsx
  frontend/src/container/GantChart/styles.ts
  frontend/src/container/GantChart/utils.ts
  frontend/src/container/TraceDetail/Missingtrace.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/container/TraceDetail/styles.ts
  frontend/src/container/TraceDetail/utils.ts
  frontend/src/container/TraceFlameGraph/__tests__/TraceFlameGraph.test.tsx
  frontend/src/container/TraceFlameGraph/index.tsx
  frontend/src/types/api/trace/getTraceItem.ts
  frontend/src/utils/getSpanTreeMetadata.ts
  frontend/src/utils/spanToTree.ts
Labels: request-more-info

#1287 perf: exception page optimization
  pkg/query-service/app/clickhouseReader/options.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/parser.go
  pkg/query-service/constants/constants.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/model/response.go
Labels: performance

#1368 chore: tests for span to trace tree with missing spans support
  frontend/src/container/GantChart/SpanName/index.tsx
  frontend/src/container/GantChart/SpanName/styles.ts
  frontend/src/container/GantChart/Trace/styles.ts
  frontend/src/container/TraceDetail/Missingtrace.tsx
  frontend/src/types/api/trace/getTraceItem.ts
  frontend/src/utils/__tests__/__snapshots__/spanToTree.test.ts.snap
  frontend/src/utils/__tests__/spanToTree.test.ts
  frontend/src/utils/fixtures/TraceData.ts
  frontend/src/utils/spanToTree.ts
Labels: request-more-info

#1391 fix: error rate as a percentage of total requests
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#1366 feat: make SigNoz rpc aware
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/Trace/Filters/index.tsx
  frontend/src/container/Trace/TraceGraphFilter/config.ts
  frontend/src/store/reducers/trace.ts
  frontend/src/types/reducer/trace.ts
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/constants/constants.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/model/response.go
Labels: enhancement

#1346 Alerts backend with metrics
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/constants/constants.go
  pkg/query-service/integrations/alertManager/manager.go
  pkg/query-service/integrations/alertManager/model.go
  pkg/query-service/integrations/alertManager/notifier.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/main.go
  pkg/query-service/pqlEngine/engine.go
  pkg/query-service/rules/alerting.go
  pkg/query-service/rules/apiParams.go
  pkg/query-service/rules/db.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/manager_test.go
  pkg/query-service/rules/promRule.go
  pkg/query-service/rules/promRuleTask.go
  pkg/query-service/rules/queriers.go
  pkg/query-service/rules/resultTypes.go
  pkg/query-service/rules/rule.go
  pkg/query-service/rules/ruleTask.go
  pkg/query-service/rules/task.go
  pkg/query-service/rules/templates.go
  pkg/query-service/rules/thresholdRule.go
  pkg/query-service/utils/labels/interface.go
  pkg/query-service/utils/labels/labels.go
  pkg/query-service/utils/times/time.go
  pkg/query-service/utils/timestamp/timestamp.go
  pkg/query-service/utils/value/value.go
Labels: request-more-info

#1399 fix: update the error rate percentage text and scale
  frontend/src/container/MetricsTable/index.tsx
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug, request-more-info

#1400 fix: remove requirement of exceptionType and serviceName from errorDetail page URL
  frontend/src/container/AllError/index.tsx
  frontend/src/container/ErrorDetails/index.tsx
  frontend/src/pages/ErrorDetails/index.tsx
Labels: bug, request-more-info

#1360 Create dependency-review.yml
  .github/workflows/dependency-review.yml
Labels: request-more-info, codeball:approved

#1402 update contributing.md file
  CONTRIBUTING.md
Labels: request-more-info

#1426 docs: added documentation for query-service local setup
  CONTRIBUTING.md
  pkg/query-service/README.md
Labels: request-more-info

#1414 Used Prepared Statements for GetChannel in clickhousereader
  pkg/query-service/app/clickhouseReader/reader.go
Labels: request-more-info
