Repository SigNoz/signoz, pull requests merged in 2023-06, with the labels that each got.

#2778 feat: add share url
  frontend/src/constants/queryBuilder.ts
  frontend/src/constants/queryBuilderQueryNames.ts
  frontend/src/container/CreateAlertRule/defaults.ts
  frontend/src/container/CreateAlertRule/index.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/FormAlertRules/utils.ts
  frontend/src/container/GridGraphLayout/WidgetHeader/index.tsx
  frontend/src/container/ListAlertRules/ListAlert.tsx
  frontend/src/container/NewDashboard/ComponentsSlider/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/hooks/queryBuilder/useShareBuilderUrl.ts
  frontend/src/lib/newQueryBuilder/queryBuilderMappers/mapQueryDataFromApi.ts
  frontend/src/lib/newQueryBuilder/transformQueryBuilderDataModel.ts
  frontend/src/lib/replaceIncorrectObjectFields.ts
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/store/actions/dashboard/getDashboard.ts
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
  frontend/src/types/common/queryBuilder.ts
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2805 fix: limit default value is updated
  frontend/src/container/QueryBuilder/filters/LimitFilter/LimitFilter.tsx
Labels: bug

#2818 fix: sorter is updated for sorting in alerts page
  frontend/src/container/ListAlertRules/ListAlert.tsx
Labels: bug, frontend, alerts

#2816 fix: alerts page threshold only number is allowed
  frontend/src/container/FormAlertRules/RuleOptions.tsx
  frontend/src/container/FormAlertRules/styles.ts
Labels: bug

#2810 fix: org name is fixed
  frontend/src/api/user/signup.ts
  frontend/src/pages/SignUp/SignUp.tsx
Labels: bug, request-more-info

#2821 fix: add legend property to Queries
  pkg/query-service/model/v3/v3.go
Labels: bug, request-more-info

#2155 feat: add cache interface and implementation for redis,inmemory
  Makefile
  go.mod
  go.sum
  pkg/query-service/cache/cache.go
  pkg/query-service/cache/cache_test.go
  pkg/query-service/cache/inmemory/cache.go
  pkg/query-service/cache/inmemory/cache_test.go
  pkg/query-service/cache/inmemory/options.go
  pkg/query-service/cache/redis/options.go
  pkg/query-service/cache/redis/redis.go
  pkg/query-service/cache/redis/redis_test.go
  pkg/query-service/cache/status/status.go
  pkg/query-service/cache/status/status_test.go
  pkg/query-service/cache/testdata/cache.yaml
Labels: enhancement, codeball:needs-careful-review

#2804 fix: query builder edit mode doesn't send correct payload
  frontend/src/api/queryBuilder/getAggregateAttribute.ts
  frontend/src/api/queryBuilder/getAttributeKeys.ts
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
  frontend/src/hooks/queryBuilder/useQueryOperations.ts
  frontend/src/hooks/queryBuilder/useTag.ts
  frontend/src/lib/createIdFromObjectFields.ts
  frontend/src/lib/newQueryBuilder/getFilterObjectValue.ts
  frontend/src/providers/QueryBuilder.tsx
Labels: bug, request-more-info, codeball:needs-careful-review

#2773 feat: add measurement value formatter
  Makefile
  go.mod
  go.sum
  pkg/query-service/formatter/bool.go
  pkg/query-service/formatter/data.go
  pkg/query-service/formatter/data_rate.go
  pkg/query-service/formatter/data_test.go
  pkg/query-service/formatter/formatter.go
  pkg/query-service/formatter/none.go
  pkg/query-service/formatter/percent.go
  pkg/query-service/formatter/scale.go
  pkg/query-service/formatter/throughput.go
  pkg/query-service/formatter/throughput_test.go
  pkg/query-service/formatter/time.go
  pkg/query-service/formatter/time_test.go
Labels: enhancement, codeball:needs-careful-review

#2841 feat: added option to download logs in csv & excel format
  frontend/package.json
  frontend/src/container/LogControls/index.tsx
  frontend/src/container/LogControls/styles.ts
  frontend/yarn.lock
Labels: frontend, logs

#2866 fix: if condition corrected in aggreagte attribute static fields
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#2867 fix: layout issue on alert page
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/FormAlertRules/index.tsx
Labels: frontend, alerts, ui

#2832 feat: add the options menu
  frontend/public/locales/en-GB/trace.json
  frontend/public/locales/en/trace.json
  frontend/src/container/OptionsMenu/AddColumnField/index.tsx
  frontend/src/container/OptionsMenu/AddColumnField/styles.ts
  frontend/src/container/OptionsMenu/FormatField/index.tsx
  frontend/src/container/OptionsMenu/FormatField/styles.ts
  frontend/src/container/OptionsMenu/MaxLinesField/index.tsx
  frontend/src/container/OptionsMenu/MaxLinesField/styles.ts
  frontend/src/container/OptionsMenu/index.tsx
  frontend/src/container/OptionsMenu/styles.ts
Labels: request-more-info

#2782 feat: add querier interface and initial implementation
  Makefile
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/v3/v3.go
Labels: enhancement, codeball:needs-careful-review

#2875 FE: invite form is reset when closed
  frontend/src/container/OrganizationSettings/PendingInvitesContainer/index.tsx
Labels: codeball:needs-careful-review

#2881 fix: raw query is updated to query
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/CreateAlertRule/defaults.ts
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/query.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/types.ts
  frontend/src/lib/newQueryBuilder/queryBuilderMappers/mapQueryDataFromApi.ts
  frontend/src/store/actions/dashboard/getQueryResults.ts
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
Labels: bug, request-more-info

#2791 Fixes for pagination in listview
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/logs/v3/enrich_query.go
  pkg/query-service/app/logs/v3/enrich_query_test.go
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/constants/constants.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/v3/v3.go
Labels: bug, request-more-info, codeball:needs-careful-review

#2884 Release/v0.20.2
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/CreateAlertRule/defaults.ts
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/query.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/types.ts
  frontend/src/lib/newQueryBuilder/queryBuilderMappers/mapQueryDataFromApi.ts
  frontend/src/store/actions/dashboard/getQueryResults.ts
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/model/v3/v3.go
Labels: request-more-info, codeball:needs-careful-review

#2882 fix: sorting logic is updated
  frontend/src/container/MetricsApplication/TopOperationsTable.tsx
  frontend/src/container/MetricsApplication/utils.ts
Labels: bug, codeball:needs-careful-review

#2873 fix: support for exists and nexists in existing parser
  pkg/query-service/app/logs/parser.go
  pkg/query-service/app/logs/parser_test.go
Labels: bug, codeball:needs-careful-review

#2894 fix: query key is updated
  frontend/src/container/FormAlertRules/QuerySection.tsx
  frontend/src/hooks/queryBuilder/useGetQueryRange.ts
Labels: bug, frontend, alerts

#2898 chore: updated frontend contributions guidelines
  frontend/CONTRIBUTIONS.md
Labels: request-more-info

#2896 fix: alert name required message & button disabled
  frontend/src/container/FormAlertRules/BasicInfo.tsx
  frontend/src/container/FormAlertRules/index.tsx
Labels: bug, frontend, alerts, customer issues

#2850 feat: added the contribution guidelines
  frontend/CONTRIBUTIONS.md
Labels: enhancement, codeball:needs-careful-review

#2908 fix: handling of 404 in dashboard is updated
  frontend/src/api/ErrorResponseHandler.ts
  frontend/src/pages/NewDashboard/index.tsx
  frontend/src/types/common/index.ts
Labels: frontend, codeball:approved

#2915 fix: clone panel permission is updated
  frontend/src/container/GridGraphLayout/WidgetHeader/index.tsx
Labels: bug, codeball:approved

#2906 fix: new widget condition is fixed and handling of undefined is done
  frontend/src/container/GridGraphLayout/Graph/index.tsx
  frontend/src/container/GridGraphLayout/index.tsx
Labels: bug, request-more-info, codeball:needs-careful-review

#2919 fix: updated redirect link for try signoz cloud button
  frontend/src/container/Header/index.tsx
Labels: request-more-info

#2910 fix: updating dashboard variables is not allowed for viewer role
  frontend/src/container/NewDashboard/DashboardVariablesSelection/index.tsx
  frontend/src/types/api/dashboard/variables/query.ts
Labels: bug, codeball:needs-careful-review

#2905 Feat/logs explorer
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/constants/queryBuilder.ts
  frontend/src/constants/queryBuilderQueryNames.ts
  frontend/src/constants/routes.ts
  frontend/src/constants/theme.ts
  frontend/src/container/CreateAlertRule/defaults.ts
  frontend/src/container/CreateAlertRule/index.tsx
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/GridGraphLayout/utils.ts
  frontend/src/container/LogsExplorerChart/LogsExplorerChart.styled.ts
  frontend/src/container/LogsExplorerChart/LogsExplorerChart.tsx
  frontend/src/container/LogsExplorerChart/index.ts
  frontend/src/container/LogsExplorerViews/LogsExplorerViews.styled.ts
  frontend/src/container/LogsExplorerViews/LogsExplorerViews.tsx
  frontend/src/container/LogsExplorerViews/index.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/MetricsPageQueriesFactory.ts
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/NewDashboard/ComponentsSlider/index.tsx
  frontend/src/container/QueryBuilder/QueryBuilder.interfaces.ts
  frontend/src/container/QueryBuilder/QueryBuilder.styled.ts
  frontend/src/container/QueryBuilder/QueryBuilder.tsx
  frontend/src/container/QueryBuilder/filters/HavingFilter/__tests__/utils.test.tsx
  frontend/src/container/SideNav/menuItems.tsx
  frontend/src/container/TopNav/Breadcrumbs/index.tsx
  frontend/src/hooks/queryBuilder/useGetCompositeQueryParam.ts
  frontend/src/hooks/queryBuilder/useGetPanelTypesQueryParam.ts
  frontend/src/hooks/queryBuilder/useGetQueryRange.ts
  frontend/src/hooks/queryBuilder/useQueryOperations.ts
  frontend/src/hooks/queryBuilder/useShareBuilderUrl.ts
  frontend/src/lib/explorer/getExplorerChartData.ts
  frontend/src/lib/newQueryBuilder/getOperatorsBySourceAndPanelType.ts
  frontend/src/lib/newQueryBuilder/queryBuilderMappers/mapQueryDataFromApi.ts
  frontend/src/lib/newQueryBuilder/transformQueryBuilderDataModel.ts
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/pages/LogsExplorer/styles.ts
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/store/actions/dashboard/getDashboard.ts
  frontend/src/store/actions/dashboard/getQueryResults.ts
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
  frontend/src/types/common/queryBuilder.ts
  frontend/src/utils/permission/index.ts
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2924 fix: query operator
  frontend/src/hooks/queryBuilder/useQueryOperations.ts
Labels: bug, request-more-info

#2923 ci(gh-workflows): 👷 bump up versions and minor updates
  .github/workflows/build.yaml
  .github/workflows/codeql.yaml
  .github/workflows/create-issue-on-pr-merge.yml
  .github/workflows/e2e-k3s.yaml
  .github/workflows/playwright.yaml
  .github/workflows/pr_verify_linked_issue.yml
  .github/workflows/push.yaml
  .github/workflows/release-drafter.yml
  .github/workflows/remove-label.yaml
  .github/workflows/sonar.yml
Labels: ok-to-test, testing-deploy

#2928 chore: try signoz cloud link is updated
  frontend/src/container/Header/index.tsx
Labels: chore, codeball:approved

#2843 feat: add the Trace Explorer page with Query Builder
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/constants/routes.ts
  frontend/src/container/Controls/config.ts
  frontend/src/container/Controls/index.tsx
  frontend/src/container/Controls/styles.ts
  frontend/src/container/LogControls/config.ts
  frontend/src/container/LogControls/index.tsx
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/QueryBuilder/QueryBuilder.tsx
  frontend/src/container/QueryBuilder/components/AdditionalFiltersToggler/AdditionalFiltersToggler.tsx
  frontend/src/container/QueryBuilder/components/FilterLabel/FilterLabel.tsx
  frontend/src/container/SideNav/config.ts
  frontend/src/container/SideNav/menuItems.tsx
  frontend/src/container/TopNav/Breadcrumbs/index.tsx
  frontend/src/container/TracesExplorer/Controls/index.tsx
  frontend/src/container/TracesExplorer/Controls/styles.ts
  frontend/src/container/TracesExplorer/QuerySection/index.tsx
  frontend/src/container/TracesExplorer/QuerySection/styles.ts
  frontend/src/container/TracesExplorer/TimeSeriesView/index.tsx
  frontend/src/container/TracesExplorer/TimeSeriesView/styles.ts
  frontend/src/lib/dashbaordVariables/getDashboardVariables.ts
  frontend/src/lib/getStartEndRangeTime.ts
  frontend/src/pages/TracesExplorer/constants.ts
  frontend/src/pages/TracesExplorer/index.tsx
  frontend/src/pages/TracesExplorer/styles.ts
  frontend/src/pages/TracesExplorer/utils.tsx
  frontend/src/store/actions/dashboard/getQueryResults.ts
  frontend/src/utils/permission/index.ts
Labels: request-more-info

#2925 feat: add the export panel
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/container/ExportPanel/ExportPanel.tsx
  frontend/src/container/ExportPanel/config.ts
  frontend/src/container/ExportPanel/index.tsx
  frontend/src/container/ExportPanel/styles.ts
  frontend/src/container/ExportPanel/utils.ts
Labels: request-more-info

#2790 feat: add zap otel logger support
  ee/query-service/app/server.go
  ee/query-service/main.go
  go.mod
  go.sum
  pkg/query-service/app/server.go
  pkg/query-service/constants/constants.go
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2944 fix: white screen issue is fixed when cloning the panel
  frontend/src/hooks/queryBuilder/useGetWidgetQueryRange.ts
Labels: bug, frontend, codeball:approved

#2930 fix: feature flag is added when we are switching the tab
  frontend/src/container/FormAlertRules/QuerySection.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
Labels: bug, enhancement, codeball:needs-careful-review

#2946 fix: save rules/dashboard is now enabled for metrics irrespective of feature flag disabled
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/NewWidget/index.tsx
Labels: bug, enhancement, request-more-info, codeball:needs-careful-review

#2959 fix: filters for explorer page
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
Labels: bug, request-more-info, codeball:approved

#2936 feat: Add Generic Table View in the logs explorer
  frontend/src/components/ResizeTable/ResizeTable.tsx
  frontend/src/container/LogsExplorerTable/LogsExplorerTable.tsx
  frontend/src/container/LogsExplorerTable/index.ts
  frontend/src/container/LogsExplorerViews/LogsExplorerViews.tsx
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
  frontend/src/container/QueryTable/QueryTable.intefaces.ts
  frontend/src/container/QueryTable/QueryTable.tsx
  frontend/src/container/QueryTable/index.ts
  frontend/src/lib/newQueryBuilder/convertNewDataToOld.ts
  frontend/src/lib/query/createTableColumnsFromQuery.ts
  frontend/src/lib/toCapitalize.ts
  frontend/src/types/api/metrics/getQueryRange.ts
  frontend/src/types/api/widgets/getQuery.ts
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2962 Fix/query builder updating
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/LogsExplorerChart/index.ts
  frontend/src/container/LogsExplorerChart/index.tsx
  frontend/src/container/LogsExplorerList/LogsExplorerList.interfaces.ts
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsExplorerTable/LogsExplorerTable.interfaces.ts
  frontend/src/container/LogsExplorerTable/LogsExplorerTable.tsx
  frontend/src/container/LogsExplorerTable/index.ts
  frontend/src/container/LogsExplorerTable/index.tsx
  frontend/src/container/LogsExplorerViews/LogsExplorerViews.tsx
  frontend/src/container/LogsExplorerViews/index.ts
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/QueryBuilder/QueryBuilder.tsx
  frontend/src/hooks/queryBuilder/useGetWidgetQueryRange.ts
  frontend/src/hooks/queryBuilder/useQueryOperations.ts
  frontend/src/hooks/queryBuilder/useShareBuilderUrl.ts
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/pages/TracesExplorer/index.tsx
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/types/api/widgets/getQuery.ts
  frontend/src/types/common/queryBuilder.ts
Labels: bug, request-more-info, codeball:needs-careful-review

#2943 feat: add the url pagination & update options menu
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/Controls/index.tsx
  frontend/src/container/LogControls/index.tsx
  frontend/src/container/NewDashboard/ComponentsSlider/menuItems.ts
  frontend/src/container/OptionsMenu/AddColumnField/index.tsx
  frontend/src/container/OptionsMenu/AddColumnField/styles.ts
  frontend/src/container/OptionsMenu/FormatField/index.tsx
  frontend/src/container/OptionsMenu/MaxLinesField/index.tsx
  frontend/src/container/OptionsMenu/constants.ts
  frontend/src/container/OptionsMenu/index.tsx
  frontend/src/container/OptionsMenu/types.ts
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
  frontend/src/container/OptionsMenu/utils.ts
  frontend/src/container/TracesExplorer/Controls/index.tsx
  frontend/src/container/TracesExplorer/QuerySection/index.tsx
  frontend/src/hooks/queryPagination/config.ts
  frontend/src/hooks/queryPagination/index.ts
  frontend/src/hooks/queryPagination/types.ts
  frontend/src/hooks/queryPagination/useQueryPagination.ts
  frontend/src/hooks/queryPagination/utils.ts
  frontend/src/hooks/useUrlQueryData.ts
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/pages/TracesExplorer/constants.ts
  frontend/src/pages/TracesExplorer/index.tsx
  frontend/src/pages/TracesExplorer/utils.tsx
  frontend/src/types/actions/logs.ts
  frontend/src/types/common/queryBuilder.ts
  frontend/src/types/reducer/logs.ts
Labels: request-more-info

#2903 fix: step size is made dynamic
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/GridGraphLayout/Graph/FullView/index.metricsBuilder.tsx
  frontend/src/container/GridGraphLayout/Graph/index.tsx
  frontend/src/container/MetricsApplication/MetricsPageQueries/MetricsPageQueriesFactory.ts
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/QueryBuilder/filters/AggregateEveryFilter/index.tsx
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
  frontend/src/hooks/queryBuilder/useGetWidgetQueryRange.ts
  frontend/src/hooks/queryBuilder/useStepInterval.ts
  frontend/src/lib/__tests__/getStep.test.ts
  frontend/src/lib/dashbaordVariables/getDashboardVariables.ts
  frontend/src/lib/getStep.test.ts
  frontend/src/lib/getStep.ts
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/store/actions/dashboard/getQueryResults.ts
  frontend/src/store/actions/dashboard/saveDashboard.ts
  frontend/src/types/common/queryBuilder.ts
Labels: bug, codeball:needs-careful-review

#2982 feat: added time series tab in logs explorer
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
  frontend/src/container/TimeSeriesView/index.tsx
  frontend/src/container/TimeSeriesView/styles.ts
  frontend/src/pages/TracesExplorer/utils.tsx
Labels: enhancement

#2975 feat: add custom orderBy
  frontend/src/container/QueryBuilder/filters/OrderByFilter/OrderByFilter.tsx
  frontend/src/container/QueryBuilder/filters/OrderByFilter/config.ts
  frontend/src/container/QueryBuilder/filters/OrderByFilter/utils.ts
Labels: enhancement, request-more-info

#2978 feat: ability to configure noisy top level operations to discard
  ee/query-service/app/api/api.go
  ee/query-service/app/server.go
  ee/query-service/main.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/main.go
  pkg/query-service/model/config.go
Labels: enhancement, request-more-info

#3000 fix: trace column attributes
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#2995 feat: create alerts is updated from trace explorer
  frontend/src/container/CreateAlertRule/SelectAlertType/config.ts
  frontend/src/container/CreateAlertRule/SelectAlertType/index.tsx
  frontend/src/container/CreateAlertRule/SelectAlertType/types.ts
  frontend/src/container/CreateAlertRule/config.ts
  frontend/src/container/CreateAlertRule/index.tsx
  frontend/src/container/ExportPanel/index.tsx
  frontend/src/container/GridGraphLayout/WidgetHeader/index.tsx
  frontend/src/container/ListAlertRules/ListAlert.tsx
  frontend/src/container/NewDashboard/ComponentsSlider/index.tsx
  frontend/src/hooks/queryBuilder/useGetCompositeQueryParam.ts
  frontend/src/pages/TracesExplorer/index.tsx
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/store/actions/dashboard/saveDashboard.ts
Labels: enhancement
