Repository SigNoz/signoz, pull requests merged in 2023-11, with the labels that each got.

#3857 Fix: log pipelines: only one of the trace parser fields is required
  frontend/public/locales/en/pipeline.json
  frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/FormFields/NameInput.tsx
  frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/config.ts
  frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/utils.tsx
Labels: bug

#3862 fix: ignore reload identity calls
  pkg/query-service/telemetry/telemetry.go
Labels: bug

#3847 feat: widget full view fixes
  frontend/src/container/GridCardLayout/GridCard/FullView/GraphManager.styles.scss
  frontend/src/container/GridCardLayout/GridCard/FullView/GraphManager.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/WidgetFullView.styles.scss
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/styles.scss
Labels: bug, enhancement, request-more-info

#3848 [Feat]: Download as CSV and Execl and Search option for key-operation table
  frontend/src/container/Download/Download.styles.scss
  frontend/src/container/Download/Download.tsx
  frontend/src/container/Download/Download.types.ts
  frontend/src/container/LogControls/index.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/TopOperation.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/TopOperationMetrics.tsx
  frontend/src/container/MetricsApplication/TopOperationsTable.styles.scss
  frontend/src/container/MetricsApplication/TopOperationsTable.tsx
  frontend/src/container/MetricsApplication/constant.ts
  frontend/src/container/MetricsApplication/utils.ts
  frontend/src/container/QueryTable/QueryTable.intefaces.ts
  frontend/src/container/QueryTable/QueryTable.styles.scss
  frontend/src/container/QueryTable/QueryTable.tsx
  frontend/src/container/QueryTable/utils.ts
Labels: enhancement

#3861 fix: support for dash in path name for json query
  pkg/query-service/app/logs/v3/json_filter.go
  pkg/query-service/app/logs/v3/json_filter_test.go
  pkg/query-service/app/logs/v3/query_builder_test.go
Labels: bug

#3755 [Fix]: the loading state based on the time interval
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ServiceOverview.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/TopLevelOperations.tsx
Labels: request-more-info

#3830 fix: empty widget is handled
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/ListOfDashboard/ImportJSON/index.tsx
  frontend/src/lib/dashboard/getUpdatedLayout.ts
  frontend/src/providers/Dashboard/Dashboard.tsx
Labels: bug, frontend

#3879 [Fix]: full view chart label and checkbox issue
  frontend/src/container/GridCardLayout/GridCard/FullView/TableRender/GetLabel.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/TableRender/GraphManagerColumns.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
Labels: bug

#3875 [Fix]: the height issue for resizable tables
  frontend/src/container/QueryTable/QueryTable.styles.scss
Labels: bug, request-more-info

#3856 chore: dashboard locking ee query-service
  ee/query-service/app/api/api.go
  ee/query-service/app/api/dashboard.go
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/parser/metrics.go
  pkg/query-service/dao/sqlite/apdex.go
Labels: chore, request-more-info

#3890 chore: dashboard locking ee query-service
  ee/query-service/app/api/dashboard.go
Labels: chore

#3880 feat: dashboard lock feature
  frontend/public/locales/en/dashboard.json
  frontend/src/api/dashboard/lockDashboard.ts
  frontend/src/api/dashboard/unlockDashboard.ts
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/GridCardLayout/config.ts
  frontend/src/container/GridCardLayout/styles.ts
  frontend/src/container/ListOfDashboard/TableComponents/DeleteButton.tsx
  frontend/src/container/ListOfDashboard/TableComponents/Name.tsx
  frontend/src/container/ListOfDashboard/index.tsx
  frontend/src/container/NewDashboard/ComponentsSlider/styles.ts
  frontend/src/container/NewDashboard/DashboardDescription/DashboardName/index.tsx
  frontend/src/container/NewDashboard/DashboardDescription/SettingsDrawer.tsx
  frontend/src/container/NewDashboard/DashboardDescription/ShareModal.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/container/NewDashboard/DashboardDescription/styles.ts
  frontend/src/container/NewDashboard/DashboardDescription/util.ts
  frontend/src/container/NewDashboard/index.tsx
  frontend/src/providers/Dashboard/Dashboard.tsx
  frontend/src/providers/Dashboard/types.ts
  frontend/src/types/api/dashboard/getAll.ts
  frontend/src/types/roles.ts
  frontend/src/utils/permission/index.ts
Labels: enhancement

#3894 fix: Tooltip values is now fixed
  frontend/src/lib/uPlotLib/getUplotChartData.ts
Labels: bug, request-more-info

#3895 feat: resize graph based on the y axis max label length
  frontend/src/lib/uPlotLib/getUplotChartData.ts
Labels: enhancement, request-more-info

#3749 fix: page break in Services overview tab
  frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/ApDexMetrics.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/ApDexMetricsApplication.tsx
  frontend/src/types/api/metrics/getApDex.ts
Labels: bug

#3896 [Feat]: Full View
  frontend/src/components/Graph/types.ts
  frontend/src/components/Uplot/Uplot.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/GraphManager.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/TableRender/CustomCheckBox.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/TableRender/GetLabel.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/TableRender/GraphManagerColumns.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/types.ts
  frontend/src/container/GridCardLayout/GridCard/FullView/utils.ts
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/types.ts
  frontend/src/container/GridCardLayout/GridCard/utils.ts
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/GridPanelSwitch/index.tsx
  frontend/src/container/GridPanelSwitch/types.ts
  frontend/src/container/NewDashboard/DashboardDescription/ShareModal.tsx
  frontend/src/container/NewDashboard/DashboardDescription/utils.ts
  frontend/src/lib/uPlotLib/getUplotChartData.ts
Labels: enhancement, request-more-info

#3919 feat: use spline renderer to plot curved line graphs, full view impor…
  frontend/src/components/TimePreferenceDropDown/index.tsx
  frontend/src/constants/theme.ts
  frontend/src/container/GridCardLayout/GridCard/FullView/GraphManager.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/WidgetFullView.styles.scss
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/config.ts
  frontend/src/container/NewDashboard/ComponentsSlider/index.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
  frontend/src/hooks/dashboard/utils.ts
  frontend/src/lib/uPlotLib/getUplotChartData.ts
  frontend/src/lib/uPlotLib/plugins/onClickPlugin.ts
  frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
  frontend/src/lib/uPlotLib/uPlotLib.styles.scss
  frontend/src/lib/uPlotLib/utils/getAxes.ts
  frontend/src/lib/uPlotLib/utils/getChartData.ts
  frontend/src/lib/uPlotLib/utils/getGridColor.ts
  frontend/src/lib/uPlotLib/utils/getRenderer.ts
  frontend/src/lib/uPlotLib/utils/getSeriesData.ts
  frontend/src/styles.scss
Labels: enhancement

#3920 [Fix]: Add panel issue in dashboard
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
Labels: bug

#3925 feat: replace time series graph in logs explorer and trace explorer w…
  frontend/src/components/Uplot/Uplot.tsx
  frontend/src/components/Uplot/uplot.scss
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
  frontend/src/lib/uPlotLib/getUplotChartData.ts
  frontend/src/styles.scss
Labels: enhancement

#3931 feat: alert threshold is added
  frontend/src/container/AlertsPanelSwitch/index.tsx
  frontend/src/container/AlertsPanelSwitch/types.ts
  frontend/src/container/AlertsPanelSwitch/utils.ts
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/lib/uPlotLib/getUplotChartData.ts
  frontend/src/lib/uPlotLib/utils/getRenderer.ts
  frontend/src/lib/uPlotLib/utils/getSeriesData.ts
Labels: enhancement, frontend

#3928 feat: added services page playwright tests
  frontend/tests/fixtures/api/services/200.json
  frontend/tests/service/servicesLanding.spec.ts
Labels: request-more-info

#3941 feat: uplot styles are fixed and build is fixed
  frontend/src/components/Uplot/uplot.scss
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/Graph.test.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/GridCardLayout/WidgetHeader/styles.ts
  frontend/src/container/GridCardLayout/styles.ts
  frontend/src/container/MetricsApplication/Tabs/Overview/TopLevelOperations.tsx
  frontend/src/lib/uPlotLib/getUplotChartData.ts
  frontend/src/lib/uPlotLib/placement.ts
  frontend/src/lib/uPlotLib/utils/getAxes.ts
  frontend/src/lib/uPlotLib/utils/getSeriesData.ts
Labels: bug, enhancement, request-more-info

#3906 fix: try Signoz button is visible on success
  frontend/src/container/Header/index.tsx
Labels: bug, frontend

#3944 Fix/app dex aligment
  frontend/src/container/GridCardLayout/WidgetHeader/styles.ts
Labels: bug, request-more-info

#3924 chore: dashboards to alerts creation support in query-service
  pkg/query-service/rules/alerting.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/promRule.go
  pkg/query-service/rules/thresholdRule.go
Labels: chore, request-more-info

#3948 fix: full View styles and saving feature
  frontend/src/container/GridCardLayout/GridCard/FullView/TableRender/Label.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/styles.ts
  frontend/src/container/GridValueComponent/index.tsx
  frontend/src/container/GridValueComponent/styles.ts
Labels: request-more-info

#3908 feat(FE): dashboard alerts is added
  frontend/public/locales/en-GB/alerts.json
  frontend/public/locales/en-GB/rules.json
  frontend/public/locales/en/alerts.json
  frontend/public/locales/en/rules.json
  frontend/src/container/FormAlertRules/PromqlSection.tsx
  frontend/src/container/FormAlertRules/RuleOptions.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/FormAlertRules/styles.ts
  frontend/src/container/FormAlertRules/utils.ts
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/WidgetHeader/index.tsx
  frontend/src/container/GridCardLayout/config.ts
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/ApDexMetricsApplication.tsx
  frontend/src/container/MetricsApplication/constant.ts
  frontend/src/container/NewWidget/RightContainer/YAxisUnitSelector.tsx
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/types/api/alerts/def.ts
Labels: enhancement, frontend

#3942 feat: happy flow for services from list view to all the three details tab rendering the correct tables
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/index.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ServiceOverview.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/TopLevelOperations.tsx
  frontend/tests/service/servicesLanding.spec.ts
  frontend/tests/service/utils.ts
Labels: request-more-info

#3966 fix: timestamp for start and end is updated for view trace
  frontend/src/container/MetricsApplication/Tabs/util.ts
Labels: bug, request-more-info

#3969 fix: loading over flow is fixed
  frontend/src/container/GridCardLayout/styles.ts
Labels: bug, request-more-info

#3970 feat: use error boundary lib and setup fallback component
  frontend/package.json
  frontend/public/locales/en/errorDetails.json
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/ServiceApplication/index.tsx
  frontend/src/index.tsx
  frontend/src/pages/ErrorBoundaryFallback/ErrorBoundaryFallback.styles.scss
  frontend/src/pages/ErrorBoundaryFallback/ErrorBoundaryFallback.tsx
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/pages/Trace/index.tsx
  frontend/src/pages/TracesExplorer/index.tsx
  frontend/yarn.lock
Labels: enhancement, request-more-info

#3949 [Feat]: Threshold in dashboard for Value Component
  frontend/package.json
  frontend/public/locales/en/valueGraph.json
  frontend/src/components/DraggableTableRow/tests/__snapshots__/DraggableTableRow.test.tsx.snap
  frontend/src/components/ExplorerCard/SaveViewWithName.tsx
  frontend/src/components/MessageTip/__snapshots__/MessageTip.test.tsx.snap
  frontend/src/components/ValueGraph/ValueGraph.styles.scss
  frontend/src/components/ValueGraph/index.tsx
  frontend/src/components/ValueGraph/styles.ts
  frontend/src/components/ValueGraph/utils.ts
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/WidgetHeader/index.tsx
  frontend/src/container/GridPanelSwitch/index.tsx
  frontend/src/container/GridPanelSwitch/types.ts
  frontend/src/container/GridValueComponent/index.tsx
  frontend/src/container/GridValueComponent/types.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/QueryHeader.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphContainer.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/index.tsx
  frontend/src/container/NewWidget/LeftContainer/index.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/ColorSelector.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/ColorSelector.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/CustomColor.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/CustomColor.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/ShowCaseValue.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/ShowCaseValue.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/ThresholdSelector.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/ThresholdSelector.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/types.ts
  frontend/src/container/NewWidget/RightContainer/constants.ts
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/NewWidget/types.ts
  frontend/src/container/OnboardingContainer/APM/Javascript/Javascript.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/AddDomain/index.tsx
  frontend/src/container/PipelinePage/tests/__snapshots__/CreatePipelineButton.test.tsx.snap
  frontend/src/container/PipelinePage/tests/__snapshots__/DragAction.test.tsx.snap
  frontend/src/container/PipelinePage/tests/__snapshots__/PipelineExpandView.test.tsx.snap
  frontend/src/container/PipelinePage/tests/__snapshots__/PipelinePageLayout.test.tsx.snap
  frontend/src/container/PipelinePage/tests/__snapshots__/PipelinesSearchSection.test.tsx.snap
  frontend/src/container/PipelinePage/tests/__snapshots__/TagInput.test.tsx.snap
  frontend/src/container/PipelinePage/tests/__snapshots__/Tags.test.tsx.snap
  frontend/src/container/ServiceApplication/ServiceMetrics/ServiceMetrics.test.tsx
  frontend/src/hooks/useDebounce.tsx
  frontend/src/pages/MetricsApplication/ApDex/ApDexSettings.test.tsx
  frontend/src/types/api/dashboard/getAll.ts
  frontend/yarn.lock
Labels: enhancement

#3973 Feat/fill span gaps reset
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphContainer.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/index.tsx
  frontend/src/container/NewWidget/LeftContainer/index.tsx
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/NewWidget/types.ts
  frontend/src/lib/uPlotLib/getUplotChartData.ts
  frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
  frontend/src/lib/uPlotLib/utils/getChartData.ts
  frontend/src/pages/DashboardWidget/index.tsx
  frontend/src/types/api/dashboard/getAll.ts
Labels: enhancement, request-more-info

#3974 [Feat]: Uplot Threshold in Time Series.
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/ThresholdSelector.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/types.ts
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/lib/getConvertedValue.ts
  frontend/src/lib/uPlotLib/getUplotChartData.ts
Labels: enhancement

#3979 [Fix]: Threshold in dashboard fixes
  frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.tsx
Labels: bug

#3972 fix: improve user telemetry
  ee/query-service/app/api/license.go
  ee/query-service/app/server.go
  ee/query-service/license/manager.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/explorer/db.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/logparsingpipeline/db.go
  pkg/query-service/app/server.go
  pkg/query-service/auth/auth.go
  pkg/query-service/auth/jwt.go
  pkg/query-service/dao/sqlite/rbac.go
  pkg/query-service/telemetry/telemetry.go
  pkg/query-service/tests/integration/logparsingpipeline_test.go
Labels: bug

#3980 [Fix]: threshold dashboard fixes
  frontend/src/container/NewWidget/RightContainer/Threshold/ColorSelector.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/ColorSelector.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.tsx
  frontend/src/container/NewWidget/RightContainer/constants.ts
  frontend/src/container/NewWidget/RightContainer/index.tsx
Labels: bug

#3985 chore: add new telemetry events and heartbeat events to saas
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/auth/auth.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore, request-more-info

#3960 feat: trace explorer page end to end test
  frontend/src/components/ExplorerCard/ExplorerCard.tsx
  frontend/src/components/ExplorerCard/SaveViewWithName.tsx
  frontend/src/container/NewExplorerCTA/index.tsx
  frontend/src/container/TracesExplorer/ListView/utils.tsx
  frontend/src/container/TracesExplorer/TracesView/configs.tsx
  frontend/tests/fixtures/api/traces/attributeKeys200.json
  frontend/tests/fixtures/api/traces/attributeKeysDurationNano200.json
  frontend/tests/fixtures/api/traces/attributeKeysHttpMethod200.json
  frontend/tests/fixtures/api/traces/attributeKeysName200.json
  frontend/tests/fixtures/api/traces/attributeKeysResponseStatusCode200.json
  frontend/tests/fixtures/api/traces/attributeKeysServiceName200.json
  frontend/tests/fixtures/api/traces/queryRange200.json
  frontend/tests/fixtures/api/traces/traceExplorerViewPost200.json
  frontend/tests/fixtures/api/traces/traceExplorerViews200.json
  frontend/tests/fixtures/api/traces/tracesRange200.json
  frontend/tests/fixtures/api/traces/tracesTableView200.json
  frontend/tests/traces/newTracesExplorer.spec.ts
  frontend/tests/traces/utils.ts
Labels: request-more-info

#3992 feat: reset selected environment, service name, framework on data so…
  frontend/src/container/OnboardingContainer/Steps/DataSource/DataSource.tsx
Labels: enhancement, frontend

#3993 feat: update logic to generate x series for line series charts
  frontend/src/components/Uplot/Uplot.tsx
  frontend/src/lib/uPlotLib/utils/getChartData.ts
Labels: enhancement, request-more-info

#3994 feat: add open sans font and set font family in theme configuration
  frontend/src/container/Header/styles.ts
  frontend/src/hooks/useDarkMode/index.tsx
  frontend/src/index.html.ejs
Labels: enhancement, frontend, request-more-info

#3995 feat: copy to clipboard start and end time added
  frontend/src/hooks/logs/useCopyLogLink.ts
Labels: enhancement

#3654 feat: improve dashboard view user experience
  frontend/src/container/ListOfDashboard/TableComponents/DeleteButton.tsx
  frontend/src/container/ListOfDashboard/index.tsx
  frontend/src/container/NewDashboard/DashboardSettings/index.tsx
  frontend/src/container/TopNav/DateTimeSelection/config.ts
  frontend/src/container/TopNav/index.tsx
  frontend/src/hooks/useDarkMode/index.tsx
  frontend/src/index.html.ejs
Labels: enhancement, request-more-info, do-not-merge

#3989 feat: added dashboard list and create tests
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/GridCardLayout/WidgetHeader/index.tsx
  frontend/src/container/ListOfDashboard/index.tsx
  frontend/src/container/NewDashboard/DashboardDescription/SettingsDrawer.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/container/NewDashboard/DashboardSettings/General/index.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/index.tsx
  frontend/tests/dashboards/index.spec.ts
  frontend/tests/dashboards/utils.ts
  frontend/tests/fixtures/api/dashboard/createNewDashboardPost200.json
  frontend/tests/fixtures/api/dashboard/dashboardGetCallWithTimeSeriesWidget200.json
  frontend/tests/fixtures/api/dashboard/getDashboardListEmpty200.json
  frontend/tests/fixtures/api/dashboard/getIndividualDashboard200.json
  frontend/tests/fixtures/api/dashboard/putDashboardWithTimeSeries200.json
  frontend/tests/fixtures/api/dashboard/putNewDashboardUpdate200.json
Labels: request-more-info

#4004 chore: uplot file renames and reference updates
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
  frontend/src/lib/uPlotLib/utils/getUplotChartData.ts
Labels: chore, request-more-info

#4007 fix: remove points with negative timestamps
  pkg/query-service/app/querier/querier.go
Labels: bug

#4026 fix: use correct operator for db and external APM metrics
  .github/CODEOWNERS
  frontend/src/container/MetricsApplication/MetricsPageQueries/DBCallQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/ExternalQueries.ts
Labels: bug

#4025 fix: having white space is removed
  frontend/src/container/QueryBuilder/filters/Formula/Having/HavingFilter.tsx
Labels: bug

#4023 [Fix]: where clause issue
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/utils.ts
Labels: bug

#4003 feat: setup end to end test framework for playwright
  .gitignore
  e2e/package.json
  e2e/playwright.config.ts
  e2e/tests/login.spec.ts
  e2e/yarn.lock
Labels: request-more-info

#4040 feat: show dashboard in full screen
  frontend/package.json
  frontend/public/locales/en/dashboard.json
  frontend/src/container/GridCardLayout/GridCardLayout.styles.scss
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/yarn.lock
Labels: enhancement, request-more-info

#4002 [Feat]: threshold in table
  frontend/src/constants/events.ts
  frontend/src/container/GridPanelSwitch/index.tsx
  frontend/src/container/GridTableComponent/index.tsx
  frontend/src/container/GridTableComponent/types.ts
  frontend/src/container/GridTableComponent/utils.ts
  frontend/src/container/NewWidget/RightContainer/Threshold/ShowCaseValue.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/ThresholdSelector.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/types.ts
  frontend/src/container/NewWidget/RightContainer/constants.ts
  frontend/src/container/QueryTable/QueryTable.intefaces.ts
  frontend/src/container/QueryTable/QueryTable.tsx
Labels: enhancement

#4044 fix: remove tooltip on chart cleanup
  frontend/src/components/Uplot/Uplot.tsx
Labels: bug, request-more-info

#4047 fix: add legacy unit types and fix floating point issue
  .github/CODEOWNERS
  pkg/query-service/converter/converter.go
  pkg/query-service/converter/data.go
  pkg/query-service/converter/time.go
  pkg/query-service/formatter/data.go
  pkg/query-service/formatter/formatter.go
  pkg/query-service/formatter/scale.go
  pkg/query-service/formatter/scale_test.go
  pkg/query-service/formatter/time.go
  pkg/query-service/rules/thresholdRule.go
Labels: bug

#4039 fix: new dashboard menu items are flickering
  frontend/src/container/ListOfDashboard/index.tsx
Labels: bug, request-more-info

#4031 feat: added auth as pre-requisite for the other tests
  .gitignore
  e2e/playwright.config.ts
  e2e/tests/auth.setup.ts
  e2e/tests/contants.ts
  e2e/tests/navigation.spec.ts
Labels: request-more-info

#4050 fix: dashboard delete is fixed and toast message is added
  frontend/public/locales/en-GB/dashboard.json
  frontend/public/locales/en/dashboard.json
  frontend/src/container/ListOfDashboard/TableComponents/DeleteButton.tsx
  frontend/src/container/ListOfDashboard/index.tsx
Labels: bug

#4058 [Fix]: the undefined threshold format issue
  frontend/src/container/GridTableComponent/index.tsx
Labels: bug

#4070 fix: update logic for handling data for uplot charts
  frontend/src/components/Uplot/utils.ts
  frontend/src/constants/theme.ts
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCard/types.ts
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/ApDexMetrics.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ServiceOverview.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/TopLevelOperations.tsx
  frontend/src/lib/uPlotLib/utils/getUplotChartData.ts
Labels: bug, request-more-info

#4059 fix: sort tooltip value based on value and highlight on hover
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
  frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
  frontend/src/lib/uPlotLib/uPlotLib.styles.scss
  frontend/src/styles.scss
Labels: bug, request-more-info

#4090 chore: update rule create response
  pkg/query-service/app/http_handler.go
  pkg/query-service/rules/db.go
  pkg/query-service/rules/manager.go
Labels: chore

#4052 feat: added the share link for view widget mode
  frontend/src/constants/query.ts
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/ListOfDashboard/index.tsx
  frontend/src/lib/createQueryParams.ts
Labels: enhancement, frontend

#4076 fix: updated the form value on mount
  frontend/src/container/EditAlertChannels/index.tsx
  frontend/src/pages/ChannelsEdit/index.tsx
Labels: bug, frontend

#4098 fix: [GH-4097]: Fix missing values in chart tooltip
  frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
Labels: bug

#4068 fix: use window function lagInFrame for rate calculation
  pkg/query-service/app/metrics/v3/cumulative_table.go
  pkg/query-service/app/metrics/v3/cumulative_table_test.go
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
Labels: bug, request-more-info

#4089 fix: [GH-4075]: block action on the view section if the dashboard is locked
  frontend/src/container/GridCardLayout/GridCard/FullView/GraphManager.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/TableRender/CustomCheckBox.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/TableRender/GetLabel.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/TableRender/GraphManagerColumns.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/TableRender/Label.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/WidgetFullView.styles.scss
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/styles.ts
  frontend/src/container/GridCardLayout/GridCard/FullView/types.ts
Labels: request-more-info

#4022 feat: custom timeout and contextTimeout flag in response
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/app/server_test.go
  pkg/query-service/constants/constants.go
  pkg/query-service/model/v3/v3.go
Labels: enhancement

#4102 feat: add pr template
  .github/pull_request_template.md
Labels: request-more-info

#4084 fix: queryTable is updated with newData
  frontend/src/container/QueryTable/QueryTable.tsx
Labels: bug

#4046 FE: while saving widget scrolled into view
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/providers/Dashboard/Dashboard.tsx
  frontend/src/providers/Dashboard/types.ts
Labels: enhancement

#4010 feat: dashboard perf improvements
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/api/dashboard/update.ts
  frontend/src/api/dashboard/variables/dashboardVariablesQuery.ts
  frontend/src/api/dashboard/variables/query.ts
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/ListOfDashboard/TableComponents/CreatedBy.tsx
  frontend/src/container/ListOfDashboard/TableComponents/DeleteButton.tsx
  frontend/src/container/ListOfDashboard/TableComponents/Name.tsx
  frontend/src/container/ListOfDashboard/TableComponents/Tags.tsx
  frontend/src/container/ListOfDashboard/index.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/index.tsx
  frontend/src/container/NewDashboard/DashboardSettings/index.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.styles.scss
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.test.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/index.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/styles.ts
  frontend/src/container/TopNav/DateTimeSelection/config.ts
  frontend/src/pages/DashboardsListPage/DashboardsListPage.tsx
  frontend/src/pages/DashboardsListPage/index.tsx
  frontend/src/pages/NewDashboard/DashboardPage.tsx
  frontend/src/pages/NewDashboard/index.tsx
  frontend/src/types/api/dashboard/variables/query.ts
  frontend/tsconfig.json
  frontend/webpack.config.js
Labels: enhancement, request-more-info

#4123 ci(staging-deployment): ✏️ fix command to fetch schema migrator image
  .github/workflows/staging-deployment.yaml
Labels: bug

#4083 fix: onRun Query offset is made zero
  frontend/src/constants/query.ts
  frontend/src/container/TracesExplorer/ListView/index.tsx
  frontend/src/container/TracesExplorer/TracesView/index.tsx
  frontend/src/hooks/queryPagination/config.ts
  frontend/src/hooks/queryPagination/useQueryPagination.ts
  frontend/src/providers/QueryBuilder.tsx
Labels: bug

#4108 [Fix]: the default query issue in log
  frontend/src/components/ExplorerCard/utils.ts
Labels: bug
