Repository SigNoz/signoz, pull requests merged in 2023-05, with the labels that each got.

#2650 test: loadable component is added
  frontend/src/components/Loadable/Loadable.test.tsx
Labels: request-more-info, codeball:approved

#2644 feat: package dependency is made exact
  frontend/.yarnrc
Labels: enhancement, chore, codeball:needs-careful-review

#2640 test: dashboard variable is updated
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.test.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/utils.test.ts
Labels: test, codeball:needs-careful-review

#2589 test: added useIsValidTag.test
  frontend/src/hooks/queryBuilder/useIsValidTag.test.ts
Labels: test, query-builder, codeball:needs-careful-review

#2649 test: editor test case is added
  frontend/src/components/Editor/Editor.test.tsx
  frontend/src/components/Editor/__snapshots__/Editor.test.tsx.snap
  frontend/src/components/Editor/index.tsx
Labels: request-more-info, codeball:needs-careful-review

#2668 fix: trim spaces from email invite
  pkg/query-service/app/parser.go
Labels: bug, request-more-info

#2664 fix: nan aggregation values are skipped
  pkg/query-service/app/metrics/query_builder.go
Labels: bug, codeball:needs-careful-review

#2663 feat(query-service): alerts integration with query builder v3
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
  pkg/query-service/model/v3/v3.go
  pkg/query-service/rules/alerting.go
  pkg/query-service/rules/apiParams.go
  pkg/query-service/rules/promRule.go
  pkg/query-service/rules/thresholdRule.go
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2669 [Fix]: Alert Channels breadcrumbs
  frontend/src/constants/routes.ts
  frontend/src/container/TopNav/Breadcrumbs/index.tsx
Labels: frontend

#2665 feat: add builder data to metric application
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/CreateAlertRule/defaults.ts
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/FormAlertRules/QuerySection.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/MetricsApplication/MetricsPageQueries/DBCallQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/ExternalQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/MetricsPageQueriesFactory.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/OverviewQueries.ts
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/Tabs/util.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/utils.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/constants.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/types.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/utils/getQueryKey.ts
  frontend/src/hooks/useResourceAttribute/utils.ts
  frontend/src/lib/newQueryBuilder/convertNewDataToOld.ts
  frontend/src/lib/newQueryBuilder/getQueryKey.ts
  frontend/src/lib/newQueryBuilder/queryBuilderMappers/mapQueryDataToApi.ts
  frontend/src/store/actions/dashboard/getQueryResults.ts
  frontend/src/types/api/alerts/compositeQuery.ts
  frontend/src/types/api/alerts/queryType.ts
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
  frontend/src/types/common/dashboard.ts
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2657 feat: add query builder to the alerts
  frontend/src/constants/alerts.ts
  frontend/src/constants/queryBuilder.ts
  frontend/src/constants/regExp.ts
  frontend/src/container/CreateAlertRule/defaults.ts
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/FormAlertRules/QuerySection.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/FormAlertRules/styles.ts
  frontend/src/container/FormAlertRules/utils.ts
  frontend/src/container/GridGraphLayout/utils.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/DBCallQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/ExternalQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/MetricsPageQueriesFactory.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/OverviewQueries.ts
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/Tabs/util.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/query.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/utils.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/constants.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/types.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/utils/getQueryKey.ts
  frontend/src/container/QueryBuilder/QueryBuilder.tsx
  frontend/src/container/QueryBuilder/components/FilterLabel/FilterLabel.styled.ts
  frontend/src/container/QueryBuilder/components/ListMarker/ListMarker.styled.ts
  frontend/src/container/QueryBuilder/components/Query/Query.interfaces.ts
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.interfaces.ts
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
  frontend/src/container/QueryBuilder/filters/HavingFilter/HavingFilter.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/hooks/queryBuilder/useQueryOperations.ts
  frontend/src/hooks/useResourceAttribute/utils.ts
  frontend/src/lib/newQueryBuilder/convertNewDataToOld.ts
  frontend/src/lib/newQueryBuilder/getFilterObjectValue.ts
  frontend/src/lib/newQueryBuilder/getOperatorsBySourceAndPanelType.ts
  frontend/src/lib/newQueryBuilder/queryBuilderMappers/mapQueryDataFromApi.ts
  frontend/src/lib/newQueryBuilder/queryBuilderMappers/mapQueryDataToApi.ts
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/store/actions/dashboard/getDashboard.ts
  frontend/src/store/actions/dashboard/getQueryResults.ts
  frontend/src/types/api/alerts/alertTypes.ts
  frontend/src/types/api/alerts/compositeQuery.ts
  frontend/src/types/api/alerts/def.ts
  frontend/src/types/api/alerts/queryType.ts
  frontend/src/types/api/dashboard/getAll.ts
  frontend/src/types/api/dashboard/shared.ts
  frontend/src/types/api/queryBuilder/queryAutocompleteResponse.ts
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
  frontend/src/types/common/dashboard.ts
  frontend/src/types/common/operations.types.ts
  frontend/src/types/common/queryBuilder.ts
  frontend/src/types/common/queryBuilderMappers.types.ts
  frontend/src/types/common/select.ts
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2678 fix: disable prometheus.NormalizeName flag
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose-core.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  pkg/query-service/tests/test-deploy/docker-compose.yaml
Labels: bug, codeball:needs-careful-review

#2683 fix: query builder filter label is adopted for dark mode
  frontend/src/constants/theme.ts
  frontend/src/container/QueryBuilder/components/FilterLabel/FilterLabel.styled.ts
  frontend/src/container/QueryBuilder/components/FilterLabel/FilterLabel.tsx
Labels: bug, codeball:needs-careful-review

#2682 chore: removed some of the stage logic in the query builder
  frontend/src/container/NewWidget/LeftContainer/QuerySection/TabHeader.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/utils/userSettings.ts
  frontend/src/container/NewWidget/LeftContainer/QueryTypeTag.tsx
  frontend/src/container/NewWidget/LeftContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
Labels: chore, codeball:needs-careful-review

#2629 fix: issues on WHERE search filter
  frontend/package.json
  frontend/src/api/queryBuilder/getAggregateAttribute.ts
  frontend/src/api/queryBuilder/getAttributeKeys.ts
  frontend/src/api/queryBuilder/getAttributesKeysValues.ts
  frontend/src/api/queryBuilder/getAttributesValues.ts
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/MetricsPageQueriesFactory.ts
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/filters/HavingFilter/HavingFilter.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/style.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/utils.ts
  frontend/src/container/QueryBuilder/type.ts
  frontend/src/container/TopNav/CustomDateTimeModal/index.tsx
  frontend/src/hooks/queryBuilder/useAutoComplete.ts
  frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
  frontend/src/hooks/queryBuilder/useOperators.ts
  frontend/src/hooks/queryBuilder/useOptions.ts
  frontend/src/hooks/queryBuilder/useQueryOperations.ts
  frontend/src/hooks/queryBuilder/useSetCurrentKeyAndOperator.ts
  frontend/src/hooks/queryBuilder/useTag.ts
  frontend/src/hooks/queryBuilder/useTagValidation.ts
  frontend/src/types/api/queryBuilder/getAttributeKeys.ts
  frontend/src/types/api/queryBuilder/getAttributesValues.ts
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
  frontend/src/utils/checkStringEndsWithSpace.ts
  frontend/src/utils/getCountOfSpace.ts
  frontend/src/utils/getSearchParams.ts
  frontend/src/utils/separateSearchValue.ts
Labels: frontend, ok-to-test, query-builder

#2686 refactor(query_builder): remove old codebase
  frontend/src/constants/dashboard.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/Options.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/promQL/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/MetricTagKeyFilter/MetricTagKey.machine.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/MetricTagKeyFilter/MetricTagKey.machine.typegen.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/MetricTagKeyFilter/QueryChip.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/MetricTagKeyFilter/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/MetricTagKeyFilter/styles.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/MetricTagKeyFilter/types.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/MetricTagKeyFilter/utils.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/formula.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/query.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/types.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/utils.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/constants.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/types/api/alerts/compositeQuery.ts
  frontend/src/types/api/dashboard/getAll.ts
  frontend/src/types/common/dashboard.ts
Labels: request-more-info, codeball:needs-careful-review

#2680 fix: resolve gaps identified in the query builder
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/parser_test.go
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
  pkg/query-service/model/v3/v3.go
Labels: bug, request-more-info, codeball:needs-careful-review

#2693 fix : parsing issue is fixed in the table view
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogDetailedView/utils.ts
Labels: bug, request-more-info, codeball:needs-careful-review

#2698 fix: count fixed columns of type bool/number
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/app/traces/v3/query_builder_test.go
Labels: bug, request-more-info

#2667 fix: small typo in README.md
  README.md
Labels: request-more-info

#2703 fix(frontend): 🐛 accept zero as valid alert threshold
  frontend/src/container/FormAlertRules/index.tsx
Labels: bug, ok-to-test

#2661 feat: introduce feature_usage table to manage features
  ee/query-service/app/api/featureFlags.go
  ee/query-service/app/server.go
  ee/query-service/license/db.go
  ee/query-service/license/manager.go
  ee/query-service/license/sqlite/init.go
  ee/query-service/model/plans.go
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/dashboards/provision.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/constants/constants.go
  pkg/query-service/featureManager/manager.go
  pkg/query-service/interfaces/featureLookup.go
  pkg/query-service/model/featureSet.go
  pkg/query-service/rules/manager.go
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2694 feat: add signoz cloud button in header
  frontend/src/container/Header/index.tsx
Labels: enhancement, codeball:needs-careful-review

#2608 feat: don't throw error if unable to enrich metadata
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
Labels: enhancement, codeball:needs-careful-review

#2679 fix: update the resource detection processor name for GCP
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
Labels: bug, codeball:needs-careful-review

#2718 chore: commit lock file
  .gitignore
  frontend/Dockerfile
  frontend/yarn.lock
Labels: chore, request-more-info, codeball:needs-careful-review

#2699 feat: trace to logs and logs to trace is added
  frontend/src/components/Logs/AddToQueryHOC.tsx
  frontend/src/components/Logs/styles.ts
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogsSearchFilter/useSearchParser.ts
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2697 fix: issue of new query builder v3
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/filters/AggregateEveryFilter/index.tsx
  frontend/src/container/QueryBuilder/filters/HavingFilter/HavingFilter.tsx
  frontend/src/container/QueryBuilder/filters/LimitFilter/LimitFilter.tsx
  frontend/src/container/QueryBuilder/filters/OrderByFilter/OrderByFilter.interfaces.ts
  frontend/src/container/QueryBuilder/filters/OrderByFilter/OrderByFilter.tsx
  frontend/src/container/QueryBuilder/filters/OrderByFilter/utils.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/config.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/utils.ts
  frontend/src/container/QueryBuilder/filters/index.ts
  frontend/src/hooks/queryBuilder/useAutoComplete.ts
  frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
  frontend/src/hooks/queryBuilder/useOptions.ts
  frontend/src/hooks/queryBuilder/useQueryOperations.ts
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
Labels: request-more-info

#2713 fix: add support for bool values in time series result
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug, request-more-info, codeball:needs-careful-review

#2706 fix: having filter removing payload
  frontend/src/api/queryBuilder/getAggregateAttribute.ts
  frontend/src/api/queryBuilder/getAttributeKeys.ts
  frontend/src/constants/queryBuilder.ts
  frontend/src/constants/queryBuilderOperators.ts
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
  frontend/src/container/QueryBuilder/filters/HavingFilter/HavingFilter.tsx
  frontend/src/container/QueryBuilder/filters/OperatorsSelect/OperatorsSelect.interfaces.ts
  frontend/src/container/QueryBuilder/filters/OperatorsSelect/OperatorsSelect.tsx
  frontend/src/hooks/queryBuilder/useQueryOperations.ts
  frontend/src/lib/newQueryBuilder/getFilterObjectValue.ts
  frontend/src/lib/newQueryBuilder/getOperatorsBySourceAndPanelType.ts
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/types/api/queryBuilder/queryAutocompleteResponse.ts
  frontend/src/types/common/operations.types.ts
Labels: bug, request-more-info, codeball:needs-careful-review

#2725 fix: api calls
  frontend/src/container/FormAlertRules/useDebounce.js
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
  frontend/src/hooks/useDebounce.tsx
Labels: bug, request-more-info, codeball:needs-careful-review

#2709 fix: add validations for aggregates on logs/traces datasource
  pkg/query-service/app/traces/v3/query_builder_test.go
  pkg/query-service/model/v3/v3.go
Labels: bug, request-more-info, codeball:needs-careful-review

#2728 fix: onBlur for groupBy
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
Labels: bug, request-more-info

#2666 feat: feature flag is updated
  frontend/src/api/features/getFeatures.ts
  frontend/src/constants/featureKeys.ts
  frontend/src/constants/features.ts
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/CreateAlertRule/defaults.ts
  frontend/src/container/FormAlertRules/QuerySection.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/GridGraphLayout/Graph/index.tsx
  frontend/src/container/GridGraphLayout/GraphLayout.tsx
  frontend/src/container/GridGraphLayout/index.tsx
  frontend/src/container/GridGraphLayout/styles.ts
  frontend/src/container/Header/ManageLicense/index.tsx
  frontend/src/container/Licenses/ApplyLicenseForm.tsx
  frontend/src/container/Licenses/index.tsx
  frontend/src/container/ListAlertRules/DeleteAlert.tsx
  frontend/src/container/ListAlertRules/ListAlert.tsx
  frontend/src/container/ListOfDashboard/ImportJSON/index.tsx
  frontend/src/container/ListOfDashboard/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/AddDomain/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/index.tsx
  frontend/src/container/OrganizationSettings/index.tsx
  frontend/src/hooks/queryBuilder/useAutoComplete.ts
  frontend/src/hooks/useFeatureFlag.ts
  frontend/src/hooks/useFeatureFlag/constant.ts
  frontend/src/hooks/useFeatureFlag/index.ts
  frontend/src/hooks/useFeatureFlag/useFeatureFlag.ts
  frontend/src/hooks/useFeatureFlag/useIsFeatureDisabled.ts
  frontend/src/hooks/useLicense/constant.ts
  frontend/src/hooks/useLicense/index.ts
  frontend/src/hooks/useLicense/useLicense.tsx
  frontend/src/store/reducers/app.ts
  frontend/src/types/actions/app.ts
  frontend/src/types/api/features/getFeatures.ts
  frontend/src/types/api/features/getFeaturesFlags.ts
  frontend/src/types/reducer/app.ts
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2701 feat: add default parser for logs
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
Labels: enhancement, codeball:approved

#2732 fix: commit lint is updated
  .github/workflows/commitlint.yml
Labels: bug, request-more-info, codeball:approved

#2731 fix: remove some of the frontend redundant packages
  frontend/package.json
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogDetailedView/util.test.ts
  frontend/src/container/LogDetailedView/utils.ts
  frontend/src/typings/d3-tip.d.ts
  frontend/yarn.lock
Labels: bug, codeball:needs-careful-review

#2735 fix: query key is made dynamic
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/GeneralSettings/index.tsx
  frontend/src/container/Login/index.tsx
  frontend/src/container/OrganizationSettings/Members/index.tsx
  frontend/src/container/OrganizationSettings/PendingInvitesContainer/index.tsx
  frontend/src/pages/Login/index.tsx
  frontend/src/pages/ResetPassword/index.tsx
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/pages/SignUp/index.tsx
Labels: bug, request-more-info, codeball:approved

#2737 chore: remove the limit condition
  frontend/src/container/GridGraphLayout/GraphLayout.tsx
  frontend/src/container/GridGraphLayout/styles.ts
Labels: chore, request-more-info, codeball:approved

#2755 Feat/extend query builder state
  frontend/src/constants/dashboard.ts
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/FormAlertRules/ChQuerySection/ChQuerySection.tsx
  frontend/src/container/FormAlertRules/ChQuerySection/transform.ts
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/FormAlertRules/PromqlSection.tsx
  frontend/src/container/FormAlertRules/QuerySection.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/FormAlertRules/utils.ts
  frontend/src/container/GridGraphLayout/utils.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/QueryHeader.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/query.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/types.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/promQL/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/promQL/query.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/promQL/types.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/types.ts
  frontend/src/container/QueryBuilder/QueryBuilder.tsx
  frontend/src/container/QueryBuilder/components/Formula/Formula.tsx
  frontend/src/hooks/queryBuilder/useQueryOperations.ts
  frontend/src/lib/newQueryBuilder/queryBuilderMappers/mapQueryDataFromApi.ts
  frontend/src/lib/newQueryBuilder/queryBuilderMappers/mapQueryDataToApi.ts
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/store/actions/dashboard/getDashboard.ts
  frontend/src/store/actions/dashboard/getQueryResults.ts
  frontend/src/store/actions/dashboard/updateQuery.ts
  frontend/src/types/actions/dashboard.ts
  frontend/src/types/api/alerts/compositeQuery.ts
  frontend/src/types/api/dashboard/getAll.ts
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
  frontend/src/types/common/queryBuilder.ts
  frontend/src/types/common/queryBuilderMappers.types.ts
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2756 fix: cloud header button is hidden when is license is not active
  frontend/src/container/Header/index.tsx
  frontend/src/hooks/useLicense/constant.ts
  frontend/src/hooks/useLicense/index.ts
Labels: bug, request-more-info, codeball:needs-careful-review

#2754 chore: form changes
  frontend/src/container/OrganizationSettings/DisplayName/index.tsx
  frontend/src/utils/form/requireErrorMessage.ts
Labels: frontend

#2607 test: some of the test case is added
  frontend/src/components/RouteTab/RouteTab.test.tsx
  frontend/src/components/RouteTab/index.tsx
  frontend/src/container/MetricsApplication/index.tsx
  frontend/src/hooks/useComponentPermission.test.ts
  frontend/src/pages/AlertChannelCreate/index.tsx
  frontend/src/pages/AllErrors/index.tsx
  frontend/src/pages/Settings/index.tsx
Labels: request-more-info, codeball:needs-careful-review

#2753 feat: support for top level keys in attributes in query parser logs v3
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/constants/constants.go
Labels: enhancement, codeball:needs-careful-review

#2780 feat: formatter updated
  pkg/query-service/utils/format.go
Labels: enhancement, codeball:needs-careful-review

#2793 Nit: fix typo in install script.
  deploy/install.sh
Labels: request-more-info

#2792 fix: typo in contribution guide
  CONTRIBUTING.md
Labels: request-more-info

#2800 fix: where clause filter
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
Labels: bug, request-more-info

#2796 fix: mutex lock to avoid concurrent map writes
  pkg/query-service/telemetry/telemetry.go
Labels: bug

#2806 fix: service name capitalisation is removed from list page
  frontend/src/container/MetricsTable/styles.ts
Labels: frontend
