Repository SigNoz/signoz, pull requests merged in 2023-09, with the labels that each got.

#3462 chore: upgrade debug dependency
  frontend/package.json
  frontend/yarn.lock
Labels: chore

#3461 chore: upgrade d3-color dependency
  frontend/package.json
  frontend/yarn.lock
Labels: chore

#3465 chore: fix update debug dependency
  frontend/package.json
  frontend/yarn.lock
Labels: bug, chore, request-more-info

#3469 chore: add debug package resolution
  frontend/package.json
  frontend/yarn.lock
Labels: chore, request-more-info

#3473 fix: threshold value is handled for undefined case
  frontend/src/container/FormAlertRules/ChartPreview/utils.ts
Labels: bug, frontend, ok-to-test, team-fe-pr, ready-for-review

#3464 chore: css-minimizer-webpack-plugin is updated
  frontend/package.json
  frontend/yarn.lock
Labels: chore, request-more-info

#3410 chore: bump SigNoz/prometheus
  ee/query-service/app/api/metrics.go
  go.mod
  go.sum
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/pqlEngine/engine.go
  pkg/query-service/rules/promRule.go
Labels: chore

#3479 fix: clear query builder staged query
  frontend/src/container/LiveLogs/BackButton/index.tsx
  frontend/src/hooks/queryBuilder/useShareBuilderUrl.ts
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/types/common/queryBuilder.ts
Labels: bug

#3437 fix(FE/logs): error alert on deleting mandatory selected fields
  frontend/src/api/logs/AddToSelectedField.ts
  frontend/src/api/logs/RemoveFromSelectedField.ts
  frontend/src/container/LogsFilters/utils.ts
Labels: bug, frontend, team-fe-pr

#3501 fix(FE): encode URL query params
  frontend/src/container/ErrorDetails/index.tsx
  frontend/src/container/GridGraphLayout/Graph/WidgetGraphComponent.tsx
  frontend/src/container/NewDashboard/ComponentsSlider/index.tsx
  frontend/src/lib/createQueryParams.ts
  frontend/src/store/actions/trace/util.ts
Labels: bug, frontend, security

#3486 chore(FE): reduce main.js chunk size
  frontend/src/AppRoutes/routes.ts
  frontend/src/api/user/signup.ts
  frontend/src/components/Graph/Plugin/DragSelect.ts
  frontend/src/components/Graph/Plugin/IntersectionCursor.ts
  frontend/src/components/Styled/index.ts
  frontend/src/container/LogControls/index.tsx
  frontend/src/container/QueryBuilder/filters/OrderByFilter/useOrderByFilter.ts
  frontend/src/container/QueryBuilder/filters/OrderByFilter/utils.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/utils.ts
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/hooks/queryBuilder/useAutoComplete.ts
  frontend/src/hooks/queryBuilder/useTag.ts
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/types/api/user/getInviteDetails.ts
  frontend/src/wdyr.ts
Labels: frontend, chore, performance, team-fe-pr

#3503 chore(FE): update webpack, add sass, remove wydr
  frontend/package.json
  frontend/src/index.tsx
  frontend/src/wdyr.ts
  frontend/webpack.config.js
  frontend/webpack.config.prod.js
  frontend/yarn.lock
Labels: chore, request-more-info

#3412 feat: initail version of QB to expr
  go.mod
  pkg/query-service/queryBuilderToExpr/queryBuilderToExpr.go
  pkg/query-service/queryBuilderToExpr/queryBuilderToExpr_test.go
Labels: enhancement

#3502 fix: tagRef is updated
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/utils.ts
Labels: bug, frontend

#3484 fix: do not add redundant [] for array
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#2814 feat: triggered alerts is migrated to useQuery
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/container/TriggeredAlerts/TriggeredAlert.tsx
  frontend/src/container/TriggeredAlerts/index.tsx
Labels: enhancement, frontend, team-fe-pr

#3514 chore: update dependencies
  go.mod
  go.sum
Labels: chore

#3512 fix(FE/Logs): fix all logs not visible on scrolling
  frontend/src/constants/card.ts
  frontend/src/container/LiveLogs/LiveLogsList/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsExplorerList/styles.ts
  frontend/src/container/LogsTable/index.tsx
  frontend/src/container/LogsTable/logsTable.styles.scss
  frontend/src/container/LogsTable/styles.ts
  frontend/src/pages/Logs/index.tsx
  frontend/src/pages/Logs/logs.styles.scss
Labels: bug, frontend

#3517 fix: live logs table color for light mode is fixed
  frontend/src/container/LiveLogs/LiveLogsList/index.tsx
  frontend/src/container/LogsExplorerContext/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/styles.ts
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsExplorerList/styles.ts
Labels: bug, frontend

#3384 feat: all dashboard is migrated to useQuery and action is removed
  frontend/src/api/dashboard/getAll.ts
  frontend/src/container/ExportPanel/ExportPanel.tsx
  frontend/src/container/ListOfDashboard/TableComponents/DeleteButton.tsx
  frontend/src/container/ListOfDashboard/index.tsx
  frontend/src/hooks/dashboard/useGetAllDashboard.tsx
  frontend/src/pages/Dashboard/index.tsx
  frontend/src/store/actions/dashboard/deleteDashboard.ts
  frontend/src/store/actions/dashboard/getAllDashboard.ts
  frontend/src/store/actions/dashboard/index.ts
  frontend/src/types/api/index.ts
Labels: frontend, community-pr

#3522 fix: code scanning issues is fixed
  frontend/src/container/ErrorDetails/config.ts
  frontend/src/container/ErrorDetails/index.tsx
  frontend/src/container/GridGraphLayout/Graph/WidgetGraphComponent.tsx
  frontend/src/container/NewDashboard/ComponentsSlider/index.tsx
  frontend/src/store/actions/trace/util.ts
Labels: bug, frontend, team-fe-pr

#3524 feat: add new ff for ee plan
  ee/query-service/model/plans.go
Labels: enhancement, request-more-info

#3531 [Refactoring]: Seperate title and menu to another component
  frontend/src/container/LogDetailedView/BodyTitleRenderer.styles.ts
  frontend/src/container/LogDetailedView/BodyTitleRenderer.tsx
  frontend/src/container/LogDetailedView/LogDetailedView.types.ts
  frontend/src/container/LogDetailedView/utils.tsx
Labels: request-more-info

#3532 refactor: instead of key showing value if array
  frontend/src/container/LogDetailedView/BodyTitleRenderer.tsx
  frontend/src/container/LogDetailedView/LogDetailedView.types.ts
  frontend/src/container/LogDetailedView/utils.tsx
Labels: request-more-info

#3535 [Feat]: connection to query builder
  frontend/src/container/LogDetailedView/BodyTitleRenderer.tsx
  frontend/src/container/LogDetailedView/LogDetailedView.types.ts
  frontend/src/container/LogDetailedView/utils.tsx
  frontend/src/hooks/logs/types.ts
  frontend/src/hooks/logs/useActiveLog.ts
  frontend/src/lib/newQueryBuilder/chooseAutocompleteFromCustomValue.ts
  frontend/src/types/api/queryBuilder/queryAutocompleteResponse.ts
Labels: request-more-info

#3538 feat: signoz cloud - update polling logic to fetch latest services
  frontend/src/container/OnboardingContainer/APM/common/ConnectionStatus/ConnectionStatus.tsx
  frontend/src/pages/SignUp/SignUp.tsx
Labels: enhancement, request-more-info

#3537 chore(frontend): load dotenv for webpack prod and related changes
  .gitignore
  frontend/.dockerignore
  frontend/example.env
  frontend/webpack.config.js
  frontend/webpack.config.prod.js
Labels: chore

#3534 feat: support for json query on body
  pkg/query-service/app/logs/v3/enrich_query.go
  pkg/query-service/app/logs/v3/enrich_query_test.go
  pkg/query-service/app/logs/v3/json_filter.go
  pkg/query-service/app/logs/v3/json_filter_test.go
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/model/v3/v3.go
Labels: enhancement

#3533 chore: prefer delta temporality by default
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose-local.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  pkg/query-service/README.md
  pkg/query-service/tests/test-deploy/docker-compose.yaml
Labels: chore, request-more-info

#3541 prefer delta by default - fix indent
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose-local.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  pkg/query-service/tests/test-deploy/docker-compose.yaml
Labels: bug, request-more-info

#3542 Refactor: Log parsing updates
  frontend/src/container/LogDetailedView/BodyTitleRenderer.tsx
  frontend/src/container/LogDetailedView/utils.tsx
Labels: request-more-info

#3540 feat: signoz cloud - show cloud onboarding docs only when the domain …
  frontend/src/AppRoutes/index.tsx
  frontend/src/container/SideNav/SideNav.tsx
Labels: enhancement

#3543 fix: remove unnecessary braces in clickhouse reader
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug, request-more-info

#3544 feat: json filter bool support
  pkg/query-service/app/logs/v3/json_filter.go
  pkg/query-service/app/logs/v3/json_filter_test.go
  pkg/query-service/model/v3/v3.go
Labels: enhancement

#3548 docs: updated APM docs
  frontend/src/container/OnboardingContainer/APM/GoLang/goLang.md
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/java.md
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/jboss.md
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/spring_boot.md
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/tomcat.md
  frontend/src/container/OnboardingContainer/APM/Javascript/Javascript.tsx
  frontend/src/container/OnboardingContainer/APM/Javascript/md-docs/angular.md
  frontend/src/container/OnboardingContainer/APM/Javascript/md-docs/express.md
  frontend/src/container/OnboardingContainer/APM/Javascript/md-docs/javascript.md
  frontend/src/container/OnboardingContainer/APM/Javascript/md-docs/nestjs.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/django.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/falcon.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/fastAPI.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/flask.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/python.md
  frontend/src/container/OnboardingContainer/InfrastructureMonitoring/InfrastructureMonitoring.tsx
  frontend/src/container/OnboardingContainer/InfrastructureMonitoring/infraMonitoringDocs.md
  frontend/src/container/OnboardingContainer/InfrastructureMonitoring/prometheus.md
  frontend/src/container/OnboardingContainer/InfrastructureMonitoring/specific-metric-receiver.md
  frontend/src/container/OnboardingContainer/LogsManagement/ExistingCollectors/ExistingCollectors.tsx
  frontend/src/container/OnboardingContainer/LogsManagement/ExistingCollectors/md-docs/fluentBit.md
  frontend/src/container/OnboardingContainer/LogsManagement/ExistingCollectors/md-docs/fluentD.md
  frontend/src/container/OnboardingContainer/LogsManagement/ExistingCollectors/md-docs/logStash.md
  frontend/src/container/OnboardingContainer/LogsManagement/LogsManagement.tsx
Labels: request-more-info

#3551 chore: :pencil2: fix typo - date => data
  frontend/public/locales/en-GB/signup.json
  frontend/public/locales/en/signup.json
Labels: request-more-info

#2696 feat: tree is updated to show different node values instead of editor
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/ExplorerOrderBy/index.tsx
  frontend/src/container/LiveLogs/constants.ts
  frontend/src/container/LogDetailedView/BodyTitleRenderer.styles.ts
  frontend/src/container/LogDetailedView/BodyTitleRenderer.tsx
  frontend/src/container/LogDetailedView/LogDetailedView.types.ts
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogDetailedView/constant.ts
  frontend/src/container/LogDetailedView/util.test.ts
  frontend/src/container/LogDetailedView/utils.ts
  frontend/src/container/LogDetailedView/utils.tsx
  frontend/src/container/LogsExplorerContext/utils.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/DBCallQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/ExternalQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/OverviewQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/TopOperationQueries.ts
  frontend/src/container/MetricsApplication/constant.ts
  frontend/src/container/OnboardingContainer/LogsManagement/common/LogsConnectionStatus/LogsConnectionStatus.tsx
  frontend/src/container/QueryBuilder/filters/HavingFilter/__tests__/utils.test.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/utils.ts
  frontend/src/container/ServiceApplication/ServiceMetrics/ServiceMetricsQuery.ts
  frontend/src/hooks/logs/types.ts
  frontend/src/hooks/logs/useActiveLog.ts
  frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
  frontend/src/hooks/queryBuilder/useOperatorType.ts
  frontend/src/hooks/queryBuilder/useOperators.ts
  frontend/src/hooks/useResourceAttribute/utils.ts
  frontend/src/lib/newQueryBuilder/chooseAutocompleteFromCustomValue.ts
  frontend/src/lib/newQueryBuilder/getPaginationQueryData.ts
  frontend/src/types/api/queryBuilder/queryAutocompleteResponse.ts
Labels: enhancement, frontend, team-fe-pr

#3563 chore: tree is expanded by default
  frontend/src/container/LogDetailedView/TableView.tsx
Labels: chore

#3558 [Refactor]: aggreated attributes and resources from json
  frontend/src/container/LogDetailedView/JsonView.tsx
  frontend/src/container/LogDetailedView/LogDetailedView.types.ts
  frontend/src/container/LogDetailedView/utils.tsx
  frontend/src/types/api/logs/log.ts
Labels: frontend, team-fe-pr

#3566 feat: limit & order by is enabled in the metrics query builder
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/hooks/queryBuilder/useQueryOperations.ts
  pkg/query-service/app/http_handler.go
Labels: enhancement, frontend, team-fe-pr

#2142 Query range caching
  Makefile
  ee/query-service/app/api/api.go
  ee/query-service/app/server.go
  ee/query-service/main.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/querier/helper.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/app/server.go
  pkg/query-service/config/cache-config.yml
  pkg/query-service/interfaces/interface.go
  pkg/query-service/main.go
  pkg/query-service/model/db.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/model/response.go
Labels: request-more-info, codeball:needs-careful-review

#3586 feat: integrate segment and track page views
  frontend/src/AppRoutes/index.tsx
  frontend/src/index.html.ejs
  frontend/src/typings/window.ts
  frontend/src/utils/segmentAnalytics.ts
  frontend/webpack.config.js
Labels: enhancement, request-more-info

#3576 feat: old logs explorer is now deprecated
  frontend/src/container/LocalTopNav/index.tsx
  frontend/src/container/NewExplorerCTA/config.ts
  frontend/src/container/NewExplorerCTA/index.tsx
  frontend/src/container/SideNav/menuItems.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/config.ts
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
Labels: enhancement, frontend

#3584 fix: add missed variable substitution for promql querires
  pkg/query-service/app/metrics/query_builder.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/parser_test.go
Labels: bug

#3588 Release/v0.29.2
  Makefile
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  ee/query-service/app/api/api.go
  ee/query-service/app/server.go
  ee/query-service/main.go
  frontend/src/AppRoutes/index.tsx
  frontend/src/container/LocalTopNav/index.tsx
  frontend/src/container/LogDetailedView/JsonView.tsx
  frontend/src/container/LogDetailedView/LogDetailedView.types.ts
  frontend/src/container/LogDetailedView/utils.tsx
  frontend/src/container/NewExplorerCTA/config.ts
  frontend/src/container/NewExplorerCTA/index.tsx
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/SideNav/menuItems.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/config.ts
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
  frontend/src/hooks/queryBuilder/useQueryOperations.ts
  frontend/src/index.html.ejs
  frontend/src/types/api/logs/log.ts
  frontend/src/typings/window.ts
  frontend/src/utils/segmentAnalytics.ts
  frontend/webpack.config.js
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metrics/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/parser_test.go
  pkg/query-service/app/querier/helper.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/app/server.go
  pkg/query-service/config/cache-config.yml
  pkg/query-service/interfaces/interface.go
  pkg/query-service/main.go
  pkg/query-service/model/db.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/model/response.go
Labels: request-more-info

#3591 [Refactor]: polished the log UI
  frontend/src/container/LogDetailedView/FieldRenderer.styles.ts
  frontend/src/container/LogDetailedView/FieldRenderer.tsx
Labels: request-more-info

#3594 feat: onboarding flow - add analytics
  frontend/src/AppRoutes/index.tsx
  frontend/src/container/OnboardingContainer/APM/APM.tsx
  frontend/src/container/OnboardingContainer/APM/Java/Java.tsx
  frontend/src/container/OnboardingContainer/APM/Javascript/Javascript.tsx
  frontend/src/container/OnboardingContainer/APM/Python/Python.tsx
  frontend/src/container/OnboardingContainer/APM/common/ConnectionStatus/ConnectionStatus.tsx
  frontend/src/container/OnboardingContainer/LogsManagement/ExistingCollectors/ExistingCollectors.tsx
  frontend/src/container/OnboardingContainer/LogsManagement/LogsManagement.tsx
  frontend/src/container/OnboardingContainer/LogsManagement/common/LogsConnectionStatus/LogsConnectionStatus.tsx
  frontend/src/container/OnboardingContainer/OnboardingContainer.tsx
  frontend/src/utils/segmentAnalytics.ts
Labels: enhancement, request-more-info

#3597 feat: onboarding flow - add analytics - update webpack config
  frontend/webpack.config.prod.js
Labels: enhancement, request-more-info

#3599 update webpack config to add segment ID
  frontend/webpack.config.prod.js
Labels: request-more-info

#3587 QueryBuilder filters for log pipelines
  frontend/jest.config.ts
  frontend/public/locales/en/pipeline.json
  frontend/src/container/PipelinePage/PipelineListsView/AddNewPipeline/FormFields/FilterInput.tsx
  frontend/src/container/PipelinePage/PipelineListsView/AddNewPipeline/FormFields/FilterSearch.tsx
  frontend/src/container/PipelinePage/PipelineListsView/TableComponents/PipelineFilterPreview/index.tsx
  frontend/src/container/PipelinePage/PipelineListsView/TableComponents/PipelineFilterPreview/styles.scss
  frontend/src/container/PipelinePage/PipelineListsView/TableComponents/index.tsx
  frontend/src/container/PipelinePage/PipelineListsView/config.ts
  frontend/src/container/PipelinePage/mocks/pipeline.ts
  frontend/src/container/PipelinePage/tests/AddNewPipeline.test.tsx
  frontend/src/container/PipelinePage/tests/utils.test.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/hooks/queryBuilder/useTag.ts
  frontend/src/types/api/pipeline/def.ts
Labels: logs

#3602 fix: active menu logic is updated
  frontend/src/container/SideNav/menuItems.tsx
Labels: frontend, team-fe-pr

#3609 fix: skip first record only for rate metrics
  pkg/query-service/model/v3/v3.go
  pkg/query-service/rules/thresholdRule.go
Labels: bug

#3612 feat: make identity call if user is logs in for first time or if identity call was not registered
  frontend/src/AppRoutes/index.tsx
  frontend/src/api/utils.ts
  frontend/src/constants/localStorage.ts
  frontend/src/container/Login/index.tsx
Labels: enhancement

#3606 feat: severityText is added
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/container/LogDetailedView/utils.tsx
  frontend/src/types/api/logs/log.ts
Labels: enhancement

#3607 feat: default options is updated
  frontend/src/container/TopNav/DateTimeSelection/config.ts
Labels: enhancement, frontend

#3620 feat: add clarity ms
  frontend/src/AppRoutes/index.tsx
  frontend/src/index.html.ejs
  frontend/src/typings/window.ts
  frontend/webpack.config.js
  frontend/webpack.config.prod.js
Labels: enhancement, request-more-info

#3619 feat: add account creation page events
  frontend/src/pages/SignUp/SignUp.tsx
Labels: enhancement, request-more-info

#3627 docs: update onboarding docs
  frontend/src/container/OnboardingContainer/APM/GoLang/goLang.md
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/java.md
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/jboss.md
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/spring_boot.md
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/tomcat.md
  frontend/src/container/OnboardingContainer/APM/Javascript/Javascript.tsx
  frontend/src/container/OnboardingContainer/APM/Javascript/md-docs/express.md
  frontend/src/container/OnboardingContainer/APM/Javascript/md-docs/javascript.md
  frontend/src/container/OnboardingContainer/APM/Javascript/md-docs/nestjs.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/django.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/falcon.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/fastAPI.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/flask.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/python.md
  frontend/src/container/OnboardingContainer/LogsManagement/ApplicationLogs/applicationLogsFromLogFile.md
  frontend/src/container/OnboardingContainer/LogsManagement/Docker/docker.md
  frontend/src/container/OnboardingContainer/LogsManagement/ExistingCollectors/md-docs/fluentBit.md
  frontend/src/container/OnboardingContainer/LogsManagement/ExistingCollectors/md-docs/fluentD.md
  frontend/src/container/OnboardingContainer/LogsManagement/ExistingCollectors/md-docs/logStash.md
  frontend/src/container/OnboardingContainer/LogsManagement/Kubernetes/kubernetes.md
  frontend/src/container/OnboardingContainer/LogsManagement/LogsManagement.tsx
  frontend/src/container/OnboardingContainer/LogsManagement/SysLogs/syslogs.md
Labels: request-more-info

#3628 feat: ignore prettier formatting for build, coverage and md files
  frontend/.prettierignore
Labels: enhancement, request-more-info

#3634 Onboarding Docs - Copy to clipboard
  frontend/package.json
  frontend/src/components/MarkdownRenderer/CodeCopyBtn/CodeCopyBtn.scss
  frontend/src/components/MarkdownRenderer/CodeCopyBtn/CodeCopyBtn.tsx
  frontend/src/components/MarkdownRenderer/MarkdownRenderer.tsx
  frontend/src/container/OnboardingContainer/APM/GoLang/GoLang.tsx
  frontend/src/container/OnboardingContainer/APM/GoLang/goLang.md
  frontend/src/container/OnboardingContainer/APM/Java/Java.tsx
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/java.md
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/jboss.md
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/spring_boot.md
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/tomcat.md
  frontend/src/container/OnboardingContainer/APM/Javascript/Javascript.tsx
  frontend/src/container/OnboardingContainer/APM/Javascript/md-docs/express.md
  frontend/src/container/OnboardingContainer/APM/Javascript/md-docs/javascript.md
  frontend/src/container/OnboardingContainer/APM/Javascript/md-docs/nestjs.md
  frontend/src/container/OnboardingContainer/APM/Python/Python.tsx
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/django.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/falcon.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/fastAPI.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/flask.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/python.md
  frontend/src/container/OnboardingContainer/InfrastructureMonitoring/InfrastructureMonitoring.tsx
  frontend/src/container/OnboardingContainer/InfrastructureMonitoring/infraMonitoringDocs.md
  frontend/src/container/OnboardingContainer/LogsManagement/ApplicationLogs/ApplicationLogs.tsx
  frontend/src/container/OnboardingContainer/LogsManagement/ApplicationLogs/applicationLogsUsingJavaOtelSDK.md
  frontend/src/container/OnboardingContainer/LogsManagement/Docker/Docker.tsx
  frontend/src/container/OnboardingContainer/LogsManagement/Docker/docker.md
  frontend/src/container/OnboardingContainer/LogsManagement/ExistingCollectors/ExistingCollectors.tsx
  frontend/src/container/OnboardingContainer/LogsManagement/Kubernetes/Kubernetes.tsx
  frontend/src/container/OnboardingContainer/LogsManagement/LogsManagement.tsx
  frontend/src/container/OnboardingContainer/LogsManagement/Nodejs/Nodejs.tsx
  frontend/src/container/OnboardingContainer/LogsManagement/SysLogs/SysLogs.tsx
  frontend/webpack.config.js
  frontend/yarn.lock
Labels: request-more-info

#3637 feat: updated infra docs
  frontend/src/container/OnboardingContainer/APM/GoLang/goLang.md
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/java.md
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/jboss.md
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/spring_boot.md
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/tomcat.md
  frontend/src/container/OnboardingContainer/APM/Javascript/md-docs/express.md
  frontend/src/container/OnboardingContainer/APM/Javascript/md-docs/javascript.md
  frontend/src/container/OnboardingContainer/APM/Javascript/md-docs/nestjs.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/django.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/falcon.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/fastAPI.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/flask.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/python.md
  frontend/src/container/OnboardingContainer/InfrastructureMonitoring/InfrastructureMonitoring.styles.scss
  frontend/src/container/OnboardingContainer/InfrastructureMonitoring/InfrastructureMonitoring.tsx
  frontend/src/container/OnboardingContainer/InfrastructureMonitoring/md-docs/hostMetricsMonitoring.md
  frontend/src/container/OnboardingContainer/InfrastructureMonitoring/md-docs/kubernetesInfraMonitoring.md
  frontend/src/container/OnboardingContainer/InfrastructureMonitoring/md-docs/otherMetrics.md
  frontend/src/container/OnboardingContainer/OnboardingContainer.tsx
Labels: enhancement, request-more-info

#3639 chore: error details stack trace height is updated
  frontend/src/container/ErrorDetails/index.tsx
  frontend/src/container/ErrorDetails/styles.scss
Labels: frontend, chore

#3613 fix: alert eval for "="/"!=" combination with "at least once"/"all th…
  Makefile
  go.mod
  go.sum
  pkg/query-service/rules/thresholdRule.go
  pkg/query-service/rules/thresholdRule_test.go
Labels: bug

#3649 fix: limit issue fixed when using contains
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/app/querier/helper.go
Labels: bug, request-more-info
