Repository SigNoz/signoz, pull requests merged in 2023-10, with the labels that each got.

#3567 feat: has and nhas filters is now enabled
  frontend/src/container/LogDetailedView/config.ts
  frontend/src/container/LogDetailedView/util.test.ts
  frontend/src/container/LogDetailedView/utils.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
Labels: enhancement, frontend

#3669 fix: navigate to new logs-explorer page for log based alerts
  frontend/src/container/CreateAlertRule/defaults.ts
Labels: bug, frontend, testing-deploy

#3674 feat: update analytics endpoints
  frontend/src/index.html.ejs
Labels: enhancement, request-more-info

#3675 fix: exists check for json filters added
  pkg/query-service/app/logs/v3/json_filter.go
  pkg/query-service/app/logs/v3/json_filter_test.go
  pkg/query-service/app/logs/v3/query_builder_test.go
Labels: bug

#3657 feat: lowercase operators support in the where clause is updated
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/utils.ts
  frontend/src/hooks/queryBuilder/useAutoComplete.ts
  frontend/src/hooks/queryBuilder/useOperatorType.ts
  frontend/src/hooks/queryBuilder/useOptions.ts
  frontend/src/hooks/queryBuilder/useSetCurrentKeyAndOperator.ts
  frontend/src/hooks/queryBuilder/useTag.ts
Labels: enhancement, frontend

#3658 perf(query-service): :hammer: improve backend build time
  Makefile
  deploy/docker/clickhouse-setup/docker-compose-local.yaml
  ee/query-service/Dockerfile
  pkg/query-service/Dockerfile
Labels: query-service, performance

#3686 chore(query-service): 🔧 update workflows and build files as per Docker optimizations
  .github/workflows/push.yaml
  .github/workflows/staging-deployment.yaml
  .github/workflows/testing-deployment.yaml
  Makefile
  ee/query-service/Dockerfile
Labels: chore

#3304 refactor: Added new props to GetMetricQueryRange to control Step from without global time range.
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/FormAlertRules/utils.test.ts
  frontend/src/container/FormAlertRules/utils.ts
  frontend/src/lib/dashboard/prepareQueryRangePayload.ts
Labels: frontend, team-fe-pr

#3699 feat: ingestion key management
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/ingestion_key.go
  pkg/query-service/app/parser.go
  pkg/query-service/dao/interface.go
  pkg/query-service/dao/sqlite/connection.go
  pkg/query-service/dao/sqlite/ingestion.go
  pkg/query-service/model/db.go
Labels: enhancement

#3703 chore: do not allow deleting more than one panel on update request
  pkg/query-service/app/dashboards/model.go
Labels: chore

#3667 feat: hoc to support markdown content with variable interpolation
  frontend/public/locales/en-GB/routes.json
  frontend/public/locales/en-GB/titles.json
  frontend/public/locales/en/routes.json
  frontend/public/locales/en/titles.json
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/api/settings/getIngestionData.ts
  frontend/src/components/MarkdownRenderer/MarkdownRenderer.tsx
  frontend/src/constants/routes.ts
  frontend/src/container/IngestionSettings/IngestionSettings.styles.scss
  frontend/src/container/IngestionSettings/IngestionSettings.tsx
  frontend/src/container/OnboardingContainer/APM/APM.tsx
  frontend/src/container/OnboardingContainer/APM/GoLang/GoLang.tsx
  frontend/src/container/OnboardingContainer/APM/GoLang/goLang.md
  frontend/src/container/OnboardingContainer/APM/Java/Java.tsx
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/java.md
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/jboss.md
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/spring_boot.md
  frontend/src/container/OnboardingContainer/APM/Java/md-docs/tomcat.md
  frontend/src/container/OnboardingContainer/APM/Javascript/Javascript.tsx
  frontend/src/container/OnboardingContainer/APM/Javascript/md-docs/express.md
  frontend/src/container/OnboardingContainer/APM/Javascript/md-docs/javascript.md
  frontend/src/container/OnboardingContainer/APM/Javascript/md-docs/nestjs.md
  frontend/src/container/OnboardingContainer/APM/Python/Python.tsx
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/django.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/falcon.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/fastAPI.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/flask.md
  frontend/src/container/OnboardingContainer/APM/Python/md-docs/python.md
  frontend/src/container/TopNav/Breadcrumbs/index.tsx
  frontend/src/container/TopNav/DateTimeSelection/config.ts
  frontend/src/pages/Settings/config.ts
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/types/api/settings/ingestion.ts
  frontend/src/utils/permission/index.ts
Labels: enhancement, request-more-info

#3697 Revert "feat: lowercase operators support in the where clause is updated"
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/utils.ts
  frontend/src/hooks/queryBuilder/useAutoComplete.ts
  frontend/src/hooks/queryBuilder/useOperatorType.ts
  frontend/src/hooks/queryBuilder/useOptions.ts
  frontend/src/hooks/queryBuilder/useSetCurrentKeyAndOperator.ts
  frontend/src/hooks/queryBuilder/useTag.ts
Labels: enhancement

#3704 chore: add billing api resources
  ee/query-service/app/api/api.go
  ee/query-service/app/api/license.go
  ee/query-service/app/server.go
  ee/query-service/constants/constants.go
  ee/query-service/model/license.go
Labels: chore, request-more-info

#3716 fix: limit for time series is updated
  frontend/src/lib/getChartData.ts
  frontend/webpack.config.js
  frontend/webpack.config.prod.js
Labels: bug, request-more-info

#3718 fix: dashboard context is updated when we update the layout
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
Labels: bug, request-more-info

#3715 fix: query key is updated
  frontend/src/container/GridCardLayout/GridCard/index.tsx
Labels: bug

#3730 feat: limit is updated for chart data
  frontend/src/container/GridCardLayout/WidgetHeader/config.ts
  frontend/src/lib/getChartData.ts
  frontend/webpack.config.js
  frontend/webpack.config.prod.js
Labels: enhancement, request-more-info

#3743 Release/v0.31.1
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  frontend/src/container/LogDetailedView/TableView.tsx
Labels: testing-deploy

#3711 Billing UI
  ee/query-service/app/api/license.go
  ee/query-service/model/license.go
  frontend/public/Images/notFound404.png
  frontend/public/locales/en-GB/titles.json
  frontend/public/locales/en/titles.json
  frontend/src/AppRoutes/Private.tsx
  frontend/src/AppRoutes/index.tsx
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/api/billing/checkout.ts
  frontend/src/api/billing/getUsage.ts
  frontend/src/api/dashboard/create.ts
  frontend/src/api/licenses/getAll.ts
  frontend/src/assets/NotFound.tsx
  frontend/src/components/NotFound/__snapshots__/NotFound.test.tsx.snap
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/constants/routes.ts
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/BillingContainer/BillingContainer.styles.scss
  frontend/src/container/BillingContainer/BillingContainer.tsx
  frontend/src/container/Header/Header.styles.scss
  frontend/src/container/Header/ManageLicense/index.tsx
  frontend/src/container/Header/index.tsx
  frontend/src/container/Licenses/ListLicenses.tsx
  frontend/src/container/Licenses/index.tsx
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/container/SideNav/config.ts
  frontend/src/container/SideNav/menuItems.tsx
  frontend/src/container/TopNav/Breadcrumbs/index.tsx
  frontend/src/container/TopNav/DateTimeSelection/config.ts
  frontend/src/hooks/useLicense/constant.ts
  frontend/src/hooks/useUsage/useUsage.tsx
  frontend/src/pages/Billing/BillingPage.styles.scss
  frontend/src/pages/Billing/BillingPage.tsx
  frontend/src/pages/Billing/index.tsx
  frontend/src/pages/WorkspaceLocked/WorkspaceLocked.styles.scss
  frontend/src/pages/WorkspaceLocked/WorkspaceLocked.tsx
  frontend/src/pages/WorkspaceLocked/index.tsx
  frontend/src/types/api/billing/checkout.ts
  frontend/src/types/api/licenses/getAll.ts
  frontend/src/utils/permission/index.ts
Labels: request-more-info

#3735 chore: update query service telemetry
  ee/query-service/app/server.go
  ee/query-service/constants/constants.go
  pkg/query-service/app/server.go
  pkg/query-service/dao/sqlite/connection.go
  pkg/query-service/telemetry/ignored.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#3757 feat: add analytics group call
  frontend/src/AppRoutes/index.tsx
  frontend/src/container/BillingContainer/BillingContainer.tsx
  frontend/src/container/IngestionSettings/IngestionSettings.tsx
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/pages/Settings/config.ts
  frontend/src/pages/Settings/utils.ts
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/utils/app.ts
Labels: enhancement, request-more-info

#3754 feat: add created{By,At} , updated{By,At} to alerts/dashboards
  pkg/query-service/app/auth.go
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/dashboards/provision.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/common/user.go
  pkg/query-service/constants/constants.go
  pkg/query-service/rules/apiParams.go
  pkg/query-service/rules/db.go
  pkg/query-service/rules/manager.go
Labels: enhancement

#3764 fix: nil pointer dereference in query builder expression
  pkg/query-service/app/queryBuilder/query_builder.go
Labels: bug, request-more-info

#3766 Update CODEOWNERS
  .github/CODEOWNERS
Labels: request-more-info

#3759 fix: update version check login and other minor UI fixes
  frontend/src/container/BillingContainer/BillingContainer.tsx
  frontend/src/container/Header/index.tsx
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/container/Version/index.tsx
  frontend/src/pages/WorkspaceLocked/WorkspaceLocked.tsx
  frontend/src/utils/app.ts
  frontend/src/utils/timeUtils.ts
Labels: bug, request-more-info

#3713 query-service: add cluster name cli flag
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose-core.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  ee/query-service/app/db/reader.go
  ee/query-service/app/server.go
  ee/query-service/main.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/server.go
  pkg/query-service/main.go
  pkg/query-service/tests/test-deploy/docker-compose.yaml
Labels: request-more-info, testing-deploy

#3780 chore: update logs/traces retention to 15days
  deploy/install.sh
Labels: chore, request-more-info

#3779 fix: warinng is now limited when timeseries panel is in widget
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraph.tsx
Labels: bug, frontend

#3781 Added unit test case for billing and workspaceLock compnent.
  frontend/package.json
  frontend/src/container/BillingContainer/BillingContainer.test.tsx
  frontend/src/mocks-server/__mockdata__/billing.ts
  frontend/src/mocks-server/__mockdata__/licenses.ts
  frontend/src/mocks-server/handlers.ts
  frontend/src/pages/WorkspaceLocked/WorkspaceLocked.test.tsx
  frontend/src/tests/test-utils.tsx
  frontend/yarn.lock
Labels: request-more-info

#3784 fix: promql alert expr formatting for composite queries with join/unless
  pkg/query-service/rules/promRule.go
Labels: bug

#3801 Release/v0.32.1
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose-core.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  frontend/package.json
  frontend/src/container/BillingContainer/BillingContainer.test.tsx
  frontend/src/container/BillingContainer/BillingContainer.tsx
  frontend/src/container/Header/index.tsx
  frontend/src/container/PipelinePage/PipelineListsView/index.tsx
  frontend/src/lib/getChartData.ts
  frontend/src/mocks-server/__mockdata__/billing.ts
  frontend/src/mocks-server/__mockdata__/licenses.ts
  frontend/src/mocks-server/handlers.ts
  frontend/src/pages/Services/Metrics.test.tsx
  frontend/src/pages/WorkspaceLocked/WorkspaceLocked.test.tsx
  frontend/src/tests/test-utils.tsx
  frontend/src/utils/timeUtils.ts
  frontend/yarn.lock
  pkg/query-service/rules/promRule.go
  pkg/query-service/tests/test-deploy/docker-compose.yaml
Labels: testing-deploy

#3804 feat: sanitize identity payload and pass source to identity and group …
  frontend/src/AppRoutes/index.tsx
Labels: enhancement

#3807 fix: update logic to conditionally show Get Started and Billing routes
  frontend/src/AppRoutes/Private.tsx
  frontend/src/AppRoutes/routes.ts
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/hooks/useLicense/constant.ts
  frontend/src/mocks-server/__mockdata__/licenses.ts
  frontend/src/pages/WorkspaceLocked/WorkspaceLocked.test.tsx
  frontend/src/pages/WorkspaceLocked/WorkspaceLocked.tsx
  frontend/src/types/roles.ts
Labels: bug, request-more-info

#3823 feat: create tooltip plugin for uplot charts
  frontend/src/components/Uplot/Uplot.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/globalStyles.ts
  frontend/src/lib/getUplotChartData.ts
  frontend/src/lib/uPlotLib/placement.ts
Labels: enhancement, request-more-info

#3817 feat: uplot points is handled
  frontend/src/components/Graph/yAxisConfig.ts
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCard/types.ts
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
  frontend/src/hooks/useDimensions.ts
  frontend/src/lib/getUplotChartData.ts
Labels: enhancement, frontend

#3822 Fix: get log pipelines trace parser working
  frontend/src/container/PipelinePage/PipelineListsView/AddNewPipeline/FormFields/DescriptionTextArea.tsx
  frontend/src/container/PipelinePage/PipelineListsView/AddNewPipeline/FormFields/NameInput.tsx
  frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/FormFields/NameInput.tsx
  frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/FormFields/ParsingRulesTextArea.tsx
  frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/config.ts
  frontend/src/container/PipelinePage/PipelineListsView/Preview/components/LogsList/styles.scss
  frontend/src/types/api/pipeline/def.ts
Labels: bug

#3782 feat: default trace_parser updated
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
Labels: enhancement

#3839 feat: fix dashboard title section and other uplot parity issues
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/NewDashboard/DashboardSettings/General/AddTags/index.tsx
  frontend/src/container/NewDashboard/DashboardSettings/General/index.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/index.tsx
  frontend/src/container/NewDashboard/DescriptionOfDashboard/Description.styles.scss
  frontend/src/container/NewDashboard/DescriptionOfDashboard/SettingsDrawer.tsx
  frontend/src/container/NewDashboard/DescriptionOfDashboard/ShareModal.tsx
  frontend/src/container/NewDashboard/DescriptionOfDashboard/index.tsx
  frontend/src/container/NewDashboard/DescriptionOfDashboard/styles.ts
  frontend/src/globalStyles.ts
  frontend/src/index.tsx
  frontend/src/lib/getUplotChartData.ts
  frontend/src/styles.scss
Labels: bug, enhancement, request-more-info

#3838 Fix: Log pipelines deployment status unknown
  frontend/src/container/PipelinePage/Layouts/ChangeHistory/utils.tsx
  frontend/src/container/PipelinePage/PipelineListsView/index.tsx
Labels: bug

#3844 [Fix]: added the darktheme support for Action Column in Alerts Listing Table.
  frontend/src/components/DropDown/DropDown.styles.scss
  frontend/src/components/DropDown/DropDown.tsx
Labels: bug

#3853 fix: 404 on clicking version menu item in side nav
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/container/Version/index.tsx
Labels: bug, request-more-info
