Repository SigNoz/signoz, pull requests merged in 2023-04, with the labels that each got.

#2516 feat(builder): add aggregator filter
  frontend/src/api/apiV1.ts
  frontend/src/api/index.ts
  frontend/src/api/queryBuilder/getAggregateAttribute.ts
  frontend/src/api/queryBuilder/getAttributeKeys.ts
  frontend/src/constants/useQueryKeys.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/QueryBuilder/QueryBuilder.interfaces.ts
  frontend/src/container/QueryBuilder/QueryBuilder.tsx
  frontend/src/container/QueryBuilder/components/DataSourceDropdown/DataSourceDropdown.interfaces.ts
  frontend/src/container/QueryBuilder/components/DataSourceDropdown/DataSourceDropdown.tsx
  frontend/src/container/QueryBuilder/components/DataSourceDropdown/index.ts
  frontend/src/container/QueryBuilder/components/FilterLabel/FilterLabel.interfaces.ts
  frontend/src/container/QueryBuilder/components/FilterLabel/FilterLabel.styled.ts
  frontend/src/container/QueryBuilder/components/FilterLabel/FilterLabel.tsx
  frontend/src/container/QueryBuilder/components/FilterLabel/index.ts
  frontend/src/container/QueryBuilder/components/Formula/Formula.interfaces.ts
  frontend/src/container/QueryBuilder/components/Formula/Formula.tsx
  frontend/src/container/QueryBuilder/components/Formula/index.ts
  frontend/src/container/QueryBuilder/components/ListMarker/ListMarker.interfaces.ts
  frontend/src/container/QueryBuilder/components/ListMarker/ListMarker.tsx
  frontend/src/container/QueryBuilder/components/Query/Query.interfaces.ts
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/components/Query/index.ts
  frontend/src/container/QueryBuilder/components/QueryLabel/QueryLabel.interfaces.ts
  frontend/src/container/QueryBuilder/components/QueryLabel/QueryLabel.styled.ts
  frontend/src/container/QueryBuilder/components/QueryLabel/QueryLabel.tsx
  frontend/src/container/QueryBuilder/components/QueryLabel/index.ts
  frontend/src/container/QueryBuilder/components/index.ts
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.intefaces.ts
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/index.ts
  frontend/src/container/QueryBuilder/filters/OperatorsSelect/OperatorsSelect.interfaces.ts
  frontend/src/container/QueryBuilder/filters/OperatorsSelect/OperatorsSelect.tsx
  frontend/src/container/QueryBuilder/filters/OperatorsSelect/index.ts
  frontend/src/container/QueryBuilder/filters/index.ts
  frontend/src/hooks/useQueryBuilder.ts
  frontend/src/lib/query/transformStringWithPrefix.ts
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/types/api/queryBuilder/getAggregatorAttribute.ts
  frontend/src/types/api/queryBuilder/getAttributeKeys.ts
  frontend/src/types/api/queryBuilder/queryAutocompleteResponse.ts
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
  frontend/src/types/common/queryBuilder.ts
  frontend/src/utils/transformToUpperCase.ts
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2533 fix: global time navigation is fixed
  frontend/src/container/SideNav/index.tsx
Labels: bug, ok-to-test, request-more-info, codeball:approved, testing-deploy

#2534 fix: 2427 latency graph onclick is updated
  frontend/src/container/MetricsApplication/Tabs/util.ts
Labels: bug, codeball:approved

#2537 fix: slider duration is fixed
  frontend/src/container/Trace/Filters/Panel/PanelBody/Duration/index.tsx
Labels: bug, frontend, codeball:approved

#2539 Release/v0.18.1
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  frontend/src/api/apiV1.ts
  frontend/src/api/index.ts
  frontend/src/api/queryBuilder/getAggregateAttribute.ts
  frontend/src/api/queryBuilder/getAttributeKeys.ts
  frontend/src/constants/useQueryKeys.ts
  frontend/src/container/MetricsApplication/Tabs/util.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/QueryBuilder/QueryBuilder.interfaces.ts
  frontend/src/container/QueryBuilder/QueryBuilder.tsx
  frontend/src/container/QueryBuilder/components/DataSourceDropdown/DataSourceDropdown.interfaces.ts
  frontend/src/container/QueryBuilder/components/DataSourceDropdown/DataSourceDropdown.tsx
  frontend/src/container/QueryBuilder/components/DataSourceDropdown/index.ts
  frontend/src/container/QueryBuilder/components/FilterLabel/FilterLabel.interfaces.ts
  frontend/src/container/QueryBuilder/components/FilterLabel/FilterLabel.styled.ts
  frontend/src/container/QueryBuilder/components/FilterLabel/FilterLabel.tsx
  frontend/src/container/QueryBuilder/components/FilterLabel/index.ts
  frontend/src/container/QueryBuilder/components/Formula/Formula.interfaces.ts
  frontend/src/container/QueryBuilder/components/Formula/Formula.tsx
  frontend/src/container/QueryBuilder/components/Formula/index.ts
  frontend/src/container/QueryBuilder/components/ListMarker/ListMarker.interfaces.ts
  frontend/src/container/QueryBuilder/components/ListMarker/ListMarker.tsx
  frontend/src/container/QueryBuilder/components/Query/Query.interfaces.ts
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/components/Query/index.ts
  frontend/src/container/QueryBuilder/components/QueryLabel/QueryLabel.interfaces.ts
  frontend/src/container/QueryBuilder/components/QueryLabel/QueryLabel.styled.ts
  frontend/src/container/QueryBuilder/components/QueryLabel/QueryLabel.tsx
  frontend/src/container/QueryBuilder/components/QueryLabel/index.ts
  frontend/src/container/QueryBuilder/components/index.ts
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.intefaces.ts
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/index.ts
  frontend/src/container/QueryBuilder/filters/OperatorsSelect/OperatorsSelect.interfaces.ts
  frontend/src/container/QueryBuilder/filters/OperatorsSelect/OperatorsSelect.tsx
  frontend/src/container/QueryBuilder/filters/OperatorsSelect/index.ts
  frontend/src/container/QueryBuilder/filters/index.ts
  frontend/src/container/SideNav/index.tsx
  frontend/src/container/Trace/Filters/Panel/PanelBody/Duration/index.tsx
  frontend/src/hooks/useQueryBuilder.ts
  frontend/src/lib/query/transformStringWithPrefix.ts
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/types/api/queryBuilder/getAggregatorAttribute.ts
  frontend/src/types/api/queryBuilder/getAttributeKeys.ts
  frontend/src/types/api/queryBuilder/queryAutocompleteResponse.ts
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
  frontend/src/types/common/queryBuilder.ts
  frontend/src/utils/transformToUpperCase.ts
Labels: codeball:needs-careful-review

#2547 fix: cursor pointer is removed the table view
  frontend/src/components/Logs/TableView/styles.ts
Labels: bug, codeball:approved

#2504 chore: set Cache-Control for auto complete requests
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/http_utils.go
Labels: chore, codeball:needs-careful-review

#2538 feat(filter): add group by filter
  frontend/src/api/queryBuilder/getAttributeKeys.ts
  frontend/src/constants/useQueryKeys.ts
  frontend/src/container/QueryBuilder/components/FilterLabel/FilterLabel.styled.ts
  frontend/src/container/QueryBuilder/components/ListMarker/ListMarker.styled.ts
  frontend/src/container/QueryBuilder/components/ListMarker/ListMarker.tsx
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.intefaces.ts
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.interfaces.ts
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
  frontend/src/container/QueryBuilder/filters/GroupByFilter/index.ts
  frontend/src/container/QueryBuilder/filters/OperatorsSelect/OperatorsSelect.tsx
  frontend/src/container/QueryBuilder/filters/index.ts
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/types/api/queryBuilder/getAttributeKeys.ts
  frontend/src/types/api/queryBuilder/queryAutocompleteResponse.ts
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
Labels: enhancement, dashboards, query-builder, codeball:needs-careful-review

#2404 feat(logs): add tag attribute autocomplete for logs
  pkg/query-service/app/clickhouseReader/options.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/parser.go
  pkg/query-service/constants/constants.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/v3/v3.go
Labels: enhancement, codeball:needs-careful-review

#2542 fix: minor issues found in development and enhancements
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/app/query_builder.go
  pkg/query-service/app/query_builder_test.go
  pkg/query-service/model/v3/v3.go
Labels: bug, codeball:needs-careful-review

#2528 fix: remove frontend code owner
  .github/CODEOWNERS
Labels: enhancement

#2549 feat(builder): add additional filter toggler
  frontend/src/constants/queryBuilder.ts
  frontend/src/constants/useQueryKeys.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/QueryBuilder/QueryBuilder.interfaces.ts
  frontend/src/container/QueryBuilder/QueryBuilder.tsx
  frontend/src/container/QueryBuilder/components/AdditionalFiltersToggler/AdditionalFiltersToggler.interfaces.ts
  frontend/src/container/QueryBuilder/components/AdditionalFiltersToggler/AdditionalFiltersToggler.styled.ts
  frontend/src/container/QueryBuilder/components/AdditionalFiltersToggler/AdditionalFiltersToggler.tsx
  frontend/src/container/QueryBuilder/components/AdditionalFiltersToggler/index.ts
  frontend/src/container/QueryBuilder/components/DataSourceDropdown/DataSourceDropdown.tsx
  frontend/src/container/QueryBuilder/components/FilterLabel/FilterLabel.styled.ts
  frontend/src/container/QueryBuilder/components/FilterLabel/FilterLabel.tsx
  frontend/src/container/QueryBuilder/components/ListMarker/ListMarker.styled.ts
  frontend/src/container/QueryBuilder/components/ListMarker/ListMarker.tsx
  frontend/src/container/QueryBuilder/components/Query/Query.interfaces.ts
  frontend/src/container/QueryBuilder/components/Query/Query.styled.ts
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/components/index.ts
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
  frontend/src/container/QueryBuilder/filters/OperatorsSelect/OperatorsSelect.tsx
  frontend/src/container/QueryBuilder/filters/ReduceToFilter/ReduceToFilter.interfaces.ts
  frontend/src/container/QueryBuilder/filters/ReduceToFilter/ReduceToFilter.tsx
  frontend/src/container/QueryBuilder/filters/ReduceToFilter/index.ts
  frontend/src/container/QueryBuilder/filters/index.ts
  frontend/src/lib/newQueryBuilder/createNewFormulaName.ts
  frontend/src/lib/newQueryBuilder/createNewQueryName.ts
  frontend/src/lib/query/findDataTypeOfOperator.ts
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/types/api/queryBuilder/queryAutocompleteResponse.ts
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
  frontend/src/types/common/queryBuilder.ts
Labels: enhancement, frontend, query-builder, codeball:needs-careful-review

#2560 feat: signoz ui color hex support is added
  frontend/src/lib/__fixtures__/getRandomColor.ts
  frontend/src/lib/getRandomColor.test.ts
  frontend/src/lib/getRandomColor.ts
Labels: enhancement, codeball:approved

#2554 test: metrics table test case is added
  frontend/jest.setup.ts
  frontend/src/container/MetricsTable/Metrics.test.tsx
  frontend/src/store/reducers/metric.ts
Labels: frontend, test, request-more-info, codeball:needs-careful-review

#2564 feat: custom time frame is updated
  frontend/src/container/TopNav/CustomDateTimeModal/CustomDateTimeModal.test.tsx
  frontend/src/container/TopNav/CustomDateTimeModal/index.tsx
Labels: enhancement, codeball:needs-careful-review

#2563 fix: max depth issue is fixed in dashboard
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
Labels: bug, request-more-info, codeball:approved

#2414 Add Span attributes APIs
  pkg/query-service/app/clickhouseReader/options.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/v3/v3.go
Labels: request-more-info, codeball:needs-careful-review

#2517 feat: Search bar for Query Builder
  frontend/src/api/queryBuilder/getAttributesKeysValues.ts
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/NewWidget/styles.ts
  frontend/src/container/QueryBuilder/components/ListMarker/ListMarker.styled.ts
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/config.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/style.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/utils.ts
  frontend/src/container/QueryBuilder/type.ts
  frontend/src/hooks/queryBuilder/useAutoComplete.ts
  frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
  frontend/src/hooks/queryBuilder/useIsValidTag.ts
  frontend/src/hooks/queryBuilder/useOperatorType.ts
  frontend/src/hooks/queryBuilder/useOperators.ts
  frontend/src/hooks/queryBuilder/useOptions.ts
  frontend/src/hooks/queryBuilder/useSetCurrentKeyAndOperator.ts
  frontend/src/hooks/queryBuilder/useTag.ts
  frontend/src/hooks/queryBuilder/useTagValidation.ts
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/utils/checkStringEndsWithSpace.ts
  frontend/src/utils/getCountOfSpace.ts
  frontend/src/utils/getSearchParams.ts
  frontend/src/utils/separateSearchValue.ts
Labels: frontend, query-builder

#2561 feat: Limt filter for QB
  frontend/src/container/QueryBuilder/components/AdditionalFiltersToggler/AdditionalFiltersToggler.tsx
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/filters/LimitFilter/LimitFilter.tsx
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
Labels: frontend, query-builder

#2288 chore: 🔧 remove resource requests/limits from sample apps
  sample-apps/hotrod/hotrod-template.yaml
  sample-apps/hotrod/hotrod.yaml
Labels: chore, codeball:needs-careful-review

#2451 chore: 🔧 update install and troubleshooting guide url
  README.de-de.md
  README.md
  README.pt-br.md
  README.zh-cn.md
  deploy/install.sh
Labels: chore, codeball:needs-careful-review

#2580 fix: tag filters query missing on page reload
  frontend/src/container/Trace/Search/index.tsx
Labels: bug, frontend, traces

#2581 feat: added aggregate every filter
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/filters/AggregateEveryFilter/index.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/style.ts
Labels: frontend, query-builder

#2584 fix: add support for count aggregate attribute
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug, request-more-info

#2567 feat(builder): add having filter
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/QueryBuilder/QueryBuilder.tsx
  frontend/src/container/QueryBuilder/components/AdditionalFiltersToggler/AdditionalFiltersToggler.styled.ts
  frontend/src/container/QueryBuilder/components/AdditionalFiltersToggler/AdditionalFiltersToggler.tsx
  frontend/src/container/QueryBuilder/components/FilterLabel/FilterLabel.styled.ts
  frontend/src/container/QueryBuilder/components/Formula/Formula.interfaces.ts
  frontend/src/container/QueryBuilder/components/Formula/Formula.tsx
  frontend/src/container/QueryBuilder/components/ListItemWrapper/ListItemWrapper.interfaces.ts
  frontend/src/container/QueryBuilder/components/ListItemWrapper/ListItemWrapper.styled.ts
  frontend/src/container/QueryBuilder/components/ListItemWrapper/ListItemWrapper.tsx
  frontend/src/container/QueryBuilder/components/ListItemWrapper/index.ts
  frontend/src/container/QueryBuilder/components/ListMarker/ListMarker.interfaces.ts
  frontend/src/container/QueryBuilder/components/ListMarker/ListMarker.tsx
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/components/index.ts
  frontend/src/container/QueryBuilder/filters/HavingFilter/HavingFilter.interfaces.ts
  frontend/src/container/QueryBuilder/filters/HavingFilter/HavingFilter.tsx
  frontend/src/container/QueryBuilder/filters/HavingFilter/__tests__/utils.test.tsx
  frontend/src/container/QueryBuilder/filters/HavingFilter/index.ts
  frontend/src/container/QueryBuilder/filters/index.ts
  frontend/src/lib/newQueryBuilder/createNewBuilderItemName.ts
  frontend/src/lib/newQueryBuilder/createNewFormulaName.ts
  frontend/src/lib/newQueryBuilder/createNewQueryName.ts
  frontend/src/lib/query/transformQueryBuilderData.ts
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
  frontend/src/types/common/queryBuilder.ts
Labels: enhancement, codeball:needs-careful-review

#2595 fix: propswithchildren is removed
  frontend/src/container/QueryBuilder/components/AdditionalFiltersToggler/AdditionalFiltersToggler.interfaces.ts
  frontend/src/container/QueryBuilder/components/ListItemWrapper/ListItemWrapper.interfaces.ts
  frontend/src/providers/QueryBuilder.tsx
Labels: bug, request-more-info, codeball:approved

#2590 fix: edit tag chip for WHERE clause updated logic
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/style.ts
  frontend/src/hooks/queryBuilder/useAutoComplete.ts
  frontend/src/hooks/queryBuilder/useTag.ts
Labels: bug, frontend, query-builder, codeball:needs-careful-review

#2544 fix: clear filter is fixed
  frontend/src/container/LogsSearchFilter/SearchFields/ActionBar.tsx
  frontend/src/container/LogsSearchFilter/SearchFields/index.tsx
  frontend/src/container/LogsSearchFilter/index.tsx
  frontend/src/container/LogsSearchFilter/useSearchParser.ts
Labels: bug, codeball:needs-careful-review

#2553 feat: resource attribute query is shared in the app navigation from sidebar
  frontend/src/constants/query.ts
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/Tabs/util.ts
  frontend/src/container/MetricsApplication/TopOperationsTable.tsx
  frontend/src/container/MetricsTable/index.tsx
  frontend/src/container/SideNav/config.ts
  frontend/src/container/SideNav/helper.test.ts
  frontend/src/container/SideNav/helper.ts
  frontend/src/container/SideNav/index.tsx
Labels: enhancement, codeball:needs-careful-review

#2609 fix: remove log lines which doesn't contain the key while performing …
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
Labels: bug

#2610 chore: validateAndCastValueData
  pkg/query-service/utils/format.go
  pkg/query-service/utils/format_test.go
Labels: chore, request-more-info, codeball:needs-careful-review

#2605 feat(docker): ✨ support for Google Cloud Storage (GCS)
  deploy/docker-swarm/clickhouse-setup/clickhouse-storage.xml
  deploy/docker/clickhouse-setup/clickhouse-storage.xml
Labels: enhancement, codeball:needs-careful-review

#2619 fix: Only positive integer values should be allowed for limit
  frontend/src/container/QueryBuilder/filters/LimitFilter/LimitFilter.tsx
Labels: frontend, query-builder

#2512 chore: update pr_verify_linked_issue workflow
  .github/workflows/pr_verify_linked_issue.yml
Labels: chore, codeball:needs-careful-review

#2626 fix: Order By filter feedback on new QB
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/filters/OrderByFilter/OrderByFilter.tsx
Labels: frontend, query-builder

#2571 feat: traces QB
  pkg/query-service/app/clickhouseReader/options.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/query_builder.go
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/app/traces/v3/query_builder_test.go
  pkg/query-service/constants/constants.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/v3/v3.go
  pkg/query-service/utils/format.go
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2633 fix: dashboard variable is fixed
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
Labels: bug, request-more-info, codeball:needs-careful-review

#2636 feat: add errorCount in top_operations API
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/model/response.go
Labels: enhancement, codeball:needs-careful-review

#2617 fix: update default PagerDuty message
  frontend/src/container/CreateAlertChannels/defaults.ts
Labels: bug, codeball:needs-careful-review

#2638 feat: error rate is added
  frontend/src/container/MetricsApplication/TopOperationsTable.tsx
  frontend/src/types/actions/metrics.ts
  frontend/src/types/api/metrics/getTopOperations.ts
  frontend/src/types/reducer/metrics.ts
Labels: enhancement, codeball:needs-careful-review
