Repository SigNoz/signoz, pull requests merged in 2023-08, with the labels that each got.

#3211 feat: usage exporter logic updated
  ee/query-service/app/server.go
  ee/query-service/main.go
  ee/query-service/usage/manager.go
  go.mod
  go.sum
Labels: enhancement

#3236 fix: the flickering issue of trace graph
  frontend/src/container/Trace/Graph/styles.ts
Labels: request-more-info

#3248 feat: getPaginationQueryData is updated
  frontend/src/lib/newQueryBuilder/getPaginationQueryData.ts
Labels: enhancement

#3252 fix: position style is updated for tooltip
  frontend/src/container/GridGraphLayout/WidgetHeader/config.ts
Labels: bug

#3250 Refactor: Created utility for generating columns for `ResizeTable`
  frontend/src/components/TableRenderer/utils.ts
  frontend/src/container/ServiceApplication/Columns/BaseColumnOptions.ts
  frontend/src/container/ServiceApplication/Columns/ServiceColumn.ts
Labels: request-more-info

#3039 Improved graph panel full view
  frontend/package.json
  frontend/src/components/Graph/Plugin/Legend.ts
  frontend/src/components/Graph/index.tsx
  frontend/src/components/Graph/types.ts
  frontend/src/components/Graph/utils.ts
  frontend/src/components/Graph/xAxisConfig.ts
  frontend/src/constants/events.ts
  frontend/src/constants/localStorage.ts
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/GridGraphLayout/Graph/FullView/GraphManager.tsx
  frontend/src/container/GridGraphLayout/Graph/FullView/TableRender/CustomCheckBox.tsx
  frontend/src/container/GridGraphLayout/Graph/FullView/TableRender/GetCheckBox.tsx
  frontend/src/container/GridGraphLayout/Graph/FullView/TableRender/GetLabel.tsx
  frontend/src/container/GridGraphLayout/Graph/FullView/TableRender/GraphManagerColumns.ts
  frontend/src/container/GridGraphLayout/Graph/FullView/TableRender/Label.tsx
  frontend/src/container/GridGraphLayout/Graph/FullView/contants.ts
  frontend/src/container/GridGraphLayout/Graph/FullView/index.tsx
  frontend/src/container/GridGraphLayout/Graph/FullView/styles.ts
  frontend/src/container/GridGraphLayout/Graph/FullView/types.ts
  frontend/src/container/GridGraphLayout/Graph/FullView/utils.ts
  frontend/src/container/GridGraphLayout/Graph/Graph.test.tsx
  frontend/src/container/GridGraphLayout/Graph/WidgetGraphComponent.tsx
  frontend/src/container/GridGraphLayout/Graph/__mock__/mockChartData.ts
  frontend/src/container/GridGraphLayout/Graph/__mock__/mockLegendEntryData.ts
  frontend/src/container/GridGraphLayout/Graph/index.tsx
  frontend/src/container/GridGraphLayout/Graph/types.ts
  frontend/src/container/GridGraphLayout/Graph/utils.ts
  frontend/src/container/GridPanelSwitch/index.tsx
  frontend/src/container/GridPanelSwitch/types.ts
  frontend/src/hooks/useChartMutable.ts
  frontend/src/lib/getChartData.ts
  frontend/src/utils/getEventEmitter.ts
  frontend/yarn.lock
Labels: request-more-info

#3220 feat: layout is updated for logs-settings
  frontend/public/locales/en-GB/routes.json
  frontend/public/locales/en-GB/translation.json
  frontend/public/locales/en/routes.json
  frontend/public/locales/en/translation.json
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/components/RouteTab/RouteTab.test.tsx
  frontend/src/components/RouteTab/index.tsx
  frontend/src/components/RouteTab/types.ts
  frontend/src/constants/routes.ts
  frontend/src/container/LogsIndexToFields/index.tsx
  frontend/src/pages/AlertChannelCreate/config.tsx
  frontend/src/pages/AlertChannelCreate/index.tsx
  frontend/src/pages/AllErrors/config.ts
  frontend/src/pages/AllErrors/index.tsx
  frontend/src/pages/LogsSettings/components/TabLabel.tsx
  frontend/src/pages/LogsSettings/config.tsx
  frontend/src/pages/LogsSettings/constant.ts
  frontend/src/pages/LogsSettings/index.tsx
  frontend/src/pages/LogsSettings/types.ts
  frontend/src/pages/MetricsApplication/index.tsx
  frontend/src/pages/MetricsApplication/useMetricsApplicationTabKey.tsx
  frontend/src/pages/Settings/config.ts
  frontend/src/pages/Settings/index.tsx
  frontend/src/pages/Settings/utils.ts
  frontend/src/utils/permission/index.ts
Labels: enhancement, request-more-info

#3262 View Traces Button fix
  frontend/src/container/GridGraphLayout/Graph/index.tsx
Labels: request-more-info

#3260 fix: tabs is updated
  frontend/src/container/LogsExplorerViews/LogsExplorerViews.styled.ts
  frontend/src/container/LogsExplorerViews/index.tsx
Labels: bug

#3271 fix: channels new key is updated
  frontend/src/pages/AlertChannelCreate/config.tsx
Labels: bug

#3272 Release/v0.25.3
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  frontend/src/container/LogsContextList/index.tsx
  frontend/src/container/LogsExplorerViews/LogsExplorerViews.styled.ts
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/PipelinePage/PipelineListsView/PipelineExpandView.tsx
  frontend/src/pages/AlertChannelCreate/config.tsx
Labels: request-more-info

#3273 Table Panel Data dashboard issue.
  frontend/src/container/GridGraphLayout/Graph/WidgetGraphComponent.tsx
Labels: request-more-info

#3280 fix: key operation table title for metrics
  frontend/src/container/MetricsApplication/Tabs/Overview/TopOperationMetrics.tsx
Labels: request-more-info

#3225 feat: add logspout as default docker logs collector
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/docker-compose-core.yaml
  deploy/docker/clickhouse-setup/docker-compose-local.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
  pkg/query-service/tests/test-deploy/docker-compose.yaml
  pkg/query-service/tests/test-deploy/otel-collector-config.yaml
Labels: enhancement

#3286 fix: table view logs on expand is updated
  frontend/src/components/Logs/TableView/types.ts
  frontend/src/container/LogsTable/index.tsx
Labels: bug, request-more-info

#3282 fix: getting first staged query
  frontend/src/container/LogsExplorerViews/index.tsx
Labels: bug, request-more-info

#3284 fix: pipeline change history: update config deployment status without having to reload
  frontend/src/container/PipelinePage/Layouts/ChangeHistory/index.tsx
  frontend/src/container/PipelinePage/Layouts/Pipeline/CreatePipelineButton.tsx
  frontend/src/container/PipelinePage/Layouts/Pipeline/index.tsx
  frontend/src/container/PipelinePage/PipelineListsView/ModeAndConfiguration.tsx
  frontend/src/container/PipelinePage/PipelineListsView/index.tsx
  frontend/src/container/PipelinePage/mocks/pipeline.ts
  frontend/src/container/PipelinePage/tests/CreatePipelineButton.test.tsx
  frontend/src/container/PipelinePage/tests/PipelinePageLayout.test.tsx
  frontend/src/pages/Pipelines/index.tsx
Labels: bug, request-more-info

#3281 feat: add ordering and sorting table column
  frontend/src/container/QueryTable/QueryTable.tsx
  frontend/src/lib/query/createTableColumnsFromQuery.ts
Labels: enhancement

#3288 feat: menu header is controlled from menuList rather than boolean for each menu
  frontend/src/container/GridGraphLayout/Graph/WidgetGraphComponent.tsx
  frontend/src/container/GridGraphLayout/Graph/index.tsx
  frontend/src/container/GridGraphLayout/Graph/types.ts
  frontend/src/container/GridGraphLayout/WidgetHeader/contants.ts
  frontend/src/container/GridGraphLayout/WidgetHeader/index.tsx
  frontend/src/container/GridGraphLayout/WidgetHeader/types.ts
  frontend/src/container/GridGraphLayout/WidgetHeader/utils.ts
  frontend/src/container/GridGraphLayout/config.ts
  frontend/src/container/GridGraphLayout/index.tsx
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ServiceOverview.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/TopLevelOperations.tsx
Labels: enhancement

#3290 fix: empty filters field
  frontend/src/container/LogsContextList/utils.ts
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/lib/newQueryBuilder/getPaginationQueryData.ts
Labels: bug

#3310 fix: lowercase filter operator and increase default conn settings
  ee/query-service/app/api/api.go
  ee/query-service/app/db/reader.go
  ee/query-service/app/server.go
  ee/query-service/main.go
  pkg/query-service/app/clickhouseReader/options.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/main.go
Labels: bug, testing-deploy

#3312 Release/v0.25.4
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/docker-compose-core.yaml
  deploy/docker/clickhouse-setup/docker-compose-local.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
  deploy/install.sh
  ee/query-service/app/api/api.go
  ee/query-service/app/db/reader.go
  ee/query-service/app/server.go
  ee/query-service/main.go
  frontend/src/components/Logs/TableView/types.ts
  frontend/src/container/ConfigDropdown/index.tsx
  frontend/src/container/ConfigDropdown/styles.ts
  frontend/src/container/GridGraphLayout/Graph/WidgetGraphComponent.tsx
  frontend/src/container/GridGraphLayout/Graph/index.tsx
  frontend/src/container/GridGraphLayout/Graph/types.ts
  frontend/src/container/GridGraphLayout/WidgetHeader/contants.ts
  frontend/src/container/GridGraphLayout/WidgetHeader/index.tsx
  frontend/src/container/GridGraphLayout/WidgetHeader/types.ts
  frontend/src/container/GridGraphLayout/WidgetHeader/utils.ts
  frontend/src/container/GridGraphLayout/config.ts
  frontend/src/container/GridGraphLayout/index.tsx
  frontend/src/container/Header/index.tsx
  frontend/src/container/Header/styles.ts
  frontend/src/container/ListOfDashboard/TableComponents/DeleteButton.tsx
  frontend/src/container/LogsContextList/utils.ts
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsTable/index.tsx
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ServiceOverview.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/TopLevelOperations.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/TopOperationMetrics.tsx
  frontend/src/container/PipelinePage/Layouts/ChangeHistory/index.tsx
  frontend/src/container/PipelinePage/Layouts/Pipeline/CreatePipelineButton.tsx
  frontend/src/container/PipelinePage/Layouts/Pipeline/index.tsx
  frontend/src/container/PipelinePage/PipelineListsView/ModeAndConfiguration.tsx
  frontend/src/container/PipelinePage/PipelineListsView/index.tsx
  frontend/src/container/PipelinePage/mocks/pipeline.ts
  frontend/src/container/PipelinePage/tests/CreatePipelineButton.test.tsx
  frontend/src/container/PipelinePage/tests/PipelinePageLayout.test.tsx
  frontend/src/container/QueryTable/QueryTable.tsx
  frontend/src/hooks/useEventSourceEvent/index.ts
  frontend/src/lib/newQueryBuilder/getPaginationQueryData.ts
  frontend/src/lib/query/createTableColumnsFromQuery.ts
  frontend/src/pages/Pipelines/index.tsx
  frontend/src/providers/EventSource.tsx
  pkg/query-service/app/clickhouseReader/options.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/main.go
  pkg/query-service/tests/test-deploy/docker-compose.yaml
  pkg/query-service/tests/test-deploy/otel-collector-config.yaml
Labels: request-more-info

#3308 feat: add new livetail to timeout exclude
  pkg/query-service/constants/constants.go
Labels: enhancement

#3319 fix: resource attribute is fixed trace data source
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ServiceOverview.tsx
  frontend/src/hooks/useResourceAttribute/utils.ts
Labels: bug, request-more-info

#3322 Release/v0.25.5
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ServiceOverview.tsx
  frontend/src/hooks/useResourceAttribute/utils.ts
  pkg/query-service/constants/constants.go
Labels: request-more-info

#3313 Refactor: Updated Adding Panel Loading State.
  frontend/src/container/GridGraphLayout/Graph/index.tsx
Labels: frontend

#3318 fix: null issue when switching from clickhouse to Query builder
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
Labels: request-more-info

#3321 feat: convert livetail to a get endpoint
  pkg/query-service/app/http_handler.go
Labels: enhancement

#3244 fix: alerts work when "equals to" or "not equals to" used with "all t…
  pkg/query-service/rules/resultTypes.go
  pkg/query-service/rules/thresholdRule.go
Labels: bug

#3332 chore: format for livetail changed
  pkg/query-service/app/http_handler.go
Labels: chore

#3268 feat: added the support of y axis unit and threshold unit in the alerts page
  frontend/public/locales/en-GB/alerts.json
  frontend/public/locales/en/alerts.json
  frontend/src/container/CreateAlertRule/defaults.ts
  frontend/src/container/FormAlertRules/ChartPreview/config.ts
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/FormAlertRules/ChartPreview/utils.test.ts
  frontend/src/container/FormAlertRules/ChartPreview/utils.ts
  frontend/src/container/FormAlertRules/RuleOptions.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/FormAlertRules/styles.ts
  frontend/src/container/NewWidget/RightContainer/alertFomatCategories.ts
  frontend/src/container/NewWidget/RightContainer/dataFormatCategories.ts
  frontend/src/container/NewWidget/RightContainer/types.ts
  frontend/src/container/QueryBuilder/filters/BuilderUnitsFilter/BuilderUnits.tsx
  frontend/src/container/QueryBuilder/filters/BuilderUnitsFilter/config.ts
  frontend/src/container/QueryBuilder/filters/BuilderUnitsFilter/index.ts
  frontend/src/container/QueryBuilder/filters/BuilderUnitsFilter/styles.ts
  frontend/src/container/QueryBuilder/filters/BuilderUnitsFilter/types.ts
  frontend/src/container/QueryBuilder/filters/BuilderUnitsFilter/utils.ts
  frontend/src/container/QueryBuilder/filters/index.ts
  frontend/src/lib/newQueryBuilder/queryBuilderMappers/mapQueryDataFromApi.ts
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/store/actions/dashboard/getQueryResults.ts
  frontend/src/types/api/alerts/compositeQuery.ts
  frontend/src/types/api/alerts/def.ts
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
  frontend/src/types/common/queryBuilder.ts
Labels: enhancement, frontend, team-fe-pr

#2689 feat: add ms teams channels
  ee/query-service/model/plans.go
  frontend/src/api/channels/createMsTeams.ts
  frontend/src/api/channels/editMsTeams.ts
  frontend/src/api/channels/testMsTeams.ts
  frontend/src/components/Upgrade/UpgradePrompt.tsx
  frontend/src/constants/features.ts
  frontend/src/container/CreateAlertChannels/config.ts
  frontend/src/container/CreateAlertChannels/index.tsx
  frontend/src/container/EditAlertChannels/index.tsx
  frontend/src/container/FormAlertChannels/Settings/MsTeams.tsx
  frontend/src/container/FormAlertChannels/index.tsx
  frontend/src/hooks/useFeatureFlag/utils.test.ts
  frontend/src/hooks/useFeatureFlag/utils.ts
  frontend/src/pages/ChannelsEdit/index.tsx
  frontend/src/types/api/channels/createMsTeams.ts
  frontend/src/types/api/channels/editMsTeams.ts
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/integrations/alertManager/model.go
  pkg/query-service/model/featureSet.go
Labels: enhancement, codeball:needs-careful-review

#3346 chore: bump alertmanager version
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose-core.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  pkg/query-service/README.md
  pkg/query-service/tests/test-deploy/docker-compose.yaml
Labels: chore

#2673 feat(alerts/query-service): measurement unit support for alerts
  go.mod
  go.sum
  pkg/query-service/converter/bool.go
  pkg/query-service/converter/converter.go
  pkg/query-service/converter/data.go
  pkg/query-service/converter/data_rate.go
  pkg/query-service/converter/percent_converter.go
  pkg/query-service/converter/throughput.go
  pkg/query-service/converter/time.go
  pkg/query-service/formatter/bool.go
  pkg/query-service/formatter/data.go
  pkg/query-service/formatter/data_rate.go
  pkg/query-service/formatter/formatter.go
  pkg/query-service/formatter/none.go
  pkg/query-service/formatter/percent.go
  pkg/query-service/formatter/throughput.go
  pkg/query-service/formatter/time.go
  pkg/query-service/model/v3/v3.go
  pkg/query-service/rules/alerting.go
  pkg/query-service/rules/apiParams.go
  pkg/query-service/rules/promRule.go
  pkg/query-service/rules/templates.go
  pkg/query-service/rules/thresholdRule.go
Labels: enhancement, codeball:needs-careful-review

#3340 bump nginx base image for cve fix
  frontend/Dockerfile
Labels: frontend, docker, community-pr

#3350 fix: log details action not it
  frontend/src/hooks/logs/useActiveLog.ts
  frontend/src/lib/newQueryBuilder/chooseAutocompleteFromCustomValue.ts
Labels: bug, request-more-info

#3197 feat: introduce PreferRPM feature
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/app/traces/v3/query_builder_test.go
  pkg/query-service/constants/constants.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/thresholdRule.go
Labels: enhancement

#3362 feat: regex operator is added in the string type for all data source
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/utils.ts
  frontend/src/hooks/queryBuilder/useOperatorType.ts
Labels: enhancement, frontend, request-more-info, team-fe-pr

#3377 fix: escape quote and backslash for ClickHouse value
  pkg/query-service/utils/format.go
  pkg/query-service/utils/format_test.go
Labels: bug

#3381 fix: update request payload and color in light mode for apdex
  frontend/src/components/TextToolTip/index.tsx
  frontend/src/container/GridGraphLayout/WidgetHeader/styles.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/OverviewQueries.ts
  frontend/src/pages/MetricsApplication/styles.ts
Labels: bug, frontend

#3388 Update Docker Download number label in README.md
  README.md
Labels: request-more-info

#3392 fix: regex support updated in logs
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
Labels: bug

#3393 feat: add regex support to traces
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/app/traces/v3/query_builder_test.go
Labels: enhancement, request-more-info

#3369 feat: default types for the query builder is updated
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/ExplorerOrderBy/index.tsx
  frontend/src/container/MetricsApplication/MetricsPageQueries/DBCallQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/ExternalQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/OverviewQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/TopOperationQueries.ts
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/container/ServiceApplication/ServiceMetrics/ServiceMetricsQuery.ts
  frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
  frontend/src/hooks/useResourceAttribute/utils.ts
  frontend/src/lib/newQueryBuilder/getPaginationQueryData.ts
  frontend/src/types/api/queryBuilder/queryAutocompleteResponse.ts
Labels: enhancement, frontend, team-fe-pr, ready-for-review

#3333 fix: [FE-3128]: Logs Explorer: Show options based on format type selected
  frontend/src/constants/optionsFormatTypes.ts
  frontend/src/container/ExplorerControlPanel/ExplorerControlPanel.interfaces.ts
  frontend/src/container/ExplorerControlPanel/index.tsx
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/OptionsMenu/index.tsx
  frontend/src/container/TracesExplorer/Controls/index.tsx
Labels: bug, frontend, team-fe-pr, ready-for-review

#3376 fix: type email is added in the invite members
  frontend/src/container/OrganizationSettings/InviteTeamMembers/index.tsx
Labels: bug, frontend, team-fe-pr, ready-for-review

#3378 chore: search support is added in dashboard variables
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
Labels: frontend, chore, request-more-info, team-fe-pr

#3401 chore: upgrade to go 1.21
  .github/workflows/build.yaml
  ee/query-service/Dockerfile
  go.mod
  pkg/query-service/Dockerfile
Labels: chore, request-more-info

#3397 fix: ts issue fixed with live tail
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/utils/format.go
  pkg/query-service/utils/format_test.go
Labels: bug

#2844 Align the query start and end timestamps to the nearest multiple of step
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/app/traces/v3/query_builder_test.go
  pkg/query-service/model/v3/v3.go
Labels: codeball:needs-careful-review

#3405 chore: disable telemetry in CI
  pkg/query-service/constants/constants.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore, request-more-info

#3399 fix: disable proxy buffering and cache
  deploy/docker-swarm/common/nginx-config.conf
  deploy/docker/common/nginx-config.conf
Labels: bug

#3275 feat: get and update log fields updated to support new materialized c…
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose-core.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/logs/parser.go
  pkg/query-service/app/logs/parser_test.go
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/constants/constants.go
  pkg/query-service/tests/test-deploy/docker-compose.yaml
  pkg/query-service/utils/format.go
  pkg/query-service/utils/format_test.go
Labels: enhancement

#3396 fix: signoz login from IDP
  ee/query-service/dao/sqlite/domain.go
Labels: bug

#3394 feat: Just-in-time provisioning of SSO users
  ee/query-service/app/api/auth.go
  ee/query-service/dao/sqlite/auth.go
  ee/query-service/dao/sqlite/domain.go
  ee/query-service/model/errors.go
  pkg/query-service/auth/auth.go
Labels: enhancement

#3403 fix: export table panel
  frontend/src/constants/panelTypes.ts
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/hooks/dashboard/utils.ts
  frontend/src/pages/TracesExplorer/index.tsx
  frontend/src/utils/dashboard/generateExportToDashboardLink.ts
Labels: bug, frontend, ready-for-review

#3422 Release/v0.27.0
  .github/workflows/build.yaml
  README.md
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker-swarm/common/nginx-config.conf
  deploy/docker/clickhouse-setup/docker-compose-core.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  deploy/docker/common/nginx-config.conf
  ee/query-service/Dockerfile
  ee/query-service/app/api/auth.go
  ee/query-service/dao/sqlite/auth.go
  ee/query-service/dao/sqlite/domain.go
  ee/query-service/model/errors.go
  frontend/src/components/TextToolTip/index.tsx
  frontend/src/constants/optionsFormatTypes.ts
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/ExplorerControlPanel/ExplorerControlPanel.interfaces.ts
  frontend/src/container/ExplorerControlPanel/index.tsx
  frontend/src/container/ExplorerOrderBy/index.tsx
  frontend/src/container/GridGraphLayout/WidgetHeader/styles.ts
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/MetricsApplication/MetricsPageQueries/DBCallQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/ExternalQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/OverviewQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/TopOperationQueries.ts
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
  frontend/src/container/OptionsMenu/index.tsx
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
  frontend/src/container/OrganizationSettings/InviteTeamMembers/index.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/container/ServiceApplication/ServiceMetrics/ServiceMetricsQuery.ts
  frontend/src/container/TracesExplorer/Controls/index.tsx
  frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
  frontend/src/hooks/useResourceAttribute/utils.ts
  frontend/src/lib/newQueryBuilder/getPaginationQueryData.ts
  frontend/src/pages/MetricsApplication/styles.ts
  frontend/src/types/api/queryBuilder/queryAutocompleteResponse.ts
  go.mod
  go.sum
  pkg/query-service/Dockerfile
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/logs/parser.go
  pkg/query-service/app/logs/parser_test.go
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/app/traces/v3/query_builder_test.go
  pkg/query-service/auth/auth.go
  pkg/query-service/constants/constants.go
  pkg/query-service/model/v3/v3.go
  pkg/query-service/telemetry/telemetry.go
  pkg/query-service/tests/test-deploy/docker-compose.yaml
  pkg/query-service/utils/format.go
  pkg/query-service/utils/format_test.go
Labels: request-more-info

#3409 fix: update apdex query to use placeholder parameters
  pkg/query-service/dao/sqlite/apdex.go
Labels: bug

#3425 chore: remove ee import
  pkg/query-service/integrations/signozio/dynamic_config.go
Labels: chore, request-more-info

#3408 fix: update dashboards to use placeholder params
  pkg/query-service/app/dashboards/model.go
Labels: bug

#3417 fix: use query-service API to fetch triggered alerts
  deploy/docker-swarm/common/nginx-config.conf
  deploy/docker/common/nginx-config.conf
  frontend/src/api/alerts/getTriggered.ts
  pkg/query-service/app/http_handler.go
Labels: bug, ok-to-test

#3407 fix(FE/logs): enable horizontal scroll in logs context
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/RawLogView/styles.ts
  frontend/src/components/Logs/RawLogView/types.ts
  frontend/src/container/LogsContextList/index.tsx
  frontend/src/container/LogsExplorerContext/index.tsx
  frontend/src/container/LogsExplorerContext/styles.ts
  frontend/src/utils/logs.ts
Labels: bug, frontend

#3314 chore: update saved views endpoints
  pkg/query-service/app/explorer/db.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/model/v3/v3.go
Labels: chore

#3434 fix: exists, nexists support for top level logs columns
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
Labels: bug

#3441 fix(FE): tooltip link not opening in apdex tooltip
  frontend/src/components/TextToolTip/index.tsx
Labels: bug, request-more-info

#3341 feat: add live logs list
  frontend/public/locales/en-GB/logs.json
  frontend/public/locales/en/logs.json
  frontend/src/constants/liveTail.ts
  frontend/src/container/LiveLogs/BackButton/index.tsx
  frontend/src/container/LiveLogs/FiltersInput/index.tsx
  frontend/src/container/LiveLogs/ListViewPanel/index.tsx
  frontend/src/container/LiveLogs/LiveLogsContainer/index.tsx
  frontend/src/container/LiveLogs/LiveLogsContainer/styles.ts
  frontend/src/container/LiveLogs/LiveLogsContainer/utils.ts
  frontend/src/container/LiveLogs/LiveLogsList/index.tsx
  frontend/src/container/LiveLogs/LiveLogsList/types.ts
  frontend/src/container/LiveLogs/LiveLogsListChart/index.tsx
  frontend/src/container/LiveLogs/LiveLogsListChart/types.ts
  frontend/src/container/LiveLogs/constants.ts
  frontend/src/container/LiveLogs/utils.ts
  frontend/src/container/LiveLogsTopNav/index.tsx
  frontend/src/container/LiveLogsTopNav/types.ts
  frontend/src/container/LogsExplorerChart/LogsExplorerChart.interfaces.ts
  frontend/src/container/LogsExplorerChart/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/types.ts
  frontend/src/container/OptionsMenu/FormatField/index.tsx
  frontend/src/container/OptionsMenu/types.ts
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
  frontend/src/providers/EventSource.tsx
Labels: enhancement, request-more-info

#3337 feat: get live data
  frontend/public/locales/en-GB/logs.json
  frontend/public/locales/en/logs.json
  frontend/src/api/metrics/getQueryRange.ts
  frontend/src/constants/liveTail.ts
  frontend/src/constants/theme.ts
  frontend/src/container/LiveLogs/BackButton/index.tsx
  frontend/src/container/LiveLogs/FiltersInput/index.tsx
  frontend/src/container/LiveLogs/ListViewPanel/index.tsx
  frontend/src/container/LiveLogs/LiveLogsContainer/index.tsx
  frontend/src/container/LiveLogs/LiveLogsContainer/styles.ts
  frontend/src/container/LiveLogs/LiveLogsList/index.tsx
  frontend/src/container/LiveLogs/LiveLogsList/types.ts
  frontend/src/container/LiveLogs/LiveLogsListChart/index.tsx
  frontend/src/container/LiveLogs/LiveLogsListChart/types.ts
  frontend/src/container/LiveLogs/constants.ts
  frontend/src/container/LiveLogs/utils.ts
  frontend/src/container/LiveLogsTopNav/index.tsx
  frontend/src/container/LiveLogsTopNav/types.ts
  frontend/src/container/LogsExplorerChart/LogsExplorerChart.interfaces.ts
  frontend/src/container/LogsExplorerChart/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/types.ts
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/OptionsMenu/FormatField/index.tsx
  frontend/src/container/OptionsMenu/types.ts
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
  frontend/src/hooks/useEventSourceEvent/index.ts
  frontend/src/pages/LiveLogs/index.tsx
  frontend/src/providers/EventSource.tsx
  frontend/src/store/actions/dashboard/getQueryResults.ts
  frontend/src/store/actions/dashboard/prepareQueryRangePayload.ts
  frontend/src/types/api/metrics/getQueryRange.ts
  frontend/src/types/api/queryBuilder/queryAutocompleteResponse.ts
Labels: enhancement, request-more-info

#3325 feat: add live logs where clause
  frontend/public/locales/en-GB/logs.json
  frontend/public/locales/en/logs.json
  frontend/src/api/metrics/getQueryRange.ts
  frontend/src/constants/liveTail.ts
  frontend/src/constants/theme.ts
  frontend/src/container/LiveLogs/BackButton/index.tsx
  frontend/src/container/LiveLogs/FiltersInput/index.tsx
  frontend/src/container/LiveLogs/FiltersInput/styles.ts
  frontend/src/container/LiveLogs/ListViewPanel/index.tsx
  frontend/src/container/LiveLogs/LiveLogsContainer/index.tsx
  frontend/src/container/LiveLogs/LiveLogsContainer/styles.ts
  frontend/src/container/LiveLogs/LiveLogsList/index.tsx
  frontend/src/container/LiveLogs/LiveLogsList/types.ts
  frontend/src/container/LiveLogs/LiveLogsListChart/index.tsx
  frontend/src/container/LiveLogs/LiveLogsListChart/types.ts
  frontend/src/container/LiveLogs/constants.ts
  frontend/src/container/LiveLogs/utils.ts
  frontend/src/container/LiveLogsTopNav/index.tsx
  frontend/src/container/LiveLogsTopNav/types.ts
  frontend/src/container/LogsExplorerChart/LogsExplorerChart.interfaces.ts
  frontend/src/container/LogsExplorerChart/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/types.ts
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/OptionsMenu/FormatField/index.tsx
  frontend/src/container/OptionsMenu/types.ts
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/hooks/queryBuilder/useShareBuilderUrl.ts
  frontend/src/hooks/useEventSourceEvent/index.ts
  frontend/src/pages/LiveLogs/index.tsx
  frontend/src/providers/EventSource.tsx
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/store/actions/dashboard/getQueryResults.ts
  frontend/src/store/actions/dashboard/prepareQueryRangePayload.ts
  frontend/src/types/api/metrics/getQueryRange.ts
  frontend/src/types/api/queryBuilder/queryAutocompleteResponse.ts
  frontend/src/types/common/queryBuilder.ts
Labels: enhancement, frontend, team-fe-pr

#3315 feat: create live logs page and custom top nav
  frontend/public/locales/en-GB/logs.json
  frontend/public/locales/en-GB/titles.json
  frontend/public/locales/en/logs.json
  frontend/public/locales/en/titles.json
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/api/metrics/getQueryRange.ts
  frontend/src/constants/liveTail.ts
  frontend/src/constants/routes.ts
  frontend/src/constants/theme.ts
  frontend/src/container/LiveLogs/BackButton/index.tsx
  frontend/src/container/LiveLogs/FiltersInput/index.tsx
  frontend/src/container/LiveLogs/FiltersInput/styles.ts
  frontend/src/container/LiveLogs/ListViewPanel/index.tsx
  frontend/src/container/LiveLogs/LiveLogsContainer/index.tsx
  frontend/src/container/LiveLogs/LiveLogsContainer/styles.ts
  frontend/src/container/LiveLogs/LiveLogsList/index.tsx
  frontend/src/container/LiveLogs/LiveLogsList/types.ts
  frontend/src/container/LiveLogs/LiveLogsListChart/index.tsx
  frontend/src/container/LiveLogs/LiveLogsListChart/types.ts
  frontend/src/container/LiveLogs/constants.ts
  frontend/src/container/LiveLogs/utils.ts
  frontend/src/container/LiveLogsTopNav/index.tsx
  frontend/src/container/LiveLogsTopNav/styles.ts
  frontend/src/container/LiveLogsTopNav/types.ts
  frontend/src/container/LocalTopNav/index.tsx
  frontend/src/container/LocalTopNav/styles.ts
  frontend/src/container/LocalTopNav/types.ts
  frontend/src/container/LogsExplorerChart/LogsExplorerChart.interfaces.ts
  frontend/src/container/LogsExplorerChart/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/types.ts
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsTopNav/index.tsx
  frontend/src/container/LogsTopNav/styles.ts
  frontend/src/container/NewExplorerCTA/config.ts
  frontend/src/container/NewExplorerCTA/index.tsx
  frontend/src/container/OptionsMenu/FormatField/index.tsx
  frontend/src/container/OptionsMenu/types.ts
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/container/TopNav/Breadcrumbs/index.tsx
  frontend/src/container/TopNav/DateTimeSelection/config.ts
  frontend/src/container/TopNav/index.tsx
  frontend/src/hooks/queryBuilder/useShareBuilderUrl.ts
  frontend/src/hooks/useEventSourceEvent/index.ts
  frontend/src/pages/LiveLogs/index.tsx
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/providers/EventSource.tsx
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/store/actions/dashboard/getQueryResults.ts
  frontend/src/store/actions/dashboard/prepareQueryRangePayload.ts
  frontend/src/types/api/metrics/getQueryRange.ts
  frontend/src/types/api/queryBuilder/queryAutocompleteResponse.ts
  frontend/src/types/common/queryBuilder.ts
  frontend/src/utils/permission/index.ts
Labels: enhancement, frontend, team-fe-pr

#3450 feat: use prefetched query in live
  frontend/src/container/LiveLogs/BackButton/index.tsx
  frontend/src/container/LiveLogs/LiveLogsContainer/index.tsx
  frontend/src/container/LiveLogs/LiveLogsList/index.tsx
  frontend/src/container/LiveLogs/LiveLogsListChart/index.tsx
  frontend/src/container/LiveLogs/LiveLogsListChart/types.ts
  frontend/src/container/LiveLogs/constants.ts
  frontend/src/container/LiveLogs/types.ts
  frontend/src/container/LiveLogsTopNav/types.ts
  frontend/src/container/LocalTopNav/index.tsx
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogsTopNav/index.tsx
  frontend/src/hooks/queryBuilder/useShareBuilderUrl.ts
Labels: enhancement, request-more-info

#3440 feat: add list loader and fix action column size
  frontend/src/container/LiveLogs/ListViewPanel/index.tsx
  frontend/src/container/LiveLogs/ListViewPanel/styles.ts
Labels: bug, enhancement, request-more-info

#3448 fix: back button issue fixed for traces/logs explorer
  frontend/src/hooks/useUrlQueryData.ts
  frontend/src/providers/QueryBuilder.tsx
Labels: frontend, community-pr, ready-for-review

#3404 Save View for Explorer pages.
  frontend/src/api/saveView/deleteView.ts
  frontend/src/api/saveView/getAllViews.ts
  frontend/src/api/saveView/saveView.ts
  frontend/src/api/saveView/updateView.ts
  frontend/src/components/ExplorerCard/ExplorerCard.tsx
  frontend/src/components/ExplorerCard/MenuItemGenerator.tsx
  frontend/src/components/ExplorerCard/SaveViewWithName.tsx
  frontend/src/components/ExplorerCard/__mock__/viewData.ts
  frontend/src/components/ExplorerCard/constants.ts
  frontend/src/components/ExplorerCard/index.tsx
  frontend/src/components/ExplorerCard/styles.ts
  frontend/src/components/ExplorerCard/test/ExplorerCard.test.tsx
  frontend/src/components/ExplorerCard/test/MenuItemGenerator.test.tsx
  frontend/src/components/ExplorerCard/test/SaveViewWithName.test.tsx
  frontend/src/components/ExplorerCard/types.ts
  frontend/src/components/ExplorerCard/utils.ts
  frontend/src/constants/queryBuilderQueryNames.ts
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/hooks/queryBuilder/useGetSearchQueryParam.ts
  frontend/src/hooks/saveViews/useDeleteView.ts
  frontend/src/hooks/saveViews/useGetAllViews.ts
  frontend/src/hooks/saveViews/useSaveView.ts
  frontend/src/hooks/saveViews/useUpdateView.ts
  frontend/src/hooks/useHandleExplorerTabChange.ts
  frontend/src/lib/newQueryBuilder/queryBuilderMappers/mapCompositeQueryFromQuery.ts
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/pages/TracesExplorer/index.tsx
  frontend/src/providers/test/MockQueryClientProvider.tsx
  frontend/src/types/api/saveViews/types.ts
Labels: frontend

#3453 fix: live tail query formatting fix
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
Labels: bug

#3429 feat: opsgenie integration
  ee/query-service/model/plans.go
  frontend/public/locales/en/channels.json
  frontend/src/api/channels/createOpsgenie.ts
  frontend/src/api/channels/editOpsgenie.ts
  frontend/src/api/channels/testOpsgenie.ts
  frontend/src/constants/features.ts
  frontend/src/container/CreateAlertChannels/config.ts
  frontend/src/container/CreateAlertChannels/defaults.ts
  frontend/src/container/CreateAlertChannels/index.tsx
  frontend/src/container/CreateAlertChannels/utils.ts
  frontend/src/container/EditAlertChannels/index.tsx
  frontend/src/container/FormAlertChannels/Settings/Opsgenie.tsx
  frontend/src/container/FormAlertChannels/index.tsx
  frontend/src/pages/AlertChannelCreate/config.tsx
  frontend/src/pages/ChannelsEdit/index.tsx
  frontend/src/types/api/channels/createOpsgenie.ts
  frontend/src/types/api/channels/editOpsgenie.ts
  pkg/query-service/model/featureSet.go
Labels: enhancement
