Repository SigNoz/signoz, pull requests merged in 2023-01, with the labels that each got.

#1927 feat: loading is added in the button
  frontend/src/container/LogControls/config.ts
  frontend/src/container/LogControls/index.tsx
  frontend/src/container/LogsSearchFilter/index.tsx
Labels: enhancement, codeball:needs-careful-review

#1946 fix: 🐛 resolve redundant metrics issue in Docker and Swarm
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker-swarm/clickhouse-setup/otel-collector-metrics-config.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/otel-collector-metrics-config.yaml
Labels: bug, codeball:needs-careful-review

#1933 ci(deployments): workflows for staging and testing deployments and related changes
  .github/workflows/remove-label.yaml
  .github/workflows/staging-deployment.yaml
  .github/workflows/testing-deployment.yaml
  Makefile
  deploy/docker/clickhouse-setup/docker-compose.yaml
Labels: codeball:needs-careful-review

#1980 ci: 👷 fix testing and staging deployments
  .github/workflows/staging-deployment.yaml
  .github/workflows/testing-deployment.yaml
Labels: bug, codeball:approved

#1971 fix: use rpc method and responseStatusCode
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/model/response.go
Labels: bug, codeball:needs-careful-review

#1987 Fix/analytics
  ee/query-service/app/server.go
  pkg/query-service/app/server.go
Labels: request-more-info

#1990 Revert "feat: react is updated to v18"
  frontend/package.json
  frontend/src/components/Logs/LogItem/index.tsx
  frontend/src/components/Logs/LogItem/styles.ts
  frontend/src/container/AllAlertChannels/index.tsx
  frontend/src/container/AllError/index.tsx
  frontend/src/container/AllError/types.ts
  frontend/src/container/GeneralSettings/GeneralSettings.tsx
  frontend/src/container/LogsSearchFilter/index.tsx
  frontend/src/container/LogsSearchFilter/useSearchParser.ts
  frontend/src/container/MetricsTable/index.tsx
  frontend/src/container/OrganizationSettings/EditMembersDetails/index.tsx
  frontend/src/container/Trace/Filters/Panel/PanelBody/Duration/index.tsx
  frontend/src/index.tsx
  frontend/src/pages/Trace/index.tsx
  frontend/yarn.lock
Labels: enhancement

#1996 Release/v0.13.1
  .github/workflows/remove-label.yaml
  .github/workflows/staging-deployment.yaml
  .github/workflows/testing-deployment.yaml
  CONTRIBUTING.md
  Makefile
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker-swarm/clickhouse-setup/otel-collector-metrics-config.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/otel-collector-metrics-config.yaml
  ee/query-service/app/server.go
  frontend/src/container/AllError/index.tsx
  frontend/src/container/LogControls/config.ts
  frontend/src/container/LogControls/index.tsx
  frontend/src/container/LogsAggregate/index.tsx
  frontend/src/container/LogsSearchFilter/index.tsx
  frontend/src/container/OrganizationSettings/DisplayName/index.tsx
  frontend/src/container/SideNav/index.tsx
  frontend/src/container/SideNav/menuItems.ts
  frontend/src/pages/Logs/index.tsx
  frontend/src/types/api/errors/getErrorCounts.ts
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/server.go
  pkg/query-service/auth/auth.go
  pkg/query-service/dao/sqlite/rbac.go
  pkg/query-service/model/response.go
  pkg/query-service/telemetry/telemetry.go
Labels: codeball:needs-careful-review

#2002 style: use 'no data' for empty graphs
  frontend/src/components/Graph/Plugin/EmptyGraph.ts
Labels: request-more-info

#2001 fix: add signoz.collector.id to spanmetrics dimensions
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
Labels: bug, codeball:needs-careful-review

#1533 Add support for histogram quantiles
  deploy/docker/clickhouse-setup/clickhouse-config.xml
  deploy/docker/clickhouse-setup/custom-function.xml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/user_scripts/histogramQuantile
  deploy/docker/clickhouse-setup/user_scripts/histogramQuantile.go
  frontend/src/types/common/dashboard.ts
  pkg/query-service/app/metrics/query_builder.go
  pkg/query-service/model/queryParams.go
Labels: ok-to-test, request-more-info, codeball:needs-careful-review, testing-deploy

#1999 fix: query builder formula fails to eval
  .github/workflows/build.yaml
  Makefile
  pkg/query-service/app/metrics/query_builder.go
  pkg/query-service/app/metrics/query_builder_test.go
Labels: bug, codeball:needs-careful-review, testing-deploy

#2027 fix: use target arch amd64
  deploy/docker/clickhouse-setup/user_scripts/histogramQuantile
  deploy/docker/clickhouse-setup/user_scripts/histogramQuantile.go
Labels: bug, request-more-info, testing-deploy

#2030 feat: react is updated to v18
  frontend/package.json
  frontend/src/components/Logs/LogItem/index.tsx
  frontend/src/components/Logs/LogItem/styles.ts
  frontend/src/container/AllError/index.tsx
  frontend/src/container/AllError/types.ts
  frontend/src/container/GeneralSettings/GeneralSettings.tsx
  frontend/src/container/LogsSearchFilter/index.tsx
  frontend/src/container/LogsSearchFilter/useSearchParser.ts
  frontend/src/container/MetricsTable/index.tsx
  frontend/src/container/OrganizationSettings/EditMembersDetails/index.tsx
  frontend/src/container/Trace/Filters/Panel/PanelBody/Duration/index.tsx
  frontend/src/index.tsx
  frontend/src/pages/Trace/index.tsx
  frontend/yarn.lock
Labels: ok-to-test

#2015 fix: Added Extra color code to stop repeat same color
  frontend/src/constants/theme.ts
  frontend/src/container/TraceDetail/utils.ts
  frontend/src/lib/getRandomColor.ts
  frontend/src/utils/getSpanTreeMetadata.ts
Labels: request-more-info

#2039 fix: Trigger Save layout only on title
  frontend/src/container/GridGraphLayout/Graph/index.tsx
  frontend/src/container/GridGraphLayout/GraphLayout.tsx
Labels: ok-to-test

#2055 Add visual feedback on `Copy JSON` in Log filter page
  frontend/src/components/Logs/LogItem/index.tsx
Labels: ok-to-test

#2036 feat: dashboard variable chaining
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/http_handler_test.go
  pkg/query-service/app/logs/parser_test.go
  pkg/query-service/app/parser_test.go
  pkg/query-service/model/queryParams.go
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2049 Fix/analytics
  ee/query-service/app/server.go
  pkg/query-service/app/server.go
  pkg/query-service/telemetry/telemetry.go
Labels: bug, request-more-info, codeball:needs-careful-review

#2018 feat: drag select timeframe on charts
  frontend/src/components/Graph/Plugin/DragSelect.ts
  frontend/src/components/Graph/Plugin/IntersectionCursor.ts
  frontend/src/components/Graph/Plugin/utils.ts
  frontend/src/components/Graph/index.tsx
  frontend/src/container/GridGraphComponent/index.tsx
  frontend/src/container/GridGraphLayout/Graph/FullView/index.metricsBuilder.tsx
  frontend/src/container/GridGraphLayout/Graph/FullView/index.tsx
  frontend/src/container/GridGraphLayout/Graph/index.tsx
  frontend/src/container/GridGraphLayout/index.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
  frontend/src/store/index.ts
Labels: ok-to-test

#2083 fix: dockerfile clickhouse indentation issue
  deploy/docker/clickhouse-setup/docker-compose.yaml
Labels: bug, request-more-info, codeball:approved

#2114 fix: yarnrc is added in the root of the frontend
  frontend/.yarnrc
Labels: bug, codeball:approved

#2115 feat: tag filter backend changes
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/parser.go
  pkg/query-service/constants/constants.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/model/response.go
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2037 feat(ui): dashboard variable chaining
  frontend/src/api/dashboard/variables/query.ts
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/index.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/index.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/styles.ts
  frontend/src/container/NewDashboard/DashboardVariablesSelection/util.ts
  frontend/src/container/NewDashboard/utils.ts
  frontend/src/types/api/dashboard/getAll.ts
  frontend/src/types/api/dashboard/variables/query.ts
Labels: enhancement, codeball:needs-careful-review

#2117 fix: total count is usage explorer
  frontend/src/modules/Usage/UsageExplorer.tsx
Labels: bug, codeball:approved

#2116 feat: tag filtering frontend changes
  frontend/src/api/trace/getSpans.ts
  frontend/src/api/trace/getSpansAggregate.ts
  frontend/src/api/trace/getTagValue.ts
  frontend/src/constants/resourceAttributes.ts
  frontend/src/container/Trace/Search/AllTags/Tag/TagKey.tsx
  frontend/src/container/Trace/Search/AllTags/Tag/TagValue.tsx
  frontend/src/container/Trace/Search/AllTags/Tag/index.tsx
  frontend/src/container/Trace/Search/AllTags/Tag/styles.ts
  frontend/src/container/Trace/Search/AllTags/Tag/utils.ts
  frontend/src/container/Trace/Search/AllTags/index.tsx
  frontend/src/container/Trace/Search/util.ts
  frontend/src/container/Trace/TraceGraphFilter/config.ts
  frontend/src/container/Trace/TraceGraphFilter/index.tsx
  frontend/src/container/Trace/TraceGraphFilter/utils.ts
  frontend/src/lib/resourceAttributes.ts
  frontend/src/types/api/trace/getTagFilters.ts
  frontend/src/types/api/trace/getTagValue.ts
  frontend/src/types/reducer/trace.ts
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2118 feat: popover is added in the trace tag search
  frontend/src/container/Trace/Search/AllTags/index.tsx
  frontend/src/container/Trace/Search/AllTags/styles.ts
  frontend/src/container/Trace/Search/config.ts
  frontend/src/container/Trace/Search/index.tsx
  frontend/src/hooks/useClickOutside.ts
Labels: enhancement, codeball:needs-careful-review

#2120 fix: graph flickering issue on trace page
  frontend/src/components/Graph/Plugin/Legend.ts
  frontend/src/components/Graph/styles.ts
Labels: request-more-info

#2119 chore(frontend): 🔧 support ARM and copy yarnrc in Dockerfile
  Makefile
  frontend/Dockerfile
Labels: chore, codeball:approved

#2053 removing repostats workflow
  .github/workflows/repo-stats.yml
Labels: codeball:needs-careful-review

#2068 fix: Chart loaders on reload and change of time interval at dashboard
  frontend/.husky/commit-msg
  frontend/src/components/Spinner/index.tsx
  frontend/src/container/GridGraphLayout/Graph/FullView/index.metricsBuilder.tsx
  frontend/src/container/GridGraphLayout/Graph/FullView/index.tsx
  frontend/src/container/GridGraphLayout/Graph/index.tsx
  frontend/src/container/GridGraphLayout/WidgetHeader/config.ts
  frontend/src/container/GridGraphLayout/WidgetHeader/index.tsx
  frontend/src/container/MetricsApplication/index.tsx
  frontend/src/hooks/usePreviousValue.ts
Labels: ok-to-test, request-more-info, testing-deploy

#2131 chore: update install message in install.sh script
  deploy/install.sh
Labels: chore, request-more-info

#2052 FIX: Exported dashboard include response of the queries #1981
  frontend/src/container/NewDashboard/DescriptionOfDashboard/ShareModal.tsx
  frontend/src/container/NewDashboard/DescriptionOfDashboard/util.ts
Labels: ok-to-test

#2141 fix: widget options are now opening
  frontend/src/container/GridGraphLayout/WidgetHeader/config.ts
  frontend/src/container/GridGraphLayout/WidgetHeader/index.tsx
  frontend/src/container/GridGraphLayout/WidgetHeader/styles.ts
Labels: ok-to-test

#2146 fix: interval is blocked for custom time selection
  frontend/src/container/TopNav/AutoRefresh/index.tsx
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
Labels: bug, codeball:needs-careful-review
