Repository SigNoz/signoz, pull requests merged in 2023-03, with the labels that each got.

#2244 chore: add payload types for autocomplete requests
  pkg/query-service/model/v3/v3.go
Labels: chore, codeball:needs-careful-review

#2380 fix: Logs Live Tail is fixed
  frontend/src/container/LogLiveTail/index.tsx
  frontend/src/container/LogsAggregate/index.tsx
  frontend/src/container/LogsSearchFilter/index.tsx
  frontend/src/hooks/useInterval.ts
Labels: bug, logs, codeball:needs-careful-review

#2401 feat: restricted_SELECTED_FIELDS is filtered from the selected list
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/TableView/index.tsx
  frontend/src/container/LogsFilters/index.tsx
Labels: enhancement, frontend, logs, codeball:needs-careful-review

#2415 feat: add span links support
  frontend/src/container/TraceDetail/SelectedSpanDetails/Tags/index.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
  frontend/src/types/api/trace/getTraceItem.ts
  frontend/src/utils/__tests__/__snapshots__/spanToTree.test.ts.snap
  frontend/src/utils/spanToTree.ts
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2419 fix: add the missing /health route removed in #2261
  pkg/query-service/app/http_handler.go
Labels: bug

#2421 chore: update CODEOWNERS for */query-service/
  .github/CODEOWNERS
Labels: chore, codeball:approved

#2263 feat: metric attribute autocomplete for the aggregation type
  ee/query-service/app/server.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/parser_test.go
  pkg/query-service/app/server.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/v3/v3.go
Labels: enhancement, codeball:needs-careful-review

#2284 feat: ability to save and retrieve the explorer queries
  ee/query-service/app/server.go
  pkg/query-service/app/explorer/db.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/model/v3/v3.go
Labels: enhancement, codeball:needs-careful-review

#2094 chore: bump SigNoz/prometheus
  .gitignore
  Makefile
  ee/query-service/Dockerfile
  go.mod
  go.sum
  pkg/query-service/Dockerfile
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler_test.go
  pkg/query-service/model/response.go
  pkg/query-service/pqlEngine/engine.go
  pkg/query-service/rules/promRule.go
  pkg/query-service/rules/promRuleTask.go
  pkg/query-service/utils/labels/interface.go
  pkg/query-service/utils/labels/labels.go
Labels: chore, request-more-info, codeball:needs-careful-review

#2403 feat: move form into `useForm` from `antd`
  frontend/src/container/Login/index.tsx
  frontend/src/container/Login/styles.ts
  frontend/src/container/ResetPassword/index.tsx
  frontend/src/container/ResetPassword/styles.ts
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/pages/SignUp/styles.ts
Labels: enhancement, frontend

#2434 chore: panel Type is disabled for now
  frontend/src/container/NewWidget/RightContainer/index.tsx
Labels: chore, codeball:approved

#2431 feat: body is added in the log
  frontend/src/components/Logs/TableView/config.ts
  frontend/src/components/Logs/TableView/index.tsx
Labels: enhancement, frontend, logs, codeball:approved

#2432 feat: color coding is added in the list view
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/ListLogView/styles.ts
Labels: enhancement, frontend, logs, codeball:needs-careful-review

#2264 feat: add attrs filters autocomplete endpoints
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/parser_test.go
  pkg/query-service/interfaces/interface.go
Labels: enhancement, codeball:needs-careful-review

#2437 feat: color coding is added in the table view
  frontend/src/components/Logs/TableView/index.tsx
  frontend/src/components/Logs/TableView/styles.ts
Labels: enhancement, frontend, logs, codeball:approved

#2443 fix: address legend formatting for external call error %
  frontend/src/container/MetricsApplication/MetricsPageQueries/ExternalQueries.ts
Labels: bug, codeball:approved

#1787 feat: opamp server application
  ee/query-service/app/server.go
  go.mod
  go.sum
  pkg/query-service/agentConf/db.go
  pkg/query-service/agentConf/manager.go
  pkg/query-service/agentConf/sqlite/init.go
  pkg/query-service/agentConf/version.go
  pkg/query-service/app/opamp/config.yaml
  pkg/query-service/app/opamp/configure_ingestionRules.go
  pkg/query-service/app/opamp/logger.go
  pkg/query-service/app/opamp/model/agent.go
  pkg/query-service/app/opamp/model/agents.go
  pkg/query-service/app/opamp/model/coordinator.go
  pkg/query-service/app/opamp/opamp_server.go
  pkg/query-service/app/opamp/otelconfig/config_parser.go
  pkg/query-service/app/opamp/otelconfig/config_parser_test.go
  pkg/query-service/app/opamp/otelconfig/filterprocessor/config.go
  pkg/query-service/app/opamp/otelconfig/otlpreceiver/config.go
  pkg/query-service/app/opamp/otelconfig/otlpreceiver/grpcSettings.go
  pkg/query-service/app/opamp/otelconfig/otlpreceiver/httpSettings.go
  pkg/query-service/app/opamp/otelconfig/otlpreceiver/tls.go
  pkg/query-service/app/opamp/otelconfig/tailsampler/config.go
  pkg/query-service/app/opamp/otelconfig/testdata/basic.yaml
  pkg/query-service/app/opamp/otelconfig/testdata/service.yaml
  pkg/query-service/app/opamp/pipeline_builder.go
  pkg/query-service/app/opamp/signal.go
  pkg/query-service/app/server.go
  pkg/query-service/constants/constants.go
  pkg/query-service/main.go
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2455 fix: get last n versions in getConfigHistory
  pkg/query-service/agentConf/db.go
  pkg/query-service/agentConf/manager.go
Labels: bug

#2464 feat: editor is updated
  frontend/src/components/Editor/index.tsx
Labels: enhancement, codeball:approved

#2465 feat: table view is updated for body field in the drawer
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogDetailedView/util.test.ts
  frontend/src/container/LogDetailedView/utils.ts
Labels: enhancement, frontend, codeball:needs-careful-review

#2449 fix: substitute nan negative rate from counter resets
  pkg/query-service/app/metrics/query_builder.go
  pkg/query-service/app/metrics/query_builder_test.go
Labels: bug, request-more-info, codeball:needs-careful-review

#2453 fix: update query range params
  pkg/query-service/model/v3/v3.go
Labels: bug, request-more-info, codeball:needs-careful-review

#2456 feat: logs parsing pipeline support in opamp
  pkg/query-service/agentConf/manager.go
  pkg/query-service/app/opamp/logspipeline.go
  pkg/query-service/app/opamp/logspipeline_test.go
  pkg/query-service/app/opamp/opamp_server.go
  pkg/query-service/constants/constants.go
  pkg/query-service/model/logparsingpipeline.go
Labels: enhancement, chore, codeball:needs-careful-review

#2265 feat: metrics query range v3
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/parser_test.go
  pkg/query-service/app/query_builder.go
  pkg/query-service/app/query_builder_test.go
  pkg/query-service/constants/constants.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/v3/v3.go
  pkg/query-service/utils/format.go
  pkg/query-service/utils/queryTemplate/vars.go
  pkg/query-service/utils/time.go
Labels: enhancement, codeball:needs-careful-review

#2498 fix(query): change correct position of provider
  frontend/src/AppRoutes/index.tsx
Labels: bug, request-more-info

#2507 fix: label is added in the tabs
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
Labels: frontend, codeball:approved

#2501 feat(provider): add base query types
  frontend/src/container/QueryBuilder/QueryBuilder.interfaces.ts
  frontend/src/container/QueryBuilder/QueryBuilder.tsx
  frontend/src/container/QueryBuilder/index.ts
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2488 feat(UI): add new query label
  frontend/src/container/QueryBuilder/components/ListMarker/ListMarker.interfaces.ts
  frontend/src/container/QueryBuilder/components/ListMarker/ListMarker.styled.ts
  frontend/src/container/QueryBuilder/components/ListMarker/ListMarker.tsx
  frontend/src/container/QueryBuilder/components/ListMarker/index.ts
  frontend/src/container/QueryBuilder/components/QueryLabel/QueryLabel.interfaces.ts
  frontend/src/container/QueryBuilder/components/QueryLabel/QueryLabel.styled.ts
  frontend/src/container/QueryBuilder/components/QueryLabel/QueryLabel.tsx
  frontend/src/container/QueryBuilder/components/QueryLabel/index.ts
  frontend/src/container/QueryBuilder/components/index.ts
  frontend/src/types/common/queryBuilder.ts
  frontend/src/types/common/select.ts
Labels: request-more-info

#2487 feat: add resource tags to ListErrors API
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/parser.go
  pkg/query-service/constants/constants.go
  pkg/query-service/model/queryParams.go
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2513 fix: commented unwanted sidebar menu option
  frontend/src/container/SideNav/menuItems.ts
Labels: enhancement, frontend

#2481 feat: support environment filtering in service map
  pkg/query-service/app/clickhouseReader/options.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/services/map.go
Labels: enhancement, codeball:needs-careful-review

#2514 fix: exception detail broken APIs due to resourceTagsMap
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug, request-more-info

#2491 feat: resource attribute is added in the exception
  frontend/src/AppRoutes/index.tsx
  frontend/src/api/errors/getAll.ts
  frontend/src/api/errors/getErrorCounts.ts
  frontend/src/api/trace/getSpans.ts
  frontend/src/api/trace/getSpansAggregate.ts
  frontend/src/container/AllError/index.tsx
  frontend/src/container/MetricsApplication/ResourceAttributesFilter/QueryChip.tsx
  frontend/src/container/MetricsApplication/ResourceAttributesFilter/ResourceAttributesFilter.Machine.ts
  frontend/src/container/MetricsApplication/ResourceAttributesFilter/ResourceAttributesFilter.Machine.typegen.ts
  frontend/src/container/MetricsApplication/ResourceAttributesFilter/index.tsx
  frontend/src/container/MetricsApplication/ResourceAttributesFilter/types.ts
  frontend/src/container/MetricsApplication/ResourceAttributesFilter/utils.ts
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/TopOperationsTable.tsx
  frontend/src/container/MetricsApplication/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/queryBuilder/MetricTagKeyFilter/MetricTagKey.machine.typegen.ts
  frontend/src/container/ResourceAttributesFilter/ResourceAttributesFilter.tsx
  frontend/src/container/ResourceAttributesFilter/components/QueryChip/QueryChip.tsx
  frontend/src/container/ResourceAttributesFilter/components/QueryChip/index.ts
  frontend/src/container/ResourceAttributesFilter/components/QueryChip/types.ts
  frontend/src/container/ResourceAttributesFilter/index.ts
  frontend/src/container/ResourceAttributesFilter/styles.ts
  frontend/src/container/SideNav/index.tsx
  frontend/src/hooks/useResourceAttribute/ResourceProvider.tsx
  frontend/src/hooks/useResourceAttribute/context.ts
  frontend/src/hooks/useResourceAttribute/index.ts
  frontend/src/hooks/useResourceAttribute/machine.ts
  frontend/src/hooks/useResourceAttribute/machine.typegen.ts
  frontend/src/hooks/useResourceAttribute/types.ts
  frontend/src/hooks/useResourceAttribute/useResourceAttribute.tsx
  frontend/src/hooks/useResourceAttribute/utils.ts
  frontend/src/lib/resourceAttributes.ts
  frontend/src/pages/AllErrors/index.tsx
  frontend/src/pages/MetricApplication/index.tsx
  frontend/src/pages/Metrics/index.tsx
  frontend/src/store/actions/metrics/setResourceAttributeQueries.ts
  frontend/src/store/reducers/metric.ts
  frontend/src/types/actions/metrics.ts
  frontend/src/types/api/errors/getAll.ts
  frontend/src/types/api/errors/getErrorCounts.ts
  frontend/src/types/reducer/metrics.ts
Labels: enhancement, frontend, codeball:needs-careful-review

#2510 fix: dependencies is updated
  frontend/src/container/LogsSearchFilter/useSearchParser.ts
Labels: bug, frontend, codeball:needs-careful-review

#2522 fix: min and max time is removed from the dependency list
  frontend/src/container/LogsSearchFilter/useSearchParser.ts
Labels: bug, ok-to-test, codeball:approved

#2529 fix: case sensitive selected field search fixed
  pkg/query-service/app/logs/parser.go
  pkg/query-service/app/logs/parser_test.go
Labels: bug

#2525 feat: keys for the service map is updated
  frontend/src/components/TextToolTip/index.tsx
  frontend/src/components/TextToolTip/styles.ts
  frontend/src/container/ResourceAttributesFilter/ResourceAttributesFilter.tsx
  frontend/src/hooks/useResourceAttribute/ResourceProvider.tsx
  frontend/src/hooks/useResourceAttribute/config.ts
  frontend/src/hooks/useResourceAttribute/machine.typegen.ts
  frontend/src/hooks/useResourceAttribute/utils.ts
  frontend/src/modules/Servicemap/Map.tsx
  frontend/src/modules/Servicemap/ServiceMap.tsx
Labels: enhancement, codeball:needs-careful-review
