Repository SigNoz/signoz, pull requests merged in 2023-02, with the labels that each got.

#2164 fix: resolved violating issue on change of layout API call
  frontend/src/container/GridGraphLayout/Graph/index.tsx
Labels: frontend, dashboards

#2013 feat: global time is updated
  frontend/src/components/Logs/AddToQueryHOC.tsx
  frontend/src/components/Logs/LogItem/index.tsx
  frontend/src/constants/theme.ts
  frontend/src/container/LogControls/index.tsx
  frontend/src/container/LogDetailedView/ActionItem.tsx
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogsFilters/FieldItem.tsx
  frontend/src/container/LogsFilters/config.ts
  frontend/src/container/LogsFilters/index.tsx
  frontend/src/container/LogsFilters/styles.ts
  frontend/src/container/LogsFilters/types.ts
  frontend/src/container/LogsFilters/utils.ts
  frontend/src/container/LogsSearchFilter/index.tsx
  frontend/src/container/LogsSearchFilter/useSearchParser.ts
  frontend/src/container/LogsSearchFilter/utils.ts
  frontend/src/lib/logs/flatLogData.ts
  frontend/src/pages/Logs/index.tsx
  frontend/src/store/reducers/global.ts
  frontend/src/store/reducers/logs.ts
  frontend/src/types/actions/globalTime.ts
  frontend/src/types/actions/logs.ts
Labels: ok-to-test

#2175 feat: modified resize table component
  frontend/src/components/ResizeTable/ResizableHeader.tsx
  frontend/src/components/ResizeTable/ResizeTable.tsx
  frontend/src/components/ResizeTable/config.ts
  frontend/src/components/ResizeTable/index.ts
  frontend/src/components/ResizeTable/styles.ts
  frontend/src/components/ResizeTableWrapper/index.ts
  frontend/src/container/AllAlertChannels/AlertChannels.tsx
  frontend/src/container/AllError/index.tsx
  frontend/src/container/ErrorDetails/index.tsx
  frontend/src/container/Licenses/ListLicenses.tsx
  frontend/src/container/ListAlertRules/ListAlert.tsx
  frontend/src/container/ListOfDashboard/index.tsx
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/MetricsApplication/TopOperationsTable.tsx
  frontend/src/container/MetricsTable/index.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/index.tsx
  frontend/src/container/OrganizationSettings/Members/index.tsx
  frontend/src/container/OrganizationSettings/PendingInvitesContainer/index.tsx
  frontend/src/container/Trace/TraceTable/index.tsx
  frontend/src/container/TriggeredAlerts/NoFilterTable.tsx
Labels: enhancement, frontend

#2152 chore: some of the eslint rules disabling are removed from Logs sections
  frontend/src/container/LogsSearchFilter/SearchFields/QueryBuilder/QueryBuilder.tsx
Labels: chore, codeball:needs-careful-review

#1970 fix: redirect to latest tag release notes
  frontend/src/container/Version/constant.ts
  frontend/src/container/Version/index.tsx
Labels: request-more-info

#2182 chore: removed react-vis dependencies
  frontend/package.json
  frontend/yarn.lock
Labels: chore, codeball:approved

#2156 feat: add autocomplete to groupBy filters
  frontend/src/api/trace/getSpans.ts
  frontend/src/container/Trace/Graph/index.tsx
  frontend/src/container/Trace/TraceGraphFilter/config.ts
  frontend/src/container/Trace/TraceGraphFilter/index.tsx
  frontend/src/container/Trace/TraceGraphFilter/utils.ts
Labels: enhancement, request-more-info, codeball:needs-careful-review

#2199 fix: unit test is fixed with react 18
  frontend/jest.config.ts
  frontend/package.json
  frontend/src/components/NotFound/NotFound.test.tsx
  frontend/src/container/TraceFlameGraph/__tests__/TraceFlameGraph.test.tsx
Labels: test

#2191 feat: navigate to trace from metrics
  frontend/src/container/MetricsApplication/MetricsPageQueries/DBCallQueries.ts
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/Tabs/util.ts
  frontend/src/lib/resourceAttributes.ts
  frontend/src/types/reducer/trace.ts
Labels: enhancement, codeball:needs-careful-review

#2201 test: traceGraphFilter/utils selectedGroupByValue is added
  frontend/src/container/Trace/TraceGraphFilter/utils.test.ts
Labels: codeball:needs-careful-review

#2213 chore: remove external metrics to trace nav
  frontend/src/container/MetricsApplication/Tabs/External.tsx
Labels: chore, request-more-info, codeball:approved

#2223 fix: graph component is memorised
  frontend/src/components/Graph/index.tsx
Labels: bug, frontend

#2210 fix: filters applied in the logs page
  frontend/src/container/LogsSearchFilter/useSearchParser.ts
Labels: bug, codeball:needs-careful-review

#2233 test: renderHook is added
  frontend/package.json
Labels: codeball:approved

#2231 fix: resource attribute tag key type is updated
  frontend/src/api/trace/getSpans.ts
  frontend/src/api/trace/getSpansAggregate.ts
  frontend/src/container/MetricsApplication/Tabs/util.ts
  frontend/src/container/Trace/Search/AllTags/Tag/TagKey.tsx
  frontend/src/container/Trace/Search/AllTags/Tag/index.tsx
  frontend/src/container/Trace/Search/AllTags/Tag/utils.ts
  frontend/src/container/Trace/Search/AllTags/index.tsx
  frontend/src/container/Trace/Search/util.ts
  frontend/src/lib/resourceAttributes.ts
  frontend/src/types/reducer/trace.ts
Labels: bug, codeball:needs-careful-review

#2257 feat: introduce health check endpoint
  deploy/install.sh
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/interfaces/interface.go
Labels: enhancement

#2207 fix: it has been fixed of difficult to click on metrics graph points
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/Tabs/util.ts
Labels: bug, codeball:needs-careful-review

#2163 feat: add list and table views for logs
  frontend/package.json
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/ListLogView/styles.ts
  frontend/src/components/Logs/ListLogView/util.ts
  frontend/src/components/Logs/RawLogView/config.ts
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/RawLogView/styles.ts
  frontend/src/components/Logs/TableView/config.ts
  frontend/src/components/Logs/TableView/index.tsx
  frontend/src/components/ResizeTable/ResizableHeader.tsx
  frontend/src/constants/localStorage.ts
  frontend/src/container/LogControls/index.tsx
  frontend/src/container/LogsFilters/index.tsx
  frontend/src/container/LogsFilters/styles.ts
  frontend/src/container/LogsSearchFilter/index.tsx
  frontend/src/container/LogsTable/index.tsx
  frontend/src/container/LogsTable/styles.ts
  frontend/src/hooks/useFontObserver.tsx
  frontend/src/index.html.ejs
  frontend/src/pages/Logs/PopoverContent.tsx
  frontend/src/pages/Logs/config.ts
  frontend/src/pages/Logs/hooks.ts
  frontend/src/pages/Logs/index.tsx
  frontend/src/pages/Logs/types.ts
  frontend/src/pages/Logs/utils.ts
  frontend/src/store/actions/logs/setLInesPerRow.ts
  frontend/src/store/actions/logs/setViewMode.ts
  frontend/src/store/reducers/logs.ts
  frontend/src/types/actions/logs.ts
  frontend/src/types/reducer/logs.ts
Labels: request-more-info

#2266 fix: onSearch callback is updated
  frontend/src/container/LogsSearchFilter/index.tsx
Labels: bug, codeball:approved

#2267 fix: onDrag is updated
  frontend/src/container/GridGraphLayout/index.tsx
Labels: bug, codeball:approved

#2270 test: testMatch is updated in jest
  frontend/jest.config.ts
Labels: chore, codeball:approved

#2292 fix: width is added for the max content
  frontend/src/container/GantChart/SpanLength/styles.ts
Labels: bug, frontend, codeball:approved

#2281 feat(FE): span Kind is added in the trace filter page
  frontend/src/api/trace/getFilters.ts
  frontend/src/api/trace/getSpans.ts
  frontend/src/api/trace/getSpansAggregate.ts
  frontend/src/api/trace/getTagFilter.ts
  frontend/src/api/trace/getTagValue.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/ExternalQueries.ts
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/Tabs/constant.ts
  frontend/src/container/MetricsApplication/Tabs/util.ts
  frontend/src/container/Trace/Filters/Panel/PanelBody/Common/Checkbox.tsx
  frontend/src/container/Trace/Filters/Panel/PanelBody/Duration/index.tsx
  frontend/src/container/Trace/Filters/Panel/PanelBody/SearchTraceID/index.tsx
  frontend/src/container/Trace/Filters/Panel/PanelHeading/index.tsx
  frontend/src/container/Trace/Search/AllTags/Tag/TagKey.tsx
  frontend/src/container/Trace/Search/AllTags/Tag/TagValue.tsx
  frontend/src/container/Trace/Search/index.tsx
  frontend/src/container/Trace/TraceGraphFilter/index.tsx
  frontend/src/pages/Trace/index.tsx
  frontend/src/store/actions/trace/getInitialFilter.ts
  frontend/src/store/actions/trace/getInitialSpansAggregate.ts
  frontend/src/store/actions/trace/getSpans.ts
  frontend/src/store/actions/trace/parseFilter/parseSpanKind.ts
  frontend/src/store/reducers/trace.ts
  frontend/src/types/actions/trace.ts
  frontend/src/types/api/trace/getFilters.ts
  frontend/src/types/api/trace/getSpanAggregate.ts
  frontend/src/types/api/trace/getSpans.ts
  frontend/src/types/api/trace/getTagFilters.ts
  frontend/src/types/api/trace/getTagValue.ts
  frontend/src/types/reducer/trace.ts
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/model/queryParams.go
Labels: enhancement, codeball:needs-careful-review

#2301 fix: attribute name corrected in logs database
  pkg/query-service/app/clickhouseReader/options.go
Labels: bug

#2304 fix: operator should be IN for top level operations
  frontend/src/container/MetricsApplication/MetricsPageQueries/OverviewQueries.ts
Labels: bug, request-more-info, codeball:needs-careful-review

#2311 fix: error rate as a percentage of range 0-100%
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug, codeball:needs-careful-review

#2277 chore: linebreak style is updated
  frontend/.eslintrc.js
Labels: chore, codeball:needs-careful-review

#2365 feat: multiple values can be selected
  frontend/src/container/Trace/Search/AllTags/Tag/TagValue.tsx
  frontend/src/container/Trace/Search/AllTags/Tag/utils.ts
Labels: enhancement, codeball:needs-careful-review

#2215 fix: changed ask admin message
  ee/query-service/app/api/api.go
  ee/query-service/app/api/auth.go
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/Login/index.tsx
  frontend/src/store/reducers/app.ts
  frontend/src/types/actions/app.ts
  frontend/src/types/api/user/getVersion.ts
  frontend/src/types/reducer/app.ts
  pkg/query-service/app/http_handler.go
  pkg/query-service/auth/auth.go
  pkg/query-service/auth/utils.go
  pkg/query-service/dao/interface.go
  pkg/query-service/dao/sqlite/rbac.go
  pkg/query-service/model/response.go
Labels: ok-to-test, testing-deploy

#2377 fix: resolves alert charts issue with 1 hr timerame
  frontend/src/container/FormAlertRules/RuleOptions.tsx
  frontend/src/container/FormAlertRules/utils.ts
Labels: bug, codeball:needs-careful-review

#2378 chore: bump signoz/signoz-otel-collector version
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose-core.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  pkg/query-service/tests/test-deploy/docker-compose.yaml
Labels: chore, codeball:approved

#2398 feat: color encoding is added in the logs raw view
  frontend/package.json
  frontend/src/components/Logs/RawLogView/config.ts
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/RawLogView/styles.ts
Labels: enhancement, frontend, logs, codeball:needs-careful-review

#2262 feat: add query range v3 API request/response payload types
  pkg/query-service/model/v3/v3.go
Labels: enhancement, codeball:needs-careful-review

#2275 chore: health endpoint related changes
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose-local.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  pkg/query-service/app/http_handler.go
  pkg/query-service/model/response.go
  pkg/query-service/telemetry/ignored.go
  pkg/query-service/tests/docker.go
  pkg/query-service/tests/test-deploy/docker-compose.yaml
Labels: chore, codeball:needs-careful-review
