Repository SigNoz/signoz, pull requests merged in 2023-07, with the labels that each got.

#2951 fix: add support for {max/min/avg} of rate
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
Labels: bug, codeball:needs-careful-review

#3006 Fix/double query logs request
  frontend/src/constants/queryBuilderQueryNames.ts
  frontend/src/container/ExplorerControlPanel/ExplorerControlPanel.interfaces.ts
  frontend/src/container/ExplorerControlPanel/index.tsx
  frontend/src/container/ExplorerControlPanel/styles.ts
  frontend/src/container/GridGraphLayout/WidgetHeader/index.tsx
  frontend/src/container/ListAlertRules/ListAlert.tsx
  frontend/src/container/LogsExplorerChart/LogsExplorerChart.interfaces.ts
  frontend/src/container/LogsExplorerChart/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/config.ts
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/styles.ts
  frontend/src/container/LogsExplorerList/InfinityTableView/types.ts
  frontend/src/container/LogsExplorerList/LogsExplorerList.interfaces.ts
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsExplorerList/styles.ts
  frontend/src/container/LogsExplorerTable/LogsExplorerTable.interfaces.ts
  frontend/src/container/LogsExplorerTable/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/NewDashboard/ComponentsSlider/index.tsx
  frontend/src/container/OptionsMenu/FormatField/index.tsx
  frontend/src/container/OptionsMenu/constants.ts
  frontend/src/container/OptionsMenu/types.ts
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
  frontend/src/container/PageSizeSelect/PageSizeSelect.interfaces.ts
  frontend/src/container/PageSizeSelect/index.tsx
  frontend/src/hooks/queryBuilder/useGetCompositeQueryParam.ts
  frontend/src/hooks/queryBuilder/useGetPanelTypesQueryParam.ts
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/pages/LogsExplorer/utils.ts
  frontend/src/pages/TracesExplorer/index.tsx
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/store/actions/dashboard/saveDashboard.ts
Labels: bug, request-more-info

#3012 fix: remove the second action button in the dashboards table
  frontend/src/container/ListOfDashboard/index.tsx
Labels: request-more-info

#2966 feat: add the traces view for the traces explorer
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/Controls/index.tsx
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryTable/QueryTable.intefaces.ts
  frontend/src/container/QueryTable/QueryTable.tsx
  frontend/src/container/TimeSeriesView/index.tsx
  frontend/src/container/TracesExplorer/Controls/index.tsx
  frontend/src/container/TracesExplorer/QuerySection/index.tsx
  frontend/src/container/TracesExplorer/TracesView/configs.tsx
  frontend/src/container/TracesExplorer/TracesView/index.tsx
  frontend/src/container/TracesExplorer/TracesView/styles.ts
  frontend/src/hooks/queryBuilder/useQueryOperations.ts
  frontend/src/hooks/queryPagination/config.ts
  frontend/src/hooks/queryPagination/types.ts
  frontend/src/hooks/queryPagination/useQueryPagination.ts
  frontend/src/hooks/queryPagination/utils.ts
  frontend/src/hooks/useUrlQueryData.ts
  frontend/src/lib/newQueryBuilder/getOperatorsBySourceAndPanelType.ts
  frontend/src/lib/newQueryBuilder/queryBuilderMappers/mapQueryDataToApi.ts
  frontend/src/lib/query/createTableColumnsFromQuery.ts
  frontend/src/pages/TracesExplorer/index.tsx
  frontend/src/pages/TracesExplorer/utils.tsx
  frontend/src/store/actions/dashboard/getQueryResults.ts
  frontend/src/types/api/widgets/getQuery.ts
  frontend/src/types/common/operations.types.ts
  frontend/src/types/common/queryBuilder.ts
Labels: request-more-info

#3022 feat: minor fixes to logs QB
  pkg/query-service/app/logs/v3/enrich_query.go
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
Labels: bug, enhancement

#2961 feat: add support for time() equivalent in formula
  pkg/query-service/app/queryBuilder/query_builder.go
Labels: enhancement

#2847 feat: trace view and list view for traces
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/app/traces/v3/query_builder_test.go
  pkg/query-service/constants/constants.go
  pkg/query-service/model/v3/v3.go
Labels: enhancement, codeball:needs-careful-review

#3004 fix: formula for table
  frontend/src/lib/query/createTableColumnsFromQuery.ts
  frontend/src/lib/toCapitalize.ts
Labels: bug, request-more-info

#3010 fix: alert evaluation params and query
  pkg/query-service/app/metrics/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/rules/thresholdRule.go
Labels: bug

#3023 Fix/handle hypen attributes
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/app/traces/v3/query_builder_test.go
Labels: bug, request-more-info

#3030 feat: update default logs page size
  frontend/src/store/reducers/logs.ts
Labels: enhancement, request-more-info

#3007 feat: add log explorer detail
  frontend/src/components/LogDetail/LogDetail.interfaces.ts
  frontend/src/components/LogDetail/index.tsx
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/container/LogDetailedView/index.tsx
  frontend/src/container/LogExplorerDetailedView/LogExplorerDetailedView.interfaces.ts
  frontend/src/container/LogExplorerDetailedView/index.tsx
  frontend/src/container/LogsExplorerList/LogsExplorerList.interfaces.ts
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsExplorerList/utils.ts
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsTable/index.tsx
Labels: enhancement, request-more-info

#3009 feat: add group by in the logs chart
  frontend/src/container/LogsExplorerChart/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/lib/explorer/getExplorerChartData.ts
  frontend/src/lib/getChartData.ts
Labels: enhancement, request-more-info

#3037 feat: add list chart
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/hooks/queryBuilder/useGetExplorerQueryRange.ts
Labels: enhancement

#3046 feat: hide aggregate every for table view
  frontend/src/container/QueryBuilder/QueryBuilder.interfaces.ts
  frontend/src/container/QueryBuilder/QueryBuilder.tsx
  frontend/src/container/QueryBuilder/components/Query/Query.interfaces.ts
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/hooks/queryBuilder/useQueryOperations.ts
  frontend/src/lib/query/createTableColumnsFromQuery.ts
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/types/common/operations.types.ts
Labels: enhancement, request-more-info

#3061 fix: enable deleting selected columns
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
Labels: bug, request-more-info

#3060 feat: remove date column table
  frontend/src/container/QueryTable/QueryTable.tsx
Labels: enhancement

#3058 fix: table columns adding
  frontend/src/components/Logs/TableView/types.ts
  frontend/src/components/Logs/TableView/useTableView.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/types.ts
  frontend/src/container/LogsExplorerList/index.tsx
Labels: bug

#3055 feat: save list options to local storage
  frontend/public/locales/en-GB/trace.json
  frontend/public/locales/en/trace.json
  frontend/src/constants/localStorage.ts
  frontend/src/container/OptionsMenu/FormatField/index.tsx
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
Labels: enhancement

#3062 fix: remove list item transition
  frontend/src/components/Logs/ListLogView/styles.ts
Labels: bug

#3056 fix: fix initial columns for the list view / fix attributes API call
  frontend/src/container/OptionsMenu/AddColumnField/index.tsx
  frontend/src/container/OptionsMenu/types.ts
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
  frontend/src/container/OptionsMenu/utils.ts
  frontend/src/container/TracesExplorer/ListView/index.tsx
Labels: request-more-info

#3068 fix: hide logs table view
  frontend/src/container/LogsExplorerViews/index.tsx
Labels: bug, request-more-info

#3069 fix: update saving column to storage
  frontend/src/constants/localStorage.ts
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
  frontend/src/container/TracesExplorer/ListView/index.tsx
Labels: request-more-info

#3071 feat: add tooltip for disabled tab
  frontend/src/components/TabLabel/TabLabel.interfaces.ts
  frontend/src/components/TabLabel/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/pages/TracesExplorer/utils.tsx
Labels: enhancement, request-more-info

#2993 feat: export panel in logs explorer is added
  frontend/src/container/ExportPanel/index.tsx
  frontend/src/container/LogsExplorerViews/LogsExplorerViews.styled.ts
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/hooks/queryBuilder/useGetExplorerQueryRange.ts
  frontend/src/hooks/useAxiosError.tsx
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/pages/TracesExplorer/index.tsx
Labels: enhancement

#3072 fix: add converting to ms for the durationNano attribute
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
  frontend/src/container/TimeSeriesView/index.tsx
  frontend/src/container/TimeSeriesView/utils.ts
Labels: request-more-info

#3075 fix: list scroll with time updating
  frontend/src/container/LogsExplorerViews/index.tsx
Labels: bug

#3093 feat: navigation to new explorer from old page are updated
  frontend/src/components/ExplorerCard/index.tsx
  frontend/src/components/TextToolTip/styles.ts
  frontend/src/container/TopNav/NewExplorerCTA/config.ts
  frontend/src/container/TopNav/NewExplorerCTA/index.tsx
  frontend/src/container/TopNav/index.tsx
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/pages/TracesExplorer/index.tsx
Labels: enhancement, request-more-info

#3092 feat: add autofill autocomplete data from response
  frontend/src/constants/queryBuilder.ts
  frontend/src/constants/regExp.ts
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
  frontend/src/lib/newQueryBuilder/chooseAutocompleteFromCustomValue.ts
  frontend/src/lib/newQueryBuilder/getAutocompleteValueAndType.ts
Labels: enhancement, request-more-info

#3083 feat: search capability is added on export panel
  frontend/src/container/ExportPanel/ExportPanel.tsx
  frontend/src/container/ExportPanel/index.tsx
  frontend/src/container/ExportPanel/utils.ts
Labels: enhancement

#3099 feat: export panel is updated
  frontend/src/container/ExportPanel/config.ts
  frontend/src/container/ExportPanel/index.tsx
Labels: enhancement

#3103 feat: update where clause based on log field
  frontend/src/components/LogDetail/LogDetail.interfaces.ts
  frontend/src/components/LogDetail/index.tsx
  frontend/src/components/Logs/AddToQueryHOC.tsx
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogDetailedView/index.tsx
  frontend/src/container/LogExplorerDetailedView/index.tsx
  frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
Labels: enhancement

#3105 chore: link is updated
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/pages/TracesExplorer/index.tsx
Labels: chore

#3104 fix: autcomplete top level keys
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#3096 chore: 🔧 upgrade distributed locust to 1.2.3 and updated related files
  deploy/README.md
  sample-apps/hotrod/README.md
  sample-apps/hotrod/hotrod-install.sh
  sample-apps/hotrod/hotrod-template.yaml
  sample-apps/hotrod/hotrod.yaml
Labels: chore

#3108 feat: choose autocomplete group by
  frontend/src/constants/queryBuilderFilterConfig.ts
  frontend/src/container/LogExplorerDetailedView/index.tsx
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
  frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
  frontend/src/lib/newQueryBuilder/chooseAutocompleteFromCustomValue.ts
Labels: enhancement

#3047 feat: add support for table view in traces
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/app/traces/v3/query_builder_test.go
Labels: enhancement

#3112 chore(hotrod): use develop branch instead of main for scripts
  .github/workflows/e2e-k3s.yaml
  CONTRIBUTING.md
  deploy/README.md
  sample-apps/hotrod/hotrod-delete.sh
  sample-apps/hotrod/hotrod-install.sh
Labels: chore

#3116 feat: [logs] Table view
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
Labels: enhancement

#3120 fix: click on field in the list item
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/container/LogExplorerDetailedView/LogExplorerDetailedView.interfaces.ts
  frontend/src/container/LogExplorerDetailedView/index.tsx
  frontend/src/container/LogsExplorerList/LogsExplorerList.interfaces.ts
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsTable/index.tsx
Labels: bug, request-more-info

#3121 fix: list pagination
  frontend/src/container/LogsExplorerViews/index.tsx
Labels: bug

#2979 feat: allow limit on metrics time series result
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/http_handler_test.go
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/model/v3/v3.go
Labels: enhancement, request-more-info

#3124 chore: limit filter is disabled for now
  frontend/src/container/QueryBuilder/filters/LimitFilter/LimitFilter.tsx
Labels: chore, request-more-info

#3127 chore: placeholder text is updated for where clause
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/constant.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
Labels: chore, request-more-info

#3126 fix: exporer log details action buttons
  frontend/src/components/LogDetail/LogDetail.interfaces.ts
  frontend/src/components/LogDetail/index.tsx
  frontend/src/components/Logs/AddToQueryHOC.tsx
  frontend/src/container/LogDetailedView/ActionItem.tsx
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogDetailedView/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsTable/index.tsx
  frontend/src/hooks/queryBuilder/useTag.ts
  frontend/src/lib/getGeneratedFilterQueryString.ts
  frontend/src/lib/removeJSONStringifyQuotes.ts
Labels: bug

#3125 fix: on delete current query length should be more than 1
  frontend/src/hooks/queryBuilder/useQueryOperations.ts
Labels: bug, frontend

#2505 Add support for Delta temporality
  ee/query-service/app/api/api.go
  ee/query-service/app/server.go
  ee/query-service/main.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metrics/v3/delta.go
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
  pkg/query-service/app/server.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/main.go
  pkg/query-service/model/v3/v3.go
Labels: codeball:needs-careful-review

#3134 feat: add flag to switch to span metrics for service level latency me…
  ee/query-service/app/api/api.go
  ee/query-service/app/api/featureFlags.go
  ee/query-service/app/server.go
  ee/query-service/main.go
  ee/query-service/model/plans.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/constants/constants.go
  pkg/query-service/main.go
  pkg/query-service/model/featureSet.go
Labels: enhancement

#3135 chore: table view for logs is updated
  frontend/src/container/LogsExplorerViews/index.tsx
Labels: chore, request-more-info

#2970 feat: add support for multiquery in ts with limit
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/constants/constants.go
  pkg/query-service/utils/format.go
  pkg/query-service/utils/format_test.go
Labels: enhancement

#3146 feat: added goto top feature in list logs veiw
  frontend/src/container/GoToTop/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/hooks/useScrollToTop/index.tsx
  frontend/src/hooks/useScrollToTop/types.ts
  frontend/src/hooks/useScrollToTop/useScrollToTop.test.ts
Labels: enhancement

#3147 fix: skip grouping set points for value type reducer
  pkg/query-service/app/metrics/v3/query_builder.go
Labels: bug

#3155 fix: not found is not visible when loading is visible
  frontend/src/container/LogsExplorerList/index.tsx
Labels: bug

#3142 fix: table column names with attribute and legend
  frontend/src/lib/query/createTableColumnsFromQuery.ts
Labels: bug

#3153 fix: table view on click is now taking raw logs
  frontend/src/components/LogDetail/index.tsx
  frontend/src/components/Logs/TableView/useTableView.tsx
Labels: bug, frontend, logs

#3138 fix: order by selection decides the result series
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/http_handler_test.go
Labels: bug

#3159 chore: limit is enabled
  frontend/src/container/QueryBuilder/filters/LimitFilter/LimitFilter.tsx
Labels: chore, request-more-info

#3163 fix: ordering of ts and table panel
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#3164 fix: use GLOBAL inner join instead of regular join
  pkg/query-service/app/traces/v3/query_builder_test.go
  pkg/query-service/constants/constants.go
Labels: bug

#3100 feat: add the ability to drag columns
  frontend/package.json
  frontend/src/components/ResizeTable/ResizeTable.tsx
  frontend/src/components/ResizeTable/styles.ts
  frontend/src/components/ResizeTable/types.ts
  frontend/src/constants/localStorage.ts
  frontend/src/container/LogsExplorerList/InfinityTableView/LogsCustomTable.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/styles.ts
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
  frontend/src/container/TracesExplorer/ListView/index.tsx
  frontend/src/hooks/useDragColumns/configs.ts
  frontend/src/hooks/useDragColumns/index.ts
  frontend/src/hooks/useDragColumns/types.ts
  frontend/src/hooks/useDragColumns/utils.ts
  frontend/yarn.lock
Labels: request-more-info

#3171 fix: encode email in loginPrecheck API
  frontend/src/api/user/loginPrecheck.ts
  frontend/src/types/api/user/loginPrecheck.ts
Labels: bug

#3157 feat: enable limit on ts (traces)
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/app/traces/v3/query_builder_test.go
Labels: enhancement

#3162 feat: add suggestion to order by filter
  frontend/src/container/ExplorerOrderBy/index.tsx
  frontend/src/container/LogExplorerQuerySection/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
  frontend/src/container/QueryBuilder/QueryBuilder.interfaces.ts
  frontend/src/container/QueryBuilder/QueryBuilder.tsx
  frontend/src/container/QueryBuilder/components/Query/Query.interfaces.ts
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
  frontend/src/container/QueryBuilder/filters/OrderByFilter/OrderByFilter.tsx
  frontend/src/container/QueryBuilder/filters/OrderByFilter/constants.ts
  frontend/src/container/QueryBuilder/filters/OrderByFilter/useOrderByFilter.ts
  frontend/src/container/QueryBuilder/filters/OrderByFilter/utils.ts
  frontend/src/container/TracesExplorer/QuerySection/index.tsx
  frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
  frontend/src/hooks/queryBuilder/useGetAggregateKeys.ts
  frontend/src/pages/TracesExplorer/index.tsx
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/types/common/queryBuilder.ts
Labels: enhancement

#3170 feat: live tail API with query range support
  pkg/query-service/app/clickhouseReader/options.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/v3/v3.go
Labels: enhancement, request-more-info

#2911 chore: use the local table for inner subquery
  pkg/query-service/app/metrics/query_builder.go
  pkg/query-service/app/metrics/v3/cumulative_table.go
  pkg/query-service/app/metrics/v3/cumulative_table_test.go
  pkg/query-service/app/metrics/v3/delta.go
  pkg/query-service/app/metrics/v3/delta_table.go
  pkg/query-service/app/metrics/v3/delta_table_test.go
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/app/parser_test.go
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
  pkg/query-service/constants/constants.go
Labels: chore

#3192 feat: use global in instead of in for second graph query
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
Labels: enhancement

#3195 feat: custom render is added int he query table
  frontend/src/container/QueryTable/QueryTable.intefaces.ts
  frontend/src/container/QueryTable/QueryTable.tsx
  frontend/src/lib/query/createTableColumnsFromQuery.ts
Labels: enhancement

#3186 feat: add support for apdex settings
  pkg/query-service/app/apdex.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/parser.go
  pkg/query-service/dao/interface.go
  pkg/query-service/dao/sqlite/apdex.go
  pkg/query-service/dao/sqlite/connection.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/db.go
  pkg/query-service/model/v3/v3.go
Labels: enhancement

#3198 feat: duplicate types are removed for panel and replaced by panel_types
  frontend/src/assets/Dashboard/Table.tsx
  frontend/src/assets/Dashboard/TimeSeries.tsx
  frontend/src/assets/Dashboard/Value.tsx
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/GridGraphLayout/Graph/FullView/styles.ts
  frontend/src/container/GridGraphLayout/index.tsx
  frontend/src/container/GridGraphLayout/styles.ts
  frontend/src/container/GridGraphLayout/utils.ts
  frontend/src/container/GridPanelSwitch/types.ts
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/NewDashboard/ComponentsSlider/index.tsx
  frontend/src/container/NewDashboard/ComponentsSlider/menuItems.ts
  frontend/src/container/NewDashboard/ComponentsSlider/styles.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/PlotTag.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/styles.ts
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/NewWidget/types.ts
  frontend/src/container/QueryBuilder/QueryBuilder.interfaces.ts
  frontend/src/hooks/queryBuilder/useGetExplorerQueryRange.ts
  frontend/src/hooks/queryBuilder/useGetPanelTypesQueryParam.ts
  frontend/src/lib/getStartEndRangeTime.ts
  frontend/src/lib/newQueryBuilder/getOperatorsBySourceAndPanelType.ts
  frontend/src/pages/DashboardWidget/index.tsx
  frontend/src/pages/TracesExplorer/index.tsx
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/store/actions/dashboard/getDashboard.ts
  frontend/src/store/actions/dashboard/saveDashboard.ts
  frontend/src/types/api/alerts/compositeQuery.ts
  frontend/src/types/api/dashboard/getAll.ts
  frontend/src/types/common/queryBuilder.ts
Labels: enhancement

#3207 fix: update how limit is added to table queries
  pkg/query-service/app/logs/v3/query_builder.go
Labels: bug

#3208 fix: ignore autocomplete request for body
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#3209 fix: custom where clause value
  frontend/src/container/LogExplorerQuerySection/index.tsx
  frontend/src/container/QueryBuilder/QueryBuilder.interfaces.ts
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/hooks/queryBuilder/useAutoComplete.ts
  frontend/src/hooks/queryBuilder/useOptions.ts
  frontend/src/hooks/queryBuilder/useQueryOperations.ts
  frontend/src/hooks/queryBuilder/useSetCurrentKeyAndOperator.ts
  frontend/src/hooks/queryBuilder/useTag.ts
Labels: bug, request-more-info

#3214 feat: add new params labelsArray to series
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/model/v3/v3.go
Labels: enhancement, request-more-info

#3221 feat: hotfix check if limit is not zero
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
Labels: bug, enhancement

#3200 fix: column name with legend
  frontend/src/constants/queryBuilder.ts
  frontend/src/lib/newQueryBuilder/getOperatorsBySourceAndPanelType.ts
  frontend/src/lib/query/createTableColumnsFromQuery.ts
  pkg/query-service/model/v3/v3.go
Labels: bug, request-more-info

#3227 fix: table resize
  frontend/src/container/QueryTable/config.ts
  frontend/src/lib/query/createTableColumnsFromQuery.ts
Labels: bug, request-more-info

#3190 feat: add logs context
  frontend/package.json
  frontend/src/api/metrics/getQueryRange.ts
  frontend/src/components/LogDetail/LogDetail.interfaces.ts
  frontend/src/components/LogDetail/index.tsx
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/ListLogView/styles.ts
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/RawLogView/styles.ts
  frontend/src/components/Logs/TableView/types.ts
  frontend/src/components/Logs/TableView/useTableView.tsx
  frontend/src/constants/query.ts
  frontend/src/constants/theme.ts
  frontend/src/container/LogsContextList/ShowButton.tsx
  frontend/src/container/LogsContextList/configs.ts
  frontend/src/container/LogsContextList/index.tsx
  frontend/src/container/LogsContextList/styles.ts
  frontend/src/container/LogsContextList/utils.ts
  frontend/src/container/LogsExplorerContext/index.tsx
  frontend/src/container/LogsExplorerContext/styles.ts
  frontend/src/container/LogsExplorerContext/types.ts
  frontend/src/container/LogsExplorerContext/useInitialQuery.ts
  frontend/src/container/LogsExplorerContext/utils.ts
  frontend/src/container/LogsExplorerList/InfinityTableView/LogsCustomTable.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/config.ts
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/styles.ts
  frontend/src/container/LogsExplorerList/InfinityTableView/types.ts
  frontend/src/container/LogsExplorerList/LogsExplorerList.interfaces.ts
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsTable/index.tsx
  frontend/src/hooks/logs/configs.ts
  frontend/src/hooks/logs/types.ts
  frontend/src/hooks/logs/useActiveLog.ts
  frontend/src/hooks/logs/useCopyLogLink.ts
  frontend/src/hooks/queryBuilder/useGetExplorerQueryRange.ts
  frontend/src/pages/Logs/index.tsx
  frontend/src/types/api/index.ts
  frontend/src/types/api/logs/log.ts
  frontend/src/utils/getAlphaColor.ts
  frontend/yarn.lock
Labels: request-more-info
