Repository SigNoz/signoz, pull requests merged in 2023-12, with the labels that each got.

#4133 [Fix]: the full view in service layer
  frontend/src/container/GridCardLayout/GridCard/FullView/utils.ts
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/MetricsApplication/MetricsApplication.factory.ts
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/ApDexMetrics.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ServiceOverview.tsx
  frontend/src/container/MetricsApplication/constant.ts
  frontend/src/container/MetricsApplication/types.ts
Labels: bug

#4131 fix: update logic for handling data for uplot charts
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
  frontend/src/lib/uPlotLib/utils/getUplotChartData.ts
  frontend/src/styles.scss
Labels: bug

#4140 fix: add onboarding complete event
  frontend/src/container/OnboardingContainer/common/ModuleStepsContainer/ModuleStepsContainer.tsx
  frontend/src/index.html.ejs
Labels: bug

#4141 fix: text formatting issues and upgrade button style updates
  frontend/src/container/Header/Header.styles.scss
  frontend/src/container/Header/index.tsx
Labels: bug, request-more-info

#4154 fix: custom variables options are not populated
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
Labels: bug

#4149 Feat: fe: logs pipelines severity parsing processor
  frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/FormFields/CSVInput.tsx
  frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/ProcessorForm.tsx
  frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/config.ts
  frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/styles.scss
  frontend/src/pages/Pipelines/index.tsx
Labels: enhancement

#4071 Fix/2967
  frontend/src/container/TriggeredAlerts/Filter.tsx
Labels: frontend

#4191 chore: add variable templating endpoint
  pkg/query-service/app/http_handler.go
Labels: chore

#4165 chore: update BuilderQuery struct and add PrepareTimeseriesFilterQuery
  pkg/query-service/app/metrics/v4/query_builder.go
  pkg/query-service/app/metrics/v4/query_builder_test.go
  pkg/query-service/model/v3/v3.go
Labels: chore

#4207 Revert "fix: variable edit flow - use updated query value on test query"
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx
Labels: bug

#4210 fix: use updated query value on test query, restrict direct commit to…
  frontend/.husky/commit-msg
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx
Labels: bug, frontend

#4193 feat: pass abort signal to cancel api request on query-key change or …
  frontend/jest.config.ts
  frontend/package.json
  frontend/src/api/ErrorResponseHandler.ts
  frontend/src/api/dashboard/get.ts
  frontend/src/api/index.ts
  frontend/src/api/metrics/getQueryRange.ts
  frontend/src/container/PipelinePage/PipelineListsView/Preview/hooks/usePipelinePreview.ts
  frontend/src/hooks/queryBuilder/useGetQueryRange.ts
  frontend/src/lib/dashboard/getQueryResults.ts
  frontend/src/pages/NewDashboard/DashboardPage.tsx
  frontend/src/providers/Dashboard/Dashboard.tsx
  frontend/yarn.lock
Labels: enhancement, frontend

#4217 feat: track channel click event in support page
  frontend/src/pages/Support/Support.tsx
Labels: enhancement

#4226 [Feat]: only clicked legend graph visible
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
Labels: enhancement

#4166 chore: add prepare query for cumulative/unspecified timeseries
  pkg/query-service/app/metrics/v4/cumulative/helper.go
  pkg/query-service/app/metrics/v4/cumulative/timeseries.go
  pkg/query-service/app/metrics/v4/cumulative/timeseries_test.go
Labels: chore

#4078 fix: createPAT method to return id
  ee/query-service/app/api/pat.go
  ee/query-service/dao/interface.go
  ee/query-service/dao/sqlite/pat.go
  ee/query-service/model/pat.go
Labels: bug

#3539 chore: update .github/CODEOWNERS
  .github/CODEOWNERS
Labels: chore, request-more-info

#4214 chore: add new dashboard/alerts info events
  ee/query-service/app/server.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/server.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/response.go
  pkg/query-service/rules/thresholdRule_test.go
  pkg/query-service/telemetry/ignored.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#4230 chore: better error handling in getAlertsInfo
  ee/query-service/model/plans.go
  pkg/query-service/model/featureSet.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#4225 feat: upgrade clickhouse to 23.11.1
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  pkg/query-service/tests/test-deploy/docker-compose.yaml
Labels: enhancement

#4229 fix: remove timestamp roundup for logs list api call
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/app/parser.go
Labels: bug

#4144 Uplot time range
  frontend/.eslintrc.js
  frontend/src/components/Uplot/Uplot.styles.scss
  frontend/src/components/Uplot/Uplot.tsx
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.styles.scss
  frontend/src/container/GridCardLayout/WidgetHeader/WidgetHeader.styles.scss
  frontend/src/container/GridCardLayout/WidgetHeader/index.tsx
  frontend/src/container/GridCardLayout/styles.ts
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/styles.ts
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
  frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
  frontend/src/lib/uPlotLib/utils/getAxes.ts
  frontend/src/lib/uPlotLib/utils/getGridColor.ts
  frontend/src/lib/uPlotLib/utils/getSeriesData.ts
  frontend/src/lib/uPlotLib/utils/getXAxisScale.ts
  frontend/src/lib/uPlotLib/utils/getYAxisScale.ts
  frontend/src/utils/getTimeRange.ts
Labels: frontend

#4187 Rearrange variables
  frontend/package.json
  frontend/src/container/NewDashboard/DashboardDescription/SettingsDrawer.tsx
  frontend/src/container/NewDashboard/DashboardSettings/DashboardSettings.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/index.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/types.ts
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.test.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/util.ts
  frontend/src/container/NewDashboard/utils.ts
  frontend/src/container/OnboardingContainer/common/ModuleStepsContainer/ModuleStepsContainer.tsx
  frontend/src/lib/dashbaordVariables/getDashboardVariables.ts
  frontend/src/providers/Dashboard/Dashboard.tsx
  frontend/src/types/api/dashboard/getAll.ts
  frontend/yarn.lock
Labels: frontend

#4204 feat: on create alerts query range format is called to fill the variables
  frontend/src/api/dashboard/queryRangeFormat.ts
  frontend/src/container/GridCardLayout/WidgetHeader/index.tsx
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/hooks/queryBuilder/useCreateAlerts.tsx
Labels: enhancement

#4203 [Fix]: the min data point as 0 in time series
  frontend/src/lib/uPlotLib/utils/getYAxisScale.ts
Labels: bug

#4237 fix: do not use grouping sets when there is no tags for group by
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/app/metrics/v4/cumulative/helper.go
  pkg/query-service/app/metrics/v4/cumulative/timeseries_test.go
Labels: bug

#4240 fix: enrichment for json in alerts and disable timestamp adjustment
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/rules/thresholdRule.go
Labels: bug

#4241 feat: show trace details on hover
  frontend/src/container/GantChart/GantChart.styles.scss
  frontend/src/container/GantChart/Span/index.tsx
  frontend/src/container/GantChart/Span/styles.ts
  frontend/src/container/GantChart/SpanLength/index.tsx
  frontend/src/container/GantChart/Trace/index.tsx
  frontend/src/container/GantChart/index.tsx
  frontend/src/container/GantChart/styles.ts
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
  frontend/src/container/TraceDetail/TraceDetails.styles.scss
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/container/TraceDetail/styles.ts
Labels: enhancement

#4262 [Fix]: range issue in uplot charts
  frontend/src/lib/uPlotLib/utils/getYAxisScale.ts
Labels: bug

#4260 feat: gh-4211: show copy and share invite link message next to pendin…
  frontend/public/locales/en-GB/organizationsettings.json
  frontend/public/locales/en/organizationsettings.json
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/OrganizationSettings/PendingInvitesContainer/index.tsx
Labels: enhancement

#4121 fix: dot support in attribute name
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/logs/v3/enrich_query_test.go
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
  pkg/query-service/utils/format.go
Labels: bug

#4255 Revert "Fix: lettercase bug in query-builder"
  frontend/src/hooks/queryBuilder/useSetCurrentKeyAndOperator.ts
Labels: bug

#4271 chore: update active user event
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#4253 chore: send event only if there are dashboards or alerts
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#4266 feat: show rate limit warning in services page when total RPS > 100
  frontend/public/locales/en-GB/services.json
  frontend/public/locales/en/services.json
  frontend/src/constants/global.ts
  frontend/src/container/ServiceApplication/ServiceMetrics/ServiceMetricTable.tsx
  frontend/src/container/ServiceApplication/ServiceTraces/ServiceTracesTable.tsx
  frontend/src/container/ServiceApplication/index.tsx
  frontend/src/hooks/analytics/useAnalytics.tsx
  frontend/src/pages/Services/index.tsx
  frontend/src/utils/services.ts
Labels: enhancement

#4274 fix(dockerfile): copy invitation email templates for EE build
  ee/query-service/Dockerfile
Labels: bug

#4222 feat: onboarding flow updates and new flow addition
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/Kubernetes/others-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/Kubernetes/others-kubernetes-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/Kubernetes/others-kubernetes-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/LinuxAMD64/QuickStart/others-linuxamd64-quickStart-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/LinuxAMD64/QuickStart/others-linuxamd64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/LinuxAMD64/Recommended/others-linuxamd64-recommended-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/LinuxAMD64/Recommended/others-linuxamd64-recommended-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/LinuxAMD64/Recommended/others-linuxamd64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/LinuxARM64/QuickStart/others-linuxarm64-quickStart-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/LinuxARM64/QuickStart/others-linuxarm64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/LinuxARM64/Recommended/others-linuxarm64-recommended-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/LinuxARM64/Recommended/others-linuxarm64-recommended-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/LinuxARM64/Recommended/others-linuxarm64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/MacOsAMD64/QuickStart/others-macosamd64-quickStart-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/MacOsAMD64/QuickStart/others-macosamd64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/MacOsAMD64/Recommended/others-macosamd64-recommended-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/MacOsAMD64/Recommended/others-macosamd64-recommended-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/MacOsAMD64/Recommended/others-macosamd64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/MacOsARM64/QuickStart/others-macosarm64-quickStart-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/MacOsARM64/QuickStart/others-macosarm64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/MacOsARM64/Recommended/others-macosarm64-recommended-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/MacOsARM64/Recommended/others-macosarm64-recommended-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/MacOsARM64/Recommended/others-macosarm64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/Kubernetes/reactjs-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/Kubernetes/reactjs-kubernetes-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/Kubernetes/reactjs-kubernetes-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/LinuxAMD64/QuickStart/reactjs-linuxamd64-quickStart-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/LinuxAMD64/QuickStart/reactjs-linuxamd64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/LinuxAMD64/Recommended/reactjs-linuxamd64-recommended-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/LinuxAMD64/Recommended/reactjs-linuxamd64-recommended-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/LinuxAMD64/Recommended/reactjs-linuxamd64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/LinuxARM64/QuickStart/reactjs-linuxarm64-quickStart-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/LinuxARM64/QuickStart/reactjs-linuxarm64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/LinuxARM64/Recommended/reactjs-linuxarm64-recommended-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/LinuxARM64/Recommended/reactjs-linuxarm64-recommended-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/LinuxARM64/Recommended/reactjs-linuxarm64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/MacOsAMD64/QuickStart/reactjs-macosamd64-quickStart-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/MacOsAMD64/QuickStart/reactjs-macosamd64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/MacOsAMD64/Recommended/reactjs-macosamd64-recommended-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/MacOsAMD64/Recommended/reactjs-macosamd64-recommended-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/MacOsAMD64/Recommended/reactjs-macosamd64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/MacOsARM64/QuickStart/reactjs-macosarm64-quickStart-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/MacOsARM64/QuickStart/reactjs-macosarm64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/MacOsARM64/Recommended/reactjs-macosarm64-recommended-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/MacOsARM64/Recommended/reactjs-macosarm64-recommended-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/MacOsARM64/Recommended/reactjs-macosarm64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/constants/apmDocFilePaths.ts
  frontend/src/container/OnboardingContainer/utils/dataSourceUtils.ts
Labels: enhancement

#4285 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: chore, request-more-info

#4247 [Fix]: threshold table issue
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
Labels: bug

#4043 [Fix]: scroll bar issue in table panel
  frontend/src/container/GridTableComponent/styles.ts
Labels: bug

#4293 fix: ignore timestamp from the subquery result for value panel
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/traces/v3/query_builder.go
Labels: bug

#4249 [Fix]: live view details modal disappear bug
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/container/LiveLogs/LiveLogsList/index.tsx
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsTable/index.tsx
Labels: bug

#4264 fix: normalize label name to follow prometheus spec
  pkg/query-service/rules/thresholdRule.go
  pkg/query-service/rules/thresholdRule_test.go
Labels: bug

#4302 fix: fill gap persistent
  frontend/src/container/NewWidget/index.tsx
Labels: bug

#4263 fix: adjust the start and end more accurately
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/app/querier/querier_test.go
Labels: bug

#4300 fix: overflow issue in service page graphs
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/Tabs/styles.ts
  frontend/src/container/MetricsApplication/styles.ts
Labels: bug

#4248 [Refactor]: css fixes
  frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.tsx
Labels: bug

#4167 chore: add prepare query for delta/unspecified timeseries
  pkg/query-service/app/metrics/v4/delta/helper.go
  pkg/query-service/app/metrics/v4/delta/time_series_test.go
  pkg/query-service/app/metrics/v4/delta/timeseries.go
Labels: chore
