Repository SigNoz/signoz, pull requests merged in 2024-01, with the labels that each got.

#4168 chore: add prepare query for delta/unspecified table
  pkg/query-service/app/metrics/v4/delta/table.go
  pkg/query-service/app/metrics/v4/delta/table_test.go
  pkg/query-service/app/metrics/v4/delta/time_series_test.go
  pkg/query-service/app/metrics/v4/delta/timeseries.go
Labels: chore

#4283 chore: fix the query range cache gaps
  pkg/query-service/app/querier/helper.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/model/v3/v3.go
Labels: bug, chore

#4332 fix: throw error when response for value panel returns more than one …
  pkg/query-service/app/querier/querier.go
Labels: bug

#4169 chore: add prepare query for cumulative/unspecified table
  pkg/query-service/app/metrics/v4/cumulative/table.go
  pkg/query-service/app/metrics/v4/cumulative/table_test.go
  pkg/query-service/app/metrics/v4/cumulative/timeseries.go
  pkg/query-service/app/metrics/v4/cumulative/timeseries_test.go
Labels: chore

#4336 feat: [SIG-505]: Integrate the new generic toolbar and date time selection according to the new designs
  frontend/src/container/QueryBuilder/components/ToolbarActions/LeftToolbarActions.tsx
  frontend/src/container/QueryBuilder/components/ToolbarActions/RightToolbarActions.tsx
  frontend/src/container/QueryBuilder/components/ToolbarActions/ToolbarActions.styles.scss
  frontend/src/container/Toolbar/Toolbar.styles.scss
  frontend/src/container/Toolbar/Toolbar.tsx
  frontend/src/container/TopNav/AutoRefresh/index.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss
  frontend/src/container/TopNav/DateTimeSelectionV2/Refresh.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/styles.ts
  frontend/src/lib/getMinMax.ts
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/store/actions/global.ts
  frontend/src/types/actions/globalTime.ts
Labels: enhancement

#4344 fix: validate password on paste, change
  frontend/src/api/utils.ts
  frontend/src/components/WelcomeLeftContainer/styles.ts
  frontend/src/container/ResetPassword/ResetPassword.test.tsx
  frontend/src/container/ResetPassword/index.tsx
  frontend/src/container/ResetPassword/styles.ts
Labels: bug

#4287 [Feat]: soft min and soft max in uplot chart
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/MetricsApplication/MetricsApplication.factory.ts
  frontend/src/container/NewDashboard/ComponentsSlider/index.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphContainer.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/index.tsx
  frontend/src/container/NewWidget/LeftContainer/index.tsx
  frontend/src/container/NewWidget/RightContainer/constants.ts
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/NewWidget/types.ts
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
  frontend/src/hooks/dashboard/utils.ts
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
  frontend/src/lib/uPlotLib/utils/getYAxisScale.test.ts
  frontend/src/lib/uPlotLib/utils/getYAxisScale.ts
  frontend/src/types/api/dashboard/getAll.ts
Labels: enhancement

#3776 chore: add signozspanmetrics delta temporality pipeline
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker-swarm/clickhouse-setup/otel-collector-metrics-config.yaml
  deploy/docker/clickhouse-setup/docker-compose-core.yaml
  deploy/docker/clickhouse-setup/docker-compose-local.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/otel-collector-metrics-config.yaml
  pkg/query-service/app/opamp/config.yaml
  pkg/query-service/app/opamp/otelconfig/config_parser_test.go
  pkg/query-service/app/opamp/otelconfig/testdata/basic.yaml
  pkg/query-service/app/opamp/otelconfig/testdata/service.yaml
  pkg/query-service/tests/test-deploy/docker-compose.yaml
  pkg/query-service/tests/test-deploy/otel-collector-config.yaml
  pkg/query-service/tests/test-deploy/otel-collector-metrics-config.yaml
Labels: chore

#4335 Fix: FE: pipelines: should be able to exit edit mode without making a change
  frontend/src/container/PipelinePage/PipelineListsView/PipelineListsView.tsx
  frontend/src/container/PipelinePage/PipelineListsView/SaveConfigButton.tsx
  frontend/src/container/PipelinePage/PipelineListsView/styles.ts
Labels: bug

#4351 fix: soft min and soft max undefined issue
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
Labels: bug

#4346 fix: empty string search doesn't return all exceptions
  frontend/src/container/AllError/index.tsx
Labels: bug

#4348 feat: logs list view changes
  frontend/src/components/Logs/ListLogView/ListLogView.styles.scss
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/ListLogView/styles.ts
  frontend/src/components/Logs/LogLinesActionButtons/LogLinesActionButtons.styles.scss
  frontend/src/components/Logs/LogLinesActionButtons/LogLinesActionButtons.tsx
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/RawLogView/styles.ts
  frontend/src/container/LogsExplorerContext/types.ts
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsTable/index.tsx
  frontend/src/container/LogsTable/logsTable.styles.scss
  frontend/src/container/QueryBuilder/components/ToolbarActions/ToolbarActions.styles.scss
  frontend/src/container/TopNav/AutoRefreshV2/AutoRefreshV2.styles.scss
  frontend/src/container/TopNav/AutoRefreshV2/config.ts
  frontend/src/container/TopNav/AutoRefreshV2/index.tsx
  frontend/src/container/TopNav/AutoRefreshV2/styles.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/utils/logs.ts
Labels: enhancement

#4353 feat: new table view for logs explorer list section
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/TableView/config.ts
  frontend/src/components/Logs/TableView/styles.ts
  frontend/src/components/Logs/TableView/useTableView.styles.scss
  frontend/src/components/Logs/TableView/useTableView.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/TableRow.styles.scss
  frontend/src/container/LogsExplorerList/InfinityTableView/TableRow.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/config.ts
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/styles.ts
  frontend/src/types/reducer/globalTime.ts
Labels: enhancement

#4360 fix: type errors with respect to new date time
  frontend/src/components/Logs/RawLogView/styles.ts
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/LogsSearchFilter/utils.ts
  frontend/src/container/ServiceApplication/types.ts
  frontend/src/container/TopNav/AutoRefresh/config.ts
  frontend/src/container/TopNav/AutoRefreshV2/config.ts
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
  frontend/src/hooks/useQueryService.ts
  frontend/src/lib/dashboard/getQueryResults.ts
  frontend/src/lib/getStartEndRangeTime.ts
Labels: bug

#4363 feat: handle light theme for logs explorer design changes
  frontend/src/components/Logs/ListLogView/ListLogView.styles.scss
  frontend/src/components/Logs/LogLinesActionButtons/LogLinesActionButtons.styles.scss
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/RawLogView/styles.ts
  frontend/src/components/Logs/RawLogView/types.ts
  frontend/src/components/Logs/TableView/config.ts
  frontend/src/components/Logs/TableView/styles.ts
  frontend/src/components/Logs/TableView/useTableView.styles.scss
  frontend/src/components/Logs/TableView/useTableView.tsx
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/styles.ts
  frontend/src/container/TopNav/AutoRefreshV2/AutoRefreshV2.styles.scss
  frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/utils/logs.ts
Labels: enhancement

#4370 feat: integrate date time selector across app
  frontend/src/components/ExplorerCard/ExplorerCard.tsx
  frontend/src/container/EditRules/index.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/container/TopNav/index.tsx
  frontend/src/container/Trace/Search/styles.ts
Labels: enhancement

#4372 feat: handle the query builder design changes across the application
  frontend/src/components/ExplorerCard/ExplorerCard.tsx
  frontend/src/container/FormAlertRules/QuerySection.styles.scss
  frontend/src/container/FormAlertRules/QuerySection.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QuerySection.styles.scss
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/QueryBuilder/components/ToolbarActions/ToolbarActions.styles.scss
  frontend/src/pages/TracesExplorer/TracesExplorer.styles.scss
  frontend/src/pages/TracesExplorer/index.tsx
Labels: enhancement

#4371 fix: update correct format in URL in case of custom date time
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
Labels: bug

#4367 feat: custom date time value
  frontend/src/components/CustomTimePicker/CustomTimePicker.styles.scss
  frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
  frontend/src/styles.scss
Labels: enhancement

#4378 fix: virtuoso scroll refresh issue
  frontend/src/container/LogsExplorerViews/index.tsx
Labels: bug

#4361 chore: add /v4/query_range endpoint
  ee/query-service/app/server.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metrics/v4/cumulative/table.go
  pkg/query-service/app/metrics/v4/cumulative/table_test.go
  pkg/query-service/app/metrics/v4/cumulative/timeseries.go
  pkg/query-service/app/metrics/v4/cumulative/timeseries_test.go
  pkg/query-service/app/metrics/v4/delta/helper.go
  pkg/query-service/app/metrics/v4/delta/table.go
  pkg/query-service/app/metrics/v4/delta/table_test.go
  pkg/query-service/app/metrics/v4/delta/time_series_test.go
  pkg/query-service/app/metrics/v4/delta/timeseries.go
  pkg/query-service/app/metrics/v4/helpers/clauses.go
  pkg/query-service/app/metrics/v4/helpers/sub_query.go
  pkg/query-service/app/metrics/v4/query_builder.go
  pkg/query-service/app/metrics/v4/query_builder_test.go
  pkg/query-service/app/server.go
  pkg/query-service/common/metrics.go
  pkg/query-service/model/v3/v3.go
Labels: chore

#4384 fix: set max 6 months for user entered time
  frontend/src/components/CustomTimePicker/CustomTimePicker.styles.scss
  frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
Labels: bug

#4380 feat: [GH-4325]: update the URL time query params when zoom in and zoom out of charts
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
Labels: enhancement

#4386 feat: handle new typing changes for date time picker v2
  frontend/src/components/CustomTimePicker/CustomTimePicker.styles.scss
  frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
  frontend/src/components/CustomTimePicker/CustomTimePickerPopoverContent.tsx
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/styles.scss
Labels: enhancement

#4385 fix: autosave layout to layout change
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/GridCardLayout/WidgetHeader/WidgetHeader.styles.scss
  frontend/src/container/GridCardLayout/utils.ts
Labels: bug, request-more-info

#4388 fix: [GH-4383]: handle special characters in the services name
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/ServiceApplication/Columns/GetColumnSearchProps.tsx
Labels: bug

#4390 fix: button visibility in clickhouse and promQL headers
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/QueryHeader.tsx
Labels: bug

#4316 [feat]: persistence of graph toggle on variable change
  frontend/src/container/FullViewHeader/FullViewHeader.styles.scss
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCard/types.ts
Labels: enhancement

#4393 fix: allow workspace blocked users to extend trial
  frontend/src/container/OnboardingContainer/Steps/DataSource/DataSource.tsx
  frontend/src/container/OnboardingContainer/common/ModuleStepsContainer/ModuleStepsContainer.tsx
  frontend/src/container/OnboardingContainer/context/OnboardingContext.tsx
  frontend/src/pages/WorkspaceLocked/WorkspaceLocked.styles.scss
  frontend/src/pages/WorkspaceLocked/WorkspaceLocked.tsx
Labels: bug, request-more-info

#4396 Revert "[Feat]: added iscolumn in option rendering"
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/OptionRenderer.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/container/QueryBuilder/type.ts
  frontend/src/hooks/queryBuilder/useOptions.ts
Labels: enhancement

#4389 chore: styles improvement across new design
  frontend/src/components/CustomTimePicker/CustomTimePicker.styles.scss
  frontend/src/components/CustomTimePicker/CustomTimePickerPopoverContent.tsx
  frontend/src/container/FormAlertRules/QuerySection.styles.scss
  frontend/src/container/FormAlertRules/QuerySection.tsx
  frontend/src/container/FormAlertRules/styles.ts
  frontend/src/container/LogsExplorerTable/LogsExplorerTable.styles.scss
  frontend/src/container/LogsExplorerTable/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/QueryHeader.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QuerySection.styles.scss
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/LeftContainer/styles.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss
  frontend/src/lib/query/createTableColumnsFromQuery.ts
  frontend/src/pages/LogsExplorer/index.tsx
Labels: bug, chore

#4397 fix: update time stamp on the first load in URL to help with back navigation
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
Labels: bug

#4398 Revert "fix: update time stamp on the first load in URL to help with back navigation"
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
Labels: bug

#4387 chore: update onboarding events
  frontend/src/container/OnboardingContainer/OnboardingContainer.tsx
  frontend/src/container/OnboardingContainer/Steps/ConnectionStatus/ConnectionStatus.tsx
  frontend/src/container/OnboardingContainer/Steps/DataSource/DataSource.tsx
  frontend/src/container/OnboardingContainer/Steps/EnvironmentDetails/EnvironmentDetails.tsx
  frontend/src/container/OnboardingContainer/Steps/LogsConnectionStatus/LogsConnectionStatus.tsx
  frontend/src/container/OnboardingContainer/Steps/MarkdownStep/MarkdownStep.tsx
  frontend/src/container/OnboardingContainer/Steps/SelectMethod/SelectMethod.tsx
  frontend/src/container/OnboardingContainer/common/ModuleStepsContainer/ModuleStepsContainer.tsx
  frontend/src/hooks/analytics/useAnalytics.tsx
Labels: chore

#4399 chore: add tenantId and orgName in usage
  ee/query-service/app/server.go
  ee/query-service/model/usage.go
  ee/query-service/usage/manager.go
Labels: enhancement

#4403 fix: trial banner moving to left screen and breaking trace detail page
  frontend/src/container/AppLayout/styles.ts
Labels: bug

#4405 fix: back btn navigation on first load
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
  frontend/src/store/actions/trace/getInitialFilter.ts
  frontend/src/store/actions/trace/util.ts
Labels: bug

#4392 feat: save view for new design
  frontend/src/container/ExplorerOptions/ExplorerOptions.styles.scss
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/pages/TracesExplorer/index.tsx
Labels: enhancement

#4406 [Fix]: Resolve glitch in graph due to variable and time stamp change
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/types.ts
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCard/types.ts
Labels: bug

#4408 fix: logs page crash when special chars present in the value of query
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/utils.ts
Labels: bug, testing-deploy

#4407 feat: update styles for logs detail view
  frontend/src/components/LogDetail/LogDetails.styles.scss
  frontend/src/components/LogDetail/index.tsx
  frontend/src/components/Logs/LogStateIndicator/LogStateIndicator.styles.scss
  frontend/src/components/Logs/LogStateIndicator/LogStateIndicator.tsx
  frontend/src/components/Logs/RawLogView/styles.ts
  frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.styles.scss
  frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.tsx
  frontend/src/container/LogDetailedView/Overview.styles.scss
  frontend/src/container/LogDetailedView/Overview.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
Labels: enhancement

#4417 fix: reset env on data source select, set logo center aligned
  frontend/src/container/FullScreenHeader/FullScreenHeader.styles.scss
  frontend/src/container/FullScreenHeader/FullScreenHeader.tsx
  frontend/src/container/OnboardingContainer/OnboardingContainer.tsx
  frontend/src/container/OnboardingContainer/Steps/DataSource/DataSource.tsx
  frontend/src/pages/WorkspaceLocked/WorkspaceLocked.tsx
Labels: bug, request-more-info

#4423 feat: added log attributes in the raw view old designs
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/RawLogView/types.ts
  frontend/src/container/LiveLogs/LiveLogsList/index.tsx
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsTable/index.tsx
  frontend/src/container/OptionsMenu/MaxLinesField/styles.ts
  frontend/src/container/OptionsMenu/index.tsx
Labels: enhancement

#4427 fix: update search logic in dashboard to search for title, description, tags
  frontend/src/AppRoutes/index.tsx
  frontend/src/AppRoutes/routes.ts
  frontend/src/container/ListOfDashboard/utils.ts
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
Labels: bug

#4428 fix: custom time width and refresh text visibility issues
  frontend/src/components/CustomTimePicker/CustomTimePicker.styles.scss
  frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
  frontend/src/container/TopNav/DateTimeSelection/DateTimeSelection.styles.scss
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
  frontend/src/container/TopNav/DateTimeSelection/styles.ts
Labels: bug

#4422 feat: add raw view attributes in the logs list view
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/RawLogView/styles.ts
  frontend/src/components/Logs/RawLogView/types.ts
  frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.styles.scss
  frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.tsx
  frontend/src/container/LiveLogs/LiveLogsList/index.tsx
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsTable/index.tsx
Labels: enhancement

#4426 fix: logs UI improvements
  frontend/src/components/CustomTimePicker/CustomTimePicker.styles.scss
  frontend/src/components/CustomTimePicker/CustomTimePickerPopoverContent.tsx
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/LogStateIndicator/LogStateIndicator.styles.scss
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/TableView/types.ts
  frontend/src/components/Logs/TableView/useTableView.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsExplorerViews/LogsExplorerViews.styles.scss
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/Toolbar/Toolbar.styles.scss
  frontend/src/container/Toolbar/Toolbar.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/container/TopNav/index.tsx
  frontend/src/lib/getMinMax.ts
  frontend/src/pages/LogsExplorer/index.tsx
Labels: bug

#4429 fix: center align the dashboard delete modal
  frontend/src/container/ListOfDashboard/TableComponents/DeleteButton.styles.scss
  frontend/src/container/ListOfDashboard/TableComponents/DeleteButton.tsx
Labels: bug

#4381 chore: add functions support
  pkg/query-service/app/having.go
  pkg/query-service/app/having_test.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/http_handler_test.go
  pkg/query-service/app/limit.go
  pkg/query-service/app/limit_test.go
  pkg/query-service/app/queryBuilder/functions.go
  pkg/query-service/app/queryBuilder/functions_test.go
  pkg/query-service/app/reduce_to.go
  pkg/query-service/app/reduce_to_test.go
  pkg/query-service/model/v3/v3.go
Labels: chore

#4355 fix: Logs UI: querybuildersearch: avoid emptying out query on sourceKeys update if tags are yet to be populated
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
Labels: bug

#4437 fix: [GH-4434]: dashboard variables performance issues
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
Labels: bug

#4382 chore: support p9{9,5,0},75,50 for space aggregation
  pkg/query-service/app/metrics/v4/query_builder.go
  pkg/query-service/app/metrics/v4/query_builder_test.go
  pkg/query-service/model/v3/v3.go
Labels: chore

#4438 fix: variable selection flow - dependent variable option not updated …
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.styles.scss
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
Labels: bug

#4447 chore: include subscription status
  ee/query-service/app/api/api.go
  ee/query-service/app/api/license.go
Labels: chore

#4441 feat: users should choose either to broadcast all or enter specific channels to alert
  frontend/public/locales/en-GB/alerts.json
  frontend/public/locales/en-GB/rules.json
  frontend/public/locales/en/alerts.json
  frontend/public/locales/en/rules.json
  frontend/src/container/CreateAlertRule/SelectAlertType/index.tsx
  frontend/src/container/FormAlertRules/BasicInfo.tsx
  frontend/src/container/FormAlertRules/ChannelSelect/index.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/types/api/alerts/def.ts
Labels: enhancement

#4448 feat: [GH-4436]: date range enhancements
  frontend/src/components/CustomTimePicker/CustomTimePicker.styles.scss
  frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
  frontend/src/components/CustomTimePicker/CustomTimePickerPopoverContent.tsx
  frontend/src/container/TopNav/DateTimeSelection/DateTimeSelection.styles.scss
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
  frontend/src/container/TopNav/DateTimeSelection/styles.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
Labels: enhancement

#4449 feat: update UI
  frontend/public/Icons/loading-plane.gif
  frontend/public/Icons/tetra-pack.svg
  frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.styles.scss
  frontend/src/container/LogsExplorerChart/LogsExplorerChart.styled.ts
  frontend/src/container/LogsExplorerChart/index.tsx
  frontend/src/container/LogsExplorerList/LogsExplorerList.style.scss
  frontend/src/container/LogsExplorerViews/LogsExplorerViews.styles.scss
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/TimeSeriesView/TimeSeriesView.styles.scss
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/container/TopNav/index.tsx
  frontend/src/pages/LogsModulePage/LogsModulePage.tsx
  frontend/src/pages/Pipelines/Pipelines.styles.scss
  frontend/src/pages/Pipelines/index.tsx
Labels: enhancement, request-more-info

#4453 feat: show total items count in table
  frontend/src/components/ResizeTable/ResizeTable.tsx
Labels: enhancement

#4452 feat: added loading and error states for logs design
  frontend/public/Icons/awwSnap.svg
  frontend/public/Icons/emptyState.svg
  frontend/public/Icons/tetra-pack.svg
  frontend/src/container/EmptyLogsSearch/EmptyLogsSearch.styles.scss
  frontend/src/container/EmptyLogsSearch/EmptyLogsSearch.tsx
  frontend/src/container/LogsError/LogsError.styles.scss
  frontend/src/container/LogsError/LogsError.tsx
  frontend/src/container/LogsExplorerList/Error.tsx
  frontend/src/container/LogsExplorerList/LogsExplorerList.interfaces.ts
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsExplorerTable/LogsExplorerTable.interfaces.ts
  frontend/src/container/LogsExplorerTable/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsLoading/LogsLoading.styles.scss
  frontend/src/container/LogsLoading/LogsLoading.tsx
  frontend/src/container/NoLogs/NoLogs.styles.scss
  frontend/src/container/TimeSeriesView/TimeSeriesView.styles.scss
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
  frontend/src/container/TimeSeriesView/styles.ts
Labels: enhancement

#4409 [Refactor]: Tab Switch deplay issue and UI improvement for Clickhouse
  frontend/src/container/FormAlertRules/QuerySection.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/QueryHeader.styles.scss
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/QueryHeader.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/query.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/styles.ts
Labels: frontend

#4459 fix: close delete modal on delete success
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/GridCardLayout/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/NewWidget/styles.ts
Labels: bug, request-more-info

#4465 fix: set light background for full screen in dashboard
  frontend/src/container/GridCardLayout/GridCardLayout.styles.scss
  frontend/src/container/SideNav/SideNav.tsx
Labels: bug

#4467 fix: update only showTotal property by spreading pagination object
  frontend/src/components/ResizeTable/ResizeTable.tsx
Labels: bug, request-more-info

#4473 Revert "fix: Logs UI: querybuildersearch: avoid emptying out query on sourceKeys update if tags are yet to be populated "
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
Labels: bug

#4474 Release v0.38.1
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
Labels: request-more-info

#4476 feat: show info message in general settings for cloud users to reacho…
  frontend/src/container/GeneralSettingsCloud/GeneralSettingsCloud.styles.scss
  frontend/src/container/GeneralSettingsCloud/GeneralSettingsCloud.tsx
  frontend/src/container/GeneralSettingsCloud/index.tsx
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/pages/Settings/config.ts
  frontend/src/pages/Settings/utils.ts
Labels: enhancement
