Repository SigNoz/signoz, pull requests merged in 2024-03, with the labels that each got.

#4599 feat: add support for email alert channel
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose-core.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  ee/query-service/model/plans.go
  frontend/public/locales/en/channels.json
  frontend/src/api/channels/createEmail.ts
  frontend/src/api/channels/editEmail.ts
  frontend/src/api/channels/testEmail.ts
  frontend/src/container/CreateAlertChannels/config.ts
  frontend/src/container/CreateAlertChannels/defaults.ts
  frontend/src/container/CreateAlertChannels/index.tsx
  frontend/src/container/CreateAlertRule/defaults.ts
  frontend/src/container/EditAlertChannels/index.tsx
  frontend/src/container/FormAlertChannels/Settings/Email.tsx
  frontend/src/container/FormAlertChannels/index.tsx
  frontend/src/pages/ChannelsEdit/index.tsx
  frontend/src/types/api/channels/createEmail.ts
  frontend/src/types/api/channels/editEmail.ts
  pkg/query-service/README.md
  pkg/query-service/model/featureSet.go
  pkg/query-service/rules/manager.go
  pkg/query-service/tests/test-deploy/docker-compose.yaml
  pkg/query-service/utils/labels/labels.go
Labels: enhancement

#4635 fix: update date picker styles
  frontend/src/components/CustomTimePicker/CustomTimePickerPopoverContent.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
Labels: bug

#4636 fix: default version to v4 if version param not present in url params
  frontend/src/container/CreateAlertRule/index.tsx
Labels: bug

#4638 chore: update APM metrics to use v4 query range
  frontend/src/api/metrics/getQueryRange.ts
  frontend/src/constants/app.ts
  frontend/src/container/CreateAlertRule/defaults.ts
  frontend/src/container/CreateAlertRule/index.tsx
  frontend/src/container/FormAlertRules/QuerySection.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/types.ts
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCard/types.ts
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/MetricsApplication/MetricsPageQueries/DBCallQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/ExternalQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/MetricsPageQueriesFactory.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/OverviewQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/TopOperationQueries.ts
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/ApDexMetrics.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/ApDexTraces.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ServiceOverview.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/TopLevelOperations.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/TopOperationMetrics.tsx
  frontend/src/container/MetricsApplication/Tabs/types.ts
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/filters/HavingFilter/HavingFilter.tsx
  frontend/src/container/ServiceApplication/ServiceMetrics/ServiceMetricTable.tsx
  frontend/src/container/ServiceApplication/ServiceMetrics/ServiceMetricsQuery.ts
  frontend/src/hooks/queryBuilder/useQueryBuilderOperations.ts
  frontend/src/mocks-server/handlers.ts
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
  frontend/src/types/common/queryBuilder.ts
  pkg/query-service/app/formula.go
  pkg/query-service/app/parser_test.go
  pkg/query-service/model/v3/v3.go
Labels: chore

#4619 fix: [SIG-538]: dashboard variables reset on tab visibility change
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx
  frontend/src/providers/Dashboard/Dashboard.tsx
  frontend/src/providers/Dashboard/types.ts
Labels: bug

#4644 fix: [SIG-532]: Copy Log Link Functionality for new designs
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/ListLogView/styles.ts
  frontend/src/components/Logs/RawLogView/styles.ts
  frontend/src/components/Logs/TableView/types.ts
  frontend/src/container/LiveLogs/LiveLogsList/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/styles.ts
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/hooks/logs/useCopyLogLink.ts
Labels: bug

#4595 feat: [SIG-526]: UI Integrations V0
  frontend/package.json
  frontend/public/Icons/redis-logo.svg
  frontend/public/locales/en/titles.json
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/api/Integrations/getAllIntegrations.ts
  frontend/src/api/Integrations/getIntegration.ts
  frontend/src/api/Integrations/getIntegrationStatus.ts
  frontend/src/api/Integrations/installIntegration.ts
  frontend/src/api/Integrations/uninstallIntegration.ts
  frontend/src/components/MarkdownRenderer/MarkdownRenderer.tsx
  frontend/src/constants/routes.ts
  frontend/src/container/SideNav/menuItems.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/hooks/Integrations/useGetAllIntegrations.ts
  frontend/src/hooks/Integrations/useGetIntegration.ts
  frontend/src/hooks/Integrations/useGetIntegrationStatus.ts
  frontend/src/pages/Integrations/Header.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContent.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContentTabs/Configure.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContentTabs/DataCollected.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContentTabs/IntegrationDetailContentTabs.styles.scss
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContentTabs/Overview.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailHeader.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailPage.styles.scss
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailPage.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationsUninstallBar.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/TestConnection.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/utils.ts
  frontend/src/pages/Integrations/Integrations.styles.scss
  frontend/src/pages/Integrations/Integrations.tsx
  frontend/src/pages/Integrations/IntegrationsList.tsx
  frontend/src/pages/Integrations/index.ts
  frontend/src/pages/Integrations/utils.ts
  frontend/src/pages/IntegrationsMarketPlace/IntegrationsMarketPlace.tsx
  frontend/src/pages/IntegrationsMarketPlace/index.ts
  frontend/src/pages/IntegrationsModulePage/IntegrationsModulePage.styles.scss
  frontend/src/pages/IntegrationsModulePage/IntegrationsModulePage.tsx
  frontend/src/pages/IntegrationsModulePage/constants.tsx
  frontend/src/pages/IntegrationsModulePage/index.ts
  frontend/src/types/api/integrations/types.ts
  frontend/src/utils/permission/index.ts
  frontend/yarn.lock
Labels: enhancement

#4617 feat: add clone query functionality
  frontend/src/container/QueryBuilder/QueryBuilder.styles.scss
  frontend/src/container/QueryBuilder/components/QBEntityOptions/QBEntityOptions.tsx
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/style.ts
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/types/common/queryBuilder.ts
Labels: enhancement

#4660 fix: [SIG-549]: bring the ts config for pre-commit hook in sync with github CI
  frontend/scripts/typecheck-staged.sh
Labels: bug, chore

#4659 chore: [SIG-526]: Improve the light theme designs for integrations UI
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContentTabs/IntegrationDetailContentTabs.styles.scss
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailPage.styles.scss
  frontend/src/pages/Integrations/Integrations.styles.scss
Labels: chore

#4600 feat: route to the onboarding flow when clicking the sending logs in case of no logs
  frontend/public/locales/en/titles.json
  frontend/src/AppRoutes/routes.ts
  frontend/src/constants/routes.ts
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/NoLogs/NoLogs.tsx
  frontend/src/container/OnboardingContainer/OnboardingContainer.tsx
  frontend/src/container/OnboardingContainer/utils/dataSourceUtils.ts
  frontend/src/container/TopNav/DateTimeSelection/config.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/utils/permission/index.ts
Labels: enhancement

#4661 chore: minor integrations UI cleanups
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContentTabs/Overview.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationsUninstallBar.tsx
  frontend/src/types/api/integrations/types.ts
Labels: chore

#4607 feat: support for timeshift in logs
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metrics/v4/query_builder.go
  pkg/query-service/app/querier/helper.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/querier/v2/helper.go
  pkg/query-service/app/queryBuilder/query_builder.go
Labels: enhancement

#4677 fix: update the md file for integrations config
  pkg/query-service/app/integrations/builtin_integrations/mongo/config/configure-otel-collector.md
  pkg/query-service/app/integrations/builtin_integrations/mongo/config/prerequisites.md
  pkg/query-service/app/integrations/builtin_integrations/postgres/config/configure-otel-collector.md
  pkg/query-service/app/integrations/builtin_integrations/postgres/config/prerequisites.md
  pkg/query-service/app/integrations/builtin_integrations/redis/config/configure-otel-collector.md
Labels: bug

#4658 feat: [SIG-543]: add time selection in the custom date selection
  frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
  frontend/src/components/CustomTimePicker/CustomTimePickerPopoverContent.tsx
  frontend/src/components/CustomTimePicker/RangePickerModal.styles.scss
  frontend/src/components/CustomTimePicker/RangePickerModal.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
Labels: enhancement

#4663 feat: [SIG-546]: user with viewer roles can only view saved views
  frontend/src/container/ExplorerOptions/ExplorerOptions.styles.scss
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/pages/SaveView/SaveView.styles.scss
  frontend/src/pages/SaveView/index.tsx
Labels: enhancement

#4669 fix: remove early return for services call in usage explorer
  frontend/src/store/actions/metrics/getService.ts
Labels: bug

#4665 chore: extract dashboard/alert query info and send event
  ee/query-service/app/server.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/model/response.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore, testing-deploy

#4678 fix: handle defaults for apm and aws
  frontend/src/container/OnboardingContainer/OnboardingContainer.tsx
  frontend/src/container/OnboardingContainer/utils/dataSourceUtils.ts
Labels: bug, request-more-info

#4668 fix: interpret missing point as zero value in formula evaluation
  pkg/query-service/app/formula.go
  pkg/query-service/app/formula_test.go
Labels: bug

#4666 chore: limit number of top level operations in services list
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/response.go
Labels: chore

#4648 chore: add day wise usage breakdown
  ee/query-service/app/api/license.go
Labels: chore

#4684 chore: dashboard info update
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#3245 feat: add support for alerting on absent metric
  frontend/public/locales/en-GB/alerts.json
  frontend/public/locales/en/alerts.json
  frontend/src/container/FormAlertRules/RuleOptions.tsx
  frontend/src/types/api/alerts/def.ts
  pkg/query-service/constants/constants.go
  pkg/query-service/rules/alerting.go
  pkg/query-service/rules/resultTypes.go
  pkg/query-service/rules/thresholdRule.go
  pkg/query-service/utils/labels/labels.go
Labels: enhancement

#4376 fix: [GH-3932]: do not retry API's in case of 4XX status code
  frontend/src/index.tsx
Labels: bug

#4379 feat: support case insensitive operators
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/utils.ts
Labels: enhancement

#4706 Release/v0.41.1
  frontend/src/constants/localStorage.ts
  frontend/src/container/ExplorerOptions/ExplorerOptionWrapper.tsx
  frontend/src/container/ExplorerOptions/ExplorerOptions.styles.scss
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/container/ExplorerOptions/ExplorerOptionsDroppableArea.styles.scss
  frontend/src/container/ExplorerOptions/ExplorerOptionsDroppableArea.tsx
  frontend/src/container/ExplorerOptions/utils.ts
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/pages/TracesExplorer/index.tsx
Labels: testing-deploy

#4707 chore(pre-release): 📌 pin versions: SigNoz 0.41.1
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
Labels: chore

#4708 feat: handled inactive tab handling by removing the display flex override
  frontend/src/pages/LogsModulePage/LogsModulePage.styles.scss
  frontend/src/pages/Pipelines/Pipelines.styles.scss
Labels: enhancement

#4709 feat: enabled variable selection in case of dashboard locked
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
Labels: enhancement

#4710 fix: context filter input overflow issue, min height for logs list view
  frontend/src/components/LogDetail/QueryBuilderSearchWrapper.styles.scss
  frontend/src/container/LogsExplorerList/LogsExplorerList.style.scss
Labels: bug

#4691 chore: remove share invite link message
  frontend/public/locales/en-GB/organizationsettings.json
  frontend/public/locales/en/organizationsettings.json
  frontend/src/container/OrganizationSettings/PendingInvitesContainer/index.tsx
  frontend/webpack.config.prod.js
Labels: chore

#4688 feat:php flow
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/Kubernetes/php-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/Kubernetes/php-kubernetes-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/Kubernetes/php-kubernetes-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxAMD64/QuickStart/php-linuxamd64-quickStart-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxAMD64/QuickStart/php-linuxamd64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxAMD64/Recommended/php-linuxamd64-recommended-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxAMD64/Recommended/php-linuxamd64-recommended-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxAMD64/Recommended/php-linuxamd64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxARM64/QuickStart/php-linuxarm64-quickStart-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxARM64/QuickStart/php-linuxarm64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxARM64/Recommended/php-linuxarm64-recommended-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxARM64/Recommended/php-linuxarm64-recommended-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/LinuxARM64/Recommended/php-linuxarm64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsAMD64/QuickStart/php-macosamd64-quickStart-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsAMD64/QuickStart/php-macosamd64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsAMD64/Recommended/php-macosamd64-recommended-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsAMD64/Recommended/php-macosamd64-recommended-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsAMD64/Recommended/php-macosamd64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsARM64/QuickStart/php-macosarm64-quickStart-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsARM64/QuickStart/php-macosarm64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsARM64/Recommended/php-macosarm64-recommended-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsARM64/Recommended/php-macosarm64-recommended-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/MacOsARM64/Recommended/php-macosarm64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/constants/apmDocFilePaths.ts
  frontend/src/container/OnboardingContainer/utils/dataSourceUtils.ts
Labels: enhancement

#4725 chore: update events
  ee/query-service/app/server.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/response.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#4720 fix: [SIG-567]: prevented stage-&-run API on legend change
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
  frontend/src/lib/uPlotLib/utils/getSeriesData.ts
Labels: bug

#4728 feat: implement download logs feature for logs explorer new design
  frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.styles.scss
  frontend/src/container/DownloadV2/DownloadV2.styles.scss
  frontend/src/container/DownloadV2/DownloadV2.tsx
  frontend/src/container/DownloadV2/DownloadV2.types.ts
  frontend/src/container/LogsExplorerViews/index.tsx
Labels: enhancement

#4736 feat: [SIG-571]: added support for has and nhas operator for json filter
  frontend/src/hooks/queryBuilder/useOperators.ts
Labels: enhancement

#4735 fix: [SIG-570]: query builder issue when - is present in free text seach
  frontend/src/hooks/queryBuilder/useTag.ts
Labels: bug

#4737 feat: [SIG-572]: allow number of lines changing in the logs list view
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/ListLogView/styles.ts
  frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.tsx
  frontend/src/container/LiveLogs/LiveLogsList/index.tsx
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsTable/index.tsx
Labels: enhancement

#4723 fix: [SIG-565]: design feedback for integrations
  frontend/public/Icons/cable-car.svg
  frontend/public/Icons/configure.svg
  frontend/public/Icons/group.svg
  frontend/src/assets/Integrations/ConfigureIcon.tsx
  frontend/src/constants/query.ts
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContent.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContentTabs/Configure.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContentTabs/DataCollected.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContentTabs/IntegrationDetailContentTabs.styles.scss
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailHeader.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailPage.styles.scss
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailPage.tsx
  frontend/src/pages/Integrations/Integrations.tsx
Labels: bug

#4733 (fix) send 403 on wrong password entry during change password operation
  pkg/query-service/app/http_handler.go
  pkg/query-service/auth/auth.go
  pkg/query-service/model/response.go
Labels: bug

#4697 feat: add ability to customize alert frequency
  frontend/public/locales/en-GB/alerts.json
  frontend/public/locales/en/alerts.json
  frontend/src/container/FormAlertRules/RuleOptions.tsx
  frontend/src/container/FormAlertRules/styles.ts
  frontend/src/pages/AlertList/index.tsx
  frontend/src/types/api/alerts/def.ts
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/thresholdRule.go
Labels: enhancement, frontend

#4726 [Fix]: Using exported dashboards as input to dashboard provisioning #2
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/types/api/dashboard/getAll.ts
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/dashboards/provision.go
Labels: frontend

#4747 fix: [SIG-574]: support __ in the groupBy clause
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
Labels: bug

#4749 fix: log chips not forming making filtering not work
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/hooks/queryBuilder/useTag.ts
Labels: bug

#4724 feat: [SIG-566]: Added message to alert user about their past due - subscription status
  frontend/public/locales/en/billings.json
  frontend/src/api/billing/getUsage.ts
  frontend/src/container/BillingContainer/BillingContainer.test.tsx
  frontend/src/container/BillingContainer/BillingContainer.tsx
Labels: enhancement

#4744 feat: [SIG-573]: Fixed billing page issues
  frontend/src/container/BillingContainer/BillingContainer.tsx
  frontend/src/container/BillingContainer/BillingUsageGraph/BillingUsageGraph.tsx
  frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
Labels: bug, enhancement

#4717 feat: show environments in a separate dropdown
  frontend/src/container/ResourceAttributesFilter/ResourceAttributesFilter.styles.scss
  frontend/src/container/ResourceAttributesFilter/ResourceAttributesFilter.tsx
  frontend/src/container/ResourceAttributesFilter/components/QueryChip/QueryChip.tsx
  frontend/src/container/ResourceAttributesFilter/styles.ts
  frontend/src/hooks/useResourceAttribute/ResourceProvider.tsx
  frontend/src/hooks/useResourceAttribute/types.ts
  frontend/src/hooks/useResourceAttribute/utils.ts
  frontend/src/pages/Services/Metrics.test.tsx
Labels: enhancement, frontend

#4752 chore: fix alerting options
  frontend/public/locales/en-GB/alerts.json
  frontend/public/locales/en/alerts.json
  frontend/src/container/FormAlertRules/RuleOptions.tsx
  frontend/src/types/api/alerts/def.ts
  pkg/query-service/rules/alerting.go
  pkg/query-service/rules/apiParams.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/promRule.go
  pkg/query-service/rules/promrule_test.go
  pkg/query-service/rules/thresholdRule.go
  pkg/query-service/rules/thresholdRule_test.go
Labels: bug, chore

#4748 fix: [SIG-575]: no data in new trace explorer page specific scenario
  frontend/src/container/OptionsMenu/constants.ts
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
Labels: bug

#4757 fix: 404 resource not found issues
  frontend/src/api/SAML/listAllDomain.ts
  frontend/src/api/queryBuilder/getAggregateAttribute.ts
  frontend/src/api/queryBuilder/getAttributeKeys.ts
  frontend/src/api/saveView/deleteView.ts
  frontend/src/api/saveView/getAllViews.ts
  frontend/src/api/saveView/saveView.ts
  frontend/src/api/saveView/updateView.ts
Labels: bug

#4618 feat: support drag select in chart - alerts page
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
Labels: enhancement, request-more-info

#4692 feat: add support to pin attributes in logs details view
  frontend/src/constants/localStorage.ts
  frontend/src/container/LogDetailedView/Overview.styles.scss
  frontend/src/container/LogDetailedView/TableView.styles.scss
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/ResourceAttributesFilter/ResourceAttributesFilter.styles.scss
  frontend/src/container/ResourceAttributesFilter/styles.ts
Labels: enhancement

#4760 fix: update devtool property to eval-source-map
  frontend/webpack.config.js
  frontend/webpack.config.prod.js
Labels: bug, request-more-info

#4761 feat: add events API
  ee/query-service/app/server.go
  ee/query-service/license/manager.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/server.go
  pkg/query-service/auth/auth.go
  pkg/query-service/dao/sqlite/rbac.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/telemetry/telemetry.go
Labels: enhancement

#4588 chore: send language and service name events as list
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#4764 fix: billing page crashes when all three signal data is not present
  frontend/src/container/BillingContainer/BillingUsageGraph/BillingUsageGraph.tsx
Labels: bug

#4758 [Refactor]: Table Grid Formula issue.
  frontend/src/lib/query/createTableColumnsFromQuery.ts
Labels: request-more-info

#4742 feat: update time range selection flows to handle relative and absolu…
  frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
  frontend/src/constants/query.ts
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/FormAlertRules/utils.ts
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/LogsExplorerChart/index.tsx
  frontend/src/container/LogsSearchFilter/utils.ts
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
  frontend/src/container/ServiceApplication/types.ts
  frontend/src/container/TopNav/AutoRefresh/config.ts
  frontend/src/container/TopNav/AutoRefreshV2/config.ts
  frontend/src/container/TopNav/DateTimeSelection/config.ts
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/hooks/logs/useCopyLogLink.ts
  frontend/src/hooks/useQueryService.ts
  frontend/src/lib/dashboard/getQueryResults.ts
  frontend/src/lib/getMinMax.ts
  frontend/src/lib/getStartEndRangeTime.ts
  frontend/src/store/actions/global.ts
  frontend/src/store/actions/trace/util.ts
  frontend/src/types/actions/globalTime.ts
  frontend/src/types/reducer/globalTime.ts
Labels: enhancement

#4768 feat: do not retry query range API's with i/o timeout error
  frontend/src/api/ErrorResponseHandler.ts
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/lib/dashboard/getQueryResults.ts
  frontend/src/types/api/index.ts
Labels: enhancement

#4772 fix: enrich all queries with non materialized attributes
  pkg/query-service/app/logs/v3/enrich_query.go
  pkg/query-service/app/logs/v3/enrich_query_test.go
Labels: bug

#4775 feat: allow characters in attribute names
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/logs/parser_test.go
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
  pkg/query-service/utils/format.go
Labels: enhancement
