Repository SigNoz/signoz, pull requests merged in 2024-04, with the labels that each got.

#4756 feat: add integrations to the side-nav for cloud users
  frontend/public/locales/en/titles.json
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/constants/routes.ts
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/container/SideNav/menuItems.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContent.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContentTabs/Configure.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContentTabs/IntegrationDetailContentTabs.styles.scss
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailHeader.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailPage.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationsUninstallBar.tsx
  frontend/src/pages/Integrations/Integrations.styles.scss
  frontend/src/pages/Integrations/Integrations.tsx
  frontend/src/pages/Integrations/utils.ts
  frontend/src/pages/IntegrationsModulePage/constants.tsx
  frontend/src/utils/permission/index.ts
Labels: enhancement, do not merge

#4784 fix: do not move to next step if env not selected in onboarding
  frontend/src/container/OnboardingContainer/common/ModuleStepsContainer/ModuleStepsContainer.tsx
Labels: bug

#4783 fix: hotfix bug in enhance query
  pkg/query-service/app/logs/v3/enrich_query.go
Labels: bug

#4785 chore: rate limit param
  pkg/query-service/app/http_handler.go
  pkg/query-service/model/queryParams.go
Labels: chore

#4786 feat: onboarding flow - enable users to submit request for a new data…
  frontend/src/api/common/logEvent.ts
  frontend/src/container/OnboardingContainer/Onboarding.styles.scss
  frontend/src/container/OnboardingContainer/Steps/DataSource/DataSource.styles.scss
  frontend/src/container/OnboardingContainer/Steps/DataSource/DataSource.tsx
  frontend/src/container/OnboardingContainer/Steps/EnvironmentDetails/EnvironmentDetails.tsx
  frontend/src/periscope.scss
  frontend/src/types/api/events/types.ts
  frontend/src/typings/window.ts
Labels: enhancement, request-more-info

#4791 fix: added dashboard and QB shortcuts to the shortcuts page
  frontend/src/constants/shortcuts/DashboardShortcuts.ts
  frontend/src/constants/shortcuts/QBShortcuts.ts
  frontend/src/pages/Shortcuts/utils.ts
Labels: bug

#4789 fix: sidenav items overlapping in small screens
  frontend/src/container/SideNav/SideNav.styles.scss
  frontend/src/container/SideNav/SideNav.tsx
Labels: bug

#4675 Dashboard Clean up and list view improvement.
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/styles.ts
  frontend/src/container/GridCardLayout/GridCard/FullView/types.ts
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCard/types.ts
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/GridPanelSwitch/index.tsx
  frontend/src/container/GridPanelSwitch/types.ts
  frontend/src/container/LogsPanelTable/LogsPanelComponent.tsx
  frontend/src/container/LogsPanelTable/utils.tsx
  frontend/src/container/MetricsApplication/MetricsApplication.factory.ts
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/ApDexMetrics.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/ApDexTraces.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ServiceOverview.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/TopLevelOperations.tsx
  frontend/src/container/MetricsApplication/styles.ts
  frontend/src/container/MetricsApplication/types.ts
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphContainer.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/index.tsx
  frontend/src/container/NewWidget/LeftContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/NewWidget/types.ts
  frontend/src/container/PanelWrapper/ListPanelWrapper.tsx
  frontend/src/container/PanelWrapper/PanelWrapper.tsx
  frontend/src/container/PanelWrapper/TablePanelWrapper.tsx
  frontend/src/container/PanelWrapper/UplotPanelWrapper.tsx
  frontend/src/container/PanelWrapper/ValuePanelWrapper.tsx
  frontend/src/container/PanelWrapper/constants.ts
  frontend/src/container/PanelWrapper/panelWrapper.types.ts
  frontend/src/container/TracesTableComponent/TracesTableComponent.tsx
Labels: request-more-info

#4795 fix: chunk load webpack error
  frontend/package.json
  frontend/webpack.config.prod.js
  frontend/yarn.lock
Labels: bug

#4802 fix: remove integrations page view and add event for the same
  frontend/src/pages/Integrations/Integrations.tsx
  frontend/src/pages/Integrations/utils.ts
Labels: bug

#4805 fix: incorrect error rate query
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#4807 fix: querier v2 synced and tablePanel result processor updated
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/querier/v2/helper.go
  pkg/query-service/app/querier/v2/querier.go
Labels: bug

#4808 chore: update events
  ee/query-service/app/server.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#4811 fix: app content overlapping sidenav
  frontend/src/container/AppLayout/AppLayout.styles.scss
  frontend/src/container/SideNav/SideNav.styles.scss
Labels: bug

#4799 chore: fixed java instructions
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Others/Kubernetes/others-kubernetes-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Others/LinuxAMD64/QuickStart/others-linuxamd64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Others/LinuxAMD64/Recommended/others-linuxamd64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Others/LinuxARM64/QuickStart/others-linuxarm64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Others/LinuxARM64/Recommended/others-linuxarm64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Others/MacOsAMD64/QuickStart/others-macosamd64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Others/MacOsAMD64/Recommended/others-macosamd64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Others/MacOsARM64/QuickStart/others-macosarm64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Others/MacOsARM64/Recommended/others-macosarm64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/Kubernetes/springBoot-kubernetes-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/LinuxAMD64/QuickStart/springBoot-linuxamd64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/LinuxAMD64/Recommended/springBoot-linuxamd64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/LinuxARM64/QuickStart/springBoot-linuxarm64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/LinuxARM64/Recommended/springBoot-linuxarm64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/MacOsAMD64/QuickStart/springBoot-macosamd64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/MacOsAMD64/Recommended/springBoot-macosamd64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/MacOsARM64/QuickStart/springBoot-macosarm64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/MacOsARM64/Recommended/springBoot-macosarm64-recommended-runApplication.md
Labels: bug, chore

#4812 fix: alerts tag popup vibrating
  frontend/src/components/TableRenderer/LabelColumn.tsx
  frontend/src/components/TableRenderer/utils.ts
Labels: bug

#4810 fix: [SIG-577]: QB functions - states not clearing
  frontend/src/container/QueryBuilder/components/QBEntityOptions/QBEntityOptions.tsx
Labels: bug

#4800 fix: [SIG-578]: changed color of function block connector
  frontend/src/container/QueryBuilder/components/QueryFunctions/QueryFunctions.styles.scss
Labels: bug

#4803 feat: retry on chunk load error
  frontend/.gitignore
  frontend/package.json
  frontend/src/components/Loadable/index.tsx
  frontend/src/constants/sessionStorage.ts
  frontend/src/container/ConfigDropdown/Config/index.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/lib/logql/reverseParser.ts
  frontend/src/utils/lazyWithRetries.ts
  frontend/webpack.config.js
  frontend/webpack.config.prod.js
  frontend/yarn.lock
Labels: enhancement, request-more-info, testing-deploy

#4813 feat: views toolbar visibility, light mode
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/container/SideNav/NavItem/NavItem.styles.scss
  frontend/src/container/SideNav/SideNav.styles.scss
Labels: enhancement, request-more-info

#4815 fix: sidebar jitter
  frontend/src/container/SideNav/NavItem/NavItem.styles.scss
  frontend/src/container/SideNav/SideNav.styles.scss
Labels: bug

#4821 fix: query range API validation
  pkg/query-service/model/v3/v3.go
Labels: bug

#4822 fix: avoid rate limiting heartbeat events
  pkg/query-service/telemetry/telemetry.go
Labels: bug

#4836 fix: time preference from the panel should be used to fetch data
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
Labels: bug

#4832 feat: revamp integration flow
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContent.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailHeader.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailPage.styles.scss
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailPage.tsx
  frontend/src/pages/Integrations/Integrations.tsx
Labels: enhancement

#4827 fix: added billing page condition to not show when its not either cloud or enterprise
  frontend/src/AppRoutes/index.tsx
  frontend/src/container/SideNav/SideNav.tsx
Labels: bug

#4759 feat: support of changing panel type in dashboards
  frontend/src/container/NewDashboard/ComponentsSlider/menuItems.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphContainer.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
  frontend/src/container/NewWidget/LeftContainer/index.tsx
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/NewWidget/utils.ts
  frontend/src/container/PanelWrapper/PanelWrapper.tsx
  frontend/src/container/PanelWrapper/UplotPanelWrapper.tsx
  frontend/src/container/PanelWrapper/panelWrapper.types.ts
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/types/common/queryBuilder.ts
Labels: enhancement

#4842 [Fix]: selected time in right container to be used in query-range
  frontend/src/container/NewWidget/LeftContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/NewWidget/types.ts
Labels: bug

#4844 fix: trace page breaking
  frontend/src/container/ExplorerOptions/ExplorerOptions.styles.scss
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/container/ExplorerOptions/ExplorerOptionsHideArea.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/providers/QueryBuilder.tsx
Labels: bug

#4778 feat: allow query restrictions for log queries
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/clickhouseReader/wrapper.go
  pkg/query-service/app/logs/v3/enrich_query.go
Labels: enhancement

#4751 Pie Chart Panel
  frontend/package.json
  frontend/src/constants/panelTypes.ts
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/GridCardLayout/GridCard/FullView/contants.ts
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridPanelSwitch/index.tsx
  frontend/src/container/GridPanelSwitch/types.ts
  frontend/src/container/NewDashboard/ComponentsSlider/constants.ts
  frontend/src/container/NewDashboard/ComponentsSlider/menuItems.tsx
  frontend/src/container/NewWidget/RightContainer/constants.ts
  frontend/src/container/NewWidget/utils.ts
  frontend/src/container/PanelWrapper/PiePanelWrapper.styles.scss
  frontend/src/container/PanelWrapper/PiePanelWrapper.tsx
  frontend/src/container/PanelWrapper/constants.ts
  frontend/src/container/PanelWrapper/panelWrapper.types.ts
  frontend/src/container/PanelWrapper/utils.ts
  frontend/src/utils/getGraphType.ts
  frontend/yarn.lock
Labels: request-more-info

#4854 fix: wrong payload being sent in the dashboard payload
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.test.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
  frontend/src/hooks/dashboard/useDashboardFromLocalStorage.tsx
  frontend/src/providers/Dashboard/Dashboard.tsx
  frontend/src/providers/Dashboard/types.ts
Labels: bug

#4828 chore: added test cases for Logs
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsExplorerViews/tests/LogsExplorerViews.test.tsx
  frontend/src/container/LogsExplorerViews/tests/mock.ts
  frontend/src/container/QueryBuilder/components/ToolbarActions/tests/ToolbarActions.test.tsx
  frontend/src/pages/LogsExplorer/__tests__/LogsExplorer.test.tsx
Labels: chore

#4829 fix: fixed sidenav alignment with and without get-started
  frontend/src/container/SideNav/NavItem/NavItem.styles.scss
Labels: bug

#4846 chore: use last 1day data for apdex latency metric meta
  ee/query-service/app/api/api.go
  ee/query-service/app/api/metrics.go
  ee/query-service/app/server.go
  frontend/src/api/metrics/ApDex/getMetricMeta.ts
  frontend/src/api/metrics/getMetricName.ts
  frontend/src/api/metrics/getResourceAttributes.ts
  frontend/src/container/MetricsApplication/constant.ts
  frontend/src/container/MetricsApplication/utils.ts
  frontend/src/hooks/useResourceAttribute/utils.ts
  frontend/src/mocks-server/handlers.ts
  frontend/src/types/api/metrics/getResourceAttributes.ts
  pkg/query-service/app/apdex.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metrics/query_builder.go
  pkg/query-service/app/metrics/query_builder_test.go
  pkg/query-service/app/parser/metrics.go
  pkg/query-service/app/parser_test.go
  pkg/query-service/app/server.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/utils/queryTemplate/vars.go
Labels: chore

#4852 chore(pre-release): 📌 pin versions: SigNoz 0.43.0, OtelCollector 0.88.20
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose-core.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  go.mod
  go.sum
  pkg/query-service/tests/test-deploy/docker-compose.yaml
Labels: chore

#4860 feat: show timestamp in list view of trace explorer
  frontend/src/container/TracesExplorer/ListView/utils.tsx
Labels: enhancement

#4875 fix: threshold getting cleared on stage and run query and user not able to create alert issue
  frontend/src/container/CreateAlertRule/index.tsx
  frontend/src/providers/Dashboard/Dashboard.tsx
Labels: bug

#4880 fix: handle the case where the functions are undefined in the query response
  frontend/src/container/QueryBuilder/components/QBEntityOptions/QBEntityOptions.tsx
Labels: bug

#4888 feat: [SIG-584]: moved facing issue btn tracking from trackEvent to logEvent
  frontend/src/container/OnboardingContainer/common/ModuleStepsContainer/ModuleStepsContainer.tsx
Labels: enhancement

#4890 fix: dashboard variable filters issue with dashboards containing older variable format
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx
Labels: bug

#4893 fix: billing container scroll issue when trial banner present
  frontend/src/container/BillingContainer/BillingContainer.styles.scss
Labels: bug

#4884 fix: do not save dashboard panel on creating a new panel if discard is pressed
  frontend/src/container/NewDashboard/ComponentsSlider/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/NewWidget/utils.ts
  frontend/src/pages/DashboardWidget/index.tsx
Labels: bug

#4894 feat: revamp the overview settings modal
  frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss
  frontend/src/container/NewDashboard/DashboardDescription/SettingsDrawer.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/container/NewDashboard/DashboardSettings/DashboardSettings.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/DashboardSettingsContent.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/General/AddTags/AddTags.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/General/AddTags/index.tsx
  frontend/src/container/NewDashboard/DashboardSettings/General/AddTags/styles.ts
  frontend/src/container/NewDashboard/DashboardSettings/General/GeneralSettings.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/General/index.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/index.tsx
  frontend/src/container/NewDashboard/DashboardSettings/index.tsx
Labels: enhancement

#4899 feat: [SIG-585]: Added facingIssueBtn at Dashboard list, detail and alert list, detail etc. pages
  frontend/src/components/ResizeTable/DynamicColumnTable.tsx
  frontend/src/components/ResizeTable/types.ts
  frontend/src/container/FormAlertRules/FormAlertRules.styles.scss
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/ListAlertRules/ListAlert.tsx
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/utils/facingIssueBtn/FacingIssueBtn.style.scss
  frontend/src/utils/facingIssueBtn/FacingIssueBtn.tsx
Labels: enhancement

#4907 fix: restrict visibility of facing-issue button to only cloud users with intercom setup
  frontend/src/components/ResizeTable/DynamicColumnTable.tsx
  frontend/src/components/ResizeTable/types.ts
  frontend/src/components/facingIssueBtn/FacingIssueBtn.style.scss
  frontend/src/components/facingIssueBtn/FacingIssueBtn.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/NewWidget/index.tsx
Labels: bug

#4908 fix(clickhouse): update endpoint of the healthcheck in deployment files
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose-core.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  pkg/query-service/tests/test-deploy/docker-compose.yaml
Labels: bug, testing-deploy

#4909 chore: pin SigNoz OtelCollector 0.88.21 and update ClickHouse dsn
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker-swarm/clickhouse-setup/prometheus.yml
  deploy/docker/clickhouse-setup/docker-compose-core.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/prometheus.yml
  go.mod
  go.sum
  pkg/query-service/app/opamp/otelconfig/testdata/basic.yaml
  pkg/query-service/config/prometheus.yml
  pkg/query-service/tests/test-deploy/docker-compose.yaml
  pkg/query-service/tests/test-deploy/otel-collector-config.yaml
  pkg/query-service/tests/test-deploy/prometheus.yml
Labels: chore

#4906 feat: follow ups for side panel section for dashboards
  frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/General/AddTags/AddTags.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/General/AddTags/index.tsx
  frontend/src/container/NewDashboard/DashboardSettings/General/AddTags/styles.ts
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx
Labels: enhancement

#4912 chore: bump SigNoz/prometheus from v1.10.1 to v1.11.0
  go.mod
  go.sum
Labels: chore

#4916 fix: rate in table panel
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/app/traces/v3/query_builder_test.go
Labels: bug

#4913 [Snyk] Security upgrade nginx from 1.25.2-alpine to 1.26-alpine
  frontend/Dockerfile
Labels: testing-deploy

#4341 [Snyk] Security upgrade axios from 1.6.2 to 1.6.4
  frontend/package.json
  frontend/yarn.lock
Labels: testing-deploy

#4920 chore: [SIG-583]: Jest coverage collection config
  frontend/jest.config.ts
  frontend/src/container/NewWidget/index.tsx
Labels: chore

#4921 feat: setup for new dashboard landing page
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/GridCardLayout/DashboardEmptyState/DashboardEmptyState.styles.scss
  frontend/src/container/GridCardLayout/DashboardEmptyState/DashboardEmptyState.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/GridCardLayout/index.tsx
  frontend/src/container/GridCardLayout/types.ts
  frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss
  frontend/src/container/NewDashboard/DashboardDescription/SettingsDrawer.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.styles.scss
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
Labels: enhancement

#4930 fix: dont enrich if non empty keys are not same
  pkg/query-service/app/logs/v3/enrich_query.go
  pkg/query-service/app/logs/v3/enrich_query_test.go
Labels: bug

#4929 feat: dashboard revamp changes follow ups
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/GridCardLayout/index.tsx
  frontend/src/container/ListOfDashboard/TableComponents/DeleteButton.tsx
  frontend/src/container/NewDashboard/ComponentsSlider/ComponentSlider.styles.scss
  frontend/src/container/NewDashboard/ComponentsSlider/index.tsx
  frontend/src/container/NewDashboard/ComponentsSlider/menuItems.tsx
  frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/container/NewDashboard/GridGraphs/index.tsx
  frontend/src/container/NewDashboard/index.tsx
Labels: enhancement

#4935 fix: metric limit works with cache
  pkg/query-service/app/limit.go
Labels: bug

#4934 fix: value panel restriction should be on enabled queries
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/v2/querier.go
  pkg/query-service/model/v3/v3.go
Labels: bug

#4806 feat: introducing collapsable rows for dashboards
  frontend/public/locales/en-GB/dashboard.json
  frontend/public/locales/en/dashboard.json
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/GridCardLayout/config.ts
  frontend/src/container/GridCardLayout/styles.ts
  frontend/src/container/NewWidget/index.tsx
  frontend/src/hooks/dashboard/utils.ts
  frontend/src/pages/DashboardWidget/index.tsx
  frontend/src/providers/Dashboard/Dashboard.tsx
  frontend/src/providers/Dashboard/types.ts
  frontend/src/providers/Dashboard/util.ts
  frontend/src/types/api/dashboard/getAll.ts
Labels: enhancement

#4942 chore: update facing issues text
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/ListAlertRules/ListAlert.tsx
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewWidget/index.tsx
Labels: chore
