Repository SigNoz/signoz, pull requests merged in 2024-02, with the labels that each got.

#4478 feat: all line series with same labels should have same color in a da…
  frontend/src/lib/getChartData.ts
  frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
  frontend/src/lib/uPlotLib/utils/generateColor.ts
  frontend/src/lib/uPlotLib/utils/getSeriesData.ts
Labels: enhancement

#4479 feat: handle loading states and incorporate UI feedback
  frontend/src/components/ResizeTable/ResizeTable.tsx
  frontend/src/container/LogDetailedView/Overview.tsx
  frontend/src/container/LogsExplorerList/LogsExplorerList.interfaces.ts
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsExplorerTable/index.tsx
  frontend/src/container/LogsExplorerViews/LogsExplorerViews.styles.scss
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsLoading/LogsLoading.styles.scss
  frontend/src/container/QueryBuilder/QueryBuilder.tsx
  frontend/src/container/TimeSeriesView/styles.ts
Labels: enhancement

#4472 feat: add typecheck on pre-commit hook
  frontend/package.json
  frontend/scripts/typecheck-staged.sh
Labels: enhancement

#4460 fix: custom range should be unique to pages
  frontend/src/container/TopNav/DateTimeSelection/config.ts
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
Labels: bug

#4484 fix: maintain existing pagination configs
  frontend/src/components/ResizeTable/ResizeTable.tsx
  frontend/src/container/GeneralSettingsCloud/GeneralSettingsCloud.tsx
  frontend/src/container/ServiceApplication/ServiceMetrics/ServiceMetricTable.tsx
  frontend/src/container/ServiceApplication/ServiceTraces/ServiceTracesTable.tsx
Labels: bug, request-more-info

#4483 fix: logs explorer issues
  frontend/src/components/ExplorerCard/test/ExplorerCard.test.tsx
  frontend/src/container/LogsExplorerList/LogsExplorerList.interfaces.ts
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/QueryBuilder/components/ToolbarActions/ToolbarActions.styles.scss
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/QueryBuilderSearch.styles.scss
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
Labels: bug

#4485 feat: support custom times unique to pages new design changes
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
Labels: enhancement

#4486 fix: loading states for list logs view
  frontend/src/container/LogsExplorerList/index.tsx
Labels: bug

#4446 feat: add alerts to explorer link in notification
  pkg/query-service/constants/constants.go
  pkg/query-service/rules/apiParams.go
  pkg/query-service/rules/thresholdRule.go
  pkg/query-service/rules/thresholdRule_test.go
Labels: enhancement

#4488 fix: make label compliant with prometheus spec
  pkg/query-service/rules/thresholdRule.go
Labels: bug

#3815 fix: remove sending_queue and retry_on_failure settings
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
  pkg/query-service/tests/test-deploy/otel-collector-config.yaml
Labels: bug, request-more-info

#4475 feat: [GH-1194]: support users with viewer roles to be able to mutate the dashboard variable values to customise views
  frontend/src/components/ResizeTable/DynamicColumnTable.syles.scss
  frontend/src/components/ResizeTable/DynamicColumnTable.tsx
  frontend/src/constants/localStorage.ts
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx
  frontend/src/hooks/dashboard/useDashboardFromLocalStorage.tsx
  frontend/src/providers/Dashboard/Dashboard.tsx
Labels: enhancement

#4495 fix: chart loading when scrolling logs
  frontend/src/components/Logs/LogLinesActionButtons/LogLinesActionButtons.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/pages/LogsExplorer/index.tsx
Labels: bug

#4496 fix: don't throw error while fetching orgname
  ee/query-service/usage/manager.go
Labels: bug

#4493 feat: setup the context for keyboard hotkeys
  frontend/src/AppRoutes/index.tsx
  frontend/src/constants/shortcuts/globalShortcuts.ts
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/hooks/hotkeys/__tests__/useKeyboardHotkeys.test.tsx
  frontend/src/hooks/hotkeys/useKeyboardHotkeys.tsx
Labels: enhancement

#4503 ci(testing-deploy): update workflow to handle force-push scenerio
  .github/workflows/testing-deployment.yaml
Labels: testing-deploy

#4492 chore: bump clickhouse-server to 24.1.2-alpine
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose-core.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  pkg/query-service/tests/test-deploy/docker-compose.yaml
Labels: chore

#4402 chore: add formula eval in query-service
  go.mod
  go.sum
  pkg/query-service/app/formula.go
  pkg/query-service/app/formula_test.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/parser_test.go
Labels: chore

#3140 docs: use the proper Node.js written convention form
  README.md
Labels: frontend, community-pr

#4445 chore: add time shift function and some refactoring
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/formula.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metrics/v4/cumulative/table_test.go
  pkg/query-service/app/metrics/v4/cumulative/timeseries.go
  pkg/query-service/app/metrics/v4/cumulative/timeseries_test.go
  pkg/query-service/app/metrics/v4/delta/table_test.go
  pkg/query-service/app/metrics/v4/delta/time_series_test.go
  pkg/query-service/app/metrics/v4/delta/timeseries.go
  pkg/query-service/app/metrics/v4/helpers/clauses.go
  pkg/query-service/app/metrics/v4/helpers/sub_query.go
  pkg/query-service/app/metrics/v4/query_builder.go
  pkg/query-service/app/metrics/v4/query_builder_test.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/querier/v2/querier.go
  pkg/query-service/app/queryBuilder/functions.go
  pkg/query-service/constants/constants.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/v3/v3.go
Labels: chore

#4461 fix: update prom rule to use range query
  frontend/src/container/FormAlertRules/RuleOptions.tsx
  pkg/query-service/pqlEngine/engine.go
  pkg/query-service/rules/promRule.go
  pkg/query-service/rules/promrule_test.go
  pkg/query-service/rules/thresholdRule.go
Labels: bug

#4514 fix: update the extend trial from default mailto client to notification panel
  frontend/src/pages/WorkspaceLocked/WorkspaceLocked.tsx
Labels: bug

#4510 fix: retain the current query on date time change
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/types/common/queryBuilder.ts
Labels: bug

#4516 feat: support cache in logs
  pkg/query-service/app/querier/helper.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/model/v3/v3.go
Labels: enhancement

#4526 [Fix]: delete formula issue
  frontend/src/container/QueryBuilder/components/Formula/Formula.tsx
  frontend/src/container/QueryBuilder/components/QBEntityOptions/QBEntityOptions.tsx
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
Labels: bug

#4532 fix: shortcuts break when there are multiple queries
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
Labels: bug

#4520 fix: old and new dashboards in sync with local storage
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx
  frontend/src/providers/Dashboard/Dashboard.tsx
Labels: bug

#4535 fix: button border color for tab in log explorer
  frontend/src/pages/LogsModulePage/LogsModulePage.styles.scss
Labels: bug

#4540 fix: orderby not working for attributes
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
Labels: bug

#4541 fix: number attributes not showing up in raw view
  frontend/src/components/Logs/RawLogView/index.tsx
Labels: bug

#4536 feat: show retention info for cloud users and show count next to team…
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/container/GeneralSettings/GeneralSettings.tsx
  frontend/src/container/GeneralSettings/Retention.tsx
  frontend/src/container/GeneralSettings/StatusMessage.tsx
  frontend/src/container/GeneralSettingsCloud/GeneralSettingsCloud.styles.scss
  frontend/src/container/OrganizationSettings/Members/index.tsx
  frontend/src/container/OrganizationSettings/PendingInvitesContainer/index.tsx
  frontend/src/pages/Settings/utils.ts
  frontend/src/styles.scss
Labels: enhancement

#4543 fix: relative time preferences not respected
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
Labels: bug

#4544 fix: added missing updated time on first load for back navigation
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
Labels: bug

#4542 feat: support zoom in for bar chart logs explorer
  frontend/src/container/LogsExplorerChart/index.tsx
Labels: enhancement

#4545 feat: add borders to keyboard shortcut and settings tables
  frontend/src/container/AllAlertChannels/AlertChannels.tsx
  frontend/src/container/IngestionSettings/IngestionSettings.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/index.tsx
  frontend/src/container/OrganizationSettings/Members/index.tsx
  frontend/src/container/OrganizationSettings/PendingInvitesContainer/index.tsx
  frontend/src/pages/Shortcuts/Shortcuts.styles.scss
  frontend/src/pages/Shortcuts/Shortcuts.tsx
Labels: enhancement

#4546 fix: date time value retain on location switch
  frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
  frontend/src/constants/shortcuts/globalShortcuts.ts
  frontend/src/constants/shortcuts/logsExplorerShortcuts.ts
  frontend/src/pages/Shortcuts/utils.ts
  frontend/src/utils/getUserOS.ts
Labels: bug

#4547 fix: invalid custom time value
  frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
Labels: bug

#4551 fix: disable cloud features for OSS
  frontend/src/utils/app.ts
Labels: bug, enhancement

#4552 fix: remove duplicate settings tab
  frontend/src/pages/Settings/utils.ts
Labels: bug, request-more-info

#4525 chore: add ExponentialHistogram support for metrics v4 query range
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
  pkg/query-service/app/metrics/v4/delta/time_series_test.go
  pkg/query-service/app/metrics/v4/delta/timeseries.go
  pkg/query-service/app/metrics/v4/helpers/clauses.go
  pkg/query-service/model/v3/v3.go
Labels: chore

#4554 fix: qb search not respecting the saved views panel type
  frontend/src/container/LogsExplorerViews/index.tsx
Labels: bug

#4555 feat: ui updates - traces explorer
  frontend/src/container/LogsContextList/LogsContextList.styles.scss
  frontend/src/container/LogsContextList/ShowButton.styles.scss
  frontend/src/container/LogsContextList/ShowButton.tsx
  frontend/src/container/TracesExplorer/Controls/styles.ts
  frontend/src/pages/TracesExplorer/TracesExplorer.styles.scss
  frontend/src/pages/TracesExplorer/index.tsx
  frontend/src/pages/TracesModulePage/TracesModulePage.styles.scss
  frontend/src/pages/TracesModulePage/TracesModulePage.tsx
Labels: enhancement

#4556 fix: dashboard panel light theme
  frontend/src/lib/logs/flatLogData.ts
  frontend/src/styles.scss
Labels: bug

#4557 feat: api management
  ee/query-service/app/api/api.go
  ee/query-service/app/api/pat.go
  ee/query-service/app/server.go
  ee/query-service/auth/auth.go
  ee/query-service/dao/interface.go
  ee/query-service/dao/sqlite/modelDao.go
  ee/query-service/dao/sqlite/pat.go
  ee/query-service/model/pat.go
  pkg/query-service/telemetry/telemetry.go
Labels: enhancement

#4553 chore: Added jest cases for logs explorer page
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/OptionsMenu/AddColumnField/index.tsx
  frontend/src/container/QueryBuilder/components/ToolbarActions/LeftToolbarActions.tsx
  frontend/src/container/TracesExplorer/ListView/utils.tsx
  frontend/src/mocks-server/__mockdata__/logs_query_range.ts
  frontend/src/pages/LogsExplorer/__tests__/LogsExplorer.test.tsx
Labels: chore

#4561 feat: open left nav items in new tab on cmd ctrl click
  frontend/src/AppRoutes/Private.tsx
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogsError/LogsError.tsx
  frontend/src/container/NoLogs/NoLogs.tsx
  frontend/src/container/SideNav/NavItem/NavItem.styles.scss
  frontend/src/container/SideNav/NavItem/NavItem.tsx
  frontend/src/container/SideNav/SideNav.tsx
Labels: enhancement

#4565 fix: change the order of local and distributed table
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#4524 API ingestion keys - CRUD
  frontend/jest.config.ts
  frontend/jest.setup.ts
  frontend/package.json
  frontend/public/locales/en-GB/routes.json
  frontend/public/locales/en-GB/titles.json
  frontend/public/locales/en/apiKeys.json
  frontend/public/locales/en/routes.json
  frontend/public/locales/en/titles.json
  frontend/src/AppRoutes/Private.tsx
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/api/APIKeys/createAPIKey.ts
  frontend/src/api/APIKeys/deleteAPIKey.ts
  frontend/src/api/APIKeys/getAPIKey.ts
  frontend/src/api/APIKeys/getAllAPIKeys.ts
  frontend/src/api/APIKeys/updateAPIKey.ts
  frontend/src/constants/routes.ts
  frontend/src/container/APIKeys/APIKeys.styles.scss
  frontend/src/container/APIKeys/APIKeys.test.tsx
  frontend/src/container/APIKeys/APIKeys.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/hooks/APIKeys/useGetAllAPIKeys.ts
  frontend/src/mocks-server/__mockdata__/apiKeys.ts
  frontend/src/pages/Settings/config.tsx
  frontend/src/pages/Settings/index.tsx
  frontend/src/pages/Settings/utils.ts
  frontend/src/periscope.scss
  frontend/src/types/api/pat/types.ts
  frontend/src/utils/permission/index.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: request-more-info

#4573 fix: address gaps in alert to notification link
  frontend/src/container/CreateAlertChannels/index.tsx
  pkg/query-service/rules/alerting.go
  pkg/query-service/rules/resultTypes.go
  pkg/query-service/rules/thresholdRule.go
Labels: bug

#4571 chore: update heartbeat, language event and add serviceName event
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/response.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#4581 fix: show expired token label
  frontend/src/container/APIKeys/APIKeys.tsx
Labels: bug

#4585 fix: date time value initialising to start of day in case of typing
  frontend/src/components/CustomTimePicker/CustomTimePickerPopoverContent.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
Labels: bug

#4584 fix: redirect old logs routes to new routes
  frontend/src/AppRoutes/Private.tsx
  frontend/src/AppRoutes/routes.ts
Labels: bug

#4590 fix: traceID link not opening from log details page
  frontend/src/container/LogDetailedView/TableView.tsx
Labels: bug

#4587 feat: send only required details in billing events
  frontend/src/container/BillingContainer/BillingContainer.tsx
Labels: enhancement

#4594 fix: update no logs text and link based on the data source
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/NoLogs/NoLogs.tsx
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
  frontend/src/container/TimeSeriesView/index.tsx
Labels: bug, request-more-info

#4596 fix: [SIG-528]: precommit typescript check for md files
  frontend/scripts/typecheck-staged.sh
  frontend/tsconfig.json
Labels: bug

#4597 feat: update naming to API keys to Access Tokens
  frontend/public/locales/en-GB/routes.json
  frontend/public/locales/en-GB/titles.json
  frontend/public/locales/en/apiKeys.json
  frontend/public/locales/en/routes.json
  frontend/public/locales/en/titles.json
  frontend/src/AppRoutes/routes.ts
  frontend/src/constants/routes.ts
  frontend/src/container/APIKeys/APIKeys.test.tsx
  frontend/src/container/APIKeys/APIKeys.tsx
Labels: enhancement

#4562 Feat: Bar chart
  frontend/jest.config.ts
  frontend/src/assets/Dashboard/BarIcon.tsx
  frontend/src/constants/panelTypes.ts
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/FormAlertRules/QuerySection.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/contants.ts
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridPanelSwitch/index.tsx
  frontend/src/container/GridPanelSwitch/types.ts
  frontend/src/container/ListAlertRules/ListAlert.tsx
  frontend/src/container/NewDashboard/ComponentsSlider/constants.ts
  frontend/src/container/NewDashboard/ComponentsSlider/menuItems.ts
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphContainer.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/index.tsx
  frontend/src/container/NewWidget/RightContainer/constants.ts
  frontend/src/container/QueryBuilder/QueryBuilder.tsx
  frontend/src/hooks/queryBuilder/useCreateAlerts.tsx
  frontend/src/hooks/queryBuilder/useGetQueryRange.ts
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
  frontend/src/lib/uPlotLib/utils/constants.ts
  frontend/src/lib/uPlotLib/utils/getAxes.ts
  frontend/src/lib/uPlotLib/utils/getRenderer.ts
  frontend/src/lib/uPlotLib/utils/getSeriesData.ts
  frontend/src/lib/uPlotLib/utils/tests/__mocks__/seriesData.ts
  frontend/src/lib/uPlotLib/utils/tests/__mocks__/uplotChartOptionsData.ts
  frontend/src/lib/uPlotLib/utils/tests/getSeriesData.test.ts
  frontend/src/lib/uPlotLib/utils/tests/getUplotChartOptions.test.ts
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/utils/getGraphType.ts
  frontend/src/utils/getSortedSeriesData.ts
Labels: enhancement

#4612 fix: remove unknown setting from connection string
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  pkg/query-service/tests/test-deploy/docker-compose.yaml
Labels: bug

#4613 fix: create PAT not null error
  ee/query-service/app/api/pat.go
  ee/query-service/dao/interface.go
  ee/query-service/dao/sqlite/pat.go
Labels: bug

#4458 feat: use attribute if present for json query
  pkg/query-service/app/logs/v3/enrich_query.go
  pkg/query-service/app/logs/v3/enrich_query_test.go
Labels: enhancement
