Repository SigNoz/signoz, pull requests merged in 2024-09, with the labels that each got.

#5816 chore: make the raw view the default view for logs
  frontend/src/container/OptionsMenu/constants.ts
  frontend/src/mocks-server/__mockdata__/logs_query_range.ts
  frontend/src/pages/LogsExplorer/__tests__/LogsExplorer.test.tsx
Labels: chore

#5828 chore: calculate start and end times from relative time and remove query params
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/pages/AlertDetails/AlertDetails.tsx
  frontend/src/pages/AlertDetails/hooks.tsx
Labels: chore

#5825 Feat/alert history remaining feats
  frontend/src/api/alerts/get.ts
  frontend/src/components/AlertDetailsFilters/Filters.tsx
  frontend/src/components/TabsAndFilters/TabsAndFilters.tsx
  frontend/src/constants/global.ts
  frontend/src/container/AlertHistory/Statistics/TopContributorsCard/TopContributorsCard.styles.scss
  frontend/src/container/AlertHistory/Timeline/Graph/Graph.tsx
  frontend/src/container/AlertHistory/Timeline/GraphWrapper/GraphWrapper.tsx
  frontend/src/container/AlertHistory/Timeline/Table/Table.styles.scss
  frontend/src/container/AlertHistory/Timeline/Table/Table.tsx
  frontend/src/container/AlertHistory/Timeline/Table/useTimelineTable.tsx
  frontend/src/container/AlertHistory/Timeline/constants.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/lib/uPlotLib/plugins/heatmapPlugin.ts
  frontend/src/pages/AlertDetails/AlertDetails.tsx
  frontend/src/pages/AlertDetails/AlertHeader/AlertState/AlertState.tsx
  frontend/src/pages/AlertDetails/hooks.tsx
  frontend/src/types/api/alerts/timelineGraph.ts
  frontend/src/types/api/alerts/timelineTable.ts
Labels: enhancement

#5835 fix: handle operator case change in query range api and client
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
Labels: bug

#5833 feat: alert history dropdown functionality
  frontend/src/api/alerts/create.ts
  frontend/src/api/alerts/delete.ts
  frontend/src/api/alerts/get.ts
  frontend/src/api/alerts/patch.ts
  frontend/src/api/alerts/put.ts
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/pages/AlertDetails/AlertDetails.tsx
  frontend/src/pages/AlertDetails/AlertHeader/ActionButtons/ActionButtons.tsx
  frontend/src/pages/AlertDetails/AlertHeader/AlertHeader.tsx
  frontend/src/pages/AlertDetails/hooks.tsx
Labels: enhancement

#5811 fix: fix logic for cache
  pkg/query-service/app/querier/helper.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/querier/v2/helper.go
  pkg/query-service/app/querier/v2/querier.go
  pkg/query-service/app/querier/v2/querier_test.go
Labels: bug

#5806 chore: make prepare task configurable
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/prom_rule.go
  pkg/query-service/rules/prom_rule_task.go
  pkg/query-service/rules/promrule_test.go
Labels: chore

#5851 chore: fixed hostmetrics dashboard link
  frontend/src/container/OnboardingContainer/Modules/AwsMonitoring/EC2InfrastructureMetrics/md-docs/LinuxAMD64/hostmetrics-configureHostmetricsJson.md
  frontend/src/container/OnboardingContainer/Modules/AwsMonitoring/EC2InfrastructureMetrics/md-docs/LinuxARM64/hostmetrics-configureHostmetricsJson.md
  frontend/src/container/OnboardingContainer/Modules/AwsMonitoring/EC2InfrastructureMetrics/md-docs/MacOsAMD64/hostmetrics-configureHostmetricsJson.md
  frontend/src/container/OnboardingContainer/Modules/AwsMonitoring/EC2InfrastructureMetrics/md-docs/MacOsARM64/hostmetrics-configureHostmetricsJson.md
  frontend/src/container/OnboardingContainer/Modules/AwsMonitoring/ECSEc2/md-docs/ecsEc2-createDaemonService.md
  frontend/src/container/OnboardingContainer/Modules/AwsMonitoring/ECSExternal/md-docs/ecsExternal-createDaemonService.md
  frontend/src/container/OnboardingContainer/Modules/InfrastructureMonitoring/Hostmetrics/md-docs/LinuxAMD64/hostmetrics-configureHostmetricsJson.md
  frontend/src/container/OnboardingContainer/Modules/InfrastructureMonitoring/Hostmetrics/md-docs/LinuxARM64/hostmetrics-configureHostmetricsJson.md
  frontend/src/container/OnboardingContainer/Modules/InfrastructureMonitoring/Hostmetrics/md-docs/MacOsAMD64/hostmetrics-configureHostmetricsJson.md
  frontend/src/container/OnboardingContainer/Modules/InfrastructureMonitoring/Hostmetrics/md-docs/MacOsARM64/hostmetrics-configureHostmetricsJson.md
Labels: bug, chore

#5844 fix: use better value for threshold value in alert description
  pkg/query-service/rules/prom_rule.go
  pkg/query-service/rules/promrule_test.go
  pkg/query-service/rules/threshold_rule.go
  pkg/query-service/rules/threshold_rule_test.go
Labels: bug

#5852 Fix: UI feedback changes
  frontend/src/container/AlertHistory/Timeline/Timeline.styles.scss
  frontend/src/pages/AlertDetails/AlertDetails.styles.scss
  frontend/src/pages/AlertDetails/AlertHeader/ActionButtons/ActionButtons.tsx
Labels: bug

#5867 fix: broken links
  frontend/src/container/OnboardingContainer/Modules/AwsMonitoring/EKS/eks-monitorUsingDashboard.md
Labels: bug

#5869 chore: update posthog-js to 1.160.3
  frontend/package.json
  frontend/yarn.lock
Labels: chore

#5799 feat: implement quick filters for the new logs explorer page
  frontend/src/components/QuickFilters/FilterRenderers/Checkbox/Checkbox.styles.scss
  frontend/src/components/QuickFilters/FilterRenderers/Checkbox/Checkbox.tsx
  frontend/src/components/QuickFilters/FilterRenderers/Slider/Slider.styles.scss
  frontend/src/components/QuickFilters/FilterRenderers/Slider/Slider.tsx
  frontend/src/components/QuickFilters/QuickFilters.styles.scss
  frontend/src/components/QuickFilters/QuickFilters.tsx
  frontend/src/constants/localStorage.ts
  frontend/src/container/QueryBuilder/QueryBuilder.styles.scss
  frontend/src/container/QueryBuilder/QueryBuilder.tsx
  frontend/src/container/QueryBuilder/components/QBEntityOptions/QBEntityOptions.styles.scss
  frontend/src/container/QueryBuilder/components/QBEntityOptions/QBEntityOptions.tsx
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/components/ToolbarActions/LeftToolbarActions.tsx
  frontend/src/container/QueryBuilder/components/ToolbarActions/ToolbarActions.styles.scss
  frontend/src/container/QueryBuilder/components/ToolbarActions/tests/ToolbarActions.test.tsx
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
  frontend/src/container/Toolbar/Toolbar.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/hooks/queryBuilder/useQueryBuilderOperations.ts
  frontend/src/pages/LogsExplorer/LogsExplorer.styles.scss
  frontend/src/pages/LogsExplorer/__tests__/LogsExplorer.test.tsx
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/pages/LogsExplorer/utils.ts
  frontend/src/pages/LogsExplorer/utils.tsx
  frontend/src/pages/TracesExplorer/__test__/TracesExplorer.test.tsx
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/types/common/queryBuilder.ts
Labels: enhancement

#5831 fix: strip starting and ending quotes from field value on copy to cli…
  frontend/src/container/LogDetailedView/TableView/TableViewActions.tsx
Labels: bug

#5860 feat: show RPS message only if user is on trail and trail is not converted to sub
  frontend/src/container/ServiceApplication/ServiceMetrics/ServiceMetricTable.tsx
  frontend/src/container/ServiceApplication/ServiceTraces/ServiceTracesTable.tsx
Labels: enhancement

#5863 feat: show add credit card chat icon only to logged in users
  frontend/src/container/AppLayout/index.tsx
Labels: enhancement

#5847 fix: added default fallback for selectedColumns, when the attributeKeys call gives empty
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
Labels: bug

#5850 chore: hide old trace explorer cta btn from trace explorer page
  frontend/src/pages/TracesExplorer/index.tsx
Labels: chore

#5837 fix: added start and end time info text to educate user better around the schedule timelines
  frontend/src/container/PlannedDowntime/PlannedDowntime.styles.scss
  frontend/src/container/PlannedDowntime/PlannedDowntimeForm.tsx
  frontend/src/container/PlannedDowntime/PlannedDowntimeutils.ts
Labels: bug

#5871 chore: dashboard detail - panel data fetched - telemetry
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCard/utils.ts
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
Labels: chore

#5870 chore: calculate user count dynamically and set user role in identity…
  pkg/query-service/dao/sqlite/connection.go
  pkg/query-service/dao/sqlite/rbac.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#5872 feat: logsV4 resource table query builder
  pkg/query-service/app/logs/v4/query_builder.go
  pkg/query-service/app/logs/v4/resource_query_builder.go
  pkg/query-service/app/logs/v4/resource_query_builder_test.go
  pkg/query-service/utils/format.go
Labels: enhancement

#5807 chore: make ee init rule manager with it's own prepareTask func
  ee/query-service/app/server.go
  ee/query-service/rules/manager.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/prom_rule_task.go
  pkg/query-service/rules/rule_task.go
  pkg/query-service/rules/task.go
Labels: chore

#5845 chore: alert state change and overall status
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/migrate/migate.go
  pkg/query-service/model/alerting.go
  pkg/query-service/model/v3/v3.go
  pkg/query-service/rules/alerting.go
  pkg/query-service/rules/api_params.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/prom_rule.go
  pkg/query-service/rules/prom_rule_task.go
  pkg/query-service/rules/rule.go
  pkg/query-service/rules/rule_task.go
  pkg/query-service/rules/threshold_rule.go
Labels: chore

#5896 fix: make the config isColumn (for attribute keys) false for all the filters
  frontend/src/pages/LogsExplorer/utils.tsx
Labels: bug

#5902 fix: use inactive for empty alert state
  pkg/query-service/model/alerting.go
Labels: bug

#5892 fix: make header sticky for table panel
  frontend/src/container/GridPanelSwitch/index.tsx
  frontend/src/container/GridTableComponent/index.tsx
  frontend/src/container/GridTableComponent/types.ts
  frontend/src/container/LogsExplorerTable/index.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/TopOperationMetrics.tsx
  frontend/src/container/PanelWrapper/TablePanelWrapper.tsx
  frontend/src/container/PanelWrapper/__tests__/__snapshots__/TablePanelWrapper.test.tsx.snap
  frontend/src/container/QueryTable/QueryTable.intefaces.ts
  frontend/src/container/QueryTable/QueryTable.styles.scss
  frontend/src/container/QueryTable/QueryTable.tsx
  frontend/src/container/TracesExplorer/TableView/index.tsx
Labels: bug

#5901 chore: remove ee references in MIT licensed code
  .github/workflows/build.yaml
  .scripts/commentLinesForSetup.sh
  Makefile
  ee/query-service/constants/constants.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/preferences/model.go
  pkg/query-service/constants/constants.go
Labels: chore

#5626 fix: make the trace table row act as an anchor tag
  frontend/src/container/TracesExplorer/ListView/utils.tsx
Labels: bug

#5453 feat: preserve last used saved view in explorer pages
  frontend/src/constants/localStorage.ts
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/container/ExplorerOptions/constants.ts
  frontend/src/container/ExplorerOptions/types.ts
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
Labels: enhancement

#5910 chore: segment oss
  pkg/query-service/constants/constants.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore, request-more-info

#5827 feat: apply resource filters on coming from service details to traces page
  frontend/src/container/MetricsApplication/Tabs/util.ts
  frontend/src/container/MetricsApplication/TopOperationsTable.tsx
  frontend/src/hooks/useResourceAttribute/utils.ts
Labels: enhancement

#5864 feat: add resource_deployment_environment as fast filter in traces page
  frontend/src/pages/TracesExplorer/Filter/Section.tsx
  frontend/src/pages/TracesExplorer/Filter/filterUtils.ts
  frontend/src/pages/TracesExplorer/__test__/testUtils.ts
Labels: enhancement

#5849 chore: add base rule and consolidate common logic
  ee/query-service/app/server.go
  ee/query-service/rules/manager.go
  pkg/query-service/app/server.go
  pkg/query-service/rules/base_rule.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/prom_rule.go
  pkg/query-service/rules/prom_rule_task.go
  pkg/query-service/rules/promrule_test.go
  pkg/query-service/rules/queriers.go
  pkg/query-service/rules/rule.go
  pkg/query-service/rules/rule_task.go
  pkg/query-service/rules/threshold_rule.go
  pkg/query-service/rules/threshold_rule_test.go
Labels: chore

#5918 fix: use just keys to check the filters rather than the whole attribute key object
  frontend/src/components/QuickFilters/FilterRenderers/Checkbox/Checkbox.tsx
  frontend/src/providers/QueryBuilder.tsx
Labels: bug

#5920 fix: label assignment issue in promql rules
  pkg/query-service/rules/prom_rule.go
Labels: bug

#5887 fix: loading and no-data states showing in loading state of alert edit/overview
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
Labels: bug

#5895 fix: add support for long texts in alert history page
  frontend/src/pages/AlertDetails/AlertHeader/AlertHeader.tsx
  frontend/src/periscope/components/KeyValueLabel/KeyValueLabel.tsx
  frontend/src/periscope/components/LineClampedText/LineClampedText.styles.scss
  frontend/src/periscope/components/LineClampedText/LineClampedText.tsx
  frontend/src/periscope/components/TrimmedText/TrimmedText.tsx
Labels: bug

#5240 chore: json logs for collector
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
Labels: chore

#5930 feat: use new schema flag
  ee/query-service/app/api/api.go
  ee/query-service/app/db/reader.go
  ee/query-service/app/server.go
  ee/query-service/main.go
  ee/query-service/rules/manager.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/v2/querier.go
  pkg/query-service/app/server.go
  pkg/query-service/main.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/threshold_rule.go
  pkg/query-service/rules/threshold_rule_test.go
  pkg/query-service/tests/integration/test_utils.go
Labels: enhancement

#5241 chore: use json formatting for ClickHouse logs
  deploy/docker-swarm/clickhouse-setup/clickhouse-config.xml
  deploy/docker/clickhouse-setup/clickhouse-config.xml
Labels: chore

#5912 feat: logs list API, logic update for better perf
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/v2/querier.go
  pkg/query-service/utils/logs.go
  pkg/query-service/utils/logs_test.go
Labels: enhancement

#5961 fix: dashboard list page showing older data
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
Labels: bug

#5923 chore: update the filter in / filter out operators
  frontend/src/components/Logs/AddToQueryHOC.tsx
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogDetailedView/TableView/TableViewActions.tsx
  frontend/src/container/LogDetailedView/index.tsx
  frontend/src/hooks/logs/useActiveLog.ts
Labels: chore

#5772 feat: group by severity logs explorer page by default
  frontend/src/components/Graph/utils.ts
  frontend/src/container/LogsExplorerChart/LogsExplorerChart.interfaces.ts
  frontend/src/container/LogsExplorerChart/index.tsx
  frontend/src/container/LogsExplorerChart/utils.ts
  frontend/src/container/LogsExplorerViews/LogsExplorerViews.styles.scss
  frontend/src/container/LogsExplorerViews/index.tsx
Labels: enhancement

#5962 chore: deprecate clarity from frontend code
  .github/workflows/build.yaml
  .github/workflows/push.yaml
  frontend/src/AppRoutes/index.tsx
  frontend/src/index.html.ejs
  frontend/src/typings/window.ts
  frontend/webpack.config.js
  frontend/webpack.config.prod.js
Labels: chore

#5917 chore: move traces builder query attributes enrichment before query prep
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/querier/helper.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/querier/v2/helper.go
  pkg/query-service/app/querier/v2/querier.go
  pkg/query-service/app/querier/v2/querier_test.go
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/app/server.go
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/app/traces/v3/query_builder_test.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/rules/threshold_rule.go
Labels: chore

#5967 feat: collect telemetry for ch log queries in alerts and dashboards
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/model/response.go
  pkg/query-service/rules/db.go
  pkg/query-service/telemetry/telemetry.go
Labels: enhancement

#5946 fix: missing related logs or traces links in alert notification
  pkg/query-service/rules/base_rule.go
  pkg/query-service/rules/promrule_test.go
  pkg/query-service/rules/threshold_rule_test.go
  pkg/query-service/rules/threshold_rule_test_data.go
Labels: bug

#5628 chore: improve error message readability
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/v2/querier.go
Labels: chore

#5856 chore: add anomaly provider interface
  ee/query-service/anomaly/daily.go
  ee/query-service/anomaly/hourly.go
  ee/query-service/anomaly/params.go
  ee/query-service/anomaly/provider.go
  ee/query-service/anomaly/seasonal.go
  ee/query-service/anomaly/weekly.go
  pkg/query-service/model/v3/v3.go
Labels: chore

#5932 chore: move some structs out of v3
  ee/query-service/app/db/metrics.go
  pkg/query-service/app/clickhouseReader/query_progress/inmemory_tracker.go
  pkg/query-service/app/clickhouseReader/query_progress/tracker.go
  pkg/query-service/app/clickhouseReader/query_progress/tracker_test.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/alerting.go
  pkg/query-service/model/logs.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/model/response.go
  pkg/query-service/model/v3/v3.go
  pkg/query-service/rules/base_rule.go
  pkg/query-service/rules/prom_rule.go
  pkg/query-service/rules/rule.go
  pkg/query-service/rules/threshold_rule.go
Labels: chore

#5953 fix: do not use removed column in traces clickhouse query
  frontend/src/container/CreateAlertRule/defaults.ts
Labels: bug

#5960 feat: add support to configure units for pie chart values
  frontend/src/container/NewWidget/RightContainer/constants.ts
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/container/PanelWrapper/PiePanelWrapper.tsx
Labels: enhancement

#5935 chore: move analytics related methods from CH reader to their own mod…
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/explorer/db.go
  pkg/query-service/dao/sqlite/connection.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#5968 feat: send last log line time stamp for timestamp order-by desc
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/lib/dashboard/prepareQueryRangePayload.ts
Labels: enhancement

#5972 chore: remove the jest-playwright-test unused package causing axios vulnerability
  frontend/package.json
  frontend/yarn.lock
Labels: chore

#5982 fix: use proper tableName
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#5983 Fix/iscolumn
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#5984 fix: add limits to suggestion query
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#5934 chore: move channel management from CH reader to rule DB
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/integrations/alertManager/manager.go
  pkg/query-service/integrations/alertManager/notifier.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/response.go
  pkg/query-service/rules/db.go
  pkg/query-service/rules/manager.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#5925 chore: add enrichment in threshold rule
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/logs/v3/enrich_query.go
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/app/traces/v3/utils.go
  pkg/query-service/common/query_range.go
  pkg/query-service/constants/constants.go
  pkg/query-service/contextlinks/links.go
  pkg/query-service/model/logs.go
  pkg/query-service/rules/alerting.go
  pkg/query-service/rules/base_rule.go
  pkg/query-service/rules/threshold_rule.go
  pkg/query-service/rules/threshold_rule_test.go
  pkg/query-service/rules/threshold_rule_test_data.go
Labels: chore

#5974 chore: use mean of past, past2 and past3 seasons for growth
  ee/query-service/anomaly/daily.go
  ee/query-service/anomaly/hourly.go
  ee/query-service/anomaly/params.go
  ee/query-service/anomaly/seasonal.go
  ee/query-service/anomaly/weekly.go
  pkg/query-service/model/v3/v3.go
Labels: chore

#5992 fix: use new table for default alerts
  frontend/src/container/CreateAlertRule/defaults.ts
Labels: bug

#5991 chore: add request dashboard issue template
  .github/ISSUE_TEMPLATE/request_dashboard.md
Labels: chore

#5997 fix: add back temlemetry for dashboard with logs queries
  pkg/query-service/app/dashboards/model.go
Labels: bug

#5990 fix: exists/nexists support for top level columns
  pkg/query-service/app/logs/v4/query_builder.go
  pkg/query-service/app/logs/v4/query_builder_test.go
Labels: bug

#5954 chore: update calendly link
  frontend/src/pages/Support/Support.tsx
Labels: chore

#6004 fix: added safety check for query filter items
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
  frontend/src/pages/LogsExplorer/index.tsx
Labels: bug

#5937 chore: hide usage explorer and update over 100rps warning
  frontend/public/locales/en-GB/services.json
  frontend/public/locales/en/services.json
  frontend/src/container/ServiceApplication/ServiceMetrics/ServiceMetricTable.tsx
  frontend/src/container/ServiceApplication/ServiceTraces/ServiceTracesTable.tsx
  frontend/src/container/SideNav/menuItems.tsx
Labels: chore

#5938 chore: add note on data refresh in billing
  frontend/src/container/BillingContainer/BillingContainer.styles.scss
  frontend/src/container/BillingContainer/BillingContainer.tsx
Labels: chore

#6029 chore: update dashboard contributing doc and issue template
  .github/ISSUE_TEMPLATE/request_dashboard.md
  CONTRIBUTING.md
Labels: chore

#6009 fix: added time range key for query and local storage handling
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.test.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
Labels: bug, DO NOT MERGE

#6018 fix: issues with like and ilike fixed in v4 qb
  pkg/query-service/app/logs/v4/query_builder.go
  pkg/query-service/app/logs/v4/query_builder_test.go
  pkg/query-service/app/logs/v4/resource_query_builder.go
  pkg/query-service/app/logs/v4/resource_query_builder_test.go
Labels: bug

#6032 chore: improve colors for the log line indicators and group by severity_text
  frontend/src/components/Logs/LogStateIndicator/LogStateIndicator.styles.scss
  frontend/src/container/LogsExplorerChart/utils.ts
Labels: chore

#5929 feat: add last option to alert condition match type
  frontend/public/locales/en-GB/alerts.json
  frontend/public/locales/en-GB/rules.json
  frontend/public/locales/en/alerts.json
  frontend/public/locales/en/rules.json
  frontend/src/container/FormAlertRules/RuleOptions.tsx
  pkg/query-service/rules/alerting.go
  pkg/query-service/rules/base_rule.go
  pkg/query-service/rules/threshold_rule_test.go
Labels: enhancement

#6035 fix: fixed dashboard header and list title alignment
  frontend/src/container/ListOfDashboard/DashboardList.styles.scss
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
Labels: bug

#5893 feat: added global search on table panel
  frontend/src/container/GridCardLayout/GridCard/FullView/WidgetFullView.styles.scss
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/WidgetHeader/WidgetHeader.styles.scss
  frontend/src/container/GridCardLayout/WidgetHeader/index.tsx
  frontend/src/container/GridTableComponent/types.ts
  frontend/src/container/PanelWrapper/PanelWrapper.tsx
  frontend/src/container/PanelWrapper/TablePanelWrapper.tsx
  frontend/src/container/PanelWrapper/panelWrapper.types.ts
  frontend/src/container/QueryTable/QueryTable.intefaces.ts
  frontend/src/container/QueryTable/QueryTable.tsx
  frontend/src/container/QueryTable/__test__/QueryTable.test.tsx
  frontend/src/container/QueryTable/__test__/mocks.ts
Labels: enhancement, work in progress

#6034 fix: tlemetry for dashboard/alerts/views using contains on attributes
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/explorer/db.go
  pkg/query-service/model/response.go
  pkg/query-service/rules/db.go
  pkg/query-service/telemetry/telemetry.go
Labels: bug

#6043 fix: alerts links are broken when there is a space in value
  frontend/src/hooks/queryBuilder/useGetCompositeQueryParam.ts
Labels: bug

#6046 fix: invalidate the cache for the alerts rules post update call
  frontend/src/container/FormAlertRules/index.tsx
Labels: bug

#6008 chore: add support for caching multiple time ranges for cache key
  pkg/query-service/app/querier/helper.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/querier/v2/helper.go
  pkg/query-service/app/querier/v2/querier.go
  pkg/query-service/app/querier/v2/querier_test.go
  pkg/query-service/common/query_range.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/querycache/query_range_cache.go
  pkg/query-service/querycache/query_range_cache_test.go
Labels: chore

#6047 fix: export as csv for logs and traces table panel type
  frontend/src/container/GridTableComponent/index.tsx
Labels: bug

#5771 feat: added new tab for infra metrics in logs detailed page
  frontend/src/components/DraggableTableRow/tests/DraggableTableRow.test.tsx
  frontend/src/components/LogDetail/constants.ts
  frontend/src/components/LogDetail/index.tsx
  frontend/src/container/LogDetailedView/InfraMetrics/InfraMetrics.styles.scss
  frontend/src/container/LogDetailedView/InfraMetrics/InfraMetrics.tsx
  frontend/src/container/LogDetailedView/InfraMetrics/NodeMetrics.tsx
  frontend/src/container/LogDetailedView/InfraMetrics/PodMetrics.tsx
  frontend/src/container/LogDetailedView/InfraMetrics/constants.ts
  frontend/src/container/LogsExplorerViews/tests/LogsExplorerViews.test.tsx
  frontend/src/container/PipelinePage/Layouts/ChangeHistory/tests/ChangeHistory.test.tsx
  frontend/src/container/PipelinePage/tests/AddNewPipeline.test.tsx
  frontend/src/container/PipelinePage/tests/AddNewProcessor.test.tsx
  frontend/src/container/PipelinePage/tests/DeleteAction.test.tsx
  frontend/src/container/PipelinePage/tests/DragAction.test.tsx
  frontend/src/container/PipelinePage/tests/EditAction.test.tsx
  frontend/src/container/PipelinePage/tests/PipelineActions.test.tsx
  frontend/src/container/PipelinePage/tests/PipelineExpandView.test.tsx
  frontend/src/container/PipelinePage/tests/PipelineListsView.test.tsx
  frontend/src/container/PipelinePage/tests/PipelinePageLayout.test.tsx
  frontend/src/container/PipelinePage/tests/TagInput.test.tsx
  frontend/src/container/PipelinePage/tests/utils.test.ts
  frontend/src/lib/dashboard/getQueryResults.ts
  frontend/src/lib/dashboard/prepareQueryRangePayload.ts
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
  frontend/src/pages/LogsExplorer/__tests__/LogsExplorer.test.tsx
Labels: enhancement

#5952 feat: enable the search v2 for logs explorer page and remove FF
  ee/query-service/model/plans.go
  frontend/src/container/LogExplorerQuerySection/index.tsx
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
Labels: enhancement

#6045 feat: support for case insensitive for contains and like queries
  pkg/query-service/app/logs/v4/query_builder.go
  pkg/query-service/app/logs/v4/query_builder_test.go
  pkg/query-service/app/logs/v4/resource_query_builder.go
  pkg/query-service/app/logs/v4/resource_query_builder_test.go
Labels: enhancement

#6051 fix: telemetry nil pointer error fix
  pkg/query-service/telemetry/telemetry.go
Labels: bug

#6052 fix: light mode design for new query builder search
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.styles.scss
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/Suggestions.styles.scss
Labels: bug

#6054 fix: the tag key flickering when moving from traces to logs
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.styles.scss
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/Suggestions.styles.scss
Labels: bug

#5973 feat: add anomaly rule
  ee/query-service/anomaly/params.go
  ee/query-service/anomaly/seasonal.go
  ee/query-service/app/api/api.go
  ee/query-service/app/api/queryrange.go
  ee/query-service/app/server.go
  ee/query-service/model/plans.go
  ee/query-service/rules/anomaly.go
  ee/query-service/rules/manager.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/common/query_range.go
  pkg/query-service/model/featureSet.go
  pkg/query-service/rules/alerting.go
  pkg/query-service/rules/api_params.go
  pkg/query-service/rules/base_rule.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/prom_rule.go
  pkg/query-service/rules/prom_rule_task.go
  pkg/query-service/rules/promrule_test.go
  pkg/query-service/rules/rule.go
  pkg/query-service/rules/rule_task.go
  pkg/query-service/rules/threshold_rule.go
  pkg/query-service/rules/threshold_rule_test.go
Labels: enhancement, chore

#6055 chore: handle error before using task
  pkg/query-service/rules/manager.go
Labels: chore

#6049 fix: fixed extra space at bottom for list and table panel
  frontend/src/container/GridCardLayout/styles.ts
  frontend/src/container/LogsPanelTable/LogsPanelComponent.styles.scss
  frontend/src/container/TracesTableComponent/TracesTableComponent.styles.scss
Labels: bug

#6038 fix: dashboard variable - ux and usability fixes
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.styles.scss
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
Labels: bug

#6059 fix: added support for `body contains X` tag on pressing enter after selecting attribute key
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
Labels: bug

#6077 feat: enable new logs schema by default
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/docker-compose-local.yaml
  deploy/docker/clickhouse-setup/docker-compose.testing.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
  pkg/query-service/tests/test-deploy/docker-compose.yaml
  pkg/query-service/tests/test-deploy/otel-collector-config.yaml
Labels: enhancement

#5684 feat: added blur event to having input in query section
  frontend/src/container/QueryBuilder/filters/HavingFilter/HavingFilter.tsx
Labels: enhancement

#6044 chore: remove slack connect and call help
  frontend/src/pages/Support/Support.tsx
Labels: chore

#6084 fix: intermittent undefined page in trace details page
  frontend/src/container/TracesExplorer/ListView/index.tsx
  frontend/src/container/TracesExplorer/ListView/utils.tsx
Labels: bug

#5793 feat: added meta tag to prevent page indexing
  frontend/src/index.html.ejs
Labels: enhancement

#6083 feat: remove sidebar dock option
  frontend/src/constants/app.ts
  frontend/src/constants/shortcuts/globalShortcuts.ts
  frontend/src/container/AppLayout/AppLayout.styles.scss
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/SideNav/SideNav.styles.scss
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/pages/TracesExplorer/TracesExplorer.styles.scss
  frontend/src/store/actions/app/index.ts
  frontend/src/store/actions/app/sideBarCollapse.ts
  frontend/src/store/actions/index.ts
  frontend/src/store/reducers/app.ts
  frontend/src/types/actions/app.ts
  frontend/src/types/reducer/app.ts
  frontend/tests/auth.json
Labels: enhancement

#6056 fix: restricted column long value to 3 line and line clamped
  frontend/src/container/GridTableComponent/GridTableComponent.styles.scss
  frontend/src/container/GridTableComponent/index.tsx
  frontend/src/container/LogsPanelTable/LogsPanelComponent.styles.scss
  frontend/src/container/PanelWrapper/__tests__/__snapshots__/TablePanelWrapper.test.tsx.snap
  frontend/src/container/TracesTableComponent/TracesTableComponent.styles.scss
  frontend/src/periscope/components/LineClampedText/LineClampedText.tsx
Labels: bug

#6091 fix: wait for licenseData to resolve before the check to show chat support
  frontend/src/AppRoutes/index.tsx
Labels: bug, request-more-info
