Repository SigNoz/signoz, pull requests merged in 2024-07, with the labels that each got.

#5387 fix: use fill gaps only for time series panel types
  pkg/query-service/postprocess/gaps.go
  pkg/query-service/postprocess/gaps_test.go
Labels: bug

#5388 fix: use the correct formatter for the description
  pkg/query-service/model/v3/v3.go
  pkg/query-service/rules/promRule.go
  pkg/query-service/rules/thresholdRule.go
Labels: bug

#5382 chore: update posthog-js
  frontend/package.json
  frontend/yarn.lock
Labels: chore

#5396 chore: remove rules dependency in CH reader
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/rules/db.go
  pkg/query-service/rules/manager.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#5400 fix: remove pagination from members listing in org settings page
  frontend/src/components/ResizeTable/ResizeTable.tsx
  frontend/src/container/OrganizationSettings/tests/OrganizationSettings.test.tsx
  frontend/src/mocks-server/__mockdata__/members.ts
  frontend/src/mocks-server/handlers.ts
  frontend/src/tests/test-utils.tsx
Labels: bug

#5416 chore: remove dynamic config invocation
  frontend/src/container/AppLayout/index.tsx
Labels: chore

#5408 fix: typecast support added for float to int
  pkg/query-service/utils/format.go
  pkg/query-service/utils/format_test.go
Labels: bug

#5365 fix: added right margin to facing issues btn on dashboad detail page
  frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss
Labels: bug

#5436 fix: resize observer charts issue in alerts builder
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
Labels: bug

#5435 fix: clickhouse editor cursor sync issue
  frontend/src/container/ListOfDashboard/ImportJSON/index.tsx
  frontend/src/container/LogDetailedView/Overview.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/query.tsx
Labels: bug

#5410 feat: added invite team member from onboarding flow
  frontend/jest.config.ts
  frontend/public/locales/en-GB/onboarding.json
  frontend/public/locales/en/onboarding.json
  frontend/src/container/OnboardingContainer/Onboarding.styles.scss
  frontend/src/container/OnboardingContainer/OnboardingContainer.tsx
  frontend/src/container/OnboardingContainer/__test__/InviteUserFlow.test.tsx
  frontend/src/container/OnboardingContainer/common/ModuleStepsContainer/ModuleStepsContainer.styles.scss
  frontend/src/container/OnboardingContainer/common/ModuleStepsContainer/ModuleStepsContainer.tsx
  frontend/src/container/OrganizationSettings/InviteTeamMembers/index.tsx
  frontend/src/container/OrganizationSettings/InviteUserModal/InviteUserModal.tsx
  frontend/src/container/OrganizationSettings/PendingInvitesContainer/index.tsx
  frontend/src/mocks-server/__mockdata__/invite_user.ts
  frontend/src/mocks-server/handlers.ts
Labels: enhancement

#5440 chore: add react-query devtools in development env
  frontend/src/index.tsx
Labels: enhancement, chore

#5347 fix: properly render \n and \t in log details + apply Geist Mono font to the logs
  frontend/public/fonts/GeistMonoVF.woff2
  frontend/src/components/LogDetail/LogDetails.styles.scss
  frontend/src/components/Logs/RawLogView/styles.ts
  frontend/src/container/LogDetailedView/FieldRenderer.styles.scss
  frontend/src/container/LogDetailedView/JsonView.tsx
  frontend/src/container/LogDetailedView/Overview.tsx
  frontend/src/container/LogDetailedView/TableView.styles.scss
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogsExplorerChart/LogsExplorerChart.styled.ts
  frontend/src/styles.scss
Labels: bug

#5443 fix: improve the padding of toolbar buttons in explorer pages
  frontend/src/container/ExplorerOptions/ExplorerOptions.styles.scss
Labels: bug

#5460 update project maintainers
  README.md
Labels: request-more-info

#5432 fix: concurrent map writes to temporalityMap
  pkg/query-service/app/http_handler.go
Labels: bug

#5457 fix: disable removing a selected field
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#5419 fix: added null check on filters obj
  frontend/src/pages/TracesExplorer/Filter/Filter.tsx
  frontend/src/pages/TracesExplorer/__test__/TracesExplorer.test.tsx
Labels: bug

#5371 fix: added logic to keep sections uncollapsed for all filtered items
  frontend/src/pages/TracesExplorer/Filter/Section.tsx
Labels: bug

#5438 chore: use version v4 for export panel from explorer pages
  frontend/src/container/ExportPanel/ExportPanelContainer.tsx
Labels: chore

#5447 fix: retain legends while changing panel types
  frontend/src/container/NewWidget/utils.ts
Labels: bug

#5458 fix: issue with table sorting when column contains both string and numbers
  frontend/src/container/GridTableComponent/__tests__/utils.test.tsx
  frontend/src/container/GridTableComponent/utils.ts
Labels: bug

#5428 feat: show status message, status code string, span kind in trace det…
  frontend/src/container/GantChart/utils.ts
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
  frontend/src/container/TraceDetail/utils.test.ts
  frontend/src/container/TraceFlameGraph/__tests__/TraceFlameGraph.test.tsx
  frontend/src/lib/__fixtures__/getRandomColor.ts
  frontend/src/types/api/trace/getTraceItem.ts
  frontend/src/utils/__tests__/__snapshots__/spanToTree.test.ts.snap
  frontend/src/utils/fixtures/TraceData.ts
  frontend/src/utils/spanToTree.ts
Labels: enhancement

#5441 fix: block alert creation if query_range API fails
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/FormAlertRules/index.tsx
Labels: bug

#5474 chore: add activation events
  frontend/src/container/AllError/index.tsx
  frontend/src/container/EmptyLogsSearch/EmptyLogsSearch.tsx
  frontend/src/container/ErrorDetails/index.tsx
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/container/ExportPanel/ExportPanelContainer.tsx
  frontend/src/container/ExportPanel/index.tsx
  frontend/src/container/GridCardLayout/DashboardEmptyState/DashboardEmptyState.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/GridCardLayout/WidgetHeader/index.tsx
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/ListOfDashboard/ImportJSON/index.tsx
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/NewDashboard/ComponentsSlider/index.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/NoLogs/NoLogs.tsx
  frontend/src/container/PipelinePage/PipelineListsView/PipelineListsView.tsx
  frontend/src/container/ServiceApplication/ServiceTraces/index.tsx
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
  frontend/src/container/TracesExplorer/ListView/index.tsx
  frontend/src/container/TracesExplorer/TracesView/index.tsx
  frontend/src/hooks/queryBuilder/useCreateAlerts.tsx
  frontend/src/pages/SaveView/index.tsx
  frontend/src/pages/TracesExplorer/Filter/Filter.tsx
  frontend/src/pages/TracesExplorer/index.tsx
Labels: chore

#5490 fix: 404 not found when intercepting the ingestion key calls
  frontend/src/api/apiV1.ts
Labels: bug

#5496 chore: helpers required for dashboards e2e test cases
  frontend/src/container/GridCardLayout/WidgetHeader/index.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/NewWidget/utils.ts
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
  frontend/src/container/QueryBuilder/filters/ReduceToFilter/ReduceToFilter.tsx
Labels: chore

#5507 chore: update heartbeat interval logic
  pkg/query-service/constants/constants.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#5417 fix: url params should not propagate across pages
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/mocks-server/__mockdata__/dashboards.ts
  frontend/src/mocks-server/handlers.ts
  frontend/src/pages/DashboardsListPage/__tests__/DashboardListPage.test.tsx
  frontend/src/providers/Dashboard/Dashboard.tsx
  frontend/src/providers/Dashboard/types.ts
  frontend/src/store/reducers/logs.ts
Labels: bug

#5511 fix: fixed logEvent breaking page due to lack of null checks
  frontend/src/container/AllError/index.tsx
  frontend/src/container/CreateAlertChannels/index.tsx
  frontend/src/container/EditAlertChannels/index.tsx
  frontend/src/container/ErrorDetails/index.tsx
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/container/FormAlertRules/BasicInfo.tsx
  frontend/src/container/ListAlertRules/utils.ts
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/ServiceApplication/ServiceTraces/index.tsx
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/pages/SaveView/index.tsx
Labels: bug

#5516 fix: update community link
  pkg/query-service/version/version.go
Labels: bug

#5520 fix: ignore offset if timestamp is selected in order by
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
Labels: bug

#5451 chore: added trace filter test cases
  frontend/src/container/TimeSeriesView/styles.ts
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/container/TracesExplorer/QuerySection/styles.ts
  frontend/src/mocks-server/__mockdata__/explorer_views.ts
  frontend/src/mocks-server/handlers.ts
  frontend/src/pages/TracesExplorer/Filter/DurationSection.tsx
  frontend/src/pages/TracesExplorer/Filter/Filter.tsx
  frontend/src/pages/TracesExplorer/Filter/Section.tsx
  frontend/src/pages/TracesExplorer/Filter/SectionContent.tsx
  frontend/src/pages/TracesExplorer/__test__/TracesExplorer.test.tsx
  frontend/src/pages/TracesExplorer/index.tsx
Labels: test, chore

#5515 fix: do not add select columns when the datasource is logs
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/NewWidget/LeftContainer/ExplorerColumnsRenderer.tsx
  frontend/src/container/NewWidget/index.tsx
Labels: bug, DO NOT MERGE

#5526 feat: add learn more urls to ingestion settings page
  frontend/src/components/Tags/Tags.tsx
  frontend/src/container/IngestionSettings/IngestionSettings.styles.scss
  frontend/src/container/IngestionSettings/MultiIngestionSettings.tsx
  frontend/src/container/IngestionSettings/__tests__/MultiIngestionSettings.test.tsx
  frontend/src/pages/Settings/utils.ts
Labels: enhancement

#4787 fix: use proper indexes for full text search
  pkg/query-service/app/logs/v3/json_filter.go
  pkg/query-service/app/logs/v3/json_filter_test.go
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/model/v3/v3.go
Labels: bug

#5506 chore: addition of jest test cases for dashboards panels
  frontend/src/components/ValueGraph/index.tsx
  frontend/src/container/PanelWrapper/__tests__/TablePanelWrapper.test.tsx
  frontend/src/container/PanelWrapper/__tests__/ValuePanelWrapper.test.tsx
  frontend/src/container/PanelWrapper/__tests__/__snapshots__/TablePanelWrapper.test.tsx.snap
  frontend/src/container/PanelWrapper/__tests__/__snapshots__/ValuePanelWrapper.test.tsx.snap
  frontend/src/container/PanelWrapper/__tests__/tablePanelWrapperHelper.ts
  frontend/src/container/PanelWrapper/__tests__/valuePanelWrapperHelper.ts
Labels: chore

#5530 chore: move from trackEvent to logEvent
  frontend/src/AppRoutes/index.tsx
  frontend/src/container/BillingContainer/BillingContainer.tsx
  frontend/src/container/OnboardingContainer/OnboardingContainer.tsx
  frontend/src/container/OnboardingContainer/Steps/ConnectionStatus/ConnectionStatus.tsx
  frontend/src/container/OnboardingContainer/Steps/LogsConnectionStatus/LogsConnectionStatus.tsx
  frontend/src/container/OnboardingContainer/common/ModuleStepsContainer/ModuleStepsContainer.tsx
  frontend/src/container/PipelinePage/Layouts/Pipeline/CreatePipelineButton.tsx
  frontend/src/container/PipelinePage/PipelineListsView/PipelineExpandView.tsx
  frontend/src/container/PipelinePage/PipelineListsView/PipelineListsView.tsx
  frontend/src/container/PipelinePage/PipelineListsView/TableComponents/PipelineActions/components/PreviewAction.tsx
  frontend/src/container/PipelinePage/tests/CreatePipelineButton.test.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContentTabs/Configure.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailHeader.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationsUninstallBar.tsx
  frontend/src/pages/Integrations/Integrations.tsx
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/pages/Support/Support.tsx
  frontend/src/pages/WorkspaceLocked/WorkspaceLocked.tsx
Labels: chore, request-more-info

#5455 fix: retain the step interval while creating alerts from the dashboard panel
  frontend/src/hooks/queryBuilder/useCreateAlerts.tsx
  frontend/src/lib/newQueryBuilder/queryBuilderMappers/__tests__/mapQueryDataFromApi.test.tsx
  frontend/src/lib/newQueryBuilder/queryBuilderMappers/__tests__/mapQueryDataFromApiInputs.ts
  frontend/src/lib/newQueryBuilder/queryBuilderMappers/mapQueryDataFromApi.ts
  frontend/src/lib/newQueryBuilder/transformQueryBuilderDataModel.ts
Labels: bug

#5539 fix: handle the super set query reset state when changing widgets
  frontend/src/container/NewWidget/index.tsx
  frontend/src/providers/QueryBuilder.tsx
Labels: bug

#5545 fix: relative time param from the url not respected
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
Labels: bug

#5561 feat(gateway): remove feature flag
  ee/query-service/app/server.go
  ee/query-service/integrations/gateway/noop.go
  ee/query-service/model/plans.go
Labels: enhancement

#5564 fix(saml): handle invalid email domain
  ee/query-service/dao/sqlite/auth.go
Labels: bug

#5571 chore: move facing issues button in dashboards and disable intercom ping
  frontend/src/components/facingIssueBtn/FacingIssueBtn.tsx
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/index.tsx
Labels: chore

#5579 Revert "fix(saml): handle invalid email domain"
  ee/query-service/dao/sqlite/auth.go
Labels: bug

#5580 fix(saml): handle invalid email domain
  ee/query-service/dao/sqlite/auth.go
Labels: bug

#5527 feat: preference framework qs changes
  ee/query-service/app/server.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/preferences/map.go
  pkg/query-service/app/preferences/model.go
  pkg/query-service/app/server.go
  pkg/query-service/auth/auth.go
  pkg/query-service/auth/jwt.go
Labels: enhancement

#5538 feat: removed top nav from new alerts landing page
  frontend/src/container/TopNav/index.tsx
Labels: enhancement

#5445 chore: remove commented code
  frontend/src/mocks-server/handlers.ts
Labels: chore, request-more-info

#5573 fix: disable the unlock dashboard btn for integration dashboards
  ee/query-service/app/api/dashboard.go
  frontend/src/container/NewDashboard/DashboardDescription/__tests__/DashboardDescription.test.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/mocks-server/__mockdata__/dashboards.ts
  frontend/src/mocks-server/handlers.ts
  frontend/src/tests/test-utils.tsx
Labels: bug

#5404 chore: only fetch top level operation from the selected time window
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/interfaces/interface.go
Labels: chore

#5605 fix: show 0 as limit is user has set it to 0
  frontend/src/container/IngestionSettings/MultiIngestionSettings.tsx
Labels: bug

#5599 feat: update logEvent to silently handle errors
  frontend/src/api/common/logEvent.ts
  frontend/src/api/index.ts
  frontend/src/hooks/analytics/useAnalytics.tsx
Labels: enhancement, request-more-info

#5602 chore: add telemetry for channel types
  pkg/query-service/model/response.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#5607 feat: faster traceID based filtering
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/traces/v3/utils.go
  pkg/query-service/interfaces/interface.go
Labels: enhancement

#5613 fix: do not send query_range api call on every keystroke
  frontend/src/providers/QueryBuilder.tsx
Labels: bug
