Repository SigNoz/signoz, pull requests merged in 2024-06, with the labels that each got.

#5128 fix: use text/template for ClickHouse query templating
  pkg/query-service/rules/thresholdRule.go
  pkg/query-service/rules/thresholdRule_test.go
Labels: bug

#5071 chore: add AWS RDS and ElastiCache integration
  pkg/query-service/app/integrations/builtin_integrations/aws_elasticache/assets/dashboards/overview.json
  pkg/query-service/app/integrations/builtin_integrations/aws_elasticache/config/collect-logs.md
  pkg/query-service/app/integrations/builtin_integrations/aws_elasticache/config/collect-metrics.md
  pkg/query-service/app/integrations/builtin_integrations/aws_elasticache/config/prerequisites.md
  pkg/query-service/app/integrations/builtin_integrations/aws_elasticache/icon.svg
  pkg/query-service/app/integrations/builtin_integrations/aws_elasticache/integration.json
  pkg/query-service/app/integrations/builtin_integrations/aws_elasticache/overview.md
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_mysql/assets/dashboards/db_metrics.json
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_mysql/assets/dashboards/overview.json
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_mysql/config/collect-logs.md
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_mysql/config/collect-metrics.md
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_mysql/config/prerequisites.md
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_mysql/icon.svg
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_mysql/integration.json
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_mysql/overview.md
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_postgres/assets/dashboards/db_metrics_overview.json
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_postgres/assets/dashboards/overview.json
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_postgres/config/collect-logs.md
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_postgres/config/collect-metrics.md
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_postgres/config/prerequisites.md
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_postgres/icon.svg
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_postgres/integration.json
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_postgres/overview.md
Labels: chore

#5132 feat: added docs for Angular
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/Docker/QuickStart/angular-docker-quickStart-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/Docker/QuickStart/angular-docker-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/Docker/Recommended/angular-docker-recommended-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/Docker/Recommended/angular-docker-recommended-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/Docker/Recommended/angular-docker-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/Kubernetes/angular-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/Kubernetes/angular-kubernetes-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/Kubernetes/angular-kubernetes-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/LinuxAMD64/QuickStart/angular-linuxamd64-quickStart-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/LinuxAMD64/QuickStart/angular-linuxamd64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/LinuxAMD64/Recommended/angular-linuxamd64-recommended-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/LinuxAMD64/Recommended/angular-linuxamd64-recommended-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/LinuxAMD64/Recommended/angular-linuxamd64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/LinuxARM64/QuickStart/angular-linuxarm64-quickStart-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/LinuxARM64/QuickStart/angular-linuxarm64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/LinuxARM64/Recommended/angular-linuxarm64-recommended-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/LinuxARM64/Recommended/angular-linuxarm64-recommended-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/LinuxARM64/Recommended/angular-linuxarm64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/MacOsAMD64/QuickStart/angular-macosamd64-quickStart-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/MacOsAMD64/QuickStart/angular-macosamd64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/MacOsAMD64/Recommended/angular-macosamd64-recommended-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/MacOsAMD64/Recommended/angular-macosamd64-recommended-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/MacOsAMD64/Recommended/angular-macosamd64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/MacOsARM64/QuickStart/angular-macosarm64-quickStart-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/MacOsARM64/QuickStart/angular-macosarm64-quickStart-runApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/MacOsARM64/Recommended/angular-macosarm64-recommended-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/MacOsARM64/Recommended/angular-macosarm64-recommended-instrumentApplication.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/MacOsARM64/Recommended/angular-macosarm64-recommended-runApplication.md
  frontend/src/container/OnboardingContainer/constants/apmDocFilePaths.ts
  frontend/src/container/OnboardingContainer/utils/dataSourceUtils.ts
Labels: documentation, enhancement, saas-onboarding

#5139 fix: page breaking when query range response is null for table panel …
  frontend/src/container/BillingContainer/BillingUsageGraph/BillingUsageGraph.tsx
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/LogDetailedView/ContextView/useContextLogData.ts
  frontend/src/container/LogsContextList/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsPanelTable/LogsPanelComponent.tsx
  frontend/src/container/LogsTopNav/index.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/TopOperationMetrics.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphContainer.tsx
  frontend/src/container/OnboardingContainer/Steps/LogsConnectionStatus/LogsConnectionStatus.tsx
  frontend/src/container/PanelWrapper/PiePanelWrapper.tsx
  frontend/src/container/PanelWrapper/TablePanelWrapper.tsx
  frontend/src/container/ServiceApplication/utils.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/container/TracesExplorer/ListView/index.tsx
  frontend/src/container/TracesExplorer/TableView/index.tsx
  frontend/src/container/TracesTableComponent/TracesTableComponent.tsx
  frontend/src/hooks/useLogsData.ts
Labels: bug

#5134 feat: per column unit option for table type
  frontend/src/container/GridTableComponent/index.tsx
  frontend/src/container/GridTableComponent/types.ts
  frontend/src/container/NewWidget/RightContainer/ColumnUnitSelector/ColumnUnitSelector.styles.scss
  frontend/src/container/NewWidget/RightContainer/ColumnUnitSelector/ColumnUnitSelector.tsx
  frontend/src/container/NewWidget/RightContainer/YAxisUnitSelector.tsx
  frontend/src/container/NewWidget/RightContainer/constants.ts
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/PanelWrapper/TablePanelWrapper.tsx
  frontend/src/types/api/dashboard/getAll.ts
Labels: enhancement

#5123 fix: dashboard variables should properly load for imported dashboards
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
Labels: bug

#5131 feat: added facing issues btn in new dashboard revamp
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/container/NewWidget/index.tsx
Labels: enhancement

#5105 feat: support multi ingestion keys
  frontend/package.json
  frontend/public/locales/en-GB/ingestionKeys.json
  frontend/public/locales/en/ingestionKeys.json
  frontend/src/api/ErrorResponseHandler.ts
  frontend/src/api/IngestionKeys/createIngestionKey.ts
  frontend/src/api/IngestionKeys/deleteIngestionKey.ts
  frontend/src/api/IngestionKeys/getAllIngestionKeys.ts
  frontend/src/api/IngestionKeys/limits/createLimitsForKey.ts
  frontend/src/api/IngestionKeys/limits/deleteLimitsForIngestionKey.ts
  frontend/src/api/IngestionKeys/limits/updateLimitsForIngestionKey.ts
  frontend/src/api/IngestionKeys/updateIngestionKey.ts
  frontend/src/api/apiV1.ts
  frontend/src/api/index.ts
  frontend/src/components/Tags/Tags.styles.scss
  frontend/src/components/Tags/Tags.tsx
  frontend/src/constants/features.ts
  frontend/src/container/APIKeys/APIKeys.tsx
  frontend/src/container/IngestionSettings/IngestionSettings.styles.scss
  frontend/src/container/IngestionSettings/MultiIngestionSettings.tsx
  frontend/src/hooks/IngestionKeys/useGetAllIngestionKeys.ts
  frontend/src/pages/Settings/config.tsx
  frontend/src/pages/Settings/index.tsx
  frontend/src/pages/Settings/utils.ts
  frontend/src/periscope.scss
  frontend/src/periscope/components/Tabs/Tabs.tsx
  frontend/src/periscope/components/Tabs/index.tsx
  frontend/src/types/api/ingestionKeys/limits/types.ts
  frontend/src/types/api/ingestionKeys/types.ts
  frontend/yarn.lock
Labels: enhancement

#5146 fix: alerts builder light theme plot tag issue
  frontend/src/container/FormAlertRules/FormAlertRules.styles.scss
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
Labels: bug

#5149 chore: update phin version in resolutions
  frontend/package.json
  frontend/yarn.lock
Labels: chore, request-more-info

#5142 feat: trace-filter style and light mode fixes
  frontend/src/pages/TracesExplorer/Filter/DurationSection.tsx
  frontend/src/pages/TracesExplorer/Filter/Filter.styles.scss
  frontend/src/pages/TracesExplorer/Filter/SectionContent.tsx
  frontend/src/pages/TracesExplorer/TracesExplorer.styles.scss
Labels: bug, enhancement

#5148 fix: incorrect order by label in query builder
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/filters/OrderByFilter/OrderByFilter.interfaces.ts
  frontend/src/container/QueryBuilder/filters/OrderByFilter/OrderByFilter.tsx
  frontend/src/container/QueryBuilder/filters/OrderByFilter/useOrderByFilter.ts
Labels: bug

#5147 feat: added facing issues and requestIntegration section in integration pages
  frontend/src/components/facingIssueBtn/FacingIssueBtn.style.scss
  frontend/src/components/facingIssueBtn/FacingIssueBtn.tsx
  frontend/src/components/facingIssueBtn/util.ts
  frontend/src/pages/Integrations/Header.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailPage.tsx
  frontend/src/pages/Integrations/Integrations.styles.scss
  frontend/src/pages/Integrations/Integrations.tsx
  frontend/src/pages/Integrations/RequestIntegrationBtn.tsx
Labels: enhancement

#5108 fix: remove the need for unnecessary dummy time column
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v4/cumulative/table_test.go
  pkg/query-service/app/metrics/v4/cumulative/timeseries_test.go
  pkg/query-service/app/metrics/v4/delta/table_test.go
  pkg/query-service/app/metrics/v4/delta/time_series_test.go
  pkg/query-service/app/metrics/v4/helpers/clauses.go
  pkg/query-service/app/metrics/v4/query_builder_test.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/v2/querier.go
  pkg/query-service/constants/constants.go
  pkg/query-service/model/v3/v3.go
  pkg/query-service/postprocess/limit_test.go
  pkg/query-service/rules/thresholdRule.go
Labels: bug

#5130 feat: integration: added copy test tracking, facing issue btn and request more integration section
  frontend/src/components/MarkdownRenderer/CodeCopyBtn/CodeCopyBtn.tsx
  frontend/src/components/MarkdownRenderer/MarkdownRenderer.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContentTabs/Configure.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContentTabs/Overview.tsx
Labels: enhancement

#5141 fix: do not mutate the rule condition
  pkg/query-service/rules/thresholdRule.go
  pkg/query-service/rules/thresholdRule_test.go
Labels: bug

#5154 fix: fixed broken header style in dashboard detail page
  frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
Labels: bug

#5162 fix: theme analytics not getting reported as user is being fetched delayed
  frontend/src/AppRoutes/index.tsx
  frontend/src/constants/localStorage.ts
  frontend/src/hooks/useDarkMode/index.tsx
Labels: bug

#5161 fix: clone panel randomly jumping around in the middle causing layout issues
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
Labels: bug

#5168 chore: track from which page user visited to support page
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/lib/uPlotLib/getUplotHistogramChartOptions.ts
  frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
  frontend/src/pages/Support/Support.tsx
Labels: chore, request-more-info

#5177 fix: use correct column name for v4 tables
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#5164 fix: clickhouse and promQL queries table column headers not handled
  frontend/src/container/NewWidget/RightContainer/ColumnUnitSelector/ColumnUnitSelector.tsx
  frontend/src/lib/query/createTableColumnsFromQuery.ts
Labels: bug

#5138 feat: added support for bar chart stacking
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/NewWidget/RightContainer/RightContainer.styles.scss
  frontend/src/container/NewWidget/RightContainer/constants.ts
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/PanelWrapper/UplotPanelWrapper.styles.scss
  frontend/src/container/PanelWrapper/UplotPanelWrapper.tsx
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
  frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
  frontend/src/lib/uPlotLib/utils/getSeriesData.ts
  frontend/src/lib/uPlotLib/utils/getUplotChartData.ts
  frontend/src/lib/uPlotLib/utils/tests/__mocks__/seriesData.ts
  frontend/src/lib/uPlotLib/utils/tests/getSeriesData.test.ts
  frontend/src/types/api/dashboard/getAll.ts
Labels: enhancement

#5182 fix: unsaved changes popping up for newly created dashboard in settings
  frontend/src/container/NewDashboard/DashboardSettings/General/index.tsx
  frontend/src/container/NewWidget/styles.ts
Labels: bug

#5183 fix: respect the sorting params present in the URL for dashboards list page
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/providers/Dashboard/Dashboard.tsx
  frontend/src/providers/Dashboard/types.ts
Labels: bug

#5158 feat: added option to download billing usage data as csv
  frontend/src/container/BillingContainer/BillingContainer.tsx
  frontend/src/container/BillingContainer/BillingUsageGraph/generateCsvData.ts
  frontend/src/container/BillingContainer/BillingUsageGraph/utils.ts
Labels: enhancement

#5176 chore: address large number of staticcheck issues
  ee/query-service/app/api/auth.go
  ee/query-service/app/db/metrics.go
  ee/query-service/app/db/trace.go
  ee/query-service/app/server.go
  ee/query-service/integrations/signozio/response.go
  ee/query-service/license/db.go
  ee/query-service/license/sqlite/init.go
  ee/query-service/main.go
  ee/query-service/model/domain.go
  ee/query-service/usage/manager.go
  pkg/query-service/agentConf/db.go
  pkg/query-service/app/auth.go
  pkg/query-service/app/clickhouseReader/options.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/clickhouseReader/wrapper.go
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/http_handler_test.go
  pkg/query-service/app/integrations/controller.go
  pkg/query-service/app/integrations/sqlite_repo.go
  pkg/query-service/app/logparsingpipeline/db.go
  pkg/query-service/app/logparsingpipeline/postablePipeline.go
  pkg/query-service/app/logparsingpipeline/preview.go
  pkg/query-service/app/logparsingpipeline/preview_test.go
  pkg/query-service/app/opamp/model/agents.go
  pkg/query-service/app/opamp/opamp_server.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/querier/v2/helper.go
  pkg/query-service/app/querier/v2/querier.go
  pkg/query-service/app/server.go
  pkg/query-service/auth/auth.go
  pkg/query-service/auth/jwt.go
  pkg/query-service/auth/utils.go
  pkg/query-service/common/ctx.go
  pkg/query-service/dao/sqlite/connection.go
  pkg/query-service/integrations/alertManager/notifier.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/pqlEngine/engine.go
  pkg/query-service/rules/promRuleTask.go
  pkg/query-service/rules/ruleTask.go
  pkg/query-service/rules/templates.go
  pkg/query-service/rules/thresholdRule.go
  pkg/query-service/rules/thresholdRule_test.go
  pkg/query-service/telemetry/telemetry.go
  pkg/query-service/tests/auth_test.go
  pkg/query-service/tests/integration/logparsingpipeline_test.go
  pkg/query-service/tests/integration/test_utils.go
Labels: chore

#5186 chore: support custom step interval
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v4/query_builder.go
  pkg/query-service/app/metrics/v4/query_builder_test.go
  pkg/query-service/app/querier/helper.go
  pkg/query-service/app/querier/v2/helper.go
  pkg/query-service/common/query_range.go
  pkg/query-service/postprocess/gaps.go
  pkg/query-service/rules/thresholdRule.go
Labels: chore

#5199 fix: default alerts yaxis unit doesn't reset on page change
  frontend/src/container/FormAlertRules/index.tsx
Labels: bug

#5192 fix: fix colors of graphs for lightMode and darkMode
  frontend/src/constants/theme.ts
  frontend/src/container/BillingContainer/BillingUsageGraph/BillingUsageGraph.tsx
  frontend/src/container/PanelWrapper/PiePanelWrapper.tsx
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
  frontend/src/lib/uPlotLib/getUplotHistogramChartOptions.ts
  frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
  frontend/src/lib/uPlotLib/utils/getSeriesData.ts
  frontend/src/lib/uPlotLib/utils/tests/__mocks__/seriesData.ts
Labels: bug

#5189 fix: fixed flaky pipelineSearchSection test case
  frontend/src/container/PipelinePage/tests/PipelinesSearchSection.test.tsx
Labels: bug

#5214 chore: open clickhouse builder by default on creating new exception alert
  frontend/src/container/CreateAlertRule/defaults.ts
Labels: chore

#5216 feat: added link for example alerts
  frontend/public/locales/en-GB/alerts.json
  frontend/public/locales/en/alerts.json
  frontend/src/components/facingIssueBtn/FacingIssueBtn.style.scss
  frontend/src/container/CreateAlertRule/SelectAlertType/index.tsx
  frontend/src/container/FormAlertRules/FormAlertRules.styles.scss
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/pages/TracesExplorer/Filter/filterUtils.ts
Labels: enhancement

#5200 fix: dashboard listing default sorting by updatedAt
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
  frontend/src/providers/Dashboard/Dashboard.tsx
  frontend/src/providers/Dashboard/types.ts
Labels: bug

#5195 feat: added an option to create channel when no Channels are available in alert config
  frontend/src/container/AllAlertChannels/index.tsx
  frontend/src/container/FormAlertRules/BasicInfo.tsx
  frontend/src/container/FormAlertRules/ChannelSelect/index.tsx
  frontend/src/container/FormAlertRules/FormAlertRules.styles.scss
Labels: enhancement

#5217 fix: do not return zero value for non-aggregated table result
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#5224 chore: add common resource attributes for span metrics
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
Labels: chore

#5185 feat: added alert rule empty state and product edu
  frontend/public/Icons/alert_emoji.svg
  frontend/src/container/CreateAlertRule/SelectAlertType/index.tsx
  frontend/src/container/ListAlertRules/AlertsEmptyState/AlertInfoCard.tsx
  frontend/src/container/ListAlertRules/AlertsEmptyState/AlertsEmptyState.styles.scss
  frontend/src/container/ListAlertRules/AlertsEmptyState/AlertsEmptyState.tsx
  frontend/src/container/ListAlertRules/AlertsEmptyState/InfoLinkText.tsx
  frontend/src/container/ListAlertRules/AlertsEmptyState/alertLinks.ts
  frontend/src/container/ListAlertRules/index.tsx
Labels: enhancement

#5231 fix: text wrap in log details view, remove json/raw tag
  frontend/src/container/LogDetailedView/JsonView.tsx
  frontend/src/container/LogDetailedView/Overview.tsx
Labels: bug

#5225 feat: added APM to new trace filter redirection
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/LiveLogs/constants.ts
  frontend/src/container/LiveLogs/utils.ts
  frontend/src/container/LogsContextList/utils.ts
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ServiceOverview.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/TableRenderer/ColumnWithLink.tsx
  frontend/src/container/MetricsApplication/Tabs/util.ts
  frontend/src/container/MetricsApplication/TopOperationsTable.tsx
  frontend/src/container/MetricsApplication/types.ts
  frontend/src/container/MetricsApplication/utils.ts
  frontend/src/pages/LogsExplorer/utils.ts
  frontend/src/providers/QueryBuilder.tsx
Labels: enhancement

#5232 fix: update view options not visible
  frontend/src/container/ExplorerOptions/ExplorerOptions.styles.scss
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
Labels: bug

#5238 chore: fix elapsed time formatting
  ee/query-service/app/db/metrics.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/utils/time.go
Labels: bug, chore

#5249 fix: table sorting when units are present
  frontend/src/container/GridTableComponent/index.tsx
  frontend/src/lib/query/createTableColumnsFromQuery.ts
Labels: bug

#5263 fix: trace explorer not highlighting in sidenav
  frontend/src/container/SideNav/menuItems.tsx
Labels: bug

#5248 fix: table row data doesn't align with the response
  frontend/src/lib/query/createTableColumnsFromQuery.ts
Labels: bug

#5191 feat: added checkbox selection in dashboard variables
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.styles.scss
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.test.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/styles.ts
Labels: enhancement

#5235 fix: convert timestamp in new trace explorer to user browser timezone and readable format
  frontend/src/container/TracesExplorer/ListView/utils.tsx
Labels: bug

#5236 fix: fixed lightMode style for histogram panel
  frontend/src/container/NewWidget/RightContainer/RightContainer.styles.scss
Labels: bug

#5251 fix: fixed panelType when creating alerts from histogram dashboard
  frontend/src/container/FormAlertRules/index.tsx
Labels: bug

#5271 fix: update the error boundary components with sentry error boundary components
  frontend/src/components/Uplot/Uplot.tsx
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/ServiceApplication/index.tsx
  frontend/src/index.tsx
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/pages/Pipelines/index.tsx
  frontend/src/pages/Trace/index.tsx
  frontend/src/pages/TracesExplorer/index.tsx
Labels: bug

#5275 fix: update companyDomain in before firing every event
  pkg/query-service/telemetry/telemetry.go
Labels: bug

#5282 fix: added null checks for stacked bar chart with fallbacks
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
Labels: bug

#5237 fix: fixed flakiness in alert list actions - delete, edit, clone & toggle
  frontend/src/components/DropDown/DropDown.tsx
  frontend/src/container/ListAlertRules/ListAlert.tsx
  frontend/src/container/ListAlertRules/styles.ts
Labels: bug

#5284 chore: threshold rule panel type to graph
  pkg/query-service/rules/thresholdRule.go
Labels: chore

#5285 feat: sanitize query to remove groupBy for list panel query
  pkg/query-service/app/parser.go
  pkg/query-service/model/v3/v3.go
Labels: enhancement

#5287 fix: dashboard empty state learn more link not working
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
Labels: bug

#5279 fix: update from typography link to react router dom link component t…
  frontend/src/container/TraceDetail/TraceDetails.styles.scss
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/container/TracesExplorer/TracesView/configs.tsx
Labels: bug

#5268 feat: [5038] enable list view - add to dashboard
  frontend/src/constants/panelTypes.ts
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsPanelTable/LogsPanelComponent.styles.scss
  frontend/src/container/NewWidget/utils.ts
  frontend/src/container/TracesTableComponent/TracesTableComponent.styles.scss
  frontend/src/hooks/dashboard/utils.ts
  frontend/src/pages/TracesExplorer/index.tsx
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
Labels: enhancement

#5283 fix: dependent variable panel not updating
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.test.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
Labels: bug

#5294 chore: bump SigNoz/signoz-otel-collector and SigNoz/prometheus
  go.mod
  go.sum
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/integrations/builtin.go
  pkg/query-service/app/logparsingpipeline/preview.go
  pkg/query-service/collectorsimulator/collectorsimulator.go
  pkg/query-service/collectorsimulator/inmemoryexporter/factory.go
  pkg/query-service/collectorsimulator/inmemoryreceiver/factory.go
  pkg/query-service/collectorsimulator/logs.go
Labels: chore

#5276 feat: pass fill gaps to query range api
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/NewWidget/LeftContainer/index.tsx
  frontend/src/lib/dashboard/getQueryResults.ts
  frontend/src/lib/dashboard/prepareQueryRangePayload.ts
  frontend/src/lib/uPlotLib/utils/getUplotChartData.ts
  frontend/src/types/api/metrics/getQueryRange.ts
Labels: enhancement

#5296 fix: move date time picker to click an option or `ok` for custom time picker rather than hover
  frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
Labels: bug

#5274 fix: handled value as string from queryParams for trace filters
  frontend/src/pages/TracesExplorer/Filter/SectionContent.tsx
  frontend/src/pages/TracesExplorer/Filter/filterUtils.ts
Labels: bug

#5159 feat: azure monitoring docs
  frontend/public/Logos/azure-aks.svg
  frontend/public/Logos/azure-app-service.svg
  frontend/public/Logos/azure-blob-storage.svg
  frontend/public/Logos/azure-container-apps.svg
  frontend/public/Logos/azure-functions.svg
  frontend/public/Logos/azure-sql-database-metrics.svg
  frontend/public/Logos/azure-vm.svg
  frontend/public/locales/en/titles.json
  frontend/src/constants/routes.ts
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/AKS/aks-installCentralCollector.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/AKS/aks-logs.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/AKS/aks-metrics.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/AKS/aks-setupEventsHub.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/AKS/aks-tracing.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/AppService/appService-installCentralCollector.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/AppService/appService-logs.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/AppService/appService-metrics.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/AppService/appService-setupEventsHub.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/AppService/appService-tracing.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/BlobStorage/blobStorage-installCentralCollector.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/BlobStorage/blobStorage-logs.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/BlobStorage/blobStorage-metrics.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/BlobStorage/blobStorage-setupEventsHub.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/ContainerApps/containerApps-installCentralCollector.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/ContainerApps/containerApps-logs.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/ContainerApps/containerApps-metrics.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/ContainerApps/containerApps-setupEventsHub.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/ContainerApps/containerApps-tracing.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/Functions/functions-installCentralCollector.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/Functions/functions-logs.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/Functions/functions-metrics.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/Functions/functions-setupEventsHub.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/Functions/functions-tracing.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/SqlDatabaseMetrics/sqlDatabaseMetrics-installCentralCollector.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/SqlDatabaseMetrics/sqlDatabaseMetrics-metrics.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/SqlDatabaseMetrics/sqlDatabaseMetrics-setupEventsHub.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/Vm/vm-hostmetrics-and-logs.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/Vm/vm-installCentralCollector.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/Vm/vm-setupEventsHub.md
  frontend/src/container/OnboardingContainer/Onboarding.styles.scss
  frontend/src/container/OnboardingContainer/OnboardingContainer.tsx
  frontend/src/container/OnboardingContainer/Steps/MarkdownStep/MarkdownStep.tsx
  frontend/src/container/OnboardingContainer/constants/azureMonitoringDocFilePaths.ts
  frontend/src/container/OnboardingContainer/constants/stepsConfig.tsx
  frontend/src/container/OnboardingContainer/utils/dataSourceUtils.ts
  frontend/src/container/OnboardingContainer/utils/getSteps.ts
  frontend/src/container/TopNav/DateTimeSelection/config.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/utils/permission/index.ts
Labels: enhancement, saas-onboarding

#5313 fix: handle overflow for attribute tooltips in trace details page
  frontend/src/container/TraceDetail/SelectedSpanDetails/Tags/Tag.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/Tags/Tags.styles.scss
Labels: bug

#5314 fix: incorrect telemetry query for samples
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#5321 chore: add start/end millis for trace details response
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/model/response.go
Labels: chore

#5325 fix: trace detail api start and end time
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#5324 chore: posthog js init
  frontend/package.json
  frontend/src/AppRoutes/index.tsx
  frontend/src/index.tsx
  frontend/webpack.config.js
  frontend/webpack.config.prod.js
  frontend/yarn.lock
Labels: chore

#5328 fix: stacked series no data case
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
Labels: bug

#5239 chore: remove deprecated option
  ee/query-service/app/api/api.go
  ee/query-service/app/server.go
  ee/query-service/main.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/main.go
Labels: chore

#5300 chore: read double pointer numbers from result
  pkg/query-service/app/clickhouseReader/reader.go
Labels: chore

#5331 fix: make the license key check case insensitive
  frontend/src/container/Header/index.tsx
  frontend/src/container/SideNav/SideNav.tsx
Labels: bug

#5308 fix: table order by with builder queries
  pkg/query-service/app/http_handler.go
  pkg/query-service/model/v3/v3.go
  pkg/query-service/postprocess/process.go
  pkg/query-service/postprocess/table.go
  pkg/query-service/postprocess/table_test.go
Labels: bug

#5346 fix: apdex tooltip not visible in service details page
  frontend/src/components/TextToolTip/TextToolTip.tsx
Labels: bug

#5330 chore: move posthog to segment
  deploy/install.sh
  go.mod
  go.sum
  pkg/query-service/telemetry/ignored.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#5318 fix: added correct query for external metric service graph
  frontend/src/container/MetricsApplication/Tabs/External.tsx
Labels: bug

#5350 fix: aks collector instruction fix
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/AKS/aks-installCentralCollector.md
Labels: bug

#5349 chore: update table response format
  Makefile
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/model/v3/v3.go
  pkg/query-service/postprocess/table.go
  pkg/query-service/postprocess/table_test.go
Labels: chore

#5355 chore: flaky TestTransformToTableForClickHouseQueries
  pkg/query-service/postprocess/table_test.go
Labels: chore

#5353 fix: search not working in services table
  frontend/src/container/ServiceApplication/Columns/GetColumnSearchProps.tsx
Labels: bug

#5316 feat: remove pagination for single-page lists
  frontend/src/components/ResizeTable/ResizeTable.tsx
  frontend/src/container/ListAlertRules/ListAlert.tsx
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/PipelinePage/Layouts/config.ts
  frontend/src/container/PlannedDowntime/PlannedDowntimeList.tsx
  frontend/src/container/ServiceApplication/ServiceMetrics/ServiceMetricTable.tsx
  frontend/src/container/ServiceApplication/ServiceTraces/ServiceTracesTable.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailContentTabs/DataCollected.tsx
  frontend/src/pages/SaveView/index.tsx
Labels: enhancement

#5357 fix: labelsArray being returned null despite of labels being present
  frontend/src/lib/query/createTableColumnsFromQuery.ts
Labels: bug

#5362 fix: remove duplicate severityText in raw logs
  frontend/src/components/Logs/RawLogView/index.tsx
Labels: bug

#5120 feat: add spanKind and status in span response
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/model/response.go
  pkg/query-service/model/response_easyjson.go
Labels: enhancement

#5354 feat: added track event in Alerts - (multiple places)
  frontend/src/components/DropDown/DropDown.tsx
  frontend/src/components/ResizeTable/DynamicColumnTable.tsx
  frontend/src/components/ResizeTable/types.ts
  frontend/src/container/AllAlertChannels/index.tsx
  frontend/src/container/CreateAlertChannels/index.tsx
  frontend/src/container/CreateAlertRule/SelectAlertType/index.tsx
  frontend/src/container/CreateAlertRule/index.tsx
  frontend/src/container/EditAlertChannels/index.tsx
  frontend/src/container/FormAlertRules/BasicInfo.tsx
  frontend/src/container/FormAlertRules/QuerySection.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/ListAlertRules/AlertsEmptyState/AlertInfoCard.tsx
  frontend/src/container/ListAlertRules/AlertsEmptyState/AlertsEmptyState.tsx
  frontend/src/container/ListAlertRules/AlertsEmptyState/InfoLinkText.tsx
  frontend/src/container/ListAlertRules/AlertsEmptyState/alertLinks.ts
  frontend/src/container/ListAlertRules/ListAlert.tsx
  frontend/src/container/ListAlertRules/index.tsx
  frontend/src/container/ListAlertRules/utils.ts
  frontend/src/container/TriggeredAlerts/index.tsx
Labels: enhancement

#5351 chore: move the table calculation to backend
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridTableComponent/__tests__/response.ts
  frontend/src/container/GridTableComponent/__tests__/utils.test.tsx
  frontend/src/container/GridTableComponent/index.tsx
  frontend/src/container/GridTableComponent/utils.ts
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphContainer.tsx
  frontend/src/container/NewWidget/LeftContainer/index.tsx
  frontend/src/container/PanelWrapper/TablePanelWrapper.tsx
  frontend/src/lib/dashboard/getQueryResults.ts
  frontend/src/lib/dashboard/prepareQueryRangePayload.ts
  frontend/src/types/api/metrics/getQueryRange.ts
Labels: enhancement, chore

#5376 fix: pie chart panels not rendering
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/NewWidget/LeftContainer/index.tsx
  frontend/src/utils/getGraphType.ts
Labels: bug

#5378 fix: restructure code to handle loading state for panel type change
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphContainer.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/index.tsx
  frontend/src/container/NewWidget/LeftContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/NewWidget/types.ts
Labels: bug
