Repository SigNoz/signoz, pull requests merged in 2024-08, with the labels that each got.

#5595 fix: logs context not working because of incorrect request data
  frontend/src/container/LogDetailedView/ContextView/useContextLogData.ts
Labels: bug

#4971 feat: show log severity indicator based on severity number if it's available when severity text is unknown
  frontend/src/components/Logs/LogStateIndicator/LogStateIndicator.tsx
  frontend/src/components/Logs/LogStateIndicator/utils.test.ts
  frontend/src/components/Logs/LogStateIndicator/utils.ts
  frontend/src/container/LogDetailedView/utils.tsx
  frontend/src/types/api/logs/log.ts
Labels: enhancement

#5552 chore: added service name and time params for top level operations
  frontend/src/api/metrics/getTopLevelOperations.ts
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/ServiceApplication/ServiceMetrics/index.tsx
  frontend/src/hooks/useGetTopLevelOperations.ts
Labels: chore

#5534 fix: mount root path in /hostfs for hostmetrics
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/docker-compose-core.yaml
  deploy/docker/clickhouse-setup/docker-compose.testing.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
  pkg/query-service/tests/test-deploy/docker-compose.yaml
  pkg/query-service/tests/test-deploy/otel-collector-config.yaml
Labels: bug

#5627 chore(telemetry): add telemetry for metrics query type and count prom…
  pkg/query-service/model/response.go
  pkg/query-service/rules/db.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#5625 feat: enable pagination for service listing, key operations, explorer t…
  frontend/src/container/MetricsApplication/TopOperationsTable.tsx
  frontend/src/container/QueryTable/QueryTable.tsx
Labels: enhancement

#5639 feat: add 1 month option in time range
  frontend/src/container/NewWidget/RightContainer/timeItems.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/lib/getMinMax.ts
  frontend/src/lib/getStartAndEndTime/index.ts
Labels: enhancement

#5629 chore: add Reduce To for pie chart
  frontend/src/container/NewWidget/utils.ts
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
Labels: chore

#5544 feat: added link for dashboard name
  frontend/src/container/ListOfDashboard/DashboardList.styles.scss
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
Labels: enhancement

#5606 feat: added links to integrations page in onboarding section
  frontend/src/container/OnboardingContainer/Steps/DataSource/DataSource.styles.scss
  frontend/src/container/OnboardingContainer/Steps/DataSource/DataSource.tsx
Labels: enhancement

#5646 fix: make timeshift work with cache
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/querier/v2/helper.go
  pkg/query-service/app/querier/v2/querier_test.go
  pkg/query-service/app/queryBuilder/query_builder.go
Labels: bug

#5654 chore: handle traceID search 404 performance issue
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/traces/v3/utils.go
Labels: chore

#5563 feat: tests for alert channels settings
  frontend/src/container/AllAlertChannels/__tests__/AlertChannels.test.tsx
  frontend/src/container/AllAlertChannels/__tests__/AlertChannelsNormalUser.test.tsx
  frontend/src/container/AllAlertChannels/__tests__/CreateAlertChannel.test.tsx
  frontend/src/container/AllAlertChannels/__tests__/CreateAlertChannelNormalUser.test.tsx
  frontend/src/container/AllAlertChannels/__tests__/EditAlertChannel.test.tsx
  frontend/src/container/AllAlertChannels/__tests__/testUtils.ts
  frontend/src/container/FormAlertChannels/Settings/Email.tsx
  frontend/src/container/FormAlertChannels/Settings/MsTeams.tsx
  frontend/src/container/FormAlertChannels/Settings/Opsgenie.tsx
  frontend/src/container/FormAlertChannels/Settings/Pager.tsx
  frontend/src/container/FormAlertChannels/Settings/Slack.tsx
  frontend/src/container/FormAlertChannels/Settings/Webhook.tsx
  frontend/src/container/FormAlertChannels/index.tsx
  frontend/src/mocks-server/__mockdata__/alerts.ts
  frontend/src/mocks-server/handlers.ts
  frontend/src/pages/GettingStarted/renderConfig.tsx
Labels: enhancement

#5499 feat: my settings page tests
  frontend/src/container/MySettings/Password/index.tsx
  frontend/src/container/MySettings/UserInfo/index.tsx
  frontend/src/container/MySettings/__tests__/MySettings.test.tsx
  frontend/src/container/MySettings/index.tsx
  frontend/src/mocks-server/handlers.ts
Labels: enhancement

#5540 feat: login flow tests
  frontend/src/container/Login/__tests__/Login.test.tsx
  frontend/src/container/Login/index.tsx
  frontend/src/mocks-server/handlers.ts
Labels: enhancement

#5649 chore: make eval delay configurable
  ee/query-service/app/server.go
  pkg/query-service/app/server.go
  pkg/query-service/constants/constants.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/thresholdRule.go
  pkg/query-service/rules/thresholdRule_test.go
Labels: chore

#5255 chore: add alerts state history query service impl
  ee/query-service/app/server.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/migrate/migate.go
  pkg/query-service/model/v3/v3.go
  pkg/query-service/rules/alerting.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/promRule.go
  pkg/query-service/rules/promrule_test.go
  pkg/query-service/rules/thresholdRule.go
Labels: chore

#5651 chore: enable caching for all panel types in metrics v4
  pkg/query-service/app/querier/v2/querier.go
  pkg/query-service/app/querier/v2/querier_test.go
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
Labels: chore

#5398 chore: add eval tests for threshold rule
  go.sum
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/v2/querier.go
  pkg/query-service/rules/thresholdRule.go
  pkg/query-service/rules/thresholdRule_test.go
Labels: chore

#5667 feat: add runningDiff function
  frontend/src/constants/queryFunctionOptions.ts
  frontend/src/types/common/queryBuilder.ts
  pkg/query-service/app/queryBuilder/functions.go
  pkg/query-service/app/queryBuilder/functions_test.go
  pkg/query-service/common/query_range.go
  pkg/query-service/model/v3/v3.go
Labels: enhancement

#5665 chore: updated k8s instructions
  frontend/src/container/OnboardingContainer/Modules/APM/Dotnet/md-docs/Kubernetes/dotnet-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Elixir/md-docs/Kubernetes/elixir-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/GoLang/md-docs/Kubernetes/golang-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Jboss/Kubernetes/jboss-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Others/Kubernetes/others-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/Kubernetes/springBoot-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/Tomcat/Kubernetes/tomcat-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Angular/Kubernetes/angular-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Express/Kubernetes/express-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/NestJS/Kubernetes/nestjs-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/NodeJS/Kubernetes/nodejs-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/Others/Kubernetes/others-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Javascript/md-docs/ReactJS/Kubernetes/reactjs-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Php/md-docs/Kubernetes/php-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Python/md-docs/Django/Kubernetes/django-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Python/md-docs/Falcon/Kubernetes/falcon-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Python/md-docs/FastAPI/Kubernetes/fastapi-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Python/md-docs/Flask/Kubernetes/flask-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Python/md-docs/Others/Kubernetes/others-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/RubyOnRails/md-docs/Kubernetes/ror-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Rust/md-docs/Kubernetes/rust-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/APM/Swift/md-docs/Kubernetes/swift-kubernetes-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/AwsMonitoring/EKS/eks-installOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/InfrastructureMonitoring/KubernetesInfraMetrics/md-docs/kubernetes-setupOtelCollector.md
  frontend/src/container/OnboardingContainer/Modules/LogsManagement/Kubernetes/md-docs/kubernetes-installOtelCollector.md
Labels: chore

#5315 fix: send alert default annotations for missing data alert
  pkg/query-service/rules/api_params.go
  pkg/query-service/rules/prom_rule.go
  pkg/query-service/rules/prom_rule_task.go
  pkg/query-service/rules/result_types.go
  pkg/query-service/rules/rule_task.go
  pkg/query-service/rules/threshold_rule.go
  pkg/query-service/rules/threshold_rule_test.go
  pkg/query-service/utils/labels/labels.go
Labels: bug

#5648 fix: clean out the panel type change attribute dependency
  frontend/src/container/NewWidget/utils.ts
Labels: bug

#5601 feat: use selected columns as pinned attributes
  frontend/src/components/LogDetail/LogDetail.interfaces.ts
  frontend/src/components/LogDetail/index.tsx
  frontend/src/container/LogDetailedView/Overview.tsx
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogDetailedView/utils.tsx
  frontend/src/container/LogsPanelTable/LogsPanelComponent.tsx
Labels: enhancement

#5674 feat: add beta tag for service map and light mode
  frontend/src/container/MySettings/__tests__/MySettings.test.tsx
  frontend/src/container/MySettings/index.tsx
  frontend/src/container/SideNav/NavItem/NavItem.tsx
  frontend/src/container/SideNav/menuItems.tsx
  frontend/src/container/SideNav/sideNav.types.ts
Labels: enhancement

#5686 chore: zeus features
  ee/query-service/app/api/featureFlags.go
  ee/query-service/app/api/featureFlags_test.go
  ee/query-service/constants/constants.go
  ee/query-service/license/manager.go
Labels: enhancement, chore

#5672 fix: dashboards listing and details page css fixes
  frontend/src/container/ListOfDashboard/DashboardList.styles.scss
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
Labels: bug

#5693 fix: hide beta icon in sidebar collapsed view
  frontend/src/container/SideNav/SideNav.styles.scss
Labels: bug

#5673 feat: move chat support behind paywall
  frontend/src/AppRoutes/index.tsx
  frontend/src/components/ChatSupportGateway/ChatSupportGateway.tsx
  frontend/src/components/LaunchChatSupport/LaunchChatSupport.styles.scss
  frontend/src/components/LaunchChatSupport/LaunchChatSupport.tsx
  frontend/src/components/LaunchChatSupport/util.ts
  frontend/src/components/ResizeTable/DynamicColumnTable.tsx
  frontend/src/components/ResizeTable/types.ts
  frontend/src/components/facingIssueBtn/FacingIssueBtn.tsx
  frontend/src/constants/features.ts
  frontend/src/container/AppLayout/AppLayout.styles.scss
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/ListAlertRules/ListAlert.tsx
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/pages/Integrations/Header.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailPage.tsx
  frontend/src/pages/Support/Support.tsx
Labels: enhancement

#5608 feat: support for attribute key suggestions and example queries in logs explorer query builder
  frontend/src/api/queryBuilder/getAttributeSuggestions.ts
  frontend/src/constants/queryBuilder.ts
  frontend/src/constants/shortcuts/logsExplorerShortcuts.ts
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsExplorerViews/tests/LogsExplorerViews.test.tsx
  frontend/src/container/OptionsMenu/constants.ts
  frontend/src/container/QueryBuilder/components/ToolbarActions/RightToolbarActions.tsx
  frontend/src/container/QueryBuilder/components/ToolbarActions/ToolbarActions.styles.scss
  frontend/src/container/QueryBuilder/components/ToolbarActions/tests/ToolbarActions.test.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/ExampleQueriesRendererForLogs.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/OptionRendererForLogs.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/QueryBuilderSearch.styles.scss
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/utils.ts
  frontend/src/container/QueryBuilder/type.ts
  frontend/src/hooks/queryBuilder/useAutoComplete.ts
  frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
  frontend/src/hooks/queryBuilder/useGetAttributeSuggestions.ts
  frontend/src/hooks/queryBuilder/useGetExplorerQueryRange.ts
  frontend/src/hooks/queryBuilder/useOptions.ts
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/types/api/queryBuilder/getAttributeSuggestions.ts
  frontend/src/types/api/queryBuilder/queryAutocompleteResponse.ts
Labels: enhancement

#5706 feat: client changes for query stats
  frontend/public/Icons/solid-x-circle.svg
  frontend/src/api/common/getQueryStats.ts
  frontend/src/api/metrics/getQueryRange.ts
  frontend/src/constants/env.ts
  frontend/src/container/LogsExplorerViews/LogsExplorerViews.styles.scss
  frontend/src/container/LogsExplorerViews/QueryStatus.styles.scss
  frontend/src/container/LogsExplorerViews/QueryStatus.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsExplorerViews/tests/LogsExplorerViews.test.tsx
  frontend/src/hooks/queryBuilder/useGetExplorerQueryRange.ts
  frontend/src/hooks/queryBuilder/useGetQueryRange.ts
  frontend/src/lib/dashboard/getQueryResults.ts
  frontend/src/typings/environment.ts
  frontend/webpack.config.js
  frontend/webpack.config.prod.js
Labels: enhancement

#5677 chore: add telemetry for dashboards/alerts with tsv2 table
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/model/response.go
  pkg/query-service/rules/db.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#5707 feat(premium-support): add premium-support feature
  ee/query-service/model/plans.go
Labels: enhancement, request-more-info

#5708 chore: remove the base URL from the ws config
  frontend/src/constants/env.ts
Labels: chore

#5709 chore: added leading slash for for ws URL
  frontend/src/api/common/getQueryStats.ts
Labels: chore

#5712 feat: client changes for consumption and design changes for where clause in logs explorer
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/CustomDropdown.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.styles.scss
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/Suggestions.styles.scss
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/Suggestions.tsx
Labels: enhancement

#5715 fix: do not use relative URLs for ws connections
  frontend/src/api/common/getQueryStats.ts
  frontend/src/container/LogsExplorerViews/tests/LogsExplorerViews.test.tsx
Labels: bug, DO NOT MERGE

#5719 chore: use base prefix of /ws for websocket paths
  ee/query-service/app/server.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
Labels: bug, chore

#5714 fix: add missing selected time range variables
  frontend/src/api/dashboard/variables/dashboardVariablesQuery.ts
Labels: bug

#5659 feat: rewrite the query builder search component
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchDropdown.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.styles.scss
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/Suggestions.styles.scss
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/Suggestions.tsx
  frontend/src/hooks/queryBuilder/useGetAggregateValues.ts
  frontend/src/hooks/queryBuilder/useIsValidTag.ts
  frontend/src/hooks/queryBuilder/useOperatorType.ts
Labels: enhancement

#5694 fix: added onDragSelect to DBCall and External metric app
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
Labels: bug

#5726 chore(codeowners): update codeowners to team
  .github/CODEOWNERS
Labels: chore

#5725 chore: chat block events
  frontend/src/components/ChatSupportGateway/ChatSupportGateway.tsx
  frontend/src/components/LaunchChatSupport/LaunchChatSupport.tsx
  frontend/src/components/LaunchChatSupport/util.ts
  frontend/src/container/OnboardingContainer/Steps/DataSource/DataSource.tsx
  frontend/src/container/OnboardingContainer/common/ModuleStepsContainer/ModuleStepsContainer.tsx
  frontend/src/pages/Support/Support.tsx
Labels: chore

#5727 feat(packages): add first dedicated confmap, config, version and instrumentation packages
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/doc.go
  pkg/config/provider.go
  pkg/config/unmarshaler.go
  pkg/config/unmarshaler_test.go
  pkg/confmap/config.go
  pkg/confmap/doc.go
  pkg/confmap/provider/signozenvprovider/provider.go
  pkg/confmap/provider/signozenvprovider/provider_test.go
  pkg/instrumentation/config.go
  pkg/instrumentation/doc.go
  pkg/instrumentation/instrumentation.go
  pkg/instrumentation/logger.go
  pkg/instrumentation/meter.go
  pkg/instrumentation/tracer.go
  pkg/query-service/collectorsimulator/inmemoryexporter/config_test.go
  pkg/query-service/collectorsimulator/inmemoryexporter/exporter_test.go
  pkg/query-service/collectorsimulator/inmemoryreceiver/config_test.go
  pkg/query-service/collectorsimulator/inmemoryreceiver/receiver_test.go
  pkg/version/doc.go
  pkg/version/version.go
Labels: enhancement

#5531 chore: added trace explorer test
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/container/ExplorerOptions/ExplorerOptionsHideArea.tsx
  frontend/src/mocks-server/__mockdata__/explorer_views.ts
  frontend/src/mocks-server/__mockdata__/query_range.ts
  frontend/src/mocks-server/handlers.ts
  frontend/src/pages/TracesExplorer/__test__/TracesExplorer.test.tsx
  frontend/src/pages/TracesExplorer/__test__/testUtils.ts
Labels: chore

#5733 fix: nan and inf values in formula result
  pkg/query-service/postprocess/formula.go
  pkg/query-service/postprocess/formula_test.go
Labels: bug

#5740 feat(packages): add registry and http packages
  .gitignore
  ee/query-service/app/server.go
  pkg/http/doc.go
  pkg/http/middleware/doc.go
  pkg/http/middleware/logging.go
  pkg/http/middleware/middleware.go
  pkg/http/middleware/response.go
  pkg/http/middleware/timeout.go
  pkg/http/middleware/timeout_test.go
  pkg/http/server/config.go
  pkg/http/server/doc.go
  pkg/http/server/server.go
  pkg/query-service/app/server.go
  pkg/query-service/app/server_test.go
  pkg/registry/doc.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  pkg/registry/service.go
  pkg/registry/service_test.go
Labels: enhancement

#5741 feat(errors): add errors package
  pkg/errors/doc.go
  pkg/errors/errors.go
  pkg/errors/errors_test.go
  pkg/errors/type.go
  pkg/errors/type_test.go
Labels: enhancement

#5743 feat(web): add web package
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/http/middleware/cache.go
  pkg/http/middleware/cache_test.go
  pkg/web/config.go
  pkg/web/testdata/index.html
  pkg/web/web.go
  pkg/web/web_test.go
Labels: enhancement

#5739 feat: add support for changing the font size in logs
  frontend/src/components/Logs/AddToQueryHOC.styles.scss
  frontend/src/components/Logs/AddToQueryHOC.tsx
  frontend/src/components/Logs/ListLogView/ListLogView.styles.scss
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/ListLogView/styles.ts
  frontend/src/components/Logs/LogStateIndicator/LogStateIndicator.styles.scss
  frontend/src/components/Logs/LogStateIndicator/LogStateIndicator.test.tsx
  frontend/src/components/Logs/LogStateIndicator/LogStateIndicator.tsx
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/RawLogView/styles.ts
  frontend/src/components/Logs/RawLogView/types.ts
  frontend/src/components/Logs/TableView/styles.ts
  frontend/src/components/Logs/TableView/types.ts
  frontend/src/components/Logs/TableView/useTableView.styles.scss
  frontend/src/components/Logs/TableView/useTableView.tsx
  frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.styles.scss
  frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.tsx
  frontend/src/container/LiveLogs/LiveLogsList/index.tsx
  frontend/src/container/LogDetailedView/ContextView/ContextLogRenderer.tsx
  frontend/src/container/LogDetailedView/ContextView/useContextLogData.ts
  frontend/src/container/LogDetailedView/LogContext.tsx
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogsContextList/configs.ts
  frontend/src/container/LogsContextList/index.tsx
  frontend/src/container/LogsExplorerContext/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/TableRow.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/config.ts
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/styles.ts
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsTable/index.tsx
  frontend/src/container/OptionsMenu/constants.ts
  frontend/src/container/OptionsMenu/types.ts
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
Labels: enhancement

#5753 feat: add support for group by attribute in log details
  frontend/public/Icons/groupBy.svg
  frontend/src/assets/CustomIcons/GroupByIcon.tsx
  frontend/src/components/LogDetail/LogDetail.interfaces.ts
  frontend/src/components/LogDetail/index.tsx
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/container/LiveLogs/LiveLogsList/index.tsx
  frontend/src/container/LogDetailedView/Overview.tsx
  frontend/src/container/LogDetailedView/TableView.styles.scss
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogDetailedView/TableView/TableViewActions.styles.scss
  frontend/src/container/LogDetailedView/TableView/TableViewActions.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsPanelTable/LogsPanelComponent.tsx
  frontend/src/container/LogsTable/index.tsx
  frontend/src/container/PipelinePage/PipelineListsView/Preview/components/LogsList/index.tsx
  frontend/src/hooks/logs/types.ts
  frontend/src/hooks/logs/useActiveLog.ts
  frontend/src/pages/LogsExplorer/index.tsx
Labels: enhancement

#5655 feat: tabs and filters for alert history page
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/components/AlertDetailsFilters/Filters.tsx
  frontend/src/components/AlertDetailsFilters/filters.styles.scss
  frontend/src/constants/routes.ts
  frontend/src/container/AlertHistory/alertHistory.styles.scss
  frontend/src/container/AlertHistory/index.tsx
  frontend/src/container/AlertHistory/types.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/pages/AlertDetails/alertDetails.styles.scss
  frontend/src/pages/AlertDetails/hooks.tsx
  frontend/src/pages/AlertDetails/index.tsx
  frontend/src/pages/AlertHistory/index.tsx
  frontend/src/utils/permission/index.ts
Labels: enhancement

#5755 fix: raw view css condense fix for line clamp
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/RawLogView/styles.ts
Labels: bug

#5751 feat(render): add render package
  pkg/errors/errors.go
  pkg/http/render/render.go
  pkg/http/render/render_test.go
  pkg/http/render/status.go
  pkg/query-service/app/http_handler.go
Labels: enhancement

#5752 fix: handled defaultTraceSelected for traces list view
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
Labels: bug

#5724 fix: remove same origin check and return proper errors from upgrader function
  deploy/docker/common/nginx-config.conf
  frontend/src/api/common/getQueryStats.ts
  frontend/src/container/LogsExplorerViews/index.tsx
  pkg/query-service/app/http_handler.go
Labels: bug, chore

#5745 chore: add total count and state filter
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/common/query_range.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/v3/v3.go
  pkg/query-service/rules/alerting.go
  pkg/query-service/rules/api_params.go
  pkg/query-service/rules/prom_rule.go
  pkg/query-service/rules/threshold_rule.go
Labels: chore

#5766 patch for ee
  ee/query-service/app/server.go
Labels: request-more-info

#5767 chore: add extra safety nets in case of malformed URL
  frontend/src/pages/LogsExplorer/index.tsx
Labels: chore

#5749 fix: colored logs in new logs explorer
  frontend/src/components/LogDetail/index.tsx
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/TableView/useTableView.tsx
  frontend/src/container/LogDetailedView/Overview.tsx
  frontend/src/container/LogDetailedView/TableView/TableViewActions.tsx
  frontend/src/container/LogDetailedView/utils.tsx
Labels: bug

#5760 feat: enable macro
  deploy/docker-swarm/clickhouse-setup/clickhouse-config.xml
  deploy/docker/clickhouse-setup/clickhouse-config.xml
  pkg/query-service/tests/test-deploy/clickhouse-config.xml
Labels: enhancement

#5770 fix: copy to clipboard not copying complete value in case of numbers
  frontend/src/components/Logs/AddToQueryHOC.styles.scss
  frontend/src/components/Logs/CopyClipboardHOC.tsx
  frontend/src/container/LogDetailedView/FieldRenderer.styles.scss
  frontend/src/container/LogDetailedView/TableView/TableViewActions.tsx
Labels: bug

#5769 small patch to fix consumer_group check
  pkg/query-service/app/integrations/messagingQueues/kafka/translator.go
Labels: request-more-info

#5590 chore: clean out the logs time range issues / old logs explorer routes issue
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsTable/index.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/hooks/logs/types.ts
  frontend/src/hooks/logs/useCopyLogLink.ts
  frontend/src/hooks/useLogsData.ts
  frontend/src/utils/permission/index.ts
Labels: chore

#5773 Feat: alert history horizontal timeline chart
  frontend/src/api/alerts/timelineGraph.ts
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/container/AlertHistory/Timeline/Graph/Graph.tsx
  frontend/src/container/AlertHistory/Timeline/Graph/constants.ts
  frontend/src/container/AlertHistory/Timeline/GraphWrapper/GraphWrapper.tsx
  frontend/src/container/AlertHistory/Timeline/Timeline.tsx
  frontend/src/lib/uPlotLib/plugins/timelinePlugin.ts
  frontend/src/pages/AlertDetails/hooks.tsx
  frontend/src/periscope/components/DataStateRenderer/DataStateRenderer.tsx
  frontend/src/types/api/alerts/def.ts
  frontend/src/types/api/alerts/timelineGraph.ts
  frontend/src/utils/timeUtils.ts
Labels: enhancement

#5675 feat: alert rule details metadata header
  frontend/public/locales/en-GB/titles.json
  frontend/public/locales/en/titles.json
  frontend/src/assets/AlertHistory/SeverityCriticalIcon.tsx
  frontend/src/assets/AlertHistory/SeverityErrorIcon.tsx
  frontend/src/assets/AlertHistory/SeverityInfoIcon.tsx
  frontend/src/assets/AlertHistory/SeverityWarningIcon.tsx
  frontend/src/pages/AlertDetails/AlertHeader/ActionButtons/actionButtons.styles.scss
  frontend/src/pages/AlertDetails/AlertHeader/ActionButtons/index.tsx
  frontend/src/pages/AlertDetails/AlertHeader/AlertHeader.tsx
  frontend/src/pages/AlertDetails/AlertHeader/AlertIcon/AlertIcon.tsx
  frontend/src/pages/AlertDetails/AlertHeader/AlertIcon/alertIcon.styles.scss
  frontend/src/pages/AlertDetails/AlertHeader/AlertLabels/AlertLabels.tsx
  frontend/src/pages/AlertDetails/AlertHeader/AlertLabels/alertLabels.styles.scss
  frontend/src/pages/AlertDetails/AlertHeader/AlertSeverity/AlertSeverity.tsx
  frontend/src/pages/AlertDetails/AlertHeader/AlertSeverity/alertSeverity.styles.scss
  frontend/src/pages/AlertDetails/AlertHeader/AlertStatus/AlertStatus.tsx
  frontend/src/pages/AlertDetails/AlertHeader/AlertStatus/alertStatus.styles.scss
  frontend/src/pages/AlertDetails/AlertHeader/AlertStatus/types.ts
  frontend/src/pages/AlertDetails/AlertHeader/alertHeader.styles.scss
  frontend/src/pages/AlertDetails/alertDetails.styles.scss
  frontend/src/pages/AlertDetails/hooks.tsx
  frontend/src/pages/AlertDetails/index.tsx
  frontend/src/pages/AlertDetails/types.ts
  frontend/src/pages/EditRules/index.tsx
  frontend/src/periscope/components/CopyToClipboard/copyToClipboard.styles.scss
  frontend/src/periscope/components/CopyToClipboard/index.tsx
  frontend/src/periscope/components/KeyValueLabel/KeyValueLabel.tsx
  frontend/src/periscope/components/KeyValueLabel/keyValueLabel.styles.scss
  frontend/src/periscope/components/SeeMore/SeeMore.tsx
  frontend/src/periscope/components/SeeMore/seeMore.styles.scss
  frontend/src/utils/timeUtils.ts
Labels: enhancement

#5776 Fix/alert history UI fixes
  frontend/src/components/AlertDetailsFilters/Filters.tsx
  frontend/src/container/AlertHistory/Timeline/GraphWrapper/GraphWrapper.tsx
  frontend/src/container/AlertHistory/Timeline/Table/Table.tsx
  frontend/src/container/AlertHistory/Timeline/Timeline.tsx
  frontend/src/container/FormAlertRules/QuerySection.styles.scss
  frontend/src/pages/AlertDetails/AlertHeader/AlertHeader.tsx
  frontend/src/pages/AlertDetails/alertDetails.styles.scss
  frontend/src/pages/AlertDetails/index.tsx
  frontend/src/pages/EditRules/EditRules.styles.scss
  frontend/src/pages/EditRules/index.tsx
Labels: bug

#5775 fix: remove the checks for aggregate operator in case of metrics v3/v4
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
  frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
Labels: bug

#5777 fix: double encode composite query for explorer links
  pkg/query-service/common/query_range.go
  pkg/query-service/rules/threshold_rule.go
Labels: bug

#5731 fix: changing color of beta tag for Service Map & light theme changer
  frontend/src/container/MySettings/index.tsx
  frontend/src/container/SideNav/NavItem/NavItem.tsx
Labels: bug

#5785 feat: messaging queue misc tasks
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCard/types.ts
  frontend/src/container/PanelWrapper/PanelWrapper.tsx
  frontend/src/container/PanelWrapper/UplotPanelWrapper.tsx
  frontend/src/container/PanelWrapper/panelWrapper.types.ts
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
  frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
  frontend/src/pages/MessagingQueues/MQDetailPage/MQDetailPage.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/MQTables.styles.scss
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/MQTables.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/getConsumerLagDetails.ts
  frontend/src/pages/MessagingQueues/MQGraph/MQGraph.tsx
  frontend/src/pages/MessagingQueues/MessagingQueues.styles.scss
  frontend/src/pages/MessagingQueues/MessagingQueues.tsx
  frontend/src/pages/MessagingQueues/MessagingQueuesUtils.ts
Labels: enhancement, testing-deploy

#5690 feat: added Messaging queue detail page
  frontend/public/locales/en/titles.json
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/constants/query.ts
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/constants/routes.ts
  frontend/src/constants/shortcuts/globalShortcuts.ts
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCard/types.ts
  frontend/src/container/PanelWrapper/PanelWrapper.tsx
  frontend/src/container/PanelWrapper/UplotPanelWrapper.tsx
  frontend/src/container/PanelWrapper/panelWrapper.types.ts
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/container/SideNav/config.ts
  frontend/src/container/SideNav/menuItems.tsx
  frontend/src/container/TopNav/Breadcrumbs/index.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
  frontend/src/lib/uPlotLib/plugins/onClickPlugin.ts
  frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
  frontend/src/pages/MessagingQueues/MQCommon/MQCommon.styles.scss
  frontend/src/pages/MessagingQueues/MQCommon/MQCommon.tsx
  frontend/src/pages/MessagingQueues/MQDetailPage/MQDetailPage.tsx
  frontend/src/pages/MessagingQueues/MQDetailPage/index.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MQDetails.style.scss
  frontend/src/pages/MessagingQueues/MQDetails/MQDetails.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/MQTables.styles.scss
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/MQTables.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/getConsumerLagDetails.ts
  frontend/src/pages/MessagingQueues/MQGraph/MQConfigOptions.styles.scss
  frontend/src/pages/MessagingQueues/MQGraph/MQConfigOptions.tsx
  frontend/src/pages/MessagingQueues/MQGraph/MQGraph.tsx
  frontend/src/pages/MessagingQueues/MQGraph/useGetAllConfigOptions.ts
  frontend/src/pages/MessagingQueues/MessagingQueues.styles.scss
  frontend/src/pages/MessagingQueues/MessagingQueues.tsx
  frontend/src/pages/MessagingQueues/MessagingQueuesUtils.ts
  frontend/src/pages/MessagingQueues/index.tsx
  frontend/src/utils/permission/index.ts
Labels: enhancement

#5797 fix: show add credit card modal only for cloud users
  frontend/src/container/AppLayout/index.tsx
Labels: bug, request-more-info

#5523 chore: added trace detail tests
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/mocks-server/__mockdata__/tracedetail.ts
  frontend/src/mocks-server/handlers.ts
  frontend/src/pages/TraceDetail/__test__/TraceDetail.test.tsx
Labels: chore

#5519 chore: added trace views test
  frontend/src/mocks-server/__mockdata__/explorer_views.ts
  frontend/src/pages/SaveView/__test__/SaveView.test.tsx
  frontend/src/pages/SaveView/index.tsx
  frontend/src/pages/TracesExplorer/__test__/TracesExplorer.test.tsx
Labels: chore

#5802 chore: remove old data migrations
  pkg/query-service/migrate/0_45_alerts_to_v4/run.go
  pkg/query-service/migrate/0_47_alerts_custom_step/run.go
  pkg/query-service/migrate/migate.go
Labels: chore

#5803 chore: remove feature usage code from manager
  pkg/query-service/rules/manager.go
Labels: enhancement, chore

#5804 chore: add types for alert type, state, and rule data kind
  pkg/query-service/app/http_handler.go
  pkg/query-service/rules/alerting.go
  pkg/query-service/rules/api_params.go
  pkg/query-service/rules/db.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/threshold_rule.go
  pkg/query-service/rules/threshold_rule_test.go
Labels: chore

#5801 feat: Kafka UI feedbacks
  frontend/src/container/SideNav/NavItem/NavItem.styles.scss
  frontend/src/container/SideNav/NavItem/NavItem.tsx
  frontend/src/container/SideNav/menuItems.tsx
  frontend/src/pages/MessagingQueues/MQCommon/MQCommon.tsx
  frontend/src/pages/MessagingQueues/MQDetailPage/MQDetailPage.tsx
  frontend/src/pages/MessagingQueues/MessagingQueues.styles.scss
  frontend/src/pages/MessagingQueues/MessagingQueues.tsx
  frontend/src/pages/MessagingQueues/MessagingQueuesUtils.ts
Labels: enhancement

#5810 chore: added logeEvents in Kafka-ui
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCard/types.ts
  frontend/src/pages/MessagingQueues/MQDetailPage/MQDetailPage.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/MQTables.tsx
  frontend/src/pages/MessagingQueues/MQGraph/MQGraph.tsx
  frontend/src/pages/MessagingQueues/MessagingQueues.tsx
Labels: chore

#5728 feat: consume the new search bar
  ee/query-service/model/plans.go
  frontend/src/constants/features.ts
  frontend/src/container/LogExplorerQuerySection/index.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/Suggestions.styles.scss
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/Suggestions.tsx
Labels: enhancement, DO NOT MERGE

#5805 chore: change returned error from list to error
  pkg/query-service/rules/api_params.go
  pkg/query-service/rules/manager.go
Labels: chore
