Repository SigNoz/signoz, pull requests merged in 2024-10, with the labels that each got.

#5980 feat: add expand/collapse button to the top in trace details
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
  frontend/src/container/TraceDetail/TraceDetails.styles.scss
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/container/TraceDetail/styles.ts
  frontend/src/pages/TraceDetail/__test__/TraceDetail.test.tsx
Labels: enhancement

#5994 fix: added custom breakdown of one day to handle billing graph issue.
  frontend/src/container/BillingContainer/BillingUsageGraph/BillingUsageGraph.tsx
Labels: bug

#5928 feat: add drag support to alert history horizontal graph
  frontend/src/container/AlertHistory/Timeline/Graph/Graph.tsx
  frontend/src/pages/AlertDetails/hooks.tsx
Labels: enhancement

#5242 feat: add ability to configure number of required points
  frontend/public/locales/en-GB/alerts.json
  frontend/public/locales/en/alerts.json
  frontend/src/container/FormAlertRules/RuleOptions.tsx
  frontend/src/types/api/alerts/def.ts
  pkg/query-service/rules/alerting.go
  pkg/query-service/rules/base_rule.go
  pkg/query-service/rules/base_rule_test.go
Labels: enhancement

#6062 feat: add dot support for alerts
  ee/query-service/app/server.go
  ee/query-service/rules/anomaly.go
  ee/query-service/rules/manager.go
  pkg/query-service/app/server.go
  pkg/query-service/rules/base_rule.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/prom_rule.go
  pkg/query-service/rules/result_types.go
  pkg/query-service/rules/templates.go
  pkg/query-service/rules/templates_test.go
  pkg/query-service/rules/threshold_rule.go
  pkg/query-service/rules/threshold_rule_test.go
Labels: enhancement

#5647 feat: store columns while saving view and restore columns on selecting view without select columns
  frontend/src/components/ExplorerCard/types.ts
  frontend/src/components/ExplorerCard/utils.ts
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
Labels: enhancement

#5826 feat: added view logs button for error and latency chart
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/GraphControlsPanel/GraphControlsPanel.styles.scss
  frontend/src/container/MetricsApplication/Tabs/Overview/GraphControlsPanel/GraphControlsPanel.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ServiceOverview.tsx
  frontend/src/container/MetricsApplication/Tabs/util.ts
Labels: enhancement

#6089 chore: changes for new alert e2e tests
  frontend/src/container/CreateAlertRule/SelectAlertType/index.tsx
  frontend/src/container/FormAlertRules/BasicInfo.tsx
  frontend/src/container/FormAlertRules/ChannelSelect/index.tsx
  frontend/src/container/FormAlertRules/QuerySection.tsx
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
Labels: chore

#5898 fix: fix incorrect alert history state
  frontend/src/pages/AlertDetails/AlertHeader/ActionButtons/ActionButtons.tsx
  frontend/src/pages/AlertDetails/AlertHeader/AlertHeader.tsx
  frontend/src/pages/AlertDetails/hooks.tsx
  frontend/src/providers/Alert.tsx
Labels: bug

#6127 fix: updated the triggered alert list code
  frontend/src/container/TriggeredAlerts/Filter.tsx
  frontend/src/container/TriggeredAlerts/TriggeredAlert.tsx
  frontend/src/container/TriggeredAlerts/index.tsx
Labels: bug

#6106 chore: do not materialize ttl after modify
  pkg/query-service/app/clickhouseReader/reader.go
Labels: chore

#5891 feat: client side query builder search
  frontend/src/components/ClientSideQBSearch/ClientSideQBSearch.styles.scss
  frontend/src/components/ClientSideQBSearch/ClientSideQBSearch.tsx
  frontend/src/container/AlertHistory/Timeline/Table/Table.styles.scss
  frontend/src/container/AlertHistory/Timeline/Table/Table.tsx
  frontend/src/container/AlertHistory/Timeline/Table/useTimelineTable.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.styles.scss
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/Suggestions.styles.scss
  frontend/src/container/QueryBuilder/filters/utils.ts
  frontend/src/pages/AlertDetails/AlertHeader/AlertLabels/AlertLabels.tsx
  frontend/src/pages/AlertDetails/hooks.tsx
  frontend/src/providers/Alert.tsx
  frontend/src/types/api/alerts/def.ts
Labels: enhancement

#6136 chore: added some easter eggs
  frontend/src/AppRoutes/index.tsx
Labels: chore

#6117 fix: hide PromQL from table panel type
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/utils.ts
Labels: bug

#6130 fix: incorrect query being generated from traces page
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/config.ts
Labels: bug

#6140 chore: hide promql from panel type - pie
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/utils.ts
Labels: chore

#6133 feat: added info funct for panels in dashaboard layout for showing description
  frontend/src/container/GridCardLayout/WidgetHeader/WidgetHeader.styles.scss
  frontend/src/container/GridCardLayout/WidgetHeader/index.tsx
Labels: enhancement

#6000 fix: enrich attributes regardless if it is materialized
  pkg/query-service/app/logs/v3/enrich_query.go
  pkg/query-service/app/logs/v3/enrich_query_test.go
  pkg/query-service/contextlinks/links.go
  pkg/query-service/model/logs.go
  pkg/query-service/model/v3/v3.go
  pkg/query-service/utils/logs.go
  pkg/query-service/utils/logs_test.go
Labels: bug

#6095 chore: bump SigNoz/prometheus
  ee/query-service/main.go
  go.mod
  go.sum
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/main.go
  pkg/query-service/pqlEngine/engine.go
Labels: chore

#6096 chore: skip showing metrics with dot in name
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/interfaces/interface.go
Labels: chore

#6123 chore: add hosts list support
  ee/query-service/app/server.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/infra.go
  pkg/query-service/app/inframetrics/hosts.go
  pkg/query-service/app/inframetrics/table_list_query.go
  pkg/query-service/app/inframetrics/table_list_query_k8s.go
  pkg/query-service/app/querier/v2/querier.go
  pkg/query-service/app/server.go
  pkg/query-service/model/infra.go
Labels: chore

#6163 Revert "chore(deps): bump uplot from 1.6.26 to 1.6.31 in /frontend"
  frontend/package.json
  frontend/yarn.lock
Labels: chore

#6165 chore: update body parser
  frontend/package.json
  frontend/yarn.lock
Labels: chore, request-more-info

#5916 feat: anomaly detection UI
  frontend/public/locales/en-GB/alerts.json
  frontend/public/locales/en-GB/rules.json
  frontend/public/locales/en/alerts.json
  frontend/public/locales/en/rules.json
  frontend/src/constants/alerts.ts
  frontend/src/constants/query.ts
  frontend/src/constants/queryFunctionOptions.ts
  frontend/src/container/AnomalyAlertEvaluationView/AnomalyAlertEvaluationView.styles.scss
  frontend/src/container/AnomalyAlertEvaluationView/AnomalyAlertEvaluationView.tsx
  frontend/src/container/AnomalyAlertEvaluationView/index.tsx
  frontend/src/container/CreateAlertRule/SelectAlertType/config.ts
  frontend/src/container/CreateAlertRule/SelectAlertType/index.tsx
  frontend/src/container/CreateAlertRule/defaults.ts
  frontend/src/container/CreateAlertRule/index.tsx
  frontend/src/container/EditRules/index.tsx
  frontend/src/container/FormAlertRules/BasicInfo.tsx
  frontend/src/container/FormAlertRules/ChartPreview/ChartPreview.styles.scss
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/FormAlertRules/FormAlertRules.styles.scss
  frontend/src/container/FormAlertRules/QuerySection.tsx
  frontend/src/container/FormAlertRules/RuleOptions.styles.scss
  frontend/src/container/FormAlertRules/RuleOptions.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/FormAlertRules/styles.ts
  frontend/src/container/QueryBuilder/components/QueryFunctions/Function.tsx
  frontend/src/lib/dashboard/getQueryResults.ts
  frontend/src/lib/newQueryBuilder/convertNewDataToOld.ts
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
  frontend/src/lib/uPlotLib/utils/getUplotChartData.ts
  frontend/src/lib/uPlotLib/utils/getYAxisScale.ts
  frontend/src/periscope/components/Tabs2/Tabs2.styles.scss
  frontend/src/types/api/alerts/alertTypes.ts
  frontend/src/types/api/alerts/def.ts
  frontend/src/types/api/widgets/getQuery.ts
  frontend/src/types/common/queryBuilder.ts
Labels: enhancement, request-more-info

#6180 feat: move anomaly detection behind ff and show beta
  frontend/src/constants/features.ts
  frontend/src/container/CreateAlertRule/SelectAlertType/config.ts
  frontend/src/container/CreateAlertRule/SelectAlertType/index.tsx
  frontend/src/container/CreateAlertRule/SelectAlertType/types.ts
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/periscope/components/Tabs2/Tabs2.tsx
Labels: enhancement

#6177 fix: fixed incorrect label for orderBy clause when selected
  frontend/src/container/QueryBuilder/filters/OrderByFilter/useOrderByFilter.ts
  frontend/src/container/QueryBuilder/filters/OrderByFilter/utils.ts
Labels: bug

#6184 chore: update default feature flag and error response for formula
  ee/query-service/app/api/queryrange.go
  ee/query-service/model/plans.go
Labels: enhancement, chore

#6154 fix: updated row key in triggered alert list table
  frontend/src/container/TriggeredAlerts/NoFilterTable.tsx
Labels: bug

#6185 feat: search series in anomaly response data
  frontend/src/container/AnomalyAlertEvaluationView/AnomalyAlertEvaluationView.styles.scss
  frontend/src/container/AnomalyAlertEvaluationView/AnomalyAlertEvaluationView.tsx
Labels: enhancement

#6125 chore: add process list
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/infra.go
  pkg/query-service/app/inframetrics/hosts.go
  pkg/query-service/app/inframetrics/processes.go
  pkg/query-service/app/inframetrics/table_list_query.go
  pkg/query-service/model/infra.go
Labels: chore

#6086 fix: fixed all not deselecting and empty array setting to _ALL_
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
Labels: bug

#6199 fix(docker): use env prefix for boolean in collector config
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
  pkg/query-service/tests/test-deploy/otel-collector-config.yaml
Labels: bug, testing-deploy

#6090 fix: add v4 to the new alert payload
  frontend/src/api/alerts/create.ts
Labels: bug

#6183 chore: add test id to additional filters button
  frontend/src/components/ResizeTable/DynamicColumnTable.tsx
Labels: chore

#6057 feat: bulk invite user api
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/parser.go
  pkg/query-service/auth/auth.go
  pkg/query-service/model/auth.go
Labels: enhancement

#6058 feat: onboarding API via proxy
  ee/query-service/app/api/gateway.go
  ee/query-service/integrations/gateway/proxy.go
Labels: enhancement

#6212 chore: remove the trial expiry banner on logout
  frontend/src/container/AppLayout/index.tsx
Labels: chore

#6216 chore: make the clear selection view more highlighted
  frontend/src/container/ExplorerOptions/ExplorerOptions.styles.scss
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/container/ExplorerOptions/ExplorerOptionsHideArea.tsx
Labels: chore

#6217 chore: change the log background to same as severity text with some opacity
  frontend/src/components/LogDetail/index.tsx
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/ListLogView/styles.ts
  frontend/src/components/Logs/LogStateIndicator/LogStateIndicator.styles.scss
  frontend/src/components/Logs/LogStateIndicator/LogStateIndicator.test.tsx
  frontend/src/components/Logs/LogStateIndicator/LogStateIndicator.tsx
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/RawLogView/styles.ts
  frontend/src/components/Logs/TableView/useTableView.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/TableRow.styles.scss
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/styles.ts
  frontend/src/utils/logs.ts
Labels: chore

#5679 chore: update query builder to use 5min/30min aggregation tables
  pkg/query-service/app/metrics/v4/cumulative/timeseries.go
  pkg/query-service/app/metrics/v4/delta/timeseries.go
  pkg/query-service/app/metrics/v4/helpers/sub_query.go
  pkg/query-service/app/metrics/v4/query_builder_pre_agg_test.go
  pkg/query-service/app/metrics/v4/query_builder_test.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/parser_test.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
  pkg/query-service/constants/constants.go
  pkg/query-service/rules/threshold_rule.go
Labels: chore

#6079 fix: fixed threshold for columns with units
  frontend/src/container/GridTableComponent/index.tsx
  frontend/src/container/GridTableComponent/utils.ts
  frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/ThresholdSelector.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/types.ts
  frontend/src/container/NewWidget/RightContainer/constants.ts
  frontend/src/container/NewWidget/RightContainer/dataFormatCategories.ts
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/container/NewWidget/utils.ts
Labels: bug

#6145 fix: removed selectedValue & uuid from exported and copied dashboard json
  frontend/src/container/ListOfDashboard/ImportJSON/index.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
Labels: bug

#6222 chore: added doc link for kafka on getStarted for non-cloud users
  frontend/src/pages/MessagingQueues/MessagingQueuesUtils.ts
Labels: chore

#6225 chore: remove the required check from organisation name
  frontend/src/pages/SignUp/SignUp.tsx
Labels: chore

#6238 feat: move resource qb to its own package and use common options
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/app/logs/v4/query_builder.go
  pkg/query-service/app/logs/v4/query_builder_test.go
  pkg/query-service/app/querier/helper.go
  pkg/query-service/app/querier/v2/helper.go
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/app/resource/resource_query_builder.go
  pkg/query-service/app/resource/resource_query_builder_test.go
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/app/traces/v3/query_builder_test.go
  pkg/query-service/model/v3/v3.go
Labels: enhancement

#6107 chore: split migrator job to sync and async
  deploy/docker/clickhouse-setup/docker-compose-minimal.yaml
Labels: chore

#6194 feat: tooltip plugin to show series data in tooltip
  frontend/src/constants/queryFunctionOptions.ts
  frontend/src/container/AnomalyAlertEvaluationView/AnomalyAlertEvaluationView.styles.scss
  frontend/src/container/AnomalyAlertEvaluationView/AnomalyAlertEvaluationView.tsx
  frontend/src/container/AnomalyAlertEvaluationView/tooltipPlugin.ts
  frontend/src/container/CreateAlertRule/defaults.ts
  frontend/src/container/CreateAlertRule/index.tsx
  frontend/src/container/FormAlertRules/RuleOptions.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/QueryBuilder/components/QueryFunctions/Function.tsx
  frontend/src/container/QueryBuilder/components/QueryFunctions/QueryFunctions.tsx
  frontend/src/lib/uPlotLib/utils/getUplotChartData.ts
  frontend/src/lib/uPlotLib/utils/getYAxisScale.ts
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
Labels: enhancement

#6245 feat: remove hardcode is darkmode value from get anomaly data func
  frontend/src/container/AnomalyAlertEvaluationView/AnomalyAlertEvaluationView.tsx
  frontend/src/lib/uPlotLib/utils/getUplotChartData.ts
Labels: enhancement

#6246 fix: name is optional in bulk invite API
  pkg/query-service/app/parser.go
Labels: bug

#6248 feat: add org onboarding preference
  pkg/query-service/app/preferences/map.go
Labels: enhancement

#6247 Fix/bulk invite api error response
  pkg/query-service/app/http_handler.go
Labels: bug

#6239 chore: add missing shiftby in alert rule
  pkg/query-service/app/parser.go
  pkg/query-service/app/parser_test.go
  pkg/query-service/model/v3/v3.go
  pkg/query-service/rules/threshold_rule.go
  pkg/query-service/rules/threshold_rule_test.go
Labels: chore

#6243 chore: enable anomaly detection for ee/paid plan
  ee/query-service/model/plans.go
Labels: chore

#6227 chore: update hosts list to use pre-aggregated data table dynamically
  pkg/query-service/app/inframetrics/common.go
  pkg/query-service/app/inframetrics/hosts.go
  pkg/query-service/app/metrics/v4/helpers/sub_query.go
  pkg/query-service/model/v3/v3.go
Labels: chore

#6229 chore: add k8s pods list
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/infra.go
  pkg/query-service/app/inframetrics/common.go
  pkg/query-service/app/inframetrics/pods.go
  pkg/query-service/app/inframetrics/pods_query.go
  pkg/query-service/model/infra.go
  pkg/query-service/postprocess/process.go
Labels: chore

#6234 chore: add clusters list
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/infra.go
  pkg/query-service/app/inframetrics/clusters.go
  pkg/query-service/app/inframetrics/common.go
  pkg/query-service/model/infra.go
Labels: chore

#6258 fix: explicitly return the empty slice for variables query
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#6256 chore: remove facing issues button
  frontend/src/components/LaunchChatSupport/util.ts
  frontend/src/container/ListAlertRules/ListAlert.tsx
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/pages/Integrations/Header.tsx
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailPage.tsx
Labels: chore

#6268 Fix api query context
  .github/workflows/staging-deployment.yaml
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/integrations/messagingQueues/kafka/model.go
  pkg/query-service/app/integrations/messagingQueues/kafka/translator.go
Labels: request-more-info

#6275 feat(integrations): whitelist /deployments/me
  ee/query-service/integrations/gateway/proxy.go
Labels: enhancement

#6276 fix: arithmetic operators are removed from Dashboard query builder formulas
  frontend/src/container/GridCardLayout/WidgetHeader/index.tsx
Labels: bug

#6200 fix: issue while switching between views
  frontend/src/hooks/useUrlQueryData.ts
Labels: bug

#6290 chore: bump signoz-otel-collector version
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/docker-compose-core.yaml
  deploy/docker/clickhouse-setup/docker-compose-minimal.yaml
  deploy/docker/clickhouse-setup/docker-compose.testing.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
Labels: chore

#6260 fix: fixed the step interval which was being perculated to list view
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/querier/v2/querier_test.go
  pkg/query-service/app/traces/v3/query_builder.go
Labels: bug

#6303 chore: move hostname to resource attributes for logs qf
  frontend/src/pages/LogsExplorer/utils.tsx
Labels: chore

#6282 fix: add support for {{.Labels.<key>}} with dots in `key` for template
  pkg/query-service/rules/templates.go
  pkg/query-service/rules/templates_test.go
Labels: bug

#6266 [Snyk] Fix for 2 vulnerabilities
  frontend/package.json
  frontend/yarn.lock
Labels: bug

#6291 chore: upgrade axios from 1.7.4 to 1.7.7
  frontend/package.json
  frontend/yarn.lock
Labels: chore

#6334 fix: typo
  pkg/query-service/app/integrations/messagingQueues/kafka/translator.go
Labels: request-more-info
