Repository SigNoz/signoz, pull requests merged in 2024-05, with the labels that each got.

#4944 fix: step interval not getting updated on time range change
  frontend/src/container/GridCardLayout/GridCard/index.tsx
Labels: bug

#4940 fix: time interval not getting updated in case of edit dashboard
  frontend/src/container/NewWidget/LeftContainer/index.tsx
Labels: bug

#4941 fix: ch queries sending builder as query type in query range api for exceptions alerts
  frontend/src/constants/query.ts
  frontend/src/container/CreateAlertRule/index.tsx
  frontend/src/container/FormAlertRules/index.tsx
Labels: bug

#4936 fix: fixed facing issue btn alignment issue
  frontend/src/components/facingIssueBtn/util.ts
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/ListAlertRules/ListAlert.tsx
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewWidget/NewWidget.styles.scss
  frontend/src/container/NewWidget/index.tsx
Labels: bug

#4949 feat: show milliseconds in timestamp in logs views
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/TableView/useTableView.tsx
  frontend/src/container/LogControls/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
Labels: enhancement

#4939 fix: add safety checks to handle null response from query range API
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
Labels: bug, request-more-info

#4950 chore: disallow small step intervals for large durations
  pkg/query-service/app/parser.go
  pkg/query-service/app/parser_test.go
  pkg/query-service/common/metrics.go
  pkg/query-service/constants/constants.go
  pkg/query-service/rules/thresholdRule.go
  pkg/query-service/rules/thresholdRule_test.go
Labels: chore

#4948 feat: added tooltips for facing issue btn
  frontend/src/components/facingIssueBtn/FacingIssueBtn.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/ListAlertRules/ListAlert.tsx
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewWidget/index.tsx
Labels: enhancement

#4872 feat: added test cases for pipeline pages
  frontend/src/container/PipelinePage/Layouts/ChangeHistory/tests/ChangeHistory.test.tsx
  frontend/src/container/PipelinePage/Layouts/ChangeHistory/tests/testUtils.ts
  frontend/src/container/PipelinePage/tests/CreatePipelineButton.test.tsx
  frontend/src/container/PipelinePage/tests/PipelinesSearchSection.test.tsx
Labels: enhancement

#4955 Revert "fix: step interval not getting updated on time range change"
  frontend/src/container/GridCardLayout/GridCard/index.tsx
Labels: bug

#4962 feat: sort tags and events in trace detail
  frontend/src/container/TraceDetail/SelectedSpanDetails/Events/index.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/Tags/index.tsx
Labels: enhancement

#4918 fix: add read-in-order config
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/clickhouseReader/wrapper.go
Labels: bug

#4963 fix: make integrations available for the ee cloud user
  frontend/src/container/SideNav/SideNav.tsx
Labels: bug, do not merge

#4964 fix: prevent page from crashing in case items in filters is null
  frontend/src/lib/newQueryBuilder/getPaginationQueryData.ts
Labels: bug

#4945 feat(workflow): integrate with workflow identity pool
  .github/workflows/staging-deployment.yaml
  .github/workflows/testing-deployment.yaml
Labels: enhancement, testing-deploy

#4969 fix: added right padding to the notifications bar to show cancel button
  frontend/src/styles.scss
Labels: bug

#4946 feat: dashboard widget edit page design revamp
  frontend/src/components/TimePreferenceDropDown/TimePreference.styles.scss
  frontend/src/components/TimePreferenceDropDown/index.tsx
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/NewWidget/LeftContainer/LeftContainer.styles.scss
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QuerySection.styles.scss
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/LeftContainer/QueryTypeTag.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/PlotTag.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraph.styles.scss
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/index.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/styles.ts
  frontend/src/container/NewWidget/LeftContainer/index.tsx
  frontend/src/container/NewWidget/LeftContainer/styles.ts
  frontend/src/container/NewWidget/NewWidget.styles.scss
  frontend/src/container/NewWidget/RightContainer/RightContainer.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/ColorSelector.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/ColorSelector.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/CustomColor.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/ThresholdSelector.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/ThresholdSelector.tsx
  frontend/src/container/NewWidget/RightContainer/YAxisUnitSelector.tsx
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/NewWidget/styles.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
Labels: enhancement

#4990 feat: threshold preview changes
  frontend/src/container/NewWidget/RightContainer/RightContainer.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/ShowCaseValue.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/ShowCaseValue.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/ThresholdSelector.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/types.ts
Labels: enhancement

#4992 feat: dashboard panel grouping change for new designs
  frontend/src/container/GridCardLayout/GridCardLayout.styles.scss
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/container/NewDashboard/DashboardDescription/utils.ts
  frontend/src/container/NewWidget/index.tsx
Labels: enhancement

#4877 chore: add toUnixTimestamp to supported functions
  pkg/query-service/app/formula.go
Labels: chore

#4996 feat: sort and pagination changes for dashboard list view designs
  frontend/src/container/ListOfDashboard/DashboardList.styles.scss
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
Labels: enhancement

#4997 chore: enable limits for trace queries
  pkg/query-service/app/clickhouseReader/wrapper.go
Labels: chore

#4989 chore: allow unlimited dashboards and alerts in community version
  ee/query-service/model/plans.go
  pkg/query-service/model/featureSet.go
Labels: chore

#5006 feat: light mode changes for new dashboard revamp
  frontend/src/components/TimePreferenceDropDown/TimePreference.styles.scss
  frontend/src/container/GridCardLayout/GridCardLayout.styles.scss
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/GridCardLayout/styles.ts
  frontend/src/container/ListOfDashboard/DashboardList.styles.scss
  frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/container/NewDashboard/DashboardSettings/DashboardSettings.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/DashboardSettingsContent.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/General/GeneralSettings.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.styles.scss
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.styles.scss
  frontend/src/container/NewWidget/LeftContainer/LeftContainer.styles.scss
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QuerySection.styles.scss
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraph.styles.scss
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/index.tsx
  frontend/src/container/NewWidget/NewWidget.styles.scss
  frontend/src/container/NewWidget/RightContainer/RightContainer.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/ColorSelector.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/ColorSelector.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/ThresholdSelector.styles.scss
  frontend/src/container/NewWidget/styles.ts
  frontend/src/pages/DashboardsListPage/DashboardsListPage.styles.scss
Labels: enhancement

#5001 fix: several issues
  frontend/src/container/CreateAlertChannels/index.tsx
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metrics/v3/cumulative_table.go
  pkg/query-service/app/metrics/v3/cumulative_table_test.go
  pkg/query-service/app/metrics/v3/delta.go
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v4/query_builder.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/parser_test.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/v2/querier.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
  pkg/query-service/errors/clickhouse.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/v3/v3.go
  pkg/query-service/utils/format.go
  pkg/query-service/utils/queryTemplate/vars.go
Labels: bug

#5014 fix: usability / customer issues
  frontend/src/container/NewDashboard/ComponentsSlider/ComponentSlider.styles.scss
  frontend/src/container/NewDashboard/DashboardDescription/SettingsDrawer.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/index.tsx
  frontend/src/container/NewDashboard/DashboardSettings/index.tsx
Labels: bug

#5015 fix: multiple widgets getting created and hence blocking the delete
  frontend/src/container/NewWidget/index.tsx
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/limit.go
Labels: bug

#5010 chore: migrate alerts to v4 for supported operators
  ee/query-service/main.go
  pkg/query-service/app/formula.go
  pkg/query-service/app/parser.go
  pkg/query-service/main.go
  pkg/query-service/migrate/0_45_alerts_to_v4/run.go
  pkg/query-service/migrate/migate.go
  pkg/query-service/rules/db.go
  pkg/query-service/rules/manager.go
Labels: chore

#5029 fix: metrics order by avg
  pkg/query-service/app/limit.go
Labels: bug

#5030 fix: new dashboards feedback from testing
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/ListOfDashboard/TableComponents/DeleteButton.tsx
  frontend/src/container/NewDashboard/DashboardDescription/Description.styles.scss
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/styles.scss
Labels: bug

#4976 fix: retain the query name,expression and disabled property on changing panel type
  frontend/src/container/NewWidget/utils.ts
  frontend/src/providers/QueryBuilder.tsx
Labels: bug

#4905 feat: restrict the rendering of img and form tags in the logs content
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/TableView/useTableView.tsx
  frontend/src/utils/app.ts
Labels: enhancement

#5034 fix: comment out filters code for phase 2
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
Labels: bug

#5021 chore: query range v3 metrics use v4 tables
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metrics/v3/cumulative_table.go
  pkg/query-service/app/metrics/v3/cumulative_table_test.go
  pkg/query-service/app/metrics/v3/delta.go
  pkg/query-service/app/metrics/v3/delta_table.go
  pkg/query-service/app/metrics/v3/delta_table_test.go
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/app/metrics/v4/helpers/sub_query.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
  pkg/query-service/constants/constants.go
Labels: chore

#5044 Fix promql light theme
  frontend/public/Icons/promQL.svg
  frontend/src/assets/Dashboard/PromQl.tsx
  frontend/src/container/FormAlertRules/QuerySection.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QuerySection.styles.scss
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
Labels: bug

#5054 feat: update packages
  frontend/jest.config.ts
  frontend/package.json
  frontend/yarn.lock
Labels: enhancement, request-more-info

#5024 feat: added helper text, learn-more and doc-link
  frontend/src/container/ExplorerOptions/ExplorerOptions.styles.scss
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/container/FormAlertRules/UserGuide/index.tsx
  frontend/src/container/ListAlertRules/ListAlert.tsx
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/PipelinePage/Layouts/Pipeline/CreatePipelineButton.tsx
  frontend/src/container/PipelinePage/PipelineListsView/PipelineListsView.tsx
  frontend/src/container/PipelinePage/tests/__snapshots__/PipelinePageLayout.test.tsx.snap
  frontend/src/container/QueryBuilder/QueryBuilder.tsx
  frontend/src/container/QueryBuilder/components/QBEntityOptions/QBEntityOptions.tsx
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/components/QueryFunctions/QueryFunctions.tsx
  frontend/src/pages/SaveView/SaveView.styles.scss
  frontend/src/pages/SaveView/index.tsx
Labels: enhancement

#5068 feat: added drag select in time series chart for logs explorer page
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
Labels: enhancement

#5069 feat: added padding bottom to increase the visibility of logs in explorer page
  frontend/src/container/LogsExplorerViews/LogsExplorerViews.styles.scss
Labels: enhancement

#5065 fix: clickhouse builder cursor issue
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/query.tsx
Labels: bug

#5063 fix: cursor resetting in dropdown causing wrong query selection
  frontend/src/hooks/queryBuilder/useAutoComplete.ts
  frontend/src/hooks/queryBuilder/useOptions.ts
Labels: bug

#5040 fix: step interval not getting updated on time range change
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/styles.ts
Labels: bug

#5066 fix: retain the alerts table sorting when editing or discarding the opened alert
  frontend/src/constants/query.ts
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/ListAlertRules/ListAlert.tsx
Labels: bug

#5045 chore: use querier in alerts
  .gitignore
  ee/query-service/app/api/dashboard.go
  ee/query-service/app/server.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/server.go
  pkg/query-service/postprocess/formula.go
  pkg/query-service/postprocess/formula_test.go
  pkg/query-service/postprocess/having.go
  pkg/query-service/postprocess/having_test.go
  pkg/query-service/postprocess/limit.go
  pkg/query-service/postprocess/limit_test.go
  pkg/query-service/postprocess/query_range.go
  pkg/query-service/postprocess/reduce_to.go
  pkg/query-service/postprocess/reduce_to_test.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/thresholdRule.go
  pkg/query-service/rules/thresholdRule_test.go
Labels: chore

#5073 fix: update the metrics datasource version v4 inproduct link
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
Labels: bug

#4863 feat: [SIG-582]: added planned maintenance create dialog
  frontend/src/api/plannedDowntime/createDowntimeSchedule.ts
  frontend/src/api/plannedDowntime/deleteDowntimeSchedule.ts
  frontend/src/api/plannedDowntime/getAllDowntimeSchedules.ts
  frontend/src/api/plannedDowntime/updateDowntimeSchedule.ts
  frontend/src/constants/features.ts
  frontend/src/container/PlannedDowntime/DropdownWithSubMenu/DropdownWithSubMenu.styles.scss
  frontend/src/container/PlannedDowntime/DropdownWithSubMenu/DropdownWithSubMenu.tsx
  frontend/src/container/PlannedDowntime/PlannedDowntime.styles.scss
  frontend/src/container/PlannedDowntime/PlannedDowntime.tsx
  frontend/src/container/PlannedDowntime/PlannedDowntimeDeleteModal.tsx
  frontend/src/container/PlannedDowntime/PlannedDowntimeForm.tsx
  frontend/src/container/PlannedDowntime/PlannedDowntimeList.tsx
  frontend/src/container/PlannedDowntime/PlannedDowntimeutils.ts
  frontend/src/pages/AlertList/index.tsx
  frontend/src/utils/timeZoneUtil.ts
Labels: enhancement

#5067 feat: added download as csv support for table panel type
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/types.ts
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/WidgetHeader/contants.ts
  frontend/src/container/GridCardLayout/WidgetHeader/index.tsx
  frontend/src/container/GridCardLayout/WidgetHeader/utils.ts
  frontend/src/container/GridTableComponent/index.tsx
  frontend/src/container/GridTableComponent/types.ts
  frontend/src/container/PanelWrapper/PanelWrapper.tsx
  frontend/src/container/PanelWrapper/TablePanelWrapper.tsx
  frontend/src/container/PanelWrapper/panelWrapper.types.ts
Labels: enhancement

#5077 fix: remove series with no points
  pkg/query-service/postprocess/having.go
Labels: bug

#5079 fix: add back the templating for query
  pkg/query-service/rules/thresholdRule.go
Labels: bug

#5080 fix: page breaking when all queries are hidden
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphContainer.tsx
Labels: bug

#5016 chore: deprecate old columns in traces
  frontend/src/container/Trace/Filters/index.tsx
  frontend/src/container/Trace/TraceGraphFilter/config.ts
  frontend/src/store/reducers/trace.ts
  frontend/src/types/reducer/trace.ts
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/constants/constants.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/model/response.go
Labels: chore

#5085 chore: default zero only for counters and label normalization
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/model/v3/v3.go
  pkg/query-service/postprocess/formula.go
  pkg/query-service/postprocess/formula_test.go
  pkg/query-service/postprocess/query_range.go
  pkg/query-service/rules/thresholdRule.go
  pkg/query-service/rules/thresholdRule_test.go
  pkg/query-service/utils/labels/labels.go
Labels: chore, request-more-info

#5041 fix: respect the query labels array for ordering than labels object
  frontend/src/lib/query/createTableColumnsFromQuery.ts
  frontend/src/lib/uPlotLib/utils/getYAxisScale.test.ts
  frontend/src/lib/uPlotLib/utils/tests/__mocks__/seriesData.ts
  frontend/src/lib/uPlotLib/utils/tests/__mocks__/uplotChartOptionsData.ts
  frontend/src/types/api/widgets/getQuery.ts
Labels: bug, do not merge

#5083 fix: escape string for contains and ncontains
  pkg/query-service/app/logs/v3/json_filter.go
  pkg/query-service/app/logs/v3/json_filter_test.go
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/app/traces/v3/query_builder_test.go
  pkg/query-service/utils/format.go
Labels: bug

#5084 post-release: sync main changes in develop
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/docker-compose-core.yaml
  deploy/docker/clickhouse-setup/docker-compose.yaml
  deploy/docker/clickhouse-setup/keeper_config.xml
  go.mod
  go.sum
  pkg/query-service/tests/test-deploy/docker-compose.yaml
Labels: chore

#5092 chore: make time macros available for all query types
  pkg/query-service/postprocess/formula.go
  pkg/query-service/utils/queryTemplate/vars.go
Labels: chore

#5094 fix(github): expire ssh keys after 15m
  .github/workflows/staging-deployment.yaml
  .github/workflows/testing-deployment.yaml
Labels: bug, testing-deploy

#5093 fix: query range api triggering on every keystroke
  frontend/src/providers/QueryBuilder.tsx
Labels: bug

#5098 fix: dashboard vqa pt 2
  frontend/src/container/ListOfDashboard/DashboardList.styles.scss
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewWidget/LeftContainer/ExplorerColumnsRenderer.styles.scss
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/QueryHeader.styles.scss
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraph.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/ThresholdSelector.styles.scss
  frontend/src/container/NewWidget/RightContainer/Threshold/ThresholdSelector.tsx
  frontend/src/container/NewWidget/styles.ts
Labels: bug

#5101 fix: dashboard editor width fixes on large screens
  frontend/src/container/NewWidget/RightContainer/RightContainer.styles.scss
  frontend/src/container/NewWidget/styles.ts
Labels: bug

#5104 fix: dashboard design feedback
  frontend/src/container/ListOfDashboard/DashboardList.styles.scss
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
Labels: bug

#5096 fix: clone dashboard panel intermittent issue
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
Labels: bug

#5119 fix: page jumping for alerts
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
Labels: bug

#5114 feat: enable temporary sorting on table panel type
  frontend/src/lib/query/createTableColumnsFromQuery.ts
Labels: enhancement

#5116 fix: random sizing issue with alerts query builder
  frontend/src/container/PlannedDowntime/DropdownWithSubMenu/DropdownWithSubMenu.styles.scss
  frontend/src/styles.scss
Labels: bug

#5124 fix: do not consider Inf and NaN for formula
  pkg/query-service/rules/thresholdRule.go
Labels: bug

#4834 chore: scheduled maintenance query-service impl
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/rules/db.go
  pkg/query-service/rules/maintenance.go
  pkg/query-service/rules/maintenance_test.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/promRuleTask.go
  pkg/query-service/rules/ruleTask.go
  pkg/query-service/rules/task.go
Labels: chore

#5106 chore(query-service): update `GoValuateFuncs` definitions
  pkg/query-service/postprocess/formula.go
Labels: bug
