Repository SigNoz/signoz, pull requests merged in 2024-11, with the labels that each got.

#6318 fix: issues with resource query builder w.r.t quotes
  pkg/query-service/app/logs/v4/query_builder.go
  pkg/query-service/app/resource/resource_query_builder.go
  pkg/query-service/app/resource/resource_query_builder_test.go
  pkg/query-service/utils/format.go
Labels: bug

#6269 enable scenario 4 on staging
  .github/workflows/staging-deployment.yaml
  deploy/docker/clickhouse-setup/docker-compose.testing.yaml
Labels: request-more-info, testing-deploy

#6343 fix: add safety check to check if anomaly rule in uplot chart options
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
Labels: bug

#6342 feat: improve async handling for org onboarding cases
  frontend/src/AppRoutes/Private.tsx
  frontend/src/container/OnboardingContainer/OnboardingContainer.tsx
  frontend/src/container/OnboardingQuestionaire/InviteTeamMembers/InviteTeamMembers.tsx
  frontend/src/container/OnboardingQuestionaire/OnboardingQuestionaire.styles.scss
  frontend/src/container/OnboardingQuestionaire/OptimiseSignozNeeds/OptimiseSignozNeeds.tsx
  frontend/src/container/OnboardingQuestionaire/index.tsx
  frontend/src/pages/SignUp/SignUp.tsx
Labels: enhancement

#6344 chore: add feature flag, handle out-of-index error, some house keeping work
  ee/query-service/model/plans.go
  pkg/query-service/app/inframetrics/common.go
  pkg/query-service/app/inframetrics/hosts.go
  pkg/query-service/app/inframetrics/hosts_query.go
  pkg/query-service/app/inframetrics/namespaces.go
  pkg/query-service/app/inframetrics/pods.go
  pkg/query-service/app/inframetrics/process_query.go
  pkg/query-service/app/inframetrics/processes.go
  pkg/query-service/app/inframetrics/table_list_query_k8s.go
  pkg/query-service/constants/constants.go
  pkg/query-service/model/featureSet.go
  pkg/query-service/model/infra.go
Labels: enhancement, chore

#6355 fix: re add threshold for promql alerts
  frontend/src/container/FormAlertRules/RuleOptions.tsx
Labels: bug

#6333 chore: adding github action to update pr labels and block pr until related docs are…
  .github/workflows/docs.yml
Labels: chore

#6287 feat: added generic UI for scenario 1,3,4
  frontend/src/constants/query.ts
  frontend/src/pages/MessagingQueues/MQDetailPage/MQDetailPage.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MQDetails.style.scss
  frontend/src/pages/MessagingQueues/MQDetails/MQDetails.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/MQTables.styles.scss
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/MQTables.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/getConsumerLagDetails.ts
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/getPartitionLatencyDetails.ts
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/getPartitionLatencyOverview.ts
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/getTopicThroughputDetails.ts
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/getTopicThroughputOverview.ts
  frontend/src/pages/MessagingQueues/MQDetails/MessagingQueueOverview.tsx
  frontend/src/pages/MessagingQueues/MessagingQueues.styles.scss
  frontend/src/pages/MessagingQueues/MessagingQueuesUtils.ts
Labels: enhancement, docs required

#6236 feat: added onboarding setup for Producer for Messaging queues
  frontend/src/api/messagingQueues/onboarding/getOnboardingStatus.ts
  frontend/src/constants/query.ts
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/Kubernetes/springBoot-kubernetes-runApplication-producer.md
  frontend/src/container/OnboardingContainer/Steps/ConnectionStatus/ConnectionStatus.tsx
  frontend/src/container/OnboardingContainer/Steps/DataSource/DataSource.styles.scss
  frontend/src/container/OnboardingContainer/Steps/DataSource/DataSource.tsx
  frontend/src/container/OnboardingContainer/Steps/MarkdownStep/MarkdownStep.tsx
  frontend/src/container/OnboardingContainer/constants/apmDocFilePaths.ts
  frontend/src/container/OnboardingContainer/utils/dataSourceUtils.ts
  frontend/src/hooks/messagingQueue / onboarding/useOnboardingStatus.tsx
  frontend/src/pages/MessagingQueues/MessagingQueues.tsx
  frontend/src/pages/MessagingQueues/MessagingQueuesUtils.ts
Labels: enhancement, docs required

#6362 fix: initialize target to 3 in anomaly detection alert
  frontend/src/container/CreateAlertRule/defaults.ts
Labels: bug

#6267 feat: added the host detail view
  frontend/src/components/HostMetricsDetail/HostMetricDetail.interfaces.ts
  frontend/src/components/HostMetricsDetail/HostMetricsDetail.styles.scss
  frontend/src/components/HostMetricsDetail/constants.ts
  frontend/src/components/HostMetricsDetail/index.tsx
  frontend/src/pages/InfraMonitoringHosts/HostsList.tsx
  frontend/src/pages/InfraMonitoringHosts/utils.tsx
Labels: enhancement

#6371 feat: added healthcheck and attribute checklist component for Kafka
  frontend/src/api/messagingQueues/onboarding/getOnboardingStatus.ts
  frontend/src/container/OnboardingContainer/Modules/APM/Java/md-docs/SpringBoot/Kubernetes/springBoot-kubernetes-runApplication-producers.md
  frontend/src/container/OnboardingContainer/Steps/ConnectionStatus/ConnectionStatus.tsx
  frontend/src/container/OnboardingContainer/Steps/DataSource/DataSource.tsx
  frontend/src/container/OnboardingContainer/constants/apmDocFilePaths.ts
  frontend/src/hooks/messagingQueue / onboarding/useOnboardingStatus.tsx
  frontend/src/pages/MessagingQueues/MessagingQueueHealthCheck/AttributeCheckList.tsx
  frontend/src/pages/MessagingQueues/MessagingQueueHealthCheck/MessagingQueueHealthCheck.styles.scss
  frontend/src/pages/MessagingQueues/MessagingQueueHealthCheck/MessagingQueueHealthCheck.tsx
  frontend/src/pages/MessagingQueues/MessagingQueues.styles.scss
  frontend/src/pages/MessagingQueues/MessagingQueues.tsx
  frontend/src/pages/MessagingQueues/MessagingQueuesUtils.ts
Labels: enhancement, docs required

#6319 feat: updated the design for Messaging Queue - summary section
  frontend/public/locales/en/messagingQueuesKafkaOverview.json
  frontend/src/constants/query.ts
  frontend/src/pages/MessagingQueues/MQDetailPage/MQDetailPage.tsx
  frontend/src/pages/MessagingQueues/MessagingQueues.styles.scss
  frontend/src/pages/MessagingQueues/MessagingQueues.tsx
  frontend/src/pages/MessagingQueues/MessagingQueuesUtils.ts
Labels: enhancement, docs required

#6392 feat: corrected the handling of relativeTime as null in alertHistory
  frontend/src/pages/AlertDetails/hooks.tsx
Labels: enhancement, docs required

#6378 feat: added support for instrumentation scope in logs
  frontend/src/components/Logs/LogStateIndicator/utils.test.ts
  frontend/src/container/LogDetailedView/utils.tsx
  frontend/src/container/MetricsApplication/constant.ts
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
  frontend/src/container/QueryBuilder/filters/GroupByFilter/utils.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/OptionRenderer.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.styles.scss
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/Suggestions.styles.scss
  frontend/src/container/QueryBuilder/type.ts
  frontend/src/hooks/queryBuilder/useOptions.ts
  frontend/src/types/api/logs/log.ts
Labels: enhancement, docs not required

#6296 fix: adding the key requires double enter before it gets added as label key after the first label
  frontend/src/container/FormAlertRules/labels/index.tsx
Labels: bug, docs not required

#6380 feat: added kafka - scenario - 4 - drop rate table
  frontend/src/pages/MessagingQueues/MQDetailPage/MQDetailPage.tsx
  frontend/src/pages/MessagingQueues/MQDetails/DropRateView/DropRateView.styles.scss
  frontend/src/pages/MessagingQueues/MQDetails/DropRateView/DropRateView.tsx
  frontend/src/pages/MessagingQueues/MQDetails/DropRateView/EvaluationTimeSelector.tsx
  frontend/src/pages/MessagingQueues/MQDetails/DropRateView/dropRateViewUtils.ts
  frontend/src/pages/MessagingQueues/MQDetails/MQDetails.style.scss
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/MQTables.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/getKafkaSpanEval.tsx
Labels: enhancement, docs not required

#6400 feat: styles misc fixes
  frontend/src/pages/MessagingQueues/MQDetails/DropRateView/DropRateView.styles.scss
  frontend/src/pages/MessagingQueues/MQDetails/MQDetails.style.scss
  frontend/src/pages/MessagingQueues/MQDetails/MetricPage/MetricPage.styles.scss
  frontend/src/pages/MessagingQueues/MessagingQueueHealthCheck/MessagingQueueHealthCheck.styles.scss
  frontend/src/pages/MessagingQueues/MessagingQueues.styles.scss
Labels: bug

#6391 fix: test notification missing for anomaly alert
  ee/query-service/app/server.go
  ee/query-service/rules/manager.go
  pkg/query-service/model/response.go
  pkg/query-service/rules/api_params.go
  pkg/query-service/rules/api_params_test.go
  pkg/query-service/rules/db.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/templates.go
  pkg/query-service/rules/templates_test.go
  pkg/query-service/rules/test_notification.go
Labels: bug, docs not required

#6399 feat: added metric page in messaging queues
  frontend/public/locales/en-GB/messagingQueues.json
  frontend/public/locales/en-GB/messagingQueuesKafkaOverview.json
  frontend/public/locales/en/messagingQueues.json
  frontend/public/locales/en/messagingQueuesKafkaOverview.json
  frontend/src/pages/MessagingQueues/MQDetailPage/MQDetailPage.tsx
  frontend/src/pages/MessagingQueues/MQDetails/DropRateView/DropRateView.styles.scss
  frontend/src/pages/MessagingQueues/MQDetails/DropRateView/DropRateView.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MQDetails.style.scss
  frontend/src/pages/MessagingQueues/MQDetails/MQDetails.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MetricPage/MetricColumnGraphs.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MetricPage/MetricPage.styles.scss
  frontend/src/pages/MessagingQueues/MQDetails/MetricPage/MetricPage.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MetricPage/MetricPageGraph.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MetricPage/MetricPageUtil.ts
  frontend/src/pages/MessagingQueues/MessagingQueueHealthCheck/MessagingQueueHealthCheck.styles.scss
  frontend/src/pages/MessagingQueues/MessagingQueues.styles.scss
  frontend/src/pages/MessagingQueues/MessagingQueues.tsx
  frontend/src/pages/MessagingQueues/MessagingQueuesUtils.ts
Labels: enhancement, docs not required

#6410 chore: add k8s job resources
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/infra.go
  pkg/query-service/app/inframetrics/common.go
  pkg/query-service/app/inframetrics/jobs.go
  pkg/query-service/model/infra.go
Labels: chore

#6409 chore: add k8s statefulset resources
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/infra.go
  pkg/query-service/app/inframetrics/common.go
  pkg/query-service/app/inframetrics/jobs.go
  pkg/query-service/app/inframetrics/statefulsets.go
  pkg/query-service/model/infra.go
Labels: chore

#6408 chore: add k8s daemonset resources
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/infra.go
  pkg/query-service/app/inframetrics/common.go
  pkg/query-service/app/inframetrics/daemonsets.go
  pkg/query-service/app/inframetrics/jobs.go
  pkg/query-service/app/inframetrics/statefulsets.go
  pkg/query-service/model/infra.go
Labels: chore

#6286 fix: fix the issue of adding new query in new alert page changing the data source
  frontend/src/container/FormAlertRules/index.tsx
Labels: bug

#6208 feat: alert rename interaction
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/container/CreateAlertRule/defaults.ts
  frontend/src/pages/AlertDetails/AlertHeader/ActionButtons/ActionButtons.tsx
  frontend/src/pages/AlertDetails/AlertHeader/ActionButtons/RenameModal.styles.scss
  frontend/src/pages/AlertDetails/AlertHeader/ActionButtons/RenameModal.tsx
  frontend/src/pages/AlertDetails/AlertHeader/AlertHeader.tsx
  frontend/src/pages/AlertDetails/hooks.tsx
  frontend/src/types/api/alerts/def.ts
Labels: enhancement, docs not required

#6341 feat: consume the new licenses v3 structure.
  ee/query-service/app/api/api.go
  ee/query-service/app/api/license.go
  ee/query-service/app/server.go
  ee/query-service/constants/constants.go
  ee/query-service/integrations/signozio/response.go
  ee/query-service/integrations/signozio/signozio.go
  ee/query-service/license/db.go
  ee/query-service/license/manager.go
  ee/query-service/license/sqlite/init.go
  ee/query-service/main.go
  ee/query-service/model/errors.go
  ee/query-service/model/license.go
  ee/query-service/model/license_test.go
  ee/query-service/model/plans.go
  pkg/query-service/app/http_handler.go
Labels: enhancement, docs not required

#6422 feat: fixProducerAPI
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/integrations/messagingQueues/kafka/translator.go
Labels: bug, enhancement, docs shipped

#6415 fix: add severity_text legend
  frontend/src/container/LogsExplorerViews/index.tsx
Labels: bug, docs not required

#6419 fix: ignore ts for panel type table
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
Labels: bug, docs not required

#6323 fix: update request payload for span metrics queries
  frontend/src/container/MetricsApplication/MetricsPageQueries/DBCallQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/ExternalQueries.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/MetricsPageQueriesFactory.ts
  frontend/src/container/MetricsApplication/MetricsPageQueries/OverviewQueries.ts
  frontend/src/container/MetricsApplication/Tabs/types.ts
  frontend/src/container/MetricsApplication/constant.ts
Labels: bug, docs not required

#6428 chore: return proper http codes on unique constraint error
  ee/query-service/license/db.go
  ee/query-service/license/manager.go
  pkg/query-service/app/http_handler.go
Labels: chore, docs not required

#6432 chore: add experimental rate/increase calc
  pkg/query-service/app/metrics/v4/cumulative/timeseries.go
Labels: chore

#6407 feat: trace V4 QB
  pkg/query-service/app/logs/v4/query_builder.go
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/app/traces/v4/query_builder.go
  pkg/query-service/app/traces/v4/query_builder_test.go
  pkg/query-service/constants/constants.go
Labels: enhancement, docs not required

#6430 feat: ingestion limits - add toggle feature
  frontend/src/container/IngestionSettings/IngestionSettings.styles.scss
  frontend/src/container/IngestionSettings/MultiIngestionSettings.tsx
  frontend/src/types/api/ingestionKeys/limits/types.ts
Labels: enhancement, docs not required, VQA completed

#6359 feat: added logs and traces tab in host metrics detail view
  frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
  frontend/src/components/HostMetricsDetail/Containers.styles.scss
  frontend/src/components/HostMetricsDetail/HostMetricTraces/HostMetricTraces.styles.scss
  frontend/src/components/HostMetricsDetail/HostMetricTraces/HostMetricTraces.tsx
  frontend/src/components/HostMetricsDetail/HostMetricTraces/constants.ts
  frontend/src/components/HostMetricsDetail/HostMetricsDetail.styles.scss
  frontend/src/components/HostMetricsDetail/HostMetricsLogs/HostMetricLogs.styles.scss
  frontend/src/components/HostMetricsDetail/HostMetricsLogs/HostMetricLogsDetailedView.tsx
  frontend/src/components/HostMetricsDetail/HostMetricsLogs/HostMetricsLogs.tsx
  frontend/src/components/HostMetricsDetail/Metrics/Metrics.tsx
  frontend/src/components/HostMetricsDetail/index.tsx
  frontend/src/constants/features.ts
  frontend/src/container/InfraMonitoringHosts/HostsList.tsx
  frontend/src/container/InfraMonitoringHosts/HostsListControls.tsx
  frontend/src/container/InfraMonitoringHosts/InfraMonitoring.styles.scss
  frontend/src/container/InfraMonitoringHosts/index.tsx
  frontend/src/container/InfraMonitoringHosts/utils.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/container/SideNav/menuItems.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
  frontend/src/pages/InfraMonitoringHosts/InfraMonitoring.styles.scss
  frontend/src/pages/InfrastructureMonitoring/InfrastructureMonitoring.styles.scss
  frontend/src/pages/InfrastructureMonitoring/constants.tsx
  frontend/src/providers/QueryBuilder.tsx
Labels: enhancement

#6451 fix: show org onboarding only to cloud customers
  frontend/src/AppRoutes/Private.tsx
Labels: bug

#6448 feat: removed dashboard uuid is all cases be it duplicate, empty or somevalid, while import json
  frontend/src/container/ListOfDashboard/ImportJSON/index.tsx
Labels: enhancement, docs not required

#6453 fix: update struct to fix live logs
  pkg/query-service/model/response.go
Labels: bug

#6438 feat: support for new enrichment logic in traces
  pkg/query-service/app/logs/v3/enrich_query.go
  pkg/query-service/app/traces/v4/enrich.go
  pkg/query-service/app/traces/v4/enrich_test.go
  pkg/query-service/app/traces/v4/query_builder_test.go
  pkg/query-service/constants/constants.go
  pkg/query-service/contextlinks/links.go
  pkg/query-service/utils/logs.go
  pkg/query-service/utils/logs_test.go
Labels: enhancement, docs not required

#6458 fix: compare op outside bounds for anomaly alert
  ee/query-service/rules/anomaly.go
  frontend/src/container/FormAlertRules/RuleOptions.tsx
  pkg/query-service/rules/base_rule.go
Labels: bug

#6461 chore: add user email to log_comment
  pkg/query-service/app/server.go
Labels: chore

#6459 chore: add missing alert telemetry
  pkg/query-service/telemetry/telemetry.go
Labels: chore, docs not required

#6464 fix: remove unwanted trace API's
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/interfaces/interface.go
Labels: bug

#6468 chore: use the license v2 key to fill licenses v3 on startup
  ee/query-service/license/manager.go
Labels: enhancement, chore, docs not required

#6470 fix: update TestListTsRange to return all range
  pkg/query-service/utils/logs.go
  pkg/query-service/utils/logs_test.go
Labels: bug

#6460 fix: incorrect formula for apdex
  frontend/src/container/MetricsApplication/constant.ts
Labels: bug, docs not required

#6475 chore: set `ZEUS_URL` via build time variable
  Makefile
  ee/query-service/constants/constants.go
Labels: chore

#6469 Trace static fields and structs for response.
  pkg/query-service/constants/constants.go
  pkg/query-service/model/trace.go
Labels: docs not required

#6480 feat(key): enable edit access for gateway
  ee/query-service/app/api/api.go
Labels: enhancement

#6481 chore: exactly match the list licenses v2 structure with FF on
  ee/query-service/app/api/license.go
  ee/query-service/license/manager.go
  ee/query-service/model/plans.go
Labels: chore

#6486 chore: update http proxy middleware
  frontend/package.json
  frontend/src/setupProxy.js
  frontend/yarn.lock
Labels: chore

#6495 fix: remove service overview API
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/parser.go
  pkg/query-service/interfaces/interface.go
Labels: bug

#6479 feat: update clickhouse reader to support new trace schema
  pkg/query-service/app/clickhouseReader/options.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/constants/constants.go
  pkg/query-service/model/trace.go
Labels: enhancement, docs not required

#6497 feat: ttl api for new trace tables
  pkg/query-service/app/clickhouseReader/reader.go
Labels: enhancement, docs not required

#6226 feat: trace v4 integration
  ee/query-service/app/api/api.go
  ee/query-service/app/api/traces.go
  ee/query-service/app/db/reader.go
  ee/query-service/app/server.go
  ee/query-service/main.go
  ee/query-service/rules/manager.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/querier/helper.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/querier/v2/helper.go
  pkg/query-service/app/querier/v2/querier.go
  pkg/query-service/app/querier/v2/querier_test.go
  pkg/query-service/app/server.go
  pkg/query-service/main.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/test_notification.go
  pkg/query-service/rules/threshold_rule.go
  pkg/query-service/rules/threshold_rule_test.go
  pkg/query-service/tests/integration/test_utils.go
Labels: enhancement, docs not required

#6496 fix: fixed back navigation issue for dashboard details coming from dashboard list table
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
Labels: bug, docs not required

#6488 fix: updated folder name and structure
  frontend/src/container/OnboardingContainer/Steps/ConnectionStatus/ConnectionStatus.tsx
  frontend/src/hooks/messagingQueue/useOnboardingStatus.tsx
  frontend/src/pages/MessagingQueues/MessagingQueueHealthCheck/MessagingQueueHealthCheck.tsx
Labels: bug, docs not required

#6502 chore: enable sorting for hosts list
  ee/query-service/app/server.go
  frontend/src/container/InfraMonitoringHosts/utils.tsx
  pkg/query-service/app/inframetrics/hosts.go
  pkg/query-service/app/server.go
  pkg/query-service/model/infra.go
Labels: chore, docs not required

#6505 chore: remove the fancy text while fetching data
  frontend/public/locales/en/common.json
  frontend/src/pages/LogsExplorer/__tests__/LogsExplorer.test.tsx
Labels: chore, docs not required

#6499 chore: update http proxy middleware
  frontend/package.json
  frontend/yarn.lock
Labels: chore, docs not required

#6516 fix: add v2 for getServices and GetTopOperations
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/constants/constants.go
  pkg/query-service/utils/format.go
Labels: bug

#6517 fix: add settings to allow distributed_product_mode for trace panel
  pkg/query-service/app/traces/v3/query_builder_test.go
  pkg/query-service/app/traces/v4/query_builder.go
  pkg/query-service/app/traces/v4/query_builder_test.go
  pkg/query-service/constants/constants.go
Labels: bug

#6526 fix: update api's to repect the new changes in attributes table
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/logs/v3/enrich_query.go
  pkg/query-service/constants/constants.go
Labels: bug

#6529 chore: add additional info for host metrics onboarding
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/inframetrics/hosts.go
  pkg/query-service/constants/constants.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/infra.go
Labels: chore

#6527 chore: move away from parallel usages of licenses v2 and v3
  ee/query-service/app/api/license.go
  ee/query-service/license/db.go
  ee/query-service/license/manager.go
  ee/query-service/model/license.go
Labels: chore, docs not required

#6522 fix: open the timepicker on clicking the time picker input after closing the timezone picker by clicking outside it
  frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
Labels: bug

#6521 feat: display timezone adjusted time range in time picker
  frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
  frontend/src/components/CustomTimePicker/RangePickerModal.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
Labels: enhancement

#6536 feat: add infra monitoring - host lists - usage events
  frontend/public/locales/en-GB/infraMonitoring.json
  frontend/public/locales/en/infraMonitoring.json
  frontend/src/components/HostMetricsDetail/Containers/Containers.styles.scss
  frontend/src/components/HostMetricsDetail/Containers/Containers.tsx
  frontend/src/components/HostMetricsDetail/HostMetricsDetails.tsx
  frontend/src/components/HostMetricsDetail/Processes/Processes.styles.scss
  frontend/src/components/HostMetricsDetail/Processes/Processes.tsx
  frontend/src/components/HostMetricsDetail/WaitlistFragment/WaitListFragment.styles.scss
  frontend/src/components/HostMetricsDetail/WaitlistFragment/WaitlistFragment.tsx
  frontend/src/container/InfraMonitoringHosts/HostsList.tsx
  frontend/src/container/SideNav/menuItems.tsx
Labels: enhancement

#6489 Fix for running signoz-schema-migrator under docker-swarm
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
Labels: docs not required

#6530 feat: improve empty hosts, incorrect metrics and no filter views
  frontend/public/locales/en-GB/infraMonitoring.json
  frontend/public/locales/en/infraMonitoring.json
  frontend/src/api/infraMonitoring/getHostLists.ts
  frontend/src/components/HostMetricsDetail/Containers/Containers.styles.scss
  frontend/src/components/HostMetricsDetail/Containers/Containers.tsx
  frontend/src/components/HostMetricsDetail/HostMetricsDetails.tsx
  frontend/src/components/HostMetricsDetail/Processes/Processes.styles.scss
  frontend/src/components/HostMetricsDetail/Processes/Processes.tsx
  frontend/src/components/HostMetricsDetail/WaitlistFragment/WaitListFragment.styles.scss
  frontend/src/components/HostMetricsDetail/WaitlistFragment/WaitlistFragment.tsx
  frontend/src/container/InfraMonitoringHosts/HostsEmptyOrIncorrectMetrics.tsx
  frontend/src/container/InfraMonitoringHosts/HostsList.tsx
  frontend/src/container/InfraMonitoringHosts/InfraMonitoring.styles.scss
  frontend/src/container/SideNav/NavItem/NavItem.tsx
  frontend/src/container/SideNav/SideNav.styles.scss
  frontend/src/container/SideNav/menuItems.tsx
  frontend/src/container/SideNav/sideNav.types.ts
Labels: enhancement, docs not required

#6548 feat: handle keyboard navigations for column selection in logs explor…
  frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.styles.scss
  frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.tsx
Labels: enhancement, docs not required

#6549 fix: explicit mouse move event user action
  frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.tsx
Labels: bug, docs not required

#6553 fix: add dashbard names and update logs count in telemetry
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/model/response.go
  pkg/query-service/telemetry/telemetry.go
Labels: bug

#6557 fix: fixed typo in metric view dashboard title
  frontend/src/pages/MessagingQueues/MQDetails/MetricPage/MetricPageUtil.ts
Labels: bug
