Repository SigNoz/signoz, pull requests merged in 2024-12, with the labels that each got.

#6523 fix: make x axis and tooltip time format consistent in uPlot graphs
  frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
Labels: bug

#6571 chore: remove infra monitoring ff
  frontend/src/AppRoutes/index.tsx
  frontend/src/constants/features.ts
  frontend/src/container/SideNav/SideNav.tsx
Labels: chore

#6560 feat: show failed payment banner and block the workspace integration
  ee/query-service/app/api/api.go
  ee/query-service/app/api/license.go
  frontend/public/Images/feature-graphic-correlation.svg
  frontend/public/locales/en-GB/failedPayment.json
  frontend/public/locales/en-GB/titles.json
  frontend/public/locales/en/failedPayment.json
  frontend/public/locales/en/titles.json
  frontend/src/AppRoutes/Private.tsx
  frontend/src/AppRoutes/index.tsx
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/api/licensesV3/getActive.ts
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/constants/routes.ts
  frontend/src/container/AppLayout/AppLayout.styles.scss
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/TopNav/Breadcrumbs/index.tsx
  frontend/src/container/TopNav/DateTimeSelection/config.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/hooks/useActiveLicenseV3/useActiveLicenseV3.tsx
  frontend/src/pages/WorkspaceSuspended/WorkspaceSuspended.styles.scss
  frontend/src/pages/WorkspaceSuspended/WorkspaceSuspended.tsx
  frontend/src/providers/App/App.tsx
  frontend/src/types/api/licensesV3/getActive.ts
  frontend/src/utils/permission/index.ts
  frontend/src/utils/timeUtils.ts
Labels: enhancement, docs not required

#6574 chore: make the entire row clickable in logs quick filters
  frontend/src/components/QuickFilters/FilterRenderers/Checkbox/Checkbox.styles.scss
  frontend/src/components/QuickFilters/FilterRenderers/Checkbox/Checkbox.tsx
Labels: chore, docs not required

#6570 feat: add timezone support to ingestion settings list page and alerts page when groupe filter is applied
  frontend/src/container/IngestionSettings/MultiIngestionSettings.tsx
  frontend/src/container/TriggeredAlerts/FilteredTable/ExapandableRow.tsx
Labels: enhancement

#6566 feat: add timezone support to logs explorer chart (built with Chartjs)
  frontend/src/components/Graph/index.tsx
  frontend/src/components/Graph/utils.ts
  frontend/src/hooks/useTimezoneFormatter/useTimezoneFormatter.ts
Labels: enhancement

#6565 feat: apply timezone to the date/time in tabular data throughout the app
  frontend/src/components/Graph/index.tsx
  frontend/src/components/Graph/utils.ts
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/TableView/useTableView.tsx
  frontend/src/components/ResizeTable/TableComponent/Time.tsx
  frontend/src/container/AlertHistory/Timeline/Table/Table.tsx
  frontend/src/container/AlertHistory/Timeline/Table/useTimelineTable.tsx
  frontend/src/container/AllError/index.tsx
  frontend/src/container/ErrorDetails/index.tsx
  frontend/src/container/IngestionSettings/MultiIngestionSettings.tsx
  frontend/src/container/Licenses/ListLicenses.tsx
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/LogDetailedView/TableView/TableViewActions.tsx
  frontend/src/container/LogsPanelTable/LogsPanelComponent.tsx
  frontend/src/container/LogsPanelTable/utils.tsx
  frontend/src/container/PipelinePage/Layouts/ChangeHistory/DeploymentTime.tsx
  frontend/src/container/PipelinePage/PipelineListsView/Preview/components/LogsList/index.tsx
  frontend/src/container/PipelinePage/PipelineListsView/TableComponents/index.tsx
  frontend/src/container/TracesExplorer/ListView/index.tsx
  frontend/src/container/TracesExplorer/ListView/utils.tsx
  frontend/src/container/TracesTableComponent/TracesTableComponent.tsx
  frontend/src/container/TriggeredAlerts/FilteredTable/ExapandableRow.tsx
  frontend/src/container/TriggeredAlerts/NoFilterTable.tsx
  frontend/src/hooks/useTimezoneFormatter/useTimezoneFormatter.ts
  frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
  frontend/src/pages/SaveView/index.tsx
  frontend/src/providers/Timezone.tsx
Labels: enhancement

#6520 feat: add timezone support to the graphs throughout the app
  frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
  frontend/src/components/CustomTimePicker/RangePickerModal.tsx
  frontend/src/components/Graph/index.tsx
  frontend/src/components/Graph/utils.ts
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/TableView/useTableView.tsx
  frontend/src/components/ResizeTable/TableComponent/Time.tsx
  frontend/src/container/AlertHistory/Timeline/Graph/Graph.tsx
  frontend/src/container/AlertHistory/Timeline/Table/Table.tsx
  frontend/src/container/AlertHistory/Timeline/Table/useTimelineTable.tsx
  frontend/src/container/AllError/index.tsx
  frontend/src/container/AnomalyAlertEvaluationView/AnomalyAlertEvaluationView.tsx
  frontend/src/container/AnomalyAlertEvaluationView/tooltipPlugin.ts
  frontend/src/container/ErrorDetails/index.tsx
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/GantChart/Span/index.tsx
  frontend/src/container/IngestionSettings/MultiIngestionSettings.tsx
  frontend/src/container/Licenses/ListLicenses.tsx
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/LogDetailedView/InfraMetrics/NodeMetrics.tsx
  frontend/src/container/LogDetailedView/InfraMetrics/PodMetrics.tsx
  frontend/src/container/LogDetailedView/TableView/TableViewActions.tsx
  frontend/src/container/LogsPanelTable/LogsPanelComponent.tsx
  frontend/src/container/LogsPanelTable/utils.tsx
  frontend/src/container/PanelWrapper/UplotPanelWrapper.tsx
  frontend/src/container/PipelinePage/Layouts/ChangeHistory/DeploymentTime.tsx
  frontend/src/container/PipelinePage/PipelineListsView/Preview/components/LogsList/index.tsx
  frontend/src/container/PipelinePage/PipelineListsView/TableComponents/index.tsx
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/container/TracesExplorer/ListView/index.tsx
  frontend/src/container/TracesExplorer/ListView/utils.tsx
  frontend/src/container/TracesTableComponent/TracesTableComponent.tsx
  frontend/src/container/TriggeredAlerts/FilteredTable/ExapandableRow.tsx
  frontend/src/container/TriggeredAlerts/NoFilterTable.tsx
  frontend/src/hooks/useTimezoneFormatter/useTimezoneFormatter.ts
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
  frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
  frontend/src/pages/SaveView/index.tsx
  frontend/src/providers/Timezone.tsx
Labels: enhancement

#6596 fix: enable smart trace detail
  ee/query-service/app/api/traces.go
Labels: bug

#6564 fix(docker): otel-collector-migrator command fixed in docker-compose-core.yml
  deploy/docker/clickhouse-setup/docker-compose-core.yaml
Labels: docs not required

#6583 chore: replace the 'Get started' CTA with 'New source'
  frontend/src/container/SideNav/SideNav.tsx
Labels: chore

#6603 fix: resolve unnecessary refetching of graphs on service details page
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ServiceOverview.tsx
Labels: bug, docs not required

#6602 fix: smartTraceAlgo for new schema
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug, docs not required

#6552 fix: update default alert ch queries for traces and logs
  frontend/src/container/CreateAlertRule/defaults.ts
Labels: bug, docs not required

#6610 fix: migration for ingestion dashboard
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/migrate/ingestion_dashboard.go
  pkg/query-service/migrate/migate.go
Labels: bug

#6613 fix: fix count aggregate attribute column name
  pkg/query-service/app/traces/v4/query_builder.go
  pkg/query-service/app/traces/v4/query_builder_test.go
  pkg/query-service/rules/threshold_rule.go
Labels: bug

#6433 feat: added table column and row logic for the new api response structure for producer overview
  frontend/src/api/messagingQueues/getTopicThroughputOverview.ts
  frontend/src/pages/MessagingQueues/MQDetails/MQDetails.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/MQTableUtils.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/MQTables.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MessagingQueueOverview.tsx
Labels: enhancement, docs not required

#6595 feat: add functionality to export dashboard as json from listing page
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/pages/DashboardsListPage/__tests__/DashboardListPage.test.tsx
Labels: enhancement, docs shipped

#6423 fix: improve traces table ux by making the table scrollable
  frontend/src/container/TracesExplorer/ListView/index.tsx
  frontend/src/pages/TracesExplorer/TracesExplorer.styles.scss
  frontend/src/pages/TracesExplorer/index.tsx
Labels: bug, docs not required

#6643 chore: add queries with tag attributes v1
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/model/response.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore, docs not required

#6616 chore: use tag attributes v2 table
  pkg/query-service/app/clickhouseReader/filter_suggestions.go
  pkg/query-service/app/clickhouseReader/options.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/tests/integration/filter_suggestions_test.go
Labels: chore, docs not required

#6645 fix: unable to remove query tags from the beginning when similar tags present
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
Labels: bug, docs not required

#6634 fix: time range from traces to logs
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
Labels: bug, docs not required

#6632 fix: correlation time stamps for APM to traces and logs
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/Tabs/util.ts
Labels: bug, docs not required

#6647 fix(flag): add missing flag back
  ee/query-service/main.go
Labels: bug, docs not required

#6609 feat: added API limiting to reduce unnecessary api call for dashboard variables
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/util.ts
Labels: enhancement, docs required

#6621 feat: add jest test cases for new logic's utils, functions and processors - dashboardVariables
  frontend/src/container/NewDashboard/DashboardVariablesSelection/__test__/dashboardVariables.test.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/__test__/mock.ts
  frontend/src/container/NewDashboard/DashboardVariablesSelection/util.ts
Labels: enhancement, docs required

#6651 fix: add flags for using trace new schema
  deploy/docker-swarm/clickhouse-setup/docker-compose.yaml
  deploy/docker-swarm/clickhouse-setup/otel-collector-config.yaml
  deploy/docker/clickhouse-setup/docker-compose-local.yaml
  deploy/docker/clickhouse-setup/docker-compose-minimal.yaml
  deploy/docker/clickhouse-setup/docker-compose.testing.yaml
  deploy/docker/clickhouse-setup/otel-collector-config.yaml
Labels: bug, docs not required

#6667 fix: use placehold in limit and use proper exists
  pkg/query-service/app/querier/helper.go
  pkg/query-service/app/querier/v2/helper.go
  pkg/query-service/app/traces/v4/enrich.go
  pkg/query-service/app/traces/v4/query_builder.go
  pkg/query-service/app/traces/v4/query_builder_test.go
Labels: bug, docs not required

#6669 Add bucketing for messaging queues
  pkg/query-service/app/integrations/messagingQueues/kafka/sql.go
Labels: request-more-info, docs not required

#6646 feat: api for trace materialization
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/logs/parser.go
  pkg/query-service/app/logs/parser_test.go
  pkg/query-service/app/logs/validator.go
  pkg/query-service/constants/constants.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/response.go
Labels: enhancement, docs not required

#6605 feat: changed start and end time logic for consumer lag details
  frontend/src/pages/MessagingQueues/MQDetails/MQDetails.tsx
  frontend/src/pages/MessagingQueues/MessagingQueuesUtils.ts
Labels: enhancement, docs not required

#6668 chore: develop deprecation and related changes
  .github/workflows/build.yaml
  .github/workflows/docs.yml
  .github/workflows/e2e-k3s.yaml
  .github/workflows/jest-coverage-changes.yml
  .github/workflows/push.yaml
  .github/workflows/sonar.yml
  .github/workflows/staging-deployment.yaml
  .github/workflows/testing-deployment.yaml
  CONTRIBUTING.md
  deploy/README.md
  frontend/.husky/commit-msg
  frontend/src/pages/MessagingQueues/MQDetails/MQDetails.tsx
  frontend/src/pages/MessagingQueues/MessagingQueuesUtils.ts
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/integrations/messagingQueues/kafka/sql.go
  pkg/query-service/app/logs/parser.go
  pkg/query-service/app/logs/parser_test.go
  pkg/query-service/app/logs/validator.go
  pkg/query-service/app/querier/helper.go
  pkg/query-service/app/querier/v2/helper.go
  pkg/query-service/app/traces/v4/enrich.go
  pkg/query-service/app/traces/v4/query_builder.go
  pkg/query-service/app/traces/v4/query_builder_test.go
  pkg/query-service/constants/constants.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/response.go
  sample-apps/hotrod/README.md
  sample-apps/hotrod/hotrod-delete.sh
  sample-apps/hotrod/hotrod-install.sh
Labels: chore

#6654 chore: add pvcs list
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/infra.go
  pkg/query-service/app/inframetrics/common.go
  pkg/query-service/app/inframetrics/pvcs.go
  pkg/query-service/app/inframetrics/pvcs_query.go
  pkg/query-service/model/infra.go
Labels: chore

#6683 chore: remove data migration
  pkg/query-service/migrate/ingestion_dashboard.go
  pkg/query-service/migrate/migate.go
Labels: chore, docs not required

#6676 chore: add log events for timezone interactions in date/time picker and timezone adaptation
  frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
  frontend/src/components/CustomTimePicker/CustomTimePickerPopoverContent.tsx
  frontend/src/components/CustomTimePicker/TimezonePicker.tsx
  frontend/src/container/MySettings/TimezoneAdaptation/TimezoneAdaptation.tsx
Labels: chore

#6681 fix: detach the log indicator from timestamp column
  frontend/src/components/Logs/TableView/useTableView.styles.scss
  frontend/src/components/Logs/TableView/useTableView.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/TableRow.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/styles.ts
Labels: bug

#6675 fix: fix the mismatch between time range picker placeholder and timerange popover values
  frontend/src/components/CustomTimePicker/RangePickerModal.tsx
Labels: bug

#6686 fix: route permissions for billing and alerts
  frontend/src/utils/permission/index.ts
Labels: bug

#6687 feat: rename access tokens to api keys
  frontend/public/locales/en-GB/routes.json
  frontend/public/locales/en-GB/titles.json
  frontend/public/locales/en/apiKeys.json
  frontend/public/locales/en/routes.json
  frontend/public/locales/en/titles.json
  frontend/src/AppRoutes/routes.ts
  frontend/src/constants/routes.ts
  frontend/src/container/APIKeys/APIKeys.test.tsx
  frontend/src/container/APIKeys/APIKeys.tsx
  frontend/src/mocks-server/__mockdata__/apiKeys.ts
Labels: enhancement, update docs on SigNoz.io, docs shipped

#6688 fix: add support route to the base route for private routes
  frontend/src/AppRoutes/Private.tsx
  frontend/src/AppRoutes/routes.ts
Labels: bug

#6692 fix: do not try to route to org onboarding when workspace locked or suspended
  frontend/src/AppRoutes/Private.tsx
  frontend/src/AppRoutes/routes.ts
  frontend/src/providers/App/App.tsx
Labels: bug

#6694 feat: add k8s pod name as quick filter for logs
  frontend/src/pages/LogsExplorer/utils.tsx
Labels: enhancement, docs shipped

#6696 feat(ee): serve frontend pages with query-service
  .github/workflows/push.yaml
  Makefile
  conf/defaults.yaml
  ee/query-service/Dockerfile
  ee/query-service/app/server.go
  ee/query-service/main.go
  pkg/config/config.go
  pkg/config/unmarshaler.go
  pkg/config/unmarshaler_test.go
Labels: enhancement

#6641 feat: implement node details page
  frontend/src/container/InfraMonitoringK8s/Nodes/K8sNodesList.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Events/NoEventsContainer.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Events/NodeEvents.styles.scss
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Events/NodeEvents.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Events/constants.ts
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Events/index.ts
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Logs/NoLogsContainer.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Logs/NodeLogs.styles.scss
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Logs/NodeLogs.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Logs/NodeLogsDetailedView.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Logs/constants.ts
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Logs/index.ts
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Metrics/NodeMetrics.styles.scss
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Metrics/NodeMetrics.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Metrics/constants.ts
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Metrics/index.ts
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/NodeDetails.interfaces.ts
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/NodeDetails.styles.scss
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/NodeDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Traces/NodeTraces.styles.scss
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Traces/NodeTraces.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Traces/constants.ts
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Traces/index.ts
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Traces/utils.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/constants.ts
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/index.ts
  frontend/src/container/InfraMonitoringK8s/utils.tsx
Labels: enhancement

#6709 chore: fix cross spawn vulnerability
  frontend/package.json
  frontend/yarn.lock
Labels: bug, chore

#6677 fix(Traces Explorer): prevent duplicate API calls to query_range in traces explorer
  frontend/src/container/TracesExplorer/ListView/index.tsx
  frontend/src/pages/TracesExplorer/Filter/Filter.tsx
  frontend/src/pages/TracesExplorer/__test__/TracesExplorer.test.tsx
  frontend/src/providers/QueryBuilder.tsx
Labels: bug

#6678 fix: fix the issue of saved view overriding query for logs and traces
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/pages/LogsExplorer/__tests__/LogsExplorer.test.tsx
  frontend/src/pages/TracesExplorer/__test__/testUtils.ts
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/types/common/queryBuilder.ts
Labels: bug

#6717 fix: update API key expiration display logic in MultiIngestionSettings component
  frontend/src/container/IngestionSettings/MultiIngestionSettings.tsx
Labels: bug

#6693 chore: changed droprate view options values
  frontend/src/pages/MessagingQueues/MQDetails/DropRateView/EvaluationTimeSelector.tsx
Labels: chore, docs not required

#6611 chore: restructure Kafka codebase
  frontend/src/api/messagingQueues/getConsumerLagDetails.ts
  frontend/src/api/messagingQueues/getKafkaSpanEval.tsx
  frontend/src/api/messagingQueues/getPartitionLatencyDetails.ts
  frontend/src/api/messagingQueues/getPartitionLatencyOverview.ts
  frontend/src/api/messagingQueues/getTopicThroughputDetails.ts
  frontend/src/api/messagingQueues/getTopicThroughputOverview.ts
  frontend/src/components/MessagingQueueHealthCheck/AttributeCheckList.tsx
  frontend/src/components/MessagingQueueHealthCheck/MessagingQueueHealthCheck.styles.scss
  frontend/src/components/MessagingQueueHealthCheck/MessagingQueueHealthCheck.tsx
  frontend/src/components/MessagingQueues/MQCommon/MQCommon.styles.scss
  frontend/src/components/MessagingQueues/MQCommon/MQCommon.tsx
  frontend/src/container/OnboardingContainer/Steps/ConnectionStatus/ConnectionStatus.tsx
  frontend/src/pages/MessagingQueues/MQDetails/DropRateView/DropRateView.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/MQTableUtils.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/MQTables.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MessagingQueueOverview.tsx
  frontend/src/pages/MessagingQueues/MQGraph/MQConfigOptions.tsx
  frontend/src/pages/MessagingQueues/MessagingQueues.tsx
  frontend/src/pages/MessagingQueues/MessagingQueuesUtils.ts
Labels: chore

#6729 feat(releaser): update releaser workflow based on new enhancements
  .github/workflows/releaser-signoz.yaml
  .github/workflows/releaser.yaml
Labels: enhancement

#6720 fix: removed caching for all other panel type for expression except time series
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
Labels: bug, docs not required

#6735 fix(ci): fix jest coverage since github workflow
  frontend/package.json
Labels: bug
