Repository SigNoz/signoz, pull requests merged in 2025-03, with the labels that each got.

#7177 fix: fixed view trace or logs button on graph not disappearing on outside click
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskLatencyGraph.tsx
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/Tabs/util.ts
  frontend/src/hooks/useClickOutside.tsx
  frontend/src/pages/Celery/CeleryOverview/CeleryOverviewDetail/OverviewRightPanelGraph.tsx
Labels: bug

#7182 chore: bump github.com/SigNoz/prometheus
  go.mod
  go.sum
  pkg/query-service/app/metrics/v3/cumulative_table_test.go
  pkg/query-service/app/metrics/v3/delta_table_test.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/app/metrics/v4/cumulative/table_test.go
  pkg/query-service/app/metrics/v4/cumulative/timeseries_test.go
  pkg/query-service/app/metrics/v4/delta/table_test.go
  pkg/query-service/app/metrics/v4/delta/time_series_test.go
  pkg/query-service/app/metrics/v4/helpers/sub_query.go
  pkg/query-service/app/metrics/v4/query_builder_pre_agg_test.go
  pkg/query-service/app/metrics/v4/query_builder_test.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
Labels: chore

#7198 chore: upgraded path-to-regexp
  frontend/package.json
  frontend/yarn.lock
Labels: chore

#7143 feat: add default interval of 30s when the user enables auto refresh
  frontend/src/container/TopNav/AutoRefreshV2/index.tsx
Labels: enhancement, docs required

#7217 feat(alertmanager): simplify and test e2e alertmanager
  .gitignore
  go.mod
  go.sum
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanagerbatcher/batcher.go
  pkg/alertmanager/alertmanagerbatcher/batcher_test.go
  pkg/alertmanager/alertmanagerbatcher/config.go
  pkg/alertmanager/alertmanagerserver/server.go
  pkg/alertmanager/alertmanagerserver/server_test.go
  pkg/alertmanager/alertmanagerstore/sqlalertmanagerstore/config.go
  pkg/alertmanager/api.go
  pkg/alertmanager/config.go
  pkg/alertmanager/config_test.go
  pkg/alertmanager/legacyalertmanager/provider.go
  pkg/alertmanager/service.go
  pkg/alertmanager/signozalertmanager/provider.go
  pkg/sqlmigrator/migrator.go
  pkg/types/alertmanagertypes/alert.go
  pkg/types/alertmanagertypes/channel.go
  pkg/types/alertmanagertypes/channel_test.go
  pkg/types/alertmanagertypes/config.go
  pkg/types/alertmanagertypes/config_test.go
  pkg/types/alertmanagertypes/receiver.go
Labels: enhancement, docs not required

#7142 feat: logs explorer context log line redirection
  frontend/src/container/LogDetailedView/ContextView/ContextLogRenderer.styles.scss
  frontend/src/container/LogDetailedView/ContextView/ContextLogRenderer.tsx
Labels: enhancement, docs required

#7215 fix: added safety checks for buildgraph functions and revert upgrades
  frontend/package.json
  frontend/src/container/NewDashboard/DashboardVariablesSelection/util.ts
Labels: bug

#7200 feat: implement metrics explorer summary section
  frontend/package.json
  frontend/src/api/metricsExplorer/getMetricsList.ts
  frontend/src/api/metricsExplorer/getMetricsListFilterKeys.ts
  frontend/src/api/metricsExplorer/getMetricsListFilterValues.ts
  frontend/src/api/metricsExplorer/getMetricsTreeMap.ts
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/container/MetricsExplorer/Summary/MetricsSearch.tsx
  frontend/src/container/MetricsExplorer/Summary/MetricsTable.tsx
  frontend/src/container/MetricsExplorer/Summary/MetricsTreemap.tsx
  frontend/src/container/MetricsExplorer/Summary/Summary.styles.scss
  frontend/src/container/MetricsExplorer/Summary/Summary.tsx
  frontend/src/container/MetricsExplorer/Summary/constants.ts
  frontend/src/container/MetricsExplorer/Summary/types.ts
  frontend/src/container/MetricsExplorer/Summary/utils.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/hooks/metricsExplorer/useGetMetricsList.ts
  frontend/src/hooks/metricsExplorer/useGetMetricsListFilterKeys.ts
  frontend/src/hooks/metricsExplorer/useGetMetricsTreeMap.ts
  frontend/src/hooks/queryBuilder/useAutoComplete.ts
  frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
  frontend/yarn.lock
Labels: enhancement, docs not required

#7224 feat(sqlstore): add transaction support for sqlstore
  pkg/alertmanager/alertmanagerserver/server.go
  pkg/alertmanager/alertmanagerstore/sqlalertmanagerstore/config.go
  pkg/alertmanager/legacyalertmanager/provider.go
  pkg/alertmanager/signozalertmanager/provider.go
  pkg/sqlstore/bun.go
  pkg/sqlstore/postgressqlstore/provider.go
  pkg/sqlstore/sqlitesqlstore/provider.go
  pkg/sqlstore/sqlstore.go
  pkg/sqlstore/sqlstoretest/provider.go
  pkg/types/alertmanagertypes/config.go
  pkg/types/alertmanagertypes/receiver.go
Labels: enhancement, docs not required

#7201 fix: new implementation for finding missing timerange
  pkg/query-service/interfaces/interface.go
  pkg/query-service/querycache/query_range_cache.go
  pkg/query-service/querycache/query_range_cache_test.go
Labels: bug

#7162 chore: use platform property to evaluate type of user, update all references
  frontend/src/AppRoutes/Private.tsx
  frontend/src/AppRoutes/index.tsx
  frontend/src/components/LaunchChatSupport/LaunchChatSupport.tsx
  frontend/src/components/MessagingQueueHealthCheck/AttributeCheckList.tsx
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/BillingContainer/BillingContainer.tsx
  frontend/src/container/GeneralSettings/GeneralSettings.tsx
  frontend/src/container/GeneralSettings/Retention.tsx
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/LogsError/LogsError.tsx
  frontend/src/container/NoLogs/NoLogs.tsx
  frontend/src/container/ServiceApplication/ServiceMetrics/ServiceMetricTable.tsx
  frontend/src/container/ServiceApplication/ServiceTraces/ServiceTracesTable.tsx
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/hooks/useGetTenantLicense.ts
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailPage.tsx
  frontend/src/pages/Integrations/IntegrationsList.tsx
  frontend/src/pages/MessagingQueues/MessagingQueues.tsx
  frontend/src/pages/Settings/index.tsx
  frontend/src/pages/Settings/utils.ts
  frontend/src/pages/TraceDetailV2/NoData/NoData.tsx
  frontend/src/tests/test-utils.tsx
  frontend/src/types/api/licensesV3/getActive.ts
  frontend/src/utils/app.ts
Labels: chore, docs not required, tech-debt

#7226 fix: update bearer to capital case and handle undefined
  frontend/src/api/channels/createWebhook.ts
  frontend/src/api/channels/editWebhook.ts
  frontend/src/api/channels/testWebhook.ts
Labels: bug

#7175 fix(logs): centralize time range handling in DateTimeSelectionV2
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/hooks/logs/types.ts
  frontend/src/hooks/logs/useCopyLogLink.ts
  frontend/src/hooks/useLogsData.ts
Labels: bug

#7155 Fix: Multitenancy support for ORG
  ee/query-service/app/api/cloudIntegrations.go
  ee/query-service/app/api/pat.go
  ee/query-service/app/server.go
  ee/query-service/auth/auth.go
  ee/query-service/dao/interface.go
  ee/query-service/dao/sqlite/auth.go
  ee/query-service/dao/sqlite/pat.go
  ee/query-service/model/domain.go
  frontend/src/api/user/setFlags.ts
  frontend/src/components/ReleaseNote/ReleaseNoteProps.ts
  frontend/src/components/ReleaseNote/Releases/ReleaseNote0120.tsx
  frontend/src/components/ReleaseNote/index.tsx
  frontend/src/container/ListAlertRules/index.tsx
  frontend/src/container/OrganizationSettings/Members/index.tsx
  frontend/src/pages/DashboardsListPage/DashboardsListPage.tsx
  frontend/src/pages/Services/index.tsx
  frontend/src/providers/App/App.tsx
  frontend/src/providers/App/types.ts
  frontend/src/providers/App/utils.ts
  frontend/src/tests/test-utils.tsx
  frontend/src/types/api/user/getUser.ts
  frontend/src/types/api/user/setFlags.ts
  pkg/query-service/app/apdex.go
  pkg/query-service/app/auth.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/server.go
  pkg/query-service/auth/auth.go
  pkg/query-service/auth/rbac.go
  pkg/query-service/common/user.go
  pkg/query-service/dao/interface.go
  pkg/query-service/dao/sqlite/apdex.go
  pkg/query-service/dao/sqlite/connection.go
  pkg/query-service/dao/sqlite/rbac.go
  pkg/query-service/model/auth.go
  pkg/query-service/model/db.go
  pkg/query-service/telemetry/telemetry.go
  pkg/query-service/tests/integration/filter_suggestions_test.go
  pkg/query-service/tests/integration/logparsingpipeline_test.go
  pkg/query-service/tests/integration/signoz_cloud_integrations_test.go
  pkg/query-service/tests/integration/signoz_integrations_test.go
  pkg/query-service/tests/integration/test_utils.go
  pkg/query-service/utils/testutils.go
  pkg/signoz/signoz.go
  pkg/sqlmigration/009_add_pats.go
  pkg/sqlmigration/012_modify_org_domain.go
  pkg/sqlmigration/013_update_organization.go
  pkg/sqlmigration/sqlmigration.go
  pkg/sqlstore/postgressqlstore/dialect.go
  pkg/sqlstore/postgressqlstore/provider.go
  pkg/sqlstore/sqlitesqlstore/dialect.go
  pkg/sqlstore/sqlitesqlstore/provider.go
  pkg/sqlstore/sqlstore.go
  pkg/sqlstore/sqlstoretest/dialect.go
  pkg/sqlstore/sqlstoretest/provider.go
  pkg/types/auditable.go
  pkg/types/organization.go
  pkg/types/user.go
Labels: bug

#7187 fix: disabled same url check for redirect in logs explorer
  frontend/src/hooks/useSafeNavigate.ts
  frontend/src/providers/QueryBuilder.tsx
Labels: bug

#7231 fix: fix the issue of logs preview and count mismatch in pipelines by updating sample logs query param from limit to pageSize
  frontend/src/container/PipelinePage/PipelineListsView/Preview/hooks/useSampleLogs.ts
Labels: bug

#7219 chore: add identify and group event support to /event API
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/parser.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#7209 feat: update logEvent to pass eventType and replace segment calls wit…
  frontend/src/AppRoutes/index.tsx
  frontend/src/api/common/logEvent.ts
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/OnboardingContainer/__test__/InviteUserFlow.test.tsx
  frontend/src/hooks/analytics/useAnalytics.tsx
  frontend/src/index.html.ejs
  frontend/webpack.config.js
  frontend/webpack.config.prod.js
Labels: enhancement, docs required

#7239 chore: add new user preferences for welcome checklist
  pkg/query-service/app/preferences/map.go
Labels: chore

#7240 fix: add missing send_resolved for email/pager/opsgenie edit payload
  frontend/src/container/EditAlertChannels/index.tsx
Labels: bug

#7222 feat(alertmanager): integrate with ruler
  conf/example.yaml
  ee/query-service/app/api/api.go
  ee/query-service/app/api/auth.go
  ee/query-service/app/server.go
  ee/query-service/main.go
  ee/query-service/rules/manager.go
  frontend/src/api/alerts/getTriggered.ts
  frontend/src/api/channels/createMsTeams.ts
  frontend/src/api/channels/editMsTeams.ts
  frontend/src/api/channels/testMsTeams.ts
  frontend/src/pages/ChannelsEdit/index.tsx
  go.mod
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanagerserver/config.go
  pkg/alertmanager/alertmanagerserver/server.go
  pkg/alertmanager/alertmanagerserver/server_test.go
  pkg/alertmanager/config.go
  pkg/alertmanager/config_test.go
  pkg/alertmanager/legacyalertmanager/provider.go
  pkg/alertmanager/service.go
  pkg/alertmanager/signozalertmanager/provider.go
  pkg/config/conf.go
  pkg/factory/registry.go
  pkg/factory/registry_test.go
  pkg/http/middleware/response.go
  pkg/instrumentation/sdk.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/auth/auth.go
  pkg/query-service/constants/constants.go
  pkg/query-service/constants/constants_test.go
  pkg/query-service/integrations/alertManager/manager.go
  pkg/query-service/integrations/alertManager/model.go
  pkg/query-service/integrations/alertManager/notifier.go
  pkg/query-service/main.go
  pkg/query-service/rules/api_params.go
  pkg/query-service/rules/base_rule.go
  pkg/query-service/rules/db.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/test_notification.go
  pkg/signoz/config.go
  pkg/signoz/provider.go
  pkg/signoz/provider_test.go
  pkg/signoz/signoz.go
  pkg/sqlmigration/001_add_organization.go
  pkg/sqlmigration/014_add_alertmanager.go
  pkg/types/alertmanagertypes/channel.go
  pkg/types/alertmanagertypes/channel_test.go
  pkg/types/alertmanagertypes/config.go
  pkg/types/alertmanagertypes/config_test.go
  pkg/types/alertmanagertypes/matcher.go
  pkg/types/alertmanagertypes/matcher_test.go
  pkg/types/alertmanagertypes/receiver.go
  pkg/types/alertmanagertypes/receiver_test.go
  pkg/types/alertmanagertypes/route.go
Labels: enhancement

#7244 fix: fixed handling of how and when to set ALL option
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
Labels: bug

#7257 fix: ignore identity for default user
  pkg/query-service/app/http_handler.go
  pkg/query-service/telemetry/telemetry.go
Labels: bug

#7238 feat: implement metric details view in metrics explorer
  frontend/src/api/metricsExplorer/getMetricDetails.ts
  frontend/src/api/metricsExplorer/updateMetricMetadata.ts
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/container/MetricsExplorer/MetricDetails/AllAttributes.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/DashboardsAndAlertsPopover.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/Metadata.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/MetricDetails.styles.scss
  frontend/src/container/MetricsExplorer/MetricDetails/MetricDetails.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/TopAttributes.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/constants.ts
  frontend/src/container/MetricsExplorer/MetricDetails/index.ts
  frontend/src/container/MetricsExplorer/MetricDetails/types.ts
  frontend/src/container/MetricsExplorer/MetricDetails/utils.tsx
  frontend/src/container/MetricsExplorer/Summary/MetricsTable.tsx
  frontend/src/container/MetricsExplorer/Summary/MetricsTreemap.tsx
  frontend/src/container/MetricsExplorer/Summary/Summary.styles.scss
  frontend/src/container/MetricsExplorer/Summary/Summary.tsx
  frontend/src/container/MetricsExplorer/Summary/types.ts
  frontend/src/container/MetricsExplorer/Summary/utils.tsx
  frontend/src/hooks/metricsExplorer/useGetMetricDetails.ts
  frontend/src/hooks/metricsExplorer/useUpdateMetricMetadata.ts
Labels: enhancement, docs not required

#7256 feat: implement explore section in metrics explorer
  frontend/src/api/metricsExplorer/getRelatedMetrics.ts
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/container/ExplorerOptions/constants.ts
  frontend/src/container/ExplorerOptions/types.ts
  frontend/src/container/ExplorerOptions/utils.ts
  frontend/src/container/MetricsExplorer/Explorer/Explorer.styles.scss
  frontend/src/container/MetricsExplorer/Explorer/Explorer.tsx
  frontend/src/container/MetricsExplorer/Explorer/QuerySection.tsx
  frontend/src/container/MetricsExplorer/Explorer/RelatedMetrics.tsx
  frontend/src/container/MetricsExplorer/Explorer/RelatedMetricsCard.tsx
  frontend/src/container/MetricsExplorer/Explorer/TimeSeries.tsx
  frontend/src/container/MetricsExplorer/Explorer/types.ts
  frontend/src/container/MetricsExplorer/Explorer/useGetRelatedMetricsGraphs.ts
  frontend/src/container/MetricsExplorer/Explorer/utils.tsx
  frontend/src/container/MetricsExplorer/Summary/MetricsTable.tsx
  frontend/src/hooks/metricsExplorer/useGetRelatedMetrics.ts
Labels: enhancement, docs not required

#7255 fix: display same key with multiple data types in filter suggestions by enhancing the deduping logic
  frontend/src/hooks/queryBuilder/useOptions.ts
Labels: bug

#7271 fix: update design to support light mode in onboarding v3
  frontend/src/container/OnboardingV2Container/AddDataSource/AddDataSource.tsx
  frontend/src/container/OnboardingV2Container/OnboardingV2.styles.scss
Labels: bug

#7277 feat: update ingestion details api in new onboarding flow
  frontend/src/container/IngestionSettings/MultiIngestionSettings.tsx
  frontend/src/container/OnboardingV2Container/AddDataSource/AddDataSource.tsx
  frontend/src/container/OnboardingV2Container/IngestionDetails/IngestionDetails.tsx
  frontend/src/container/OnboardingV2Container/OnboardingV2.styles.scss
  frontend/src/utils/timeUtils.ts
Labels: enhancement, docs not required

#7237 fix: support multitenancy in dashboards & savedviews
  ee/query-service/app/api/dashboard.go
  ee/query-service/app/server.go
  frontend/src/providers/Dashboard/Dashboard.tsx
  frontend/src/types/api/dashboard/getAll.ts
  pkg/errors/code.go
  pkg/errors/type.go
  pkg/query-service/app/cloudintegrations/controller.go
  pkg/query-service/app/cloudintegrations/model.go
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/dashboards/provision.go
  pkg/query-service/app/explorer/db.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/integrations/controller.go
  pkg/query-service/app/integrations/manager.go
  pkg/query-service/app/integrations/test_utils.go
  pkg/query-service/app/metricsexplorer/summary.go
  pkg/query-service/app/server.go
  pkg/query-service/auth/rbac.go
  pkg/query-service/common/user.go
  pkg/query-service/tests/integration/signoz_integrations_test.go
  pkg/query-service/utils/testutils.go
  pkg/signoz/provider.go
  pkg/sqlmigration/015_update_dashboards_savedviews.go
  pkg/types/dashboard.go
  pkg/types/savedview.go
Labels: bug

#7283 fix: use correct keys in dashboard list
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/hooks/dashboard/useUpdateDashboard.tsx
  frontend/src/mocks-server/__mockdata__/dashboards.ts
Labels: bug

#7288 fix(alertmanager): fix templating
  pkg/alertmanager/alertmanagerserver/server.go
  pkg/query-service/contextlinks/links.go
  pkg/types/alertmanagertypes/template.go
  pkg/types/alertmanagertypes/template_test.go
Labels: bug

#7265 refactor(e2e): remove e2e package
  e2e/package.json
  e2e/playwright.config.ts
  e2e/tests/auth.setup.ts
  e2e/tests/contants.ts
  e2e/tests/navigation.spec.ts
  e2e/yarn.lock
Labels: do-not-merge

#7285 chore: metrics explorer improvements
  frontend/src/api/metricsExplorer/getMetricDetails.ts
  frontend/src/api/metricsExplorer/updateMetricMetadata.ts
  frontend/src/constants/localStorage.ts
  frontend/src/container/MetricsExplorer/Explorer/Explorer.styles.scss
  frontend/src/container/MetricsExplorer/Explorer/Explorer.tsx
  frontend/src/container/MetricsExplorer/Explorer/RelatedMetrics.tsx
  frontend/src/container/MetricsExplorer/Explorer/RelatedMetricsCard.tsx
  frontend/src/container/MetricsExplorer/Explorer/types.ts
  frontend/src/container/MetricsExplorer/MetricDetails/AllAttributes.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/Metadata.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/MetricDetails.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/constants.ts
  frontend/src/container/MetricsExplorer/MetricDetails/types.ts
  frontend/src/container/MetricsExplorer/MetricDetails/utils.tsx
  frontend/src/container/MetricsExplorer/MetricsLoading/MetricsLoading.styles.scss
  frontend/src/container/MetricsExplorer/MetricsLoading/MetricsLoading.tsx
  frontend/src/container/MetricsExplorer/Summary/Summary.tsx
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
  frontend/src/pages/MetricsExplorer/MetricsExplorerPage.tsx
Labels: chore

#7268 chore: update infra monitoring events
  frontend/src/components/HostMetricsDetail/HostMetricsDetails.tsx
  frontend/src/constants/events.ts
  frontend/src/container/InfraMonitoringHosts/HostsList.tsx
  frontend/src/container/InfraMonitoringHosts/HostsListTable.tsx
  frontend/src/container/InfraMonitoringK8s/Clusters/ClusterDetails/ClusterDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Clusters/K8sClustersList.tsx
  frontend/src/container/InfraMonitoringK8s/DaemonSets/DaemonSetDetails/DaemonSetDetails.tsx
  frontend/src/container/InfraMonitoringK8s/DaemonSets/K8sDaemonSetsList.tsx
  frontend/src/container/InfraMonitoringK8s/Deployments/DeploymentDetails/DeploymentDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Deployments/K8sDeploymentsList.tsx
  frontend/src/container/InfraMonitoringK8s/InfraMonitoringK8s.tsx
  frontend/src/container/InfraMonitoringK8s/Jobs/JobDetails/JobDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Jobs/K8sJobsList.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/K8sNamespacesList.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/NamespaceDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/K8sNodesList.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/NodeDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Pods/K8sPodLists.tsx
  frontend/src/container/InfraMonitoringK8s/Pods/PodDetails/PodDetails.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/K8sStatefulSetsList.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/StatefulSetDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Volumes/K8sVolumesList.tsx
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/VolumeDetails.tsx
Labels: chore

#7197 feat: Add inspect metrics API
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metricsexplorer/parser.go
  pkg/query-service/app/metricsexplorer/summary.go
  pkg/query-service/app/summary.go
  pkg/query-service/constants/constants.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/metrics_explorer/summary.go
  pkg/query-service/utils/filter_conditions.go
Labels: enhancement, docs required

#7305 fix: use correct createdAt and updatedAt for dashboards
  frontend/src/container/AlertHistory/Statistics/TopContributorsCard/TopContributorsCard.tsx
  frontend/src/container/GridCardLayout/DashboardEmptyState/DashboardEmptyState.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/GridCardLayout/WidgetRow.tsx
  frontend/src/container/ListOfDashboard/SearchFilter/__tests__/utils.test.ts
  frontend/src/pages/DashboardsListPage/__tests__/DashboardListPage.test.tsx
Labels: bug

#7247 fix: include frontend with oss query-service
  pkg/query-service/Dockerfile
Labels: safe-to-test

#7307 fix: handle 0 step interval
  pkg/query-service/app/inframetrics/hosts.go
Labels: bug

#7254 fix: update the auto-complete API reading logic
  frontend/src/components/CeleryTask/CeleryTaskConfigOptions/useGetCeleryFilters.ts
  frontend/src/components/QuickFilters/FilterRenderers/Checkbox/Checkbox.tsx
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
  frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
  frontend/src/pages/MessagingQueues/MQGraph/useGetAllConfigOptions.ts
  frontend/src/pages/TracesExplorer/Filter/filterUtils.ts
Labels: bug

#7301 feat: signoz package and deprecation of frontend, alertmanager
  .github/workflows/build.yaml
  .github/workflows/gor-histogramquantile.yaml
  .github/workflows/gor-signoz-community.yaml
  .github/workflows/gor-signoz.yaml
  .github/workflows/push.yaml
  .github/workflows/staging-deployment.yaml
  .github/workflows/testing-deployment.yaml
  .gitpod.yml
  Makefile
  conf/cache-config.yml
  conf/prometheus.yml
  deploy/README.md
  deploy/common/signoz/nginx-config.conf
  deploy/common/signoz/otel-collector-opamp-config.yaml
  deploy/docker-swarm/docker-compose.ha.yaml
  deploy/docker-swarm/docker-compose.yaml
  deploy/docker-swarm/generator/infra/otel-agent-config.yaml
  deploy/docker/docker-compose.ha.yaml
  deploy/docker/docker-compose.testing.yaml
  deploy/docker/docker-compose.yaml
  deploy/docker/generator/infra/otel-collector-config.yaml
  deploy/install.sh
  ee/query-service/.goreleaser.yaml
  ee/query-service/Dockerfile
  ee/query-service/constants/constants.go
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/conf/default.conf
  frontend/docker-compose.yaml
  frontend/example.env
  pkg/query-service/.goreleaser.yaml
  pkg/query-service/Dockerfile
  scripts/clickhouse/histogramquantile/.goreleaser.yaml
  templates/email/invitation_email_template.html
Labels: enhancement, docs shipped

#7312 fix(alertmanager): send empty array instead of nil
  pkg/alertmanager/api.go
Labels: bug

#7314 fix(usage): set default tenant for exporting usage
  ee/query-service/usage/manager.go
Labels: bug

#7287 fix: give correct span counts via waterfall api
  pkg/query-service/app/clickhouseReader/reader.go
Labels: safe-to-test

#7330 feat: update license based ui messaging
  frontend/public/locales/en-GB/titles.json
  frontend/public/locales/en/titles.json
  frontend/src/AppRoutes/Private.tsx
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/constants/routes.ts
  frontend/src/container/AppLayout/AppLayout.styles.scss
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/BillingContainer/BillingContainer.tsx
  frontend/src/container/InfraMonitoringK8s/commonUtils.tsx
  frontend/src/container/TopNav/Breadcrumbs/index.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/pages/WorkspaceAccessRestricted/WorkspaceAccessRestricted.styles.scss
  frontend/src/pages/WorkspaceAccessRestricted/WorkspaceAccessRestricted.tsx
  frontend/src/pages/WorkspaceAccessRestricted/index.tsx
  frontend/src/pages/WorkspaceLocked/WorkspaceLocked.tsx
  frontend/src/pages/WorkspaceSuspended/WorkspaceSuspended.tsx
  frontend/src/utils/permission/index.ts
Labels: request-more-info

#7328 feat: update ui based on license states
  frontend/public/locales/en-GB/titles.json
  frontend/public/locales/en/titles.json
  frontend/src/AppRoutes/Private.tsx
  frontend/src/AppRoutes/index.tsx
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/components/LaunchChatSupport/LaunchChatSupport.tsx
  frontend/src/constants/routes.ts
  frontend/src/container/AppLayout/AppLayout.styles.scss
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/BillingContainer/BillingContainer.test.tsx
  frontend/src/container/BillingContainer/BillingContainer.tsx
  frontend/src/container/InfraMonitoringK8s/commonUtils.tsx
  frontend/src/container/ServiceApplication/ServiceMetrics/ServiceMetricTable.tsx
  frontend/src/container/ServiceApplication/ServiceTraces/ServiceTracesTable.tsx
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/container/TopNav/Breadcrumbs/index.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/pages/Settings/index.tsx
  frontend/src/pages/Support/Support.tsx
  frontend/src/pages/WorkspaceAccessRestricted/WorkspaceAccessRestricted.styles.scss
  frontend/src/pages/WorkspaceAccessRestricted/WorkspaceAccessRestricted.tsx
  frontend/src/pages/WorkspaceAccessRestricted/index.tsx
  frontend/src/pages/WorkspaceLocked/WorkspaceLocked.tsx
  frontend/src/pages/WorkspaceSuspended/WorkspaceSuspended.tsx
  frontend/src/providers/App/App.tsx
  frontend/src/providers/App/types.ts
  frontend/src/tests/test-utils.tsx
  frontend/src/types/api/licenses/getAll.ts
  frontend/src/types/api/licensesV3/getActive.ts
  frontend/src/utils/permission/index.ts
Labels: enhancement, docs not required

#7336 fix: enable 8080 ports for testing standalone and swarm
  deploy/docker-swarm/docker-compose.ha.yaml
  deploy/docker-swarm/docker-compose.yaml
  deploy/docker/docker-compose.testing.yaml
Labels: bug

#7341 fix(license): add check for current route for workspace access
  frontend/src/AppRoutes/Private.tsx
Labels: bug

#7345 fix(license): OSS UI build failing due to restrictive active license check
  frontend/src/AppRoutes/index.tsx
  frontend/src/container/Home/DataSourceInfo/DataSourceInfo.tsx
  frontend/src/container/Home/HomeChecklist/HomeChecklist.tsx
  frontend/src/container/Home/Services/ServiceMetrics.tsx
  frontend/src/container/Home/Services/ServiceTraces.tsx
  frontend/src/container/Home/constants.ts
  frontend/src/pages/WorkspaceAccessRestricted/WorkspaceAccessRestricted.tsx
  frontend/src/pages/WorkspaceLocked/WorkspaceLocked.tsx
  frontend/src/pages/WorkspaceSuspended/WorkspaceSuspended.tsx
Labels: bug, request-more-info

#7300 fix: fixed legend format not working for Pie Chart
  frontend/src/container/PanelWrapper/PiePanelWrapper.styles.scss
  frontend/src/container/PanelWrapper/PiePanelWrapper.tsx
Labels: bug

#7235 feat(summary): added update metrics metadata api
  ee/query-service/app/server.go
  go.mod
  go.sum
  pkg/http/middleware/logging.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metricsexplorer/parser.go
  pkg/query-service/app/metricsexplorer/summary.go
  pkg/query-service/app/querier/helper.go
  pkg/query-service/app/querier/v2/helper.go
  pkg/query-service/app/server.go
  pkg/query-service/app/summary.go
  pkg/query-service/constants/constants.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/metrics_explorer/summary.go
  pkg/query-service/model/updatedMetricsMetadata.go
  pkg/query-service/rules/threshold_rule_test.go
Labels: enhancement

#7354 fix: min step interval to 60
  pkg/query-service/common/query_range.go
Labels: bug

#7339 feat: made value panel responsive and background color to full
  frontend/src/components/ValueGraph/ValueGraph.styles.scss
  frontend/src/components/ValueGraph/index.tsx
  frontend/src/container/PanelWrapper/__tests__/ValuePanelWrapper.test.tsx
  frontend/src/container/PanelWrapper/__tests__/__snapshots__/ValuePanelWrapper.test.tsx.snap
Labels: enhancement, docs not required

#7322 feat: added label with value (result) in Pie charts
  frontend/src/container/PanelWrapper/PiePanelWrapper.tsx
Labels: enhancement, docs not required

#7357 fix(metrics-explorer): added type in list summary api as filter
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/model/metrics_explorer/summary.go
Labels: bug, testing-deploy

#7320 fix: fixed list panel getting no-data in full view and edit panel
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/NewWidget/index.tsx
Labels: bug

#7359 chore: update metric metadata response payload
  pkg/query-service/model/metrics_explorer/summary.go
Labels: bug

#7356 chore: add in-table-search for metric name and type in metrics explorer
  frontend/src/api/metricsExplorer/getMetricsListFilterValues.ts
  frontend/src/container/MetricsExplorer/Summary/MetricNameSearch.tsx
  frontend/src/container/MetricsExplorer/Summary/MetricTypeSearch.tsx
  frontend/src/container/MetricsExplorer/Summary/Summary.styles.scss
  frontend/src/container/MetricsExplorer/Summary/utils.tsx
  frontend/src/hooks/metricsExplorer/useGetMetricsListFilterValues.ts
Labels: chore

#7362 chore: metrics explorer fixes
  frontend/src/api/metricsExplorer/getMetricsListFilterKeys.ts
  frontend/src/container/MetricsExplorer/Explorer/EmptyMetricsSearch.tsx
  frontend/src/container/MetricsExplorer/Explorer/Explorer.styles.scss
  frontend/src/container/MetricsExplorer/Explorer/Explorer.tsx
  frontend/src/container/MetricsExplorer/Explorer/TimeSeries.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/AllAttributes.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/MetricDetails.tsx
  frontend/src/container/MetricsExplorer/Summary/MetricsTable.tsx
  frontend/src/container/MetricsExplorer/Summary/MetricsTreemap.tsx
  frontend/src/container/MetricsExplorer/Summary/Summary.tsx
  frontend/src/container/MetricsExplorer/Summary/types.ts
  frontend/src/container/SideNav/menuItems.tsx
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
  frontend/src/hooks/metricsExplorer/useGetMetricsListFilterKeys.ts
  frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
Labels: bug, chore

#7372 fix(cache): rely on if-modified-since header to serve static files
  pkg/http/middleware/cache.go
  pkg/http/middleware/cache_test.go
  pkg/web/routerweb/provider.go
Labels: bug

#7373 chore: fix query builder datasource issue in metrics explorer
  frontend/src/container/MetricsExplorer/Summary/Summary.tsx
Labels: bug, chore

#7375 fix(apiserver): remove redundant logs by default
  conf/example.yaml
  pkg/apiserver/config.go
Labels: bug

#7141 feat: added context redirection from panels to explorer pages
  frontend/src/components/CeleryTask/CeleryTaskDetail/CeleryTaskDetail.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskBar.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskLatencyGraph.tsx
  frontend/src/components/CeleryTask/useNavigateToExplorer.ts
  frontend/src/components/CeleryTask/useNavigateToTraces.ts
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/types.ts
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/utils.ts
  frontend/src/container/GridCardLayout/GridCardLayout.styles.scss
  frontend/src/container/GridCardLayout/useGraphClickToShowButton.ts
  frontend/src/container/GridCardLayout/useNavigateToExplorerPages.ts
  frontend/src/container/GridCardLayout/useResolveQuery.ts
  frontend/src/container/GridCardLayout/utils.ts
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
  frontend/src/lib/uPlotLib/plugins/onClickPlugin.ts
  frontend/src/pages/Celery/CeleryOverview/CeleryOverviewDetail/OverviewRightPanelGraph.tsx
  frontend/src/pages/Celery/CeleryOverview/CeleryOverviewDetail/ValueInfo.tsx
  frontend/src/styles.scss
Labels: enhancement, docs required

#7337 fix: move pat and org domains towards postgres multitenancy
  ee/http/middleware/pat.go
  ee/query-service/app/api/cloudIntegrations.go
  ee/query-service/app/api/domains.go
  ee/query-service/app/api/pat.go
  ee/query-service/app/server.go
  ee/query-service/auth/auth.go
  ee/query-service/dao/interface.go
  ee/query-service/dao/sqlite/auth.go
  ee/query-service/dao/sqlite/domain.go
  ee/query-service/dao/sqlite/modelDao.go
  ee/query-service/dao/sqlite/pat.go
  ee/query-service/model/pat.go
  ee/types/domain.go
  ee/types/sso.go
  frontend/src/container/APIKeys/APIKeys.tsx
  frontend/src/types/api/pat/types.ts
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/ingestion_key.go
  pkg/query-service/dao/interface.go
  pkg/query-service/dao/sqlite/connection.go
  pkg/query-service/dao/sqlite/ingestion.go
  pkg/query-service/utils/testutils.go
  pkg/signoz/provider.go
  pkg/sqlmigration/014_add_alertmanager.go
  pkg/sqlmigration/016_pat_org_domains.go
  pkg/sqlmigration/sqlmigration.go
  pkg/types/personal_access_token.go
Labels: bug

#7381 fix(metrics-explorer): added updated metadata in list summary
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metricsexplorer/summary.go
  pkg/query-service/app/querier/helper.go
  pkg/query-service/app/querier/v2/helper.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/metrics_explorer/summary.go
  pkg/query-service/rules/threshold_rule_test.go
Labels: bug

#7377 chore: metris explorer fixes
  frontend/src/api/metricsExplorer/getMetricDetails.ts
  frontend/src/api/metricsExplorer/updateMetricMetadata.ts
  frontend/src/constants/routes.ts
  frontend/src/container/MetricsExplorer/Explorer/EmptyMetricsSearch.tsx
  frontend/src/container/MetricsExplorer/Explorer/Explorer.styles.scss
  frontend/src/container/MetricsExplorer/Explorer/Explorer.tsx
  frontend/src/container/MetricsExplorer/Explorer/TimeSeries.tsx
  frontend/src/container/MetricsExplorer/Explorer/utils.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/Metadata.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/MetricDetails.styles.scss
  frontend/src/container/MetricsExplorer/MetricDetails/utils.tsx
  frontend/src/container/MetricsExplorer/Summary/MetricNameSearch.tsx
  frontend/src/container/MetricsExplorer/Summary/MetricTypeSearch.tsx
  frontend/src/container/MetricsExplorer/Summary/Summary.tsx
  frontend/src/container/SideNav/menuItems.tsx
  frontend/src/pages/MetricsExplorer/MetricsExplorerPage.tsx
  frontend/src/utils/permission/index.ts
Labels: bug, chore

#7393 chore: correct isMonotonic field name in metric details
  frontend/src/container/MetricsExplorer/MetricDetails/Metadata.tsx
Labels: chore

#7392 fix(portal): url limit reached for stripe customer portal
  frontend/src/container/AppLayout/index.tsx
Labels: bug

#7402 fix: fix the pat middleware
  ee/http/middleware/pat.go
Labels: bug

#7324 feat: trace funnels list page
  frontend/public/locales/en/titles.json
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/api/traceFunnels/index.ts
  frontend/src/components/LearnMore/LearnMore.styles.scss
  frontend/src/components/LearnMore/LearnMore.tsx
  frontend/src/components/SignozModal/SignozModal.style.scss
  frontend/src/components/SignozModal/SignozModal.tsx
  frontend/src/constants/dateTimeFormats.ts
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/constants/routes.ts
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/hooks/TracesFunnels/useFunnels.tsx
  frontend/src/hooks/TracesFunnels/useHandleTraceFunnelsSearch.tsx
  frontend/src/hooks/TracesFunnels/useHandleTraceFunnelsSort.tsx
  frontend/src/pages/TracesFunnelDetails/TracesFunnelDetails.tsx
  frontend/src/pages/TracesFunnelDetails/index.tsx
  frontend/src/pages/TracesFunnels/TracesFunnels.styles.scss
  frontend/src/pages/TracesFunnels/components/CreateFunnel/CreateFunnel.tsx
  frontend/src/pages/TracesFunnels/components/DeleteFunnel/DeleteFunnel.styles.scss
  frontend/src/pages/TracesFunnels/components/DeleteFunnel/DeleteFunnel.tsx
  frontend/src/pages/TracesFunnels/components/FunnelsEmptyState/FunnelsEmptyState.styles.scss
  frontend/src/pages/TracesFunnels/components/FunnelsEmptyState/FunnelsEmptyState.tsx
  frontend/src/pages/TracesFunnels/components/FunnelsList/FunnelItemPopover.tsx
  frontend/src/pages/TracesFunnels/components/FunnelsList/FunnelsList.styles.scss
  frontend/src/pages/TracesFunnels/components/FunnelsList/FunnelsList.tsx
  frontend/src/pages/TracesFunnels/components/Header/Header.styles.scss
  frontend/src/pages/TracesFunnels/components/Header/Header.tsx
  frontend/src/pages/TracesFunnels/components/RenameFunnel/RenameFunnel.styles.scss
  frontend/src/pages/TracesFunnels/components/RenameFunnel/RenameFunnel.tsx
  frontend/src/pages/TracesFunnels/components/SearchBar/SearchBar.styles.scss
  frontend/src/pages/TracesFunnels/components/SearchBar/SearchBar.tsx
  frontend/src/pages/TracesFunnels/index.tsx
  frontend/src/pages/TracesModulePage/TracesModulePage.styles.scss
  frontend/src/pages/TracesModulePage/TracesModulePage.tsx
  frontend/src/pages/TracesModulePage/constants.tsx
  frontend/src/types/api/traceFunnels/index.ts
  frontend/src/utils/permission/index.ts
Labels: enhancement, docs required

#7407 fix: update pat last used
  ee/http/middleware/pat.go
Labels: bug

#7408 chore: remove otlp zap encoder
  ee/query-service/main.go
  go.mod
  go.sum
Labels: chore

#7315 feat: adds trace funnels
  ee/query-service/app/server.go
  pkg/alertmanager/alertmanagerserver/server.go
  pkg/factory/registry.go
  pkg/http/middleware/middleware.go
  pkg/http/server/server.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/integrations/traceFunnels/funnel.go
  pkg/query-service/app/integrations/traceFunnels/model.go
  pkg/query-service/app/integrations/traceFunnels/query.go
  pkg/query-service/app/integrations/traceFunnels/store.go
  pkg/query-service/app/integrations/traceFunnels/utils.go
  pkg/query-service/app/server.go
Labels: docs shipped, safe-to-test

#7371 fix: pipelines postgres support and multitenancy
  ee/query-service/app/server.go
  pkg/query-service/agentConf/manager.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/integrations/controller.go
  pkg/query-service/app/integrations/manager.go
  pkg/query-service/app/integrations/pipeline_utils.go
  pkg/query-service/app/integrations/test_utils.go
  pkg/query-service/app/logparsingpipeline/collector_config.go
  pkg/query-service/app/logparsingpipeline/collector_config_test.go
  pkg/query-service/app/logparsingpipeline/controller.go
  pkg/query-service/app/logparsingpipeline/db.go
  pkg/query-service/app/logparsingpipeline/model.go
  pkg/query-service/app/logparsingpipeline/pipelineBuilder.go
  pkg/query-service/app/logparsingpipeline/pipelineBuilder_test.go
  pkg/query-service/app/logparsingpipeline/preview.go
  pkg/query-service/app/logparsingpipeline/preview_test.go
  pkg/query-service/app/logparsingpipeline/processors_test.go
  pkg/query-service/app/logparsingpipeline/severity_parser_test.go
  pkg/query-service/app/logparsingpipeline/time_parser_test.go
  pkg/query-service/app/opamp/model/agent.go
  pkg/query-service/app/server.go
  pkg/query-service/tests/integration/logparsingpipeline_test.go
  pkg/query-service/tests/integration/signoz_integrations_test.go
  pkg/query-service/tests/integration/test_utils.go
  pkg/query-service/utils/testutils.go
  pkg/signoz/provider.go
  pkg/sqlmigration/017_update_pipelines.go
  pkg/types/pipeline.go
  pkg/types/pipelinetypes/pipeline.go
  pkg/types/pipelinetypes/postable_pipeline_test.go
  pkg/types/pipelinetypes/time_parser.go
  pkg/types/pipelinetypes/time_parser_test.go
Labels: bug

#7406 chore: add event on span row click
  frontend/src/components/HostMetricsDetail/HostMetricTraces/HostMetricTraces.tsx
  frontend/src/components/HostMetricsDetail/HostMetricsDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Clusters/ClusterDetails/ClusterDetails.tsx
  frontend/src/container/InfraMonitoringK8s/DaemonSets/DaemonSetDetails/DaemonSetDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Deployments/DeploymentDetails/DeploymentDetails.tsx
  frontend/src/container/InfraMonitoringK8s/EntityDetailsUtils/EntityTraces/EntityTraces.tsx
  frontend/src/container/InfraMonitoringK8s/Jobs/JobDetails/JobDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/NamespaceDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/NodeDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Pods/PodDetails/PodDetails.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/StatefulSetDetails.tsx
Labels: chore, docs not required

#7411 feat: add the new version package
  .github/workflows/build.yaml
  .github/workflows/commitci.yaml
  .github/workflows/goci.yaml
  .github/workflows/gor-signoz-community.yaml
  .github/workflows/gor-signoz.yaml
  .github/workflows/push.yaml
  .github/workflows/staging-deployment.yaml
  .github/workflows/testing-deployment.yaml
  Makefile
  conf/example.yaml
  deploy/docker/docker-compose.ha.yaml
  deploy/docker/docker-compose.testing.yaml
  deploy/docker/docker-compose.yaml
  docs/contributing/development.md
  ee/query-service/.goreleaser.yaml
  ee/query-service/Dockerfile
  ee/query-service/app/api/api.go
  ee/query-service/main.go
  pkg/instrumentation/sdk.go
  pkg/query-service/.goreleaser.yaml
  pkg/query-service/Dockerfile
  pkg/query-service/app/http_handler.go
  pkg/query-service/config/alerts.yml
  pkg/query-service/config/cache-config.yml
  pkg/query-service/config/prometheus.yml
  pkg/query-service/main.go
  pkg/query-service/telemetry/telemetry.go
  pkg/query-service/templates/invitation_email_template.html
  pkg/query-service/version/version.go
  pkg/signoz/config.go
  pkg/signoz/signoz.go
  pkg/version/config.go
  pkg/version/doc.go
  pkg/version/version.go
Labels: enhancement, docs not required

#7416 fix: use sqlStore instead of bun.db
  ee/http/middleware/pat.go
  ee/query-service/app/server.go
  ee/query-service/license/db.go
  ee/query-service/license/manager.go
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/explorer/db.go
  pkg/query-service/app/server.go
  pkg/query-service/utils/testutils.go
Labels: bug

#7420 ci: append amd64 suffix for staging/testing deployment versions
  .github/workflows/staging-deployment.yaml
  .github/workflows/testing-deployment.yaml
Labels: bug, testing-deploy

#7358 docs: for setting up otel demo app and sending data to signoz
  CONTRIBUTING.md
  docs/img/otel-demo-docker-containers.png
  docs/img/otel-demo-helm.png
  docs/img/otel-demo-pods.png
  docs/img/otel-demo-services.png
  docs/otel-demo-docs.md
Labels: safe-to-test

#7308 feat: api monitoring domain details
  frontend/package.json
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/components/QuickFilters/QuickFilters.tsx
  frontend/src/components/QuickFilters/types.ts
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/constants/routes.ts
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/AllEndPoints.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/DomainDetails.styles.scss
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/DomainDetails.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/EndPointDetails.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/EndPointDetailsWrapper.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/DependentServices.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/DomainMetrics.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/EndPointDetailsZeroState.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/EndPointMetrics.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/EndPointsDropDown.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/ErrorState.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/ExpandedRow.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/MetricOverTimeGraph.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/StatusCodeBarCharts.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/StatusCodeTable.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/constants.ts
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainList.tsx
  frontend/src/container/ApiMonitoring/Explorer/Explorer.styles.scss
  frontend/src/container/ApiMonitoring/Explorer/Explorer.tsx
  frontend/src/container/ApiMonitoring/utils.tsx
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
  frontend/src/container/SideNav/menuItems.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/lib/dashboard/getQueryResults.ts
  frontend/src/pages/ApiMonitoring/ApiMonitoringPage.styles.scss
  frontend/src/pages/ApiMonitoring/ApiMonitoringPage.tsx
  frontend/src/pages/ApiMonitoring/constants.tsx
  frontend/src/pages/ApiMonitoring/index.ts
  frontend/src/types/api/widgets/getQuery.ts
  frontend/src/utils/permission/index.ts
  frontend/yarn.lock
Labels: enhancement, docs required

#7413 feat: added logarithmic scale for panels
  frontend/src/container/NewWidget/RightContainer/RightContainer.styles.scss
  frontend/src/container/NewWidget/RightContainer/constants.ts
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/PanelWrapper/UplotPanelWrapper.tsx
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
  frontend/src/lib/uPlotLib/utils/getAxes.ts
  frontend/src/types/api/dashboard/getAll.ts
Labels: enhancement, docs required

#7423 Revert "feat: adds trace funnels"
  ee/query-service/app/server.go
  pkg/alertmanager/alertmanagerserver/server.go
  pkg/factory/registry.go
  pkg/http/middleware/middleware.go
  pkg/http/server/server.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/integrations/traceFunnels/funnel.go
  pkg/query-service/app/integrations/traceFunnels/model.go
  pkg/query-service/app/integrations/traceFunnels/query.go
  pkg/query-service/app/integrations/traceFunnels/store.go
  pkg/query-service/app/integrations/traceFunnels/utils.go
  pkg/query-service/app/server.go
Labels: enhancement

#7422 feat(sqlmigration): cleanup the licenses and sites table
  frontend/src/components/ExplorerCard/ExplorerCard.tsx
  frontend/src/components/ExplorerCard/MenuItemGenerator.tsx
  frontend/src/components/ExplorerCard/__mock__/viewData.ts
  frontend/src/components/ExplorerCard/test/MenuItemGenerator.test.tsx
  frontend/src/components/ExplorerCard/types.ts
  frontend/src/components/ExplorerCard/utils.ts
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/container/Home/SavedViews/SavedViews.tsx
  frontend/src/hooks/useHandleExplorerTabChange.ts
  frontend/src/mocks-server/__mockdata__/explorer_views.ts
  frontend/src/pages/SaveView/index.tsx
  frontend/src/types/api/saveViews/types.ts
  pkg/query-service/app/explorer/db.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/model/v3/v3.go
  pkg/signoz/provider.go
  pkg/sqlmigration/018_drop_licenses_sites.go
  pkg/sqlstore/postgressqlstore/dialect.go
  pkg/sqlstore/postgressqlstore/provider.go
  pkg/sqlstore/sqlitesqlstore/dialect.go
  pkg/sqlstore/sqlitesqlstore/provider.go
  pkg/sqlstore/sqlstore.go
  pkg/sqlstore/sqlstoretest/dialect.go
  pkg/sqlstore/sqlstoretest/provider.go
  pkg/types/identity.go
  pkg/types/savedview.go
  pkg/valuer/uuid.go
  pkg/valuer/valuer.go
Labels: enhancement

#7428 feat(sqlmigration): migrate invites table from bigint to uuid
  pkg/query-service/auth/auth.go
  pkg/signoz/provider.go
  pkg/sqlmigration/019_update_invites.go
  pkg/sqlstore/postgressqlstore/dialect.go
  pkg/sqlstore/sqlitesqlstore/dialect.go
  pkg/sqlstore/sqlstore.go
  pkg/sqlstore/sqlstoretest/dialect.go
  pkg/types/user.go
Labels: enhancement

#7350 feat: AWS Managed Streaming Kafka service integration
  .gitignore
  pkg/query-service/app/cloudintegrations/serviceDefinitions/aws/msk/assets/dashboards/overview.json
  pkg/query-service/app/cloudintegrations/serviceDefinitions/aws/msk/assets/dashboards/overview.png
  pkg/query-service/app/cloudintegrations/serviceDefinitions/aws/msk/icon.svg
  pkg/query-service/app/cloudintegrations/serviceDefinitions/aws/msk/integration.json
  pkg/query-service/app/cloudintegrations/serviceDefinitions/aws/msk/overview.md
Labels: enhancement, docs required

#7436 fix(metrics-explorer): added time filter in inner sub queries of list and samples api
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/metricsexplorer/summary.go
  pkg/query-service/app/summary.go
  pkg/query-service/model/metrics_explorer/summary.go
Labels: bug

#7410 fix: handle expected value less than zero
  ee/query-service/anomaly/seasonal.go
Labels: bug

#7415 fix: stage and run query button same url navigation enabled
  frontend/src/providers/QueryBuilder.tsx
Labels: bug

#7404 fix: use search v2 component for traces data source & minor improvements to search v2 component
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchDropdown.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.styles.scss
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
  frontend/src/hooks/queryBuilder/useOptions.ts
Labels: bug

#7433 chore: skip logfield/spanfield type in the suggestions
  pkg/query-service/app/clickhouseReader/filter_suggestions.go
  pkg/query-service/app/clickhouseReader/reader.go
Labels: chore

#7445 feat(sqlstore): move postgres to enterprise codebase
  ee/query-service/main.go
  ee/sqlstore/postgressqlstore/dialect.go
  ee/sqlstore/postgressqlstore/provider.go
  pkg/signoz/provider.go
Labels: enhancement

#7448 fix: fixed copy to clipboard popup getting flooded on every click
  frontend/src/components/Logs/CopyClipboardHOC.tsx
Labels: bug

#7453 fix: telemetry version function call
  pkg/query-service/telemetry/telemetry.go
Labels: bug

#7460 chore: added doc title to messaging queues
  frontend/public/locales/en/titles.json
Labels: chore

#7273 feat: allow width customisation and persist it across users and view
  frontend/src/components/CeleryOverview/CeleryOverviewTable/CeleryOverviewTable.tsx
  frontend/src/components/ResizeTable/ResizableHeader.tsx
  frontend/src/components/ResizeTable/ResizeTable.styles.scss
  frontend/src/components/ResizeTable/ResizeTable.tsx
  frontend/src/components/ResizeTable/styles.ts
  frontend/src/components/ResizeTable/types.ts
  frontend/src/container/AllAlertChannels/__tests__/AlertChannels.test.tsx
  frontend/src/container/AllAlertChannels/__tests__/AlertChannelsNormalUser.test.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/GridCardLayout/utils.ts
  frontend/src/container/GridTableComponent/index.tsx
  frontend/src/container/GridTableComponent/types.ts
  frontend/src/container/LogsPanelTable/LogsPanelComponent.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/PanelWrapper/TablePanelWrapper.tsx
  frontend/src/container/PanelWrapper/__tests__/__snapshots__/TablePanelWrapper.test.tsx.snap
  frontend/src/container/QueryTable/QueryTable.intefaces.ts
  frontend/src/container/QueryTable/QueryTable.tsx
  frontend/src/container/TracesTableComponent/TracesTableComponent.tsx
  frontend/src/providers/Dashboard/Dashboard.tsx
  frontend/src/providers/Dashboard/types.ts
  frontend/src/types/api/dashboard/getAll.ts
Labels: enhancement, docs not required

#7414 fix: added default value to time,space aggregation to fix query_range getting 500 for metric
  frontend/src/constants/queryBuilderOperators.ts
  frontend/src/hooks/queryBuilder/useQueryBuilderOperations.ts
Labels: bug

#7464 Revert "fix: added default value to time,space aggregation to fix query_range getting 500 for metric"
  frontend/src/constants/queryBuilderOperators.ts
  frontend/src/hooks/queryBuilder/useQueryBuilderOperations.ts
Labels: bug

#7474 fix: collector connection to opamp without orgID
  pkg/query-service/app/logparsingpipeline/controller.go
Labels: bug

#7462 Fix the hyperlink for otel-demo-docs in contributing guide
  CONTRIBUTING.md
Labels: safe-to-test

#7478 chore: trace funnels feature flag changes
  ee/query-service/model/plans.go
  frontend/src/constants/features.ts
  frontend/src/pages/TracesModulePage/TracesModulePage.tsx
  pkg/query-service/model/featureSet.go
Labels: enhancement, chore

#7431 feat(sqlmigration): update the alertmanager tables
  ee/sqlstore/postgressqlstore/dialect.go
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanagerstore/sqlalertmanagerstore/config.go
  pkg/alertmanager/api.go
  pkg/alertmanager/legacyalertmanager/provider.go
  pkg/alertmanager/signozalertmanager/provider.go
  pkg/signoz/provider.go
  pkg/sqlmigration/021_update_alertmanager.go
  pkg/sqlstore/sqlitesqlstore/dialect.go
  pkg/sqlstore/sqlstore.go
  pkg/sqlstore/sqlstoretest/dialect.go
  pkg/types/alertmanagertypes/channel.go
  pkg/types/alertmanagertypes/config.go
  pkg/types/alertmanagertypes/state.go
Labels: enhancement

#7432 feat: api monitoring feedback - 2
  frontend/public/locales/en/titles.json
  frontend/src/constants/features.ts
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/AllEndPoints.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/DomainDetails.styles.scss
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/DomainDetails.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/EndPointDetails.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/EndPointDetailsWrapper.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/EndPointDetailsZeroState.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/EndPointMetrics.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/EndPointsDropDown.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/ExpandedRow.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/MetricOverTimeGraph.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/StatusCodeBarCharts.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainList.tsx
  frontend/src/container/ApiMonitoring/Explorer/Explorer.tsx
  frontend/src/container/ApiMonitoring/utils.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/types.ts
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCard/types.ts
  frontend/src/container/GridCardLayout/GridCard/utils.ts
  frontend/src/container/GridCardLayout/useNavigateToExplorerPages.ts
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/container/SideNav/menuItems.tsx
Labels: enhancement, docs required

#7481 feat(sqlmigration): update apdex and TTL status tables
  ee/query-service/app/db/reader.go
  ee/query-service/app/server.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/dao/sqlite/apdex.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/telemetry/telemetry.go
  pkg/query-service/tests/integration/filter_suggestions_test.go
  pkg/query-service/tests/integration/signoz_cloud_integrations_test.go
  pkg/query-service/tests/integration/signoz_integrations_test.go
  pkg/query-service/tests/integration/test_utils.go
  pkg/signoz/provider.go
  pkg/sqlmigration/022_update_apdex_ttl.go
  pkg/types/dashboard.go
  pkg/types/organization.go
Labels: enhancement

#7482 feat(sqlmigration): fix the reset password and pat tables
  ee/sqlstore/postgressqlstore/dialect.go
  pkg/modules/preference/core/store.go
  pkg/query-service/auth/auth.go
  pkg/query-service/telemetry/telemetry.go
  pkg/signoz/provider.go
  pkg/sqlmigration/019_update_invites.go
  pkg/sqlmigration/021_update_alertmanager.go
  pkg/sqlmigration/023_update_apdex_ttl.go
  pkg/sqlmigration/024_update_reset_password.go
  pkg/sqlstore/sqlitesqlstore/dialect.go
  pkg/sqlstore/sqlstore.go
  pkg/sqlstore/sqlstoretest/dialect.go
  pkg/types/user.go
Labels: bug, enhancement

#7442 feat(preference): add multi-tenant preference module
  ee/query-service/app/api/api.go
  ee/query-service/app/db/reader.go
  ee/query-service/app/server.go
  ee/sqlstore/postgressqlstore/dialect.go
  pkg/modules/preference/api.go
  pkg/modules/preference/core/preference.go
  pkg/modules/preference/core/store.go
  pkg/modules/preference/usecase.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/preferences/map.go
  pkg/query-service/app/preferences/model.go
  pkg/query-service/app/server.go
  pkg/query-service/auth/auth.go
  pkg/query-service/dao/sqlite/apdex.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/telemetry/telemetry.go
  pkg/query-service/tests/integration/filter_suggestions_test.go
  pkg/query-service/tests/integration/signoz_cloud_integrations_test.go
  pkg/query-service/tests/integration/signoz_integrations_test.go
  pkg/query-service/tests/integration/test_utils.go
  pkg/signoz/provider.go
  pkg/sqlmigration/019_update_invites.go
  pkg/sqlmigration/021_update_alertmanager.go
  pkg/sqlmigration/022_update_preferences.go
  pkg/sqlmigration/023_update_apdex_ttl.go
  pkg/sqlmigration/024_update_reset_password.go
  pkg/sqlmigration/sqlmigration.go
  pkg/sqlstore/sqlitesqlstore/dialect.go
  pkg/sqlstore/sqlstore.go
  pkg/sqlstore/sqlstoretest/dialect.go
  pkg/types/dashboard.go
  pkg/types/organization.go
  pkg/types/preference.go
  pkg/types/preferencetypes/preference.go
  pkg/types/preferencetypes/value.go
  pkg/types/user.go
Labels: enhancement

#7454 fix: handle 404 redirection on root route
  frontend/src/AppRoutes/index.tsx
Labels: bug

#7477 feat: add span to funnel flow (from trace details page)
  frontend/public/Icons/funnel-add.svg
  frontend/src/api/traceFunnels/index.ts
  frontend/src/container/TraceWaterfall/AddSpanToFunnelModal/AddSpanToFunnelModal.styles.scss
  frontend/src/container/TraceWaterfall/AddSpanToFunnelModal/AddSpanToFunnelModal.tsx
  frontend/src/container/TraceWaterfall/TraceWaterfallStates/Success/Success.styles.scss
  frontend/src/container/TraceWaterfall/TraceWaterfallStates/Success/Success.tsx
  frontend/src/hooks/TracesFunnels/useFunnels.tsx
  frontend/src/pages/TraceDetailV2/TraceDetailV2.styles.scss
  frontend/src/pages/TraceDetailV2/index.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/FunnelConfiguration.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/InterStepConfig.styles.scss
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/StepsContent.styles.scss
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/StepsContent.tsx
  frontend/src/pages/TracesFunnels/FunnelContext.tsx
  frontend/src/pages/TracesFunnels/components/CreateFunnel/CreateFunnel.tsx
  frontend/src/pages/TracesFunnels/components/DeleteFunnel/DeleteFunnel.tsx
  frontend/src/pages/TracesFunnels/components/FunnelsEmptyState/FunnelsEmptyState.tsx
  frontend/src/pages/TracesFunnels/components/FunnelsList/FunnelItemPopover.tsx
  frontend/src/pages/TracesFunnels/components/FunnelsList/FunnelsList.tsx
  frontend/src/pages/TracesFunnels/index.tsx
Labels: enhancement

#7451 feat: funnel details page results
  frontend/public/Icons/funnel-add.svg
  frontend/public/Icons/solid-info-circle.svg
  frontend/src/api/traceFunnels/index.ts
  frontend/src/components/ChangePercentagePill/ChangePercentagePill.styles.scss
  frontend/src/components/ChangePercentagePill/ChangePercentagePill.tsx
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
  frontend/src/container/TraceWaterfall/AddSpanToFunnelModal/AddSpanToFunnelModal.styles.scss
  frontend/src/container/TraceWaterfall/AddSpanToFunnelModal/AddSpanToFunnelModal.tsx
  frontend/src/container/TraceWaterfall/TraceWaterfallStates/Success/Success.styles.scss
  frontend/src/container/TraceWaterfall/TraceWaterfallStates/Success/Success.tsx
  frontend/src/hooks/TracesFunnels/useFunnelConfiguration.tsx
  frontend/src/hooks/TracesFunnels/useFunnelGraph.tsx
  frontend/src/hooks/TracesFunnels/useFunnelMetrics.ts
  frontend/src/hooks/TracesFunnels/useFunnels.tsx
  frontend/src/hooks/TracesFunnels/useHandleTraceFunnelsSearch.tsx
  frontend/src/pages/TraceDetailV2/TraceDetailV2.styles.scss
  frontend/src/pages/TraceDetailV2/index.tsx
  frontend/src/pages/TracesFunnelDetails/TracesFunnelDetails.styles.scss
  frontend/src/pages/TracesFunnelDetails/TracesFunnelDetails.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/AddFunnelStepDetailsModal.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/FunnelConfiguration.styles.scss
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/FunnelConfiguration.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/FunnelStep.styles.scss
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/FunnelStep.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/FunnelStepPopover.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/InterStepConfig.styles.scss
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/InterStepConfig.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/StepsContent.styles.scss
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/StepsContent.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/StepsFooter.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/EmptyFunnelResults.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/FunnelGraph.styles.scss
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/FunnelGraph.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/FunnelMetricsTable.styles.scss
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/FunnelMetricsTable.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/FunnelResults.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/FunnelTable.styles.scss
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/FunnelTable.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/FunnelTopTracesTable.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/OverallMetrics.styles.scss
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/OverallMetrics.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/StepsTransitionMetrics.styles.scss
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/StepsTransitionMetrics.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/StepsTransitionResults.styles.scss
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/StepsTransitionResults.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/TopSlowestTraces.styles.scss
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/TopSlowestTraces.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/TopTracesWithErrors.styles.scss
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/TopTracesWithErrors.tsx
  frontend/src/pages/TracesFunnels/FunnelContext.tsx
  frontend/src/pages/TracesFunnels/components/CreateFunnel/CreateFunnel.tsx
  frontend/src/pages/TracesFunnels/components/DeleteFunnel/DeleteFunnel.tsx
  frontend/src/pages/TracesFunnels/components/FunnelsEmptyState/FunnelsEmptyState.tsx
  frontend/src/pages/TracesFunnels/components/FunnelsList/FunnelItemPopover.tsx
  frontend/src/pages/TracesFunnels/components/FunnelsList/FunnelsList.tsx
  frontend/src/pages/TracesFunnels/index.tsx
Labels: enhancement

#7463 fix(nil-pointer): wrong error passed | 2262
  pkg/query-service/app/summary.go
Labels: bug

#7487 chore: use new uuid in pipelines
  pkg/query-service/app/integrations/manager.go
  pkg/query-service/app/logparsingpipeline/controller.go
  pkg/query-service/app/logparsingpipeline/db.go
  pkg/query-service/app/logparsingpipeline/pipelineBuilder_test.go
  pkg/query-service/tests/integration/signoz_integrations_test.go
  pkg/types/pipelinetypes/pipeline.go
Labels: chore

#7397 feat(prometheus): create a dedicated prometheus package
  Makefile
  conf/example.yaml
  ee/query-service/app/db/reader.go
  ee/query-service/app/server.go
  ee/query-service/interfaces/connector.go
  ee/query-service/main.go
  ee/query-service/rules/manager.go
  go.mod
  go.sum
  pkg/prometheus/clickhouseprometheus/client.go
  pkg/prometheus/clickhouseprometheus/json.go
  pkg/prometheus/clickhouseprometheus/provider.go
  pkg/prometheus/clickhouseprometheus/scanner.go
  pkg/prometheus/clickhouseprometheus/table.go
  pkg/prometheus/config.go
  pkg/prometheus/engine.go
  pkg/prometheus/prometheus.go
  pkg/prometheus/prometheustest/provider.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/querier/v2/querier_test.go
  pkg/query-service/app/server.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/main.go
  pkg/query-service/pqlEngine/engine.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/prom_rule.go
  pkg/query-service/rules/test_notification.go
  pkg/query-service/rules/threshold_rule_test.go
  pkg/query-service/tests/integration/test_utils.go
  pkg/signoz/config.go
  pkg/signoz/provider.go
  pkg/signoz/provider_test.go
  pkg/signoz/signoz.go
  pkg/telemetrystore/clickhousetelemetrystore/provider.go
  pkg/telemetrystore/config.go
  pkg/telemetrystore/config_test.go
  pkg/telemetrystore/event.go
  pkg/telemetrystore/telemetrystore.go
  pkg/telemetrystore/telemetrystorehook/logging.go
  pkg/telemetrystore/telemetrystorehook/settings.go
  pkg/telemetrystore/telemetrystoretest/provider.go
  pkg/telemetrystore/telemetrystoretest/provider_test.go
Labels: enhancement, docs not required

#7493 fix: don't panic in GetClickhouseColumnName
  pkg/query-service/utils/format.go
Labels: bug
