Repository SigNoz/signoz, pull requests merged in 2025-09, with the labels that each got.

#8954 Revert "3rd party API sem conv fix (Supports >1.26)"
  pkg/modules/thirdpartyapi/translator.go
  pkg/modules/thirdpartyapi/translator_test.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/integrations/thirdPartyApi/model.go
  pkg/query-service/app/integrations/thirdPartyApi/translator.go
  pkg/query-service/app/integrations/thirdPartyApi/translator_test.go
  pkg/query-service/app/parser.go
  pkg/types/thirdpartyapitypes/thirdpartyapi.go
Labels: bug

#8513 feat: added custom retention for logs api
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/queryParams.go
  pkg/signoz/provider.go
  pkg/sqlmigration/048_update_ttl_setting.go
  pkg/types/organization.go
Labels: enhancement, events-pod, docs not required, safe-to-integrate, staging:legal-bluejay

#8970 chore: update clickhouse-sql-parser
  go.mod
  go.sum
Labels: bug

#8971 fix(dashboard): remove context from dashboard types
  pkg/modules/dashboard/dashboard.go
  pkg/modules/dashboard/impldashboard/handler.go
  pkg/modules/dashboard/impldashboard/module.go
  pkg/types/dashboardtypes/dashboard.go
Labels: bug

#8973 fix: support canDefaultZero for logs and traces
  pkg/querier/postprocess.go
  pkg/types/querybuildertypes/querybuildertypesv5/req.go
  pkg/types/querybuildertypes/querybuildertypesv5/req_test.go
Labels: bug

#8769 feat: add pinning functionality for span attributes
  frontend/src/constants/localStorage.ts
  frontend/src/constants/userPreferences.ts
  frontend/src/container/SpanDetailsDrawer/Attributes/AttributeActions.tsx
  frontend/src/container/SpanDetailsDrawer/Attributes/Attributes.styles.scss
  frontend/src/container/SpanDetailsDrawer/Attributes/Attributes.tsx
  frontend/src/container/SpanDetailsDrawer/__tests__/AttributeActions.userflow.test.tsx
  frontend/src/hooks/spanDetails/usePinnedAttributes.ts
  pkg/types/preferencetypes/name.go
  pkg/types/preferencetypes/preference.go
Labels: enhancement, docs not required

#8983 feat(password): implement strong controls for password
  cmd/enterprise/Dockerfile.integration
  ee/query-service/app/api/cloudIntegrations.go
  pkg/http/binding/binding.go
  pkg/http/binding/json.go
  pkg/modules/organization/implorganization/store.go
  pkg/modules/quickfilter/implquickfilter/store.go
  pkg/modules/user/impluser/handler.go
  pkg/modules/user/impluser/module.go
  pkg/modules/user/impluser/store.go
  pkg/modules/user/option.go
  pkg/modules/user/user.go
  pkg/query-service/app/http_handler.go
  pkg/types/factor_password.go
  pkg/types/factor_password_test.go
  pkg/types/user.go
  tests/integration/fixtures/auth.py
  tests/integration/fixtures/postgres.py
  tests/integration/fixtures/sqlite.py
  tests/integration/fixtures/types.py
  tests/integration/poetry.lock
  tests/integration/pyproject.toml
  tests/integration/src/auth/a_register.py
  tests/integration/src/auth/b_license.py
  tests/integration/src/auth/c_apikey.py
  tests/integration/src/auth/d_password.py
Labels: enhancement, safe-to-integrate, staging:next-ewe

#9010 fix(binding): better error messages
  pkg/http/binding/binding.go
  pkg/http/binding/json.go
  pkg/http/binding/json_test.go
Labels: bug, safe-to-integrate

#7744 feat: added new component to existing variables
  frontend/src/components/NewSelect/CustomMultiSelect.tsx
  frontend/src/components/NewSelect/CustomSelect.tsx
  frontend/src/components/NewSelect/__test__/CustomMultiSelect.comprehensive.test.tsx
  frontend/src/components/NewSelect/__test__/CustomSelect.comprehensive.test.tsx
  frontend/src/components/NewSelect/__test__/VariableItem.integration.test.tsx
  frontend/src/components/NewSelect/styles.scss
  frontend/src/components/NewSelect/types.ts
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.test.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/__test__/VariableItem.defaulting.behavior.test.tsx
Labels: enhancement, docs not required, staging:patient-bat

#8876 feat: added ability to add/remove variable filter to one or more existing panels
  frontend/src/api/dynamicVariables/__tests__/getFieldValues.test.ts
  frontend/src/api/dynamicVariables/getFieldKeys.ts
  frontend/src/api/dynamicVariables/getFieldValues.ts
  frontend/src/api/v5/queryRange/prepareQueryRangePayloadV5.ts
  frontend/src/components/HostMetricsDetail/Metrics/Metrics.tsx
  frontend/src/components/NewSelect/CustomMultiSelect.tsx
  frontend/src/components/NewSelect/CustomSelect.tsx
  frontend/src/components/NewSelect/__test__/CustomMultiSelect.test.tsx
  frontend/src/components/NewSelect/styles.scss
  frontend/src/components/NewSelect/types.ts
  frontend/src/components/NewSelect/utils.ts
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAggregation/QueryAggregationSelect.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QuerySearch/QuerySearch.tsx
  frontend/src/components/QueryBuilderV2/__tests__/utils.test.ts
  frontend/src/components/QueryBuilderV2/utils.ts
  frontend/src/components/TextToolTip/TextToolTip.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCard/types.ts
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/GridCardLayout/useResolveQuery.ts
  frontend/src/container/InfraMonitoringK8s/EntityDetailsUtils/EntityMetrics/EntityMetrics.tsx
  frontend/src/container/NewDashboard/DashboardSettings/DashboardSettings.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/DynamicVariable/DynamicVariable.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/DynamicVariable/DynamicVariable.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/DynamicVariable/__test__/DynamicVariable.test.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.test.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/WidgetSelector.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/addTagFiltersToDashboard.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/index.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DynamicVariableSelection.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/__test__/DynamicVariableSelection.test.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/util.ts
  frontend/src/container/NewDashboard/__test__/DynamicVariableDefaultBehavior.test.tsx
  frontend/src/container/NewDashboard/__test__/IntegrationTests.test.tsx
  frontend/src/container/NewDashboard/__test__/PanelManagement.test.tsx
  frontend/src/container/NewDashboard/__test__/VariableItem.test.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/__test__/QueryBuilderSearchV2.test.tsx
  frontend/src/hooks/dashboard/__test__/useGetDynamicVariables.test.tsx
  frontend/src/hooks/dashboard/useAddDynamicVariableToPanels.tsx
  frontend/src/hooks/dashboard/useDashboardFromLocalStorage.tsx
  frontend/src/hooks/dashboard/useGetDynamicVariables.tsx
  frontend/src/hooks/dashboard/utils.ts
  frontend/src/hooks/dynamicVariables/useGetFieldValues.ts
  frontend/src/hooks/queryBuilder/useCreateAlerts.tsx
  frontend/src/hooks/queryBuilder/useGetQueryRange.ts
  frontend/src/hooks/queryBuilder/useOptions.ts
  frontend/src/lib/dashbaordVariables/getDashboardVariables.ts
  frontend/src/lib/dashboard/getQueryResults.ts
  frontend/src/providers/Dashboard/types.ts
  frontend/src/types/api/dynamicVariables/getFieldValues.ts
Labels: enhancement, safe-to-test

#9019 chore: tooltip editorial changes
  frontend/src/components/NewSelect/CustomMultiSelect.tsx
  frontend/src/components/NewSelect/CustomSelect.tsx
  frontend/src/components/NewSelect/__test__/CustomMultiSelect.comprehensive.test.tsx
  frontend/src/components/NewSelect/__test__/CustomMultiSelect.test.tsx
  frontend/src/components/NewSelect/__test__/CustomSelect.test.tsx
  frontend/src/components/NewSelect/styles.scss
  frontend/src/components/OrderBy/ListViewOrderBy.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/DynamicVariable/DynamicVariable.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/DynamicVariable/DynamicVariable.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/DynamicVariable/__test__/DynamicVariable.test.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.test.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DynamicVariableSelection.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/__test__/DynamicVariableSelection.test.tsx
Labels: chore

#9018 chore: product link and retires retry condition
  frontend/src/components/NewSelect/CustomMultiSelect.tsx
  frontend/src/components/NewSelect/CustomSelect.tsx
  frontend/src/components/NewSelect/__test__/CustomMultiSelect.comprehensive.test.tsx
  frontend/src/components/NewSelect/__test__/CustomMultiSelect.retry.test.tsx
  frontend/src/components/NewSelect/__test__/CustomMultiSelect.test.tsx
  frontend/src/components/NewSelect/__test__/CustomSelect.test.tsx
  frontend/src/components/NewSelect/styles.scss
  frontend/src/components/NewSelect/types.ts
  frontend/src/components/OrderBy/ListViewOrderBy.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/DynamicVariable/DynamicVariable.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/DynamicVariable/DynamicVariable.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/DynamicVariable/__test__/DynamicVariable.test.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.test.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DynamicVariableSelection.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/__test__/DynamicVariableSelection.test.tsx
  frontend/src/utils/__tests__/errorUtils.test.ts
  frontend/src/utils/errorUtils.ts
Labels: enhancement, chore, docs not required

#9021 fix(variable_replace_visitor): do not skip boolean value
  pkg/variables/variable_replace_visitor.go
  pkg/variables/variable_replace_visitor_test.go
Labels: bug, chore

#9023 Interactive dashboards fix: hide drilldown features for non-query builder panels
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
Labels: bug, enhancement

#9020 chore: enable alertmanager metrics collection with instrumentation::metrics
  go.mod
  pkg/alertmanager/alertmanagerserver/server.go
  pkg/instrumentation/metric.go
  pkg/instrumentation/sdk.go
Labels: enhancement, chore, staging:patient-bat

#9030 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: chore

#9043 fix(user): populate correct error message on client
  frontend/src/api/v1/login/loginPrecheck.ts
  frontend/src/api/v1/register/signup.ts
  frontend/src/container/Login/index.tsx
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/types/api/user/getInviteDetails.ts
  frontend/src/types/api/user/loginPrecheck.ts
  pkg/query-service/app/http_handler.go
Labels: bug, docs not required, staging:wealthy-pelican

#9047 chore: enable forbidigo and noerrors in depguard
  .golangci.yml
  cmd/community/server.go
  cmd/config.go
  cmd/enterprise/server.go
  pkg/config/resolver.go
  pkg/errors/code.go
  pkg/errors/errors.go
  pkg/errors/errors_test.go
  pkg/factory/registry.go
  pkg/gateway/config.go
  pkg/instrumentation/metric.go
  pkg/signoz/config.go
  pkg/signoz/config_test.go
  pkg/smtp/client/auth.go
  pkg/smtp/client/smtp.go
  pkg/sqlmigration/013_update_organization.go
  pkg/sqlmigration/014_add_alertmanager.go
  pkg/sqlmigration/046_update_dashboard_alert_and_saved_view_v5.go
  pkg/sqlmigration/sqlmigration.go
  pkg/sqlmigrator/config.go
  pkg/sqlmigrator/migrator.go
  pkg/sqlschema/sqlitesqlschema/ddl.go
  pkg/telemetrystore/telemetrystorehook/logging.go
  pkg/types/authtypes/uuid.go
  pkg/types/pipelinetypes/time_parser.go
  pkg/types/ruletypes/recurrence.go
  pkg/types/ruletypes/templates.go
  pkg/types/ssotypes/google.go
  pkg/valuer/string.go
  pkg/valuer/uuid.go
  pkg/valuer/valuer.go
  pkg/version/version.go
Labels: chore, safe-to-integrate

#9048 Fix: changelog modal spacing issue
  frontend/src/components/ChangelogModal/components/ChangelogRenderer.styles.scss
  frontend/src/components/ChangelogModal/components/ChangelogRenderer.tsx
Labels: bug

#9049 chore: added resolution brace-expansion to 2.0.2 to fix the vulnerability
  frontend/package.json
  frontend/yarn.lock
Labels: bug, chore

#8731 fix: logs explorer chart severity text bugfixes
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/LogStateIndicator/LogStateIndicator.styles.scss
  frontend/src/components/Logs/LogStateIndicator/LogStateIndicator.test.tsx
  frontend/src/components/Logs/LogStateIndicator/LogStateIndicator.tsx
  frontend/src/components/Logs/LogStateIndicator/utils.ts
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/TableView/useTableView.tsx
  frontend/src/container/LogsExplorerChart/utils.ts
  frontend/src/container/LogsExplorerList/ColumnView/ColumnView.tsx
Labels: bug

#9055 feat: update yarn lock file
  frontend/yarn.lock
Labels: enhancement, docs not required

#9024 chore: automatically show query addon when the value is present even after refresh
  frontend/src/components/InputWithLabel/InputWithLabel.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAddOns/QueryAddOns.tsx
  frontend/src/components/QueryBuilderV2/__tests__/QueryAddOns.test.tsx
Labels: chore

#8991 chore: add query section to create alerts
  frontend/src/container/CreateAlertV2/CreateAlertHeader/__tests__/CreateAlertHeader.test.tsx
  frontend/src/container/CreateAlertV2/CreateAlertV2.styles.scss
  frontend/src/container/CreateAlertV2/CreateAlertV2.tsx
  frontend/src/container/CreateAlertV2/QuerySection/ChartPreview/ChartPreview.tsx
  frontend/src/container/CreateAlertV2/QuerySection/ChartPreview/index.ts
  frontend/src/container/CreateAlertV2/QuerySection/QuerySection.tsx
  frontend/src/container/CreateAlertV2/QuerySection/__tests__/ChartPreview.test.tsx
  frontend/src/container/CreateAlertV2/QuerySection/__tests__/QuerySection.test.tsx
  frontend/src/container/CreateAlertV2/QuerySection/index.ts
  frontend/src/container/CreateAlertV2/QuerySection/styles.scss
  frontend/src/container/CreateAlertV2/Stepper/styles.scss
  frontend/src/container/CreateAlertV2/context/index.tsx
  frontend/src/container/CreateAlertV2/context/types.ts
  frontend/src/container/CreateAlertV2/context/utils.tsx
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/FormAlertRules/QuerySection.tsx
  frontend/src/pages/CreateAlert/index.tsx
Labels: chore, staging:quiet-buffalo

#9026 feat: change Bar color opacity and make stacking as default
  frontend/src/container/ApiMonitoring/utils.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.test.tsx
  frontend/src/container/MeterExplorer/Breakdown/graphs.ts
  frontend/src/container/MetricsApplication/MetricsApplication.factory.ts
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/container/NewWidget/__test__/NewWidget.test.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/NewWidget/utils.ts
  frontend/src/container/PanelWrapper/__tests__/tablePanelWrapperHelper.ts
  frontend/src/container/PanelWrapper/__tests__/valuePanelWrapperHelper.ts
  frontend/src/container/QueryTable/__test__/mocks.ts
  frontend/src/hooks/dashboard/utils.ts
  frontend/src/lib/uPlotLib/utils/getSeriesData.ts
  frontend/src/lib/uPlotLib/utils/tests/getSeriesData.test.ts
  frontend/src/pages/MessagingQueues/MQDetails/MetricPage/MetricPageUtil.ts
  frontend/src/types/api/dashboard/getAll.ts
Labels: enhancement, docs not required

#9083 Feat: updated antlr files and added script to generate antlr files
  frontend/src/parser/FilterQueryLexer.interp
  frontend/src/parser/FilterQueryLexer.ts
  frontend/src/parser/FilterQueryListener.ts
  frontend/src/parser/FilterQueryParser.ts
  frontend/src/parser/FilterQueryVisitor.ts
  scripts/grammar/generate-frontend-parser.sh
Labels: enhancement

#9085 chore: make qb v5 default
  pkg/modules/dashboard/impldashboard/handler.go
  pkg/querybuilder/init.go
Labels: chore

#8815 feat: clean up tooltip elements and add dependencies
  frontend/src/components/Uplot/Uplot.tsx
  frontend/src/hooks/useInterval.ts
  frontend/src/index.tsx
Labels: enhancement, docs not required

#9033 fix: fix the incorrect matching spans count
  frontend/src/container/TraceWaterfall/TraceWaterfallStates/Success/Filters/Filters.tsx
Labels: bug

#8857 feat: add support for span logs
  frontend/package.json
  frontend/src/components/Logs/RawLogView/RawLogView.styles.scss
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/RawLogView/styles.ts
  frontend/src/components/Logs/RawLogView/types.ts
  frontend/src/components/SignozRadioGroup/SignozRadioGroup.tsx
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/container/SpanDetailsDrawer/SpanDetailsDrawer.styles.scss
  frontend/src/container/SpanDetailsDrawer/SpanDetailsDrawer.tsx
  frontend/src/container/SpanDetailsDrawer/SpanLogs/SpanLogs.tsx
  frontend/src/container/SpanDetailsDrawer/SpanLogs/constants.ts
  frontend/src/container/SpanDetailsDrawer/SpanLogs/spanLogs.styles.scss
  frontend/src/container/SpanDetailsDrawer/SpanLogs/useSpanContextLogs.ts
  frontend/src/container/SpanDetailsDrawer/SpanRelatedSignals/SpanRelatedSignals.styles.scss
  frontend/src/container/SpanDetailsDrawer/SpanRelatedSignals/SpanRelatedSignals.tsx
  frontend/src/container/SpanDetailsDrawer/__tests__/AttributeActions.userflow.test.tsx
  frontend/src/container/SpanDetailsDrawer/__tests__/SpanDetailsDrawer.test.tsx
  frontend/src/container/SpanDetailsDrawer/__tests__/mockData.ts
  frontend/src/container/SpanDetailsDrawer/constants.ts
  frontend/src/pages/TraceDetailV2/TraceDetailV2.tsx
  frontend/src/types/api/logs/log.ts
  frontend/src/types/api/widgets/getQuery.ts
  frontend/src/utils/logs.ts
  frontend/yarn.lock
Labels: enhancement, docs not required

#9034 feat: make the trace details v2 sidebar resizable
  frontend/package.json
  frontend/src/container/SpanDetailsDrawer/SpanDetailsDrawer.styles.scss
  frontend/src/container/SpanDetailsDrawer/SpanDetailsDrawer.tsx
  frontend/src/pages/TraceDetail/__test__/TraceDetail.test.tsx
  frontend/src/pages/TraceDetailV2/TraceDetailV2.tsx
  frontend/yarn.lock
Labels: enhancement, docs not required

#9094 Converted format options menu to popover
  frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.styles.scss
  frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.tsx
  frontend/src/container/LiveLogs/LiveLogsContainer/index.tsx
  frontend/src/container/LogsExplorerViews/LogsActionsContainer.tsx
Labels: enhancement, frontend, ui

#9104 chore: use wss usage for workloads listing
  frontend/src/container/InfraMonitoringK8s/Clusters/utils.tsx
  frontend/src/container/InfraMonitoringK8s/DaemonSets/utils.tsx
  frontend/src/container/InfraMonitoringK8s/Deployments/utils.tsx
  frontend/src/container/InfraMonitoringK8s/Jobs/utils.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/utils.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/utils.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/utils.tsx
  frontend/src/container/InfraMonitoringK8s/utils.tsx
  pkg/query-service/app/inframetrics/common.go
  pkg/query-service/app/inframetrics/nodes.go
  pkg/query-service/app/inframetrics/pods.go
  pkg/query-service/app/inframetrics/workload_query.go
Labels: chore

#9050 Added Download Button to leverage exportRawData API
  frontend/src/api/v1/download/downloadExportData.ts
  frontend/src/components/LogsDownloadOptionsMenu/LogsDownloadOptionsMenu.styles.scss
  frontend/src/components/LogsDownloadOptionsMenu/LogsDownloadOptionsMenu.test.tsx
  frontend/src/components/LogsDownloadOptionsMenu/LogsDownloadOptionsMenu.tsx
  frontend/src/components/LogsDownloadOptionsMenu/constants.ts
  frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.tsx
  frontend/src/container/LogsExplorerViews/LogsActionsContainer.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsExplorerViews/tests/LogsExplorerViews.test.tsx
  frontend/src/types/api/exportRawData/getExportRawData.ts
Labels: enhancement, frontend, ui, staging:included-weevil

#9025 chore: fix edit alerts page crashing
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
  frontend/src/utils/convertNewToOldQueryBuilder.ts
Labels: bug, chore

#9103 chore: populate default zero queries for metrics
  pkg/types/querybuildertypes/querybuildertypesv5/req.go
  pkg/types/querybuildertypes/querybuildertypesv5/req_test.go
Labels: chore

#9116 Fix: trace details bugfixes
  frontend/src/container/SpanDetailsDrawer/Attributes/Attributes.styles.scss
  frontend/src/container/SpanDetailsDrawer/Attributes/Attributes.tsx
  frontend/src/container/SpanDetailsDrawer/SpanDetailsDrawer.styles.scss
  frontend/src/pages/TraceDetailV2/TraceDetailV2.tsx
Labels: bug

#9027 feat: frontend unit test suite setup
  frontend/.cursorrules
  frontend/__mocks__/uplotMock.ts
  frontend/__mocks__/useSafeNavigate.ts
  frontend/jest.config.ts
  frontend/src/components/DraggableTableRow/tests/DraggableTableRow.test.tsx
  frontend/src/components/ErrorModal/ErrorModal.test.tsx
  frontend/src/components/QuickFilters/tests/QuickFilters.test.tsx
  frontend/src/container/AllAlertChannels/__tests__/AlertChannels.test.tsx
  frontend/src/container/AllAlertChannels/__tests__/AlertChannelsNormalUser.test.tsx
  frontend/src/container/BillingContainer/BillingContainer.test.tsx
  frontend/src/container/CreateAlertRule/AlertRuleDocumentationRedirection.test.tsx
  frontend/src/container/CreateAlertRule/AnomalyAlertDocumentationRedirection.test.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.test.tsx
  frontend/src/container/InfraMonitoringHosts/__tests__/HostsList.test.tsx
  frontend/src/container/InfraMonitoringHosts/__tests__/HostsListTable.test.tsx
  frontend/src/container/InfraMonitoringHosts/__tests__/utilts.test.tsx
  frontend/src/container/InfraMonitoringK8s/EntityDetailsUtils/EntityLogs/__tests__/EntityLogs.test.tsx
  frontend/src/container/InfraMonitoringK8s/__tests__/Jobs/JobDetails/JobDetails.test.tsx
  frontend/src/container/InfraMonitoringK8s/__tests__/commonMocks.ts
  frontend/src/container/LogDetailedView/ContextView/__tests__/ContextLogRenderer.test.tsx
  frontend/src/container/LogsExplorerList/__tests__/LogsExplorerList.test.tsx
  frontend/src/container/LogsExplorerViews/tests/LogsExplorerPagination.test.tsx
  frontend/src/container/LogsExplorerViews/tests/LogsExplorerViews.test.tsx
  frontend/src/container/LogsPanelTable/__tests__/LogsPanelComponent.test.tsx
  frontend/src/container/MetricsExplorer/Explorer/__tests__/Explorer.test.tsx
  frontend/src/container/MetricsExplorer/Inspect/__tests__/GraphView.test.tsx
  frontend/src/container/MetricsExplorer/Inspect/__tests__/Inspect.test.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/__tests__/DashboardsAndAlertsPopover.test.tsx
  frontend/src/container/MetricsExplorer/Summary/__tests__/Summary.test.tsx
  frontend/src/container/PipelinePage/Layouts/ChangeHistory/tests/ChangeHistory.test.tsx
  frontend/src/container/PipelinePage/tests/AddNewPipeline.test.tsx
  frontend/src/container/PipelinePage/tests/AddNewProcessor.test.tsx
  frontend/src/container/PipelinePage/tests/DeleteAction.test.tsx
  frontend/src/container/PipelinePage/tests/DragAction.test.tsx
  frontend/src/container/PipelinePage/tests/EditAction.test.tsx
  frontend/src/container/PipelinePage/tests/PipelineActions.test.tsx
  frontend/src/container/PipelinePage/tests/PipelineExpandView.test.tsx
  frontend/src/container/PipelinePage/tests/PipelineListsView.test.tsx
  frontend/src/container/PipelinePage/tests/PipelinePageLayout.test.tsx
  frontend/src/container/PipelinePage/tests/TagInput.test.tsx
  frontend/src/container/PipelinePage/tests/Tags.test.tsx
  frontend/src/container/PipelinePage/tests/utils.test.ts
  frontend/src/container/PlannedDowntime/__test__/PlannedDowntime.test.tsx
  frontend/src/container/TraceWaterfall/TraceWaterfallStates/Success/__tests__/SpanDuration.test.tsx
  frontend/src/mocks-server/server.ts
  frontend/src/pages/LogsExplorer/__tests__/LogsExplorer.test.tsx
  frontend/src/pages/TraceDetail/__test__/TraceDetail.test.tsx
  frontend/src/pages/TracesExplorer/__test__/TracesExplorer.test.tsx
  frontend/src/pages/WorkspaceLocked/WorkspaceLocked.test.tsx
  frontend/src/tests/README.md
  frontend/src/tests/test-utils.tsx
Labels: enhancement, docs not required

#9124 fix: removed staleTime and cacheTime from query client level
  frontend/src/index.tsx
  frontend/src/providers/Dashboard/Dashboard.tsx
Labels: bug

#9138 fix intermittent failing test
  frontend/src/components/QuickFilters/tests/QuickFilters.test.tsx
Labels: bug

#9125 fix: stale threshold state after modifying alert conditions
  ee/query-service/app/server.go
  pkg/query-service/app/server.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/manager_test.go
  pkg/ruler/rulestore/rulestoretest/rule.go
  pkg/types/ruletypes/api_params.go
  pkg/types/ruletypes/api_params_test.go
  pkg/types/ruletypes/threshold.go
Labels: bug, staging:patient-bat

#9139 fix: dont accept materialized key from payload
  pkg/telemetrylogs/stmt_builder_test.go
  pkg/types/telemetrytypes/field.go
Labels: bug

#9141 fix: added dashboard route param, to allow trigger when new panel creation action happens
  frontend/src/providers/Dashboard/Dashboard.tsx
  frontend/src/providers/Dashboard/__tests__/Dashboard.test.tsx
Labels: bug

#9131 feat: add evaluation cadence component for alerts v2
  frontend/src/container/CreateAlertV2/EvaluationSettings/AdvancedOptionItem/AdvancedOptionItem.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/AdvancedOptionItem/index.ts
  frontend/src/container/CreateAlertV2/EvaluationSettings/AdvancedOptionItem/styles.scss
  frontend/src/container/CreateAlertV2/EvaluationSettings/EvaluationCadence/EditCustomSchedule.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/EvaluationCadence/EvaluationCadence.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/EvaluationCadence/EvaluationCadenceDetails.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/EvaluationCadence/EvaluationCadencePreview.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/EvaluationCadence/index.ts
  frontend/src/container/CreateAlertV2/EvaluationSettings/EvaluationCadence/styles.scss
  frontend/src/container/CreateAlertV2/EvaluationSettings/__tests__/AdvancedOptionItem.test.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/__tests__/EditCustomSchedule.test.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/__tests__/EvaluationCadence.test.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/__tests__/EvaluationCadenceDetails.test.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/__tests__/EvaluationCadencePreview.test.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/__tests__/testUtils.ts
  frontend/src/container/CreateAlertV2/EvaluationSettings/constants.ts
  frontend/src/container/CreateAlertV2/EvaluationSettings/styles.scss
  frontend/src/container/CreateAlertV2/EvaluationSettings/types.ts
  frontend/src/container/CreateAlertV2/context/constants.ts
Labels: enhancement, docs not required, staging:quiet-buffalo

#9175 chore(authz): bump up openfga version
  go.mod
  go.sum
  pkg/authz/openfgaauthz/sqlstore.go
  pkg/instrumentation/sdk.go
  pkg/types/alertmanagertypes/config_test.go
Labels: chore, safe-to-integrate

#9178 chore: change update workspace URL to upgrade guide
  frontend/src/components/ChangelogModal/ChangelogModal.tsx
  frontend/src/components/ChangelogModal/__test__/ChangelogModal.test.tsx
Labels: chore

#9193 revert: removed changes done for cursor position jump fix
  frontend/src/components/QueryBuilderV2/QueryV2/QuerySearch/QuerySearch.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/__tests__/QuerySearch.test.tsx
Labels: bug

#9189 feat: add materialise ttl = 0 in set ttl v2
  pkg/query-service/app/clickhouseReader/reader.go
Labels: enhancement, backend, events-pod, docs not required

#9180 fix: added fix for passing activeLogId in query range in log context view
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsExplorerViews/tests/LogsExplorerViews.test.tsx
Labels: bug

#9096 chore: create a HOC to wrap components with ErrorBoundary
  .gitignore
  frontend/jest.config.ts
  frontend/public/Images/cloud.svg
  frontend/src/components/ErrorBoundaryHOC/README.md
  frontend/src/components/ErrorBoundaryHOC/__tests__/withErrorBoundary.test.tsx
  frontend/src/components/ErrorBoundaryHOC/index.ts
  frontend/src/components/ErrorBoundaryHOC/withErrorBoundary.example.tsx
  frontend/src/components/ErrorBoundaryHOC/withErrorBoundary.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/TopErrors.tsx
  frontend/src/container/MetricsExplorer/Summary/__tests__/Summary.test.tsx
  frontend/src/pages/ErrorBoundaryFallback/ErrorBoundaryFallback.styles.scss
  frontend/src/pages/ErrorBoundaryFallback/ErrorBoundaryFallback.tsx
  frontend/src/pages/Support/Support.styles.scss
  frontend/src/pages/Support/Support.tsx
Labels: chore

#9198 feat: add routing polices page
  frontend/src/api/routingPolicies/createRoutingPolicy.ts
  frontend/src/api/routingPolicies/deleteRoutingPolicy.ts
  frontend/src/api/routingPolicies/getRoutingPolicies.ts
  frontend/src/api/routingPolicies/updateRoutingPolicy.ts
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/container/RoutingPolicies/DeleteRoutingPolicy.tsx
  frontend/src/container/RoutingPolicies/RoutingPolicies.tsx
  frontend/src/container/RoutingPolicies/RoutingPolicyDetails.tsx
  frontend/src/container/RoutingPolicies/RoutingPolicyList.tsx
  frontend/src/container/RoutingPolicies/RoutingPolicyListItem.tsx
  frontend/src/container/RoutingPolicies/__tests__/DeleteRoutingPolicy.test.tsx
  frontend/src/container/RoutingPolicies/__tests__/RoutingPolicies.test.tsx
  frontend/src/container/RoutingPolicies/__tests__/RoutingPoliciesList.test.tsx
  frontend/src/container/RoutingPolicies/__tests__/RoutingPolicyDetails.test.tsx
  frontend/src/container/RoutingPolicies/__tests__/RoutingPolicyListItem.test.tsx
  frontend/src/container/RoutingPolicies/__tests__/testUtils.ts
  frontend/src/container/RoutingPolicies/constants.ts
  frontend/src/container/RoutingPolicies/index.ts
  frontend/src/container/RoutingPolicies/styles.scss
  frontend/src/container/RoutingPolicies/types.ts
  frontend/src/container/RoutingPolicies/useRoutingPolicies.ts
  frontend/src/container/RoutingPolicies/utils.tsx
  frontend/src/hooks/routingPolicies/useCreateRoutingPolicy.ts
  frontend/src/hooks/routingPolicies/useDeleteRoutingPolicy.ts
  frontend/src/hooks/routingPolicies/useGetRoutingPolicies.ts
  frontend/src/hooks/routingPolicies/useUpdateRoutingPolicy.ts
  frontend/src/pages/AlertList/AlertList.styles.scss
  frontend/src/pages/AlertList/index.tsx
Labels: enhancement, docs not required

#9136 feat(authz): build role module
  ee/authz/openfgaschema/base.fga
  ee/http/middleware/authz.go
  pkg/authz/authz.go
  pkg/authz/openfgaauthz/provider.go
  pkg/http/middleware/authz.go
  pkg/modules/dashboard/dashboard.go
  pkg/modules/dashboard/impldashboard/module.go
  pkg/modules/role/implrole/handler.go
  pkg/modules/role/implrole/module.go
  pkg/modules/role/implrole/store.go
  pkg/modules/role/role.go
  pkg/types/authtypes/name.go
  pkg/types/authtypes/organization.go
  pkg/types/authtypes/relation.go
  pkg/types/authtypes/resource.go
  pkg/types/authtypes/resources.go
  pkg/types/authtypes/role.go
  pkg/types/authtypes/selector.go
  pkg/types/authtypes/transaction.go
  pkg/types/authtypes/typeable.go
  pkg/types/authtypes/typeable_organization.go
  pkg/types/authtypes/typeable_resource.go
  pkg/types/authtypes/typeable_resources.go
  pkg/types/authtypes/typeable_role.go
  pkg/types/authtypes/typeable_user.go
  pkg/types/authtypes/user.go
  pkg/types/dashboardtypes/dashboard.go
  pkg/types/roletypes/role.go
  pkg/types/roletypes/store.go
Labels: enhancement

#9165 feat: create alerts ux improvements and api integration
  frontend/src/api/alerts/createAlertRule.ts
  frontend/src/api/alerts/testAlertRule.ts
  frontend/src/container/CreateAlertRule/index.tsx
  frontend/src/container/CreateAlertV2/AlertCondition/AlertCondition.tsx
  frontend/src/container/CreateAlertV2/AlertCondition/AlertThreshold.tsx
  frontend/src/container/CreateAlertV2/AlertCondition/AnomalyThreshold.tsx
  frontend/src/container/CreateAlertV2/AlertCondition/ThresholdItem.tsx
  frontend/src/container/CreateAlertV2/AlertCondition/__tests__/AlertCondition.test.tsx
  frontend/src/container/CreateAlertV2/AlertCondition/__tests__/AlertThreshold.test.tsx
  frontend/src/container/CreateAlertV2/AlertCondition/__tests__/AnomalyThreshold.test.tsx
  frontend/src/container/CreateAlertV2/AlertCondition/__tests__/ThresholdItem.test.tsx
  frontend/src/container/CreateAlertV2/AlertCondition/styles.scss
  frontend/src/container/CreateAlertV2/AlertCondition/types.ts
  frontend/src/container/CreateAlertV2/AlertCondition/utils.tsx
  frontend/src/container/CreateAlertV2/CreateAlertHeader/CreateAlertHeader.tsx
  frontend/src/container/CreateAlertV2/CreateAlertHeader/__tests__/CreateAlertHeader.test.tsx
  frontend/src/container/CreateAlertV2/CreateAlertHeader/styles.scss
  frontend/src/container/CreateAlertV2/CreateAlertV2.styles.scss
  frontend/src/container/CreateAlertV2/CreateAlertV2.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/AdvancedOptionItem/styles.scss
  frontend/src/container/CreateAlertV2/EvaluationSettings/AdvancedOptions.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/EvaluationCadence/EvaluationCadence.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/EvaluationCadence/styles.scss
  frontend/src/container/CreateAlertV2/EvaluationSettings/EvaluationWindowPopover/EvaluationWindowDetails.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/EvaluationWindowPopover/EvaluationWindowPopover.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/__tests__/AdvancedOptions.test.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/__tests__/EvaluationCadence.test.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/__tests__/EvaluationWindowDetails.test.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/__tests__/EvaluationWindowPopover.test.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/__tests__/testUtils.ts
  frontend/src/container/CreateAlertV2/EvaluationSettings/constants.ts
  frontend/src/container/CreateAlertV2/EvaluationSettings/styles.scss
  frontend/src/container/CreateAlertV2/Footer/Footer.tsx
  frontend/src/container/CreateAlertV2/Footer/index.ts
  frontend/src/container/CreateAlertV2/Footer/styles.scss
  frontend/src/container/CreateAlertV2/Footer/types.ts
  frontend/src/container/CreateAlertV2/Footer/utils.tsx
  frontend/src/container/CreateAlertV2/NotificationSettings/NotificationMessage.tsx
  frontend/src/container/CreateAlertV2/NotificationSettings/styles.scss
  frontend/src/container/CreateAlertV2/QuerySection/ChartPreview/ChartPreview.tsx
  frontend/src/container/CreateAlertV2/QuerySection/QuerySection.tsx
  frontend/src/container/CreateAlertV2/QuerySection/__tests__/ChartPreview.test.tsx
  frontend/src/container/CreateAlertV2/QuerySection/__tests__/QuerySection.test.tsx
  frontend/src/container/CreateAlertV2/QuerySection/styles.scss
  frontend/src/container/CreateAlertV2/Stepper/styles.scss
  frontend/src/container/CreateAlertV2/context/constants.ts
  frontend/src/container/CreateAlertV2/context/index.tsx
  frontend/src/container/CreateAlertV2/context/types.ts
  frontend/src/container/CreateAlertV2/context/utils.tsx
  frontend/src/container/CreateAlertV2/types.ts
  frontend/src/container/CreateAlertV2/utils.tsx
  frontend/src/container/FormAlertRules/QuerySection.styles.scss
  frontend/src/container/FormAlertRules/QuerySection.tsx
  frontend/src/hooks/alerts/useCreateAlertRule.ts
  frontend/src/hooks/alerts/useTestAlertRule.ts
  frontend/src/pages/CreateAlert/index.tsx
  frontend/src/types/api/alerts/alertTypesV2.ts
Labels: enhancement, docs not required

#9220 chore(statsreporter): add nomad, vultr, aca platform detection
  pkg/version/deployment.go
Labels: safe-to-test
