Repository SigNoz/signoz, pull requests merged in 2025-05, with the labels that each got.

#7806 chore(ruler): remove the notification for rule ID migration
  frontend/src/container/Home/Home.tsx
Labels: chore

#7712 feat: added changes related to custom options for quick filters
  ee/query-service/app/api/api.go
  ee/query-service/app/api/auth.go
  pkg/modules/quickfilter/api.go
  pkg/modules/quickfilter/core/core.go
  pkg/modules/quickfilter/core/store.go
  pkg/modules/quickfilter/usecase.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/auth/auth.go
  pkg/query-service/tests/integration/filter_suggestions_test.go
  pkg/query-service/tests/integration/signoz_cloud_integrations_test.go
  pkg/query-service/tests/integration/signoz_integrations_test.go
  pkg/signoz/provider.go
  pkg/sqlmigration/030_create_quick_filters.go
  pkg/types/quickfiltertypes/filter.go
  pkg/types/quickfiltertypes/store.go
Labels: enhancement, docs shipped, safe-to-integrate

#7809 chore: updates os for Docker Engine Installation for redhat
  deploy/install.sh
Labels: safe-to-test

#7816 feat: quick_filter_fix
  pkg/modules/quickfilter/core/store.go
  pkg/sqlmigration/030_create_quick_filters.go
  pkg/types/quickfiltertypes/filter.go
Labels: bug, enhancement, docs shipped

#7818 fix(ruler): scan orgIDs in string slice instead of valuer struct
  pkg/ruler/rulestore/sqlrulestore/rule.go
Labels: bug

#7823 fix: description tooltip coming up twice in metrics list table
  frontend/src/container/MetricsExplorer/Summary/__tests__/utils.test.tsx
  frontend/src/container/MetricsExplorer/Summary/utils.tsx
Labels: bug

#7822 fix: correctly populate response_status
  frontend/src/container/ApiMonitoring/APIMonitoringUtils.test.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/constants.ts
  frontend/src/container/ApiMonitoring/utils.tsx
Labels: bug, request-more-info

#7758 Fix/logs issues main
  frontend/src/components/QuickFilters/QuickFilters.styles.scss
  frontend/src/container/LogDetailedView/ContextView/ContextLogRenderer.tsx
  frontend/src/container/LogDetailedView/ContextView/__tests__/ContextLogRenderer.test.tsx
  frontend/src/container/LogDetailedView/ContextView/__tests__/mockData.ts
  frontend/src/container/LogDetailedView/ContextView/useContextLogData.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.styles.scss
  frontend/src/pages/AllErrors/AllErrors.styles.scss
Labels: bug

#7833 fix(7832): added filters in inspect metrics api
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/metricsexplorer/summary.go
  pkg/query-service/interfaces/interface.go
Labels: bug

#7772 chore: trace funnels feedback changes
  frontend/package.json
  frontend/src/container/TraceWaterfall/AddSpanToFunnelModal/AddSpanToFunnelModal.styles.scss
  frontend/src/container/TraceWaterfall/AddSpanToFunnelModal/AddSpanToFunnelModal.tsx
  frontend/src/hooks/TracesFunnels/useFunnelGraph.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/AddFunnelDescriptionModal.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/FunnelConfiguration.styles.scss
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/FunnelConfiguration.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/FunnelStep.styles.scss
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/FunnelStep.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/FunnelStepPopover.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/StepsFooter.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/FunnelGraph.tsx
  frontend/src/pages/TracesFunnels/components/FunnelsList/FunnelsList.styles.scss
  frontend/src/pages/TracesFunnels/components/FunnelsList/FunnelsList.tsx
  frontend/yarn.lock
Labels: chore

#7780 chore: trace funnel changes
  frontend/src/api/traceFunnels/index.ts
  frontend/src/components/CeleryOverview/CeleryOverviewConfigOptions/CeleryOverviewConfigOptions.tsx
  frontend/src/container/TraceWaterfall/AddSpanToFunnelModal/AddSpanToFunnelModal.tsx
  frontend/src/hooks/TracesFunnels/useFunnels.tsx
  frontend/src/hooks/TracesFunnels/useHandleTraceFunnelsSearch.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/AddFunnelStepDetailsModal.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/FunnelStep.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/FunnelStepPopover.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelResults/StepsTransitionResults.tsx
  frontend/src/pages/TracesFunnelDetails/constants.ts
  frontend/src/pages/TracesFunnels/index.tsx
  frontend/src/pages/TracesFunnels/utils.ts
  frontend/src/types/api/traceFunnels/index.ts
Labels: chore

#7607 fix: add dark class to the elements when dark mode is enabled to support components library modes
  frontend/src/container/AppLayout/index.tsx
Labels: bug

#7841 fix(ruler): improve the user experience for rule id migration
  frontend/src/AppRoutes/routes.ts
  frontend/src/pages/AlertDetails/AlertDetails.tsx
Labels: bug, docs not required, staging:next-ewe

#7838 chore: disable writing to v2 tables and add signozclickhousemetrics in signozspanmetrics
  deploy/docker-swarm/otel-collector-config.yaml
  deploy/docker/otel-collector-config.yaml
Labels: chore

#7549 feat: implement inspect feature for metrics explorer
  frontend/src/api/metricsExplorer/getInspectMetricsDetails.ts
  frontend/src/components/ResizeTable/styles.ts
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/container/MetricsExplorer/Inspect/ExpandedView.tsx
  frontend/src/container/MetricsExplorer/Inspect/GraphPopover.tsx
  frontend/src/container/MetricsExplorer/Inspect/GraphView.tsx
  frontend/src/container/MetricsExplorer/Inspect/Inspect.styles.scss
  frontend/src/container/MetricsExplorer/Inspect/Inspect.tsx
  frontend/src/container/MetricsExplorer/Inspect/QueryBuilder.tsx
  frontend/src/container/MetricsExplorer/Inspect/Stepper.tsx
  frontend/src/container/MetricsExplorer/Inspect/TableView.tsx
  frontend/src/container/MetricsExplorer/Inspect/__tests__/ExpandedView.test.tsx
  frontend/src/container/MetricsExplorer/Inspect/__tests__/GraphPopover.test.tsx
  frontend/src/container/MetricsExplorer/Inspect/__tests__/GraphView.test.tsx
  frontend/src/container/MetricsExplorer/Inspect/__tests__/Inspect.test.tsx
  frontend/src/container/MetricsExplorer/Inspect/__tests__/QueryBuilder.test.tsx
  frontend/src/container/MetricsExplorer/Inspect/__tests__/Stepper.test.tsx
  frontend/src/container/MetricsExplorer/Inspect/__tests__/TableView.test.tsx
  frontend/src/container/MetricsExplorer/Inspect/constants.ts
  frontend/src/container/MetricsExplorer/Inspect/types.ts
  frontend/src/container/MetricsExplorer/Inspect/useInspectMetrics.ts
  frontend/src/container/MetricsExplorer/Inspect/utils.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/MetricDetails.tsx
  frontend/src/container/MetricsExplorer/Summary/Summary.tsx
  frontend/src/container/MetricsExplorer/Summary/utils.tsx
  frontend/src/container/QueryBuilder/components/FilterLabel/FilterLabel.styled.ts
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.intefaces.ts
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
  frontend/src/hooks/metricsExplorer/useGetInspectMetricsDetails.ts
Labels: enhancement, docs not required

#7849 chore(signoz): remove deprecated signoz arguments
  Makefile
  deploy/docker-swarm/docker-compose.ha.yaml
  deploy/docker-swarm/docker-compose.yaml
  deploy/docker/docker-compose.ha.yaml
  deploy/docker/docker-compose.yaml
Labels: chore

#7844 fix(migration): fix cascading drops in sqlite
  ee/sqlstore/postgressqlstore/provider.go
  pkg/sqlmigration/029_drop_groups.go
  pkg/sqlstore/sqlitesqlstore/dialect.go
  pkg/sqlstore/sqlstore.go
  pkg/sqlstore/sqlstoretest/dialect.go
Labels: bug, safe-to-integrate, staging:next-ewe

#7851 feat(error): base setup for error handling in frontend
  frontend/package.json
  frontend/src/api/ErrorResponseHandlerV2.ts
  frontend/src/api/login/login.ts
  frontend/src/types/api/error.ts
  frontend/src/types/api/index.ts
  frontend/yarn.lock
Labels: enhancement

#7848 chore: add notification for upcoming migration for cloud region IN users
  frontend/src/container/Home/Home.tsx
Labels: chore

#7842 Feat trace ordering on the basis of span_count or Trace_duration
  pkg/query-service/app/traces/v4/query_builder.go
  pkg/query-service/app/traces/v4/query_builder_test.go
  pkg/query-service/constants/constants.go
Labels: enhancement, docs shipped, staging:evolving-elephant

#7864 fix(api-key): make the expires in human readable in api keys
  frontend/src/container/APIKeys/APIKeys.tsx
Labels: bug

#7873 fix: fix 'open in explorer' functionality in metrics explorer
  frontend/src/container/MetricsExplorer/MetricDetails/AllAttributes.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/MetricDetails.styles.scss
  frontend/src/container/MetricsExplorer/MetricDetails/MetricDetails.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/__tests__/AllAttributes.test.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/__tests__/MetricDetails.test.tsx
Labels: bug

#7862 chore: improve error handling and loading states in summary view of metrics explorer
  frontend/src/container/MetricsExplorer/Summary/MetricsTable.tsx
  frontend/src/container/MetricsExplorer/Summary/MetricsTreemap.tsx
  frontend/src/container/MetricsExplorer/Summary/Summary.tsx
  frontend/src/container/MetricsExplorer/Summary/__tests__/MetricsTable.test.tsx
  frontend/src/container/MetricsExplorer/Summary/__tests__/MetricsTreemap.test.tsx
Labels: chore

#7852 chore: change time series layout to grid in explorer view
  frontend/src/container/MetricsExplorer/Explorer/Explorer.styles.scss
Labels: chore

#7856 chore(error): update the channels module to use the new api errors
  frontend/src/api/ErrorResponseHandlerV2.ts
  frontend/src/api/channels/createEmail.ts
  frontend/src/api/channels/createMsTeams.ts
  frontend/src/api/channels/createOpsgenie.ts
  frontend/src/api/channels/createPager.ts
  frontend/src/api/channels/createSlack.ts
  frontend/src/api/channels/createWebhook.ts
  frontend/src/api/channels/delete.ts
  frontend/src/api/channels/editEmail.ts
  frontend/src/api/channels/editMsTeams.ts
  frontend/src/api/channels/editOpsgenie.ts
  frontend/src/api/channels/editPager.ts
  frontend/src/api/channels/editSlack.ts
  frontend/src/api/channels/editWebhook.ts
  frontend/src/api/channels/get.ts
  frontend/src/api/channels/getAll.ts
  frontend/src/api/channels/testEmail.ts
  frontend/src/api/channels/testMsTeams.ts
  frontend/src/api/channels/testOpsgenie.ts
  frontend/src/api/channels/testPager.ts
  frontend/src/api/channels/testSlack.ts
  frontend/src/api/channels/testWebhook.ts
  frontend/src/api/login/login.ts
  frontend/src/container/AllAlertChannels/AlertChannels.tsx
  frontend/src/container/AllAlertChannels/Delete.tsx
  frontend/src/container/AllAlertChannels/__tests__/AlertChannels.test.tsx
  frontend/src/container/AllAlertChannels/__tests__/AlertChannelsNormalUser.test.tsx
  frontend/src/container/AllAlertChannels/__tests__/CreateAlertChannel.test.tsx
  frontend/src/container/AllAlertChannels/index.tsx
  frontend/src/container/CreateAlertChannels/index.tsx
  frontend/src/container/EditAlertChannels/index.tsx
  frontend/src/container/FormAlertRules/BasicInfo.tsx
  frontend/src/container/FormAlertRules/ChannelSelect/index.tsx
  frontend/src/container/OrganizationSettings/DisplayName/index.tsx
  frontend/src/mocks-server/handlers.ts
  frontend/src/pages/ChannelsEdit/index.tsx
  frontend/src/types/api/channels/get.ts
  frontend/src/types/api/channels/getAll.ts
  frontend/src/types/api/error.ts
  frontend/src/types/api/index.ts
Labels: chore, safe-to-integrate, staging:next-ewe

#7878 fix: resolve typescript issues in metrics explorer
  frontend/.prettierignore
  frontend/src/components/DropDown/DropDown.styles.scss
  frontend/src/components/LearnMore/LearnMore.styles.scss
  frontend/src/components/TableRenderer/LabelColumn.styles.scss
  frontend/src/components/TextToolTip/TextToolTip.style.scss
  frontend/src/container/CloudIntegrationPage/HeroSection/components/AccountActions.style.scss
  frontend/src/container/CloudIntegrationPage/HeroSection/components/RemoveIntegrationAccount.scss
  frontend/src/container/Download/Download.styles.scss
  frontend/src/container/ExplorerOptions/ExplorerOptionsHideArea.styles.scss
  frontend/src/container/LogDetailedView/ContextView/ContextLogRenderer.styles.scss
  frontend/src/container/LogDetailedView/ContextView/ContextView.styles.scss
  frontend/src/container/LogDetailedView/InfraMetrics/InfraMetrics.styles.scss
  frontend/src/container/LogDetailedView/LogContext.styles.scss
  frontend/src/container/LogsSearchFilter/SearchFields/utils.ts
  frontend/src/container/MetricsApplication/Tabs/Overview/GraphControlsPanel/GraphControlsPanel.styles.scss
  frontend/src/container/MetricsApplication/TopOperationsTable.styles.scss
  frontend/src/container/MetricsExplorer/MetricDetails/AllAttributes.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/MetricDetails.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/__tests__/AllAttributes.test.tsx
  frontend/src/container/MetricsExplorer/Summary/Summary.tsx
  frontend/src/container/OnboardingV2Container/onboarding-configs/onboarding-config-with-links.json
  frontend/src/container/PipelinePage/PipelineListsView/AddNewPipeline/FormFields/FilterInput/styles.scss
  frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/styles.scss
  frontend/src/container/PipelinePage/PipelineListsView/Preview/LogsFilterPreview/styles.scss
  frontend/src/container/PipelinePage/PipelineListsView/Preview/PipelineProcessingPreview/components/PipelineSimulationResult/styles.scss
  frontend/src/container/PipelinePage/PipelineListsView/Preview/PipelineProcessingPreview/styles.scss
  frontend/src/container/PipelinePage/PipelineListsView/Preview/components/LogsList/styles.scss
  frontend/src/container/PipelinePage/PipelineListsView/Preview/components/PreviewIntervalSelector/components/LogsCountInInterval/styles.scss
  frontend/src/container/PipelinePage/PipelineListsView/Preview/components/PreviewIntervalSelector/styles.scss
  frontend/src/container/PipelinePage/PipelineListsView/Preview/components/SampleLogs/styles.scss
  frontend/src/container/PipelinePage/PipelineListsView/styles.scss
  frontend/src/container/QueryBuilder/components/AdditionalFiltersToggler/AdditionalFiltersToggler.styles.scss
  frontend/src/container/ResourceAttributeFilterV2/ResourceAttributesFilter.styles.scss
  frontend/src/modules/Servicemap/utils.ts
  frontend/src/pages/Logs/logs.styles.scss
Labels: bug

#7872 fix: added prismjs 1.30.0 in resolutions
  frontend/package.json
  frontend/yarn.lock
Labels: bug

#7880 fix(dashboards): fix lock/unlock functionality
  ee/query-service/app/api/dashboard.go
  pkg/query-service/app/dashboards/model.go
Labels: bug, safe-to-integrate, staging:next-ewe

#7885 chore(go): upgrade to 1.23
  .github/workflows/build-community.yaml
  .github/workflows/build-enterprise.yaml
  .github/workflows/build-staging.yaml
  .github/workflows/goci.yaml
  .github/workflows/gor-signoz-community.yaml
  .github/workflows/gor-signoz.yaml
  ee/query-service/Dockerfile.integration
  go.mod
  go.sum
Labels: chore, safe-to-integrate, staging:next-ewe

#7884 chore: persist one chart per query toggle across refreshes and exports
  frontend/src/container/MetricsExplorer/Explorer/Explorer.tsx
  frontend/src/container/MetricsExplorer/Explorer/__tests__/Explorer.test.tsx
Labels: chore

#7879 chore: improvements to the all attributes section in metric details
  frontend/src/container/MetricsExplorer/MetricDetails/AllAttributes.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/MetricDetails.styles.scss
  frontend/src/container/MetricsExplorer/MetricDetails/MetricDetails.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/__tests__/AllAttributes.test.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/types.ts
  frontend/src/container/MetricsExplorer/MetricDetails/utils.tsx
Labels: chore

#7808 feat(analytics): add analytics package
  conf/example.yaml
  go.mod
  go.sum
  pkg/analytics/analytics.go
  pkg/analytics/config.go
  pkg/analytics/noopanalytics/provider.go
  pkg/analytics/segmentanalytics/provider.go
  pkg/query-service/telemetry/telemetry.go
  pkg/types/analyticstypes/message.go
Labels: enhancement, docs not required, safe-to-integrate

#7863 fix: changed the keys in the default quick filters to actual keys in …
  pkg/signoz/provider.go
  pkg/sqlmigration/031_update_quick_filters.go
  pkg/types/quickfiltertypes/filter.go
Labels: bug, docs shipped, safe-to-integrate, staging:evolving-elephant

#7901 chore(frontend): update the api folder structure
  frontend/src/AppRoutes/Private.tsx
  frontend/src/api/index.ts
  frontend/src/api/organization/editOrg.ts
  frontend/src/api/organization/getOrganization.ts
  frontend/src/api/v1/factor_password/changeMyPassword.ts
  frontend/src/api/v1/factor_password/getResetPasswordToken.ts
  frontend/src/api/v1/factor_password/resetPassword.ts
  frontend/src/api/v1/invite/bulk/create.ts
  frontend/src/api/v1/invite/create.ts
  frontend/src/api/v1/invite/getPendingInvites.ts
  frontend/src/api/v1/invite/id/delete.ts
  frontend/src/api/v1/invite/id/get.ts
  frontend/src/api/v1/login/login.ts
  frontend/src/api/v1/login/loginPrecheck.ts
  frontend/src/api/v1/register/signup.ts
  frontend/src/api/v1/user/getOrgUser.ts
  frontend/src/api/v1/user/id/delete.ts
  frontend/src/api/v1/user/id/get.ts
  frontend/src/api/v1/user/id/getRoles.ts
  frontend/src/api/v1/user/id/update.ts
  frontend/src/api/v1/user/id/updateRole.ts
  frontend/src/api/v1/user/login.ts
  frontend/src/api/v1/user/preferences/get.ts
  frontend/src/api/v1/version/getLatestVersion.ts
  frontend/src/api/v1/version/getVersion.ts
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/Login/index.tsx
  frontend/src/container/MySettings/Password/index.tsx
  frontend/src/container/MySettings/UserInfo/index.tsx
  frontend/src/container/OnboardingQuestionaire/InviteTeamMembers/InviteTeamMembers.tsx
  frontend/src/container/OnboardingQuestionaire/OrgQuestions/OrgQuestions.tsx
  frontend/src/container/OnboardingV2Container/InviteTeamMembers/InviteTeamMembers.tsx
  frontend/src/container/OrganizationSettings/DisplayName/index.tsx
  frontend/src/container/OrganizationSettings/EditMembersDetails/index.tsx
  frontend/src/container/OrganizationSettings/InviteUserModal/InviteUserModal.tsx
  frontend/src/container/OrganizationSettings/Members/index.tsx
  frontend/src/container/OrganizationSettings/PendingInvitesContainer/index.tsx
  frontend/src/container/ResetPassword/ResetPassword.test.tsx
  frontend/src/container/ResetPassword/index.tsx
  frontend/src/hooks/user/useGetUser.ts
  frontend/src/pages/Login/index.tsx
  frontend/src/pages/ResetPassword/index.tsx
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/pages/SignUp/index.tsx
  frontend/src/providers/EventSource.tsx
Labels: chore

#7906 Fix: Update query_range api from v3 to v4 (Logs and Traces)
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/TimeSeriesView/index.tsx
  frontend/src/container/TracesExplorer/ListView/index.tsx
  frontend/src/container/TracesExplorer/TableView/index.tsx
  frontend/src/container/TracesExplorer/TracesView/index.tsx
  frontend/src/pages/TracesExplorer/__test__/TracesExplorer.test.tsx
Labels: bug

#7908 fix: OSS telemetry for the number of services
  pkg/query-service/app/http_handler.go
Labels: safe-to-test

#7918 fix: quick filter dependency injection issue in CE
  pkg/query-service/app/server.go
Labels: bug, backend, docs not required, staging:evolving-elephant

#7905 feat: user pilot reload
  frontend/src/AppRoutes/index.tsx
  frontend/src/components/UserpilotRouteTracker/UserpilotRouteTracker.test.tsx
  frontend/src/components/UserpilotRouteTracker/UserpilotRouteTracker.tsx
Labels: enhancement, docs not required, staging:many-herring

#7718 feat: S3 Sync (AWS Integrations)
  pkg/errors/errors.go
  pkg/query-service/app/cloudintegrations/constants.go
  pkg/query-service/app/cloudintegrations/controller.go
  pkg/query-service/app/cloudintegrations/controller_test.go
  pkg/query-service/app/cloudintegrations/model.go
  pkg/query-service/app/cloudintegrations/models.go
  pkg/query-service/app/cloudintegrations/serviceconfig_db.go
  pkg/query-service/app/cloudintegrations/services/definitions/aws/alb/assets/dashboards/overview.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/alb/assets/dashboards/overview.png
  pkg/query-service/app/cloudintegrations/services/definitions/aws/alb/icon.svg
  pkg/query-service/app/cloudintegrations/services/definitions/aws/alb/integration.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/alb/overview.md
  pkg/query-service/app/cloudintegrations/services/definitions/aws/api-gateway/assets/dashboards/overview.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/api-gateway/assets/dashboards/overview.png
  pkg/query-service/app/cloudintegrations/services/definitions/aws/api-gateway/icon.svg
  pkg/query-service/app/cloudintegrations/services/definitions/aws/api-gateway/integration.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/api-gateway/overview.md
  pkg/query-service/app/cloudintegrations/services/definitions/aws/ec2/assets/dashboards/overview.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/ec2/assets/dashboards/overview.png
  pkg/query-service/app/cloudintegrations/services/definitions/aws/ec2/icon.svg
  pkg/query-service/app/cloudintegrations/services/definitions/aws/ec2/integration.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/ec2/overview.md
  pkg/query-service/app/cloudintegrations/services/definitions/aws/lambda/assets/dashboards/overview.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/lambda/assets/dashboards/overview.png
  pkg/query-service/app/cloudintegrations/services/definitions/aws/lambda/icon.svg
  pkg/query-service/app/cloudintegrations/services/definitions/aws/lambda/integration.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/lambda/overview.md
  pkg/query-service/app/cloudintegrations/services/definitions/aws/msk/assets/dashboards/overview.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/msk/assets/dashboards/overview.png
  pkg/query-service/app/cloudintegrations/services/definitions/aws/msk/icon.svg
  pkg/query-service/app/cloudintegrations/services/definitions/aws/msk/integration.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/msk/overview.md
  pkg/query-service/app/cloudintegrations/services/definitions/aws/rds/assets/dashboards/overview.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/rds/assets/dashboards/overview.png
  pkg/query-service/app/cloudintegrations/services/definitions/aws/rds/icon.svg
  pkg/query-service/app/cloudintegrations/services/definitions/aws/rds/integration.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/rds/overview.md
  pkg/query-service/app/cloudintegrations/services/definitions/aws/s3sync/icon.svg
  pkg/query-service/app/cloudintegrations/services/definitions/aws/s3sync/integration.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/s3sync/overview.md
  pkg/query-service/app/cloudintegrations/services/models.go
  pkg/query-service/app/cloudintegrations/services/services.go
  pkg/query-service/app/cloudintegrations/services/services_test.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/tests/integration/signoz_cloud_integrations_test.go
  pkg/types/integration.go
Labels: enhancement, docs shipped, staging:civil-eagle

#7936 chore(go): add go-deps workflow
  .github/workflows/goci.yaml
  go.mod
  go.sum
Labels: chore

#7938 chore: remove unnecessary AWS dependency
  go.mod
  pkg/query-service/app/cloudintegrations/constants.go
Labels: chore

#7815 feat: external services co relation and url sharing
  frontend/public/locales/en/titles.json
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/AllEndPoints.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/DomainDetails.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/EndPointDetails.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/TopErrors.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/MetricOverTimeGraph.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/StatusCodeBarCharts.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainList.tsx
  frontend/src/container/ApiMonitoring/Explorer/Explorer.tsx
  frontend/src/container/ApiMonitoring/__tests__/AllEndPoints.test.tsx
  frontend/src/container/ApiMonitoring/__tests__/EndPointDetails.test.tsx
  frontend/src/container/ApiMonitoring/__tests__/queryParams.test.tsx
  frontend/src/container/ApiMonitoring/queryParams.ts
  frontend/src/container/ApiMonitoring/utils.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCard/types.ts
  frontend/src/container/GridCardLayout/GridCard/utils.ts
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/GraphControlsPanel/GraphControlsPanel.styles.scss
  frontend/src/container/MetricsApplication/Tabs/Overview/GraphControlsPanel/GraphControlsPanel.tsx
  frontend/src/container/MetricsApplication/Tabs/util.ts
  frontend/src/container/SideNav/menuItems.tsx
  frontend/src/pages/MessagingQueues/MessagingQueuesUtils.ts
Labels: enhancement, docs shipped

#7541 feat: added dynamic variables creation flow
  frontend/src/api/dynamicVariables/getFieldKeys.ts
  frontend/src/api/dynamicVariables/getFieldValues.ts
  frontend/src/components/NewSelect/types.ts
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/DynamicVariable/DynamicVariable.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/DynamicVariable/DynamicVariable.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx
  frontend/src/hooks/dynamicVariables/useGetFieldKeys.ts
  frontend/src/hooks/dynamicVariables/useGetFieldValues.ts
  frontend/src/types/api/dashboard/getAll.ts
  frontend/src/types/api/dynamicVariables/getFieldKeys.ts
  frontend/src/types/api/dynamicVariables/getFieldValues.ts
Labels: enhancement, docs required

#7755 feat: added dynamic variable to the dashboard details
  frontend/src/api/dynamicVariables/getFieldValues.ts
  frontend/src/components/NewSelect/CustomMultiSelect.tsx
  frontend/src/components/NewSelect/CustomSelect.tsx
  frontend/src/components/NewSelect/styles.scss
  frontend/src/components/NewSelect/types.ts
  frontend/src/components/NewSelect/utils.ts
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/DynamicVariable/DynamicVariable.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/DynamicVariable/__test__/DynamicVariable.test.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.styles.scss
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DynamicVariableSelection.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/__test__/DynamicVariableSelection.test.tsx
  frontend/src/container/NewDashboard/utils.ts
  frontend/src/hooks/dynamicVariables/useGetFieldValues.ts
  frontend/src/lib/dashbaordVariables/getDashboardVariables.ts
  frontend/src/types/api/dashboard/getAll.ts
  frontend/src/types/api/dynamicVariables/getFieldValues.ts
Labels: enhancement, staging:devoted-reindeer

#7944 feat: added variable in url and made dashboard sync around that and sharable
  frontend/src/constants/query.ts
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
  frontend/src/hooks/dashboard/__test__/useVariablesFromUrl.test.tsx
  frontend/src/hooks/dashboard/useVariablesFromUrl.tsx
  frontend/src/providers/Dashboard/Dashboard.tsx
  frontend/src/providers/Dashboard/initializeDefaultVariables.ts
Labels: enhancement

#7949 fix: refresh token to access token
  ee/modules/user/impluser/handler.go
Labels: bug, staging:next-ewe

#7807 chore: less strict context for fetching field values
  pkg/telemetrymetadata/condition_builder.go
  pkg/telemetrymetadata/condition_builder_test.go
  pkg/telemetrymetadata/metadata.go
  pkg/types/telemetrytypes/field_context.go
  pkg/types/telemetrytypes/field_datatype.go
Labels: chore

#7897 feat: added variable description icon and details on tooltip
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.styles.scss
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
Labels: enhancement, docs not required

#7896 feat: added user role restriction on crud for planned downtime feat
  frontend/src/container/PlannedDowntime/PlannedDowntimeList.tsx
Labels: enhancement, docs not required

#7955 chore: add fieldmapper implementation
  pkg/errors/errors.go
  pkg/parser/grammar/where_clause_visitor.go
  pkg/parser/grammar/where_clause_visitor_test.go
  pkg/telemetrylogs/condition_builder.go
  pkg/telemetrylogs/condition_builder_test.go
  pkg/telemetrylogs/field_mapper.go
  pkg/telemetrylogs/field_mapper_test.go
  pkg/telemetrylogs/json.go
  pkg/telemetrymetadata/condition_builder.go
  pkg/telemetrymetadata/condition_builder_test.go
  pkg/telemetrymetadata/field_mapper.go
  pkg/telemetrymetadata/field_mapper_test.go
  pkg/telemetrymetadata/metadata.go
  pkg/telemetrymetadata/stmt_parse.go
  pkg/telemetrytraces/condition_builder.go
  pkg/telemetrytraces/condition_builder_test.go
  pkg/telemetrytraces/field_mapper.go
  pkg/telemetrytraces/field_mapper_test.go
  pkg/types/querybuildertypes/querybuildertypesv5/qb.go
  pkg/types/querybuildertypes/querybuildertypesv5/query.go
  pkg/types/telemetrytypes/maybe_typo.go
Labels: chore

#7956 chore: move visitor impl out of generated files
  pkg/parser/grammar/where_clause_visitor_test.go
  pkg/querybuilder/query_to_keys.go
  pkg/querybuilder/query_to_keys_test.go
  pkg/querybuilder/where_clause_visitor.go
Labels: chore

#7960 chore(savedview|apdex|dashboard): create modules and handlers
  ee/query-service/app/api/api.go
  ee/query-service/app/api/dashboard.go
  ee/query-service/app/server.go
  ee/query-service/dao/factory.go
  ee/query-service/dao/interface.go
  ee/query-service/dao/sqlite/domain.go
  ee/query-service/dao/sqlite/modelDao.go
  ee/query-service/dao/sqlite/pat.go
  pkg/modules/apdex/apdex.go
  pkg/modules/apdex/implapdex/handler.go
  pkg/modules/apdex/implapdex/module.go
  pkg/modules/dashboard/dashboard.go
  pkg/modules/dashboard/impldashboard/handler.go
  pkg/modules/dashboard/impldashboard/module.go
  pkg/modules/savedview/implsavedview/handler.go
  pkg/modules/savedview/implsavedview/module.go
  pkg/modules/savedview/savedview.go
  pkg/query-service/app/apdex.go
  pkg/query-service/app/cloudintegrations/controller.go
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/integrations/controller.go
  pkg/query-service/app/integrations/manager.go
  pkg/query-service/app/metricsexplorer/summary.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/server.go
  pkg/query-service/dao/factory.go
  pkg/query-service/dao/interface.go
  pkg/query-service/dao/sqlite/connection.go
  pkg/query-service/dao/sqlite/rbac.go
  pkg/query-service/rules/manager.go
  pkg/query-service/telemetry/dashboard.go
  pkg/query-service/telemetry/rule.go
  pkg/query-service/telemetry/saved_view.go
  pkg/query-service/telemetry/telemetry.go
  pkg/query-service/tests/integration/filter_suggestions_test.go
  pkg/query-service/tests/integration/logparsingpipeline_test.go
  pkg/query-service/tests/integration/signoz_cloud_integrations_test.go
  pkg/query-service/tests/integration/signoz_integrations_test.go
  pkg/query-service/utils/testutils.go
  pkg/ruler/rulestore/sqlrulestore/rule.go
  pkg/signoz/handler.go
  pkg/signoz/module.go
  pkg/types/ruletypes/rule.go
Labels: chore, safe-to-integrate, staging:next-ewe

#7894 feat: removed allow clear icon from when ALL option is selected
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
Labels: enhancement, docs not required

#7965 fix: cover the title as reactNode case for useGetResolvedText
  frontend/src/hooks/dashboard/__test__/useGetResolvedText.test.tsx
  frontend/src/hooks/dashboard/useGetResolvedText.tsx
Labels: bug

#7950 Custom Quick FIlters: UI fixes and Announcement Tooltip
  frontend/src/api/utils.ts
  frontend/src/components/QuickFilters/FilterRenderers/Checkbox/Checkbox.tsx
  frontend/src/components/QuickFilters/QuickFilters.styles.scss
  frontend/src/components/QuickFilters/QuickFilters.tsx
  frontend/src/components/QuickFilters/QuickFiltersSettings/AddedFilters.styles.scss
  frontend/src/components/QuickFilters/QuickFiltersSettings/AddedFilters.tsx
  frontend/src/components/QuickFilters/QuickFiltersSettings/AnnouncementTooltip/AnnouncementTooltip.styles.scss
  frontend/src/components/QuickFilters/QuickFiltersSettings/AnnouncementTooltip/index.tsx
  frontend/src/components/QuickFilters/QuickFiltersSettings/OtherFilters.styles.scss
  frontend/src/components/QuickFilters/QuickFiltersSettings/OtherFilters.tsx
  frontend/src/components/QuickFilters/QuickFiltersSettings/QuickFiltersSettings.styles.scss
  frontend/src/components/QuickFilters/types.ts
  frontend/src/constants/localStorage.ts
Labels: bug

#7939 Custom quick filter: Other Filters | Search integration
  frontend/package.json
  frontend/src/api/quickFilters/getCustomFilters.ts
  frontend/src/api/quickFilters/updateCustomFilters.ts
  frontend/src/api/utils.ts
  frontend/src/components/QuickFilters/FilterRenderers/Checkbox/Checkbox.tsx
  frontend/src/components/QuickFilters/QuickFilters.styles.scss
  frontend/src/components/QuickFilters/QuickFilters.tsx
  frontend/src/components/QuickFilters/QuickFiltersSettings/AddedFilters.styles.scss
  frontend/src/components/QuickFilters/QuickFiltersSettings/AddedFilters.tsx
  frontend/src/components/QuickFilters/QuickFiltersSettings/AnnouncementTooltip/AnnouncementTooltip.styles.scss
  frontend/src/components/QuickFilters/QuickFiltersSettings/AnnouncementTooltip/index.tsx
  frontend/src/components/QuickFilters/QuickFiltersSettings/OtherFilters.tsx
  frontend/src/components/QuickFilters/QuickFiltersSettings/QuickFiltersSettings.styles.scss
  frontend/src/components/QuickFilters/QuickFiltersSettings/QuickFiltersSettings.tsx
  frontend/src/components/QuickFilters/QuickFiltersSettings/constants.ts
  frontend/src/components/QuickFilters/QuickFiltersSettings/hooks/useQuickFilterSettings.tsx
  frontend/src/components/QuickFilters/hooks/useFilterConfig.tsx
  frontend/src/components/QuickFilters/types.ts
  frontend/src/components/QuickFilters/utils.tsx
  frontend/src/constants/localStorage.ts
  frontend/src/types/api/quickFilters/updateCustomFilters.ts
  frontend/yarn.lock
Labels: frontend, events-pod

#7966 fix(apm): update the apdex to latest response structure
  frontend/src/api/metrics/ApDex/getApDexSettings.ts
  frontend/src/api/v1/settings/apdex/services/get.ts
  frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/index.tsx
  frontend/src/hooks/apDex/useGetApDexSettings.ts
  frontend/src/pages/MetricsApplication/ApDex/ApDexApplication.tsx
  frontend/src/pages/MetricsApplication/ApDex/__mock__/axiosResponseMockThresholdData.ts
  frontend/src/pages/MetricsApplication/ApDex/types.ts
  frontend/src/types/api/metrics/getApDex.ts
Labels: bug, staging:next-ewe

#7975 fix(analytics): fix heartbeat event
  pkg/query-service/telemetry/user.go
Labels: bug

#7942 chore: persist the filters and time selection, modal open state in summary view
  frontend/src/container/InfraMonitoringK8s/commonUtils.tsx
  frontend/src/container/MetricsExplorer/Summary/MetricNameSearch.tsx
  frontend/src/container/MetricsExplorer/Summary/MetricTypeSearch.tsx
  frontend/src/container/MetricsExplorer/Summary/MetricsSearch.tsx
  frontend/src/container/MetricsExplorer/Summary/MetricsTreemap.tsx
  frontend/src/container/MetricsExplorer/Summary/Summary.styles.scss
  frontend/src/container/MetricsExplorer/Summary/Summary.tsx
  frontend/src/container/MetricsExplorer/Summary/__tests__/MetricsTable.test.tsx
  frontend/src/container/MetricsExplorer/Summary/__tests__/MetricsTreemap.test.tsx
  frontend/src/container/MetricsExplorer/Summary/__tests__/Summary.test.tsx
  frontend/src/container/MetricsExplorer/Summary/constants.ts
  frontend/src/container/MetricsExplorer/Summary/types.ts
Labels: chore

#7840 feat: introducing ECS + SQS integration
  pkg/query-service/app/cloudintegrations/services/definitions/aws/ecs/assets/dashboards/overview.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/ecs/assets/dashboards/overview.png
  pkg/query-service/app/cloudintegrations/services/definitions/aws/ecs/icon.svg
  pkg/query-service/app/cloudintegrations/services/definitions/aws/ecs/integration.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/ecs/overview.md
  pkg/query-service/app/cloudintegrations/services/definitions/aws/sqs/assets/dashboards/overview.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/sqs/assets/dashboards/overview.png
  pkg/query-service/app/cloudintegrations/services/definitions/aws/sqs/icon.svg
  pkg/query-service/app/cloudintegrations/services/definitions/aws/sqs/integration.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/sqs/overview.md
Labels: enhancement, docs required, staging:civil-eagle

#7638 chore: add analytics events for trace funnels
  frontend/src/pages/TraceDetailV2/index.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/StepsContent.tsx
  frontend/src/pages/TracesFunnels/FunnelContext.tsx
  frontend/src/pages/TracesFunnels/components/CreateFunnel/CreateFunnel.tsx
  frontend/src/pages/TracesModulePage/TracesModulePage.tsx
Labels: chore

#7978 feat(7274): added dot metrics migration for messaging queue
  frontend/src/pages/MessagingQueues/MQDetails/MetricPage/MetricColumnGraphs.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MetricPage/MetricPage.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MetricPage/MetricPageUtil.ts
  frontend/src/pages/MessagingQueues/MQGraph/MQConfigOptions.tsx
  frontend/src/pages/MessagingQueues/MQGraph/useGetAllConfigOptions.ts
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/integrations/messagingQueues/kafka/translator.go
Labels: enhancement

#7886 fix: AWS integration bugfixes
  frontend/src/container/CloudIntegrationPage/Header/Header.styles.scss
  frontend/src/container/CloudIntegrationPage/Header/Header.tsx
  frontend/src/container/CloudIntegrationPage/HeroSection/components/AccountSettingsModal.tsx
Labels: bug

#7957 feat: added entry point operations api for the service overview page
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/interfaces/interface.go
Labels: enhancement, backend, docs shipped, staging:evolving-elephant

#7972 chore: add aggregation expr rewriter and exhaustive tests for logs filter
  grammar/FilterQuery.g4
  pkg/parser/grammar/FilterQuery.interp
  pkg/parser/grammar/FilterQueryLexer.interp
  pkg/parser/grammar/filterquery_lexer.go
  pkg/parser/grammar/filterquery_parser.go
  pkg/querybuilder/agg_funcs.go
  pkg/querybuilder/agg_rewrite.go
  pkg/querybuilder/filter_error_listener.go
  pkg/querybuilder/where_clause_visitor.go
  pkg/telemetrylogs/condition_builder.go
  pkg/telemetrylogs/condition_builder_test.go
  pkg/telemetrylogs/const.go
  pkg/telemetrylogs/json.go
  pkg/telemetrymetadata/condition_builder.go
  pkg/telemetrytests/agg_rewrite_test.go
  pkg/telemetrytests/filter_expr_logs_body_json_test.go
  pkg/telemetrytests/filter_expr_logs_test.go
  pkg/telemetrytests/test_data.go
  pkg/telemetrytraces/condition_builder.go
  pkg/telemetrytraces/condition_builder_test.go
  pkg/telemetrytraces/const.go
  pkg/types/querybuildertypes/querybuildertypesv5/builder_elements.go
  pkg/types/telemetrytypes/field.go
Labels: chore

#7874 feat: add support for S3 region buckets syncing
  frontend/src/container/CloudIntegrationPage/ServicesSection/ConfigureServiceModal.tsx
  frontend/src/container/CloudIntegrationPage/ServicesSection/S3BucketsSelector.tsx
  frontend/src/container/CloudIntegrationPage/ServicesSection/__tests__/ConfigureServiceModalS3Sync.test.tsx
  frontend/src/container/CloudIntegrationPage/ServicesSection/__tests__/mockData.ts
  frontend/src/container/CloudIntegrationPage/ServicesSection/__tests__/utils.tsx
  frontend/src/container/CloudIntegrationPage/ServicesSection/types.ts
  frontend/src/hooks/integration/aws/useUpdateServiceConfig.ts
Labels: enhancement, docs required, staging:civil-eagle

#7990 feat: show pricing update banner in home page
  frontend/src/constants/localStorage.ts
  frontend/src/container/Home/Home.styles.scss
  frontend/src/container/Home/Home.tsx
  frontend/src/mocks-server/__mockdata__/billing.ts
Labels: enhancement, docs not required

#7968 feat: add support for request integrations in aws integrations page
  frontend/src/container/CloudIntegrationPage/CloudIntegrationPage.tsx
  frontend/src/container/CloudIntegrationPage/__tests__/RequestIntegration.test.tsx
  frontend/src/pages/Integrations/Integrations.styles.scss
  frontend/src/pages/Integrations/RequestIntegrationBtn.tsx
  frontend/src/pages/IntegrationsModulePage/IntegrationsModulePage.styles.scss
Labels: enhancement, frontend, docs required

#7987 Fix: exists clause in logs QB
  pkg/query-service/app/logs/v4/json_filter.go
  pkg/query-service/app/logs/v4/json_filter_test.go
  pkg/query-service/app/logs/v4/query_builder.go
  pkg/query-service/app/logs/v4/query_builder_test.go
  pkg/query-service/app/resource/resource_query_builder.go
  pkg/query-service/app/resource/resource_query_builder_test.go
Labels: bug

#7997 fix: changed the get request access from admin to view
  pkg/query-service/app/http_handler.go
Labels: bug, backend, events-pod, docs not required

#7959 chore(api-key): refactor API key
  ee/http/middleware/pat.go
  ee/modules/user/impluser/handler.go
  ee/modules/user/impluser/module.go
  ee/query-service/app/api/api.go
  ee/query-service/app/api/cloudIntegrations.go
  ee/query-service/app/api/pat.go
  ee/query-service/dao/interface.go
  ee/query-service/dao/sqlite/pat.go
  ee/query-service/model/pat.go
  ee/sqlstore/postgressqlstore/dialect.go
  ee/types/personal_access_token.go
  pkg/modules/user/impluser/handler.go
  pkg/modules/user/impluser/module.go
  pkg/modules/user/impluser/store.go
  pkg/modules/user/user.go
  pkg/query-service/utils/testutils.go
  pkg/signoz/provider.go
  pkg/sqlmigration/033_api_keys.go
  pkg/sqlmigration/sqlmigration.go
  pkg/sqlstore/sqlitesqlstore/dialect.go
  pkg/types/factor_api_key.go
  pkg/types/user.go
  tests/integration/src/bootstrap/d_apikey.py
Labels: chore, safe-to-integrate, staging:actual-guppy

#8011 fix(cache): use sensible defaults for caching
  pkg/cache/config.go
  pkg/cache/memorycache/provider.go
Labels: chore

#7993 feat(emailing): add smtp and emailing
  conf/example.yaml
  ee/modules/user/impluser/module.go
  ee/query-service/dao/sqlite/domain.go
  ee/query-service/dao/sqlite/modelDao.go
  ee/query-service/main.go
  pkg/emailing/config.go
  pkg/emailing/emailing.go
  pkg/emailing/noopemailing/provider.go
  pkg/emailing/smtpemailing/provider.go
  pkg/emailing/templatestore/filetemplatestore/store.go
  pkg/modules/user/impluser/module.go
  pkg/query-service/app/cloudintegrations/controller_test.go
  pkg/query-service/app/integrations/manager_test.go
  pkg/query-service/constants/constants.go
  pkg/query-service/main.go
  pkg/query-service/tests/integration/filter_suggestions_test.go
  pkg/query-service/tests/integration/logparsingpipeline_test.go
  pkg/query-service/tests/integration/signoz_cloud_integrations_test.go
  pkg/query-service/tests/integration/signoz_integrations_test.go
  pkg/query-service/utils/smtpService/smtp.go
  pkg/signoz/config.go
  pkg/signoz/provider.go
  pkg/signoz/provider_test.go
  pkg/signoz/signoz.go
  pkg/smtp/client/auth.go
  pkg/smtp/client/content.go
  pkg/smtp/client/option.go
  pkg/smtp/client/smtp.go
  pkg/types/emailtypes/template.go
  templates/email/invitation_email.gotmpl
Labels: enhancement, docs required, safe-to-integrate, staging:next-ewe

#7999 fix: time shift not working with fill gaps
  pkg/query-service/postprocess/gaps.go
  pkg/query-service/postprocess/gaps_test.go
Labels: bug

#7923 feat: ElastiCache AWS Integration
  pkg/query-service/app/cloudintegrations/services/definitions/aws/elasticache/assets/dashboards/redis_overview.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/elasticache/assets/dashboards/redis_overview.png
  pkg/query-service/app/cloudintegrations/services/definitions/aws/elasticache/icon.svg
  pkg/query-service/app/cloudintegrations/services/definitions/aws/elasticache/integration.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/elasticache/overview.md
  pkg/query-service/app/cloudintegrations/services/definitions/aws/lambda/integration.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/msk/integration.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/rds/integration.json
Labels: enhancement, backend, docs shipped, staging:civil-eagle

#8013 fix: allow non expireable API key
  ee/http/middleware/api_key.go
  ee/http/middleware/pat.go
  ee/modules/user/impluser/handler.go
  ee/query-service/app/server.go
  frontend/src/api/APIKeys/createAPIKey.ts
  frontend/src/api/APIKeys/deleteAPIKey.ts
  frontend/src/api/APIKeys/getAPIKey.ts
  frontend/src/api/APIKeys/getAllAPIKeys.ts
  frontend/src/api/APIKeys/updateAPIKey.ts
  frontend/src/api/v1/pats/create.ts
  frontend/src/api/v1/pats/delete.ts
  frontend/src/api/v1/pats/list.ts
  frontend/src/api/v1/pats/update.ts
  frontend/src/container/APIKeys/APIKeys.tsx
  frontend/src/hooks/APIKeys/useGetAllAPIKeys.ts
  frontend/src/types/api/pat/types.ts
  pkg/types/factor_api_key.go
Labels: bug, staging:actual-guppy

#8019 chore: remove telemetrytests package and add generic type for aggregation
  pkg/telemetrylogs/filter_expr_logs_body_json_test.go
  pkg/telemetrylogs/filter_expr_logs_test.go
  pkg/telemetrylogs/test_data.go
  pkg/telemetrytests/agg_rewrite_test.go
  pkg/types/querybuildertypes/querybuildertypesv5/builder_elements.go
  pkg/types/querybuildertypes/querybuildertypesv5/builder_query.go
  pkg/types/querybuildertypes/querybuildertypesv5/qb.go
  pkg/types/querybuildertypes/querybuildertypesv5/req.go
  pkg/types/querybuildertypes/querybuildertypesv5/req_test.go
  pkg/types/telemetrytypes/telemetrytypestest/metadata_store_stub.go
Labels: chore

#8022 chore(go-lint): enable go-lint
  .github/CODEOWNERS
  .golangci.yml
  ee/modules/user/impluser/handler.go
  pkg/apis/fields/parse.go
  pkg/cache/cachetest/provider.go
  pkg/modules/user/impluser/handler.go
  pkg/modules/user/impluser/module.go
  pkg/modules/user/impluser/store.go
  pkg/sqlmigration/011_modify_datetime.go
  pkg/sqlmigration/012_modify_org_domain.go
  pkg/sqlmigration/013_update_organization.go
  pkg/sqlmigration/014_add_alertmanager.go
  pkg/sqlmigration/015_update_dashboards_savedviews.go
  pkg/sqlmigration/016_pat_org_domains.go
  pkg/sqlmigration/017_update_pipelines.go
  pkg/sqlmigration/018_drop_licenses_sites.go
  pkg/sqlmigration/019_update_invites.go
  pkg/sqlmigration/020_pat_update.go
  pkg/sqlmigration/021_update_alertmanager.go
  pkg/sqlmigration/022_update_preferences.go
  pkg/sqlmigration/023_update_apdex_ttl.go
  pkg/sqlmigration/024_update_reset_password.go
  pkg/sqlmigration/026_update_integrations.go
  pkg/sqlmigration/027_update_rules.go
  pkg/sqlmigration/028_update_organizations.go
  pkg/sqlmigration/029_drop_groups.go
  pkg/sqlmigration/030_create_quick_filters.go
  pkg/sqlmigration/031_update_quick_filters.go
  pkg/sqlmigration/032_auth_refactor.go
  pkg/sqlmigration/033_api_keys.go
  pkg/types/pipelinetypes/pipeline.go
  pkg/types/ssotypes/saml.go
Labels: chore, safe-to-integrate

#7996 feat: Introducing SNS integration (AWS)
  pkg/query-service/app/cloudintegrations/services/definitions/aws/sns/assets/dashboards/overview.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/sns/assets/dashboards/overview.png
  pkg/query-service/app/cloudintegrations/services/definitions/aws/sns/icon.svg
  pkg/query-service/app/cloudintegrations/services/definitions/aws/sns/integration.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/sns/overview.md
Labels: enhancement, events-pod, docs shipped

#8031 fix(quickfilter): fix injection of quickfilter
  ee/query-service/app/api/api.go
  pkg/modules/quickfilter/implquickfilter/handler.go
  pkg/modules/quickfilter/implquickfilter/module.go
  pkg/modules/quickfilter/implquickfilter/store.go
  pkg/modules/quickfilter/quickfilter.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/auth/auth.go
  pkg/query-service/tests/integration/filter_suggestions_test.go
  pkg/query-service/tests/integration/logparsingpipeline_test.go
  pkg/query-service/tests/integration/signoz_cloud_integrations_test.go
  pkg/query-service/tests/integration/signoz_integrations_test.go
  pkg/signoz/handler.go
  pkg/signoz/module.go
  pkg/types/quickfiltertypes/filter.go
Labels: bug, safe-to-integrate

#8033 feat(signoz): compile time check for dependency injection
  pkg/emailing/emailingtest/provider.go
  pkg/signoz/handler_test.go
  pkg/signoz/module_test.go
Labels: enhancement, safe-to-integrate

#8030 feat(user): support sso and api key
  ee/modules/user/impluser/handler.go
  ee/modules/user/impluser/module.go
  ee/modules/user/impluser/store.go
  ee/query-service/app/api/api.go
  ee/query-service/app/api/auth.go
  ee/query-service/app/api/domains.go
  ee/query-service/app/server.go
  ee/query-service/constants/constants.go
  ee/query-service/dao/interface.go
  ee/query-service/dao/sqlite/domain.go
  ee/query-service/dao/sqlite/modelDao.go
  ee/query-service/main.go
  ee/query-service/usage/manager.go
  frontend/src/api/SAML/deleteDomain.ts
  frontend/src/api/SAML/listAllDomain.ts
  frontend/src/api/SAML/postDomain.ts
  frontend/src/api/SAML/updateDomain.ts
  frontend/src/api/v1/domains/create.ts
  frontend/src/api/v1/domains/delete.ts
  frontend/src/api/v1/domains/list.ts
  frontend/src/api/v1/domains/update.ts
  frontend/src/components/HostMetricsDetail/HostMetricsLogs/__tests__/HostMetricsLogs.test.tsx
  frontend/src/container/LogsExplorerViews/tests/LogsExplorerPagination.test.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/AddDomain/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/Create/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/index.tsx
  frontend/src/container/OrganizationSettings/index.tsx
  frontend/src/pages/Settings/utils.ts
  frontend/src/types/api/SAML/deleteDomain.ts
  frontend/src/types/api/SAML/listDomain.ts
  frontend/src/types/api/SAML/postDomain.ts
  frontend/src/types/api/SAML/updateDomain.ts
  pkg/http/middleware/api_key.go
  pkg/modules/user/impluser/handler.go
  pkg/modules/user/impluser/module.go
  pkg/modules/user/impluser/store.go
  pkg/modules/user/user.go
  pkg/query-service/app/cloudintegrations/controller_test.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/integrations/manager_test.go
  pkg/query-service/app/server.go
  pkg/query-service/constants/constants.go
  pkg/query-service/main.go
  pkg/query-service/tests/integration/filter_suggestions_test.go
  pkg/query-service/tests/integration/logparsingpipeline_test.go
  pkg/query-service/tests/integration/signoz_cloud_integrations_test.go
  pkg/query-service/tests/integration/signoz_integrations_test.go
  pkg/signoz/handler.go
  pkg/signoz/handler_test.go
  pkg/signoz/module.go
  pkg/signoz/module_test.go
  pkg/signoz/signoz.go
  pkg/types/user.go
Labels: enhancement, safe-to-integrate, staging:next-ewe

#8038 feat(error): build generic error component
  frontend/src/AppRoutes/index.tsx
  frontend/src/assets/Error.tsx
  frontend/src/components/ErrorModal/ErrorModal.styles.scss
  frontend/src/components/ErrorModal/ErrorModal.test.tsx
  frontend/src/components/ErrorModal/ErrorModal.tsx
  frontend/src/components/ErrorModal/components/ErrorContent.styles.scss
  frontend/src/components/ErrorModal/components/ErrorContent.tsx
  frontend/src/container/AllAlertChannels/__tests__/CreateAlertChannel.test.tsx
  frontend/src/container/CreateAlertChannels/index.tsx
  frontend/src/periscope/components/KeyValueLabel/KeyValueLabel.tsx
  frontend/src/providers/App/App.tsx
  frontend/src/providers/App/types.ts
  frontend/src/providers/ErrorModalProvider.tsx
  frontend/src/tests/test-utils.tsx
Labels: enhancement, staging:wealthy-pelican

#8023 feat: added custom stepIntervals to bar chart for better visibilty
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/__tests__/utils.test.ts
  frontend/src/container/GridCardLayout/utils.ts
  frontend/src/container/NewWidget/index.tsx
  frontend/src/hooks/queryBuilder/useGetQueryRange.ts
  frontend/src/lib/dashboard/getQueryResults.ts
Labels: enhancement, docs not required

#8012 feat: Introducing DynamoDB integration
  pkg/query-service/app/cloudintegrations/services/definitions/aws/dynamodb/assets/dashboards/overview.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/dynamodb/assets/dashboards/overview.png
  pkg/query-service/app/cloudintegrations/services/definitions/aws/dynamodb/icon.svg
  pkg/query-service/app/cloudintegrations/services/definitions/aws/dynamodb/integration.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/dynamodb/overview.md
Labels: enhancement, docs shipped, staging:civil-eagle

#8063 feat: allow custom color pallete in panel for legends
  frontend/src/container/NewWidget/LeftContainer/index.tsx
  frontend/src/container/NewWidget/RightContainer/LegendColors/LegendColors.styles.scss
  frontend/src/container/NewWidget/RightContainer/LegendColors/LegendColors.tsx
  frontend/src/container/NewWidget/RightContainer/RightContainer.styles.scss
  frontend/src/container/NewWidget/RightContainer/constants.ts
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/NewWidget/types.ts
  frontend/src/container/PanelWrapper/PiePanelWrapper.tsx
  frontend/src/container/PanelWrapper/UplotPanelWrapper.tsx
  frontend/src/lib/uPlotLib/utils/getSeriesData.ts
  frontend/src/types/api/dashboard/getAll.ts
Labels: enhancement, docs not required

#8024 chore: add logs statement builder base
  pkg/telemetrylogs/filter_compiler.go
  pkg/telemetrylogs/statement_builder.go
  pkg/telemetrylogs/stmt_builder_test.go
Labels: chore

#8028 chore: add querier base implementation
  pkg/querier/builder_query.go
  pkg/querier/clickhouse_query.go
  pkg/querier/consume.go
  pkg/querier/list_range.go
  pkg/querier/promql_query.go
  pkg/querier/querier.go
  pkg/querybuilder/agg_funcs.go
  pkg/querybuilder/agg_rewrite.go
  pkg/querybuilder/cte.go
  pkg/querybuilder/fallback_expr.go
  pkg/querybuilder/resourcefilter/filter_compiler.go
  pkg/querybuilder/resourcefilter/statement_builder.go
  pkg/querybuilder/time.go
  pkg/telemetrylogs/condition_builder.go
  pkg/telemetrylogs/condition_builder_test.go
  pkg/telemetrylogs/statement_builder.go
  pkg/telemetrylogs/stmt_builder_test.go
  pkg/telemetrylogs/test_data.go
  pkg/telemetrymetadata/metadata.go
  pkg/telemetrytraces/condition_builder.go
  pkg/telemetrytraces/field_mapper.go
  pkg/telemetrytraces/filter_compiler.go
  pkg/telemetrytraces/statement_builder.go
  pkg/telemetrytraces/stmt_builder_test.go
  pkg/telemetrytraces/test_data.go
  pkg/types/querybuildertypes/querybuildertypesv5/qb.go
  pkg/types/querybuildertypes/querybuildertypesv5/query.go
  pkg/types/querybuildertypes/querybuildertypesv5/resp.go
Labels: chore

#8073 feat(pylon|appcues): add pylon and appcues
  .github/workflows/build-enterprise.yaml
  .github/workflows/build-staging.yaml
  .github/workflows/gor-signoz.yaml
Labels: enhancement

#8045 feat: add appcues and remove customerio
  frontend/example.env
  frontend/src/AppRoutes/index.tsx
  frontend/src/index.html.ejs
  frontend/src/typings/window.ts
  frontend/webpack.config.js
  frontend/webpack.config.prod.js
Labels: enhancement, frontend, docs required, docs not required

#8097 fix(license): return the active license even in case of suspended status
  frontend/src/container/SideNav/SideNav.tsx
  pkg/types/licensetypes/license.go
Labels: bug, request-more-info, staging:distinct-gnat

#8091 feat: add views tab to metrics explorer
  frontend/src/container/MetricsExplorer/Views/Views.tsx
  frontend/src/container/MetricsExplorer/Views/index.ts
  frontend/src/pages/MetricsExplorer/MetricsExplorerPage.tsx
  frontend/src/pages/MetricsExplorer/constants.tsx
  frontend/src/pages/SaveView/constants.ts
Labels: enhancement, frontend, docs not required

#8055 FIX: Pipelines edit filter return empty filter
  frontend/src/container/PipelinePage/PipelineListsView/AddNewPipeline/index.tsx
  frontend/src/container/PipelinePage/PipelineListsView/PipelineListsView.tsx
  frontend/src/container/PipelinePage/tests/AddNewPipeline.test.tsx
  frontend/src/container/PipelinePage/tests/PipelineListsView.test.tsx
Labels: bug, frontend
