Repository SigNoz/signoz, pull requests merged in 2025-07, with the labels that each got.

#8393 fix: fix the regex matching logic in RouteTab
  frontend/src/components/RouteTab/index.tsx
Labels: bug

#8389 fix: fix the issue of traces filters getting duplicated on switching between the span scopes
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/SpanScopeSelector.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/__test__/SpanScopeSelector.test.tsx
  frontend/src/container/TraceWaterfall/TraceWaterfallStates/Success/Filters/Filters.tsx
Labels: bug

#8390 fix: override the stagedQuery orderBy and send order by timestamp in traces view of traces explorer
  frontend/src/container/TracesExplorer/TracesView/index.tsx
  frontend/src/pages/TracesExplorer/__test__/TracesExplorer.test.tsx
  frontend/src/utils/queryTransformers.ts
Labels: bug

#8412 fix: remove deprecated telemetry::metrics::address from config
  deploy/docker-swarm/otel-collector-config.yaml
  deploy/docker/otel-collector-config.yaml
Labels: bug

#8418 Revert "fix: fix the regex matching logic in RouteTab"
  frontend/src/components/RouteTab/index.tsx
Labels: bug

#8421 fix: no logs in list view issue - added logs datasource for formatting and column options in the useoptionsmenu consumption
  frontend/src/components/LogDetail/index.tsx
  frontend/src/container/LogDetailedView/ContextView/ContextLogRenderer.tsx
  frontend/src/container/LogsExplorerList/index.tsx
Labels: bug

#8425 fix: update media styling for changelog renderer and adjust video class
  frontend/src/components/ChangelogModal/components/ChangelogRenderer.styles.scss
  frontend/src/components/ChangelogModal/components/ChangelogRenderer.tsx
Labels: bug

#8426 fix(statsreporter): add unix timestamps for last observed time
  pkg/statsreporter/analyticsstatsreporter/provider.go
Labels: bug

#8324 fix: performance optimizations in log details view json field rendering
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogDetailedView/TableView/TableViewActions.tsx
  frontend/src/container/LogDetailedView/TableView/__test__/TableViewActions.test.tsx
  frontend/src/container/LogDetailedView/TableView/useAsyncJSONProcessing.ts
Labels: bug

#8428 Fix drag handle obstruction on dashboard and service details page
  frontend/src/container/GridCardLayout/GridCardLayout.styles.scss
  frontend/src/pages/MetricsApplication/MetricsApplication.styles.scss
  frontend/src/pages/MetricsApplication/MetricsApplication.tsx
Labels: bug

#8433 fix: used a new classname for banner container earlier one was in ad block list
  frontend/src/container/AppLayout/AppLayout.styles.scss
  frontend/src/container/AppLayout/index.tsx
Labels: bug

#8432 fix: simplify changelog fetching logic and enhance version display interactivity
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/SideNav/SideNav.styles.scss
  frontend/src/container/SideNav/SideNav.tsx
Labels: bug

#8229 chore: added preloaded metrics metadata at first api call
  ee/query-service/app/server.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/querier/helper.go
  pkg/query-service/app/querier/v2/helper.go
  pkg/query-service/app/server.go
  pkg/query-service/rules/threshold_rule_test.go
Labels: chore, safe-to-integrate

#8440 chore: fix regex issue in route tab
  frontend/src/components/RouteTab/index.tsx
  frontend/src/constants/query.ts
  frontend/src/pages/MetricsApplication/MetricsApplication.styles.scss
  frontend/src/pages/MetricsApplication/MetricsApplication.tsx
Labels: bug, chore

#8377 feat: new qb selectedfields changes for logs and traces
  frontend/src/api/querySuggestions/getKeySuggestions.ts
  frontend/src/api/v5/queryRange/prepareQueryRangePayloadV5.ts
  frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QuerySearch/QuerySearch.tsx
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogsExplorerList/utils.ts
  frontend/src/container/NewDashboard/ComponentsSlider/constants.ts
  frontend/src/container/NewWidget/LeftContainer/ExplorerAttributeColumns.tsx
  frontend/src/container/NewWidget/LeftContainer/ExplorerColumnsRenderer.tsx
  frontend/src/container/NewWidget/LeftContainer/__test__/ExplorerColumnsRenderer.test.tsx
  frontend/src/container/NewWidget/utils.ts
  frontend/src/container/OptionsMenu/AddColumnField/index.tsx
  frontend/src/container/OptionsMenu/constants.ts
  frontend/src/container/OptionsMenu/types.ts
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
  frontend/src/container/OptionsMenu/utils.ts
  frontend/src/container/TracesExplorer/ListView/configs.tsx
  frontend/src/container/TracesExplorer/ListView/index.tsx
  frontend/src/container/TracesExplorer/ListView/utils.tsx
  frontend/src/container/TracesTableComponent/TracesTableComponent.tsx
  frontend/src/hooks/dashboard/utils.ts
  frontend/src/hooks/queryBuilder/useGetExplorerQueryRange.ts
  frontend/src/hooks/querySuggestions/useGetQueryKeySuggestions.ts
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/pages/TracesExplorer/Filter/filterUtils.ts
  frontend/src/providers/preferences/__tests__/PreferenceContextProvider.test.tsx
  frontend/src/providers/preferences/__tests__/logsLoaderConfig.test.ts
  frontend/src/providers/preferences/__tests__/logsUpdaterConfig.test.ts
  frontend/src/providers/preferences/__tests__/tracesLoaderConfig.test.ts
  frontend/src/providers/preferences/__tests__/tracesUpdaterConfig.test.ts
  frontend/src/providers/preferences/__tests__/usePreferenceUpdater.test.tsx
  frontend/src/providers/preferences/configs/logsLoaderConfig.ts
  frontend/src/providers/preferences/configs/logsUpdaterConfig.ts
  frontend/src/providers/preferences/configs/tracesLoaderConfig.ts
  frontend/src/providers/preferences/configs/tracesUpdaterConfig.ts
  frontend/src/providers/preferences/loader/usePreferenceLoader.ts
  frontend/src/providers/preferences/sync/usePreferenceSync.ts
  frontend/src/providers/preferences/types/index.ts
  frontend/src/providers/preferences/updater/usePreferenceUpdater.ts
  frontend/src/types/api/dashboard/getAll.ts
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
  frontend/src/types/api/querySuggestions/types.ts
  frontend/src/types/api/v5/queryRange.ts
Labels: enhancement

#8398 chore: use {k8s.pod/k8s.node/container}.cpu.usage metric for metadata…
  frontend/src/container/InfraMonitoringK8s/Clusters/ClusterDetails/constants.ts
  frontend/src/container/InfraMonitoringK8s/DaemonSets/DaemonSetDetails/constants.ts
  frontend/src/container/InfraMonitoringK8s/Deployments/DeploymentDetails/constants.ts
  frontend/src/container/InfraMonitoringK8s/Jobs/JobDetails/constants.ts
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/constants.ts
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/constants.ts
  frontend/src/container/InfraMonitoringK8s/Pods/PodDetails/constants.ts
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/constants.ts
  frontend/src/container/InfraMonitoringK8s/constants.ts
  frontend/src/container/LogDetailedView/InfraMetrics/constants.ts
  pkg/query-service/app/inframetrics/clusters.go
  pkg/query-service/app/inframetrics/common.go
  pkg/query-service/app/inframetrics/daemonsets.go
  pkg/query-service/app/inframetrics/deployments.go
  pkg/query-service/app/inframetrics/namespaces.go
  pkg/query-service/app/inframetrics/nodes.go
  pkg/query-service/app/inframetrics/pods.go
  pkg/query-service/app/inframetrics/statefulsets.go
  pkg/query-service/app/inframetrics/workload_query.go
  pkg/query-service/utils/format.go
Labels: chore

#8459 fix(users): skip sending email if frontend base url is not set
  pkg/modules/user/impluser/module.go
Labels: bug

#8458 chore: fix small typo error in docs
  docs/otel-demo-docs.md
Labels: safe-to-test

#8464 chore: only log telemetry query for explorer, rule and dashboard pages
  pkg/query-service/app/http_handler.go
Labels: chore

#8467 feat(statsreporter): add railway platform detection
  pkg/version/deployment.go
Labels: safe-to-test

#8450 fix: allowed user to select text in json body field in log details
  frontend/src/container/LogDetailedView/BodyTitleRenderer.styles.ts
  frontend/src/container/LogDetailedView/BodyTitleRenderer.tsx
  frontend/src/container/LogDetailedView/TableView/TableViewActions.styles.scss
  frontend/src/container/LogDetailedView/TableView/TableViewActions.tsx
Labels: bug

#8463 fix(apdex): use right metric name for metadata
  frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/ApDexMetricsApplication.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ApDex/constants.ts
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug

#8487 fix(aws-elastic-cache): corrected variable query for elastic cache
  pkg/query-service/app/cloudintegrations/services/definitions/aws/elasticache/assets/dashboards/redis_overview_dot.json
Labels: bug

#8500 chore: added got at 11.8.5 patch to fix image-webpack-loader vulnerability
  frontend/package.json
  frontend/yarn.lock
Labels: chore

#8489 chore: send email on role update
  pkg/modules/user/impluser/handler.go
  pkg/modules/user/impluser/module.go
  pkg/types/emailtypes/template.go
  templates/email/update_role.gotmpl
Labels: chore, staging:actual-guppy

#8512 Feat: changes for showing changelog to cloud users
  frontend/src/components/ChangelogModal/ChangelogModal.tsx
  frontend/src/constants/userPreferences.ts
  frontend/src/container/AppLayout/index.tsx
  pkg/types/preferencetypes/name.go
  pkg/types/preferencetypes/preference.go
Labels: enhancement

#8472 feat: qb - dashboard related code changes [PR-06]
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/GridCardLayout/useResolveQuery.ts
  frontend/src/container/GridTableComponent/index.tsx
  frontend/src/container/GridTableComponent/utils.ts
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/NewDashboard/ComponentsSlider/constants.ts
  frontend/src/container/NewWidget/LeftContainer/ExplorerAttributeColumns.tsx
  frontend/src/container/NewWidget/LeftContainer/ExplorerColumnsRenderer.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphContainer.tsx
  frontend/src/container/NewWidget/LeftContainer/__test__/ExplorerColumnsRenderer.test.tsx
  frontend/src/container/NewWidget/LeftContainer/index.tsx
  frontend/src/container/NewWidget/RightContainer/ColumnUnitSelector/ColumnUnitSelector.styles.scss
  frontend/src/container/NewWidget/RightContainer/ColumnUnitSelector/ColumnUnitSelector.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/ThresholdSelector.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/NewWidget/utils.ts
  frontend/src/container/OptionsMenu/AddColumnField/index.tsx
  frontend/src/container/PanelWrapper/UplotPanelWrapper.tsx
  frontend/src/container/PanelWrapper/ValuePanelWrapper.tsx
  frontend/src/container/TimeSeriesView/TimeSeriesView.styles.scss
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
  frontend/src/container/TimeSeriesView/index.tsx
  frontend/src/lib/dashboard/getQueryResults.ts
  frontend/src/lib/query/createTableColumnsFromQuery.ts
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
  frontend/src/lib/uPlotLib/utils/getSeriesData.ts
  frontend/src/lib/uPlotLib/utils/getUplotChartData.ts
  frontend/src/types/api/dashboard/getAll.ts
Labels: enhancement

#8514 chore: queries variable replacement and escape $ in mat col
  pkg/querier/clickhouse_query.go
  pkg/querier/consume.go
  pkg/querier/promql_query.go
  pkg/querier/querier.go
  pkg/telemetrylogs/condition_builder.go
  pkg/telemetrylogs/condition_builder_test.go
  pkg/telemetrylogs/filter_expr_logs_test.go
  pkg/telemetrymetadata/metadata.go
  pkg/telemetrytraces/condition_builder.go
  pkg/telemetrytraces/const.go
  pkg/telemetrytraces/span_scope_simple_test.go
  pkg/telemetrytraces/statement_builder.go
  pkg/types/telemetrytypes/field.go
  pkg/types/telemetrytypes/field_test.go
Labels: chore

#8508 feat: update data on skip in onboarding
  frontend/src/container/OnboardingQuestionaire/index.tsx
Labels: enhancement, request-more-info, docs not required

#8521 fix: preserve query context inside parentheses + removed normalizespaces
  frontend/src/utils/queryContextUtils.ts
Labels: bug

#8522 feat: query builder v2 enhancement and styling upgrades
  frontend/src/api/v5/queryRange/prepareQueryRangePayloadV5.ts
  frontend/src/components/OrderBy/ListViewOrderBy.tsx
  frontend/src/components/QueryBuilderV2/QueryBuilderV2.styles.scss
  frontend/src/components/QueryBuilderV2/QueryBuilderV2.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/MerticsAggregateSection/MetricsAggregateSection.styles.scss
  frontend/src/components/QueryBuilderV2/QueryV2/MetricsSelect/MetricsSelect.styles.scss
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAggregation/QueryAggregation.styles.scss
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAggregation/QueryAggregationSelect.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QuerySearch/QuerySearch.styles.scss
  frontend/src/components/QueryBuilderV2/QueryV2/QuerySearch/QuerySearch.tsx
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/LogsExplorerViews/LogsExplorerViews.styles.scss
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/MetricsExplorer/Explorer/TimeSeries.tsx
  frontend/src/container/NewWidget/LeftContainer/index.tsx
  frontend/src/container/QueryBuilder/components/Formula/Formula.interfaces.ts
  frontend/src/container/QueryBuilder/components/Formula/Formula.styles.scss
  frontend/src/container/QueryBuilder/components/Formula/Formula.tsx
  frontend/src/container/TracesExplorer/ListView/index.tsx
  frontend/src/hooks/queryBuilder/useGetQueryRange.ts
  frontend/src/hooks/queryBuilder/useGetWidgetQueryRange.ts
Labels: enhancement

#8526 fix: changelog ui fixes
  frontend/src/components/ChangelogModal/ChangelogModal.styles.scss
  frontend/src/components/ChangelogModal/ChangelogModal.tsx
  frontend/src/container/SideNav/SideNav.styles.scss
  frontend/src/container/SideNav/SideNav.tsx
Labels: bug

#8532 fix: revalidate changelog on tab visibility change
  frontend/src/container/AppLayout/index.tsx
Labels: bug

#8457 chore: update in agent version
  pkg/query-service/app/cloudintegrations/controller.go
Labels: chore, staging:civil-eagle

#8536 feat: added new datasources
  frontend/public/Logos/argocd.svg
  frontend/public/Logos/azure-mysql.svg
  frontend/public/Logos/cloudflare.svg
  frontend/public/Logos/dynamodb.svg
  frontend/public/Logos/elk.svg
  frontend/public/Logos/external-api-monitoring.svg
  frontend/public/Logos/github-actions.svg
  frontend/public/Logos/github.svg
  frontend/public/Logos/http-monitoring.svg
  frontend/public/Logos/jenkins.svg
  frontend/public/Logos/newrelic.svg
  frontend/public/Logos/openai.svg
  frontend/public/Logos/s3.svg
  frontend/public/Logos/snowflake.svg
  frontend/public/Logos/sns.svg
  frontend/public/Logos/sqs.svg
  frontend/public/Logos/systemd.svg
  frontend/public/Logos/wordpress.svg
  frontend/src/container/OnboardingV2Container/AddDataSource/AddDataSource.tsx
  frontend/src/container/OnboardingV2Container/onboarding-configs/onboarding-config-with-links.json
Labels: enhancement, onboarding, docs shipped

#8542 fix: light mode for channels create and edit
  frontend/src/container/CreateAlertChannels/CreateAlertChannels.styles.scss
  frontend/src/pages/ChannelsEdit/ChannelsEdit.styles.scss
Labels: bug, docs not required

#8543 chore(release): bump SigNoz to v0.90.0, OTel Collector to v0.128.1
  .devenv/docker/clickhouse/compose.yaml
  .github/workflows/integrationci.yaml
  deploy/docker-swarm/docker-compose.ha.yaml
  deploy/docker-swarm/docker-compose.yaml
  deploy/docker/docker-compose.ha.yaml
  deploy/docker/docker-compose.yaml
Labels: chore

#8545 fix: added fix for changelog refetching multiple times on tab change
  frontend/src/container/AppLayout/index.tsx
Labels: bug

#8481 feat: add support for role based access in trace funnels flows
  frontend/src/components/SignozRadioGroup/SignozRadioGroup.styles.scss
  frontend/src/components/SignozRadioGroup/SignozRadioGroup.tsx
  frontend/src/container/TraceWaterfall/TraceWaterfallStates/Success/Success.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/FunnelConfiguration.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/FunnelStep.styles.scss
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/FunnelStep.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/FunnelStepPopover.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/InterStepConfig.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/StepsContent.tsx
  frontend/src/pages/TracesFunnels/components/FunnelsEmptyState/FunnelsEmptyState.tsx
  frontend/src/pages/TracesFunnels/components/FunnelsList/FunnelItemPopover.tsx
  frontend/src/pages/TracesFunnels/components/SearchBar/SearchBar.tsx
  frontend/src/providers/App/App.tsx
  frontend/src/providers/App/types.ts
  frontend/src/tests/test-utils.tsx
Labels: enhancement, docs required, docs not required

#8300 fix: retain filters during pagination and field filtering on exceptions page
  frontend/src/container/AllError/index.tsx
  frontend/src/container/AllError/utils.ts
Labels: safe-to-test

#8502 fix(dedup-prom): added check for duplicated samples data
  pkg/prometheus/clickhouseprometheus/client.go
  pkg/prometheus/clickhouseprometheus/client_query_test.go
Labels: bug

#8556 Remove docker downloads badge
  README.md
Labels: docs not required

#8175 feat: add support for entrypoint spans toggle in top operations table
  frontend/src/api/metrics/getTopOperations.ts
  frontend/src/container/MetricsApplication/Tabs/Overview/TopOperation.tsx
  frontend/src/container/MetricsApplication/TopOperationsTable.styles.scss
  frontend/src/container/MetricsApplication/TopOperationsTable.tsx
  frontend/src/container/MetricsApplication/__mocks__/getTopOperation.ts
  frontend/src/container/MetricsApplication/__tests__/TopOperationsTable.test.tsx
  frontend/src/types/api/metrics/getTopOperations.ts
Labels: enhancement, docs shipped

#8427 fix: added attribute check for log details filtering
  frontend/src/container/LogDetailedView/ActionItem.tsx
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogDetailedView/TableView/TableViewActions.tsx
  frontend/src/hooks/logs/useActiveLog.ts
  frontend/src/lib/__tests__/chooseAutocompleteFromCustomValue.test.ts
  frontend/src/lib/newQueryBuilder/chooseAutocompleteFromCustomValue.ts
Labels: bug

#8563 fix(prom-dup-labels): added fingerprint in prom labels
  pkg/prometheus/clickhouseprometheus/client.go
  pkg/prometheus/clickhouseprometheus/client_query_test.go
  pkg/prometheus/clickhouseprometheus/json.go
  pkg/prometheus/constants.go
  pkg/prometheus/prometheustest/utils_test.go
  pkg/prometheus/utils.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/rules/prom_rule.go
Labels: bug, staging:magnetic-flea

#8492 feat: add support for single step funnels while creating from span details
  frontend/src/container/TraceWaterfall/AddSpanToFunnelModal/AddSpanToFunnelModal.styles.scss
  frontend/src/container/TraceWaterfall/AddSpanToFunnelModal/AddSpanToFunnelModal.tsx
  frontend/src/pages/TracesFunnelDetails/constants.ts
  frontend/src/pages/TracesFunnels/FunnelContext.tsx
Labels: enhancement, docs required, docs not required

#8585 fix: added fix for logs orderby filter refetching
  frontend/src/components/OrderBy/ListViewOrderBy.styles.scss
  frontend/src/components/OrderBy/ListViewOrderBy.tsx
Labels: bug

#8561 fix: update how index filters are built for resource table
  pkg/query-service/app/logs/v4/query_builder_test.go
  pkg/query-service/app/resource/resource_query_builder.go
  pkg/query-service/app/resource/resource_query_builder_test.go
  pkg/query-service/app/traces/v4/query_builder_test.go
  pkg/querybuilder/resourcefilter/condition_builder.go
  pkg/querybuilder/resourcefilter/condition_builder_test.go
  pkg/telemetrylogs/stmt_builder_test.go
  pkg/telemetrytraces/stmt_builder_test.go
Labels: bug

#8518 chore(dot-metrics): added log line to check for those queries who are still using normalized metrics
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/querier/v2/helper.go
  pkg/query-service/app/querier/v2/querier.go
  pkg/query-service/constants/constants.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/normalizedMetrics.go
Labels: chore

#8491 feat: show success message with note to notify user on role change
  frontend/src/container/OrganizationSettings/Members/index.tsx
Labels: enhancement, docs not required

#8566 chore: fix sentry issues in alerts and infra monitoring
  frontend/src/container/FormAlertRules/ChannelSelect/index.tsx
  frontend/src/container/InfraMonitoringK8s/commonUtils.tsx
Labels: bug, chore

#8606 fix: added fix for key suggestions in metrics
  frontend/src/components/QueryBuilderV2/QueryV2/QuerySearch/QuerySearch.tsx
Labels: bug

#8611 chore: upgraded typescript-plugin-css-modules package to latest and remove stylus resolution
  frontend/package.json
  frontend/yarn.lock
Labels: chore

#8612 fix(community): fix injection of alertmanager
  pkg/query-service/app/server.go
Labels: bug

#8621 feat: update env variable names
  frontend/e2e/utils/login.util.ts
Labels: enhancement, docs not required

#8629 feat: enable latency pointer configuration with smart defaults
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/FunnelStep.tsx
  frontend/src/pages/TracesFunnelDetails/constants.ts
  frontend/src/pages/TracesFunnels/FunnelContext.tsx
Labels: enhancement

#8615 fix: changes in code to support ch 25.5
  pkg/modules/tracefunnel/clickhouse_queries.go
  pkg/modules/tracefunnel/query.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/traces/v4/query_builder.go
  pkg/query-service/app/traces/v4/query_builder_test.go
  pkg/query-service/constants/constants.go
Labels: bug, staging:next-ewe

#8638 chore: order time series result set
  pkg/http/render/render.go
  pkg/querier/bucket_cache.go
  pkg/querier/consume.go
  pkg/querier/postprocess.go
  pkg/telemetrylogs/statement_builder.go
  pkg/telemetrylogs/stmt_builder_test.go
  pkg/telemetrytraces/statement_builder.go
  pkg/telemetrytraces/stmt_builder_test.go
  pkg/types/querybuildertypes/querybuildertypesv5/builder_query.go
  pkg/types/querybuildertypes/querybuildertypesv5/clickhouse_query.go
  pkg/types/querybuildertypes/querybuildertypesv5/formula.go
  pkg/types/querybuildertypes/querybuildertypesv5/math.go
  pkg/types/querybuildertypes/querybuildertypesv5/prom_query.go
  pkg/types/querybuildertypes/querybuildertypesv5/req.go
  pkg/types/querybuildertypes/querybuildertypesv5/request_type.go
  pkg/types/querybuildertypes/querybuildertypesv5/resp.go
  pkg/types/querybuildertypes/querybuildertypesv5/validation.go
  pkg/types/telemetrytypes/virtualfield.go
Labels: chore

#8641 chore: add alert link visitor for expression link
  pkg/contextlinks/alert_link_visitor.go
  pkg/contextlinks/alert_link_visitor_test.go
  pkg/contextlinks/links.go
  pkg/contextlinks/types.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/rules/threshold_rule.go
Labels: chore

#8618 fix: open log details on clicking on empty column cell too
  frontend/src/container/LogsExplorerList/InfinityTableView/TableRow.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
Labels: bug

#8619 test(integration): add integration tests for logs
  .github/workflows/integrationci.yaml
  cmd/enterprise/Dockerfile.integration
  tests/integration/conftest.py
  tests/integration/fixtures/auth.py
  tests/integration/fixtures/clickhouse.py
  tests/integration/fixtures/dev.py
  tests/integration/fixtures/fingerprint.py
  tests/integration/fixtures/http.py
  tests/integration/fixtures/logs.py
  tests/integration/fixtures/migrator.py
  tests/integration/fixtures/network.py
  tests/integration/fixtures/postgres.py
  tests/integration/fixtures/signoz.py
  tests/integration/fixtures/sqlite.py
  tests/integration/fixtures/types.py
  tests/integration/fixtures/zookeeper.py
  tests/integration/poetry.lock
  tests/integration/pyproject.toml
  tests/integration/src/auth/__init__.py
  tests/integration/src/auth/a_register.py
  tests/integration/src/auth/b_license.py
  tests/integration/src/auth/c_apikey.py
  tests/integration/src/bootstrap/a_database.py
  tests/integration/src/bootstrap/setup.py
  tests/integration/src/querier/__init__.py
  tests/integration/src/querier/a_logs.py
Labels: safe-to-integrate

#8651 test(integration): add or filter with resource attributes
  tests/integration/fixtures/logs.py
  tests/integration/src/querier/a_logs.py
Labels: safe-to-integrate

#8595 Chore/added_ilike : added ilike and notIlike filter operator
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/utils.ts
  frontend/src/hooks/queryBuilder/useOperatorType.ts
  pkg/query-service/app/logs/v4/query_builder.go
  pkg/query-service/app/logs/v4/query_builder_test.go
  pkg/query-service/app/metrics/v4/helpers/sub_query.go
  pkg/query-service/app/metrics/v4/query_builder_test.go
  pkg/query-service/app/resource/resource_query_builder.go
  pkg/query-service/app/resource/resource_query_builder_test.go
  pkg/query-service/app/traces/v4/query_builder.go
  pkg/query-service/app/traces/v4/query_builder_test.go
  pkg/query-service/model/v3/v3.go
Labels: chore, staging:magnetic-flea

#8446 feat: enhance logs explorer chart to display full selected time window
  frontend/src/components/Graph/index.tsx
  frontend/src/components/Graph/types.ts
  frontend/src/components/Graph/utils.ts
  frontend/src/components/Graph/xAxisConfig.ts
  frontend/src/container/LogsExplorerChart/index.tsx
Labels: enhancement, docs not required

#8581 chore: write test for recalculating timestamps on clicking stage and run in logs explorer
  frontend/src/container/LogsExplorerViews/tests/LogsExplorerPagination.test.tsx
  frontend/src/tests/test-utils.tsx
Labels: chore

#8628 feat: enable creating more than 3 steps in trace funnels + enable latency pointer
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/FunnelStep.tsx
  frontend/src/pages/TracesFunnelDetails/components/FunnelConfiguration/StepsContent.tsx
  frontend/src/pages/TracesFunnelDetails/constants.ts
  frontend/src/pages/TracesFunnels/FunnelContext.tsx
Labels: enhancement, docs shipped

#8653 fix: adding missing flags to run go-run-community
  Makefile
Labels: safe-to-test

#8637 fix: uPlot logarithmic scale range error
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
Labels: bug

#8652 Fix/query builder themeing
  frontend/package.json
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAddOns/HavingFilter/HavingFilter.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAddOns/QueryAddOns.styles.scss
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAggregation/QueryAggregation.styles.scss
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAggregation/QueryAggregationSelect.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QuerySearch/QuerySearch.styles.scss
  frontend/src/components/QueryBuilderV2/QueryV2/QuerySearch/QuerySearch.tsx
  frontend/src/container/Home/Home.tsx
  frontend/src/container/LogsExplorerViews/LogsExplorerViews.styles.scss
  frontend/src/utils/app.ts
  frontend/yarn.lock
Labels: bug

#8663 fix: minor fix for changelog popup to show only when preference is av…
  frontend/src/container/AppLayout/index.tsx
Labels: bug

#8665 chore: add unsupported saml list
  frontend/src/container/OrganizationSettings/AuthDomains/Create/Row/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/Create/index.tsx
Labels: chore

#8660 chore: updated antlr grammar files
  frontend/src/parser/FilterQuery.interp
  frontend/src/parser/FilterQueryLexer.interp
  frontend/src/parser/FilterQueryLexer.ts
  grammar/FilterQuery.g4
Labels: chore

#8669 feat: fix and misc enhancements for qb v5
  frontend/src/api/v5/queryRange/prepareQueryRangePayloadV5.ts
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAggregation/QueryAggregationSelect.tsx
  frontend/src/container/MetricsExplorer/Explorer/Explorer.styles.scss
  frontend/src/pages/TracesExplorer/TracesExplorer.styles.scss
Labels: bug, enhancement

#8608 feat: saved view and alert payload migration
  frontend/src/api/v5/queryRange/convertV5Response.ts
  frontend/src/api/v5/queryRange/prepareQueryRangePayloadV5.ts
  frontend/src/components/OrderBy/ListViewOrderBy.tsx
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/FormAlertRules/usePrefillAlertConditions.ts
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCard/utils.ts
  frontend/src/container/GridCardLayout/WidgetHeader/index.tsx
  frontend/src/container/InfraMonitoringK8s/EntityDetailsUtils/EntityLogs/__tests__/EntityLogs.test.tsx
  frontend/src/container/LogsExplorerViews/tests/LogsExplorerPagination.test.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/clickHouse/query.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/QueryBuilder/promQL/query.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/QueryBuilder/components/Formula/Formula.tsx
  frontend/src/container/TracesExplorer/TracesView/configs.tsx
  frontend/src/container/TracesExplorer/TracesView/index.tsx
  frontend/src/hooks/queryBuilder/useGetQueryRange.ts
  frontend/src/lib/dashboard/getQueryResults.ts
  frontend/src/lib/newQueryBuilder/queryBuilderMappers/mapCompositeQueryFromQuery.ts
  frontend/src/lib/newQueryBuilder/queryBuilderMappers/mapQueryDataFromApi.ts
  frontend/src/mocks-server/__mockdata__/query_range.ts
  frontend/src/types/api/alerts/compositeQuery.ts
  frontend/src/types/api/error.ts
  frontend/src/types/api/v5/queryRange.ts
  frontend/src/utils/compositeQueryToQueryEnvelope.ts
  frontend/src/utils/convertNewToOldQueryBuilder.ts
Labels: enhancement, safe-to-test

#8668 fix: added fix for persisting currentquery even without stage+run and…
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/providers/QueryBuilder.tsx
Labels: bug

#8666 test(integration): add traces integration tests
  tests/integration/conftest.py
  tests/integration/fixtures/logs.py
  tests/integration/fixtures/traces.py
  tests/integration/src/querier/a_logs.py
  tests/integration/src/querier/b_traces.py
Labels: safe-to-integrate
