Repository SigNoz/signoz, pull requests merged in 2025-10, with the labels that each got.

#9224 fix: test rule multiple threhsold
  ee/query-service/rules/anomaly.go
  ee/query-service/rules/manager.go
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanagerserver/server.go
  pkg/alertmanager/alertmanagerserver/server_test.go
  pkg/alertmanager/service.go
  pkg/alertmanager/signozalertmanager/provider.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/prom_rule.go
  pkg/query-service/rules/test_notification.go
  pkg/query-service/rules/threshold_rule.go
  pkg/types/alertmanagertypes/receiver.go
Labels: bug

#9240 fix: handle resource/attribute context collision with expression usin…
  pkg/querybuilder/where_clause_visitor.go
  pkg/telemetrylogs/stmt_builder_test.go
  pkg/telemetrylogs/test_data.go
Labels: bug

#9129 fix: exists/not exists for resource attributes
  pkg/telemetrylogs/condition_builder.go
  pkg/telemetrylogs/condition_builder_test.go
  pkg/telemetrylogs/filter_expr_logs_test.go
  pkg/telemetrylogs/stmt_builder_test.go
  pkg/telemetrytraces/condition_builder.go
  pkg/telemetrytraces/condition_builder_test.go
  pkg/telemetrytraces/field_mapper_test.go
  pkg/telemetrytraces/stmt_builder_test.go
  pkg/telemetrytraces/trace_operator_cte_builder_test.go
Labels: bug

#9243 chore(statsreporter): fix azure IMDS endpoint in statsreporter
  pkg/version/deployment.go
Labels: safe-to-test

#9249 chore: remove routing policies feature flag
  frontend/src/container/CreateAlertV2/AlertCondition/AlertCondition.tsx
  frontend/src/container/CreateAlertV2/AlertCondition/AlertThreshold.tsx
  frontend/src/container/CreateAlertV2/AlertCondition/__tests__/AlertThreshold.test.tsx
  frontend/src/container/CreateAlertV2/CreateAlertV2.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/EvaluationSettings.tsx
  frontend/src/container/CreateAlertV2/EvaluationSettings/__tests__/EvaluationSettings.test.tsx
  frontend/src/container/CreateAlertV2/NotificationSettings/NotificationSettings.tsx
  frontend/src/container/CreateAlertV2/NotificationSettings/__tests__/NotificationSettings.test.tsx
  frontend/src/container/CreateAlertV2/utils.tsx
  frontend/src/container/EditAlertV2/EditAlertV2.tsx
  frontend/src/container/RoutingPolicies/utils.tsx
  frontend/src/pages/AlertList/index.tsx
Labels: enhancement, chore

#9255 fix: fix the flaky test
  frontend/src/container/SpanDetailsDrawer/__tests__/SpanDetailsDrawer.test.tsx
Labels: bug

#9288 fix: anomaly with below operator negates the target
  ee/anomaly/seasonal.go
  ee/query-service/rules/anomaly.go
  pkg/types/ruletypes/api_params.go
  pkg/types/ruletypes/api_params_test.go
Labels: bug

#9154 fix: use numerical comparison instead of lexicographical for string-encoded numbers
  pkg/querybuilder/fallback_expr.go
  pkg/querybuilder/fallback_expr_test.go
  pkg/telemetrylogs/condition_builder.go
  pkg/telemetrylogs/filter_expr_logs_test.go
  pkg/telemetrymetadata/condition_builder.go
  pkg/telemetrytraces/condition_builder.go
  pkg/types/querybuildertypes/querybuildertypesv5/builder_elements.go
  pkg/types/telemetrytypes/field.go
  pkg/types/telemetrytypes/field_test.go
  tests/integration/src/querier/a_logs.py
Labels: bug, safe-to-integrate
