Repository SigNoz/signoz, pull requests merged in 2025-08, with the labels that each got.

#8681 fix: cloned panel query shows previous query
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/providers/QueryBuilder.tsx
Labels: bug

#8685 fix: fixed table columns getting duplicate data
  frontend/src/api/v5/queryRange/convertV5Response.ts
  frontend/src/components/QueryBuilderV2/utils.ts
  frontend/src/container/TracesExplorer/TableView/index.tsx
  frontend/src/lib/query/createTableColumnsFromQuery.ts
Labels: bug

#8661 fix: fix the issue of stale pipeline processor state while switching between different processors after updating json flattening config in any processor
  frontend/src/container/PipelinePage/PipelineListsView/AddNewProcessor/index.tsx
Labels: bug

#8676 chore: add tooltips with links to documentation
  frontend/src/components/QueryBuilderV2/QueryV2/MerticsAggregateSection/MetricsAggregateSection.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAddOns/QueryAddOns.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAggregation/QueryAggregation.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAggregation/QueryAggregationSelect.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QueryFooter/QueryFooter.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QuerySearch/QuerySearch.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
Labels: chore, staging:civil-eagle

#8694 fix: added fix for query validation and empty query error
  frontend/src/components/QueryBuilderV2/QueryV2/QuerySearch/QuerySearch.tsx
Labels: bug

#8640 fix: disabling alert from overview page doesn't work
  frontend/src/pages/AlertDetails/AlertHeader/ActionButtons/ActionButtons.tsx
  frontend/src/pages/AlertDetails/hooks.tsx
Labels: bug

#8631 chore: update home page task tracker for metrics explorer
  frontend/src/constants/orgPreferences.ts
  frontend/src/container/Home/Home.tsx
  frontend/src/container/Home/SavedViews/SavedViews.tsx
  frontend/src/container/Home/constants.ts
Labels: chore

#8711 chore: improve metrics explorer empty state
  frontend/src/container/MetricsExplorer/Summary/Summary.tsx
  frontend/src/container/NoLogs/NoLogs.tsx
  frontend/src/utils/docLinks.ts
Labels: chore

#8709 fix: added fix for selected columns being empty in logs explorer
  frontend/src/providers/preferences/sync/usePreferenceSync.ts
  frontend/src/types/api/v5/queryRange.ts
Labels: bug

#8700 feat: created new error content plugin for QB v5
  frontend/src/api/metrics/getQueryRange.ts
  frontend/src/api/v5/queryRange/convertV5Response.ts
  frontend/src/components/ErrorInPlace/ErrorInPlace.tsx
  frontend/src/components/ErrorPopover/ErrorPopover.tsx
  frontend/src/components/WarningPopover/WarningPopover.styles.scss
  frontend/src/components/WarningPopover/WarningPopover.tsx
  frontend/src/container/FormAlertRules/ChartPreview/ChartPreview.styles.scss
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/WidgetHeader/index.tsx
  frontend/src/container/LogsExplorerList/LogsExplorerList.interfaces.ts
  frontend/src/container/LogsExplorerList/__tests__/LogsExplorerList.test.tsx
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/LogsExplorerTable/LogsExplorerTable.interfaces.ts
  frontend/src/container/LogsExplorerTable/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsExplorerViews/tests/LogsExplorerViews.test.tsx
  frontend/src/container/MetricsExplorer/Explorer/Explorer.tsx
  frontend/src/container/MetricsExplorer/Explorer/TimeSeries.tsx
  frontend/src/container/MetricsExplorer/Explorer/types.ts
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraph.styles.scss
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphContainer.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/index.tsx
  frontend/src/container/NewWidget/types.ts
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
  frontend/src/container/TimeSeriesView/index.tsx
  frontend/src/container/Toolbar/Toolbar.tsx
  frontend/src/container/TracesExplorer/ListView/index.tsx
  frontend/src/container/TracesExplorer/TableView/index.tsx
  frontend/src/container/TracesExplorer/TracesView/index.tsx
  frontend/src/hooks/queryBuilder/useGetExplorerQueryRange.ts
  frontend/src/hooks/queryBuilder/useGetQueryRange.ts
  frontend/src/lib/dashboard/getQueryResults.ts
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/pages/TracesExplorer/index.tsx
  frontend/src/pages/TracesExplorer/utils.tsx
  frontend/src/types/api/index.ts
  frontend/src/types/api/metrics/getQueryRange.ts
  frontend/src/types/api/v5/queryRange.ts
Labels: enhancement, docs not required

#8675 fixes: includes fixes required in the new QB
  frontend/src/api/dashboard/substitute_vars.ts
  frontend/src/api/v5/queryRange/convertV5Response.ts
  frontend/src/api/v5/queryRange/prepareQueryRangePayloadV5.ts
  frontend/src/components/CeleryTask/useNavigateToExplorer.ts
  frontend/src/components/Common/Common.styles.scss
  frontend/src/components/Common/ErrorStateComponent.tsx
  frontend/src/components/QueryBuilderV2/QueryBuilderV2Context.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/MerticsAggregateSection/MetricsAggregateSection.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/MetricsSelect/MetricsSelect.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAddOns/HavingFilter/HavingFilter.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAddOns/QueryAddOns.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAggregation/QueryAggregation.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAggregation/QueryAggregationSelect.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QueryFooter/QueryFooter.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QuerySearch/QuerySearch.tsx
  frontend/src/components/QueryBuilderV2/utils.ts
  frontend/src/components/ResizeTable/ResizeTable.tsx
  frontend/src/constants/antlrQueryConstants.ts
  frontend/src/container/CreateAlertRule/defaults.ts
  frontend/src/container/CreateAlertRule/index.tsx
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/utils.ts
  frontend/src/container/GridCardLayout/useResolveQuery.ts
  frontend/src/container/GridTableComponent/index.tsx
  frontend/src/container/LogDetailedView/BodyTitleRenderer.tsx
  frontend/src/container/LogsExplorerViews/tests/LogsExplorerViews.test.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/RightContainer/ColumnUnitSelector/ColumnUnitSelector.tsx
  frontend/src/container/NewWidget/RightContainer/LegendColors/LegendColors.tsx
  frontend/src/container/NewWidget/RightContainer/Threshold/Threshold.tsx
  frontend/src/container/NewWidget/RightContainer/YAxisUnitSelector.tsx
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/container/QueryBuilder/components/QBEntityOptions/QBEntityOptions.tsx
  frontend/src/container/QueryBuilder/components/QueryFunctions/Function.tsx
  frontend/src/container/QueryBuilder/components/QueryFunctions/QueryFunctions.tsx
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.intefaces.ts
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
  frontend/src/container/TracesExplorer/TableView/index.tsx
  frontend/src/hooks/queryBuilder/useCreateAlerts.tsx
  frontend/src/hooks/queryBuilder/useQueryBuilderOperations.ts
  frontend/src/lib/dashboard/getQueryResults.ts
  frontend/src/lib/query/createTableColumnsFromQuery.ts
  frontend/src/lib/uPlotLib/utils/getSeriesData.ts
  frontend/src/pages/LogsExplorer/__tests__/LogsExplorer.test.tsx
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/providers/preferences/sync/usePreferenceSync.ts
  frontend/src/types/api/metrics/getQueryRange.ts
  frontend/src/types/api/queryBuilder/queryBuilderData.ts
  frontend/src/types/api/v5/queryRange.ts
  frontend/src/types/common/operations.types.ts
  frontend/src/utils/antlrQueryUtils.ts
  frontend/src/utils/convertNewToOldQueryBuilder.ts
  frontend/src/utils/functionNameNormalizer.test.ts
  frontend/src/utils/functionNameNormalizer.ts
  frontend/src/utils/queryValidationUtils.ts
  frontend/src/utils/tokenUtils.ts
Labels: bug

#8719 fix: added fix for query suggestions position
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAddOns/QueryAddOns.styles.scss
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAggregation/QueryAggregation.styles.scss
  frontend/src/components/QueryBuilderV2/QueryV2/QuerySearch/QuerySearch.styles.scss
Labels: bug

#8725 fix: added fix for query addon lightmode ui
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAddOns/QueryAddOns.styles.scss
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAggregation/QueryAggregation.styles.scss
  frontend/src/components/QueryBuilderV2/QueryV2/QuerySearch/QuerySearch.styles.scss
Labels: bug

#8642 chore: add sql migration for dashboards, alerts, and saved views
  go.mod
  pkg/apis/fields/api.go
  pkg/modules/dashboard/impldashboard/handler.go
  pkg/querier/querier.go
  pkg/query-service/rules/threshold_rule.go
  pkg/query-service/tests/integration/filter_suggestions_test.go
  pkg/query-service/tests/integration/logparsingpipeline_test.go
  pkg/query-service/tests/integration/signoz_cloud_integrations_test.go
  pkg/query-service/tests/integration/signoz_integrations_test.go
  pkg/querybuilder/init.go
  pkg/querybuilder/query_to_keys.go
  pkg/querybuilder/query_to_keys_test.go
  pkg/querybuilder/resourcefilter/statement_builder.go
  pkg/querybuilder/time.go
  pkg/querybuilder/where_clause_visitor.go
  pkg/signoz/handler.go
  pkg/signoz/handler_test.go
  pkg/signoz/provider.go
  pkg/signoz/provider_test.go
  pkg/signoz/signoz.go
  pkg/sqlmigration/046_update_dashboard_alert_and_saved_view_v5.go
  pkg/telemetrylogs/json.go
  pkg/telemetrylogs/statement_builder.go
  pkg/telemetrymetadata/metadata.go
  pkg/telemetrymetadata/metadata_test.go
  pkg/telemetrymetrics/statement_builder.go
  pkg/telemetrytraces/statement_builder.go
  pkg/transition/migrate_alert.go
  pkg/transition/migrate_common.go
  pkg/transition/migrate_dashboard.go
  pkg/transition/migrate_saved_view.go
  pkg/types/querybuildertypes/querybuildertypesv5/builder_elements.go
  pkg/types/querybuildertypes/querybuildertypesv5/builder_query.go
  pkg/types/querybuildertypes/querybuildertypesv5/clickhouse_query.go
  pkg/types/querybuildertypes/querybuildertypesv5/formula.go
  pkg/types/querybuildertypes/querybuildertypesv5/join.go
  pkg/types/querybuildertypes/querybuildertypesv5/prom_query.go
  pkg/types/querybuildertypes/querybuildertypesv5/resp.go
  pkg/types/telemetrytypes/field.go
  pkg/types/telemetrytypes/store.go
  pkg/types/telemetrytypes/telemetrytypestest/metadata_store.go
Labels: chore

#8728 fix: limit keys for empty search key
  pkg/telemetrymetadata/metadata.go
Labels: bug

#8739 fix: added fix for query becoming empty on time change
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
Labels: bug

#8743 test(integration): bump requests to 2.32.4
  tests/integration/poetry.lock
  tests/integration/pyproject.toml
Labels: safe-to-integrate

#8747 feat: migrate old saved columns keys to name
  frontend/src/providers/preferences/loader/usePreferenceLoader.ts
Labels: enhancement, docs not required

#8749 fix(alert-querier v5): added querier v5 in test notify
  pkg/query-service/rules/manager.go
Labels: bug, staging:magnetic-flea

#8702 feat: show count in span details drawer tabs
  frontend/src/container/SpanDetailsDrawer/SpanDetailsDrawer.styles.scss
  frontend/src/container/SpanDetailsDrawer/SpanDetailsDrawer.tsx
Labels: enhancement, docs not required

#8751 fix: use localstorage value to avoid waiting for pref api to set the toggle state, add shortcut
  frontend/src/constants/shortcuts/globalShortcuts.ts
  frontend/src/container/AppLayout/__tests__/sidebar-toggle-shortcut.test.tsx
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/MySettings/index.tsx
Labels: bug

#8768 fix: `key CONTAINS value` doesn't work for numeric values
  conf/example.yaml
  pkg/querybuilder/fallback_expr.go
  pkg/querybuilder/format_test.go
  pkg/querybuilder/resourcefilter/condition_builder.go
  pkg/querybuilder/resourcefilter/condition_builder_test.go
  pkg/telemetrylogs/condition_builder.go
  pkg/telemetrylogs/condition_builder_test.go
  pkg/telemetrylogs/filter_expr_logs_test.go
  pkg/telemetrylogs/test_data.go
  pkg/telemetrymetadata/condition_builder.go
  pkg/telemetrymetrics/condition_builder.go
  pkg/telemetrymetrics/condition_builder_test.go
  pkg/telemetrystore/config.go
  pkg/telemetrystore/telemetrystorehook/settings.go
  pkg/telemetrytraces/condition_builder.go
  pkg/telemetrytraces/condition_builder_test.go
Labels: bug

#8778 fix: check ch version
  pkg/signoz/provider.go
  pkg/telemetrystore/clickhousetelemetrystore/provider.go
  pkg/telemetrystore/telemetrystore.go
  pkg/telemetrystore/telemetrystorehook/settings.go
Labels: bug, safe-to-integrate

#8779 fix: resolve infinite loading issue in metric view in messaging queues
  frontend/src/pages/MessagingQueues/MQDetails/MetricPage/MetricPage.tsx
Labels: bug

#8774 chore: add unit tests for k8s entity details
  frontend/src/container/InfraMonitoringK8s/Clusters/ClusterDetails/ClusterDetails.tsx
  frontend/src/container/InfraMonitoringK8s/EntityDetailsUtils/EntityEvents/__tests__/EntityEvents.test.tsx
  frontend/src/container/InfraMonitoringK8s/EntityDetailsUtils/EntityMetrics/__tests__/EntityMetrics.test.tsx
  frontend/src/container/InfraMonitoringK8s/EntityDetailsUtils/EntityTraces/__tests__/EntityTraces.test.tsx
  frontend/src/container/InfraMonitoringK8s/LoadingContainer.tsx
  frontend/src/container/InfraMonitoringK8s/__tests__/Clusters/ClusterDetails/ClusterDetails.test.tsx
  frontend/src/container/InfraMonitoringK8s/__tests__/DaemonSets/DaemonSetDetails/DaemonSetDetails.test.tsx
  frontend/src/container/InfraMonitoringK8s/__tests__/Deployments/DeploymentDetails/DeploymentDetails.test.tsx
  frontend/src/container/InfraMonitoringK8s/__tests__/Jobs/JobDetails/JobDetails.test.tsx
  frontend/src/container/InfraMonitoringK8s/__tests__/Namespaces/NamespaceDetails/NamespaceDetails.test.tsx
  frontend/src/container/InfraMonitoringK8s/__tests__/Nodes/NodeDetails/NodeDetails.test.tsx
  frontend/src/container/InfraMonitoringK8s/__tests__/Pods/PodDetails/PodDetails.test.tsx
  frontend/src/container/InfraMonitoringK8s/__tests__/StatefulSets/StatefulSetDetails/StatefulSetDetails.test.tsx
  frontend/src/container/InfraMonitoringK8s/__tests__/Volumes/VolumeDetails/VolumeDetails.test.tsx
  frontend/src/container/InfraMonitoringK8s/__tests__/commonMocks.ts
Labels: chore

#8834 fix: added fix for supporting older queries
  frontend/src/components/QueryBuilderV2/__tests__/utils.test.ts
  frontend/src/components/QueryBuilderV2/utils.ts
  frontend/src/constants/antlrQueryConstants.ts
  frontend/src/utils/tokenUtils.ts
Labels: bug

#8836 fix: set source on add new query
  frontend/src/components/QueryBuilderV2/QueryV2/MetricsSelect/MetricsSelect.styles.scss
  frontend/src/container/MeterExplorer/Explorer/Explorer.styles.scss
  frontend/src/providers/QueryBuilder.tsx
Labels: bug

#8730 chore: backend changes for y-axis management
  pkg/query-service/converter/converter.go
  pkg/query-service/converter/data.go
  pkg/query-service/converter/data_rate.go
  pkg/query-service/converter/data_rate_test.go
  pkg/query-service/converter/data_test.go
  pkg/query-service/converter/percent_converter.go
  pkg/query-service/converter/percent_converter_test.go
  pkg/query-service/converter/time.go
  pkg/query-service/converter/time_test.go
  pkg/query-service/formatter/data.go
  pkg/query-service/formatter/data_rate.go
  pkg/query-service/formatter/data_test.go
  pkg/query-service/formatter/formatter.go
  pkg/query-service/formatter/percent.go
  pkg/query-service/formatter/throughput.go
  pkg/query-service/formatter/throughput_test.go
  pkg/query-service/formatter/time.go
  pkg/query-service/formatter/time_test.go
  pkg/query-service/rules/threshold_rule_test.go
  pkg/query-service/rules/threshold_rule_test_data.go
Labels: chore

#8877 feat: reverted dynamic variable url config changes
  frontend/src/constants/query.ts
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/useDashboardVariableUpdate.ts
  frontend/src/hooks/dashboard/__test__/useVariablesFromUrl.test.tsx
  frontend/src/hooks/dashboard/useVariablesFromUrl.tsx
  frontend/src/providers/Dashboard/Dashboard.tsx
  frontend/src/providers/Dashboard/initializeDefaultVariables.ts
Labels: enhancement

#8878 fix: resolve sentry issues in alert list
  frontend/src/container/FormAlertRules/labels/utils.ts
  frontend/src/container/ListAlertRules/ListAlert.tsx
  frontend/src/pages/AlertDetails/AlertHeader/AlertHeader.tsx
  frontend/src/types/api/alerts/def.ts
  pkg/transition/migrate_common.go
Labels: bug

#8883 fix: related links for rule history page
  pkg/query-service/app/http_handler.go
  pkg/query-service/rules/threshold_rule.go
  pkg/transition/migrate_alert.go
  pkg/types/ruletypes/alerting.go
Labels: bug

#8902 chore: do not send field context as tag for deprecated fields
  frontend/src/api/v5/queryRange/prepareQueryRangePayloadV5.ts
Labels: chore

#8897 chore: update dashboard template links to SigNoz website dashboard template landing page
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/ListOfDashboard/ImportJSON/index.tsx
  frontend/src/container/ListOfDashboard/RequestDashboardBtn.tsx
Labels: chore

#8886 feat: date picker v2
  frontend/jest.config.ts
  frontend/package.json
  frontend/src/components/CustomTimePicker/CustomTimePicker.styles.scss
  frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
  frontend/src/components/CustomTimePicker/CustomTimePickerPopoverContent.tsx
  frontend/src/components/DatePickerV2/DatePickerV2.styles.scss
  frontend/src/components/DatePickerV2/DatePickerV2.tsx
  frontend/src/constants/dateTimeFormats.ts
  frontend/src/constants/localStorage.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/DateTimeSelectionV2.styles.scss
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/hooks/useCustomTimeRanges.ts
  frontend/src/styles.scss
  frontend/src/utils/customTimeRangeUtils.ts
  frontend/src/utils/timeUtils.ts
  frontend/yarn.lock
Labels: enhancement, docs not required

#8906 feat: enable global actions
  frontend/package.json
  frontend/src/AppRoutes/index.tsx
  frontend/src/components/KBarCommandPalette/KBarCommandPalette.scss
  frontend/src/components/KBarCommandPalette/KBarCommandPalette.tsx
  frontend/src/constants/shortcuts/globalShortcuts.ts
  frontend/src/constants/shortcuts/logsExplorerShortcuts.ts
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/MySettings/index.tsx
  frontend/src/hooks/useDarkMode/constant.ts
  frontend/src/hooks/useDarkMode/index.tsx
  frontend/src/pages/Shortcuts/Shortcuts.styles.scss
  frontend/src/pages/Shortcuts/utils.ts
  frontend/src/providers/KBarCommandPaletteProvider.tsx
  frontend/yarn.lock
Labels: enhancement, docs not required

#8921 fix(meter): meter regex for comment middleware
  pkg/types/ctxtypes/comment.go
Labels: bug

#8922 fix: removed transformstringwithprefix and removeprefix utilities
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
  frontend/src/container/QueryBuilder/filters/GroupByFilter/GroupByFilter.tsx
  frontend/src/container/QueryBuilder/filters/GroupByFilter/utils.ts
  frontend/src/container/QueryBuilder/filters/HavingFilter/HavingFilter.tsx
  frontend/src/container/QueryBuilder/filters/HavingFilter/__tests__/utils.test.tsx
  frontend/src/hooks/queryBuilder/useOptions.ts
  frontend/src/lib/query/transformStringWithPrefix.ts
Labels: bug

#8934 fix: trace explorer and home page keyboard shortcut
  frontend/src/constants/shortcuts/globalShortcuts.ts
  frontend/src/container/SideNav/SideNav.tsx
Labels: bug

#8807 fix: update live tail api
  pkg/querier/api.go
  pkg/querier/consume.go
  pkg/querier/interfaces.go
  pkg/querier/querier.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/logs.go
  pkg/query-service/model/response.go
  pkg/querybuilder/resourcefilter/statement_builder.go
  pkg/telemetrylogs/statement_builder.go
  pkg/telemetrylogs/stmt_builder_test.go
  pkg/types/querybuildertypes/querybuildertypesv5/request_type.go
  pkg/types/querybuildertypes/querybuildertypesv5/resp.go
  pkg/types/querybuildertypes/querybuildertypesv5/validation.go
Labels: bug, safe-to-integrate, staging:included-weevil

#8948 feat: show timestamp in selected timezone format
  frontend/src/container/LogsExplorerList/ColumnView/ColumnView.tsx
Labels: enhancement, docs not required

#8949 feat(ingestion): add ingestion id to ingestion key details page
  frontend/src/container/IngestionSettings/MultiIngestionSettings.tsx
Labels: enhancement, request-more-info

#8950 feat: use updated props from data table component for better UX
  frontend/package.json
  frontend/src/container/LogsExplorerList/ColumnView/ColumnView.tsx
  frontend/src/container/LogsExplorerList/LogsExplorerList.style.scss
  frontend/yarn.lock
Labels: enhancement, docs not required

#8893 fix: remove isRoot and Entrypoint from selectfields
  pkg/types/querybuildertypes/querybuildertypesv5/validation.go
Labels: bug

#8947 feat: minor ui updates
  frontend/src/container/OrganizationSettings/AuthDomains/AddDomain/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/index.tsx
  frontend/src/container/OrganizationSettings/AuthDomains/styles.ts
  frontend/src/container/OrganizationSettings/InviteUserModal/InviteUserModal.tsx
  frontend/src/container/OrganizationSettings/Members/index.tsx
  frontend/src/container/OrganizationSettings/OrganizationSettings.styles.scss
  frontend/src/container/OrganizationSettings/PendingInvitesContainer/index.tsx
  frontend/src/container/OrganizationSettings/index.tsx
Labels: enhancement, docs not required

#8940 fix: return 404 status code if rule not found
  pkg/query-service/app/http_handler.go
Labels: bug
