Repository SigNoz/signoz, pull requests merged in 2025-04, with the labels that each got.

#7492 chore: add migration for pat to add default values
  ee/http/middleware/pat.go
  ee/query-service/app/api/cloudIntegrations.go
  ee/query-service/app/api/pat.go
  ee/query-service/dao/interface.go
  ee/query-service/dao/sqlite/pat.go
  ee/query-service/model/pat.go
  ee/sqlstore/postgressqlstore/dialect.go
  ee/types/personal_access_token.go
  pkg/signoz/provider.go
  pkg/sqlmigration/014_add_alertmanager.go
  pkg/sqlmigration/020_pat_update.go
  pkg/sqlstore/sqlitesqlstore/dialect.go
  pkg/sqlstore/sqlstore.go
  pkg/sqlstore/sqlstoretest/dialect.go
  pkg/types/personal_access_token.go
Labels: chore

#7456 fix: licenses in community edition & improve messaging
  frontend/src/AppRoutes/index.tsx
  frontend/src/container/CustomDomainSettings/CustomDomainSettings.tsx
  frontend/src/container/Home/DataSourceInfo/DataSourceInfo.tsx
  frontend/src/container/IngestionSettings/MultiIngestionSettings.tsx
  frontend/src/container/OnboardingV2Container/IngestionDetails/IngestionDetails.tsx
  frontend/src/container/SideNav/SideNav.styles.scss
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/hooks/CustomDomain/useGetDeploymentsData.ts
  frontend/src/hooks/useGetTenantLicense.ts
  frontend/src/index.tsx
  frontend/src/pages/Settings/index.tsx
  frontend/src/pages/Settings/utils.ts
  pkg/http/render/render.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
Labels: bug, enhancement

#7485 feat: support request data source and improve layout
  frontend/src/container/OnboardingV2Container/AddDataSource/AddDataSource.tsx
  frontend/src/container/OnboardingV2Container/OnboardingV2.styles.scss
  frontend/src/container/OnboardingV2Container/onboarding-configs/onboarding-config-with-links.json
  frontend/src/periscope.scss
Labels: enhancement, docs not required

#7494 fix: handle maintenance windows that cross day boundaries
  pkg/query-service/rules/maintenance.go
  pkg/query-service/rules/maintenance_test.go
Labels: bug

#7405 chore: add info icon tool tips for webhook/routing/integration key
  frontend/public/locales/en-GB/channels.json
  frontend/public/locales/en/channels.json
  frontend/src/container/AllAlertChannels/__tests__/CreateAlertChannel.test.tsx
  frontend/src/container/AllAlertChannels/__tests__/CreateAlertChannelNormalUser.test.tsx
  frontend/src/container/AllAlertChannels/__tests__/EditAlertChannel.test.tsx
  frontend/src/container/FormAlertChannels/Settings/MsTeams.tsx
  frontend/src/container/FormAlertChannels/Settings/Opsgenie.tsx
  frontend/src/container/FormAlertChannels/Settings/Pager.tsx
  frontend/src/container/FormAlertChannels/Settings/Slack.tsx
  frontend/src/container/FormAlertChannels/Settings/Webhook.tsx
Labels: chore

#7514 fix: do not crash service on panic during rule eval
  pkg/query-service/rules/prom_rule_task.go
  pkg/query-service/rules/rule_task.go
Labels: bug

#7513 feat(sqlmigration): update the alertmanager tables
  ee/sqlstore/postgressqlstore/dialect.go
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanagerstore/sqlalertmanagerstore/config.go
  pkg/alertmanager/api.go
  pkg/alertmanager/legacyalertmanager/provider.go
  pkg/alertmanager/signozalertmanager/provider.go
  pkg/signoz/provider.go
  pkg/sqlmigration/021_update_alertmanager.go
  pkg/sqlstore/sqlitesqlstore/dialect.go
  pkg/sqlstore/sqlstore.go
  pkg/sqlstore/sqlstoretest/dialect.go
  pkg/types/alertmanagertypes/channel.go
  pkg/types/alertmanagertypes/config.go
  pkg/types/alertmanagertypes/state.go
Labels: enhancement

#7516 feat(preference): multi tenant preference module
  ee/query-service/app/api/api.go
  ee/query-service/app/server.go
  ee/sqlstore/postgressqlstore/dialect.go
  pkg/modules/preference/api.go
  pkg/modules/preference/core/preference.go
  pkg/modules/preference/core/store.go
  pkg/modules/preference/usecase.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/preferences/map.go
  pkg/query-service/app/preferences/model.go
  pkg/query-service/app/server.go
  pkg/signoz/provider.go
  pkg/sqlmigration/021_update_alertmanager.go
  pkg/sqlmigration/022_update_preferences.go
  pkg/sqlmigration/sqlmigration.go
  pkg/sqlstore/sqlitesqlstore/dialect.go
  pkg/sqlstore/sqlstore.go
  pkg/sqlstore/sqlstoretest/dialect.go
  pkg/types/preference.go
  pkg/types/preferencetypes/preference.go
  pkg/types/preferencetypes/value.go
Labels: enhancement

#7517 feat(sqlmigration): update apdex and TTL status tables
  ee/query-service/app/db/reader.go
  ee/query-service/app/server.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/dao/sqlite/apdex.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/telemetry/telemetry.go
  pkg/query-service/tests/integration/filter_suggestions_test.go
  pkg/query-service/tests/integration/signoz_cloud_integrations_test.go
  pkg/query-service/tests/integration/signoz_integrations_test.go
  pkg/query-service/tests/integration/test_utils.go
  pkg/signoz/provider.go
  pkg/sqlmigration/023_update_apdex_ttl.go
  pkg/types/dashboard.go
  pkg/types/organization.go
Labels: enhancement

#7518 feat(sqlmigration): update the user related tables according to new schema
  ee/query-service/app/api/pat.go
  ee/query-service/dao/interface.go
  ee/query-service/dao/sqlite/pat.go
  ee/sqlstore/postgressqlstore/dialect.go
  ee/types/personal_access_token.go
  pkg/query-service/auth/auth.go
  pkg/query-service/telemetry/telemetry.go
  pkg/signoz/provider.go
  pkg/sqlmigration/019_update_invites.go
  pkg/sqlmigration/021_update_alertmanager.go
  pkg/sqlmigration/023_update_apdex_ttl.go
  pkg/sqlmigration/024_update_reset_password.go
  pkg/sqlstore/sqlitesqlstore/dialect.go
  pkg/sqlstore/sqlstore.go
  pkg/sqlstore/sqlstoretest/dialect.go
  pkg/types/user.go
Labels: enhancement

#7524 fix: disable sidenav items for cloud users whose license has expired
  frontend/src/providers/App/App.tsx
Labels: bug, request-more-info

#7526 fix(dashboards): remove ff interface
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/http_handler.go
Labels: bug

#7527 chore(ff): remove unused SMART_TRACE_DETAIL feature flag
  ee/query-service/app/api/api.go
  ee/query-service/app/api/traces.go
  ee/query-service/app/db/reader.go
  ee/query-service/app/server.go
  ee/query-service/model/plans.go
  frontend/src/constants/features.ts
  frontend/src/tests/test-utils.tsx
  go.mod
  go.sum
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/querier/v2/querier_test.go
  pkg/query-service/app/server.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/featureSet.go
  pkg/query-service/rules/threshold_rule_test.go
  pkg/query-service/tests/integration/filter_suggestions_test.go
  pkg/query-service/tests/integration/signoz_cloud_integrations_test.go
  pkg/query-service/tests/integration/signoz_integrations_test.go
  pkg/query-service/tests/integration/test_utils.go
Labels: enhancement, chore

#7528 fix(ff): remove prefer rpm
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v3/query_builder_test.go
  pkg/query-service/app/logs/v4/query_builder.go
  pkg/query-service/app/logs/v4/query_builder_test.go
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/app/querier/helper.go
  pkg/query-service/app/querier/v2/helper.go
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/app/traces/v3/query_builder_test.go
  pkg/query-service/app/traces/v4/query_builder.go
  pkg/query-service/constants/constants.go
  pkg/query-service/model/v3/v3.go
Labels: bug

#7529 fix(ff): remove feature interface from ruler
  ee/query-service/anomaly/seasonal.go
  ee/query-service/app/api/queryrange.go
  ee/query-service/app/server.go
  ee/query-service/rules/anomaly.go
  ee/query-service/rules/manager.go
  pkg/query-service/app/server.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/test_notification.go
  pkg/query-service/rules/threshold_rule.go
  pkg/query-service/rules/threshold_rule_test.go
Labels: bug, enhancement

#7530 fix(duration|timestamp): remove duration/timestamp sort
  frontend/src/constants/features.ts
  frontend/src/tests/test-utils.tsx
  pkg/query-service/constants/constants.go
Labels: bug

#7531 fix(querier): remove ff
  ee/query-service/anomaly/daily.go
  ee/query-service/anomaly/hourly.go
  ee/query-service/anomaly/seasonal.go
  ee/query-service/anomaly/weekly.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/querier/v2/querier.go
  pkg/query-service/app/querier/v2/querier_test.go
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
Labels: bug

#7554 feat(valuer): add string valuer
  pkg/valuer/string.go
  pkg/valuer/uuid.go
  pkg/valuer/valuer.go
Labels: enhancement

#7553 chore: error log on query error
  pkg/telemetrystore/telemetrystorehook/logging.go
Labels: chore

#7532 chore(ff): remove some more unused ffs
  ee/query-service/model/license.go
  ee/query-service/model/license_test.go
  ee/query-service/model/plans.go
  frontend/src/constants/features.ts
  frontend/src/container/FormAlertChannels/index.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/OrganizationSettings/index.tsx
  frontend/src/tests/test-utils.tsx
  pkg/query-service/constants/constants.go
  pkg/query-service/featureManager/manager.go
  pkg/query-service/model/featureSet.go
Labels: chore

#7538 chore: add generated parser files for go
  go.mod
  go.sum
  grammar/FilterQuery.g4
  pkg/parser/grammar/FilterQuery.interp
  pkg/parser/grammar/FilterQuery.tokens
  pkg/parser/grammar/FilterQueryLexer.interp
  pkg/parser/grammar/FilterQueryLexer.tokens
  pkg/parser/grammar/filterquery_base_listener.go
  pkg/parser/grammar/filterquery_base_visitor.go
  pkg/parser/grammar/filterquery_lexer.go
  pkg/parser/grammar/filterquery_listener.go
  pkg/parser/grammar/filterquery_parser.go
  pkg/parser/grammar/filterquery_visitor.go
  scripts/grammar/generate-go-parser.sh
Labels: chore

#7552 chore: add field type definitions for qb v5
  go.mod
  go.sum
  pkg/types/querybuildertypes/querybuildertypesv5/qb.go
  pkg/types/telemetrytypes/field.go
  pkg/types/telemetrytypes/field_context.go
  pkg/types/telemetrytypes/field_datatype.go
  pkg/types/telemetrytypes/field_test.go
  pkg/types/telemetrytypes/signal.go
  pkg/types/telemetrytypes/store.go
  pkg/types/telemetrytypes/telemetrystmt.go
Labels: chore

#7567 Revert "fix: reevaluated newdashboard bool to ensure that widget doesn't exist, incase of a prior PUT call"
  frontend/src/container/NewWidget/index.tsx
Labels: bug

#7571 chore(build): include missing LDFLAGS in the community/enterprise builds
  .github/workflows/build-community.yaml
  .github/workflows/build-enterprise.yaml
Labels: chore

#7582 feat: include tenant_url in event attributes for logging
  frontend/src/api/common/logEvent.ts
Labels: enhancement, docs required

#7555 chore: add non-json condition builder for logs v2
  pkg/telemetrylogs/condition_builder.go
  pkg/telemetrylogs/condition_builder_test.go
  pkg/telemetrylogs/tables.go
  pkg/types/querybuildertypes/querybuildertypesv5/qb.go
  pkg/types/telemetrytypes/field.go
Labels: chore

#7586 chore: add virtual fields table
  pkg/query-service/utils/testutils.go
  pkg/signoz/provider.go
  pkg/sqlmigration/025_add_virtual_fields.go
  pkg/types/telemetrytypes/virtualfield.go
Labels: chore

#7556 chore: add condition builder for span index v3
  pkg/telemetrytraces/condition_builder.go
  pkg/telemetrytraces/condition_builder_test.go
  pkg/telemetrytraces/tables.go
Labels: chore

#7557 chore: add materialized field extractor from table schema
  pkg/telemetrymetadata/stmt_parse.go
  pkg/telemetrymetadata/stmt_parse_test.go
Labels: chore

#7558 chore: add condition builder attributes metadata
  pkg/telemetrymetadata/condition_builder.go
  pkg/telemetrymetadata/condition_builder_test.go
  pkg/telemetrytraces/condition_builder.go
Labels: chore

#7559 chore: add metadatastore implementation for logs and traces
  pkg/telemetrymetadata/metadata.go
  pkg/telemetrymetadata/metadata_test.go
  pkg/telemetrymetadata/tables.go
  pkg/telemetrymetrics/tables.go
Labels: chore

#7566 fix: remove unnecssary code for email domain check error
  ee/query-service/dao/sqlite/auth.go
Labels: bug

#7522 chore: add tag type filter support in attribute keys
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/parser_test.go
  pkg/query-service/model/v3/v3.go
Labels: chore

#7603 fix: missing receivers in json payload for legacy postableAlert
  pkg/alertmanager/legacyalertmanager/provider.go
  pkg/alertmanager/legacyalertmanager/provider_test.go
Labels: bug

#7507 feat(integrations): multitenancy in integrations
  ee/query-service/app/api/cloudIntegrations.go
  ee/query-service/app/api/pat.go
  ee/query-service/dao/interface.go
  ee/query-service/dao/sqlite/auth.go
  ee/query-service/dao/sqlite/pat.go
  ee/sqlstore/postgressqlstore/dialect.go
  pkg/query-service/app/cloudintegrations/accountsRepo.go
  pkg/query-service/app/cloudintegrations/controller.go
  pkg/query-service/app/cloudintegrations/controller_test.go
  pkg/query-service/app/cloudintegrations/model.go
  pkg/query-service/app/cloudintegrations/serviceConfigRepo.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/integrations/controller.go
  pkg/query-service/app/integrations/manager.go
  pkg/query-service/app/integrations/manager_test.go
  pkg/query-service/app/integrations/repo.go
  pkg/query-service/app/integrations/sqlite_repo.go
  pkg/query-service/app/integrations/test_utils.go
  pkg/query-service/app/logparsingpipeline/controller.go
  pkg/query-service/auth/auth.go
  pkg/query-service/auth/rbac.go
  pkg/query-service/tests/integration/signoz_cloud_integrations_test.go
  pkg/query-service/tests/integration/test_utils.go
  pkg/query-service/utils/testutils.go
  pkg/signoz/provider.go
  pkg/sqlmigration/026_update_integrations.go
  pkg/sqlmigration/sqlmigration.go
  pkg/sqlstore/sqlitesqlstore/dialect.go
  pkg/types/integration.go
Labels: chore, docs not required

#7611 fix(integrations): add check for empty services
  pkg/sqlmigration/026_update_integrations.go
Labels: bug

#7591 chore: enhancing JSON Parser handling
  go.mod
  go.sum
  pkg/query-service/app/logparsingpipeline/pipelineBuilder.go
  pkg/query-service/app/logparsingpipeline/pipelineBuilder_test.go
Labels: enhancement

#7637 chore(build-staging): only include telemetry tunnel FE envs
  .github/workflows/build-staging.yaml
Labels: chore

#7640 chore(prereleaser): update cron schedule - 6:30AM UTC
  .github/workflows/prereleaser.yaml
Labels: chore

#7641 chore: log original query failed to transform
  pkg/query-service/app/parser.go
Labels: chore

#7653 fix: proper formatting of floating point
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug, safe-to-integrate

#7564 chore: add where clause visitor implementation for query expression
  grammar/FilterQuery.g4
  pkg/parser/grammar/FilterQuery.interp
  pkg/parser/grammar/FilterQuery.tokens
  pkg/parser/grammar/FilterQueryLexer.interp
  pkg/parser/grammar/FilterQueryLexer.tokens
  pkg/parser/grammar/filterquery_lexer.go
  pkg/parser/grammar/filterquery_parser.go
  pkg/parser/grammar/query_to_keys.go
  pkg/parser/grammar/query_to_keys_test.go
  pkg/parser/grammar/where_clause_visitor.go
  pkg/parser/grammar/where_clause_visitor_test.go
  pkg/telemetrylogs/condition_builder.go
  pkg/telemetrylogs/condition_builder_test.go
  pkg/telemetrylogs/const.go
  pkg/types/telemetrytypes/field.go
  pkg/types/telemetrytypes/field_datatype.go
Labels: chore

#7667 feat: update callback url for billing
  frontend/src/components/ChatSupportGateway/ChatSupportGateway.tsx
  frontend/src/components/LaunchChatSupport/LaunchChatSupport.tsx
  frontend/src/container/BillingContainer/BillingContainer.tsx
  frontend/src/pages/Support/Support.tsx
  frontend/src/pages/WorkspaceLocked/WorkspaceLocked.tsx
Labels: enhancement, docs not required

#7560 chore: add API endpoints for fields keys and values
  ee/query-service/app/api/api.go
  ee/query-service/app/server.go
  pkg/apis/fields/api.go
  pkg/apis/fields/parse.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/telemetrymetadata/metadata.go
  pkg/telemetrymetadata/metadata_test.go
  pkg/types/telemetrytypes/field.go
Labels: chore, staging:patient-bat

#7649 chore: deprecate stagingapp/testingapp
  .github/workflows/staging-deployment.yaml
  .github/workflows/testing-deployment.yaml
  deploy/docker/docker-compose.testing.yaml
Labels: chore

#7673 feat: show notification for alert rule ID logic change
  frontend/src/container/Home/Home.tsx
Labels: enhancement, request-more-info, docs not required

#7661 feat: implement graph popover and expanded view panel
  frontend/src/api/metricsExplorer/getInspectMetricsDetails.ts
  frontend/src/container/MetricsExplorer/Inspect/ExpandedView.tsx
  frontend/src/container/MetricsExplorer/Inspect/GraphPopover.tsx
  frontend/src/container/MetricsExplorer/Inspect/GraphView.tsx
  frontend/src/container/MetricsExplorer/Inspect/Inspect.styles.scss
  frontend/src/container/MetricsExplorer/Inspect/Inspect.tsx
  frontend/src/container/MetricsExplorer/Inspect/QueryBuilder.tsx
  frontend/src/container/MetricsExplorer/Inspect/types.ts
  frontend/src/container/MetricsExplorer/Inspect/useInspectMetrics.ts
  frontend/src/container/MetricsExplorer/Inspect/utils.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
Labels: enhancement

#7584 feat: implement custom query builder for inspect metrics
  frontend/src/api/metricsExplorer/getInspectMetricsDetails.ts
  frontend/src/container/MetricsExplorer/Inspect/ExpandedView.tsx
  frontend/src/container/MetricsExplorer/Inspect/GraphPopover.tsx
  frontend/src/container/MetricsExplorer/Inspect/GraphView.tsx
  frontend/src/container/MetricsExplorer/Inspect/Inspect.styles.scss
  frontend/src/container/MetricsExplorer/Inspect/Inspect.tsx
  frontend/src/container/MetricsExplorer/Inspect/QueryBuilder.tsx
  frontend/src/container/MetricsExplorer/Inspect/Stepper.tsx
  frontend/src/container/MetricsExplorer/Inspect/constants.ts
  frontend/src/container/MetricsExplorer/Inspect/types.ts
  frontend/src/container/MetricsExplorer/Inspect/useInspectMetrics.ts
  frontend/src/container/MetricsExplorer/Inspect/utils.tsx
  frontend/src/container/MetricsExplorer/Summary/Summary.tsx
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.intefaces.ts
  frontend/src/container/QueryBuilder/filters/AggregatorFilter/AggregatorFilter.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
Labels: enhancement

#7589 Introduce new Resource Attribute FIlter in exceptions tab
  frontend/src/components/QuickFilters/QuickFilters.tsx
  frontend/src/components/QuickFilters/tests/QuickFilters.test.tsx
  frontend/src/components/QuickFilters/tests/__snapshots__/QuickFilters.test.tsx.snap
  frontend/src/components/QuickFilters/tests/constants.ts
  frontend/src/components/QuickFilters/types.ts
  frontend/src/constants/localStorage.ts
  frontend/src/constants/queryBuilder.ts
  frontend/src/constants/resourceAttributes.ts
  frontend/src/container/AllError/index.tsx
  frontend/src/container/AllError/tests/AllError.test.tsx
  frontend/src/container/AllError/tests/constants.ts
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
  frontend/src/container/QueryBuilder/filters/utils.ts
  frontend/src/container/ResourceAttributeFilterV2/ResourceAttributesFilter.styles.scss
  frontend/src/container/ResourceAttributeFilterV2/ResourceAttributesFilterV2.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/hooks/useResourceAttribute/utils.ts
  frontend/src/pages/AllErrors/AllErrors.styles.scss
  frontend/src/pages/AllErrors/index.tsx
  frontend/src/pages/AllErrors/utils.tsx
Labels: enhancement, staging:adapted-tetra

#7668 fix: boolean values are not shown in the list panel's column
  frontend/src/periscope/components/LineClampedText/LineClampedText.tsx
  frontend/src/periscope/components/LineClampedText/__test__/LineClampedText.test.tsx
Labels: bug

#7687 chore: update copy webpack plugin
  frontend/package.json
  frontend/yarn.lock
Labels: chore

#7691 Resource attr filter: style fix and quick filter changes
  frontend/src/pages/AllErrors/index.tsx
  frontend/src/pages/AllErrors/utils.tsx
Labels: bug

#7695 fix: handle rate operators for table panel
  pkg/query-service/app/logs/v3/query_builder.go
  pkg/query-service/app/logs/v4/query_builder.go
  pkg/query-service/app/logs/v4/query_builder_test.go
  pkg/query-service/app/traces/v4/query_builder.go
  pkg/query-service/app/traces/v4/query_builder_test.go
Labels: bug

#7701 Fix error rate for Third Party API
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/integrations/thirdPartyApi/translator.go
Labels: request-more-info, safe-to-test

#7680 chore: use attributes table for metric keys and values
  pkg/apis/fields/api.go
  pkg/parser/grammar/where_clause_visitor.go
  pkg/parser/grammar/where_clause_visitor_test.go
  pkg/telemetrymetadata/condition_builder.go
  pkg/telemetrymetadata/metadata.go
  pkg/telemetrymetadata/metadata_test.go
  pkg/telemetrymetrics/tables.go
Labels: chore

#7689 chore: always add reserved vars
  go.mod
  go.sum
  pkg/variables/clickhouse/transform.go
  pkg/variables/reserved_vars.go
Labels: chore

#7676 fix: query builder in metrics explorer picking up wrong datasource
  frontend/src/container/MetricsExplorer/Explorer/Explorer.tsx
  frontend/src/container/MetricsExplorer/Explorer/__tests__/Explorer.test.tsx
  frontend/src/container/MetricsExplorer/Summary/Summary.tsx
  frontend/src/pages/MetricsExplorer/MetricsExplorerPage.tsx
Labels: bug

#7659 chore: added new datasources
  frontend/public/Logos/amazon-msk.svg
  frontend/public/Logos/api-gateway.svg
  frontend/public/Logos/aws-alb.svg
  frontend/public/Logos/celery.svg
  frontend/public/Logos/clickhouse.svg
  frontend/public/Logos/confluent-kafka.svg
  frontend/public/Logos/elasticache.svg
  frontend/public/Logos/kafka.svg
  frontend/public/Logos/mongo.svg
  frontend/public/Logos/nginx.svg
  frontend/public/Logos/nuxtjs.svg
  frontend/public/Logos/postgresql.svg
  frontend/public/Logos/quickstart.svg
  frontend/public/Logos/reactjs.svg
  frontend/public/Logos/redis.svg
  frontend/public/Logos/strimzi.svg
  frontend/src/container/OnboardingV2Container/AddDataSource/AddDataSource.tsx
  frontend/src/container/OnboardingV2Container/onboarding-configs/onboarding-config-with-links.json
Labels: chore

#7684 feat(organization): schema changes for the organizations entity
  ee/query-service/app/api/api.go
  ee/query-service/app/api/auth.go
  ee/query-service/integrations/signozio/signozio.go
  ee/query-service/usage/manager.go
  ee/sqlstore/postgressqlstore/dialect.go
  frontend/src/AppRoutes/index.tsx
  frontend/src/api/user/editOrg.ts
  frontend/src/container/CustomDomainSettings/CustomDomainSettings.tsx
  frontend/src/container/OnboardingQuestionaire/OrgQuestions/OrgQuestions.tsx
  frontend/src/container/OnboardingQuestionaire/index.tsx
  frontend/src/container/OnboardingV2Container/AddDataSource/AddDataSource.tsx
  frontend/src/container/OrganizationSettings/DisplayName/index.tsx
  frontend/src/container/OrganizationSettings/index.tsx
  frontend/src/pages/SignUp/SignUp.tsx
  frontend/src/providers/App/App.tsx
  frontend/src/tests/test-utils.tsx
  frontend/src/types/api/user/editOrg.ts
  frontend/src/types/api/user/getInviteDetails.ts
  frontend/src/types/api/user/getOrganization.ts
  frontend/src/types/api/user/signup.ts
  frontend/src/types/common/index.ts
  frontend/tests/fixtures/common.ts
  pkg/modules/organization/implorganization/api.go
  pkg/modules/organization/implorganization/module.go
  pkg/modules/organization/implorganization/store.go
  pkg/modules/organization/organization.go
  pkg/modules/preference/api.go
  pkg/modules/preference/usecase.go
  pkg/query-service/app/cloudintegrations/controller_test.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/integrations/manager_test.go
  pkg/query-service/app/integrations/test_utils.go
  pkg/query-service/app/logparsingpipeline/db.go
  pkg/query-service/app/parser.go
  pkg/query-service/app/server.go
  pkg/query-service/auth/auth.go
  pkg/query-service/dao/interface.go
  pkg/query-service/dao/sqlite/connection.go
  pkg/query-service/dao/sqlite/rbac.go
  pkg/query-service/tests/integration/filter_suggestions_test.go
  pkg/query-service/tests/integration/logparsingpipeline_test.go
  pkg/query-service/tests/integration/signoz_cloud_integrations_test.go
  pkg/query-service/tests/integration/signoz_integrations_test.go
  pkg/query-service/tests/integration/test_utils.go
  pkg/query-service/utils/testutils.go
  pkg/signoz/provider.go
  pkg/sqlmigration/028_update_organizations.go
  pkg/sqlstore/sqlitesqlstore/dialect.go
  pkg/sqlstore/sqlstore.go
  pkg/sqlstore/sqlstoretest/dialect.go
  pkg/types/organization.go
Labels: enhancement, safe-to-integrate

#7497 feat: added custom single and multiselect components
  frontend/src/components/NewSelect/CustomMultiSelect.scss
  frontend/src/components/NewSelect/CustomMultiSelect.tsx
  frontend/src/components/NewSelect/CustomSelect.tsx
  frontend/src/components/NewSelect/__test__/CustomMultiSelect.test.tsx
  frontend/src/components/NewSelect/__test__/CustomSelect.test.tsx
  frontend/src/components/NewSelect/index.ts
  frontend/src/components/NewSelect/styles.scss
  frontend/src/components/NewSelect/types.ts
  frontend/src/components/NewSelect/utils.ts
Labels: enhancement, docs not required

#7736 feat: added permission restriction for viewer for planned Maintaince
  frontend/src/container/PlannedDowntime/PlannedDowntime.tsx
  frontend/src/container/PlannedDowntime/__test__/PlannedDowntime.test.tsx
Labels: enhancement, docs not required

#7743 chore(conf): add clickhouse settings
  conf/example.yaml
Labels: chore

#7739 chore: remove references to unused flags
  .github/workflows/README.md
  .github/workflows/remove-label.yaml
  ee/query-service/app/api/api.go
  ee/query-service/app/server.go
  ee/query-service/main.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/constants/constants.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/main.go
  pkg/query-service/model/auth.go
  pkg/query-service/model/config.go
  pkg/query-service/model/db.go
  pkg/query-service/rules/manager.go
Labels: chore, safe-to-integrate

#7747 fix(organization): return display name instead of name for organization
  pkg/query-service/dao/sqlite/rbac.go
Labels: bug, safe-to-integrate

#7741 chore(use-*): remove use-new-traces-schema and use-new-logs-schema flags
  ee/query-service/app/api/api.go
  ee/query-service/app/db/reader.go
  ee/query-service/app/server.go
  ee/query-service/main.go
  ee/query-service/rules/manager.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/querier/helper.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/querier/v2/helper.go
  pkg/query-service/app/querier/v2/querier.go
  pkg/query-service/app/querier/v2/querier_test.go
  pkg/query-service/app/server.go
  pkg/query-service/main.go
  pkg/query-service/rules/manager.go
  pkg/query-service/rules/test_notification.go
  pkg/query-service/rules/threshold_rule.go
  pkg/query-service/rules/threshold_rule_test.go
  pkg/query-service/tests/integration/test_utils.go
Labels: chore, safe-to-integrate

#7751 fix(ruler): telemetry for rules
  pkg/ruler/rulestore/sqlrulestore/rule.go
Labels: bug, safe-to-integrate

#7579 feat: init userpilot
  frontend/package.json
  frontend/src/AppRoutes/index.tsx
  frontend/webpack.config.js
  frontend/webpack.config.prod.js
  frontend/yarn.lock
Labels: enhancement, docs required

#7754 fix(zeus): build pipelines LD flags
  .github/workflows/build-enterprise.yaml
  .github/workflows/build-staging.yaml
  ee/query-service/.goreleaser.yaml
Labels: bug

#7427 fix: black gap on on cloud in sidebar (#7383)
  frontend/src/container/SideNav/SideNav.styles.scss
Labels: safe-to-test

#7767 fix: nil pointer error on failed to create rule
  ee/query-service/rules/manager.go
Labels: bug, request-more-info

#7768 fix(sentry): initialize sentry only once
  frontend/src/AppRoutes/index.tsx
Labels: enhancement, docs not required, staging:next-ewe

#7769 feat: added new datasources
  frontend/public/Logos/datadog.svg
  frontend/public/Logos/grafana.svg
  frontend/public/Logos/temporal.svg
  frontend/src/container/OnboardingV2Container/AddDataSource/AddDataSource.tsx
  frontend/src/container/OnboardingV2Container/onboarding-configs/onboarding-config-with-links.json
Labels: enhancement, docs required

#7771 fix: api monitoring cosmetic changes
  frontend/src/container/ApiMonitoring/APIMonitoringUtils.test.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/AllEndPoints.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/DomainDetails.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/TopErrors.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/DomainMetrics.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/components/EndPointMetrics.tsx
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainDetails/constants.ts
  frontend/src/container/ApiMonitoring/__tests__/AllEndPoints.test.tsx
  frontend/src/container/ApiMonitoring/__tests__/TopErrors.test.tsx
  frontend/src/container/ApiMonitoring/utils.tsx
Labels: bug, staging:blessed-wildcat
