Repository SigNoz/signoz, pull requests merged in 2025-01, with the labels that each got.

#6739 fix(frontend): do not use redirects outside the react router
  frontend/src/AppRoutes/Private.tsx
  frontend/src/AppRoutes/index.tsx
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
Labels: bug

#6586 feat: updated the logic for variable update queue
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.test.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/__test__/dashboardVariables.test.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/__test__/mock.ts
  frontend/src/container/NewDashboard/DashboardVariablesSelection/util.ts
Labels: enhancement, docs not required

#6671 feat: enable the new where clause for all the log based queries
  frontend/src/container/QueryBuilder/components/Query/Query.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
Labels: enhancement, docs not required

#6736 chore: add option skip web
  ee/query-service/app/server.go
  ee/query-service/main.go
Labels: chore

#6727 fix: added backticks for tags containing dots while generating query …
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/app/metrics/v4/cumulative/table_test.go
  pkg/query-service/app/metrics/v4/cumulative/timeseries_test.go
  pkg/query-service/app/metrics/v4/delta/table_test.go
  pkg/query-service/app/metrics/v4/delta/time_series_test.go
  pkg/query-service/app/metrics/v4/helpers/clauses.go
  pkg/query-service/app/metrics/v4/helpers/sub_query.go
  pkg/query-service/app/metrics/v4/query_builder_test.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
  pkg/query-service/utils/format.go
Labels: bug

#6733 feat: added new cache package for query service
  Makefile
  conf/defaults.yaml
  ee/query-service/app/server.go
  ee/query-service/main.go
  pkg/cache/cache.go
  pkg/cache/config.go
  pkg/cache/strategy/memory/memory.go
  pkg/cache/strategy/memory/memory_test.go
  pkg/cache/strategy/redis/redis.go
  pkg/cache/strategy/redis/redis_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/signoz/signoz.go
Labels: enhancement, docs not required

#6745 feat: support updating subdomain for tenants
  frontend/public/locales/en-GB/routes.json
  frontend/public/locales/en-GB/titles.json
  frontend/public/locales/en/routes.json
  frontend/public/locales/en/titles.json
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/api/customDomain/getDeploymentsData.ts
  frontend/src/api/customDomain/updateSubDomain.ts
  frontend/src/components/CustomTimePicker/TimezonePicker.tsx
  frontend/src/constants/routes.ts
  frontend/src/container/CustomDomainSettings/CustomDomainSettings.styles.scss
  frontend/src/container/CustomDomainSettings/CustomDomainSettings.tsx
  frontend/src/container/CustomDomainSettings/index.tsx
  frontend/src/container/PlannedDowntime/PlannedDowntimeutils.ts
  frontend/src/container/TopNav/Breadcrumbs/index.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/hooks/CustomDomain/useGetDeploymentsData.ts
  frontend/src/pages/Settings/config.tsx
  frontend/src/pages/Settings/utils.ts
  frontend/src/types/api/customDomain/types.ts
  frontend/src/utils/permission/index.ts
Labels: enhancement, docs not required

#6751 feat(generics): add a new performant resizable table
  frontend/package.json
  frontend/src/components/TableV3/TableV3.styles.scss
  frontend/src/components/TableV3/TableV3.tsx
  frontend/yarn.lock
Labels: enhancement

#6760 feat(timeline): add new timeline v2 component
  frontend/src/components/TimelineV2/TimelineV2.styles.scss
  frontend/src/components/TimelineV2/TimelineV2.tsx
  frontend/src/components/TimelineV2/utils.ts
Labels: enhancement, docs not required

#6765 feat: return if data is fetching
  frontend/src/container/CustomDomainSettings/CustomDomainSettings.tsx
Labels: enhancement, request-more-info, docs required

#6761 feat: enable billing and org-settings in workspace blocked state
  frontend/src/AppRoutes/Private.tsx
  frontend/src/container/SideNav/NavItem/NavItem.styles.scss
  frontend/src/container/SideNav/NavItem/NavItem.tsx
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/pages/Settings/index.tsx
  frontend/src/pages/Settings/utils.ts
  frontend/src/pages/WorkspaceLocked/WorkspaceLocked.styles.scss
  frontend/src/pages/WorkspaceLocked/WorkspaceLocked.tsx
Labels: enhancement, request-more-info, docs not required

#6770 fix(portal): use window.location.origin instead of the window.location.href
  frontend/src/container/AppLayout/index.tsx
Labels: bug

#6773 chore: fix cookie vulnerability
  frontend/package.json
  frontend/yarn.lock
Labels: bug, chore

#6775 fix: resolve k8s pods list local storage issue
  frontend/src/container/InfraMonitoringK8s/Pods/K8sPodLists.tsx
Labels: bug

#6787 feat: toggle off infra monitoring
  frontend/src/pages/InfrastructureMonitoring/InfrastructureMonitoringPage.tsx
Labels: enhancement, docs required

#6788 feat: updated the logic for variable update queue (#6586)
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.test.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/__test__/dashboardVariables.test.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/__test__/mock.ts
  frontend/src/container/NewDashboard/DashboardVariablesSelection/util.ts
Labels: enhancement, docs not required

#6790 chore: update default cloud plan text to Teams Cloud and Teams
  frontend/public/locales/en/billings.json
  frontend/src/container/BillingContainer/BillingContainer.tsx
Labels: chore

#6791 chore: added sentry alert for dashboard when query_range not called
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/providers/Dashboard/Dashboard.tsx
  frontend/src/providers/Dashboard/types.ts
Labels: chore

#6804 chore: update telemetry events
  ee/query-service/app/server.go
  frontend/src/container/LogsExplorerList/index.tsx
  frontend/src/container/TimeSeriesView/TimeSeriesView.tsx
  frontend/src/container/TracesExplorer/ListView/index.tsx
  frontend/src/container/TracesExplorer/TracesView/index.tsx
  frontend/src/pages/TracesExplorer/Filter/Filter.tsx
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/server.go
  pkg/query-service/model/response.go
  pkg/query-service/rules/db.go
  pkg/query-service/telemetry/telemetry.go
Labels: chore

#6789 feat(flamegraph): new trace details flamegraph
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/api/trace/getTraceFlamegraph.tsx
  frontend/src/components/TableV3/TableV3.tsx
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/PaginatedTraceFlamegraph/PaginatedTraceFlamegraph.styles.scss
  frontend/src/container/PaginatedTraceFlamegraph/PaginatedTraceFlamegraph.tsx
  frontend/src/container/PaginatedTraceFlamegraph/TraceFlamegraphStates/Error/Error.tsx
  frontend/src/container/PaginatedTraceFlamegraph/TraceFlamegraphStates/NoData/NoData.tsx
  frontend/src/container/PaginatedTraceFlamegraph/TraceFlamegraphStates/Success/Success.styles.scss
  frontend/src/container/PaginatedTraceFlamegraph/TraceFlamegraphStates/Success/Success.tsx
  frontend/src/container/PaginatedTraceFlamegraph/constants.ts
  frontend/src/container/TraceMetadata/TraceMetadata.styles.scss
  frontend/src/container/TraceMetadata/TraceMetadata.tsx
  frontend/src/container/TraceWaterfall/TraceWaterfall.tsx
  frontend/src/container/TraceWaterfall/TraceWaterfallStates/Success/Success.styles.scss
  frontend/src/container/TraceWaterfall/TraceWaterfallStates/Success/Success.tsx
  frontend/src/hooks/trace/useGetTraceFlamegraph.tsx
  frontend/src/pages/TraceDetailV2/TraceDetailV2.styles.scss
  frontend/src/pages/TraceDetailV2/TraceDetailV2.tsx
  frontend/src/pages/TraceDetailV2/index.tsx
  frontend/src/types/api/trace/getTraceFlamegraph.ts
  frontend/src/types/api/trace/getTraceV2.ts
  frontend/src/utils/timeUtils.ts
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/model/response.go
Labels: enhancement

#6744 chore: added series aggregation for group by with value type panel
  pkg/query-service/app/metrics/v4/helpers/series_agg_helper.go
  pkg/query-service/app/metrics/v4/query_builder.go
  pkg/query-service/app/metrics/v4/query_builder_test.go
  pkg/query-service/app/queryBuilder/query_builder.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
  pkg/query-service/model/v3/v3.go
Labels: enhancement, docs required

#6769 fix: fixed tables view not honouring order by in traces explorer
  frontend/src/lib/query/createTableColumnsFromQuery.ts
Labels: bug

#6617 feat: implement namespaces list table in infra monitoring
  frontend/src/api/infraMonitoring/getK8sNamespacesList.ts
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/container/InfraMonitoringK8s/InfraMonitoringK8s.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/K8sNamespacesList.styles.scss
  frontend/src/container/InfraMonitoringK8s/Namespaces/K8sNamespacesList.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/Events/NamespaceEvents.styles.scss
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/Events/NamespaceEvents.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/Events/NoEventsContainer.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/Events/constants.ts
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/Events/index.ts
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/Logs/NamespaceLogs.styles.scss
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/Logs/NamespaceLogs.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/Logs/NamespaceLogsDetailedView.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/Logs/NoLogsContainer.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/Logs/constants.ts
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/Logs/index.ts
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/Metrics/NamespaceMetrics.styles.scss
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/Metrics/NamespaceMetrics.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/Metrics/constants.ts
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/Metrics/index.ts
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/NamespaceDetails.interfaces.ts
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/NamespaceDetails.styles.scss
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/NamespaceDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/Traces/NamespaceTraces.styles.scss
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/Traces/NamespaceTraces.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/Traces/constants.ts
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/Traces/index.ts
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/constants.ts
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/index.ts
  frontend/src/container/InfraMonitoringK8s/Namespaces/utils.tsx
  frontend/src/container/InfraMonitoringK8s/commonUtils.tsx
  frontend/src/container/InfraMonitoringK8s/constants.ts
  frontend/src/hooks/infraMonitoring/useGetK8sNamespacesList.ts
Labels: enhancement, docs required

#6738 chore: add count based limits for metrics
  frontend/src/container/IngestionSettings/MultiIngestionSettings.tsx
  frontend/src/types/api/ingestionKeys/limits/types.ts
Labels: chore

#6841 fix(infra-monitoring): use proper axios instance for retrying the 401 req
  frontend/src/api/infraMonitoring/getHostLists.ts
Labels: bug

#6706 feat: update page titles for dashboards and alerts
  frontend/src/pages/AlertDetails/AlertDetails.tsx
  frontend/src/pages/NewDashboard/DashboardPage.tsx
Labels: docs not required

#6832 feat(factory): add factory package
  pkg/factory/config.go
  pkg/factory/config_test.go
  pkg/factory/name.go
  pkg/factory/name_test.go
  pkg/factory/named.go
  pkg/factory/named_test.go
  pkg/factory/provider.go
  pkg/factory/provider_test.go
  pkg/factory/service.go
  pkg/factory/servicetest/http.go
  pkg/factory/setting.go
Labels: enhancement

#6834 feat(instrumentation): use new config factory
  pkg/config/config.go
  pkg/config/unmarshaler_test.go
  pkg/instrumentation/config.go
  pkg/instrumentation/instrumentation.go
  pkg/instrumentation/instrumentationtest/instrumentation.go
  pkg/instrumentation/logger.go
  pkg/instrumentation/meter.go
  pkg/instrumentation/sdk.go
  pkg/instrumentation/tracer.go
Labels: enhancement

#6835 feat(sqlstore): add sqlstore package
  go.mod
  go.sum
  pkg/sqlstore/config.go
  pkg/sqlstore/sqlitesqlstore/provider.go
  pkg/sqlstore/sqlstore.go
  pkg/sqlstore/sqlstoretest/provider.go
Labels: enhancement

#6836 feat(sqlmigrator): add sqlmigrator package
  pkg/sqlmigrator/000_noop.go
  pkg/sqlmigrator/config.go
  pkg/sqlmigrator/migration.go
  pkg/sqlmigrator/migration/000_add_data_migrations.go
  pkg/sqlmigrator/migration/001_add_organization.go
  pkg/sqlmigrator/migration/002_add_preferences.go
  pkg/sqlmigrator/migration/003_add_dashboards.go
  pkg/sqlmigrator/migration/004_add_saved_views.go
  pkg/sqlmigrator/migration/005_add_agents.go
  pkg/sqlmigrator/migration/006_add_pipelines.go
  pkg/sqlmigrator/migration/007_add_integrations.go
  pkg/sqlmigrator/migrator.go
  pkg/sqlmigrator/migrator_test.go
  pkg/sqlmigrator/sqlmigrator.go
Labels: enhancement

#6689 fix: support in operator for json search
  pkg/query-service/app/logs/v3/enrich_query.go
  pkg/query-service/app/logs/v3/enrich_query_test.go
  pkg/query-service/app/logs/v4/json_filter_test.go
Labels: bug

#6795 chore: infra monitoring bug fixes
  frontend/src/api/infraMonitoring/getK8sNodesList.ts
  frontend/src/api/infraMonitoring/getK8sPodsList.ts
  frontend/src/container/InfraMonitoringK8s/InfraMonitoringK8s.styles.scss
  frontend/src/container/InfraMonitoringK8s/InfraMonitoringK8s.tsx
  frontend/src/container/InfraMonitoringK8s/K8sFiltersSidePanel/K8sFiltersSidePanel.tsx
  frontend/src/container/InfraMonitoringK8s/K8sHeader.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/K8sNodesList.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/Events/NodeEvents.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/NodeDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/utils.tsx
  frontend/src/container/InfraMonitoringK8s/Pods/K8sPodLists.tsx
  frontend/src/container/InfraMonitoringK8s/Pods/PodDetails/Events/Events.tsx
  frontend/src/container/InfraMonitoringK8s/Pods/PodDetails/PodDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Pods/PodDetails/PodTraces/PodTraces.tsx
  frontend/src/container/InfraMonitoringK8s/commonUtils.tsx
  frontend/src/container/InfraMonitoringK8s/constants.ts
  frontend/src/container/InfraMonitoringK8s/entityDetailUtils.ts
  frontend/src/container/InfraMonitoringK8s/utils.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
  frontend/src/hooks/queryBuilder/useAutoComplete.ts
  frontend/src/pages/InfrastructureMonitoring/InfrastructureMonitoringPage.tsx
Labels: bug, chore

#6822 chore: new alert rule documentation redirection tests
  frontend/src/container/AnomalyAlertEvaluationView/AnomalyAlertEvaluationView.tsx
  frontend/src/container/CreateAlertRule/AlertRuleDocumentationRedirection.test.tsx
  frontend/src/container/CreateAlertRule/AnomalyAlertDocumentationRedirection.test.tsx
  frontend/src/container/CreateAlertRule/constants.ts
Labels: chore

#6831 feat: show/hide timestamp and body fields in logs explorer (raw, default, column views)
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/TableView/useTableView.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/styles.ts
  frontend/src/container/OptionsMenu/constants.ts
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
Labels: enhancement, docs required

#6630 feat: statefulsets implementation for k8s infra monitoring
  frontend/src/api/infraMonitoring/getsK8sStatefulSetsList.ts
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/container/InfraMonitoringK8s/InfraMonitoringK8s.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/K8sStatefulSetsList.styles.scss
  frontend/src/container/InfraMonitoringK8s/StatefulSets/K8sStatefulSetsList.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/Events/NoEventsContainer.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/Events/StatefulSetEvents.styles.scss
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/Events/StatefulSetEvents.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/Events/constants.ts
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/Events/index.ts
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/Logs/NoLogsContainer.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/Logs/StatefulSetLogs.styles.scss
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/Logs/StatefulSetLogs.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/Logs/StatefulSetLogsDetailedView.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/Logs/constants.ts
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/Logs/index.ts
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/Metrics/StatefulSetMetrics.styles.scss
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/Metrics/StatefulSetMetrics.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/Metrics/constants.ts
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/Metrics/index.ts
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/StatefulSetDetails.interfaces.ts
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/StatefulSetDetails.styles.scss
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/StatefulSetDetails.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/Traces/StatefulSetTraces.styles.scss
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/Traces/StatefulSetTraces.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/Traces/constants.ts
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/Traces/index.ts
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/constants.ts
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/index.ts
  frontend/src/container/InfraMonitoringK8s/StatefulSets/utils.tsx
  frontend/src/container/InfraMonitoringK8s/constants.ts
  frontend/src/hooks/infraMonitoring/useGetK8sStatefulSetsList.ts
Labels: enhancement, docs required

#6856 fix: remove analytics schema migrations
  ee/query-service/app/server.go
  pkg/query-service/app/server.go
  pkg/query-service/migrate/migate.go
Labels: bug

#6810 feat: add search span scope in the list view tab to add the scope at per Query level
  pkg/query-service/app/traces/v4/query_builder.go
  pkg/query-service/app/traces/v4/query_builder_test.go
  pkg/query-service/constants/constants.go
  pkg/query-service/model/v3/v3.go
Labels: enhancement, docs shipped

#6857 chore(install-script): install.sh script improvements
  deploy/install.sh
Labels: chore

#6847 chore: correct order within page result
  pkg/query-service/app/inframetrics/clusters.go
  pkg/query-service/app/inframetrics/daemonsets.go
  pkg/query-service/app/inframetrics/deployments.go
  pkg/query-service/app/inframetrics/jobs.go
  pkg/query-service/app/inframetrics/namespaces.go
  pkg/query-service/app/inframetrics/nodes.go
  pkg/query-service/app/inframetrics/nodes_query.go
  pkg/query-service/app/inframetrics/pods.go
  pkg/query-service/app/inframetrics/pvcs.go
  pkg/query-service/app/inframetrics/statefulsets.go
  pkg/query-service/model/infra.go
Labels: chore

#6778 chore: clickhouse sql support for v3
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/clickhouseReader/wrapper.go
  pkg/query-service/app/querier/querier.go
  pkg/query-service/app/querier/v2/querier.go
  pkg/query-service/constants/constants.go
Labels: chore

#6862 fix: remove depricated message from ingestion dashboard
  pkg/query-service/app/dashboards/model.go
Labels: bug

#6864 fix: update azure event hub receiver config
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/AKS/aks-installCentralCollector.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/AppService/appService-installCentralCollector.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/BlobStorage/blobStorage-installCentralCollector.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/ContainerApps/containerApps-installCentralCollector.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/Functions/functions-installCentralCollector.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/SqlDatabaseMetrics/sqlDatabaseMetrics-installCentralCollector.md
  frontend/src/container/OnboardingContainer/Modules/AzureMonitoring/Vm/vm-installCentralCollector.md
Labels: bug

#6868 Revert "feat: show/hide timestamp and body fields in logs explorer (raw, default, column views)"
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/TableView/useTableView.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/styles.ts
  frontend/src/container/OptionsMenu/constants.ts
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
Labels: enhancement

#6871 chore: address some gaps in infra
  frontend/src/container/InfraMonitoringK8s/Clusters/K8sClustersList.tsx
  frontend/src/container/InfraMonitoringK8s/Deployments/K8sDeploymentsList.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/K8sNamespacesList.tsx
  pkg/query-service/app/inframetrics/clusters.go
  pkg/query-service/app/inframetrics/daemonsets.go
  pkg/query-service/app/inframetrics/deployments.go
  pkg/query-service/app/inframetrics/jobs.go
  pkg/query-service/app/inframetrics/namespaces.go
  pkg/query-service/app/inframetrics/nodes.go
  pkg/query-service/app/inframetrics/pods.go
  pkg/query-service/app/inframetrics/pvcs.go
  pkg/query-service/app/inframetrics/statefulsets.go
Labels: chore

#6622 feat: implement volumes list table in infra monitoring
  frontend/src/api/infraMonitoring/getK8sVolumesList.ts
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/container/InfraMonitoringK8s/InfraMonitoringK8s.tsx
  frontend/src/container/InfraMonitoringK8s/Volumes/K8sVolumesList.styles.scss
  frontend/src/container/InfraMonitoringK8s/Volumes/K8sVolumesList.tsx
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/Events/NoEventsContainer.tsx
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/Events/VolumeEvents.styles.scss
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/Events/VolumeEvents.tsx
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/Events/constants.ts
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/Events/index.ts
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/Logs/NoLogsContainer.tsx
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/Logs/VolumeLogs.styles.scss
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/Logs/VolumeLogs.tsx
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/Logs/VolumeLogsDetailedView.tsx
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/Logs/constants.ts
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/Logs/index.ts
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/Metrics/VolumeMetrics.styles.scss
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/Metrics/VolumeMetrics.tsx
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/Metrics/constants.ts
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/Metrics/index.ts
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/Traces/VolumeTraces.styles.scss
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/Traces/VolumeTraces.tsx
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/Traces/constants.ts
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/Traces/index.ts
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/VolumeDetails.styles.scss
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/VolumeDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/VoumeDetails.interfaces.ts
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/constants.ts
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/index.ts
  frontend/src/container/InfraMonitoringK8s/Volumes/utils.tsx
  frontend/src/container/InfraMonitoringK8s/constants.ts
  frontend/src/hooks/infraMonitoring/useGetK8sVolumesList.ts
Labels: enhancement

#6865 fix: use common logging middleware
  ee/query-service/app/server.go
  pkg/http/middleware/logging.go
  pkg/query-service/app/server.go
Labels: bug, enhancement, docs not required

#6866 fix: use common timeout middleware
  conf/example.yaml
  ee/query-service/app/server.go
  ee/query-service/main.go
  pkg/apiserver/config.go
  pkg/apiserver/config_test.go
  pkg/http/middleware/timeout.go
  pkg/http/middleware/timeout_test.go
  pkg/query-service/app/server.go
  pkg/query-service/app/server_test.go
  pkg/query-service/constants/constants.go
  pkg/query-service/constants/constants_test.go
  pkg/query-service/main.go
  pkg/signoz/config.go
Labels: bug

#6899 fix: move log comment middleware
  ee/query-service/app/server.go
  pkg/http/middleware/logging.go
  pkg/query-service/app/server.go
Labels: bug

#6901 fix: move analytics middleware
  ee/query-service/app/server.go
  pkg/http/middleware/analytics.go
  pkg/query-service/app/server.go
Labels: bug

#6906 feat(trace-details): query service changes for trace details
  ee/query-service/app/db/reader.go
  ee/query-service/app/server.go
  ee/query-service/main.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/querier/v2/querier_test.go
  pkg/query-service/app/server.go
  pkg/query-service/app/traces/tracedetail/flamegraph.go
  pkg/query-service/app/traces/tracedetail/waterfall.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/main.go
  pkg/query-service/model/cacheable.go
  pkg/query-service/model/queryParams.go
  pkg/query-service/model/response.go
  pkg/query-service/model/trace.go
  pkg/query-service/rules/threshold_rule_test.go
  pkg/query-service/tests/integration/test_utils.go
Labels: enhancement

#6869 fix: added safety check on uplot-xaxis logic to solve sentry issue
  frontend/src/lib/uPlotLib/utils/getUplotChartData.ts
Labels: bug

#6917 fix: logging middleware add excluded routes
  conf/example.yaml
  ee/query-service/app/server.go
  pkg/apiserver/config.go
  pkg/apiserver/config_test.go
  pkg/http/middleware/logging.go
  pkg/query-service/app/server.go
Labels: bug

#6907 feat(instrumentation): adopt slog
  conf/example.yaml
  go.mod
  go.sum
  pkg/errors/errors.go
  pkg/factory/setting.go
  pkg/instrumentation/config.go
  pkg/instrumentation/config_test.go
  pkg/instrumentation/instrumentation.go
  pkg/instrumentation/instrumentationtest/instrumentation.go
  pkg/instrumentation/logger.go
  pkg/instrumentation/loghandler/correlation.go
  pkg/instrumentation/loghandler/correlation_test.go
  pkg/instrumentation/loghandler/loghandler.go
  pkg/instrumentation/sdk.go
  pkg/sqlmigrator/migrator.go
  pkg/sqlstore/sqlitesqlstore/provider.go
Labels: enhancement

#6911 chore: integrate goreleaser for user_scripts and restructuring
  .github/workflows/goreleaser.yaml
  .gitignore
  Makefile
  deploy/docker/clickhouse-setup/user_scripts/.deprecated
  scripts/clickhouse/histogramquantile/.goreleaser.yaml
  scripts/clickhouse/histogramquantile/main.go
Labels: chore

#6840 feat: added celery task feature - with task graphs and details
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/components/CeleryTask/CeleryTaskConfigOptions/CeleryTaskConfigOptions.styles.scss
  frontend/src/components/CeleryTask/CeleryTaskConfigOptions/CeleryTaskConfigOptions.tsx
  frontend/src/components/CeleryTask/CeleryTaskConfigOptions/useGetCeleryFilters.ts
  frontend/src/components/CeleryTask/CeleryTaskDetail/CeleryTaskDetail.style.scss
  frontend/src/components/CeleryTask/CeleryTaskDetail/CeleryTaskDetail.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskBar.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskGraph.style.scss
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskGraph.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskGraphGrid.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskGraphUtils.ts
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskLatencyGraph.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskStateGraphConfig.tsx
  frontend/src/components/CeleryTask/CeleryUtils.ts
  frontend/src/components/CeleryTask/useCeleryFilterOptions.ts
  frontend/src/constants/query.ts
  frontend/src/constants/routes.ts
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCard/types.ts
  frontend/src/container/GridTableComponent/GridTableComponent.styles.scss
  frontend/src/container/GridTableComponent/index.tsx
  frontend/src/container/GridTableComponent/types.ts
  frontend/src/container/MetricsApplication/MetricsApplication.factory.ts
  frontend/src/container/MetricsApplication/types.ts
  frontend/src/container/PanelWrapper/HistogramPanelWrapper.tsx
  frontend/src/container/PanelWrapper/PanelWrapper.tsx
  frontend/src/container/PanelWrapper/TablePanelWrapper.tsx
  frontend/src/container/PanelWrapper/UplotPanelWrapper.tsx
  frontend/src/container/PanelWrapper/panelWrapper.types.ts
  frontend/src/container/SideNav/config.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
  frontend/src/lib/uPlotLib/getUplotHistogramChartOptions.ts
  frontend/src/lib/uPlotLib/utils/generateColor.ts
  frontend/src/pages/Celery/CeleryTask/CeleryTask.styles.scss
  frontend/src/pages/Celery/CeleryTask/CeleryTask.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MetricPage/MetricPageUtil.ts
  frontend/src/pages/MessagingQueues/MessagingQueues.styles.scss
  frontend/src/pages/MessagingQueues/MessagingQueues.tsx
  frontend/src/pages/MessagingQueues/MessagingQueuesMainPage.styles.scss
  frontend/src/pages/MessagingQueues/MessagingQueuesMainPage.tsx
  frontend/src/pages/MessagingQueues/index.tsx
  frontend/src/utils/permission/index.ts
Labels: enhancement, docs not required

#6918 feat: celery overview page
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/api/messagingQueues/celery/getQueueOverview.ts
  frontend/src/components/CeleryOverview/CeleryOverviewConfigOptions/CeleryOverviewConfigOptions.styles.scss
  frontend/src/components/CeleryOverview/CeleryOverviewConfigOptions/CeleryOverviewConfigOptions.tsx
  frontend/src/components/CeleryOverview/CeleryOverviewTable/CeleryOverviewTable.styles.scss
  frontend/src/components/CeleryOverview/CeleryOverviewTable/CeleryOverviewTable.tsx
  frontend/src/components/CeleryTask/CeleryTaskConfigOptions/useGetCeleryFilters.ts
  frontend/src/components/CeleryTask/useCeleryFilterOptions.ts
  frontend/src/constants/localStorage.ts
  frontend/src/constants/query.ts
  frontend/src/constants/routes.ts
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/SideNav/config.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/pages/Celery/CeleryOverview/CeleryOverview.styles.scss
  frontend/src/pages/Celery/CeleryOverview/CeleryOverview.tsx
  frontend/src/pages/MessagingQueues/MessagingQueuesMainPage.tsx
  frontend/src/utils/permission/index.ts
Labels: enhancement, docs not required

#6910 feat: add support for span scope
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/QueryBuilderSearch.styles.scss
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/SpanScopeSelector.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
Labels: enhancement, docs required

#6922 feat: changed the traces tab query to incorporate span scopes
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/app/traces/v3/query_builder_test.go
  pkg/query-service/app/traces/v4/query_builder.go
  pkg/query-service/app/traces/v4/query_builder_test.go
  pkg/query-service/constants/constants.go
Labels: enhancement, docs shipped

#6925 feat: Centralize and Standardize Date/Time Format Handling
  frontend/src/components/CustomTimePicker/CustomTimePicker.tsx
  frontend/src/components/CustomTimePicker/RangePickerModal.tsx
  frontend/src/components/Graph/index.tsx
  frontend/src/components/Graph/utils.ts
  frontend/src/components/HostMetricsDetail/HostMetricTraces/utils.tsx
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/TableView/useTableView.tsx
  frontend/src/components/ResizeTable/TableComponent/Time.tsx
  frontend/src/constants/dateTimeFormats.ts
  frontend/src/container/AlertHistory/Timeline/Graph/Graph.tsx
  frontend/src/container/AlertHistory/Timeline/Table/useTimelineTable.tsx
  frontend/src/container/AllError/index.tsx
  frontend/src/container/AnomalyAlertEvaluationView/tooltipPlugin.ts
  frontend/src/container/BillingContainer/BillingUsageGraph/generateCsvData.ts
  frontend/src/container/BillingContainer/BillingUsageGraph/utils.ts
  frontend/src/container/ErrorDetails/index.tsx
  frontend/src/container/GantChart/Span/index.tsx
  frontend/src/container/IngestionSettings/MultiIngestionSettings.tsx
  frontend/src/container/Licenses/ListLicenses.tsx
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/LogControls/index.tsx
  frontend/src/container/LogDetailedView/TableView/TableViewActions.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/OrganizationSettings/Members/index.tsx
  frontend/src/container/PipelinePage/Layouts/ChangeHistory/DeploymentTime.tsx
  frontend/src/container/PipelinePage/PipelineListsView/Preview/components/LogsList/index.tsx
  frontend/src/container/PipelinePage/PipelineListsView/TableComponents/index.tsx
  frontend/src/container/PipelinePage/PipelineListsView/utils.tsx
  frontend/src/container/PlannedDowntime/PlannedDowntimeForm.tsx
  frontend/src/container/PlannedDowntime/PlannedDowntimeutils.ts
  frontend/src/container/TopNav/DateTimeSelection/index.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/container/Trace/TraceTable/index.tsx
  frontend/src/container/TraceDetail/SelectedSpanDetails/Events/EventStartTime.tsx
  frontend/src/container/TraceDetail/index.tsx
  frontend/src/container/TracesExplorer/ListView/utils.tsx
  frontend/src/container/TriggeredAlerts/FilteredTable/ExapandableRow.tsx
  frontend/src/container/TriggeredAlerts/NoFilterTable.tsx
  frontend/src/hooks/useTimezoneFormatter/useTimezoneFormatter.ts
  frontend/src/lib/uPlotLib/plugins/tooltipPlugin.ts
  frontend/src/lib/uPlotLib/utils/constants.ts
  frontend/src/lib/uPlotLib/utils/getAxes.ts
  frontend/src/pages/Integrations/IntegrationDetailPage/IntegrationDetailHeader.tsx
  frontend/src/pages/SaveView/index.tsx
  frontend/src/utils/timeUtils.ts
Labels: enhancement, docs required

#6903 feat: show/hide timestamp and body fields in logs explorer (raw, default, column views)
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/components/Logs/TableView/useTableView.tsx
  frontend/src/components/LogsFormatOptionsMenu/LogsFormatOptionsMenu.tsx
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/index.tsx
  frontend/src/container/LogsExplorerList/InfinityTableView/styles.ts
  frontend/src/container/OptionsMenu/constants.ts
  frontend/src/container/OptionsMenu/types.ts
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
  frontend/src/pages/LogsExplorer/index.tsx
Labels: enhancement, docs required

#6629 feat: statefulsets, daemonsets, jobs and volumes implementation in k8s infra monitoring
  frontend/src/api/infraMonitoring/getK8sDaemonSetsList.ts
  frontend/src/api/infraMonitoring/getK8sJobsList.ts
  frontend/src/api/infraMonitoring/getK8sVolumesList.ts
  frontend/src/api/infraMonitoring/getsK8sStatefulSetsList.ts
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/container/InfraMonitoringK8s/DaemonSets/DaemonSetDetails/DaemonSetDetails.interfaces.ts
  frontend/src/container/InfraMonitoringK8s/DaemonSets/DaemonSetDetails/DaemonSetDetails.tsx
  frontend/src/container/InfraMonitoringK8s/DaemonSets/DaemonSetDetails/constants.ts
  frontend/src/container/InfraMonitoringK8s/DaemonSets/DaemonSetDetails/index.ts
  frontend/src/container/InfraMonitoringK8s/DaemonSets/K8sDaemonSetsList.styles.scss
  frontend/src/container/InfraMonitoringK8s/DaemonSets/K8sDaemonSetsList.tsx
  frontend/src/container/InfraMonitoringK8s/DaemonSets/utils.tsx
  frontend/src/container/InfraMonitoringK8s/Deployments/utils.tsx
  frontend/src/container/InfraMonitoringK8s/EntityDetailsUtils/entityDetails.styles.scss
  frontend/src/container/InfraMonitoringK8s/EntityDetailsUtils/utils.tsx
  frontend/src/container/InfraMonitoringK8s/InfraMonitoringK8s.tsx
  frontend/src/container/InfraMonitoringK8s/Jobs/JobDetails/JobDetails.interfaces.ts
  frontend/src/container/InfraMonitoringK8s/Jobs/JobDetails/JobDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Jobs/JobDetails/constants.ts
  frontend/src/container/InfraMonitoringK8s/Jobs/JobDetails/index.ts
  frontend/src/container/InfraMonitoringK8s/Jobs/K8sJobsList.styles.scss
  frontend/src/container/InfraMonitoringK8s/Jobs/K8sJobsList.tsx
  frontend/src/container/InfraMonitoringK8s/Jobs/utils.tsx
  frontend/src/container/InfraMonitoringK8s/K8sFiltersSidePanel/K8sFiltersSidePanel.styles.scss
  frontend/src/container/InfraMonitoringK8s/StatefulSets/K8sStatefulSetsList.styles.scss
  frontend/src/container/InfraMonitoringK8s/StatefulSets/K8sStatefulSetsList.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/StatefulSetDetails.interfaces.ts
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/StatefulSetDetails.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/constants.ts
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/index.ts
  frontend/src/container/InfraMonitoringK8s/StatefulSets/utils.tsx
  frontend/src/container/InfraMonitoringK8s/Volumes/K8sVolumesList.styles.scss
  frontend/src/container/InfraMonitoringK8s/Volumes/K8sVolumesList.tsx
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/VolumeDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/VoumeDetails.interfaces.ts
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/constants.ts
  frontend/src/container/InfraMonitoringK8s/Volumes/VolumeDetails/index.ts
  frontend/src/container/InfraMonitoringK8s/Volumes/utils.tsx
  frontend/src/container/InfraMonitoringK8s/constants.ts
  frontend/src/hooks/infraMonitoring/useGetK8sDaemonSetsList.ts
  frontend/src/hooks/infraMonitoring/useGetK8sJobsList.ts
  frontend/src/hooks/infraMonitoring/useGetK8sStatefulSetsList.ts
  frontend/src/hooks/infraMonitoring/useGetK8sVolumesList.ts
  pkg/query-service/app/inframetrics/daemonsets.go
  pkg/query-service/app/inframetrics/deployments.go
  pkg/query-service/app/inframetrics/jobs.go
  pkg/query-service/app/inframetrics/statefulsets.go
  pkg/query-service/app/metrics/v4/helpers/sub_query.go
  pkg/query-service/model/infra.go
Labels: enhancement, docs not required

#6950 feat: implement page size configuration in infra monitoring
  frontend/src/container/InfraMonitoringHosts/HostsList.tsx
  frontend/src/container/InfraMonitoringK8s/Clusters/K8sClustersList.tsx
  frontend/src/container/InfraMonitoringK8s/DaemonSets/K8sDaemonSetsList.tsx
  frontend/src/container/InfraMonitoringK8s/Deployments/K8sDeploymentsList.tsx
  frontend/src/container/InfraMonitoringK8s/InfraMonitoringK8s.styles.scss
  frontend/src/container/InfraMonitoringK8s/Jobs/K8sJobsList.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/K8sNamespacesList.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/K8sNodesList.tsx
  frontend/src/container/InfraMonitoringK8s/Pods/K8sPodLists.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/K8sStatefulSetsList.tsx
  frontend/src/container/InfraMonitoringK8s/Volumes/K8sVolumesList.tsx
  frontend/src/container/InfraMonitoringK8s/constants.ts
  frontend/src/container/InfraMonitoringK8s/utils.tsx
Labels: enhancement, docs not required

#6944 feat: added right panel graphs in overview page
  frontend/src/AppRoutes/routes.ts
  frontend/src/components/CeleryOverview/CeleryOverviewConfigOptions/CeleryOverviewConfigOptions.styles.scss
  frontend/src/components/CeleryOverview/CeleryOverviewConfigOptions/CeleryOverviewConfigOptions.tsx
  frontend/src/components/CeleryOverview/CeleryOverviewTable/CeleryOverviewTable.tsx
  frontend/src/components/CeleryTask/CeleryTaskConfigOptions/useGetCeleryFilters.ts
  frontend/src/components/CeleryTask/CeleryTaskDetail/CeleryTaskDetail.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskBar.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskGraph.style.scss
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskGraphUtils.ts
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskStateGraphConfig.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/useGetValueFromWidget.ts
  frontend/src/components/CeleryTask/useCeleryFilterOptions.ts
  frontend/src/components/CeleryTask/useNavigateToTraces.ts
  frontend/src/constants/query.ts
  frontend/src/constants/routes.ts
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/SideNav/config.ts
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/pages/Celery/CeleryOverview/CeleryOverview.tsx
  frontend/src/pages/Celery/CeleryOverview/CeleryOverviewDetail/CeleryOverviewDetails.styles.scss
  frontend/src/pages/Celery/CeleryOverview/CeleryOverviewDetail/CeleryOverviewDetails.tsx
  frontend/src/pages/Celery/CeleryOverview/CeleryOverviewDetail/OverviewRightPanelGraph.tsx
  frontend/src/pages/Celery/CeleryOverview/CeleryOverviewDetail/ValueInfo.styles.scss
  frontend/src/pages/Celery/CeleryOverview/CeleryOverviewDetail/ValueInfo.tsx
  frontend/src/pages/Celery/CeleryOverview/CeleryOverviewGraphUtils.ts
  frontend/src/pages/Celery/CeleryOverview/CeleryOverviewUtils.ts
  frontend/src/pages/MessagingQueues/MessagingQueuesMainPage.tsx
  frontend/src/utils/permission/index.ts
Labels: enhancement, docs not required

#6953 fix: adjust the buffer time for start and end time in trace to logs
  frontend/src/container/TraceDetail/SelectedSpanDetails/index.tsx
Labels: bug

#6851 feat: integrate AWS integration page API
  frontend/src/api/integrations/aws/index.ts
  frontend/src/container/CloudIntegrationPage/HeroSection/components/AccountActions.tsx
  frontend/src/container/CloudIntegrationPage/ServicesSection/ServiceDetails.tsx
  frontend/src/container/CloudIntegrationPage/ServicesSection/ServicesList.tsx
  frontend/src/container/CloudIntegrationPage/ServicesSection/ServicesTabs.tsx
  frontend/src/hooks/integrations/aws/useAccountStatus.ts
Labels: enhancement

#6854 feat: add documentation link for logs explorer quick filters
  frontend/src/assets/CustomIcons/EmptyQuickFilterIcon.tsx
  frontend/src/components/QuickFilters/FilterRenderers/Checkbox/Checkbox.styles.scss
  frontend/src/components/QuickFilters/FilterRenderers/Checkbox/Checkbox.tsx
  frontend/src/components/QuickFilters/FilterRenderers/Checkbox/LogsQuickFilterEmptyState.tsx
  frontend/src/components/QuickFilters/FilterRenderers/Slider/Slider.tsx
  frontend/src/components/QuickFilters/QuickFilters.tsx
  frontend/src/components/QuickFilters/types.ts
  frontend/src/container/InfraMonitoringK8s/InfraMonitoringK8s.tsx
  frontend/src/container/InfraMonitoringK8s/constants.ts
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/pages/LogsExplorer/utils.tsx
Labels: enhancement, docs required

#6909 fix: show upgrade plan option in grace period if not converted to trial
  frontend/src/container/BillingContainer/BillingContainer.test.tsx
  frontend/src/container/BillingContainer/BillingContainer.tsx
Labels: bug, request-more-info

#6964 fix: window size for small time ranges
  ee/query-service/anomaly/params.go
  ee/query-service/anomaly/seasonal.go
  pkg/query-service/rules/db.go
Labels: bug

#6962 feat: Docker volume migration - OSS improvements Part 2
  deploy/docker-swarm/docker-compose.ha.yaml
  deploy/docker-swarm/docker-compose.yaml
  deploy/docker/.env
  deploy/docker/clickhouse-setup/.deprecated
  deploy/docker/docker-compose.ha.yaml
  deploy/docker/docker-compose.testing.yaml
  deploy/docker/docker-compose.yaml
  scripts/volume-migration/migrate.sh
Labels: enhancement, docs required

#6951 feat: added worker count and other misc changes
  frontend/src/AppRoutes/routes.ts
  frontend/src/components/CeleryOverview/CeleryOverviewTable/CeleryOverviewTable.styles.scss
  frontend/src/components/CeleryOverview/CeleryOverviewTable/CeleryOverviewTable.tsx
  frontend/src/components/CeleryTask/CeleryTaskConfigOptions/useGetCeleryFilters.ts
  frontend/src/components/CeleryTask/CeleryTaskDetail/CeleryTaskDetail.style.scss
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskGraph.style.scss
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskGraphGrid.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskGraphUtils.ts
  frontend/src/components/CeleryTask/useCeleryFilterOptions.ts
  frontend/src/constants/routes.ts
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/GridTableComponent/index.tsx
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/container/SideNav/config.ts
  frontend/src/container/SideNav/menuItems.tsx
  frontend/src/container/TopNav/Breadcrumbs/index.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/pages/Celery/CeleryOverview/CeleryOverview.styles.scss
  frontend/src/pages/Celery/CeleryOverview/CeleryOverviewDetail/CeleryOverviewDetails.styles.scss
  frontend/src/pages/Celery/CeleryOverview/CeleryOverviewDetail/CeleryOverviewDetails.tsx
  frontend/src/pages/Celery/CeleryOverview/CeleryOverviewDetail/ValueInfo.styles.scss
  frontend/src/pages/Celery/CeleryTask/CeleryTask.styles.scss
  frontend/src/pages/MessagingQueues/MQDetailPage/MQDetailPage.tsx
  frontend/src/pages/MessagingQueues/MessagingQueues.styles.scss
  frontend/src/pages/MessagingQueues/MessagingQueues.tsx
  frontend/src/pages/MessagingQueues/MessagingQueuesMainPage.tsx
  frontend/src/utils/permission/index.ts
Labels: enhancement, docs not required

#6926 feat: add hostname and os type quick filter to hosts list
  frontend/src/container/InfraMonitoringHosts/HostsList.tsx
  frontend/src/container/InfraMonitoringHosts/HostsListTable.tsx
  frontend/src/container/InfraMonitoringHosts/InfraMonitoring.styles.scss
  frontend/src/container/InfraMonitoringHosts/utils.tsx
Labels: enhancement, docs not required

#6969 chore: add cluster, nodes that are sending incorrect host metrics
  pkg/query-service/app/inframetrics/hosts.go
  pkg/query-service/model/infra.go
Labels: chore

#6961 chore: fix filter editing issue in infra monitoring
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearch/index.tsx
Labels: bug, chore

#6974 fix: properly get the alert severity
  frontend/src/pages/AlertDetails/AlertHeader/AlertHeader.tsx
Labels: bug

#6956 fix: apply x axis date/time formatting only to panel types that have date/time in x axis
  frontend/src/container/AnomalyAlertEvaluationView/AnomalyAlertEvaluationView.tsx
  frontend/src/container/BillingContainer/BillingUsageGraph/BillingUsageGraph.tsx
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
  frontend/src/lib/uPlotLib/getUplotHistogramChartOptions.ts
  frontend/src/lib/uPlotLib/utils/getAxes.ts
Labels: bug

#6972 chore(license): default to basic plan if license validation fails
  .github/workflows/pr_verify_linked_issue.yml
  ee/query-service/license/db.go
  ee/query-service/license/manager.go
  ee/query-service/model/license.go
Labels: chore

#6976 chore: fix visibility toggle in host filters
  frontend/src/container/InfraMonitoringHosts/HostsList.tsx
  frontend/src/container/InfraMonitoringHosts/InfraMonitoring.styles.scss
  frontend/src/container/InfraMonitoringK8s/K8sFiltersSidePanel/K8sFiltersSidePanel.tsx
Labels: bug, chore

#6923 fix: telemetry store
  conf/example.yaml
  ee/query-service/app/api/api.go
  ee/query-service/app/db/reader.go
  ee/query-service/app/server.go
  ee/query-service/main.go
  ee/query-service/usage/manager.go
  pkg/query-service/app/clickhouseReader/options.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/clickhouseReader/wrapper.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/querier/v2/querier_test.go
  pkg/query-service/app/server.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/main.go
  pkg/query-service/rules/threshold_rule_test.go
  pkg/query-service/tests/integration/test_utils.go
  pkg/signoz/config.go
  pkg/signoz/provider.go
  pkg/signoz/signoz.go
  pkg/telemetrystore/clickhousetelemetrystore/provider.go
  pkg/telemetrystore/config.go
  pkg/telemetrystore/config_test.go
  pkg/telemetrystore/telemetrystore.go
  pkg/telemetrystore/telemetrystorehook/settings.go
  pkg/telemetrystore/telemetrystoretest/provider.go
  pkg/telemetrystore/telemetrystoretest/provider_test.go
Labels: bug

#6985 feat: celery task page restructuring and other misc fixes
  frontend/src/components/CeleryTask/CeleryTaskConfigOptions/CeleryTaskConfigOptions.tsx
  frontend/src/components/CeleryTask/CeleryTaskConfigOptions/useGetCeleryFilters.ts
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskBar.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskGraph.style.scss
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskGraphGrid.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskGraphUtils.ts
  frontend/src/components/CeleryTask/useGetGraphCustomSeries.ts
  frontend/src/constants/reactQueryKeys.ts
  frontend/src/pages/Celery/CeleryOverview/CeleryOverviewDetail/OverviewRightPanelGraph.tsx
  frontend/src/pages/Celery/CeleryOverview/CeleryOverviewGraphUtils.ts
  frontend/src/pages/Celery/CeleryTask/CeleryTask.styles.scss
  frontend/src/pages/Celery/CeleryTask/CeleryTask.tsx
  frontend/src/pages/MessagingQueues/MessagingQueuesMainPage.tsx
Labels: bug, enhancement, docs required

#6991 fix: raw log data not rendering in log context
  frontend/src/container/LogDetailedView/ContextView/ContextLogRenderer.tsx
  frontend/src/pages/TraceDetailV2/TraceDetailV2.tsx
Labels: bug

#6992 Fix/check the flows of toggling logs timestamp and body columns
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/container/LiveLogs/LiveLogsList/index.tsx
  frontend/src/container/LogDetailedView/ContextView/ContextLogRenderer.tsx
  frontend/src/pages/LogsExplorer/index.tsx
Labels: bug

#6981 chore: add functionality to open entity details from nested table items in groupby mode
  frontend/src/container/InfraMonitoringK8s/Clusters/K8sClustersList.tsx
  frontend/src/container/InfraMonitoringK8s/DaemonSets/K8sDaemonSetsList.tsx
  frontend/src/container/InfraMonitoringK8s/Deployments/K8sDeploymentsList.tsx
  frontend/src/container/InfraMonitoringK8s/InfraMonitoringK8s.styles.scss
  frontend/src/container/InfraMonitoringK8s/Jobs/K8sJobsList.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/K8sNamespacesList.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/K8sNodesList.tsx
  frontend/src/container/InfraMonitoringK8s/Pods/K8sPodLists.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/K8sStatefulSetsList.tsx
  frontend/src/container/InfraMonitoringK8s/Volumes/K8sVolumesList.tsx
Labels: chore

#6998 fix(trace-detail): trace details improvements
  frontend/src/container/SpanDetailsDrawer/Events/Events.tsx
  frontend/src/container/TraceWaterfall/TraceWaterfallStates/Success/Success.styles.scss
  frontend/src/container/TraceWaterfall/TraceWaterfallStates/Success/Success.tsx
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/traces/tracedetail/flamegraph.go
  pkg/query-service/app/traces/tracedetail/waterfall.go
  pkg/query-service/model/cacheable.go
Labels: bug

#6979 fix(query-service): skip preloading non-json files under dashboards
  pkg/query-service/app/dashboards/provision.go
Labels: bug

#6977 chore: add k8s metrics receiving status
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/infra.go
  pkg/query-service/app/inframetrics/common.go
  pkg/query-service/app/inframetrics/nodes.go
  pkg/query-service/app/inframetrics/pods.go
  pkg/query-service/model/infra.go
Labels: chore
