Repository SigNoz/signoz, pull requests merged in 2025-06, with the labels that each got.

#8039 Fix html escape and json string parsing in qb
  frontend/src/components/LogDetail/index.tsx
  frontend/src/components/Logs/ListLogView/index.tsx
  frontend/src/components/Logs/RawLogView/index.tsx
  frontend/src/container/LogDetailedView/TableView/TableViewActions.tsx
  frontend/src/container/LogDetailedView/utils.tsx
Labels: bug, frontend

#8029 fix: remove create dashboard call before navigate
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/MetricsExplorer/Explorer/Explorer.tsx
  frontend/src/pages/TracesExplorer/index.tsx
Labels: bug

#8113 Feat/7294: Updated Dashboards for integrations
  pkg/query-service/app/cloudintegrations/services/definitions/aws/alb/assets/dashboards/overview_dot.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/api-gateway/assets/dashboards/overview_dot.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/dynamodb/assets/dashboards/overview_dot.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/ec2/assets/dashboards/overview_dot.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/ecs/assets/dashboards/overview_dot.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/elasticache/assets/dashboards/redis_overview_dot.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/lambda/assets/dashboards/overview_dot.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/msk/assets/dashboards/overview_dot.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/rds/assets/dashboards/overview_dot.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/sns/assets/dashboards/overview_dot.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/sqs/assets/dashboards/overview_dot.json
  pkg/query-service/app/integrations/builtin.go
  pkg/query-service/app/integrations/builtin_integrations/aws_elasticache/assets/dashboards/overview_dot.json
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_mysql/assets/dashboards/db_metrics_dot.json
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_mysql/assets/dashboards/overview_dot.json
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_postgres/assets/dashboards/db_metrics_overview_dot.json
  pkg/query-service/app/integrations/builtin_integrations/aws_rds_postgres/assets/dashboards/overview_dot.json
  pkg/query-service/app/integrations/builtin_integrations/clickhouse/assets/dashboards/overview_dot.json
  pkg/query-service/app/integrations/builtin_integrations/mongo/assets/dashboards/overview_dot.json
  pkg/query-service/app/integrations/builtin_integrations/postgres/assets/dashboards/overview_dot.json
  pkg/query-service/app/integrations/builtin_integrations/redis/assets/dashboards/overview_dot.json
Labels: enhancement, staging:civil-eagle

#8123 Fix(8082): Removed Unnecessary log lines
  pkg/query-service/app/clickhouseReader/reader.go
Labels: bug, enhancement

#7674 fix(metrics): exclude NoRecordedValue data points from aggregation
  pkg/prometheus/clickhouseprometheus/client.go
  pkg/query-service/app/metrics/v4/cumulative/table_test.go
  pkg/query-service/app/metrics/v4/cumulative/timeseries.go
  pkg/query-service/app/metrics/v4/cumulative/timeseries_test.go
  pkg/query-service/app/metrics/v4/delta/table_test.go
  pkg/query-service/app/metrics/v4/delta/time_series_test.go
  pkg/query-service/app/metrics/v4/delta/timeseries.go
  pkg/query-service/app/metrics/v4/helpers/sub_query.go
  pkg/query-service/app/metrics/v4/query_builder_test.go
  pkg/query-service/constants/constants.go
Labels: bug

#8105 chore: port functions, reduce to, series limit support
  pkg/types/querybuildertypes/querybuildertypesv5/builder_elements.go
  pkg/types/querybuildertypes/querybuildertypesv5/functions.go
  pkg/types/querybuildertypes/querybuildertypesv5/functions_test.go
  pkg/types/querybuildertypes/querybuildertypesv5/reduce_test.go
  pkg/types/querybuildertypes/querybuildertypesv5/req_test.go
  pkg/types/querybuildertypes/querybuildertypesv5/series_limit.go
  pkg/types/querybuildertypes/querybuildertypesv5/series_limit_test.go
Labels: chore

#7954 fix: Broken Docker Downloads Badge
  README.md
Labels: safe-to-test

#8124 chore(feature): drop the feature status table
  .github/CODEOWNERS
  ee/licensing/httplicensing/provider.go
  ee/licensing/licensingstore/sqllicensingstore/store.go
  ee/query-service/app/api/api.go
  ee/query-service/app/api/featureFlags.go
  ee/query-service/app/api/featureFlags_test.go
  frontend/src/api/features/getFeatureFlags.ts
  frontend/src/api/v1/features/list.ts
  frontend/src/constants/features.ts
  frontend/src/container/AllAlertChannels/__tests__/CreateAlertChannelNormalUser.test.tsx
  frontend/src/container/FormAlertRules/QuerySection.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/ListAlertRules/ListAlert.tsx
  frontend/src/hooks/useGetFeatureFlag.tsx
  frontend/src/pages/LogsExplorer/__tests__/LogsExplorer.test.tsx
  frontend/src/providers/App/App.tsx
  frontend/src/types/api/features/getFeaturesFlags.ts
  frontend/src/types/api/licensesV3/getActive.ts
  pkg/licensing/licensing.go
  pkg/licensing/nooplicensing/provider.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/constants/constants.go
  pkg/signoz/provider.go
  pkg/sqlmigration/039_drop_feature_set.go
  pkg/types/featuretypes/feature.go
  pkg/types/licensetypes/license.go
  pkg/types/licensetypes/license_test.go
  pkg/types/licensetypes/plan.go
Labels: enhancement, chore, safe-to-integrate

#8139 Feat/7294
  pkg/query-service/app/integrations/builtin_integrations/clickhouse/assets/dashboards/overview_dot.json
Labels: enhancement, request-more-info, staging:wealthy-pelican

#8148 feat: fixed multiple sentry error around dashboards
  frontend/src/AppRoutes/Private.tsx
  frontend/src/components/Uplot/Uplot.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/utils.ts
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/GridCardLayout/utils.ts
  frontend/src/container/GridTableComponent/utils.ts
  frontend/src/container/LogDetailedView/utils.tsx
  frontend/src/container/NewDashboard/DashboardSettings/Variables/VariableItem/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/DashboardVariableSelection.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
  frontend/src/container/NewDashboard/DashboardVariablesSelection/util.ts
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/PanelWrapper/HistogramPanelWrapper.tsx
  frontend/src/container/PanelWrapper/PiePanelWrapper.tsx
  frontend/src/container/PanelWrapper/UplotPanelWrapper.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/SpanScopeSelector.tsx
  frontend/src/container/Trace/Graph/config.ts
  frontend/src/hooks/queryBuilder/useGetQueryRange.ts
  frontend/src/lib/uPlotLib/getUplotChartOptions.ts
  frontend/src/lib/uPlotLib/utils/getUplotChartData.ts
  frontend/src/providers/Dashboard/Dashboard.tsx
Labels: bug, enhancement, docs not required

#8112 chore: add formula evaluator
  pkg/types/querybuildertypes/querybuildertypesv5/formula.go
  pkg/types/querybuildertypes/querybuildertypesv5/formula_bench_test.go
  pkg/types/querybuildertypes/querybuildertypesv5/formula_test.go
Labels: chore

#8153 fix(promql): add missing flag columns in query
  pkg/prometheus/clickhouseprometheus/client.go
Labels: bug

#8134 fix: Enhance filter support for Pipeline Simulation
  pkg/query-service/app/logparsingpipeline/pipelineBuilder.go
  pkg/query-service/queryBuilderToExpr/queryBuilderToExpr.go
  pkg/query-service/queryBuilderToExpr/queryBuilderToExpr_test.go
Labels: bug, backend, events-pod

#8104 chore: metric statement builder
  pkg/query-service/app/metrics/v4/helpers/clauses.go
  pkg/telemetrymetrics/const.go
  pkg/telemetrymetrics/field_mapper.go
  pkg/telemetrymetrics/statement_builder.go
  pkg/telemetrymetrics/stmt_builder_test.go
  pkg/telemetrymetrics/tables.go
  pkg/telemetrymetrics/testdata/keys_map.json
  pkg/types/metrictypes/metrictypes.go
  pkg/types/querybuildertypes/querybuildertypesv5/builder_elements.go
  pkg/types/telemetrytypes/telemetrytypestest/load_keys.go
Labels: chore

#8122 feat: Adding ContainerInsights in ECS Integrations (AWS)
  pkg/query-service/app/cloudintegrations/services/definitions/aws/ecs/assets/dashboards/containerinsights.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/ecs/assets/dashboards/containerinsights.png
  pkg/query-service/app/cloudintegrations/services/definitions/aws/ecs/assets/dashboards/containerinsights_dot.json
  pkg/query-service/app/cloudintegrations/services/definitions/aws/ecs/integration.json
Labels: enhancement, docs shipped, staging:civil-eagle

#8142 feat(preference): add support for objects and arrays
  frontend/src/AppRoutes/Private.tsx
  frontend/src/api/preferences/getAllOrgPreferences.ts
  frontend/src/api/preferences/getAllUserPreference.ts
  frontend/src/api/preferences/getOrgPreference.ts
  frontend/src/api/preferences/getUserPreference.ts
  frontend/src/api/preferences/updateOrgPreference.ts
  frontend/src/api/preferences/updateUserPreference.ts
  frontend/src/api/v1/org/preferences/list.ts
  frontend/src/api/v1/org/preferences/name/get.ts
  frontend/src/api/v1/org/preferences/name/update.ts
  frontend/src/api/v1/user/preferences/get.ts
  frontend/src/api/v1/user/preferences/list.ts
  frontend/src/api/v1/user/preferences/name/get.ts
  frontend/src/api/v1/user/preferences/name/update.ts
  frontend/src/container/Home/Home.tsx
  frontend/src/container/Home/constants.ts
  frontend/src/container/OnboardingQuestionaire/index.tsx
  frontend/src/providers/App/App.tsx
  frontend/src/providers/App/types.ts
  frontend/src/tests/test-utils.tsx
  frontend/src/types/api/preferences/get.ts
  frontend/src/types/api/preferences/list.ts
  frontend/src/types/api/preferences/preference.ts
  frontend/src/types/api/preferences/update.ts
  frontend/src/types/api/preferences/userOrgPreferences.ts
  frontend/src/types/api/user/getUserPreference.ts
  frontend/src/types/reducer/app.ts
  pkg/modules/preference/implpreference/handler.go
  pkg/modules/preference/implpreference/module.go
  pkg/modules/preference/implpreference/store.go
  pkg/modules/preference/preference.go
  pkg/query-service/app/http_handler.go
  pkg/signoz/module.go
  pkg/types/preferencetypes/name.go
  pkg/types/preferencetypes/preference.go
  pkg/types/preferencetypes/preference_test.go
  pkg/types/preferencetypes/scope.go
  pkg/types/preferencetypes/value.go
  pkg/types/preferencetypes/value_test.go
Labels: enhancement, safe-to-integrate, staging:next-ewe

#8167 chore: replace y axis unit selector in alerts and dashboards
  frontend/src/components/YAxisUnitSelector/YAxisUnitSelector.tsx
  frontend/src/components/YAxisUnitSelector/styles.scss
  frontend/src/container/FormAlertRules/FormAlertRules.styles.scss
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/MetricsExplorer/Explorer/Explorer.tsx
  frontend/src/container/MetricsExplorer/Explorer/TimeSeries.tsx
  frontend/src/container/MetricsExplorer/Explorer/types.ts
  frontend/src/container/NewWidget/RightContainer/RightContainer.styles.scss
  frontend/src/container/NewWidget/RightContainer/YAxisUnitSelectorV2.tsx
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/src/container/NewWidget/index.tsx
Labels: chore

#8172 chore: fix nanoid vulnerability
  frontend/package.json
  frontend/webpack.config.prod.js
  frontend/yarn.lock
Labels: bug, chore, staging:quiet-buffalo

#8187 feat(statsreporter): report stats on stop
  pkg/statsreporter/analyticsstatsreporter/provider.go
Labels: enhancement, docs not required, safe-to-integrate, staging:next-ewe

#8108 chore: add analytics for metrics explorer
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/container/MetricsExplorer/Explorer/Explorer.tsx
  frontend/src/container/MetricsExplorer/Explorer/QuerySection.tsx
  frontend/src/container/MetricsExplorer/Inspect/ExpandedView.tsx
  frontend/src/container/MetricsExplorer/Inspect/GraphView.tsx
  frontend/src/container/MetricsExplorer/Inspect/Inspect.tsx
  frontend/src/container/MetricsExplorer/Inspect/utils.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/AllAttributes.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/Metadata.tsx
  frontend/src/container/MetricsExplorer/MetricDetails/MetricDetails.tsx
  frontend/src/container/MetricsExplorer/Summary/MetricsTable.tsx
  frontend/src/container/MetricsExplorer/Summary/MetricsTreemap.tsx
  frontend/src/container/MetricsExplorer/Summary/Summary.tsx
  frontend/src/container/MetricsExplorer/Summary/__tests__/MetricsTable.test.tsx
  frontend/src/container/MetricsExplorer/Summary/types.ts
  frontend/src/container/MetricsExplorer/events.ts
  frontend/src/pages/SaveView/index.tsx
  frontend/src/pages/SaveView/utils.ts
Labels: chore

#8041 fix: logs and traces issues
  frontend/src/container/TraceMetadata/TraceMetadata.tsx
Labels: bug

#8214 fix(dashboard): create dashboard panic for id
  pkg/modules/dashboard/impldashboard/handler.go
Labels: bug, safe-to-integrate

#7903 feat: generalised preferences framework
  frontend/src/components/ExplorerCard/test/ExplorerCard.test.tsx
  frontend/src/components/ExplorerCard/utils.ts
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsExplorerViews/tests/LogsExplorerViews.test.tsx
  frontend/src/container/LogsPanelTable/__tests__/LogsPanelComponent.test.tsx
  frontend/src/container/OptionsMenu/useOptionsMenu.ts
  frontend/src/container/PipelinePage/tests/PipelineListsView.test.tsx
  frontend/src/pages/LiveLogs/index.tsx
  frontend/src/pages/LogsExplorer/__tests__/LogsExplorer.test.tsx
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/pages/LogsModulePage/constants.tsx
  frontend/src/pages/MetricsExplorer/constants.tsx
  frontend/src/pages/TracesModulePage/constants.tsx
  frontend/src/providers/preferences/__tests__/PreferenceContextProvider.test.tsx
  frontend/src/providers/preferences/__tests__/logsLoaderConfig.test.ts
  frontend/src/providers/preferences/__tests__/logsUpdaterConfig.test.ts
  frontend/src/providers/preferences/__tests__/tracesLoaderConfig.test.ts
  frontend/src/providers/preferences/__tests__/tracesUpdaterConfig.test.ts
  frontend/src/providers/preferences/__tests__/usePreferenceLoader.test.tsx
  frontend/src/providers/preferences/__tests__/usePreferenceUpdater.test.tsx
  frontend/src/providers/preferences/configs/logsLoaderConfig.ts
  frontend/src/providers/preferences/configs/logsUpdaterConfig.ts
  frontend/src/providers/preferences/configs/tracesLoaderConfig.ts
  frontend/src/providers/preferences/configs/tracesUpdaterConfig.ts
  frontend/src/providers/preferences/context/PreferenceContextProvider.tsx
  frontend/src/providers/preferences/loader/usePreferenceLoader.ts
  frontend/src/providers/preferences/sync/usePreferenceSync.ts
  frontend/src/providers/preferences/types/index.ts
  frontend/src/providers/preferences/updater/usePreferenceUpdater.ts
Labels: enhancement, docs required, staging:modest-tuna

#8005 feat: add span scope filter to trace details page
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/SpanScopeSelector.tsx
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/__test__/SpanScopeSelector.test.tsx
  frontend/src/container/TraceWaterfall/TraceWaterfallStates/Success/Filters/Filters.tsx
Labels: enhancement, docs required

#8244 chore: allow url as label value in alerts
  frontend/src/container/FormAlertRules/labels/index.tsx
Labels: chore

#8245 chore: updated http-proxy-middleware to 3.0.5 from 3.0.3
  frontend/package.json
  frontend/yarn.lock
Labels: chore

#7889 feat(trace): add visuals for events on span waterfall and flamegraph
  frontend/src/container/PaginatedTraceFlamegraph/TraceFlamegraphStates/Success/Success.styles.scss
  frontend/src/container/PaginatedTraceFlamegraph/TraceFlamegraphStates/Success/Success.tsx
  frontend/src/container/SpanDetailsDrawer/Events/Events.styles.scss
  frontend/src/container/SpanDetailsDrawer/Events/Events.tsx
  frontend/src/container/TraceWaterfall/TraceWaterfallStates/Success/Success.styles.scss
  frontend/src/container/TraceWaterfall/TraceWaterfallStates/Success/Success.tsx
  frontend/src/types/api/trace/getTraceFlamegraph.ts
  frontend/src/types/api/trace/getTraceV2.ts
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/response.go
Labels: docs not required, safe-to-test, safe-to-integrate

#7888 fix: span links tab to span details drawer
  frontend/src/container/SpanDetailsDrawer/LinkedSpans/LinkedSpans.styles.scss
  frontend/src/container/SpanDetailsDrawer/LinkedSpans/LinkedSpans.tsx
  frontend/src/container/SpanDetailsDrawer/SpanDetailsDrawer.styles.scss
  frontend/src/container/SpanDetailsDrawer/SpanDetailsDrawer.tsx
Labels: safe-to-test, safe-to-integrate

#8251 feat(statsreporter): add stats for telemetry.*.last_observed.time
  pkg/statsreporter/analyticsstatsreporter/provider.go
Labels: enhancement, staging:next-ewe

#8239 fix: configs in multi-node docker-swarm cluster
  deploy/docker-swarm/docker-compose.yaml
Labels: safe-to-test

#8165 feat: added support for trace_operators in query range v5
  pkg/types/querybuildertypes/querybuildertypesv5/query_type.go
  pkg/types/querybuildertypes/querybuildertypesv5/req.go
  pkg/types/querybuildertypes/querybuildertypesv5/req_test.go
  pkg/types/querybuildertypes/querybuildertypesv5/trace_operator.go
Labels: enhancement, backend, events-pod, docs not required, staging:evolving-elephant

#8261 chore(github): fix codeowners file
  .github/CODEOWNERS
Labels: bug, chore, request-more-info

#8237 chore: disallow unknown fields and address gaps
  pkg/querier/api.go
  pkg/querier/bucket_cache.go
  pkg/querier/bucket_cache_bench_test.go
  pkg/querier/bucket_cache_step_test.go
  pkg/querier/bucket_cache_test.go
  pkg/querier/builder_query.go
  pkg/querier/builder_query_test.go
  pkg/querier/consume.go
  pkg/querier/interfaces.go
  pkg/querier/postprocess.go
  pkg/querier/querier.go
  pkg/querier/shift_test.go
  pkg/querybuilder/fallback_expr.go
  pkg/querybuilder/resourcefilter/condition_builder.go
  pkg/querybuilder/where_clause_visitor.go
  pkg/telemetrylogs/field_mapper.go
  pkg/telemetrylogs/filter_expr_logs_test.go
  pkg/telemetrylogs/statement_builder.go
  pkg/telemetrylogs/stmt_builder_test.go
  pkg/telemetrymetadata/field_mapper.go
  pkg/telemetrymetadata/metadata.go
  pkg/telemetrymetrics/statement_builder.go
  pkg/telemetrymetrics/stmt_builder_test.go
  pkg/telemetrytraces/field_mapper.go
  pkg/telemetrytraces/statement_builder.go
  pkg/types/metrictypes/metrictypes.go
  pkg/types/querybuildertypes/querybuildertypesv5/builder_elements.go
  pkg/types/querybuildertypes/querybuildertypesv5/builder_query.go
  pkg/types/querybuildertypes/querybuildertypesv5/formula.go
  pkg/types/querybuildertypes/querybuildertypesv5/functions.go
  pkg/types/querybuildertypes/querybuildertypesv5/json_decoder.go
  pkg/types/querybuildertypes/querybuildertypesv5/req.go
  pkg/types/querybuildertypes/querybuildertypesv5/req_error_test.go
  pkg/types/querybuildertypes/querybuildertypesv5/req_test.go
  pkg/types/querybuildertypes/querybuildertypesv5/resp.go
  pkg/types/querybuildertypes/querybuildertypesv5/validation.go
  pkg/types/telemetrytypes/maybe_typo.go
  pkg/types/telemetrytypes/store.go
  pkg/types/telemetrytypes/telemetrytypestest/metadata_store.go
Labels: chore

#8269 fix: use first org in agent migration
  pkg/sqlmigration/041_update_agents.go
Labels: bug

#8279 feat(analytics): move frontend event to group_id
  conf/example.yaml
  pkg/analytics/analytics.go
  pkg/analytics/analyticstest/provider.go
  pkg/analytics/noopanalytics/provider.go
  pkg/analytics/segmentanalytics/provider.go
  pkg/modules/dashboard/impldashboard/module.go
  pkg/modules/user/impluser/getter.go
  pkg/modules/user/impluser/handler.go
  pkg/modules/user/impluser/module.go
  pkg/modules/user/impluser/store.go
  pkg/modules/user/user.go
  pkg/query-service/app/http_handler.go
  pkg/signoz/provider.go
  pkg/signoz/provider_test.go
  pkg/signoz/signoz.go
  pkg/statsreporter/analyticsstatsreporter/provider.go
  pkg/statsreporter/config.go
  pkg/types/organization.go
  pkg/types/user.go
Labels: enhancement, safe-to-integrate, staging:next-ewe

#8283 fixing steps and funnel
  pkg/modules/tracefunnel/clickhouse_queries.go
Labels: bug

#8129 feat: adds a final part of trace funnel feature (analytics APIs, and analytics queries) implementation
  pkg/modules/tracefunnel/clickhouse_queries.go
  pkg/modules/tracefunnel/query.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/traces/v4/query_builder.go
  pkg/types/tracefunneltypes/tracefunnel.go
Labels: enhancement, docs shipped, safe-to-test

#7994 chore: remove dev env check (merge after the trace funnels BE changes get merged)
  frontend/src/container/TraceWaterfall/TraceWaterfallStates/Success/Success.tsx
  frontend/src/pages/TraceDetailV2/index.tsx
  frontend/src/pages/TracesModulePage/TracesModulePage.tsx
Labels: chore

#8294 fix: tracefunnel analytics duration fixes + 2-step funnel fixes
  pkg/modules/tracefunnel/clickhouse_queries.go
Labels: bug

#8297 fix(sidebar): added fix routes not highlighting, minor gitter fix
  frontend/src/constants/routes.ts
  frontend/src/container/SideNav/SideNav.styles.scss
  frontend/src/container/SideNav/menuItems.tsx
  frontend/src/utils/permission/index.ts
Labels: bug

#8295 Query builder misc - fixes
  frontend/src/api/v5/queryRange/convertV5Response.ts
  frontend/src/api/v5/queryRange/prepareQueryRangePayloadV5.ts
  frontend/src/components/QueryBuilderV2/QueryBuilderV2.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/MerticsAggregateSection/MetricsAggregateSection.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAddOns/HavingFilter/HavingFilter.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAddOns/QueryAddOns.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAggregation/QueryAggregation.styles.scss
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAggregation/QueryAggregationSelect.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QuerySearch/QuerySearch.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QueryV2.tsx
  frontend/src/components/QueryBuilderV2/utils.ts
  frontend/src/constants/query.ts
  frontend/src/container/LogExplorerQuerySection/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/MetricsExplorer/Explorer/Explorer.tsx
  frontend/src/container/QueryBuilder/filters/OrderByFilter/OrderByFilter.interfaces.ts
  frontend/src/container/QueryBuilder/filters/OrderByFilter/OrderByFilter.tsx
  frontend/src/container/TracesExplorer/QuerySection/index.tsx
  frontend/src/hooks/useHandleExplorerTabChange.ts
  frontend/src/lib/dashboard/getQueryResults.ts
  frontend/src/lib/query/createTableColumnsFromQuery.ts
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/pages/TracesExplorer/index.tsx
  frontend/src/utils/aggregationConverter.ts
  frontend/src/utils/explorerUtils.ts
Labels: bug

#8298 fix: use pathname to get channel id
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/constants/routes.ts
  frontend/src/container/AllAlertChannels/AlertChannels.tsx
  frontend/src/container/FormAlertChannels/index.tsx
  frontend/src/pages/AlertList/AlertList.styles.scss
  frontend/src/pages/ChannelsEdit/ChannelsEdit.styles.scss
  frontend/src/pages/ChannelsEdit/index.tsx
  frontend/src/pages/Settings/Settings.tsx
Labels: bug, request-more-info

#8303 fix: use pathname to get channel id while saving
  frontend/src/container/EditAlertChannels/index.tsx
Labels: bug, request-more-info

#8306 chore(sqlstore): remove sqlx
  ee/query-service/app/server.go
  ee/sqlstore/postgressqlstore/provider.go
  go.mod
  go.sum
  pkg/query-service/app/server.go
  pkg/query-service/rules/manager.go
  pkg/sqlstore/sqlitesqlstore/provider.go
  pkg/sqlstore/sqlstore.go
  pkg/sqlstore/sqlstoretest/provider.go
Labels: chore, safe-to-integrate

#8270 feat(changelog): show changelogs for newer versions available
  frontend/src/api/changelog/getChangelogByVersion.ts
  frontend/src/components/ChangelogModal/ChangelogModal.styles.scss
  frontend/src/components/ChangelogModal/ChangelogModal.tsx
  frontend/src/components/ChangelogModal/__test__/ChangelogModal.test.tsx
  frontend/src/components/ChangelogModal/__test__/ChangelogRenderer.test.tsx
  frontend/src/components/ChangelogModal/components/ChangelogRenderer.styles.scss
  frontend/src/components/ChangelogModal/components/ChangelogRenderer.tsx
  frontend/src/container/AppLayout/index.tsx
  frontend/src/container/SideNav/SideNav.tsx
  frontend/src/providers/App/App.tsx
  frontend/src/providers/App/types.ts
  frontend/src/tests/test-utils.tsx
  frontend/src/types/api/changelog/getChangelogByVersion.ts
Labels: enhancement, frontend, staging:merry-iguana

#8307 fix: update app layout height based on banners visible
  frontend/src/container/AppLayout/AppLayout.styles.scss
  frontend/src/container/AppLayout/index.tsx
Labels: bug

#8315 fix: update trace panel query
  pkg/query-service/app/querier/querier_test.go
  pkg/query-service/app/traces/v3/query_builder.go
  pkg/query-service/app/traces/v3/query_builder_test.go
  pkg/query-service/app/traces/v4/query_builder.go
  pkg/query-service/app/traces/v4/query_builder_test.go
  pkg/query-service/constants/constants.go
Labels: bug

#8318 chore: handle nan/inf in response
  pkg/types/querybuildertypes/querybuildertypesv5/resp.go
  pkg/types/querybuildertypes/querybuildertypesv5/resp_test.go
Labels: chore

#8308 chore(signoz): deprecate all flags
  .golangci.yml
  conf/example.yaml
  ee/query-service/Dockerfile
  ee/query-service/Dockerfile.multi-arch
  ee/query-service/app/api/api.go
  ee/query-service/app/api/auth.go
  ee/query-service/app/api/featureFlags.go
  ee/query-service/app/db/reader.go
  ee/query-service/app/server.go
  ee/query-service/constants/constants.go
  ee/query-service/interfaces/connector.go
  ee/query-service/main.go
  pkg/gateway/config.go
  pkg/modules/user/impluser/module.go
  pkg/modules/user/user.go
  pkg/query-service/Dockerfile
  pkg/query-service/Dockerfile.multi-arch
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/opamp/config_provider_test.go
  pkg/query-service/app/opamp/model/agents.go
  pkg/query-service/app/server.go
  pkg/query-service/constants/constants.go
  pkg/query-service/main.go
  pkg/query-service/telemetry/dashboard.go
  pkg/query-service/telemetry/ignored.go
  pkg/query-service/telemetry/rule.go
  pkg/query-service/telemetry/saved_view.go
  pkg/query-service/telemetry/telemetry.go
  pkg/query-service/telemetry/user.go
  pkg/query-service/tests/integration/filter_suggestions_test.go
  pkg/query-service/tests/integration/logparsingpipeline_test.go
  pkg/query-service/tests/integration/signoz_cloud_integrations_test.go
  pkg/query-service/tests/integration/signoz_integrations_test.go
  pkg/signoz/config.go
  pkg/telemetrylogs/stmt_builder_test.go
  pkg/telemetrymetadata/field_mapper.go
  pkg/telemetrymetrics/statement_builder.go
  pkg/telemetrystore/clickhousetelemetrystore/provider.go
  pkg/telemetrystore/config.go
  pkg/telemetrystore/config_test.go
  pkg/telemetrystore/telemetrystore.go
  pkg/telemetrystore/telemetrystorehook/settings.go
  pkg/telemetrystore/telemetrystoretest/provider.go
  pkg/telemetrytraces/field_mapper.go
  pkg/telemetrytraces/stmt_builder_test.go
Labels: chore, safe-to-integrate, staging:next-ewe

#8299 fix: fetch only required log fields
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/logs/parser.go
  pkg/query-service/app/logs/parser_test.go
  pkg/query-service/app/logs/v3/enrich_query.go
  pkg/query-service/app/logs/v3/enrich_query_test.go
  pkg/query-service/interfaces/interface.go
Labels: bug

#8278 fix: log details filters use data types from log data response as primary data type
  frontend/src/components/Logs/AddToQueryHOC.tsx
  frontend/src/container/LogDetailedView/ActionItem.tsx
  frontend/src/container/LogDetailedView/TableView.tsx
  frontend/src/container/LogDetailedView/TableView/TableViewActions.tsx
  frontend/src/lib/__tests__/chooseAutocompleteFromCustomValue.test.ts
  frontend/src/lib/newQueryBuilder/chooseAutocompleteFromCustomValue.ts
Labels: bug, frontend, p0, events-pod

#8317 chore: add time range optimization for trace id search
  pkg/querier/signozquerier/provider.go
  pkg/telemetrytraces/condition_builder.go
  pkg/telemetrytraces/const.go
  pkg/telemetrytraces/field_mapper.go
  pkg/telemetrytraces/span_scope_simple_test.go
  pkg/telemetrytraces/statement_builder.go
  pkg/telemetrytraces/stmt_builder_test.go
  pkg/telemetrytraces/tables.go
  pkg/telemetrytraces/trace_id_extractor.go
  pkg/telemetrytraces/trace_time_range.go
  pkg/telemetrytraces/trace_time_range_multi_test.go
  pkg/telemetrytraces/trace_time_range_test.go
Labels: chore

#8327 chore: alerts fixes and improvements
  frontend/public/locales/en-GB/channels.json
  frontend/public/locales/en/channels.json
  frontend/src/container/AllAlertChannels/__tests__/CreateAlertChannel.test.tsx
  frontend/src/container/CreateAlertChannels/index.tsx
  frontend/src/container/TriggeredAlerts/FilteredTable/ExapandableRow.tsx
  frontend/src/container/TriggeredAlerts/FilteredTable/TableRow.tsx
  frontend/src/container/TriggeredAlerts/FilteredTable/index.tsx
  frontend/src/container/TriggeredAlerts/FilteredTable/styles.ts
Labels: bug, chore

#8328 chore: recognize variable in expression
  ee/query-service/app/api/api.go
  grammar/FilterQuery.g4
  pkg/apis/fields/parse.go
  pkg/parser/grammar/FilterQuery.interp
  pkg/parser/grammar/FilterQueryLexer.interp
  pkg/parser/grammar/filterquery_lexer.go
  pkg/parser/grammar/filterquery_parser.go
  pkg/querier/api.go
  pkg/querier/clickhouse_query.go
  pkg/querier/format.go
  pkg/querier/postprocess.go
  pkg/querier/promql_query.go
  pkg/querier/querier.go
  pkg/query-service/app/server.go
  pkg/querybuilder/having_rewriter.go
  pkg/querybuilder/resourcefilter/statement_builder.go
  pkg/querybuilder/time.go
  pkg/querybuilder/where_clause_visitor.go
  pkg/telemetrylogs/condition_builder_test.go
  pkg/telemetrylogs/const.go
  pkg/telemetrylogs/statement_builder.go
  pkg/telemetrylogs/stmt_builder_having_test.go
  pkg/telemetrymetadata/metadata.go
  pkg/telemetrymetrics/statement_builder.go
  pkg/telemetrytraces/condition_builder.go
  pkg/telemetrytraces/const.go
  pkg/telemetrytraces/statement_builder.go
Labels: chore

#8277 fix: recalculate the query_range start and end timestamps for logs explorer chart and list queries
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsExplorerViews/tests/LogsExplorerViews.test.tsx
Labels: bug

#8250 fix: prevent sending order by id with traces query
  frontend/src/hooks/queryBuilder/useGetQueryRange.ts
  frontend/src/pages/TracesExplorer/__test__/TracesExplorer.test.tsx
Labels: bug

#8304 fix: fix the flickering in logs explorer table view
  frontend/src/components/Logs/TableView/config.ts
Labels: bug

#8330 feat: add support for expandable popover for stack message and body in trace details page
  frontend/src/container/SpanDetailsDrawer/Events/Events.tsx
  frontend/src/container/SpanDetailsDrawer/Events/components/AttributeWithExpandablePopover.styles.scss
  frontend/src/container/SpanDetailsDrawer/Events/components/AttributeWithExpandablePopover.tsx
  frontend/src/container/SpanDetailsDrawer/Events/components/EventAttribute.tsx
Labels: enhancement, docs required

#8342 fix: added missing context provider in pipelines
  frontend/src/pages/LogsModulePage/constants.tsx
Labels: bug

#8346 fix: show status message in trace details v2 drawer
  frontend/src/container/SpanDetailsDrawer/SpanDetailsDrawer.tsx
Labels: bug

#8326 feat(telemetry): remove telemetry
  ee/query-service/app/server.go
  frontend/src/api/userFeedback/sendFeedback.ts
  pkg/http/middleware/analytics.go
  pkg/modules/user/impluser/module.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/query_info.go
  pkg/query-service/app/server.go
  pkg/query-service/constants/constants.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/telemetry/dashboard.go
  pkg/query-service/telemetry/ignored.go
  pkg/query-service/telemetry/rule.go
  pkg/query-service/telemetry/saved_view.go
  pkg/query-service/telemetry/telemetry.go
  pkg/query-service/telemetry/user.go
  pkg/statsreporter/analyticsstatsreporter/provider.go
Labels: enhancement, safe-to-integrate, staging:next-ewe

#8350 fix: fixed stepInterval not getting updated in the request payload for Bar
  frontend/src/container/GridCardLayout/__tests__/utils.test.ts
  frontend/src/container/GridCardLayout/utils.ts
  frontend/src/container/NewWidget/index.tsx
Labels: bug

#8357 chore: fix environment filter in infra monitoring
  frontend/src/container/InfraMonitoringHosts/utils.tsx
  frontend/src/container/InfraMonitoringK8s/constants.ts
Labels: bug, chore

#8359 feat: new query builder misc fixes
  frontend/src/api/v5/queryRange/convertV5Response.ts
  frontend/src/api/v5/queryRange/prepareQueryRangePayloadV5.ts
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAddOns/HavingFilter/HavingFilter.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAggregation/QueryAggregation.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QueryAggregation/QueryAggregationSelect.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QuerySearch/QuerySearch.tsx
  frontend/src/components/QueryBuilderV2/QueryV2/QueryV2.tsx
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/ApiMonitoring/Explorer/Domains/DomainList.tsx
  frontend/src/container/FormAlertRules/ChartPreview/index.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/LogExplorerQuerySection/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/MetricsExplorer/Explorer/Explorer.tsx
  frontend/src/container/NewWidget/LeftContainer/QuerySection/index.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphContainer.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/util.ts
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/NewWidget/utils.ts
  frontend/src/container/QueryBuilder/filters/QueryBuilderSearchV2/QueryBuilderSearchV2.tsx
  frontend/src/container/ResourceAttributeFilterV2/ResourceAttributesFilterV2.tsx
  frontend/src/hooks/hotkeys/useKeyboardHotkeys.tsx
  frontend/src/hooks/queryBuilder/useGetCompositeQueryParam.ts
  frontend/src/hooks/queryBuilder/useShareBuilderUrl.ts
  frontend/src/pages/LiveLogs/index.tsx
  frontend/src/pages/LogsExplorer/index.tsx
  frontend/src/pages/TracesExplorer/index.tsx
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/types/api/v5/queryRange.ts
  frontend/src/types/common/queryBuilder.ts
Labels: bug, enhancement

#8173 chore: update memory usage field in hosts list to exclude cached memory
  frontend/src/components/HostMetricsDetail/HostMetricsDetails.tsx
  frontend/src/container/InfraMonitoringHosts/InfraMonitoring.styles.scss
  frontend/src/container/InfraMonitoringHosts/utils.tsx
  frontend/src/container/LogDetailedView/InfraMetrics/constants.ts
  pkg/query-service/app/inframetrics/hosts_query.go
Labels: frontend, chore, backend, staging:quiet-buffalo

#8341 chore: log the request and expected response payload
  pkg/querier/postprocess.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/rules/threshold_rule.go
  pkg/query-service/transition/v3_to_v5_req.go
  pkg/query-service/transition/v3_to_v5_resp.go
  pkg/telemetrymetadata/metadata.go
  pkg/telemetrytraces/const.go
  pkg/telemetrytraces/statement_builder.go
  pkg/types/querybuildertypes/querybuildertypesv5/formula.go
Labels: chore

#8344 fix: panic after connecting to Collector
  pkg/query-service/app/opamp/config_provider_test.go
  pkg/query-service/app/opamp/model/agent.go
  pkg/query-service/app/opamp/model/agents.go
  pkg/query-service/app/opamp/opamp_server.go
  pkg/query-service/tests/integration/logparsingpipeline_test.go
  pkg/valuer/uuid.go
Labels: bug, backend, events-pod
