Repository SigNoz/signoz, pull requests merged in 2025-02, with the labels that each got.

#7006 fix the gap between text and button in logs quick filters
  frontend/src/components/QuickFilters/FilterRenderers/Checkbox/Checkbox.styles.scss
Labels: bug

#7008 feat: fix incorrect suggestions while moving between explorers
  frontend/src/container/InfraMonitoringHosts/HostsListControls.tsx
  frontend/src/container/InfraMonitoringK8s/K8sHeader.tsx
  frontend/src/hooks/queryBuilder/useFetchKeysAndValues.ts
Labels: bug, enhancement, docs required

#7019 feat: celery - misc feedback fixes
  frontend/src/components/CeleryOverview/CeleryOverviewConfigOptions/CeleryOverviewConfigOptions.tsx
  frontend/src/components/CeleryOverview/CeleryOverviewTable/CeleryOverviewTable.styles.scss
  frontend/src/components/CeleryOverview/CeleryOverviewTable/CeleryOverviewTable.tsx
  frontend/src/components/CeleryTask/CeleryTaskDetail/CeleryTaskDetail.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskBar.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskGraph.style.scss
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskGraph.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskGraphGrid.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskGraphUtils.ts
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskLatencyGraph.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskStateGraphConfig.tsx
  frontend/src/components/CeleryTask/CeleryUtils.ts
  frontend/src/components/CeleryTask/useNavigateToTraces.ts
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCard/types.ts
  frontend/src/container/GridCardLayout/GridCardLayout.styles.scss
  frontend/src/pages/Celery/CeleryOverview/CeleryOverview.tsx
  frontend/src/pages/Celery/CeleryTask/CeleryTask.tsx
Labels: bug, enhancement, docs not required

#6994 chore: update logs in infra monitoring for analytics
  frontend/src/container/InfraMonitoringK8s/Clusters/ClusterDetails/ClusterDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Clusters/K8sClustersList.tsx
  frontend/src/container/InfraMonitoringK8s/DaemonSets/DaemonSetDetails/DaemonSetDetails.tsx
  frontend/src/container/InfraMonitoringK8s/DaemonSets/K8sDaemonSetsList.tsx
  frontend/src/container/InfraMonitoringK8s/Deployments/DeploymentDetails/DeploymentDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Deployments/K8sDeploymentsList.tsx
  frontend/src/container/InfraMonitoringK8s/InfraMonitoringK8s.tsx
  frontend/src/container/InfraMonitoringK8s/Jobs/JobDetails/JobDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Jobs/K8sJobsList.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/K8sNamespacesList.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/NamespaceDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/K8sNodesList.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/NodeDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Pods/K8sPodLists.tsx
  frontend/src/container/InfraMonitoringK8s/Pods/PodDetails/PodDetails.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/K8sStatefulSetsList.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/StatefulSetDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Volumes/K8sVolumesList.tsx
Labels: chore

#7021 chore(licenses): update the license events and the state names
  ee/query-service/model/license.go
  ee/query-service/model/plans.go
  frontend/src/AppRoutes/Private.tsx
  frontend/src/container/AppLayout/index.tsx
  frontend/src/pages/WorkspaceSuspended/WorkspaceSuspended.tsx
  frontend/src/types/api/licensesV3/getActive.ts
Labels: chore

#7023 feat: bug fix for the issue in span filtering feature. No spans returned in traces tab
  pkg/query-service/app/traces/v3/query_builder_test.go
  pkg/query-service/app/traces/v4/query_builder.go
  pkg/query-service/app/traces/v4/query_builder_test.go
  pkg/query-service/constants/constants.go
Labels: bug, enhancement, docs shipped

#7026 fix(add_pats): fix type of column
  pkg/sqlmigration/009_add_pats.go
Labels: bug

#7027 feat: change grid to flex - flower metrics section
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskGraph.style.scss
Labels: enhancement, docs not required

#7030 feat: corrected the color map for error % and added throughput unit
  frontend/src/components/CeleryOverview/CeleryOverviewTable/CeleryOverviewTable.tsx
  frontend/src/pages/Celery/CeleryOverview/CeleryOverviewDetail/OverviewRightPanelGraph.tsx
Labels: enhancement, docs not required

#7014 chore: share filters across logs and traces views in entity details
  frontend/src/container/InfraMonitoringK8s/Clusters/ClusterDetails/ClusterDetails.tsx
  frontend/src/container/InfraMonitoringK8s/DaemonSets/DaemonSetDetails/DaemonSetDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Deployments/DeploymentDetails/DeploymentDetails.tsx
  frontend/src/container/InfraMonitoringK8s/EntityDetailsUtils/EntityLogs/EntityLogsDetailedView.tsx
  frontend/src/container/InfraMonitoringK8s/EntityDetailsUtils/EntityTraces/EntityTraces.tsx
  frontend/src/container/InfraMonitoringK8s/EntityDetailsUtils/utils.tsx
  frontend/src/container/InfraMonitoringK8s/Jobs/JobDetails/JobDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Namespaces/NamespaceDetails/NamespaceDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Nodes/NodeDetails/NodeDetails.tsx
  frontend/src/container/InfraMonitoringK8s/Pods/PodDetails/PodDetails.tsx
  frontend/src/container/InfraMonitoringK8s/StatefulSets/StatefulSetDetails/StatefulSetDetails.tsx
Labels: chore

#7024 feat: metrics explorer base setup
  frontend/public/locales/en/titles.json
  frontend/src/AppRoutes/pageComponents.ts
  frontend/src/AppRoutes/routes.ts
  frontend/src/constants/routes.ts
  frontend/src/container/MetricsExplorer/Explorer/Explorer.tsx
  frontend/src/container/MetricsExplorer/Explorer/index.ts
  frontend/src/container/MetricsExplorer/Summary/Summary.tsx
  frontend/src/container/MetricsExplorer/Summary/index.ts
  frontend/src/container/MetricsExplorer/Views/Views.tsx
  frontend/src/container/MetricsExplorer/Views/index.ts
  frontend/src/container/SideNav/menuItems.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
  frontend/src/pages/MetricsExplorer/MetricsExplorerPage.styles.scss
  frontend/src/pages/MetricsExplorer/MetricsExplorerPage.tsx
  frontend/src/pages/MetricsExplorer/constants.tsx
  frontend/src/pages/MetricsExplorer/index.ts
  frontend/src/utils/permission/index.ts
Labels: enhancement, docs required

#7034 task(licenses): update the license events and the state names
  ee/query-service/model/license.go
  ee/query-service/model/plans.go
  frontend/src/AppRoutes/Private.tsx
  frontend/src/container/AppLayout/index.tsx
  frontend/src/pages/WorkspaceSuspended/WorkspaceSuspended.tsx
  frontend/src/types/api/licensesV3/getActive.ts
Labels: request-more-info

#6619 chore: add related values
  pkg/query-service/app/clickhouseReader/options.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/parser.go
  pkg/query-service/model/v3/v3.go
Labels: chore

#7046 feat: bug fix for segregating entrypoint spans and root spans in span filtering
  pkg/query-service/app/traces/v4/query_builder.go
  pkg/query-service/app/traces/v4/query_builder_test.go
Labels: bug, enhancement, docs shipped

#7033 feat: aws integration feature flag changes
  ee/query-service/model/plans.go
  frontend/src/constants/features.ts
  frontend/src/pages/Integrations/IntegrationsList.tsx
  pkg/query-service/model/featureSet.go
Labels: enhancement, docs required

#7035 chore: parse string values for __value filter
  pkg/query-service/app/metrics/query_builder.go
  pkg/query-service/app/metrics/v4/query_builder_test.go
Labels: chore

#7017 chore: use any of [cpu.usage, cpu.utilization] for cpu
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/metrics/v3/cumulative_table.go
  pkg/query-service/app/metrics/v3/cumulative_table_test.go
  pkg/query-service/app/metrics/v3/delta.go
  pkg/query-service/app/metrics/v3/delta_table.go
  pkg/query-service/app/metrics/v3/delta_table_test.go
  pkg/query-service/app/metrics/v3/query_builder.go
  pkg/query-service/app/metrics/v3/query_builder_test.go
  pkg/query-service/app/metrics/v4/cumulative/table_test.go
  pkg/query-service/app/metrics/v4/cumulative/timeseries.go
  pkg/query-service/app/metrics/v4/cumulative/timeseries_test.go
  pkg/query-service/app/metrics/v4/delta/table_test.go
  pkg/query-service/app/metrics/v4/delta/time_series_test.go
  pkg/query-service/app/metrics/v4/delta/timeseries.go
  pkg/query-service/app/metrics/v4/helpers/sub_query.go
  pkg/query-service/app/metrics/v4/query_builder_pre_agg_test.go
  pkg/query-service/app/metrics/v4/query_builder_test.go
  pkg/query-service/app/queryBuilder/query_builder_test.go
  pkg/query-service/metrics/transition.go
  pkg/query-service/utils/format.go
Labels: chore

#7054 fix: address the first point increase without previous measurement value
  pkg/query-service/app/metrics/v4/cumulative/timeseries.go
Labels: bug

#7067 revert: "chore: add related values"
  pkg/query-service/app/clickhouseReader/options.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/parser.go
  pkg/query-service/model/v3/v3.go
Labels: chore

#7062 chore: add customerio to frontend
  .github/workflows/push.yaml
  frontend/package.json
  frontend/src/index.html.ejs
  frontend/webpack.config.js
  frontend/webpack.config.prod.js
Labels: chore

#7071 feat: added create alerts option for panel in locked dashboard
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
Labels: enhancement, docs required

#7079 chore: add customerio identity calls
  frontend/src/AppRoutes/index.tsx
  frontend/src/index.html.ejs
  frontend/src/typings/window.ts
Labels: chore

#6993 feat: added new and cloned panel at the bottom of the page
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/NewWidget/__test__/NewWidget.test.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/NewWidget/utils.ts
  frontend/src/hooks/dashboard/utils.ts
Labels: enhancement, docs required

#6999 feat: added feat to add new panel in a section
  frontend/src/container/GridCardLayout/DashboardEmptyState/DashboardEmptyState.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.styles.scss
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/GridCardLayout/WidgetRow.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/container/NewWidget/__test__/NewWidget.test.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/NewWidget/utils.ts
  frontend/src/providers/Dashboard/Dashboard.tsx
  frontend/src/providers/Dashboard/types.ts
Labels: enhancement, docs required

#7055 fix: move migrations to bun
  pkg/sqlmigration/000_add_data_migrations.go
  pkg/sqlmigration/001_add_organization.go
  pkg/sqlmigration/002_add_preferences.go
  pkg/sqlmigration/003_add_dashboards.go
  pkg/sqlmigration/004_add_saved_views.go
  pkg/sqlmigration/005_add_agents.go
  pkg/sqlmigration/006_add_pipelines.go
  pkg/sqlmigration/007_add_integrations.go
  pkg/sqlmigration/008_add_licenses.go
  pkg/sqlmigration/009_add_pats.go
  pkg/types/agent.go
  pkg/types/dashboard.go
  pkg/types/datamigration.go
  pkg/types/integration.go
  pkg/types/license.go
  pkg/types/organization.go
  pkg/types/personal_access_token.go
  pkg/types/pipeline.go
  pkg/types/preference.go
  pkg/types/savedview.go
Labels: bug

#7092 feat: changed visible Panel name for Value Panel to Number
  frontend/src/constants/queryBuilder.ts
  frontend/src/container/NewDashboard/ComponentsSlider/menuItems.tsx
  frontend/src/container/NewWidget/RightContainer/index.tsx
  frontend/yarn.lock
Labels: enhancement, docs required

#7089 fix: add migration and postgres provider
  go.mod
  go.sum
  pkg/signoz/provider.go
  pkg/sqlmigration/003_add_dashboards.go
  pkg/sqlmigration/004_add_saved_views.go
  pkg/sqlmigration/005_add_agents.go
  pkg/sqlmigration/011_modify_datetime.go
  pkg/sqlstore/config.go
  pkg/sqlstore/postgressqlstore/provider.go
Labels: bug

#7099 fix(otelcol): rename clickhousemetricswritev2 to signozclickhousemetrics
  deploy/docker-swarm/otel-collector-config.yaml
  deploy/docker/otel-collector-config.yaml
Labels: bug

#7101 feat(alertmanager): add alertmanagertypes
  go.mod
  go.sum
  pkg/errors/code.go
  pkg/errors/errors.go
  pkg/errors/errors_test.go
  pkg/http/render/render.go
  pkg/http/render/render_test.go
  pkg/types/alertmanagertypes/alert.go
  pkg/types/alertmanagertypes/channel.go
  pkg/types/alertmanagertypes/channel_test.go
  pkg/types/alertmanagertypes/config.go
  pkg/types/alertmanagertypes/marker.go
  pkg/types/alertmanagertypes/receiver.go
  pkg/types/alertmanagertypes/state.go
  pkg/types/dashboard.go
Labels: enhancement

#7105 fix(otelcol): remove the v2 metrics exporter configuration
  deploy/docker-swarm/otel-collector-config.yaml
  deploy/docker/otel-collector-config.yaml
Labels: bug

#6454 fix[FE]: fix the update view button not visible on changes to Not Updating in Logs and Traces List View.
  frontend/src/components/ExplorerCard/ExplorerCard.tsx
  frontend/src/components/ExplorerCard/test/ExplorerCard.test.tsx
  frontend/src/components/ExplorerCard/types.ts
  frontend/src/components/ExplorerCard/utils.ts
  frontend/src/container/ExplorerOptions/ExplorerOptions.tsx
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/types/common/queryBuilder.ts
Labels: in review

#7103 feat(alertmanager): add server implementation for alertmanager
  pkg/alertmanager/server/config.go
  pkg/alertmanager/server/server.go
  pkg/alertmanager/server/server_test.go
  pkg/types/alertmanagertypes/alertmanagertypestest/state.go
  pkg/types/alertmanagertypes/state.go
Labels: enhancement

#7106 fix: fixed widgets not visible after saving in the dashboard detail
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/providers/Dashboard/Dashboard.tsx
  frontend/src/providers/Dashboard/types.ts
Labels: bug

#6701 Feat: back navigation support throughout the app
  frontend/src/components/ExplorerCard/test/ExplorerCard.test.tsx
  frontend/src/components/ResizeTable/DynamicColumnTable.tsx
  frontend/src/components/ResizeTable/types.ts
  frontend/src/container/CreateAlertRule/AlertRuleDocumentationRedirection.test.tsx
  frontend/src/container/CreateAlertRule/AnomalyAlertDocumentationRedirection.test.tsx
  frontend/src/container/FormAlertRules/index.tsx
  frontend/src/container/GridCardLayout/GridCard/FullView/index.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.test.tsx
  frontend/src/container/GridCardLayout/GridCard/WidgetGraphComponent.tsx
  frontend/src/container/GridCardLayout/GridCardLayout.tsx
  frontend/src/container/GridCardLayout/WidgetHeader/index.tsx
  frontend/src/container/ListOfDashboard/DashboardsList.tsx
  frontend/src/container/ListOfDashboard/ImportJSON/index.tsx
  frontend/src/container/LogsExplorerChart/index.tsx
  frontend/src/container/LogsExplorerViews/index.tsx
  frontend/src/container/LogsExplorerViews/tests/LogsExplorerViews.test.tsx
  frontend/src/container/MetricsApplication/Tabs/DBCall.tsx
  frontend/src/container/MetricsApplication/Tabs/External.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/ServiceOverview.tsx
  frontend/src/container/MetricsApplication/Tabs/Overview/TableRenderer/ColumnWithLink.tsx
  frontend/src/container/MetricsApplication/Tabs/util.ts
  frontend/src/container/MetricsApplication/TopOperationsTable.tsx
  frontend/src/container/MetricsApplication/types.ts
  frontend/src/container/MetricsApplication/utils.ts
  frontend/src/container/NewDashboard/DashboardDescription/__tests__/DashboardDescription.test.tsx
  frontend/src/container/NewDashboard/DashboardDescription/index.tsx
  frontend/src/container/NewWidget/LeftContainer/WidgetGraph/WidgetGraphs.tsx
  frontend/src/container/NewWidget/RightContainer/ColumnUnitSelector/__tests__/ColumnSelector.test.tsx
  frontend/src/container/NewWidget/index.tsx
  frontend/src/container/QueryTable/__test__/QueryTable.test.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/index.tsx
  frontend/src/container/TracesTableComponent/TracesTableComponent.tsx
  frontend/src/hooks/useResourceAttribute/ResourceProvider.tsx
  frontend/src/hooks/useResourceAttribute/__tests__/useResourceAttribute.test.tsx
  frontend/src/hooks/useSafeNavigate.ts
  frontend/src/hooks/useUrlQueryData.ts
  frontend/src/pages/AlertDetails/hooks.tsx
  frontend/src/pages/AlertList/index.tsx
  frontend/src/pages/DashboardWidget/index.tsx
  frontend/src/pages/DashboardsListPage/__tests__/DashboardListPage.test.tsx
  frontend/src/pages/EditRules/index.tsx
  frontend/src/pages/LogsExplorer/__tests__/LogsExplorer.test.tsx
  frontend/src/pages/TracesExplorer/Filter/Filter.tsx
  frontend/src/pages/TracesExplorer/__test__/TracesExplorer.test.tsx
  frontend/src/pages/TracesExplorer/index.tsx
  frontend/src/providers/Dashboard/Dashboard.tsx
  frontend/src/providers/QueryBuilder.tsx
  frontend/src/tests/test-utils.tsx
  frontend/src/utils/timeUtils.ts
Labels: enhancement

#7115 fix: fixed selected value getting reset for variables and refetch not going
  frontend/src/container/NewDashboard/DashboardVariablesSelection/VariableItem.tsx
Labels: bug

#7118 Revert "fix(otelcol): remove the v2 metrics exporter configuration (#… …7105)"
  deploy/docker-swarm/docker-compose.ha.yaml
  deploy/docker-swarm/docker-compose.yaml
  deploy/docker-swarm/otel-collector-config.yaml
  deploy/docker/docker-compose.ha.yaml
  deploy/docker/docker-compose.yaml
  deploy/docker/otel-collector-config.yaml
Labels: bug

#7123 fix(alertmanager): fix a flaky test
  go.mod
  pkg/types/alertmanagertypes/channel_test.go
Labels: bug

#7129 chore: added mq celery analytics
  frontend/src/components/CeleryTask/CeleryTaskDetail/CeleryTaskDetail.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskBar.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskGraph.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskGraphGrid.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskLatencyGraph.tsx
  frontend/src/components/CeleryTask/CeleryTaskGraph/CeleryTaskStateGraphConfig.tsx
  frontend/src/container/GridCardLayout/GridCard/index.tsx
  frontend/src/container/GridCardLayout/GridCard/types.ts
  frontend/src/pages/Celery/CeleryTask/CeleryTask.tsx
Labels: chore

#7133 fix: analytics middleware fixed
  ee/query-service/app/server.go
  pkg/http/middleware/analytics.go
  pkg/query-service/app/server.go
Labels: bug

#7127 chore: added kakfa analytics
  frontend/src/pages/MessagingQueues/MQDetails/DropRateView/DropRateView.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MQTables/MQTables.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MessagingQueueOverview.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MetricPage/MetricColumnGraphs.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MetricPage/MetricPage.tsx
  frontend/src/pages/MessagingQueues/MQDetails/MetricPage/MetricPageGraph.tsx
Labels: chore

#7114 fix: fixed paths to unblock lint check failing locally
  frontend/src/api/integration/aws/index.ts
  frontend/src/container/CloudIntegrationPage/HeroSection/components/AccountActions.tsx
  frontend/src/container/CloudIntegrationPage/HeroSection/components/AccountSettingsModal.tsx
  frontend/src/container/CloudIntegrationPage/HeroSection/components/CloudAccountSetupModal.tsx
  frontend/src/container/CloudIntegrationPage/HeroSection/components/RegionForm.tsx
  frontend/src/container/CloudIntegrationPage/HeroSection/components/RegionSelector.tsx
  frontend/src/container/CloudIntegrationPage/ServicesSection/ConfigureServiceModal.tsx
  frontend/src/container/CloudIntegrationPage/ServicesSection/ServiceDetails.tsx
  frontend/src/container/CloudIntegrationPage/ServicesSection/ServicesList.tsx
  frontend/src/container/CloudIntegrationPage/ServicesSection/ServicesTabs.tsx
  frontend/src/hooks/integration/aws/useAccountSettingsModal.ts
  frontend/src/hooks/integration/aws/useAccountStatus.ts
  frontend/src/hooks/integration/aws/useAwsAccounts.ts
  frontend/src/hooks/integration/aws/useConnectionParams.ts
  frontend/src/hooks/integration/aws/useGenerateConnectionUrl.ts
  frontend/src/hooks/integration/aws/useGetAccountServices.ts
  frontend/src/hooks/integration/aws/useIntegrationModal.ts
  frontend/src/hooks/integration/aws/useRegionSelection.ts
  frontend/src/hooks/integration/aws/useServiceDetails.ts
  frontend/src/hooks/integration/aws/useUpdateAccountConfig.ts
  frontend/src/hooks/integration/aws/useUpdateServiceConfig.ts
Labels: bug

#7110 fix: refactor auth package
  ee/http/middleware/pat.go
  ee/query-service/app/api/api.go
  ee/query-service/app/api/auth.go
  ee/query-service/app/api/cloudIntegrations.go
  ee/query-service/app/api/pat.go
  ee/query-service/app/server.go
  ee/query-service/auth/auth.go
  ee/query-service/dao/interface.go
  ee/query-service/dao/sqlite/auth.go
  ee/query-service/license/manager.go
  ee/query-service/main.go
  go.mod
  go.sum
  pkg/http/middleware/analytics.go
  pkg/http/middleware/auth.go
  pkg/http/middleware/logging.go
  pkg/query-service/app/auth.go
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/explorer/db.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/logparsingpipeline/controller.go
  pkg/query-service/app/logparsingpipeline/db.go
  pkg/query-service/app/server.go
  pkg/query-service/auth/auth.go
  pkg/query-service/auth/jwt.go
  pkg/query-service/auth/rbac.go
  pkg/query-service/main.go
  pkg/query-service/rules/db.go
  pkg/query-service/tests/integration/filter_suggestions_test.go
  pkg/query-service/tests/integration/logparsingpipeline_test.go
  pkg/query-service/tests/integration/signoz_cloud_integrations_test.go
  pkg/query-service/tests/integration/signoz_integrations_test.go
  pkg/query-service/tests/integration/test_utils.go
  pkg/types/authtypes/jwt.go
  pkg/types/authtypes/jwt_test.go
  pkg/types/authtypes/uuid.go
Labels: bug

#7137 feat(sqlstorehook): add sqlstore logging hook
  pkg/signoz/provider.go
  pkg/sqlstore/bun.go
  pkg/sqlstore/postgressqlstore/provider.go
  pkg/sqlstore/sqlitesqlstore/provider.go
  pkg/sqlstore/sqlstore.go
  pkg/sqlstore/sqlstorehook/logging.go
  pkg/types/alertmanagertypes/channel_test.go
Labels: enhancement, docs not required

#7138 fix: signoz shouldn't panic with postgres provider
  ee/query-service/app/api/cloudIntegrations.go
  ee/query-service/app/server.go
  ee/query-service/auth/auth.go
  ee/query-service/dao/factory.go
  ee/query-service/dao/sqlite/auth.go
  ee/query-service/dao/sqlite/modelDao.go
  ee/query-service/license/db.go
  ee/query-service/license/manager.go
  pkg/query-service/app/cloudintegrations/controller.go
  pkg/query-service/app/cloudintegrations/controller_test.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/integrations/controller.go
  pkg/query-service/app/integrations/test_utils.go
  pkg/query-service/app/opamp/config_provider_test.go
  pkg/query-service/app/server.go
  pkg/query-service/auth/auth.go
  pkg/query-service/auth/rbac.go
  pkg/query-service/dao/factory.go
  pkg/query-service/dao/interface.go
  pkg/query-service/dao/sqlite/connection.go
  pkg/query-service/dao/sqlite/rbac.go
  pkg/query-service/tests/integration/filter_suggestions_test.go
  pkg/query-service/tests/integration/logparsingpipeline_test.go
  pkg/query-service/tests/integration/signoz_cloud_integrations_test.go
  pkg/query-service/tests/integration/signoz_integrations_test.go
  pkg/query-service/tests/integration/test_utils.go
  pkg/query-service/utils/testutils.go
  pkg/signoz/provider.go
  pkg/types/license.go
  pkg/types/organization.go
Labels: bug

#7120 fix: prefer local storage list options over url query options and handle an edge case
  frontend/src/pages/LogsExplorer/index.tsx
Labels: bug

#7136 feat(alertmanager): add service for alertmanager
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanagerstore/sqlalertmanagerstore/config.go
  pkg/alertmanager/alertmanagerstore/sqlalertmanagerstore/state.go
  pkg/alertmanager/api.go
  pkg/alertmanager/config.go
  pkg/alertmanager/internalalertmanager/provider.go
  pkg/alertmanager/server/server.go
  pkg/alertmanager/service.go
  pkg/errors/code.go
  pkg/types/alertmanagertypes/alertmanagertypestest/state.go
  pkg/types/alertmanagertypes/channel.go
  pkg/types/alertmanagertypes/config.go
  pkg/types/alertmanagertypes/state.go
Labels: enhancement

#7088 feat(summary view): added tree map metric details apis | 7087
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metricsexplorer/parser.go
  pkg/query-service/app/metricsexplorer/summary.go
  pkg/query-service/app/summary.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/metrics_explorer/summary.go
Labels: enhancement

#7148 fix: org domain
  pkg/signoz/provider.go
  pkg/sqlmigration/012_modify_org_domain.go
Labels: bug

#7150 chore: reset filters while going from hosts list to host details
  frontend/src/components/HostMetricsDetail/HostMetricTraces/HostMetricTraces.tsx
  frontend/src/components/HostMetricsDetail/HostMetricsLogs/HostMetricLogsDetailedView.tsx
  frontend/src/container/InfraMonitoringHosts/InfraMonitoring.styles.scss
Labels: chore

#7161 feat(summary view): added summary view endpoints
  ee/query-service/app/server.go
  go.mod
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metricsexplorer/parser.go
  pkg/query-service/app/metricsexplorer/summary.go
  pkg/query-service/app/server.go
  pkg/query-service/app/summary.go
  pkg/query-service/constants/constants.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/metrics_explorer/summary.go
  pkg/query-service/utils/filter_conditions.go
  pkg/telemetrystore/telemetrystorehook/settings.go
Labels: enhancement

#7156 feat(legacyalertmanager): add legacyalertmanager
  pkg/alertmanager/alertmanager.go
  pkg/alertmanager/alertmanagerbatcher/batcher.go
  pkg/alertmanager/alertmanagerbatcher/config.go
  pkg/alertmanager/alertmanagerserver/config.go
  pkg/alertmanager/alertmanagerserver/server.go
  pkg/alertmanager/alertmanagerserver/server_test.go
  pkg/alertmanager/alertmanagerstore/sqlalertmanagerstore/config.go
  pkg/alertmanager/api.go
  pkg/alertmanager/config.go
  pkg/alertmanager/internalalertmanager/provider.go
  pkg/alertmanager/legacyalertmanager/provider.go
  pkg/alertmanager/service.go
  pkg/alertmanager/signozalertmanager/provider.go
  pkg/types/alertmanagertypes/alert.go
  pkg/types/alertmanagertypes/config.go
Labels: enhancement

#7144 feat: enable ms teams channel for all users
  frontend/src/components/Upgrade/UpgradePrompt.tsx
  frontend/src/container/AllAlertChannels/__tests__/CreateAlertChannel.test.tsx
  frontend/src/container/AllAlertChannels/__tests__/CreateAlertChannelNormalUser.test.tsx
  frontend/src/container/FormAlertChannels/index.tsx
  frontend/src/container/TopNav/DateTimeSelectionV2/config.ts
Labels: enhancement, docs not required

#7112 feat: show a alert if api takes more than 5 secs
  frontend/src/api/index.ts
  frontend/src/constants/events.ts
  frontend/src/constants/localStorage.ts
  frontend/src/container/AppLayout/AppLayout.styles.scss
  frontend/src/container/AppLayout/index.tsx
Labels: enhancement, docs not required

#7181 fix: fix the issue of service to logs/traces explorer caused by similar start and end timestamps
  frontend/src/container/MetricsApplication/Tabs/Overview.tsx
  frontend/src/container/MetricsApplication/Tabs/util.ts
  frontend/src/utils/timeUtils.ts
Labels: bug

#7174 feat(summary): added alerts and basic query updates
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metricsexplorer/summary.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/metrics_explorer/summary.go
  pkg/query-service/rules/manager.go
Labels: enhancement

#7190 chore: update restart policy of Docker containers
  deploy/docker-swarm/docker-compose.ha.yaml
  deploy/docker-swarm/docker-compose.yaml
  deploy/docker/docker-compose.ha.yaml
  deploy/docker/docker-compose.testing.yaml
  deploy/docker/docker-compose.yaml
  deploy/docker/generator/hotrod/docker-compose.yaml
  deploy/docker/generator/infra/docker-compose.yaml
  pkg/query-service/README.md
Labels: chore

#7193 feat(explorer): added related metrics
  pkg/query-service/app/clickhouseReader/reader.go
  pkg/query-service/app/dashboards/model.go
  pkg/query-service/app/http_handler.go
  pkg/query-service/app/metricsexplorer/parser.go
  pkg/query-service/app/metricsexplorer/summary.go
  pkg/query-service/app/summary.go
  pkg/query-service/interfaces/interface.go
  pkg/query-service/model/metrics_explorer/summary.go
  pkg/query-service/model/v3/v3.go
  pkg/query-service/rules/manager.go
  pkg/query-service/utils/format.go
Labels: enhancement
